### ISSUE TITLE
Additional Goto Commands

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-vscode-fsharp#100]
The full goto set we should aim for is -
- Go to Signature
- Go to Definition
- Go to Declaration
- Go to Implementation
- Go to Type of Symbol
- Go to Next Usage of Symbol

(and peeks too)

**Comment by Krzysztof-Cieslak** [comment]
I think we need additional API for it, it may be good to create issue on VSCode repo about it.

**Comment by Krzysztof-Cieslak** [comment]
Closing due to lack of needed APIs on the Code side.
