### ISSUE TITLE
ProjectCrackerTool.exe not installed

### ISSUE THREAD

**Issue by thelazydogsback** [ionide/ionide-vscode-fsharp#1000]
On new install of ionide-fsharp, getting same as #873. (Verified that I have the ProjectCracker.DLL but not the ProjectCrackerTool.exe.)
I am still getting this on the newest 3.31.0.

thanks

Status: failed to load
Error:ProjectCracker exe not found at: C:\Users\Michael\.vscode\extensions\ionide.ionide-fsharp-3.31.0\bin\FSharp.Compiler.Service.ProjectCrackerTool.exe it must be next to the ProjectCracker dll.

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

**Comment by thelazydogsback** [comment]
Verified still have the issue on a separate install on a different PC.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed by 3.32.0
