### ISSUE TITLE
Unable To Open Project - D:/Programowanie

### ISSUE THREAD

**Issue by paytonrules** [ionide/ionide-vscode-fsharp#1002]
On opening a folder with two fsharp projects in it ionide detects both of them, but fails to load with the error below: 

<img width="240" alt="nerdstrengthtests_assemblyinfo_fs_ _nerdstrengthunity" src="https://user-images.githubusercontent.com/21752/52123789-c3dc1200-25ec-11e9-9442-3ebe7d334bfa.png">

It looks like a developer path is hard coded somewhere? I'm on MacOS so I don't even have a d drive, let alone that path.

**Comment by paytonrules** [comment]
I should add - the project builds just fine at the command line with `dotnet build`.

**Comment by Krzysztof-Cieslak** [comment]
Huh, it doesn’t look like - https://github.com/ionide/ionide-vscode-fsharp/search?utf8=✓&q=programowanie&type=

**Comment by Krzysztof-Cieslak** [comment]
Can you open F# solution explorer (F# icon in the activity bar), right click the failing project and then check project status?

**Comment by paytonrules** [comment]
I can't - not for lack of trying. I just get that same error again: "Unable to open 'Project NerdStrengthTests status': D:/Programowanie/ionide/src/Components/SolutionExplorer.fs." 

I'm kinda shocked the unique directory path doesn't immediately make a contributor say "oh no that's my machine!"

**Comment by enriqueMartinezInter** [comment]
Same thing happening to me
![image](https://user-images.githubusercontent.com/12499680/52314450-50cdf500-2978-11e9-825b-2660fd7998f1.png)

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak `Programowanie` seems to a polish word meaning `programming` (but you know better than me ^^).

Perhaps, one of the dependencies of Ionide has been compiled on a Polish computer and have `Programowanie` in hard in the code or the path resolution functions.

**Comment by Krzysztof-Cieslak** [comment]
> Perhaps, one of the dependencies of Ionide has been compiled on a Polish computer and have Programowanie in hard in the code or the path resolution functions.

Yeah, sure. But it has nothing to do with the bug happening here - every unhandled exception will have some path displayed. And yeah probably our webpack config has some small issue (it should replace those paths with relative)... but it’s not connected to behavior in any way

**Comment by MangelMaxime** [comment]
Ah yes, I see what you mean.

And you are right #1008 will fix this issue. I didn't read correctly the thread and didn't understand that the error was coming when trying to show the project status...

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #1008

**Comment by paytonrules** [comment]
Can confirm, this problem went away. I'm now struggling with this issue: https://github.com/fsharp/FsAutoComplete/issues/326.  So progress of a sort.
