### ISSUE TITLE
fsi not found

### ISSUE THREAD

**Issue by xDelph** [ionide/ionide-vscode-fsharp#1006]
hello,
i'm on ubuntu 18.10, fsharpi work in my terminal
but each time i want to run code in vscode, i get
`Failed to spawn FSI, please ensure it's in PATH`

**Comment by MangelMaxime** [comment]
Hello @xDelph , in your VSCode settings you can set the path to `fsharpi` using `FSharp.fsiFilePath` setting.

**Comment by xDelph** [comment]
just find the way
and i have code runner that was also interferre with ionic that not help
thanks for helping anyway
