### ISSUE TITLE
Alt + Enter *always* moves to the next line

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#101]
Great to see that Alt + Enter now automatically moves to the next line. However (and this is only if you want to keep with VS behaviour), this should only happen when the user hasn't highlighted text - if they have, the caret should remain where it was (along with the highlighting).

In other words - keep the old behaviour for when there's something selected, otherwise use new "move to next line" behaviour :-)

**Comment by Krzysztof-Cieslak** [comment]
Is there any value (other than VS compatibility) to stay at same line after sending selection to FSI?

**Comment by Krzysztof-Cieslak** [comment]
(I mean, it's not bug, I've implemented it this way on purpose. Might be wrong tho)

**Comment by isaacabraham** [comment]
Yes - I often want to repeatedly execute the same block of code. With it automatically moving to the next line, I have to now move back to the start of the block, highlight the selection again and then send to FSI.

**Comment by Krzysztof-Cieslak** [comment]
Fair enough, will change it.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.2.4`
