### ISSUE TITLE
Lint Issue: 'function' keyword clause indentation

### ISSUE THREAD

**Issue by pimbrouwers** [ionide/ionide-vscode-fsharp#1014]
Despite whatever indentation or formatting you apply. The linter constantly marks function clause alignment as incorrect. Citing "Lint: Match clauses should be indented one level from 'function' keyword."

![image](https://user-images.githubusercontent.com/4595453/52481492-b2f74780-2b7c-11e9-9e34-7b4d758420d6.png)

**Comment by Krzysztof-Cieslak** [comment]
Discussed in referenced issue.
