### ISSUE TITLE
Several Linter issues

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#1015]
I've noticed several Linter issues:

### Constants

```fsharp
let SOME_CONSTANT_FOR_ENV_VAR = "ENV_VAR"
```

Lint: Consider changing SOME_CONSTANT_FOR_ENV_VAR to remove any underscores.

### String.Split Function

```fsharp
someVar.Split([| ','; ' ' |], StringSplitOptions.RemoveEmptyEntries)
```

![image](https://user-images.githubusercontent.com/4580714/52531826-89245900-2d13-11e9-8c5a-2f46ea757cf8.png)

The linter gets fooled by the `','`. Anything which is inside double quotes or inside single quotes is a string or character definition and probably shouldn't trigger the Linter.

### Unions

Not sure what it doesn't like here, but this is pretty common syntax in F# I thought:

![image](https://user-images.githubusercontent.com/4580714/52531849-eddfb380-2d13-11e9-82a5-ca849b88ac76.png)

### Default Property Initialisers

When I set properties to default values when initialising an object the linter mistakes it for a tuple:

```fsharp
let forwardedHeadersOptions =
            ForwardedHeadersOptions(
                ForwardedHeaders = ForwardedHeaders.XForwardedFor,
                ForwardLimit = Nullable<int>(1))
```

![image](https://user-images.githubusercontent.com/4580714/52531902-73fbfa00-2d14-11e9-835f-e300b3867952.png)

### function pattern matching

EDIT: Same as #1014 

The linter seems to confuse the pattern matching syntax with a function declaration:

![image](https://user-images.githubusercontent.com/4580714/52531916-a4dc2f00-2d14-11e9-9c7c-55cc551aa235.png)

### Comments on class members

![image](https://user-images.githubusercontent.com/4580714/52532836-da881480-2d22-11e9-81f5-3396775f82a0.png)

Otherwise works great! Got a solution which is growing in size and it's working nice!

**Comment by MangelMaxime** [comment]
I think, you should open the issue on [FSharpLint](https://github.com/fsprojects/FSharpLint) because Ionide is just a client of the tool.

Note that some of the issues have already been reported and fixed in the linter repo.
Example: https://github.com/fsprojects/FSharpLint/issues/293

**Comment by dustinmoris** [comment]
Ok cool, thanks, didn't know about that but I'll move the issue over now!
