### ISSUE TITLE
Intellisense stops working

### ISSUE THREAD

**Issue by halcwb** [ionide/ionide-vscode-fsharp#1016]
This problem, unfortunately, is old and I see this for years on a row. Intellisense stops working when an syntactical error is encountered and after correction of the error saving the file, the error keeps popping up:

I would be really, really, really happy if this problem could be resolved.

![ionide](https://user-images.githubusercontent.com/683631/52626353-48fbdc80-2eb3-11e9-87a8-b2a2b379865b.png)

Trying to do this with an include to avoid relative paths doesn't work either, have to get back to VS ;-(

![ionide include](https://user-images.githubusercontent.com/683631/52627075-e60b4500-2eb4-11e9-9b4b-9a92d86fcd72.png)

**Comment by inosik** [comment]
The only reliable workaround I found for this error is using the `net462` framework. For some reason referencing netstandard works differently in VS (`#r "netstandard"`) and Ionide (`#r "Facades/netstandard"`) and generating a load script for `net462` is the only way for me to get script files (FAKE scripts) to work with both.

**Comment by MangelMaxime** [comment]
`#r "Facades/netstandard"` is if you are using `mono` because they didn't put the "facades" in the same place as `.Net` framework which made them accessible from `#r "netstandard"`

So in general, it's better to use both of them so people on Windows or *nix can use the script.

**Comment by halcwb** [comment]
So, I need to do `paket generate-load-scripts --framework net462` and use those generated load scripts to get intellisense working?

**Comment by inosik** [comment]
That's what I do for my FAKE 5 scripts, because FAKE itself generates a load script for the latest known framework, which is `net472` at the moment. The generated script includes some `netstandard` compatible assemblies, which I think triggers the error from your screenshot.

You can also try to add this to your script, as @MangelMaxime suggested:

``` fsharp
#r "Facades/netstandard"
#r "netstandard"
```

I don't remember why I decided against this, though.

**Comment by halcwb** [comment]
I tried generating the load script for the net462 framework, but then when I want to load the reference script, the FSI crashes ;-(.
I am quite unhappy with how poorly script files and the FSI are supported, as this is a major selling point for using F#.

**Comment by Krzysztof-Cieslak** [comment]
Whole scripting experience should be better now, with all changes @baronfel done in FSAC.
