### ISSUE TITLE
Intellisense searches are now case-sensitive

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#102]
Given the following code: -

```fsharp
type Thing = { Name : string }
let x = { Name = "isaac" }
```

If you hit "x." you get automatic intellisense - great: -

![ionidebug1](https://cloud.githubusercontent.com/assets/1781813/17035084/da7949e6-4f85-11e6-9f85-c8efcd44459b.png)

However, if I then hit "n" to go to Name, the intellisense goes a bit weird: -

![ionidebug2](https://cloud.githubusercontent.com/assets/1781813/17035096/e76832ac-4f85-11e6-92d7-ba6cff3c45eb.png)

It also matches now case sensitive, so even if I type "name" in full, it goes to "namespace".

**Comment by Krzysztof-Cieslak** [comment]
Hopefully fixed in `2.2.4`. This keyword completion gives me headache ;)
