### ISSUE TITLE
"Project Parsing Failed" error repeats indefinitely

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1022]
I'm upgrading an old net452 project up to netstandard. Whilst doing this, Ionide repeatedly shows, hides and then shows again the "Project Parsing Failed" pop-up - even after closing the pop-up dialog. If you ignore it, it continually hides and shows.

**Comment by psowinski** [comment]
![bug](https://user-images.githubusercontent.com/8286574/52995882-2e2de880-341c-11e9-8383-fbe48868528c.jpg)
I have the same problem

**Comment by Krzysztof-Cieslak** [comment]
I'll close that in favour of #1077
