### ISSUE TITLE
Type Provider issue when using netcore FSAC

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1026]
Using the netcore version of FSAC doesn't appear to work with type providers. Using it with e.g. JSON TP gives this error:

![image](https://user-images.githubusercontent.com/1781813/52953415-b2825c00-3387-11e9-9eb0-693acb14614a.png)

I've tried adding a reference to this System.Private.CoreLib as a #r but no change. Any ideas?

**Comment by Krzysztof-Cieslak** [comment]
Cc: @enricosada.

Also CC: @MangelMaxime - it seems that formating in tooltip in above screenshot is wrong. We probably should create separate issue for that

**Comment by MangelMaxime** [comment]
If an issue is opened with a reproduction code I can take a look at fixing the tooltip.

**Comment by enricosada** [comment]
tracking this issue in https://github.com/fsharp/FsAutoComplete/issues/348

**Comment by isaacabraham** [comment]
@Krzysztof-Cieslak for the moment I'd like to suggest removing the pop-ups to move over to the netcore FSAC - it's actually not necessarily good advice, since it doesn't work with type providers. Or at the very least it should be able to stop the alert appearing - it currently shows *every single time* that you start Code.

**Comment by baronfel** [comment]
I think that makes a lot of sense. I think we could easily make it so if there was a user-set value for the fsacRuntime then we'd just ignore the suggestion overall.

**Comment by isaacabraham** [comment]
@baronfel have just updated to latest ionide but the messages are still showing every time we start.

**Comment by isaacabraham** [comment]
@baronfel @Krzysztof-Cieslak do you know of any reason why this might not be working? Do I have to first explicitly move to netcore and then back to net before it takes effect or something?

**Comment by drk-mtr** [comment]
I had issues with this too recently when using the SQLProvider type provider. I read a comment that suggested the wrong version of FSharp.Data or the compiler might be getting used, and that wiping the `.vscode` folder from the your windows user folder, and the `Code` directory from `AppData` might be a solution - this seemed to work for me but I also cleaned my paket cache at the same time so I can't be certain.

Great to see the prompts to switch to netcore each time are being removed! Prompts generally infuriate me, one of the main reason I switched to vscode is that some other apps can be quite "noisy" in terms of the development experience, so the less popups the better in my view.

**Comment by drk-mtr** [comment]
Also just to mention that for something like this that can be reproduced with just a few lines of code, it's probably worth including all lines of code, since it could make a difference whether you are doing:

```
r# "./packages"
#I "PackageFolder/PackageName.dll"
```

Compared to:

`#r ./packages/PackageFolder/PackageName.dll"`

**Comment by isaacabraham** [comment]
Is there a roadmap for this issue? Current status is that AFAICS out of the box Ionide won't work with type providers.

**Comment by isaacabraham** [comment]
This seems to work now, also on the netcore version of FSAC :-) Closing.

**Comment by humhei** [comment]
Just a note,
For custom type provider, `baseType = None` will alse trigger this issue,
Replace it to `Some typeof<obj>`

```fsharp
/// this is will trigger this issue
ProvidedTypeDefinition(baseType = None) 

/// this is will  not trigger this issue
ProvidedTypeDefinition(baseType = Some typeof<obj>) 
```
