### ISSUE TITLE
let (<<.) a = 1 breaks syntax highlighting

### ISSUE THREAD

**Issue by vivainio** [ionide/ionide-vscode-fsharp#1027]
Try adding this to your .fs file:

```
let (<<.) a = 1
```

Observe that syntax highlight gets broken.

![image](https://user-images.githubusercontent.com/557579/52967875-36523d80-33b4-11e9-9c20-e18b4baa3344.png)

**Comment by MangelMaxime** [comment]
Can you please move the issue to [ionide-fsgrammar](https://github.com/ionide/ionide-fsgrammar)?

**Comment by vivainio** [comment]
Filed new bug at https://github.com/ionide/ionide-fsgrammar/issues/117
