### ISSUE TITLE
Where are the log files on linux?

### ISSUE THREAD

**Issue by ffoqsi** [ionide/ionide-vscode-fsharp#1034]
When I issue command "F#: Get Ionied Logs", I get an error:

    no such file or directory, open
    'tmp/ionied/FSAC_logs/20190220-115521.log'

Actually there is no tmp/ionied folder. Where can I find the logs?

**Comment by MangelMaxime** [comment]
Hello @ffoqsi , this is strange I think the path is missing a leading `/`.

Can you try to check for `/tmp/ionied/FSAC_logs/20190220-115521.log`?

**Comment by ffoqsi** [comment]
there is absolutely nothing below /tmp like ionide.

**Comment by MangelMaxime** [comment]
I don't have access to a Linux computer ATM. I will try to take a look when home.

**Comment by MangelMaxime** [comment]
I confirm there is a bug on Linux. The file/folder isn't created anymore.

**Comment by Krzysztof-Cieslak** [comment]
We've changed the logging strategy with move to LSP

**Comment by LiteracyFanatic** [comment]
This is still broken on linux for me. Note that the path in the error does include the leading `/`.

```
ENOENT: no such file or directory, open '/tmp/ionide/FSAC_logs/20200401-200905.log'
```

Furthermore, running "F#: Get Ionide Logs" results in the creation of an empty folder in my home directory: `~/tmp/ionide/FSAC_logs/`. 

> We've changed the logging strategy with move to LSP

Could you elaborate on what this means?

**Comment by Krzysztof-Cieslak** [comment]
You can get logs in `F#` tab in output panel in VSCode.
