### ISSUE TITLE
Upgrade to Fable 2

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1036]
@Krzysztof-Cieslak Would you be ok, if I upgrade the repo to Fable 2.1 ?

In theory it will:
- Decrease the bundle size
- Improve the performance
- Be up to date again with latest Fable version
- Easier to start as `dotnet fable` is now replace with `webpack`

**Comment by Krzysztof-Cieslak** [comment]
I’d love to see that

**Comment by MangelMaxime** [comment]
Ok, I will give it a try. :)

**Comment by MangelMaxime** [comment]
Small update.

I got the project to compile and Ionide works.

Strange behavior/bugs:

- [ ] Intellisense, errors checking start when you open a `*.fs` files. I think it should start if there are some visible editors opened.
- [ ] Code generation is broken:
    - [ ] Record stub generation
    - [ ] Interface stub generation
    - [ ] Union case generation

I will use this issue to track the different bugs/strange behaviour I see. If am stuck, I will open a PR so others can take a look at it too.

**Comment by MangelMaxime** [comment]
I am waiting for Fable 2.2 to be released.

So I can do all at once and not redo the same work again :)
