### ISSUE TITLE
launchSetting.json being ignored. How to change listen port?

### ISSUE THREAD

**Issue by mniak** [ionide/ionide-vscode-fsharp#1038]
When I try to debug my project, it starts running in ports `5000` and `5001`.
When a request comes, it tries to upgrade to an HTTPS connection.

When I run the project using `dotnet run`, it only listens in port `5000`, as I have it configured in the file `launchSettings.json`. But the **Ionide** plugin seems to ignore the settings in this file.

How can I change the listen port when running?

**Comment by enricosada** [comment]
For custom arguments, you can create a `launchSettings.json` and use `Debug` panel to run it

![image](https://user-images.githubusercontent.com/147243/56097536-e4cab880-5ef5-11e9-844b-0d7168ff5484.png)

the debug command on the project, will run the projects without args
