### ISSUE TITLE
Can't always load project properly

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#104]
On a few solutions, I have situations where the project file doesn't seem to load properly - it's as though any references to third-party assemblies don't show up.

I now do have a repro of this - https://github.com/fsprojects/AzureStorageTypeProvider. If you load the solution and do a fake build, it'll build successfully (you'll need the Azure Storage SDK on your machine for the emulator though - sorry!). But when you open any files in the Test project, you'll see that all the references to e.g. WindowsAzure.Storage have red squigglies because the namespace isn't defined.

But the main FSharp.Azure.StorageTypeProvider project works fine.

**Comment by Krzysztof-Cieslak** [comment]
Any reproduction for which I don't need to install any additional requirements?

**Comment by isaacabraham** [comment]
If I find another project I'll let you know. Sorry.
________________________________

**Comment by Krzysztof-Cieslak** [comment]
@isaacabraham: Can you try latest version? We've updated FCS, new version apparently is bit better at handling `fsproj` files

**Comment by isaacabraham** [comment]
Works!!

**Comment by Krzysztof-Cieslak** [comment]
![](http://i.giphy.com/11sBLVxNs7v6WA.gif)
