### ISSUE TITLE
Tabs - 2 spaces

### ISSUE THREAD

**Issue by et1975** [ionide/ionide-vscode-fsharp#1040]
Not sure if it's on Ionide, but my VSCode preferences say 4 spaces, yet I always get 2.

**Comment by MangelMaxime** [comment]
VSCode is detecting the indentation used in the file.

Even when setting it to 4 or 2 spaces it sometimes chooses to put something else in it based on what if detects. This is what I understand from my experience of using VSCode even in others languages.

Perhaps, you can try to disable this behavior with the settings "Editor: Detect indentation"

**Comment by et1975** [comment]
Thanks, that was it.
