### ISSUE TITLE
Key-bindings for multi-cursor get reassigned to moving .fs files in project

### ISSUE THREAD

**Issue by pkese** [ionide/ionide-vscode-fsharp#1043]
When I edit python files [Ctrl][Shift][Up] / [Ctrl][Shift][Down] are assigned to creating multiple cursors.

When I open .fs files, the same key bindings get reassigned to moving .fs files up and down inside the project. It would be nice to find another solution -- a useful multi-cursor feature gets replaced with a 'mess-up-my-project' shortcut.

This is on Ubuntu

**Comment by pkese** [comment]
I've noticed #805 mentioning [Ctrl][Alt][Up]/[Down] but on my computer this is assigned to switching desktop workspaces.

**Comment by pkese** [comment]
Another thing: 

The [Ctrl][Shift][Up] / [Ctrl][Shift][Down] stay assigned to moving files up/down even if Solution Explorer pane is disabled altogether (as in settings `FSharp.enableTreeView <- false`)

**Comment by MangelMaxime** [comment]
> The [Ctrl][Shift][Up] / [Ctrl][Shift][Down] stay assigned to moving files up/down even if Solution Explorer pane is disabled altogether (as in settings FSharp.enableTreeView <- false)

This is "normal" because the shortcut is not registered on the solution explorer but if the editor is focused and if it's an F# file. [Source](https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L1036-L1040)

**Comment by pkese** [comment]
Thanks @MangelMaxime 

Using your suggestion I've changed the keyboard shortcut condition to
```javascript 
when: false && editorFocus  && editorLangId == 'fsharp'
```
...and this perfectly fixed my problem.

But it would be nice if we had a more generic solution or at least not steal universal keybindings.

I think moving files up and down inside in the solution is a rare-enough necessity that we could just change the keybinding to something like [Ctrl][Alt][Del][Shift][CapsLock][F7][Up] and we'd end up with less issue reports than in the current situation :-) (just joking of course... well partially at least)

**Comment by Krzysztof-Cieslak** [comment]
I agree that moving files up/down is not really an operation that justifies overriding some default editor shortcuts. And yes, in general, project modification has its problems ;-)

I removed default keybindings with 62377eb42a4296e8c75382731361c8bfa4de998e.
