### ISSUE TITLE
UX annoyance with moving .fs files inside the project

### ISSUE THREAD

**Issue by pkese** [ionide/ionide-vscode-fsharp#1044]
When I wish to choose a file inside the F# project inspector my workflow is:
1) visually search for the file I wish to choose
2) move the mouse to that file and click
3) _(just before clicking, the Up/Down arrows pop up underneath the mouse cursor)_
4) instead of opening file, the file gets moved up or down inside the project and the project gets messed up
5) Y^$@#* curse

Am I the only one who acquired this particular workflow?

Could we think in direction of:
1) the up/down arrows be always visible
2) have an option to remove the arrows altogether (right menu click is there already; generally the moving file up/down inside the project is in practical workflow much less used than the exposure it gets inside the IDE)
3) drag&drop

**Comment by pkese** [comment]
Another possible (partial) solution:

4) show the up & down arrows only on selected file (but not on hovering unselected files).

**Comment by vbfox** [comment]
1. Can't do (vscode feature)
2. Doable
3. There is an old issue on vscode for that for now it's impossible
4. Not doable directly but we might be able to trick it (set a value in the context with the file path and filter on that) need to be tried

**Comment by MangelMaxime** [comment]
About point 4, it's not really user-friendly either. Because if you want to re-order several files you need to click on each of them. Instead of hovering them.

Waiting for a solution from Ionide, perhaps you can take the habit of clicking on the text on the row Instead of the "empty" space where the arrows show up.

**Comment by pkese** [comment]
I would think that any of the 4 points are more user friendly than the current situation (but that is merely my personal opinion).  
I wonder how often is it, that one would wish to reorder that many files at the same time...

And yes, I am indeed training very hard to change that nasty habit ;-)  
Cheers, and thanks

**Comment by Krzysztof-Cieslak** [comment]
I've thought about it, and I think I'm happy with the current situation - it's consistent with general VSCode behaviour. We probably could try really hard and hack something like a suggestion 4... but that's not really how VSCode works in terms of UX. So, I'm closing the issue. Thanks for the suggestion, anyway!

**Comment by pkese** [comment]
@Krzysztof-Cieslak Sure. Your point is understandable. Still, thanks for giving it a thought.
