### ISSUE TITLE
Projects aren't reloaded when FSAC is restarted

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1046]
This is kind-of a follow-on from #832, in that #832 restarted the FSAC process, but we don't re-input the workspace or project load commands necessary to ensure the currently-loaded files are all parsed.  So the requirement here would be that

* when FSAC is restarted
* the current workspace/project selections are reloaded into the new FSAC instance.

I thought that this could be easily implemented through use of an event in the LanguageService module, and this event would be triggered once each time the FSAC instance was started.
Then, in fsharp.fs, the portion of the initial ionide startup that is related to workspace peek, workspace selection, and project loads would be extracted out into a separate function that could be invoked on the event handler.  I tried this locally but am not sure that this is a good way/the best way to get to the desired result.

Some components in the startup don't directly need to be invoked each time FSAC runs, so they could be left on the current initialization pathway. This would be things like tooltips, quick fixes, etc.  They just send requests to FSAC, so as long as we are able to repopulate FSAC with parsed projects on a reload, they should continue to 'just work'.

**Comment by Krzysztof-Cieslak** [comment]
Let's not do that right now - things may change too much with incoming LSP version of FSAC
