### ISSUE TITLE
FSAC does not work with .Net Core 3.0 preview3 only, without .NET Core runtime 2.0 installed

### ISSUE THREAD

**Issue by boyedarat** [ionide/ionide-vscode-fsharp#1057]
I have the latest .Net Core 3.0 preview3 installed:

> dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   3.0.100-preview3-010431
>  Commit:    d72abce213
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17763
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\
> 
> Host (useful for support):
>   Version: 3.0.0-preview3-27503-5
>   Commit:  3844df9537
> 
> .NET Core SDKs installed:
>   3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 

Error from Ionide:

> [10:42:11 INFO ] Logging to output at level INFO. If you want detailed messages, try level DEBUG.
> [10:42:11 INFO ] Netcore runtime specified
> [10:42:11 INFO ] finding FSAC for
> 	runtime: NetcoreFdd
> 	mono: mono
> 	dotnet: C:\Program Files\dotnet\dotnet.exe
> [10:42:11 ERROR] Failed to start language services. It was not possible to find any compatible framework versio

This happens on startup, regardless of whether a project is loaded or not.

**Comment by Krzysztof-Cieslak** [comment]
CC: @enricosada, any idea?

**Comment by baronfel** [comment]
The error message in question is cut off, specifically the ` [10:42:11 ERROR] Failed to start language services. It was not possible to find any compatible framework versio` line. @boyedarat is it possible to provide the entire message?

**Comment by baronfel** [comment]
I was able just now to load the Saturn solution in Ionide after modifying the `global.json` there to use version `3.0.100-preview-010184`, which I have installed locally, so it doesn't immediately seem like a massive problem with the 3.x SDK.

**Comment by enricosada** [comment]
I'll check.

@boyedarat can you enable ionide logs? https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting

like that you should have `F# language service (server)` output tab

![image](https://user-images.githubusercontent.com/147243/54868054-99a30700-4d88-11e9-8bfe-7003d1e5e9aa.png)

who will contains more info.

That will contains the invocation of `fsautocomplete` too, @boyedarat can you try redo the same from command line? should show more info.

**Comment by boyedarat** [comment]
@enricosada here is the output you have requested:

> Running: C:\Program Files\dotnet\dotnet.exe C:\Users\st4r\.vscode\extensions\ionide.ionide-fsharp-3.34.0/bin_netcore/fsautocomplete.dll --mode http --port 8523 --hostPID=10204
> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       C:\Program Files\dotnet\
>   - The .NET Core Runtime and SDK can be installed from:
>       https://aka.ms/dotnet-download
>   - The following versions are installed:
>       3.0.0-preview3-27503-5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   - Installing .NET Core prerequisites might help resolve this problem:
>       https://go.microsoft.com/fwlink/?linkid=798306

**Comment by enricosada** [comment]
i think that 3.0.0-preview doesnt bundle the 2.1 runtime.

Can you check the list of installed runtimes with `dotnet --list-runtimes`.

Meanwhile i'll check how we can do avoid to require 2.1 for users.

@boyedarat 	as workaround you can install the 2.1 runtime alongside 3.0, should fix.
From https://dotnet.microsoft.com/download/dotnet-core/2.1 , the Runtime .NET Core Installer.
Or any .net core sdk 2.1 who bundle the runtime, will be installed side by side

**Comment by boyedarat** [comment]
@enricosada you are right, the .Net Core 3.0 SDK does not bundle the older runtimes. I installed the latest 2.2 runtime and Ionide seems to be working now.

Does this also mean that the FSAC is compatible with any of the 2.x runtimes? I don't have the 2.1 runtime installed.

Here are the list of runtimes now:
> C:\Users\st4r>dotnet --list-runtimes
> Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by samamiller** [comment]
I solved this by making sure fsac runtime pointed to **net** instead of **netcore** and making a simple fsi.cmd
![fsac1](https://user-images.githubusercontent.com/37316265/54948604-b105ff80-4f02-11e9-994a-2b04fad06d9f.PNG)
![fsicmd](https://user-images.githubusercontent.com/37316265/54948609-b3685980-4f02-11e9-82ff-c64233897edd.PNG)

**Comment by boyedarat** [comment]
@samamiller setting "FSharp.fsacRuntime": "net" only works on platforms where you actually have the .Net Framwork. On Windows, when you open a .Net Core project, Ionides prompts you to use "FSharp.fsacRuntime": "netcore".

**Comment by samamiller** [comment]
Yeah, I suppose it would only work on Windows, although, I haven't tested it on Linux.  You can just ignore the little Ionide prompt. The point is you don't need the .Net 2.x sdk.
![runtimes](https://user-images.githubusercontent.com/37316265/54966166-078e3080-4f39-11e9-82ff-d58540a1e100.PNG)
![window](https://user-images.githubusercontent.com/37316265/54966188-1ecd1e00-4f39-11e9-8f96-1cd8ffade00b.PNG)
Now if I could only figure out how to use the hardware intrinsics with F# :-(

**Comment by enricosada** [comment]
As a note, you need to have .NET Core Runtime v2.x installed.

I know is a bit confusing.

- The .NET Core Runtime is the part who run an application (so bcl, coreclr, etc).
- The .NET Core Sdk is the part who build an application (so msbuild, compiler, etc)

the `dotnet` host can be used to invoke both.

- `dotnet myapp.dll` run with .net core runtime a console app
- `dotnet build` compile a project with the .net core sdk

You can have multiple .NET Core Sdk and .NET Core Runtime installed.
In a .NET Core Sdk (usually pinned with a `global.json`), you can build targeting any runtime, and you can use any .NET Core Runtime (1.1, 2.1, 2.2, 3.0, etc) to run the built assembly.

*NOTE* You can install the .NET Core Runtime 2.1 from https://dotnet.microsoft.com/download/dotnet-core/2.1 . It will install side by side, so will be avaiable in the dotnet sdk (check with `dotnet --info`)

I added https://github.com/fsharp/FsAutoComplete/issues/364 to address that in fsac too, allowing to use .net core runtime 3 too (i think api is enough backward compatibile for now)

**Comment by enricosada** [comment]
@boyedarat @samamiller can you try with `v3.35.0`? should be fixed

**Comment by samamiller** [comment]
@enricosada v3.35.0 works using netcore as the fsac runtime.  Also, I think you are mistaken about needing the 2.x runtime.
![dotnet info](https://user-images.githubusercontent.com/37316265/55445281-cd93de80-5577-11e9-830a-1745c2cc1012.PNG)

**Comment by enricosada** [comment]
@samamiller it works now without runtime v2.x because i fixed that.

For more info (it's the default behaviour for Framework dependent deploment of .net core application, so maybe is useful to know) you can read in https://github.com/fsharp/FsAutoComplete/issues/364
