### ISSUE TITLE
Status: failed to load - Project not restored

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1058]
![image](https://user-images.githubusercontent.com/57396/55065983-1e3da000-507d-11e9-9860-dafc28fc017f.png)

how about just restoring it then? ;-)

**Comment by forki** [comment]
ah paket.lock is missing. so it's just unfortunate error message

**Comment by forki** [comment]
have another instance of this. It would be great if ionide would just try to restore

**Comment by forki** [comment]
the crazy thing is: it looks like everything still works. So I assume the restore happens eventually and it's just showing the annoying message.

Maybe we should just remove the error that's displayed from:

![image](https://user-images.githubusercontent.com/57396/55536193-6aaa6080-56b9-11e9-809f-f77bc0e8346d.png)

**Comment by Krzysztof-Cieslak** [comment]
Yeah, it’s probably something I haven’t really changed when we’ve introduced background restore

**Comment by Krzysztof-Cieslak** [comment]
This sounds like a correct behaviour - as long as the project is not restored it has "not restored" status in the solution explorer. When a restore is finished we get notification and change status.
