### ISSUE TITLE
Odd behavior when running code with trailing comment through fsi

### ISSUE THREAD

**Issue by t3dodson** [ionide/ionide-vscode-fsharp#106]
let x = true
match x with
| true -> printfn "x is true"
//| false -> printfn "x is false"

Highlighting all of this and pressing alt enter results in
> let x = true
match x with
| true -> printfn "x is true"
//| false -> printfn "x is false";;

The double semi's are ignored. I would expect this to execute like this
> let x = true
match x with
| true -> printfn "x is true"
//| false -> printfn "x is false"
;;

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.2.5`
