### ISSUE TITLE
Changing TFM causes project failure message

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1061]
Open a project file up and change the TargetFramework from e.g. netcoreapp2.2 to netcoreapp2.1. Ionide immediately throws an error saying it encountered an error parsing the project.

**Comment by enricosada** [comment]
@isaacabraham please open this in FSAC

**Comment by isaacabraham** [comment]
@enricosada link please.

**Comment by Krzysztof-Cieslak** [comment]
I'll close that in favour of #1077
