### ISSUE TITLE
Use dotnet fsi included in .NET Core 3 Preview 3

### ISSUE THREAD

**Issue by benmp** [ionide/ionide-vscode-fsharp#1062]
**Describe the bug**
As a mac user, I would like to use the "dotnet fsi" command in 3.0.100-preview3 for my fsi window as I am under the impression it would remove the requirement of mono on macOS.

**Expected behaviour**
<img width="105" alt="image" src="https://user-images.githubusercontent.com/9081154/55499054-46d81380-5602-11e9-8fd2-051cb0a24fca.png">

I would like this to work in some form using the new dotnetcore fsi

**Screenshots**
<img width="547" alt="image" src="https://user-images.githubusercontent.com/9081154/55498998-27d98180-5602-11e9-9ca0-cadf954db6ee.png">

**Environment (please complete the following information):**
macOS Mojave 10.14.4

```
➜ dotnet --version
3.0.100-preview3-010431
```
```
➜ dotnet fsi
Microsoft (R) F# Interactive version 10.4.0 for F# 4.6
```
```
Name: Ionide-fsharp
Id: ionide.ionide-fsharp
Description: F# Language Support
Version: 3.35.0
Publisher: Ionide
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp
```

Mono version - none

**Additional context**
I attempted a work around by specifying my own fsi.sh script with the following command inside:

```
dotnet fsi --readline
```

<img width="425" alt="image" src="https://user-images.githubusercontent.com/9081154/55499235-c36af200-5602-11e9-95d7-d2a99fd56914.png">

<img width="531" alt="image" src="https://user-images.githubusercontent.com/9081154/55499213-b5b56c80-5602-11e9-9931-c5a1014cd83a.png">

**Comment by ben-sfcc** [comment]
Solution has been published and works just fine on Mac

[https://vxlabs.com/2019/04/16/dotnet-fsi-in-vscode/](https://vxlabs.com/2019/04/16/dotnet-fsi-in-vscode/)

```
"FSharp.fsacRuntime": "netcore",
"FSharp.fsiFilePath": "/usr/local/share/dotnet/dotnet",
"FSharp.fsiExtraParameters": ["fsi"]
```

**Comment by benmp** [comment]
Solution has been published and works just fine on Mac

https://vxlabs.com/2019/04/16/dotnet-fsi-in-vscode/
```
"FSharp.fsacRuntime": "netcore",
"FSharp.fsiFilePath": "/usr/local/share/dotnet/dotnet",
"FSharp.fsiExtraParameters": ["fsi"]
```
