### ISSUE TITLE
Disable notifications not respected

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1064]
Using latest VS Code and Ionide. The following warning appears, but hitting "Disable Notification" does not help - every time you open the file the same warning appears.

![image](https://user-images.githubusercontent.com/1781813/55958647-78d42000-5c69-11e9-8bfc-f9fe9ee7a672.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #1070
