### ISSUE TITLE
Extension tries to process C# Project Files

### ISSUE THREAD

**Issue by fourpastmidnight** [ionide/ionide-vscode-fsharp#1065]
## Describe the bug
This extension attempts to process C# Project Files when opening a folder containing CShapr projects.

## To Reproduce
Steps to reproduce the behaviour:
1. Open a folder containing one or more C# Projects (e.g. *.csproj files)
2. Wait for it.... VS Code shows an error notification that ionide-fsharp could not process the file <whatever_its_name_in>.csproj.

## Expected behaviour
That the _F#_ extension would not try to process _C#_ projects.

## Environment (please complete the following information):
 - OS: Windows 10 1809 Enterprise
 - Ionide version: 3.35.0
 - VSCode version: 1.34.0 (Insiders)
 - dotnet SDK version: N/A
 - mono / .Net Framework version: N/A

**Comment by Krzysztof-Cieslak** [comment]
Cc: @enricosada

**Comment by enricosada** [comment]
I’ll fix that

**Comment by enricosada** [comment]
sent PR #1069
