### ISSUE TITLE
Experimental version of Ionide

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#1075]
Hey,

We've decided to publish an [experimental version of Ionide](https://marketplace.visualstudio.com/items?itemName=Ionide.experimental-fsharp) as a separate extension.

It will be used for **testing important changes** that can potentially break users such as moving to new project parser (included in the current experimental version) or moving to LSP protocol for communication with our language server (soon).

We would really appreciate any real-world testing of this experimental extension.

## How to try it

You can install it in your vscode, after uninstalling the stable ionide extension, but that's not the easy way because require more work.

For easy testing without breaking your nomal usage, it's **recommended** to install the experimental version in [VSCode Insider version](https://code.visualstudio.com/insiders/).
VSCode insiders (green icon) can be installed **side-by-side** alongside VSCode (blue icon) and have a different set of extensions.

So you can have stable ionide on vscode, and experimental in vscode insiders, ready to be used running  `code-insiders` instead of usual `code`, without risks.

VSCode insiders will auto update the experimental extension as usual, ready for new bugfixes.

Any feedback will be really appreciated.

Thanks a lot!

## Main changes in current experimental version: project system

Changed the projects parsing and loading of the workspace.
Use a newer version of [dotnet-proj-info](https://github.com/enricosada/dotnet-proj-info/) to replace old parser/loader with `Dotnet.ProjInfo.Workspace`

**What to test**: loading of projects, solution and fsx scripts
**Goal**: all projects should load like stable version, both old sdk (verbose fsproj) and .net sdk (slim fsproj) projects.

It's a big refactoring effort in FSAC and that will allow lots of bugfix and features later (multi target framework support, faster and stable parsing of projects, debug/release configuration, unified .NET and .NET Core FSAC, etc)

Please report issues in https://github.com/fsharp/FsAutoComplete/issues adding `[experimental]` to the title

For help installing or report issues, please contact @enricosada 

All changelog in the extension release notes, contained also in [RELEASE_NOTES_EXPERIMENTAL.md](https://github.com/ionide/ionide-vscode-fsharp/blob/master/RELEASE_NOTES_EXPERIMENTAL.md)

**Comment by magnushammar** [comment]
Hi. Tested experimental with a Fable project and got the following error. (can be reproduced with fable2-samples repo)

```
No .fsproj or .fsx file references c:\stargazer\fable\fable2-samples\browser\src\App.fs
```

When reporting issues on Experimental, should we do it on this issue? or perhaps an Experimental label?

**Comment by magnushammar** [comment]
It turns out that the problem was related to me checking VS2019 Preview out.  Removed it and now everything work again.

**Comment by Krzysztof-Cieslak** [comment]
> When reporting issues on Experimental, should we do it on this issue? or perhaps an Experimental label?

Yes, please create separate issues, I'll label it correctly.

**Comment by Krzysztof-Cieslak** [comment]
We don't really have a reason to use experimental at the moment, there shouldn't be any such a huge changes as in case of Ionide 4.0 anytime soon.
