### ISSUE TITLE
Have an option to make Ionide "silent"

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1077]
At least until Ionide doesn't show project parse failures on opening solutions that e.g. don't have packages restored (or at other random times), I think Ionide should either stop showing the notifications or at least have an option to stop showing them. 9/10 times they don't provide any value since they fix themselves on a build, and instead they give the impression that F# / VS Code / Ionide is somehow broken.

**Comment by enricosada** [comment]
like a disable notification in 

![image](https://user-images.githubusercontent.com/147243/56357400-f2c15780-61db-11e9-9560-865785a69084.png)

?

**Comment by isaacabraham** [comment]
In this case it should be shown front and centre - not hidden per the screenshot but a big button next to Show status and the default button.

Personally I would rather just remove it completely at the moment - it's shown so often I have no trust in it any more that the project is "really" broken or just Ionide being overly chatty.

**Comment by vbfox** [comment]
I agree that the current status where a simple `dotnet restore` can show this popup dozen of times is useless.

I'd very much prefer status bar indicators (like omnisharp) for solution/project/file.

**Comment by isaacabraham** [comment]
@vbfox it's actually worse than useless - people see it and think that Ionide (or worse just F# in general) simply is broken. I'm seeing this with virtually every new person to F# that tries Ionide - it reduces confidence and people think that the tech is broken.

Is there a way to turn off this warning and push out a new release of Ionide with that in @Krzysztof-Cieslak ?

**Comment by Krzysztof-Cieslak** [comment]
I'm still on the fence with that. Without notification people will complain that Ionide is not working and they don't know why - this at least attempts to put in their face detailed error message that they can use to debug problem instead of just crying everywhere that Ionide is broken.

**Comment by vbfox** [comment]
After working on the other issue ("file not in any project" warning) I think it's a big problem and shouldn't be there in this form.

Not the error/warning itself but the notification itself. It has an enormous problem of timing

* It's show in situations where it's 100% temporary and only present for technical reasons (A build is in progress and some files are locked by paket/dotnet/nuget or in a weird temporary state)
* In cases like that it can reappear every seconds making the notifications blink and any dismissal by the user useless (With a big impression when closing the notification to have it reappear the next second of trying babysit ionide)
* It doesn't disappear by itself, not when it's temporary, but even when it's an user error that the user fixed... it just stay there. Like there was an error, maybe it was you, maybe not, sometimes before now...

Essentially I think it should be replaced by a second indicator in the status bar showing the current workspace status (Just near the current project one), and potentially delaying status changes for 1s or 2s to ensure that the status is stable. Ideally clicking on it would lead somewhere that indicate what's wrong in the workspace

**Comment by Krzysztof-Cieslak** [comment]
> Essentially I think it should be replaced by a second indicator in the status bar showing the current workspace status (Just near the current project one), and potentially delaying status changes for 1s or 2s to ensure that the status is stable. Ideally clicking on it would lead somewhere that indicate what's wrong in the workspace

I think we can do that.

**Comment by vbfox** [comment]
If it's set/cleared correctly Ionide could also report an error in the csproj file using the normal VSCode error reporting.

It'll make the file red in the file list providing another location where the user can find why his project doesn't work

**Comment by isaacabraham** [comment]
> I'm still on the fence with that. Without notification people will complain that Ionide is not working and they don't know why - this at least attempts to put in their face detailed error message that they can use to debug problem instead of just crying everywhere that Ionide is broken.

@Krzysztof-Cieslak that's true, but the problem is that there are way, way more false positives than real project errors. So people just dismiss the warning and then when a "real" error comes up, they don't believe it. So the real purpose that you're (rightly) aiming for is unfortunately being lost.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by 66118a5ca932224eaa46ef4bd0e79d5f45cf5fa2
