### ISSUE TITLE
Ionide does not display a helpful error when dotnet isn't installed

### ISSUE THREAD

**Issue by daviwil** [ionide/ionide-vscode-fsharp#1079]
**Describe the bug**

Hi all, I recently tried to get Ionide up and running on my Linux and Windows machines after not having used it for a while and ran into an issue where F# language features didn't seem to fully activate when opening a .fs file in an F# project workspace.  It turned out that the problem was that I didn't have the `dotnet` CLI tools installed but Ionide gave me no indication that this was a requirement and the cause of the issue.

I think it'd be extremely helpful to new users if Ionide would show a notification popup when it doesn't find `dotnet` on the machine.

**To Reproduce**

1. Install Ionide extension on a machine without `dotnet` CLI installed
2. Load an F# project folder
3. Observe no IntelliSense or other language feature behavior
4. Open F# Language Server logs and observe:

```
[07:31:23 INFO ] No FSAC url provided, using http://127.0.0.1:8636/ 
[07:31:23 INFO ] No runtime specified, defaulting to .NET 
[07:31:23 INFO ] finding FSAC for runtime: Implied (NET) mono: mono dotnet: null
```

**Expected behaviour**

At first, I just expected the language features to work as I had Mono installed on Linux.  Once I realized that I needed to install `dotnet`, I wished that Ionide would have told me it was missing.

**Screenshots**

N/A

**Environment (please complete the following information):**

 - OS: Linux (also reproes on Windows without `dotnet` installed)
 - Ionide version: 3.35.0
 - VSCode version: 1.33.1
 - dotnet SDK version: None at the time of this issue
 - mono / .Net Framework version: 5.18.1

**Additional context**

N/A

**Comment by Krzysztof-Cieslak** [comment]
TBF, it is mentioned in the readme as a requirement... but I know that RTFM ain't good answer ;-)
We definitely should add some notification for this case (and general problem detection on startup is something we should work more on)

**Comment by daviwil** [comment]
Funny thing, I looked at the README and assumed that dotnet was only needed if you were working on a .NET Core code base, didn't realize it was required until I had this issue and read the README more closely :)

**Comment by Krzysztof-Cieslak** [comment]
This should be improved in Ionide 4.
