### ISSUE TITLE
What is FSI?

### ISSUE THREAD

**Issue by JoeArizona** [ionide/ionide-vscode-fsharp#108]
Hi all – I see lots of references to FSI in recent changelogs and elsewhere. Perhaps a dumb question – what is FSI, exactly? I assume it's F Sharp I.....? F Sharp Ionide? What does it mean in the context of "path to FSI" or an "FSI dir"? Is it simply another name for Ionide as such, or the Ionide executable?

**Comment by cloudRoutine** [comment]
[F# Interactive](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/fsharp-interactive-%5Bfsi.exe%5D-reference)
