### ISSUE TITLE
VS Code hangs when using the World Bank type provider and "dotting" in to certain structures

### ISSUE THREAD

**Issue by drk-mtr** [ionide/ionide-vscode-fsharp#1081]
**Description**
I'm not sure whether this is VS Code, Ionide, the type provider or (most likely!) something I'm doing wrong.

When attempting to use the World Bank type provider, when I dot into the structure in certain places, VS Code hangs and needs to be force closed and restarted.

**To Reproduce**
1. Initialise paket and add FSharp.Data to packages folder.
2. Create `.fsx` file and paste in as below:

```fsharp
#I "./packages"
#r "./packages/FSharp.Data/lib/net45/FSharp.Data.dll"
open FSharp.Data

let wb = WorldBankData.GetDataContext()

let whatever = 
  wb.Countries.``Spain``.Indicators.``Access to electricity (% of population)``
```

As soon as I place a `.` after `Access to electricity (% of population)`, VS Code hangs and doesn't seem to recover.

This occurs while in `net` and `netcore` mode, and it happens in a fresh console app as well as .fsx files.

The same snippet works fine in Visual Studio.

**Environment:**

| Software | Version |
| --- | --- |
| OS | Windows 10 |
| Ionide version | 3.35.0 |
| VSCode version | 1.33.1 |
| dotnet SDK version | I'm not sure as I don't know whether the global.json is used, however I have both 2.2.202 and 3.0.100-preview3-010431 installed. The issue occurs when I create a console app with a global.json that references 2.2.202. |
| mono / .Net Framework version | Mono 5.12.0, .Net Framework 4.7.2 - however with multiple versions hanging around my PC I sometimes find it hard to be sure what is actually being referenced! |

**Additional context**
I don't see anything new if I have the VS Code Developer Tools window open while doing this, but if there are logs written somewhere I can go and dig those out...

Also while I'm here, huge thanks for the truly **brilliant** software!

**Comment by cannorin** [comment]
I think this is related to #1073 (``` `` ``` and `( .. )` on the same line)

**Comment by drk-mtr** [comment]
Yes it appears to be that, since the issue persists when I remove the reference to the Type Provider.

What's the etiquette here, do I close my issue and let it be tracked under #1073?

**Comment by Krzysztof-Cieslak** [comment]
If bug is not connected to TPs I’ll close this one
