### ISSUE TITLE
Squigglies galore with FAKE5 / #load

### ISSUE THREAD

**Issue by MiloszKrajewski** [ionide/ionide-vscode-fsharp#1083]
I find it hard to describe the problem, so I'm attaching a minimal FAKE5 project to reproduce it. FAKE5 is working fine (is doing what I expect it to do), but Ionide considers additional `.fsx` file invalid: lot of squigglies after `open System` with cryptic error saying: 
"The type 'IEquatable`1' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, ..."

**To Reproduce**
1. Unzip attached project
2a. Run `fake build -t clean` OR...
2b. Run `dotnet tool install fake-cli --tool-path .fake && .fake/fake build -t clean`
3. Observe it installed all dependencies
4. Open `build.tools.fsx` with Ionide
5. Observe squigglies all over the file

**Expected behaviour**
As FAKE works I would expect Ionide not reporting any problems

**Screenshots**
![image](https://user-images.githubusercontent.com/4333436/56673182-b7c59500-66af-11e9-8798-e568934c82b9.png)

![image](https://user-images.githubusercontent.com/4333436/56673258-d62b9080-66af-11e9-8c7b-f10c25b467cf.png)

**Environment (please complete the following information):**
 - OS: Win 10
 - Ionide version: Ionide-FAKE 1.2.3, Ionide-fsharp 3.35.0
 - VSCode version: 1.33.1
 - dotnet SDK version: 2.2.104
 - mono / .Net Framework version: 4.7.2

**Additional context**
I do one thing which is different that usual FAKE5 setup. I have additional `.fsx` (`build.tools.fsx`) file and I'm trying to reuse same intellisense `.fsx` as mail file (`build.fsx`).

[load.fake5.zip](https://github.com/ionide/ionide-vscode-fsharp/files/3113102/load.fake5.zip)

**Comment by MangelMaxime** [comment]
Hello @MiloszKrajewski ,

you need to add:

```fs
#if !FAKE
#r "Facades/netstandard"
#r "netstandard"
#endif
```

after `#load ".fake/build.fsx/intellisense.fsx"` this is needed in order to load the the needed deps for `.fsx` files. (I don't remember the exact explanation sorry ^^)

**Comment by MiloszKrajewski** [comment]
Thanks, worked like a charm. Should I add it to main file as well?

**Comment by MangelMaxime** [comment]
It's needed only when working on an `.fsx` file. However, I don't know if this is needed in each `.fsx` you have in the repo. I guess you will have to test if you have the case.
