### ISSUE TITLE
FSI not detected for Build Tools 2019

### ISSUE THREAD

**Issue by keithn** [ionide/ionide-vscode-fsharp#1084]
I have red errors in the code where it doesn't seem to know the libraries and I get "Failed to send text to FSI"

yet I have access to 2019s FSI in the path and can use it from terminal

Microsoft (R) F# Interactive version 10.4.0 for F# 4.6
Copyright (c) Microsoft Corporation. All Rights Reserved.

with ionide 3.35.0

**Comment by keithn** [comment]
just needed to set the path to the FSI in  File->Preferences->Settings->Extensions->FSharp configration

Fsi File Path:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsi.exe

**Comment by Krzysztof-Cieslak** [comment]
This should be detected automatically, probably our set of paths we check is not updated yet

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/commit/f1b594d4bf9e1c028a056c9a7bb3925777eb398e

**Comment by ronaldschlenker** [comment]
I think you should reopen this issue. My scenario is this: VS2017 with F# 4.5 was installed. Then I installed "VS 2019 Build Tools" (with one single option "F# Compiler" enabled) to be able to use F# 4.6. But Ionide still opens F# 4.5.

BTW: The path of F# in VS 2019 Build Tools is:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsi.exe

**Comment by ronaldschlenker** [comment]
...and another thing (propably open a new issue?):

When I use this in my settings:

> "FSharp.fsiFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsiAnyCpu.exe"

Now sending this line of code to FSI:

```fsharp
let ärgerlich = "ärgerlich"
```

results in:

>> let �rgerlich = "�rgerlich";;
> matchBookings.fsx(2,5): error FS0010: Unerwartetes Zeichen "�". in Bindung
