### ISSUE TITLE
How do we add priority label mentioned by open-collective-bot?

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1089]
Perhaps, I am missing something but I don't know how to add that priority label. ^^

**Comment by Krzysztof-Cieslak** [comment]
It seems we have some small problems with the bot, I'll try to figure it out ;-)

**Comment by Krzysztof-Cieslak** [comment]
I'm fairly sure it's connected to the fact that you don't have GitHub URL set in your Open Collective profile.

**Comment by MangelMaxime** [comment]
Oo perhaps ^^

I added it and I also linked my Github account via OAuth. We will see the next time I open an issue.

**Comment by vbfox** [comment]
Once we know what's the magic thing the bot message should say that instead of the current (confusing) message
