### ISSUE TITLE
Cannot go to definition for FSharp.Core

### ISSUE THREAD

**Issue by runbmp** [ionide/ionide-vscode-fsharp#1092]
**Describe the bug**
I cannot use the "go to definition" function for any functions builtin to the standard library.

**To Reproduce**
Attempt to use the "go to definition" feature on "Head" of lst.Head below
```
[<EntryPoint>]
let main argv =
    let lst = [ 1; 2; 3;]
    let head = lst.Head
    0
```

**Expected behaviour**
The documentation would open for this property

**Screenshots**
![image](https://user-images.githubusercontent.com/9081154/57333598-7f27b180-70da-11e9-8fa2-94bdb00ef61f.png)

```
[15:08:28 DEBUG] REQ (318) -> {finddeclaration}, File = "~/src/App/Program.fs"
Data={"FileName":"/Users/me/Documents/work/fsharp_projects/Focapi/src/App/Program.fs","Line":4,"Column":21,"Filter":""}
[15:08:28 DEBUG] RES (318) <- {finddeclaration} in 3 ms: Kind={"finddecl"}
Data={"File":"/E:\\A\\_work\\935\\s\\src\\fsharp\\FSharp.Core\\prim-types.fs","Line":3264,"Column":18}
```

**Environment (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Ionide version: 3.36.1
 - VSCode version: 1.33.1
 - dotnet SDK version: 3.0.100-preview5-011568
 - mono / .Net Framework version: N/A

**Comment by bvanrijn** [comment]
I'm having this issue as well on

 - OS: macOS Mojave 10.14.5 (18F203)
 - Ionide version: 4.0.4
 - VSCode version: 1.36.1 (1.36.1)
 - dotnet SDK version: 2.2.105
 - mono / .Net Framework version: 5.18.1.28

except it just errors out instead of showing “No definition found for …”

**Comment by evgeniyp** [comment]
Same for me:

Win10 1903 (OS Build 18362.239)
Ionide-fsharp 4.0.6
dotnet core SDK 2.2.401

Trying to navigate to `printfn` declaration
![image](https://user-images.githubusercontent.com/1850852/62883199-c9e94300-bd33-11e9-8a91-29bc86261975.png)

**Comment by arthurborisow** [comment]
Having the same issue not only with `FSharp.Core` but also with other nuget packages even if they are open sourced and code is available on github

**Comment by Krzysztof-Cieslak** [comment]
This is working since some time.

**Comment by tenatus** [comment]
This is broken (again?)

**Comment by MangelMaxime** [comment]
Hello @tenatus,

Could you please provide information about your environment?

For me it seems to be working:

https://github.com/ionide/ionide-vscode-fsharp/assets/4760796/e4e5eb44-3d3f-46e1-8e5e-6c621a143bcf

**Comment by tenatus** [comment]
Ah, I tried just now with a new project (dotnet 7) and indeed it does work.

This used to work for files that are just in a folder, not part of a .fsproj so that is why I was thinking it was broken. I tested this in version 5.10.1 and it worked there for non-project files.

**Comment by MangelMaxime** [comment]
Perhaps, there is some small difference.

For example, in my case the file doesn't even exist on disk, and in that case I suppose it use it as if it was an `.fsx` file.

Perhaps, if you have a `.fs` file alone (without a project file), then it doesn't work but I would say this is kind of normal as a single `.fs` is not something that should happen.

I believe it is easier you have a single file as `.fsx` or a `.fs` file who is part of an `.fsproj`.

**Comment by tenatus** [comment]
That is interesting. I don't suppose you know what's going on with this question do you? (I'm wondering if this should be a bug report somewhere, and where).

https://stackoverflow.com/q/77430190/7392598
