### ISSUE TITLE
FSI support for dotnet core

### ISSUE THREAD

**Issue by KySpace** [ionide/ionide-vscode-fsharp#1096]
It seems that dotnet core 3 preview has already supported FSharp Interactive. I am trying to use this feature with the help of Ionide.

I have tried with opening fsi directly through dotnet CLI, and it appears to be working.
![image](https://user-images.githubusercontent.com/23047275/57506977-f43ff480-732f-11e9-9420-3216839c914a.png)

However, the `F# Run script` or `FSI: Send file` will yield `Failed to spawn FSI, please ensure it's in path`, leading to the problem of what `FSharp.fsiFilePath` should be set to. I have tried setting the path to either `dotnet.exe` or `fsi.exe` but neither works. I would like to know if there is a way to utilize it now and request it to be better supported if it is currently not.

Thank you

**Comment by benmp** [comment]
Does this work?

> Solution has been published and works just fine on Mac
> 
> https://vxlabs.com/2019/04/16/dotnet-fsi-in-vscode/
> 
> ```
> "FSharp.fsacRuntime": "netcore",
> "FSharp.fsiFilePath": "/usr/local/share/dotnet/dotnet",
> "FSharp.fsiExtraParameters": ["fsi"]
> ```

**Comment by KillyMXI** [comment]
> Does this work with adjusted path for your OS?

Not on Windows.
Already mentioned in #1087 (looks like duplicate by the way)

**Comment by KySpace** [comment]
> > Does this work with adjusted path for your OS?
> 
> Not on Windows.
> Already mentioned in #1087 (looks like duplicate by the way)

Oh, OK. Thanks!
