### ISSUE TITLE
Go To Symbol in File does not show all symbols

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1098]
Create a new F# script in Ionide (this is also the same behaviour in .fs files as well)

```fsharp
module Foo

type Person = { Name : string }

let add x y =
    x + y

module Bar =
    type Blah = { Age : int }
    let apples x = x + "! How do you like them apples?"
```

Running show all symbols in file (`ctrl + shift + O`) I would expect to see 8 symbols:

1. `Foo` module
1. `Person` record
1. `Name` field
1. `add` function
1. `Bar` module
1. `Blah` record
1. `Age` field
1. `apples` function

However, Ionide only show 7 symbols - top level functions (`add` from the list above) are not shown:

![image](https://user-images.githubusercontent.com/1781813/57570362-41d86200-7401-11e9-9b2d-4f62660052f6.png)

In this example it's just one symbol but it's very common to have a file with a single module named at the top and have your functions inside it - these are currently being missed.

As a second point (maybe just education for me here) I'm not sure why the `Blah` record is shown qualified as `Bar.Blah` but `apples` is not.

**Comment by isaacabraham** [comment]
> PS.: We offer backer support for all backers. Don't forget to add backer label when you start backing us 😄

How do I add "backer" label here ;-)

**Comment by vbfox** [comment]
@isaacabraham Tried in https://github.com/ionide/ionide-vscode-fsharp/issues/1099 and I'm recognized now, don't know what worked but I both specified my github user in opencollective profile and connected my account

The message of the bot is very confusing, is it configurable @Krzysztof-Cieslak  ?

**Comment by vbfox** [comment]
Ah it's configurable here https://github.com/ionide/ionide-vscode-fsharp/blob/master/.github/opencollective.yml#L18

**Comment by isaacabraham** [comment]
Thanks, I've done that, maybe next issue it'll do it.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/ionide/ionide-vscode-fsharp/commit/9a176c2232a7a50d22c75715d5cfcd2d8fc1f4b7
