### ISSUE TITLE
Load failed, error: Project not restored → restore succeeds, load keeps failing, error remains

### ISSUE THREAD

**Issue by lfr** [ionide/ionide-vscode-fsharp#1100]
All my fsprojs fail to load, such as the "common" project here that I chose because it has no dependencies:

![image](https://user-images.githubusercontent.com/6348118/57620857-45e3bb80-758a-11e9-95e7-11188cf735c6.png)

**To Reproduce**
1. Open solution dir
2. Open Ionide toolbar
3. Manually restore failing project (dotnet restore)

**Expected behaviour**
Projects should load properly after restore

**Screenshots**
![image](https://user-images.githubusercontent.com/6348118/57620982-93f8bf00-758a-11e9-919e-861245951a31.png)

**Environment (please complete the following information):**
 - OS: Windows 10 1809
 - Ionide version: 3.37.0
 - VSCode version: 1.33.1
 - dotnet SDK version: 2.2.203
 - mono / .Net Framework version: netcoreapp2.2

**Additional context**
I have build props that ensure build artifacts are always written in a specific place that's not within the solution directory, I'm not sure it's related:
```
<Project>
  <PropertyGroup>
		<BaseOutputPath>$(HOMEDRIVE)$(HOMEPATH)$(HOME)/.vsbuild/$(VisualStudioVersion)/cnet-akeneo/$(MSBuildProjectName)/bin/</BaseOutputPath>
		<BaseIntermediateOutputPath>$(HOMEDRIVE)$(HOMEPATH)$(HOME)/.vsbuild/$(VisualStudioVersion)/cnet-akeneo/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
	</PropertyGroup>
</Project>
```
Both VS Code and VS 2019 handle theese correctly btw.

**Comment by lfr** [comment]
I promise I'll back you if I ever manage to start using you 😇

**Comment by vbfox** [comment]
I don't know if it's the case here but Ionide (Well FSharpAutoComplete I think) has never worked well for me when I redirected `obj` so I abandoned doing it...

**Comment by enricosada** [comment]
I can repro, added https://github.com/fsharp/FsAutoComplete/issues/421

With `dotnet proj fsc-args` i get the correct values.
Seems in the projects loading fails because check `projDir/obj/project.assets.json` to see if restored. And with custom `obj` is not ok obv :D 

I'll fix that.

**Comment by lfr** [comment]
This is great news, I've always wanted to give

**Comment by Krzysztof-Cieslak** [comment]
Custom `BaseIntermediateOutputPath` should be supported in `4.8.1`
