### ISSUE TITLE
Confusing indentation of project files in the F# project explorer

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1104]
**Describe the bug**
The indentation of files within a given directory level in the project explorer is confusing and can make it seems like files that are siblings of an unopened folder are actually children of the folder.

Sample: 

Given project file items of 

```xml
  <ItemGroup>
    <Compile Include="Books.fs" />
    <Compile Include="Components/ErrorNotification.fs" />
    <Compile Include="Components/MenuItem.fs" />
    <Compile Include="Pages/Routing.fs" />
    <Compile Include="Pages/Home.fs" />
    <Compile Include="Pages/Counter.fs" />
    <Compile Include="Pages/SignIn.fs" />
    <Compile Include="Pages/Data.fs" />
    <Compile Include="Main.fs" />
    <Compile Include="Startup.fs" />
    <None Include="paket.references" />
  </ItemGroup>
```

the following tree is rendered:

![image](https://user-images.githubusercontent.com/573979/58185566-f2075f80-7c78-11e9-8cbf-5ed7629c1e5a.png)

Here `Books.fs` is actually a sibling of the `Components` folder, but it is indented to a level that suggests it's a child of the `Project References` node.  Same for `Main.fs` and the `Pages` folder.

The same structure from the Explorer view (and yes I know ordering is different, etc) is:

![image](https://user-images.githubusercontent.com/573979/58185727-3d217280-7c79-11e9-918d-4967d818a684.png)

Here flat files are clearly distinguishable from the unopened folders at this level.

**Expected behaviour**
I'd expect closed folders and flat files that are siblings of that folder to be at the same indentation level.

**Environment (please complete the following information):**
 - OS: macos
 - Ionide version: experimental
 - VSCode version: insiders
 - dotnet SDK version: 2.2.203
 - mono / .Net Framework version: 5.20

**Comment by Krzysztof-Cieslak** [comment]
I'm pretty sure it's VSCode-by-design, and it depends on your icon theme. For example if theme you're using is providing icons for the folders it looks better - file icon is clearly on the same level as folder icon.
![image](https://user-images.githubusercontent.com/5427083/58327001-b1514700-7e2e-11e9-9577-f567961670cb.png)

**Comment by baronfel** [comment]
Ok great! What icon theme are you using here? I'll see if I can fix it locally just by using it.

**Comment by Krzysztof-Cieslak** [comment]
https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme

**Comment by baronfel** [comment]
for closure, I was using the built-in Seti VS Code theme and there's no folder icon present in that theme for some reason. using many other themes (including the built-in minimal theme) did work.
