### ISSUE TITLE
Readme says "F# >= 3.1", but I get errors looking for 4.0 after install

### ISSUE THREAD

**Issue by ian-moore** [ionide/ionide-vscode-fsharp#111]
Installed ionide to a machine that only has F# installed via VS 2013, which is F# 3.1

Trying to run any ionide command gives an error similar to 

     No handler found for the command: 'fsharp.NewProject'. An extension might be missing an activation event.

In the developer console I see the following after code starts up:

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:97 [Extension Host] Activating extension `Ionide.Ionide-fsharp` failed: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0'.

I can install F# 4.0 no problem, but the readme doesn't reflect this requirement.

**Comment by Krzysztof-Cieslak** [comment]
F# 3.1 is still supported, bug fixed in `2.2.18`
