### ISSUE TITLE
File not detected as part of F# project with vscode remote

### ISSUE THREAD

**Issue by aaronpowell** [ionide/ionide-vscode-fsharp#1110]
I'm using [VS Code Remote over WSL](https://github.com/Microsoft/vscode-remote-release) and I've noticed an odd bit of behaviour with Ionide not detecting files as part of an F# project.

I keep finding this message in the quick info bar:

![image](https://user-images.githubusercontent.com/434140/58224764-4c301f80-7d62-11e9-93cf-89b140ac0c2d.png)

Upon inspection, it comes from [this line of code](https://github.com/ionide/ionide-vscode-fsharp/blob/ad67bbfff684899cd5b138cabb0ccc7afa276b94/src/Components/QuickInfoProject.fs#L27).

What's interesting is this file is part of an F# project, but when I opened VS Code Remote it was from a symlink'ed path in WSL (opened from `~/github/my-project` which is symlink'ed to `/mnt/c/github/my-project`).

It also results in some funky stuff in the project explorer:

![image](https://user-images.githubusercontent.com/434140/58224846-a4672180-7d62-11e9-8391-88c4eef9f8f8.png)

Now, if I was to open it from the non-symlink'ed path it works fine, the file is detected as part of a project, and the explorer looks normal.

I'm not 100% sure if this is a problem in Ionide or the way VS Code Remote represents file paths to extensions over the Remote bridge, nor is it a _huge_ problem (you can work around it by not using symlink'ed paths). Mostly I'm reporting this as something to be aware of and to help others who get confused (since it not being in a project results in autocomplete/code lense not working, etc.).

**Comment by vbfox** [comment]
I think ionide was never really adapted for the new remote feature, quite a bit of things must be broken :)

**Comment by Krzysztof-Cieslak** [comment]
I think it’s something about symlinks - I wouldn’t be surprised if symlinks were broken even without remote stuff.

Remote-container is working without any problems, I haven’t tried WSL or SSH

**Comment by aaronpowell** [comment]
As @Krzysztof-Cieslak said, it works with Remote, I do have it running if I'm using the path from Windows rather than a symlink via WSL, my guess is there's something weird about how the file path is represented via the extensions API to Ionide (and well, any extension).

Not a super problematic issue, there's a simple workaround, but I'm sure someone else will hit it and hopefully they find this issue first. 😄

**Comment by Krzysztof-Cieslak** [comment]
@aaronpowell, some time ago we've done bunch of improvements to the project parsing, could you check if this bug is still is present?

**Comment by aaronpowell** [comment]
Ah nope, haven't noticed this in a while (nor do I tend to use WSL in the way that I was back then since it's not idea with WSL2).

**Comment by beerai** [comment]
I created a project and am seeing this in WSL 2. I don't believe my directories are symlinked back to /mnt/c/ since when I do
`test -L dir` then I see it returns false
