### ISSUE TITLE
Debugging doesn't start

### ISSUE THREAD

**Issue by drguildo** [ionide/ionide-vscode-fsharp#1115]
**Describe the bug**
I can't seem to get debugging to work.

 - The first time I tried I got an error about it not being able to start because of something to do with OmniSharp either still running or something (sorry, I can't remember the exact error message)
 - The second time it said "Installing packages..." in the status bar but I waited for 10-15 minutes and it never went away and nothing else happened
 - Now (after restarting), whenever I try, it just opens a launch.json file in a tab and nothing else happens

Debugging a C# project using VS Code works perfectly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select Debug -> Start Debugging
2. Select ".NET Core"

**Expected behaviour**
My program is run and the breakpoint I set was triggered.

**Environment (please complete the following information):**
 - OS: Windows 10 Version 1809
 - Ionide version: 3.38.0
 - VSCode version: 1.34.0
 - dotnet SDK version: 2.2.101
 - mono / .Net Framework version:

**Comment by drguildo** [comment]
It's probably irrelevant but debugging also works in Visual Studio Community 2019.

**Comment by LukeBurgessYeo** [comment]
Was this the OmniSharp error that you saw?
![image](https://user-images.githubusercontent.com/15360369/58943772-5dbcf280-8778-11e9-96fb-8d9ed85e2443.png)

**Comment by m0rphed** [comment]
Encountering same issue on Arch Linux (Ctlos) using vscode-oss:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Ctlos
 OS Version:  net-1.0_20200407
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Debugging just hangs, never reaches breakpoints (even after I configured `task.json` and `launch.json`)

Omnisharp also saying *"Cannot create .NET debug configurations. The OmniSharp server is still initializing or has exited unexpectedly."*

Also, cannot run without debugging either. :disappointed:

**Comment by drguildo** [comment]
@LukeBurgessYeo Thanks. I was able to get debugging working using your guide.

**Comment by m0rphed** [comment]
Maybe related ? [#3694](https://github.com/OmniSharp/omnisharp-vscode/issues/3694)

**Comment by rustedwizard** [comment]
Have a look at [this](https://github.com/OmniSharp/omnisharp-vscode/issues/4172)

> F# projects are not officially supported by this extension -- this extension tries to be smart about the launch.json that it generates, but being smart requires project understanding, and OmniSharp only understands C# projects. So definitely the best option would be for the F# extension (which I think the most popular one is Ionide-fsharp) to provide smart templates for launch.json based on understanding the project, or even just really basic templates. So if Ionide-fsharp doesn't, you may want to log an issue or follow up.

I think what happened is that Omnisharp does not understand F# project since it's not designed to support F# support.

**Comment by jkone27** [comment]
link to new trials https://github.com/ionide/ionide-vscode-fsharp/issues/1309
