### ISSUE TITLE
Error Reporting for Incorrect #load and #r

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-vscode-fsharp#112]
Errors are not being shown when a file or package cannot be found in a `.fsx` It looks like -

![](http://i.imgur.com/P6AORPL.png)

When it should look like -

![](http://i.imgur.com/icxI2zw.png)

**Comment by Krzysztof-Cieslak** [comment]
That looks like a problem on FCS side? Those errors should be returned from FSAC?

**Comment by 7sharp9** [comment]
There are two error streams those from Parse and those from type check, I would expect this to be a parse error.  Maybe those are not collected properly?  Should be easy to check with a few lines of FCS code.

**Comment by Krzysztof-Cieslak** [comment]
Looks like FSAC collects only errors only from type check, ignoring parse results - https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/Commands.fs#L31-L42

**Comment by 7sharp9** [comment]
https://fsharp.github.io/FSharp.Compiler.Service/editor.html 
Try `ParseAndCheckFileInProject` and examine `parseResults` and `checkFileAnswer`  if the error is not there at all then its a compiler issue.

**Comment by 7sharp9** [comment]
In XS we used to combine all errors: https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/108e0d2ea6980af775b821d55e1e2c218c253070/MonoDevelop.FSharpBinding/Services/LanguageService.fs#L153-L161

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `2.8.7`
