### ISSUE TITLE
Getting 'command fsharp.NewProject not found' error on Mac

### ISSUE THREAD

**Issue by alexxn** [ionide/ionide-vscode-fsharp#1120]
I have VsCode 1.24.0, MacOS 10.14.4 and Ionide-fsharp 3.38.0, Ionide-Fake 1.2.3, Ionide-Paket 1.12.0 extensions installed. 

Trying to follow these basic instructions https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode

And failing on the very first step. After calling Cmd-P menu and selecting ANY "F#: ..." command I'm getting errors like "Command <fsharp.xxx> not found"

Not sure if this comes from extension or VSCode or whatever place it might be.

Is it a Ionide bug? What stept should I take to fix it/provide more info on this issue?
![1](https://user-images.githubusercontent.com/5682814/59313104-4f129600-8cb8-11e9-8afe-9a56b695320f.png)

**Comment by alexxn** [comment]
Also I brewed mono, FORGE is working from console (tried with "forge new project" command at least).

When I open new project in VsCode I see F# menu appears in the text editor. So plugin is probably activated and working.
![2](https://user-images.githubusercontent.com/5682814/59313470-d3b1e400-8cb9-11e9-86fd-078d3bf134d9.png)

**Comment by Nixonite** [comment]
same issue here
