### ISSUE TITLE
Ionide 4.0 comes with way more greyed out things. Please add quickfix for it

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1121]
![image](https://user-images.githubusercontent.com/57396/59335596-2f519100-8cfd-11e9-8269-62248738139e.png)

Missing a quickfix to remove the greyed code.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/pull/405/commits/3c35b21811813a2d3ee4b3d8bae18aff11011cbd

**Comment by Krzysztof-Cieslak** [comment]
Released in experimental `0.3.1`
