### ISSUE TITLE
Wrong quickfix for replacing unused "this" in members in Ionide 4

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1123]
![image](https://user-images.githubusercontent.com/57396/59336847-a1c37080-8cff-11e9-96da-96d1dea49b06.png)

it should propose double underscore

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/pull/405/commits/857bd98f6c9cf57868457ec66f9f66d78b00fe27

**Comment by Krzysztof-Cieslak** [comment]
Released in experimental `0.3.1`
