### ISSUE TITLE
References count is always 0 with Ionide 4

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1124]
**Describe the bug**

I don't know if references work or not in Ionide 4 but the count is always 0 for me.

**To Reproduce**

```fs
let x = ""

let test =
    x
```

See how `x` is marked with `0 references`:

**Expected behaviour**

`x` should be marked with `1 references`:

**Screenshots**

<img width="233" alt="Capture d’écran 2019-06-12 à 11 27 44" src="https://user-images.githubusercontent.com/4760796/59339949-69bf2c00-8d05-11e9-8df7-fb2dd60176c4.png">

**Environment (please complete the following information):**
 - OS: OSX
 - Ionide version: Experimental version 0.3.0

**Comment by forki** [comment]
I think if you open the solution again it should show correct values. It's probably caching issue.

Related question: If stuff is not referenced anywhere (so "0 references" is actually correct) you can still click the link and it shows one reference (which is the declaration itself). Is that correct behaviour?

**Comment by Krzysztof-Cieslak** [comment]
>  If stuff is not referenced anywhere (so "0 references" is actually correct) you can still click the link and it shows one reference (which is the declaration itself). Is that correct behaviour?

It's by-design, and it's just how reference code lenses are working at the moment in 3.X (I guess no one noticed as they're turned off by default ;-) )

**Comment by MangelMaxime** [comment]
> I think if you open the solution again it should show correct values. It's probably caching issue.

Still 0

> If stuff is not referenced anywhere (so "0 references" is actually correct) you can still click the link and it shows one reference (which is the declaration itself)

Well in my example `x` is actually referenced under `test` unless I am incorrect. 

If I click on `0 references`, it shows me "No result". Unless I didn't understand what you were speaking about.

![2019-06-12 11 58 59](https://user-images.githubusercontent.com/4760796/59342183-89f0ea00-8d09-11e9-8fd1-038d983939db.gif)

**Comment by Krzysztof-Cieslak** [comment]
I can repro that, it's the same thing as #1125 - background service doesn't notice it needs to recheck the files.

Fix in progress.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/pull/405/commits/67aa79d352e660e10d72ea8a0fbdf66e7879c435

**Comment by Krzysztof-Cieslak** [comment]
Released in experimental `0.3.1`

**Comment by MangelMaxime** [comment]
Thank you, I can confirm this is now working as expected :)
