### ISSUE TITLE
Ionide 4 does not type check "downstream" files after a change to upstream was made

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1125]
If I have files a.fs and b.fs and b dependes on a type in a.

If I change and save a.fs so that it introduces a compile error in b.fs then ionide 4 does not show this anymore. This is a regression

**Comment by forki** [comment]
Even if I save b.fs again it does not show the squigglies.

Only after doing a change in b.fs (and without saving) it shows the squigglies.

**Comment by forki** [comment]
so it looks like a cache invalidation issue.

I *assume* it actually tries to typecheck the downstream file, but since it did not change it will just skip it.

**Comment by Krzysztof-Cieslak** [comment]
I think it's problem with background service not recognizing which files it need to parse. I believe it's exact same problem as #1124

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/pull/405/commits/67aa79d352e660e10d72ea8a0fbdf66e7879c435

**Comment by Krzysztof-Cieslak** [comment]
Released in experimental `0.3.1`
