### ISSUE TITLE
Rename fails for nested DUs

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1128]
The following code fails to rename the symbol `Foo` using F2 refactor with the error "overlapping ranges not allowed":

```fsharp
type Foo = string
type Bar = Baz of Foo
```
I'm not sure what the minimal repro is but it seems to be related to a DU with a rename of a type inside it.

The following snippet correctly renames `Foo` to something else.

```fsharp
type Foo = string
let x:Foo = "test"
```

**Comment by Krzysztof-Cieslak** [comment]
Is that issue in experimental or normal version?

**Comment by isaacabraham** [comment]
Normal version

**Comment by Krzysztof-Cieslak** [comment]
I can repro also on experimental.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/commit/8c18bca2511a75d63d9dabcb7c0f7341800770f7
