### ISSUE TITLE
Working with large projects ruins code completion

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#113]
## Description

When working with large projects, like Logary, code-completion and tool-tips work as long as it all compiles. After a few minutes working, breaking things as one types new code or change type declarations, the tooltips stop working, even when closing and opening the file again.

## Expected behaviour

To work

## Actual behaviour

A 'Loading...' message is displayed.

## Steps to reproduce

Start logary, hack away at a new target for a while, watch tooltips disappear.

## Other observations

Sometimes tool-tips are "off" i.e. the red squigglies are under the wrong characters (not a full symbol is underlined).

Sometimes the tool-tips take a really long time to start showing, initially.

**Comment by Krzysztof-Cieslak** [comment]
Can you try latest version? Latest FSAC / FCS version is bit faster and should handle big projects bit better

**Comment by Krzysztof-Cieslak** [comment]
Let's actually merge this issue with #127. It's probably same problem (some unexpected slowdown in FSAC / FCS) in both cases
