### ISSUE TITLE
experimental - open namespace quickfix remove lines when adding new namespace

### ISSUE THREAD

**Issue by johlrich** [ionide/ionide-vscode-fsharp#1131]
**Describe the bug**
Open namespace quickfix remove lines when adding new namespace

**To Reproduce**
Use the open namespace quickfix on the `Stream` following code

```fsharp
module Repro

open System

type Foo = { Bar: string }

let bar (s: Foo) : Stream option = None
```

The line with type Foo will vanish.

If you remove the existing open System statement and do it again, it will remove both the type Foo and module lines. 

Here's a gif too:

![ionide-experimental-open-namespace-repro](https://user-images.githubusercontent.com/1655793/59466677-e7656380-8dfb-11e9-8512-9056e98c5ed4.gif)

**Environment (please complete the following information):**
 - OS: windows
 - Ionide version: experimental
 - VSCode version: insider
 - dotnet SDK version: 3.0-preview6
 - mono / .Net Framework version: 4.0.30319.42000

**Comment by Krzysztof-Cieslak** [comment]
Fixed by 23e71193b5af50dc696ecba75587ca007f1e617f
