### ISSUE TITLE
Experimental: LineLens not working?

### ISSUE THREAD

**Issue by drk-mtr** [ionide/ionide-vscode-fsharp#1140]
Using the non-experimental branch, I can use the `"FSharp.lineLens.enabled": "replaceCodeLens"` setting in VSCode. I really like this feature as I can have LineLens enabled and CodeLens disabled (I find it really frustrating how CodeLens messes up line spacing and the code moves around the page as it finds references - just a personal thing). Unfortunately LineLens doesn't appear to work on the experimental build - CodeLens displays instead.

As an aside, the new changes you have made are utterly brilliant. Old Ionide broke things on my mac, it got so slow that VSCode couldn't keep up with the speed of me typing and was unusable. In contrast, the experimental branch is very responsive and I don't get any of these issues at all.

I also think the Info Panel view is excellent and I found it useful immediately. The "lock" functionality is a bit inconsistent for me currently, but I'm sure that'll be smoothed out in future. I know this is all a big tangent and not the appropriate place at all, but I didn't know where else to say thanks and that the recent changes are very well received!

**Comment by Krzysztof-Cieslak** [comment]
I'm glad experimental Ionide is working well :-)

LineLens support should be released in the latest experimental (0.3.5)

**Comment by drk-mtr** [comment]
Good news, thanks!
