### ISSUE TITLE
Ionide 4 "F# Generate documentation" doesn't work consistently

### ISSUE THREAD

**Issue by AkosLukacs** [ionide/ionide-vscode-fsharp#1145]
**Describe the bug**
The "F#: Generate documentation" feature doesn't work in some cases with the latest experimental version.

**To Reproduce**
Create a new console app:
`> dotnet new console -lang F#`

Open program.fs, add a function like `let boo x = x + 1`
Right-click on it, and click ""F#: Generate documentation" (or use the shortcut / command palette)
Works on `main`, but doesn't work on a newly added function.
If you add two functions, it doesn't work on the topmost, but works on the second. In a larger file, it pretty much does nothing most of the time.

**Expected behaviour**
It generates documentation stub

**Environment:**
 - OS: win 10
 - Ionide version: Latest experimental
 - VSCode version: 1.35.1
 - dotnet SDK version: 2.2.300 or 3.0.0-preview5

**Additional context**
Does work in "regular" Inoide :)

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/commit/e998b8cc26fc91b20d0ef57cd2bc469258ddde2e
