### ISSUE TITLE
Ionide doesn't find fsi Path if only dotnet core is installed

### ISSUE THREAD

**Issue by tforkmann** [ionide/ionide-vscode-fsharp#1149]
**Describe the bug**
Hi there,

if I only have dotnet core (3.0.100-preview6-012264) on my machine Ionide can't find the Fsi out of the box.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install dotnet core only
2. Create Testfile: test.fsx
3. Try to execute following lines in F# Interactive:
let a =  1
let b = a + 1

**Expected behaviour**
Ionide will check also check dotnet core path: 
For example: C:\Program Files\dotnet\sdk
and use this as Fsi command

**Screenshots**
![image](https://user-images.githubusercontent.com/4168951/60024866-df79af00-9698-11e9-85b9-498ff1ebf102.png)

**Environment (please complete the following information):**
 - OS: Win 10
 - Ionide version: lastest experimental Version
 - VSCode version: 1.35.1
 - dotnet SDK version: 3.0.100-preview6-012264
 - mono / .Net Framework version:

**Comment by Krzysztof-Cieslak** [comment]
Support for `dotnet fsi` can be enabled by setting `FSharp.useSdkScripts`
