### ISSUE TITLE
Feature Request: command to restart language service

### ISSUE THREAD

**Issue by ntwilson** [ionide/ionide-vscode-fsharp#1150]
Sometimes Ionide fails to detect changes in other projects or files, probably similar to [#1143](https://github.com/ionide/ionide-vscode-fsharp/issues/1143), though I've also witnessed the problem when the changes are to a file within the same project.  It seems intermittent to me; at least I haven't discovered a reliable way to reproduce it.  

I propose that a command is added to the VS Code command palette to restart the F# language service, so that changes can be manually reloaded conveniently.  I've noticed the same issue of the IDE getting out-of-sync with the code files when using other language plugins, and the severity of the issue is drastically reduced when there's a simple way to reload.

The only workaround that I know of is to close VS Code and reopen it.  I thought that perhaps the "F#: Clear Cache" command would have the desired effect, but it must do something else.  I can't discern any noticeable change to anything when I clear the cache.

Also, thanks for all the hard work.  Ionide is amazing!

**Comment by matthid** [comment]
Any reason why you are not using the `Reload Window` command?

**Comment by ntwilson** [comment]
The biggest reason is that I didn't know about it :).  Thanks for the tip!  That's a far better solution than what I was doing.  Feel free to close this issue.
