### ISSUE TITLE
Special character in path breaks tooling

### ISSUE THREAD

**Issue by CallumVass** [ionide/ionide-vscode-fsharp#1151]
**Describe the bug**
Hi, I upgraded Ionide to version 4 today and since then I've lost all intellisense, errors and the greyed function signature text that used to appear

**To Reproduce**
Steps to reproduce the behaviour:
1) Create fsx file
2) Open in VS Code
3) Create some functions / modules

**Expected behaviour**
I'd usually expect to have intellisense, errors and other such features

**Screenshots**
![image](https://user-images.githubusercontent.com/2204920/60044387-262bd100-96ba-11e9-868b-8b7c63bf44aa.png)

**Environment (please complete the following information):**
 - OS: Windows 
 - Ionide version: 4
 - VSCode version: 1.35.1
 - dotnet SDK version: 2.2.104
 - mono / .Net Framework version: 4.5.1

**Additional context**
I've uninstalled VS Code and deleted my extensions folder in user profile and re-installed VS Code and Ionide extension but that doesn't seem to have worked either.

If you can tell me where the logs are kept I can upload them as well, I couldn't find anywhere in the documentation of where they're kept?

**Comment by CallumVass** [comment]
Hi, I've figured it out. I don't know if this is a bug or not but my file was in a folder called "f#". Renaming the folder to "fsharp" fixed the problem so I don't know if this is an issue with having a hash (#) in the folder name or not?

**Comment by baronfel** [comment]
This sounds like a file uri normalization issue @Krzysztof-Cieslak

**Comment by Krzysztof-Cieslak** [comment]
@baronfel: Aweeeesome ..... -_-

**Comment by baronfel** [comment]
I can dig a bit later today

**Comment by baronfel** [comment]
I made a folder on my system called `f#test` at the path `/Users/chethusk/oss`, with an fsx file in it.

The message I see sent to the LSP server has the URI `file:///Users/chethusk/oss/f%23test`.

Let's do some exploration:

```fsharp
> let testUri = System.Uri "file:///Users/chethusk/oss/f%23test";;
val testUri : System.Uri = file:///Users/chethusk/oss/f%23test

> testUri |> string |> System.Net.WebUtility.UrlDecode;;     
val it : string = "file:///Users/chethusk/oss/f#test"

> let normalizedUri = System.Uri "file:///Users/chethusk/oss/f#test";;
val normalizedUri : System.Uri = file:///Users/chethusk/oss/f#test

> normalizedUri.LocalPath;;
val it : string = "/Users/chethusk/oss/f"
```

Well crap.

**Comment by baronfel** [comment]
Anyway this is in FSAC so we need to handle it there.

**Comment by beyon** [comment]
Am I also seeing the same FSAC issue or might it be another one? (if another one I could create a new issue)

![bild](https://user-images.githubusercontent.com/3542167/71898107-bf06d300-3158-11ea-8538-8d74ab0ebb67.png)

Project created with mini-scaffold template in subdirectory of user directory containing non-ascii characters, 'ö' seems to be mangled. Errors are listed in the "Problems" window but no errors/warnings shown in editor and clicking the listed errors result in the shown "Unable to open..." dialog.

### Machine infos

* Operating system: **Windows 10**
* Ionide: **4.4.2**
* Arch: **x64**
* VSCode: **1.41.1**
* Runtime: **netcore**
* Dotnet version: **3.1.100**
* MSBuild version:
```shell
Microsoft (R) Build-motor version 4.8.3752.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. Med ensamr�tt.
```

**Comment by Krzysztof-Cieslak** [comment]
It seems to be working correctly in Ionide 5.0
