### ISSUE TITLE
Add file above and sub folders 

### ISSUE THREAD

**Issue by SCullman** [ionide/ionide-vscode-fsharp#1155]
**Describe the bug**
_Add file above_ and _Add file below_ doesn't support folders.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new project
2. Within Explorer, add a new file "manual.fs" in a folder "folder" 
3. Add ``<Compile Include="folder/manual.fs" />`` to your fproj file.
4. Switch to "F#" and use _Add File above_ to add a file "new.fs" above "manual.fs"

**Expected behaviour**

The file "new.fs" is created in the folder "folder" and added to the project

**What happens instead**
File "new.fs" is added in the root of the project. It is not added to the project.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.0.0
 - VSCode version: 1.35.1

**Comment by faldor20** [comment]
i am having this same issue. it seems in all cases where ionide should edit fsproj on my laptop it simply will not work. it does however work fine on my other computer.

**Comment by faldor20** [comment]
Actually @SCullman i found the solution. if i went to the vscode output tab (down near console) and select forge i saw that when i added a file it came up with an error message complaing about not having dot-net core 2.1 i installed it form here( just the release version) https://dotnet.microsoft.com/download/dotnet-core/2.1 and now it is sorted.

To the ionide team: maybe either make forge work for dotnet core 3.xx or make a note that it requires 2.1.
