### ISSUE TITLE
Empty file does not get intellisense

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1156]
In Code, I have it configured so that new files automatically default to F#, even without saving. In Ionide 4, if you create a new file that's not saved, you get no intellisense or anything. You have to first save the file and then Ionide kicks in.

This is confusing for newcomers because it appears as though Ionide simply isn't working, and also (I believe) is a regression from v3.

**Comment by Krzysztof-Cieslak** [comment]
Yes, it sounds like a regression.

**Comment by isaacabraham** [comment]
Can confirm that this is still active in most recent release (4.4.4)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `4.4.5`
