### ISSUE TITLE
Compile error in VS code but not when CLI commands are run outside Ionide

### ISSUE THREAD

**Issue by leolorenzoluis** [ionide/ionide-vscode-fsharp#1157]
When fsx files are used in VS Code

**To Reproduce**
Steps to reproduce the behaviour:
```
#r "packages/Deedle/lib/netstandard2.0/Deedle.dll"

open Deedle


let msftCsv = Frame.ReadCsv(__SOURCE_DIRECTORY__ + "/data/stocks/MSFT.csv")
let fbCsv = Frame.ReadCsv(__SOURCE_DIRECTORY__ + "/data/stocks/FB.csv")

```
**Expected behaviour**
It should display the correct type and not squiggle with red line

**Screenshots**

<img width="518" alt="Screen Shot 2019-06-27 at 9 12 00 PM" src="https://user-images.githubusercontent.com/15150044/60310299-35ac5380-9920-11e9-8082-7977e5cf31a3.png">

**Environment (please complete the following information):**
 - OS:  OSX
 - Ionide version: 4.0
 - VSCode version: 1.35.1
 - dotnet SDK version: 2.2.300
 - mono / .Net Framework version: Mono 5.16.0.221

**Comment by Krzysztof-Cieslak** [comment]
Outdate isse.
