### ISSUE TITLE
"No typecheck results" in .fsx referencing .fs file with #load directive outside of project

### ISSUE THREAD

**Issue by ivoh** [ionide/ionide-vscode-fsharp#1158]
When .fxs file is referencing .fs file with #load directive it shows "No typecheck results|No typecheck results" in the codelens instead of type informations. If it references .fsx file it works correctly (i.e. shows types).  This behaviour is only present using ionide outside of f# project.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create files:
Sandbox1.fsx
```
let i = 5

let add a = a + 2

#load "lib1.fsx"
```

Sandbox2.fsx
```
let i = 5

let add a = a + 2

#load "lib2.fs"
```

And empty files lib1.fsx, lib2.fs

Files are also attached in [FSharp.zip](https://github.com/ionide/ionide-vscode-fsharp/files/3341683/FSharp.zip)

2. Open Sandbox1.fsx and inspect the codelens behaviour
2. Open Sandbox2.fsx and inspect the codelens behaviour

**Actual Behaviour**
Codelens does not show type information related to the variable i, and add function in Sandbox2.fsx. It shows "No typecheck results|No typecheck results"  instead.but shows the type information in Sandbox1.fsx.

**Expected behaviour**
Codelens should show type information related to the variable i, and add function in both Sandbox1.fsx and Sandbox2.fsx the same way as it works in Sandbox1.fsx.

**Screenshots**
![image](https://user-images.githubusercontent.com/601157/60381740-e9652e80-9a59-11e9-9276-157bf4f56cd4.png)

![image](https://user-images.githubusercontent.com/601157/60381744-f2560000-9a59-11e9-8d9d-a3fd49d25184.png)

When .fs file is opened bottom status bar shows a message "Not in F# project (still loading)" even after few minutes. If there is any code in the .fs file the Codelens works correctly there, i.e. shows type information without issues.
![image](https://user-images.githubusercontent.com/601157/60381814-e454af00-9a5a-11e9-9cc4-e6b8aab57413.png)

**Environment (please complete the following information):**
 - OS: windows 10.0.17763
 - Ionide version: 4.0.0
 - VSCode version: 1.35.1
 - dotnet SDK version: 2.2.104
 - mono / .Net Framework version: .NET Framework 4.7.3190.0

**Additional context**
Hopefully this not a new behaviour by design. This used to work. I was happily using it like this for scripting purposes.

**Comment by thinkbeforecoding** [comment]
Getting this also. It seems to stop all ionide from working.. for instance even fsi.Start is not available anymore. It looks like it's failing very early during extension loading.

**Comment by Krzysztof-Cieslak** [comment]
Pretty sure this is duplicate of #669. Closing in favour of old issue.
