### ISSUE TITLE
Suggest additions to .gitignore for .ionide and .fake folders

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1159]
**Is your feature request related to a problem? Please describe.**

It comes up semi-frequently that the .ionide and .fake folders should be ignored, but users have to add them to ignore files for each project.  It would be nice if Ionide would prompt to add those lines if they aren't present.

**Describe the solution you'd like**

On startup:

* read .gitignore (if present, if not do nothing)
* if certain key patterns (ie `.ionide` and `.fake` to start with) are not present in the file, raise a message box with text like: 
> would you like to add ionide-specific folders to your .gitignore? Yes | No

and on click of 'Yes' add those lines to the .gitignore.

**Describe alternatives you've considered**

Users can add the patterns to global gitignores, but then they don't belong to the repo and other users will hit the same issues.

**Additional context**

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #1163
