### ISSUE TITLE
Info Panel: generic parameters closing '>' isn't included in type link

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1164]
**Describe the bug**
Here's the display for the info panel on the `Char` struct:

![image](https://user-images.githubusercontent.com/573979/60446219-8e147700-9be6-11e9-80b2-bc867edd452d.png)

Note here that the rightmost `>` of the generic type signature isn't a link the same way that the rest of the text is.

**To Reproduce**
Steps to reproduce the behaviour:
1. `let c: char = 'c'`
2. display Info Panel for the type `char` on that line^
3. See error

**Expected behaviour**
The rightmost `>` is a link that points to the same location as the rest of the generic-type container. Eg for `IComparable<char>`, the link should point to the docs for `IComparable<'t>`, not `char`.

**Environment (please complete the following information):**
 - OS: MacOS Mojave (10.14.5 (18F132))
 - Ionide version: 4.0
 - VSCode version: normal, june update
 - dotnet SDK version: N/A
 - mono / .Net Framework version: N/A

**Comment by Krzysztof-Cieslak** [comment]
Literally unusable 😝

**Comment by 7sharp9** [comment]
This is an FSAuto issue as the construction go the link is in there.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `4.2.0`
