### ISSUE TITLE
not and new are breaking highlighting

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1166]
@MangelMaxime HALP!

![image](https://user-images.githubusercontent.com/57396/60708491-79015600-9f0e-11e9-9571-35aa6d0e098c.png)

**Comment by MangelMaxime** [comment]
According to my test it's only the `newSomething` that's breaking the synthax. 

In your example, the breaking point is on line 133 see the coloration of `newMeterIsFullyReaded`

A fix is waiting to be released: https://github.com/ionide/ionide-fsgrammar/pull/136

Sorry for the inconvenience.

**Comment by forki** [comment]
ah ok. thx

**Comment by forki** [comment]
closing as dupe
