### ISSUE TITLE
No autocompletion on Windows 10 starting with version 4.0.0

### ISSUE THREAD

**Issue by cerk** [ionide/ionide-vscode-fsharp#1169]
**Describe the bug**
If I install Ionide-fsharp 4.0.0 or greater on Windows 10, autocompletion breaks for Fsac Runtime: netcore.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Ionide-fsharp 4.0.0.
2. Create any netcore project.
3. There is no autocompletion when editing .fs files in the project.

**Expected behaviour**
I expected autocompletion to work for the netcore project.

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Ionide version: 4.0.0+
 - VSCode version: 1.36.0
 - dotnet SDK version: 2.2.101
 - mono / .Net Framework version: 4.7.2

**Additional context**
In the Output --> F# window, I get the following:
```
[Error - 4:43:26 PM] Request textDocument/completion failed.
  Message: no type check results
  Code: -32603 
```
If I downgrade to Ionide version 3.38.0, the problem is not present and there is normal looking output in Ouput --> F# Language Service.
If I use Linux instead of Windows, the problem is not present.

**Comment by Krzysztof-Cieslak** [comment]
Does absolute path to the file contain any special characters? (https://github.com/ionide/ionide-vscode-fsharp/issues/1151)

**Comment by cerk** [comment]
> Does absolute path to the file contain any special characters? (#1151)

Yes it does: "f#". My Linux machine has the same folder structure but it is named "fs". When I change the Linux folder to "f#" I can reproduce the problem. So this is a duplicate of [#1151](https://github.com/ionide/ionide-vscode-fsharp/issues/1151). Sorry for wasting your time.
