### ISSUE TITLE
"Wrong template name" returned when "fsunit" chosen as template

### ISSUE THREAD

**Issue by EdouardM** [ionide/ionide-vscode-fsharp#117]
Copy from issue #120 in fsprojects/Forge

When using command "F# new" in VScode, I select "fsunit" as template.

I put test as directory and test as project name. Forge builds the following command:
forge new project -n test -t fsunit --folder test --no-prompt

I should have a test project with NUnit & FSunit installed under directory

## Current Behavior

Forge sends a notification "Project created"

But Forge output window returns:
"Wrong template name"

## Possible Solution

Fix template name in code

## Steps to Reproduce (for bugs)

    "F# new" in VScode
    Select FsUnit
    Input test as directory
    Input test as project name

## Your Environment

    Version used:
    F# 4.0
    VSCode 1.3.1
    Ionide 2.2.7
    Windows 10

**Comment by Krzysztof-Cieslak** [comment]
Fixed
