### ISSUE TITLE
How to debug FSAC with Ionide 4?

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1171]
@Krzysztof-Cieslak

Could you please update the `CONTRIBUTING.md` guide with the instruction for using a local version of FSAC in LSP mode?

I want to work on the documentation generation and tooltip highlights but I don't know anymore how to setup FSAC :)

**Comment by Krzysztof-Cieslak** [comment]
There is `FSharp.fsac.netCoreDllPath` which you can use to point Ionide into custom FSAC dll

**Comment by MangelMaxime** [comment]
Thank you, I will give it a try :)

**Comment by matthid** [comment]
The easiest is to use this on a particular test workspace and on you bin/debug folder of fsac. Works well for me

**Comment by MangelMaxime** [comment]
It also requires a global version of FAKE installed.
