### ISSUE TITLE
Ionide reports Fable projects as load errors

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1172]
**Describe the bug**

When I open a project that uses fable then the ionide is reporting "project loading failed" errors:

![image](https://user-images.githubusercontent.com/57396/60877249-c139b480-a23d-11e9-811d-20cdcea54307.png)

After inspection I see that this is not one of my real projects, but some Fable dependency that we got fromt NuGet:

![image](https://user-images.githubusercontent.com/57396/60877187-994a5100-a23d-11e9-9f47-91c0ed286266.png)

**Expected behaviour**

I think we can ignore these!? @MangelMaxime @alfonsogarciacaro

**Comment by MangelMaxime** [comment]
Yes, I think it can be ignored.

The question is why is Ionide, looking for a `fsproj` in the nuget folder 🤔

**Comment by Krzysztof-Cieslak** [comment]
Cc: @enricosada

**Comment by forki** [comment]
Workaround: using `storage:none` with Paket

**Comment by enricosada** [comment]
I can repro with https://github.com/fable-compiler/fable2-samples/tree/master/withpaket without `storage: none`

i think it's the `load all fsproj in FSAC`, when there is no `.sln`
by default `packages` is not excluded in the search.

another workaround

```json
    "FSharp.excludeProjectDirectories": [
		".git",
		"paket-files",
                ".fable",
                "packages",
		"node_modules"
	],
```

**Comment by Krzysztof-Cieslak** [comment]
We should add that to default I guess

**Comment by enricosada** [comment]
Yes, fsproj shouldn’t matter in packages for at discovery time, like in paket-files

From mobile

--
Enrico Sada
@enricosada
________________________________
Da: Krzysztof Cieślak <notifications@github.com>
Inviato: Tuesday, July 9, 2019 2:21:51 PM
A: ionide/ionide-vscode-fsharp
Cc: Enrico Sada; Mention
Oggetto: Re: [ionide/ionide-vscode-fsharp] Ionide reports Fable projects as load errors (#1172)


We should add that to default I guess

**Comment by Krzysztof-Cieslak** [comment]
Fixed with https://github.com/ionide/ionide-vscode-fsharp/commit/1c49b20f3c1dfe62a9c20beebd91e12b47f8021e

**Comment by whitetigle** [comment]
I don't know if it's the same error but it looks like on my windows machine: all projects are listed  

![image](https://user-images.githubusercontent.com/883207/80952453-fbda9200-8df9-11ea-9b39-4356b359e14c.png)

with error message related to some projects

![image](https://user-images.githubusercontent.com/883207/80952503-0d239e80-8dfa-11ea-9bb8-4683c2bd5670.png)

ionide v 4.10.1

**Comment by Krzysztof-Cieslak** [comment]
@whitetigle, have you tried cleaning cache with `F#: Clean Cache` and then reloading again? Another thing i'd try would be removing bin and obj dirs for each project, and then opening Code again.

**Comment by whitetigle** [comment]
ok. it's working. Thanks! 👍
