### ISSUE TITLE
Can't rename a file

### ISSUE THREAD

**Issue by drguildo** [ionide/ionide-vscode-fsharp#1173]
**Describe the bug**
I can't rename a file using the "Rename file" menu entry in the F# Solution Explorer.

**To Reproduce**
Steps to reproduce the behaviour:
1. Right click on a file
2. Select "Rename file"
3. Type in a different name for the file
4. Nothing happens

**Expected behaviour**
The file to be renamed.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.10
 - Ionide version: 4.0.4
 - VSCode version: 1.36.0
 - dotnet SDK version: 2.2.300

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce in `4.4.5`

**Comment by bradphelan** [comment]
I have Ionide-fsharp 4.7.0 and I can't rename files in my project. 

I try to rename the highlighted file from XOReport.fs to Report.fs and it doesn't do anything

![image](https://user-images.githubusercontent.com/17650/76730787-40cc3b80-675c-11ea-97e7-95d73801bbc9.png)

![image](https://user-images.githubusercontent.com/17650/76730805-49247680-675c-11ea-8843-aed4b6639802.png)
![image](https://user-images.githubusercontent.com/17650/76730823-5477a200-675c-11ea-8bcd-31c9a542aad5.png)

![image](https://user-images.githubusercontent.com/17650/76730868-6eb18000-675c-11ea-937a-63b2d6f97458.png)

![2020-03-16_08-01-56](https://user-images.githubusercontent.com/17650/76730911-825ce680-675c-11ea-8120-fce2f5cde5d3.gif)
