### ISSUE TITLE
Wrong highlighting around 'a

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1174]
![image](https://user-images.githubusercontent.com/57396/60971765-2caa8180-a325-11e9-9c12-b2ee32887a4f.png)

Not sure what causing this.

/cc @MangelMaxime

**Comment by forki** [comment]
look at updateRecords the prefix parameter has wrong color and the let! is also weird

**Comment by MangelMaxime** [comment]
Can you please provide a textual representation of your code?

**Comment by MangelMaxime** [comment]
The bug about `prefix` has been created by this fix: https://github.com/ionide/ionide-fsgrammar/pull/126

**Comment by MangelMaxime** [comment]
I have a fix ready for the bug about `prefix`

I am not able to repro the `let!` bug. I will wait for the textual representation of the code so I can copy/paste the whole block.

**Comment by forki** [comment]
let inline updateRecords<'a> prefix chunkSize (webAccessF:Environment.AccessConfig -> Fable.Core.JS.Promise<'a []>) distinctF (config:Environment.AccessConfig) = promise {
        let! newRecords = webAccessF config
        if Array.isEmpty newRecords then
            return 0
        else
            let! oldRecords = getAllChunksForEnv<'a> prefix config
            let records =
                Array.append oldRecords newRecords
                |> Array.distinctBy distinctF

            do! saveInChunks<'a> prefix chunkSize config records
            return newRecords.Length - oldRecords.Length
    }

**Comment by forki** [comment]
smaller repro:

    let inline updateRecords<'a> prefix = promise {
        let! newRecords = prefix
        return newRecords
    }

**Comment by MangelMaxime** [comment]
I can confirm that the bug on `prefix` is fixed.

**Before**
<img width="433" alt="Capture d’écran 2019-07-11 à 09 11 59" src="https://user-images.githubusercontent.com/4760796/61029759-071c8700-a3bc-11e9-9452-1b11577b4dfe.png">

**After**
<img width="404" alt="Capture d’écran 2019-07-11 à 09 12 03" src="https://user-images.githubusercontent.com/4760796/61029757-071c8700-a3bc-11e9-9a68-1f18e3570b62.png">

However, I don't have problem with `let!` highlights I tried 10 themes to check and no problem even with current version of VSCode 1.36.0

Do you have the `let!` problem if you use your smaller repro? Do you have this problem, in an empty file?

**Comment by forki** [comment]
This is a smaller repro from the first issue in that file:

![image](https://user-images.githubusercontent.com/57396/61030653-1dc3dd80-a3be-11e9-97e8-ef2ebad166ce.png)

    let f  x y =
        promise {
            do! x

            let syncImages = new System.Collections.Generic.List<_>()

            do! x
            return ()
    }

**Comment by MangelMaxime** [comment]
Thank you I can repro the bug for `do!` now. It's a problem with `new` I will take a look

**Comment by MangelMaxime** [comment]
It's already fixed in master branch of https://github.com/ionide/ionide-fsgrammar/

**Comment by forki** [comment]
all fixed! even the let! issue. thanks!
