### ISSUE TITLE
LineLense not displaying function signature

### ISSUE THREAD

**Issue by vmendivil** [ionide/ionide-vscode-fsharp#1182]
**Describe the bug**
When trying to enable LineLense, signatures are not displayed. I already tried several combinations, enabling and disabling CodeLens as well and still not working.

**To Reproduce**

Background Services is enabled.
Enable reference code lens is enabled.

I also noticed that in some cases it works and is some others it doesn't based on the lenght of the file. Attached a document with both cases, the file is the same, first case is the full file, not working, second section is a shorter version of the very same file and it works:

[Working and not working.docx](https://github.com/ionide/ionide-vscode-fsharp/files/3392892/Working.and.not.working.docx)

Scneario 1:
![Case 1](https://user-images.githubusercontent.com/20627825/61223145-18ca9b00-a6ea-11e9-9f19-95734632a662.PNG)

Scneario 2:
![Case 2](https://user-images.githubusercontent.com/20627825/61223228-4879a300-a6ea-11e9-9284-c703f5df665d.PNG)

Scenario 3:
![Case 3](https://user-images.githubusercontent.com/20627825/61223332-6f37d980-a6ea-11e9-8c2f-0da3845d17d9.PNG)

Plugins installed: I removed a bunch of plugins for testing at a point that ionide was the only one. Then I just installed the minimum I need for now:

![Plugins](https://user-images.githubusercontent.com/20627825/61223650-161c7580-a6eb-11e9-9815-a3bc2434d75d.PNG)

VS Code User configuration:

{
    "FSharp.smartIndent": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "gitlens.currentLine.enabled": false,
    "git.confirmSync": false,
    "editor.renderIndentGuides": false,
    "git.autofetch": true
}

**Expected behavior**
Signature should be displayed in the same next to the function declaration.

**Environment (please complete the following information):**
 - OS: Win 10
 - Ionide version: 4.0.6
 - VSCode version: 1.36.1
 - mono / .Net Framework version: 4.7.2

**Additional context**
Two week ago it was working, last week at some point stop working but didn't paid much attention to it and I'm not sure what version was installed when stop working.

**Comment by jfrank-summit** [comment]
I was having same problem. Finally started from scratch with fsx file and it worked. slowly added back code and for some reason when I use TypeShape it breaks, any ideas?

**Comment by vbfox** [comment]
@vmendivil  I tried on your sample file (in the docx) and can't reproduce, copy pasting in an fsx file give LineLens so there is something more creating the bug.

If there is an error in the developer tools view of vscode it would be really useful (Or some more specific setting you suspect are creating the problem)

**Comment by ronaldschlenker** [comment]
Same issue here.

There are error log message in the F# output:

```
[Error - 11:38:09] Request textDocument/documentSymbol failed.
  Message: File 'c:\temp\test.fsx' not parsed
  Code: -32603 
[Error - 11:38:15] Request textDocument/documentHighlight failed.
  Message: No symbol information found
  Code: -32603 
```

My test.fsx looks like this:

```fsharp
let x = "34"
type T = Hurz
```

F# config:

```
    "FSharp.saveOnSendLastSelection": true,
```

Extension infos:

```
Name: Ionide-fsharp
Id: ionide.ionide-fsharp
Description: F# Language Support
Version: 4.0.6
Publisher: Ionide
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp
```

No line lens or code lens, but hovering over symbols shows correct tooltip infos.

**Comment by vmendivil** [comment]
Hey @vbfox 

I just resume this today and I kind of get use to work again without the quick references of the signature in VSCode.

I tried to reproduce the issue in a different laptop and I get the same results.

![image](https://user-images.githubusercontent.com/20627825/65073920-c4e66780-d961-11e9-85ad-492d78b5d7a7.png)

In a fsx, if you copy the full code, it won't display the signature as in Scenario 1, if you delete all the code from line 22 up to the end of the file, it will start displaying the signature of the function.

Code with code beyond line 22:
![image](https://user-images.githubusercontent.com/20627825/65074816-91a4d800-d963-11e9-9e6e-260744b245ca.png)

Code without code beyond line 22:
![image](https://user-images.githubusercontent.com/20627825/65074848-a4b7a800-d963-11e9-97d2-d41ce81d314d.png)

Ass soon as I delete code beyond line 22, function signature appears on the editor.

Not sure if this is the log file you need but I see a bunch of errors related to ionide.

![image](https://user-images.githubusercontent.com/20627825/65074612-3246c800-d963-11e9-87ba-ebd96de86f83.png)

![image](https://user-images.githubusercontent.com/20627825/65074660-468ac500-d963-11e9-8b96-addcfeb75af6.png)

Console log: 
[Console log.txt](https://github.com/ionide/ionide-vscode-fsharp/files/3623154/Console.log.txt)

Hope that helps, let me know if I can provide anything else.

**Comment by Krzysztof-Cieslak** [comment]
Can't repro on `4.4.5`
