### ISSUE TITLE
Ionide omits "Microsoft" from fully qualified namespaces

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1186]
Ionide seems to be ommitting Microsoft from FQ namespaces e.g. instead of `Microsoft.AspNetCore.Hosting.IWebHostBuilder` we just get `AspNetCore.Hosting.IWebHostBuilder`. This is confusing; I would expect it to show fully-qualified namespaces in code lenses and tooltips.

![image](https://user-images.githubusercontent.com/1781813/62154750-4f65ff80-b2ff-11e9-88fb-c0f58f286d0e.png)

**Comment by matthid** [comment]
I wouldn't wonder if this would be a compiler bug...

**Comment by matthid** [comment]
I saw similar stuff and the one time I could reproduce I reported it here: https://github.com/dotnet/fsharp/issues/6043

**Comment by matthid** [comment]
Sadly, as you can see from the date, these kinds of bugs never actually get fixed. Not even in the compiler ;)

**Comment by forki** [comment]
Pretty sure it's FCS bug

**Comment by Krzysztof-Cieslak** [comment]
Folks, it's obvious - It's a feature driven by our hate of MSFT

**Comment by forki** [comment]
Should replace every occurrence with Micro$oft666

**Comment by matthid** [comment]
@forki why fcs? the linked report doesn't involve fcs (but still it got the fcs area tag for some reason)..

**Comment by matthid** [comment]
> Folks, it's obvious - It's a feature driven by our hate of MSFT

So the fix is that 'Microsoft.' prefix should be optional everywhere in F#...

**Comment by Krzysztof-Cieslak** [comment]
Closing - it's an issue in the FCS/F# compiler
