### ISSUE TITLE
Ionide sometimes hangs loading C# projects in a mixed C#/F# solution

### ISSUE THREAD

**Issue by ntwilson** [ionide/ionide-vscode-fsharp#1187]
**Describe the bug**
I have a mixed C#/F# solution, all projects using the msbuild 15 format (created with `dotnet new`), but all targeting net471 only.  Most of the time Ionide works great, but occasionally Ionide will become nonfunctional (no intellisense popups, no code lens, etc.).  When opening the F# solution explorer, I can see "(loading...)" next to all C# projects, but F# projects appear to have loaded fine.  Intellisense is not available even on F# projects that don't depend on any C# projects.  Nothing is logged to the Output window.  Once in this state, it's very difficult to get Ionide to recover.  I've tried rebuilding the solution, reloading VS Code, disabling/enabling the extension, clearing the Ionide cache, deleting the .ionide folder in my workspace, and deleting all the contents of \AppData\Roaming\Code\User\workspaceStorage, but the problem does not disappear.  The only thing that I have found to work is to downgrade Ionide to v 3.x, let it (successfully) load all of the C# projects, and then upgrade again to v 4.x.

**To Reproduce**
I have had very little luck reproducing this reliably or reproducing it in a minimal solution that I can post on GitHub, and I can find no one else experiencing the same issue, so I'm assuming I must have something peculiar in my project setup that is mostly unique to me.  I have not been able to discover any particular actions that cause the problem to surface.

**What I'm mostly hoping to get here is any idea of what cached files I should delete (or other steps that I might take) to get Ionide to recover without having to downgrade and reupgrade.**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.0.6
 - VSCode version: 1.36.1 (user setup)
 - dotnet SDK version: 2.2.401
 - mono / .Net Framework version: net471

**Additional context**
When experiencing the problem, sometimes when opening VS Code I can briefly see "(load failed)" next to the C# project highest(?) in the dependency hierarchy (other C# projects depend on it, but it doesn't depend on other C# projects).  This lasts on the screen for a fraction of a second and then it reverts to the "(loading...)" message.

**Comment by Krzysztof-Cieslak** [comment]
CC: @enricosada

**Comment by theimowski** [comment]
I'm experiencing similar issue here - ionide will usually hang in "Project loading..." state for C# project

**Comment by ntwilson** [comment]
I've turned on the verbose logging.  It's a bit difficult to parse because it seems like it's stuck in an infinite loop parsing the same projects over and over again.  2000+ lines in, I get this:
```
[LSP] Notify - Workspace
  (ProjectError
     (GenericError
        ("<path to first .csproj file in the dependency tree>",
         "Project file '<path to first .csproj file in the dependency tree>' parsing failed")))
```
Those are the only 2 occurrences of the word "error" anywhere in the log.  (Well, as far as I let it run.  I killed it after 68000 lines).  I can post the entire log if that's of any help.

The particular .csproj file it complains about looks like
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <LangVersion>8.0</LangVersion>
    <NullableContextOptions>enable</NullableContextOptions>
    <!-- NullableContextOptions was renamed to Nullable, and as of 2019-07-30, dotnet build supports one and Visual Studio supports the other.  
         We should delete NullableContextOptions when we can -->
    <Nullable>enable</Nullable>
    <DocumentationFile>bin\$(Configuration)\net471\$(AssemblyName).XML</DocumentationFile>
    <!-- warns when a public member is missing an XML comment, warns when some params have XML comments and others don't -->
    <NoWarn>1591;1573</NoWarn>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="<path to one of my .fsproj files>" />
    <ProjectReference Include="<path to one of my .fsproj files>" />
    <ProjectReference Include="<path to one of my .fsproj files>" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by ntwilson** [comment]
This issue seems to have altered a bit since 4.0 for me.  Now Ionide will not load any type info at all, as opposed to working for awhile and then breaking.  But on the plus side, it seems to have become no longer intermittent, but consistently fails, and opening VS Code to a particular project folder instead of the whole solution works without having to do anything drastic to Ionide, so it's not difficult to recover from.  Looking at the verbose logs, it still appears to be stuck in an infinite loop.

Since I can't open my solution folder in VS Code though, I've been stuck on Ionide v 3.38 since this issue started popping up.  I've had a terrible time trying to reproduce it in an open-source repo, until I finally just copied my entire project structure and removed all the code.  I've been able to reproduce the problem consistently in https://github.com/ntwilson/FS-CS-mixed-solution though I haven't been able to come up with a more minimal solution to reproduce it.  I believe it can only be reproduced on windows since it targets net471.
Steps to reproduce (from the root folder of the repo):
1) `paket restore` (or `.paket/paket.exe restore`)
2) `dotnet build`
3) `code .`
4) open SystemTests/Lib.fs, observe that ionide can't load any type info.

(reproduced with Ionide 4.3.2.  Ionide related settings in my settings.json:
```
  "FSharp.disableInMemoryProjectReferences": true,
  "FSharp.fsacRuntime": "net",
  "FSharp.lineLens.enabled": "never",
  "FSharp.showExplorerOnStartup": false,
  "FSharp.linter": false,
  "FSharp.minimizeBackgroundParsing": true,
  "FSharp.verboseLogging": true,
  "FSharp.disableFailedProjectNotifications": true,
```
it looks like not all of these are still recognized...)

Is this still the right github issue to track this or would a new issue be more appropriate since the original description doesn't seem to apply anymore?

**Comment by ntwilson** [comment]
Is this still the right github issue to track this or would a new issue be more appropriate since the original description doesn't seem to apply anymore?

**Comment by da9l** [comment]
I've seen this too. I'll see if I can create a minimal case that exposes this bug.

**Comment by Krzysztof-Cieslak** [comment]
Sample project: https://github.com/da9l/minimalFailingMixedSln4Ionide

**Comment by da9l** [comment]
I'm a supporter via opencollective. What requirements must be fulfilled for the issue to get the "backer" label?

**Comment by ntwilson** [comment]
FWIW, I've worked around this issue.  This is all anecdotal, but it _seems_ to me as if it just takes exponentially longer to load based on how many C# projects you have _and_ how much F# code you have.  Looking at the logs, it appears to me as if it loads each F# project many times per C# project or something like that (I would see files from the same F# project being processed over and over and over again, seeming in an infinite loop).  The resolution in my case (besides sticking with Ionide v 3.38) was to consolidate all my C# code into just 2 projects, and then the loading time is reasonable.  I know it's not feasible for every mixed solution to consolidate the C# code into fewer projects, but that could be a potential workaround.

**Comment by Krzysztof-Cieslak** [comment]
This should be now better with the project parsing improvements we've made in the last few weeks.
