### ISSUE TITLE
Edits to projects linked through ProjectReference in .fsproj and edited in another VSCode window are not visible

### ISSUE THREAD

**Issue by anchann** [ionide/ionide-vscode-fsharp#1188]
**Describe the bug**
Say we have code sharing set up via separate F# projects, "apps" for leaf node executables, and "libs" for bundles of shared code. Let's say a leaf node app, App, has an `App.fsproj` file containing the following line:

```
    <ProjectReference Include="../../LibSomething/src/LibSomething.fsproj" />
```

For our dev experience, we edit each project in a separate VSCode window (lest it grinds down to a halt trying to parse all the apps and libs in a single window). We have two VSCode windows, one for the App, and one for LibSomething.

A change to something (say a function return type) in LibSomething will not visible in the App VSCode window, unless we edit and save `App.fsproj`.

This introduces frustrating slowdowns and uncertainty into the dev cycle — what appears like an error in VSCode may not in fact be an error, and there's no deterministic way to tell how "in sync" the linked projects are. Even editing and saving the `.fsproj` file triggers a reload, but it happens behind the scenes, sometimes taking a few minutes, with no progress indicator, so you sit there and wait, momentum brought down to zero.

I consider this a bug and not a feature request, since a reasonable user unfamiliar with LSP internals would expect changes to be visible across multiple windows.

**To Reproduce**
Steps to reproduce the behaviour:
Set up two projects as in the description. Should be fairly obvious. If not, I can write up really detailed steps or create a sample repo.

**Expected behaviour**
An edit in a linked project (LibSomething) should be visible in current project (App). If Ionide is using Language Server Protocol, I imagine that to get this working, some kind of shared instance of service (or a singleton document store shared between multiple instances of the language service... though this gets trickier, since the filesystem is a singleton, but editor windows aren't and it's plausible that the same file will be opened in multiple windows...) that works cleanly with multiple VSCode windows would be required.

**Environment (please complete the following information):**
 - OS: OS X 10.13.6
 - Ionide version: 4.0.6
 - VSCode version: 1.36.1
 - dotnet SDK version: 2.2.203
 - mono / .Net Framework version: not quite sure... `mono --version` produces `Mono JIT compiler version 5.16.0.220`

**Comment by Krzysztof-Cieslak** [comment]
While I can understand your workflow, and see a potential advantages of it I don't really see any way to fix the problem - it's just not how VSCode, LSP and FSAC are designed to work.

I'll mark keep this open, in case someone has some awesome idea, but I'm not expecting this to be fixed any time soon.

**Comment by Krzysztof-Cieslak** [comment]
Closing as `wont-fix`. The way LSP client is designed in VSCode (or any other editor) doesn't support sharing single LSP instance across multiple editor instances.
