### ISSUE TITLE
Not able to create a new f# project with vscode version 1.3.1

### ISSUE THREAD

**Issue by omesh** [ionide/ionide-vscode-fsharp#119]
When I try to create a new F# project I get the below error in output window:

forge new project -n FetchIt -t console --folder DownloadEngine --no-prompt
Unrecognized command or missing required parameter

VSCode details:
<img width="373" alt="screenshot 2016-07-30 17 30 42" src="https://cloud.githubusercontent.com/assets/962668/17270124/023e25e2-5679-11e6-8b84-5339363ad66a.png">

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `2.2.10`
