### ISSUE TITLE
fsautocomplete running constantly at 12% CPU

### ISSUE THREAD

**Issue by deyanp** [ionide/ionide-vscode-fsharp#1190]
**Describe the bug**
A .NET Core process under VS Code with command line executing fsautocomplete.dll is constantly running and taking 12% CPU.
![Annotation 2019-08-08 095502](https://user-images.githubusercontent.com/25847560/62685291-adab7600-b9c2-11e9-927b-90408a4d11ae.jpg)

**To Reproduce**
Steps to reproduce the behaviour:
Nothing particular, just open an existing fs proj with about 10 code files (small) and look at task manager.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.0.6
 - VSCode version: 1.36.1
 - dotnet SDK version: 2.2.401 and 3.0 preview 7
 - mono / .Net Framework version: n/a

**Comment by Krzysztof-Cieslak** [comment]
Moved to FSAC repo - https://github.com/fsharp/FsAutoComplete/issues/456
