### ISSUE TITLE
New VSCode update borks up workbench icon and F# Solution Explorer

### ISSUE THREAD

**Issue by cartermp** [ionide/ionide-vscode-fsharp#1191]
![image](https://user-images.githubusercontent.com/6309070/62736488-4dc4c780-b9e2-11e9-85d8-584cf6f0eca4.png)

Ionide: 4.0.6

VSCode:

```
Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by albertwoo** [comment]
![ionide fsharp extension icon issue](https://user-images.githubusercontent.com/8017681/62772830-2d286a80-bad3-11e9-9f56-c87241a00eab.png)
Can we also change the indent for the tree, I marked as green.
From the picture it looks like file "Test.fs" and "Program.fs" is belong to folder "obj". It is very strange.

**Comment by SvenEV** [comment]
> Can we also change the indent for the tree, I marked as green.

As far as I know, the indent is the same as in the normal Explorer view and there is no way for extensions to change this. Have you tried an icon theme with folder icons, e.g. the built-in "Minimal" theme?

**Comment by albertwoo** [comment]
Ok, thanks!

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #1209

**Comment by cartermp** [comment]
As a note, apparently the OC bot doesn't think I'm a backer, but I am. Let me see if I messed that up...

**Comment by cartermp** [comment]
It was me who fucked up

**Comment by Krzysztof-Cieslak** [comment]
@cartermp You need to have correct GH username set in the OC
