### ISSUE TITLE
Add above causes issues when file names aren't valid F# file names

### ISSUE THREAD

**Issue by jpalmer** [ionide/ionide-vscode-fsharp#1194]
**Describe the bug**
When using add above and using an invalid file name, the file is added to the fs[roj, but no file is created / opened

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the F# project window in VS code
2. Click add above
3. Enter a file name like "point" (with no .fs on the end) 
4. The file name is added to the fsproj file, but it is not created, so trying to build after this will fail

**Expected behaviour**
Error message should be generated

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/225691/62816941-f8b7bb80-bb71-11e9-9625-1667f95d3ef1.png)

After:
![image](https://user-images.githubusercontent.com/225691/62816946-0705d780-bb72-11e9-82ae-25900c2044e5.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Ionide version:4.0.6
 - VSCode version:1.37.0
 - dotnet SDK version:2.1.503
 - mono / .Net Framework version: N/A

**Additional context**

**Comment by ZaymonFC** [comment]
I was considering reporting this.
It would be nice if the `add above, add below` functionality defaulted to adding `.fs` if no file extension is provided. Or if none is provided it could then prompt for a `.fs`/`.fsx` extension if creating scripts is a valid use-case.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `4.5.0`, the `.fs` extension will be added automatically
