### ISSUE TITLE
Different type signatures for identical functions.

### ISSUE THREAD

**Issue by ZaymonFC** [ionide/ionide-vscode-fsharp#1195]
**Describe the bug**
Different type signatures for identical functions.

**To Reproduce**
```fsharp
let a x y z = x (y z)
let aa x y z = x (y z)
```

You can see the inferred type signature for the first function is incorrect (`'a -> 'b`) in the screenshot.

**Expected behaviour**
Both functions should have the signature:
```
('a -> 'b) -> ('c -> 'a) -> c' -> b'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12402727/62840624-13f50900-bce1-11e9-86eb-132b3360ff76.png)

**Environment (please complete the following information):**
 - OS: Windows and OSX
 - Ionide version: 4.0.6
 - VSCode version: July 2019
 - dotnet SDK version: 2.2.204
 - mono / .Net Framework version: 5.18.1.3

**Comment by vbfox** [comment]
I suspect the bug is in FCS, not Ionide but all 1 letter functions have this problem :

![image](https://user-images.githubusercontent.com/131878/64153251-c165c300-ce2e-11e9-8dc3-6927cfcd16c7.png)

**Comment by Krzysztof-Cieslak** [comment]
It may be problem with location we check in FSAC - doesn’t we accidentally show signature of first parameter for a one-letter functions
