### ISSUE TITLE
Auto-include fsx-files specified in FSI "use" CLI-option

### ISSUE THREAD

**Issue by ronaldschlenker** [ionide/ionide-vscode-fsharp#1196]
As I work a lot with FSI, I have a fsx file which contains a lot of things I need for my daily work. This file consists of many "#I", "#r", "#load", "open", and of course code. Similar to profiles in powershell, I want to #load this script by default when I open a new FSI session, so I included it as "use" option in the FSI settings, like this:

```json
    "FSharp.fsiExtraParameters": [
        "--use:C:\\Users\\Ronald\\Documents\\.fsharp_profile\\profile.fsx"

```

Doing so, I can use all things in the script in FSI. The only thing that is missing is the editor support. FSAC knows nothing about the fact that I configured FSI with a "use" option. So as a workaround, I have to put things like that on top of every fsx file:

```fsharp
// for intellisense only (simulate "profile") - do not evaluate.
#load "C:\\Users\\Ronald\\Documents\\.fsharp_profile\\profile.fsx"

open Profile
open FSharp.Data
open FsHttp
...
// ---------------------
```

I suggest that Ionide checks it's settings for files sent to FSI with "use" and send them automatically into FSAC to have editor support without putting stuff on top of every file.

**Comment by Krzysztof-Cieslak** [comment]
I didn't even know that `use` option exists ;-)

Yeah, sounds like reasonable request - we probably should just detect if user use `use` option and in such case typecheck such files.

**Comment by ronaldschlenker** [comment]
Or we could make that more prominent by adding a „profile“ setting where users can point to an fsx file that will be used.

As far as I understand, it should be quite easy to implement, correct? New setting, and then sending it to FSI by adding „use“ parameter and sending it to fsac. If that’s the case and you would like to have it in Ionide, I could try to get my hands on that.

**Comment by Krzysztof-Cieslak** [comment]
Yes, that sounds correct. Adding `fsiProfile` setting also sounds reasonable.

**Comment by jackfoxy** [comment]
seeing as how this is open, I'd also like to be able to set a profile in same way
```
 "FSharp.fsiExtraParameters": [
        "--use:C:\\Users\\Ronald\\Documents\\.fsharp_profile\\profile.fsx"
```

**Comment by baronfel** [comment]
This actually is done already.  The configs are passed in via the structure [here](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete/LspHelpers.fs#L558), updated in the persistent compiler service state [here](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete/FsAutoComplete.Lsp.fs#L60), and are taken into account during typechecking [here](https://github.com/fsharp/FsAutoComplete/blob/8c9d57c607128d5245712530df6acadc338f2c61/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L555-L568).

**Comment by Krzysztof-Cieslak** [comment]
@baronfel, wouldn't we need to typecheck also the file specified in `--use` argument?

**Comment by baronfel** [comment]
I did some testing with the `--load` and `--use` options and they don't seem to work with regards to typechecking.  Passing them through to the typechecker results in errors like the following:

```
Unrecognized option: '--load'
Unrecognized option: '--use'
```

So We do have more work to do here.

**Comment by baronfel** [comment]
FSAC was _mostly_ there with additional argument processing, we just needed to handle load and use a bit differently from the other options, as @Krzysztof-Cieslak was mentioning.

**Comment by Krzysztof-Cieslak** [comment]
This should be working in `4.4.x`.
