### ISSUE TITLE
FsAutoComplete.Suave.exe processes left running

### ISSUE THREAD

**Issue by hyperlobic** [ionide/ionide-vscode-fsharp#12]
Under Linux, every time an F# folder is opened an autocomplete process is started up. These processes are never killed, even if the application is closed.

**Comment by azumikav** [comment]
The go extension has this problem too https://github.com/Microsoft/vscode-go/issues/26

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.2.2`
