### ISSUE TITLE
Not able to create a new f# project with vscode on windows

### ISSUE THREAD

**Issue by nestordemeure** [ionide/ionide-vscode-fsharp#120]
Hello,

I have the last version of VScode and ionide to date. When I create a new F# project in an empty folder ("F1 + F# : new project") using ionide I get the usual "Project created" message but no project gets created. 
Doing the exact same thing on ubuntu works as expected.

I updated my computeur to windows 10 a few days ago, ionide was working fine, windows 10 was updated saturday and I lost both project creation and my touchpad at once so I would be inclined to suspect it is a strange windows thing...

I also had a "No handler found for the command ...ionide:somehing..." error at a time but i am currently unable to reproduce it.

I know that I am not giving much to reproduce/identify the problem but I have not much here (if you have any idea to probe the problem, I will happily apply them).

Nestor Demeure

**Comment by nestordemeure** [comment]
The difference with issues such as this one is that I have no error message : 
https://github.com/fsprojects/Forge/issues/119

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `2.2.10`

**Comment by nestordemeure** [comment]
Sadly, the problem persists.

**Comment by Krzysztof-Cieslak** [comment]
Can you check log in output panel in Forge tab.

**Comment by nestordemeure** [comment]
That seems like a clue :

> forge new project -n projectname -t console --folder projectfolder --no-prompt
> Wrong template name

(I created a project called projectname of type console in projectfolder)

**Comment by Krzysztof-Cieslak** [comment]
Try running `F#: Refresh Project Templates` command and retry creating project.

**Comment by nestordemeure** [comment]
The log told me that it needed git to run "Refresh Project Template".
I discovered that I lost git on that machine during the last update (it was chaos).
Project creation is now working as expected 👍

**Comment by MudiLoodi** [comment]
I'm having the same exact problem.
