### ISSUE TITLE
merge ionide-fsharp and ionide-paket extensions

### ISSUE THREAD

**Issue by DoubleCouponDay** [ionide/ionide-vscode-fsharp#1202]
Initially I was quite excited to use fsharp with a light weight IDE. However I ran up against some quality of life issues which prevent me from enjoying the experience.

When I install a package using the nuget CLI, for an F# aspnet core project, it does not create an xml entry in the proj file. That means there is no way to remove a package by using `nuget restore`, as it will only trim packages that are not entered. 

When I manually enter a `PackageReference` in the proj file, there is no reproducible way to refresh the ionide intellisense. It will show errors as if the package had not been installed.

After restarting vs code the intellisense wont show as you made a spelling mistake in the proj file. Ionide will not tell you the line that this "parsing error" occurs; simply that it exists. After I find the one forward slash that you forgot to add to a closing bracket of an xml element, I have just about called it quits with this tool. 

Now that I have discovered the paket integration, using the `ionide-paket` extension I really feel that this should have all been bundled together into a single extension and that the quality of life for newcomers is quite low.

**Comment by DoubleCouponDay** [comment]
Now it seems that paket.exe is not included with the paket extension. frustrating.

**Comment by Krzysztof-Cieslak** [comment]
Our plans regarding Ionide-paket and Ionide-FAKE were discussed in https://github.com/ionide/ionide-vscode-fsharp/issues/1119
