### ISSUE TITLE
Some custom operators don't provided hover information and CodeLens

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#1203]
**To Reproduce**
Steps to reproduce the behaviour:
1. Create an F# source file
2.
``` fsharp
let (.>>) x y = x + y
```
3. Hover on the operator's name and look at the CodeLens info.
4. You won't see anything.

**Expected behaviour**
The operator's name and CodeLens info.

**Workarounds**
``` fsharp
let op_DotGreaterGreater x y = x + y
```

It surprisingly works just fine, and I can perfectly use the symbolic operator.

**Environment (please complete the following information):**
 - OS: Windows 10 Education
 - Ionide version: 4.0.6
 - VSCode version: 1.37.1
 - dotnet SDK version: 2.1.701
 - mono / .Net Framework version: 4.8

**Comment by Krzysztof-Cieslak** [comment]
I've managed to fix this, it will be released in next 5.0 preview (probably tomorrow) or, if you don't use previews, when full 5.0 is ready (probably end of this week if nothing unexpected happens again)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed with 5.0
