### ISSUE TITLE
Ionide not working with .NET SDK 3.0.0-preview8

### ISSUE THREAD

**Issue by theimowski** [ionide/ionide-vscode-fsharp#1205]
Unfortunately I don't have a minimal reproduction sample for this one. 
While trying to investigate why Ionide stopped highlighting compilation errors, I turned the verbose logging on, and I'm seeing multiple entries like this one:

```
[BACKGROUND SERVICE] Msg: Typechecking /.../Program.fs
[LSP] Notify - Diagnostics
  {Uri = "file:///.../Program.fs";
   Diagnostics = [|{Range = {Start = {Line = -1;
                                      Character = 0;};
                             End = {Line = -1;
                                    Character = 0;};};
                    Severity = Some Error;
                    Code = Some "243";
                    Source = "F# Compiler";
                    Message = "Unrecognized option: '--langversion'";
                    RelatedInformation = Some [||];
                    Tags = None;}|];}
```

Think this might have something to do with introducing the langversion parameter recently to FSC https://github.com/dotnet/fsharp/pull/6790 
But not sure how to overcome this issue - any ideas?

**Comment by theimowski** [comment]
FWIW I believe this might be related to using `netcoreapp3.0` TargetFramework, but not yet sure how

**Comment by theimowski** [comment]
I'm using OSX and have set FSAC to netcore - how do I determine which version of fsc it is invoking? Is it possible it's calling `fsharpc` (have mono installed)?

Pretty sure the issue is FSAC is calling an older version of fsc, one that doesn't support `--langversion` parameter

**Comment by theimowski** [comment]
Managed to get a minimal reproduction: https://github.com/theimowski/ionide-vscode-fsharp-1025

It's a `dotnet new console` F# app with a deliberate compilation error.
I added .devcontainer definition based on dotnet core 3.0.0-preview8 image to isolate the case.
When opening that workspace in ionide + remote containers, the compilation error does not get highlighted, and there's a chance of seeing the "--langversion" thing in logs

But when downgrading the base image to [3.0.0-preview7](https://github.com/theimowski/ionide-vscode-fsharp-1025/tree/preview7) it starts working properly - the compilation error gets highlighted 

So apparently this issue is related to preview 8

**Comment by theimowski** [comment]
Related issue: https://github.com/dotnet/fsharp/issues/7425

**Comment by emmchild** [comment]
The issue seems to have been resolved by installing  https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/.  It was nice to know that the issue was short lived.

**Comment by Krzysztof-Cieslak** [comment]
Yes, I've also been told on Slack that Ionide is working again with preview9, @theimowski can you check if that's the case for you?

**Comment by theimowski** [comment]
Yup, works for me now with preview9 - thanks!

TBH I'm not sure if the originally mentioned `Unrecognized option: '--langversion'` had anything to do with this really
