### ISSUE TITLE
Add option to specify path to mono

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#121]
By default we are using mono in PATH.

But there are some situations where users may want to use different mono version than their default in PATH (for example unstable or 64 bit one) - http://www.mono-project.com/docs/compiling-mono/parallel-mono-environments/

We should provide option to specify path to mono which should be used.

**Comment by kirill-gerasimenko** [comment]
Hi,

I've started working on this and wanted to clarify - should this mono setting apply only to language server (FsAutoComplete process), or it should also affect running Forge when generating projects? 

Thanks.

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.2.17`
