### ISSUE TITLE
Unable to create F# projects in VSCode

### ISSUE THREAD

**Issue by MudiLoodi** [ionide/ionide-vscode-fsharp#1214]
Hello,

I have the latest version of VScode and ionide. When I create a new F# project in an empty folder using the command palette using I get the "Project created" message but no project gets created.
I expect it to just create a project.

Environment
 - OS: Windows 10
 - Ionide version: 4.0.6
 - VSCode version: 1.38.0 (User setup)
 - dotnet SDK version: 2.2.401
 - .Net Framework version: .Net Framework 4.8

Here is the Forge log:
`C:\Users\USERNAME\.vscode\extensions\ionide.ionide-fsharp-4.0.6\bin_forge\Forge.dll new project -n test -t classlib --folder ""  --no-prompt
No executable found matching command "dotnet-C:\Users\USERNAME"`

**Comment by MudiLoodi** [comment]
After the latest update to F# and .Net I'm getting this message:

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-C:\Users\Moe does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by HarrisonOfTheNorth** [comment]
I have a similar problem on Mac OS, I go "View / Command Palette / F#: New Project (Project Scaffold)" and I get the error "Creating Project Failed - Directory is not empty" It occurs whether or not I have a folder open, and in the case that the folder is open, the directory is indeed empty.

I can create a .fsx file and write some F# code and, for example, use ALT-Enter to run it, however the tool-tips do not work either.

```
Ionide 4.2.0
```

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```

**Comment by cartermp** [comment]
FYI @MudiLoodi I think the general issue you're seeing is more of a docs problem than anything else, since we still suggested doing things in an older way (that was a lot more fragile!).

https://github.com/dotnet/docs/pull/15851 should probably make all of that go away
