### ISSUE TITLE
General Constant Problems

### ISSUE THREAD

**Issue by jfrank-summit** [ionide/ionide-vscode-fsharp#1221]
I don't have time to go through all of the constant problems I'm having right now with VS Code/Ionide and Fsharp. I was loving my switch to VS Code I made last year but recently there have been so many problems that I just don't have time to figure out. And they feel so random it is hard to report, it works one time, next time doesn't, next time does. I have given up for now and gone back to the dreaded Visual Studio Professional (2019 Preview) which is actually working pretty well. But I what my VS Code back. Most issues I'm having have been reported, this is just to check where things are at more generally. Thanks for all you guys do!

**Comment by Krzysztof-Cieslak** [comment]
Closed as not actionable report.
