### ISSUE TITLE
Command `F#: Get Ionide Logs` does not work.

### ISSUE THREAD

**Issue by ZaymonFC** [ionide/ionide-vscode-fsharp#1222]
**Describe the bug**
When running the command `F#: Get Ionide Logs` the following error is produced:

`command 'fsharp.diagnostics.getIonideLogs' not found`

**Environment:**
 - OS: OSX
 - Ionide version: `4.1`
 - VSCode version: `1.38.1`
 - dotnet SDK version: `dotnet Core 3.0.100`

**Comment by Krzysztof-Cieslak** [comment]
Should be working again in `4.4.x`
