### ISSUE TITLE
Show all lint errors in solution / project.

### ISSUE THREAD

**Issue by ZaymonFC** [ionide/ionide-vscode-fsharp#1223]
The F# linter integration is really nice and there are some very useful lint rules. It would be nice to view all lint errors in the solution or project to help with code cleanup and refactoring.

*Solution Description*
Ideally have a command to jump to the next lint error. Or have lint errors be shown in the info panel.

**Describe alternatives you've considered**
Currently doing it via the CLI with this little bash script:

```bash
set -euo pipefail

dotnet build

echo '[F# Lint] - Starting Project Linting'

find "$PWD" -type f -name '*.fsproj' -exec dotnet fsharplint -f {} \;
```

**Comment by Krzysztof-Cieslak** [comment]
The choice to get linter warnings only on the current editor is due to performance implication, having them everywhere would be expensive operation.

 However we probably can move that to the background service 🤔 ....

**Comment by Krzysztof-Cieslak** [comment]
Closing this as `wont-fix` at the moment. I may revisit in the future but it's really unlikely.
