### ISSUE TITLE
"Unhandled exception occurred..." & typecheck results on fsx never available

### ISSUE THREAD

**Issue by jfrank-summit** [ionide/ionide-vscode-fsharp#1224]
**Describe the bug**
I am running a clean install of visual studio code. The only extensions installed are ionide paket and ionide fsharp. When I open any folder with fsharp files I get the following dotnet.exe failure:
![dotnetexe failure](https://user-images.githubusercontent.com/37932802/65519788-cb199e00-dea3-11e9-85b1-6b4df312133f.png)

If I uninstall ionide the error goes away but so does my ability to use F#! :)

If I ignore the failure and open any fs or fsx file my files show failures everywhere:
![red squigglies](https://user-images.githubusercontent.com/37932802/65519916-061bd180-dea4-11e9-8aa5-ed9fc09271ce.png)

When I go to logs the most common issue is typecheck results not available:
![typecheck results](https://user-images.githubusercontent.com/37932802/65519999-23e93680-dea4-11e9-8288-be20a75fa700.png)

When I open projects and scripts in VS 2019 everything works fine (and I even get F# 4.7 in my FSI). I want to move back to VS Code  though, so that is not a long-term solution. I know I am not the only one experiencing issues similar to this:
Ticket #1220 for example

Current Environment
 - OS: Windows 10
 - Ionide version: 4.1
 - VSCode version: 1.38.1
 - dotnet SDK version: 3.0.100

**Additional context**
This is two of many issues I have been having over the last couple of months. So much so that I have had to revert to Visual Studio 2019, something I hoped to never do! :) I appreciate all the hard work going into F# tooling and hope to see these issues worked out soon, especially with all the recent releases impacting the dotnet and F# world.

VS Code has gone a long way to bring in traditionally non Microsoft/Visual Studio developers and allowed them to use great tools such as F#. I know it has helped my business as I work to get companies to adopt F# whenever possible. However, when tooling breaks or is a constant pain point it is only natural to revert to old ways of doing things and dismiss the baby as you throw out the tooling bathwater. While I am able to switch back to Visual Studio (reluctantly) many of my clients won't want to hassle with it. I hope these issues are addressed quickly! I love the work being done and greatly appreciate those who contribute to the projects!

**Comment by Krzysztof-Cieslak** [comment]
We're tracking current scripting problems in #1220
