### ISSUE TITLE
Ionide doesn't fold code correctly all the time

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1226]
**Describe the bug**
Ionide seems to not handle `#IF`-defines correctly when using code-folding handles.  

**To Reproduce**
1. Given the following code check out the fold-handles in the gutter on the side
```fsharp
module Test = 

  let thingA () = 1

  let thingB () = 2

  let thinger () = 
#if DEBUG
    thingA()
#else
    thingB ()
#endif

  let otherthing = thinger() + 10
```

![image](https://user-images.githubusercontent.com/573979/66137145-437a1080-e5c2-11e9-9f66-5450b35fc63b.png)

2. Try to collapse the `module Test =` line

**Expected behaviour**
The entire contents of the `Test` module is folded.

**Actual Behavior**
Only code up to the `$IF`def is folded.

**Screenshots**
![image](https://user-images.githubusercontent.com/573979/66137279-791ef980-e5c2-11e9-93bd-867c60878c01.png)

**Environment (please complete the following information):**
 - OS: mac osx mojave
 - Ionide version: 4.1.0
 - VSCode version: 1.38.1
 - dotnet SDK version: 3.0.100
 - mono / .Net Framework version: N/A

**Comment by Krzysztof-Cieslak** [comment]
We don't implement language specific folding provider (which is a possibility in VSCode), so the folding is based on indent - which I guess is what we see here.

**Comment by baronfel** [comment]
Helpful links: 

* would need to implement a [`foldingRangeProvider`](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider)
* and register it with [`registerFoldingRangeProvider`](https://code.visualstudio.com/api/references/vscode-api#languages.registerFoldingRangeProvider)

**Comment by Krzysztof-Cieslak** [comment]
Or rather we'd would do it in FSAC with https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_foldingRange ;-)

**Comment by baronfel** [comment]
Closing because FSAC has implemented this.
