### ISSUE TITLE
More visibility into what Ionide is doing

### ISSUE THREAD

**Issue by anchann** [ionide/ionide-vscode-fsharp#1230]
Thank you for all the hard work building Ionide.

**Is your feature request related to a problem? Please describe.**

There is a number of issues that make Ionide difficult for me to use:
* sometimes one or more `dotnet` processes sits stuck at 100% even though I haven't touched VSCode for half an hour
* sometimes project initialization takes forever, and it's impossible to know if it's still going, or has given up and died
* sometimes suggestions sit in "loading" for 20 seconds
* sometimes suggestions show up quickly, but list nonsensical things, like the all items available in the global namespace

**Describe the solution you'd like**

I'd like to see Ionide status information made easily accessible to the user through VSCode. Specifically, things like:
* is Ionide still alive
* is project loaded? Still loading? How many of how many files?
* is the currently open file processed or not?
* for each file in the tree, is it processed or not?
* if an underlying process died, can I have the exception trace?
* if an underlying process is stuck at 100% CPU, can I know what the last thing it tried doing is?

If there are any issues, I'd like to see errors reported in an obvious way, not the tooling quietly dying.

I would like to participate, contribute useful bug reports, maybe even features eventually, but right now I feel like I'm basically blind when I try to understand what is even going on, I have to build weak hypotheses based on some secondary symptoms, like "the inferred types comment thingy is not visible, so project must still be initializing". I think the more visibility people have, the higher the quality of participation will be, and the quicker we can arrive at solutions.

**Describe alternatives you've considered**

Now I basically infer the state of Ionide from various secondary symptoms, or build and test various hypothesis blindly, based on guesses about what must be happening inside.

I've also considered switching to Rider, but we have a DSL for which we have an LSP-based VSCode extension, and porting that to IntelliJ doesn't sound like fun work.

**Additional context**

I'm on MacOS.

**Comment by Krzysztof-Cieslak** [comment]
You can get pretty detailed view of what's happening in Ionide in `F#` output panel. To get even more info you can enable `FSharp.verboseLogging` in settings.

**Comment by anchann** [comment]
@Krzysztof-Cieslak I don't think the F# Output panel serves the use case I'm requesting to be addressed in this feature request.

The F# Output panel is a log firehose. What I'm asking for is a snapshot of the current state.

It's the difference between a transaction log of a database and the data tables. Sure, you can reconstruct the current state of the data tables from the transaction log, but at what cost?

So I think the log and the snapshot are two different tools, serving completely different use cases.

On the one hand, we have you, as the author of the code, who knows precisely what to look for in the log stream, and what to ignore. It's a white box world for you, everything is transparent, it's home territory. Of course the log is sufficient for your debugging needs. Just consider the sheer amount of implicit knowledge you have about the system, which helps you consume the logs and extract useful information about the current state of the system out of them.

On the other hand, we have your community. For the most part, they just want to get work done. When the tooling craps out for the nth time that day, they just cross their fingers and hope a VSCode restart fixes the situation, without grinding their CPU for less than five minutes. Sometimes, in the midst of trying to meet their own deadlines and getting their own work done, they feel that they "should do the right thing", and do their part in the community. But what is that part? Figure out exactly what went wrong, instead of just "tooling crapped out". Then pour over the multitude of existing github issues, to see if theirs is somehow related. And then finally maybe write up a detailed bug report, to likely have it tagged with "concrete repro case needed". One has to have a serious amount of time energy to spare in order to see something like this through. And when at the first step, the "figure out what actually went wrong", they're presented with a log firehose, whatever little energy they had committed to "doing the right thing" quickly gets sucked out. So after five minutes of scrolling through the log, VSCode gets restarted, and life goes on.

It's human nature. And if you want help from these humans, and based on "I want your help. No really, I do" it sounds like you do, you need to make it easy for them to do the right thing. What I'm requesting here is a feature to help do exactly that — lower the threshold to contribution, empower your community to submit useful, information-rich bug reports before they run out of steam. It's essentially relatively cheap to implement, poor man's telemetry.

I realize (in part by reading online discussions) there must be a lot of sentiment along the lines of "but they are using for free, and complaining about, something that took one person years to build, and is serving, often decently well, millions of F# developers every day! Who do they think they are to take this work for granted and to act so entitled?" The sentiment may be entirely justified, but if your goal is, for whatever reason, to make Ionide better, then the sentiment is entirely besides the point. The point is "how do we extract the most value in terms of making Ionide better out of these entitled, ungrateful, and otherwise imperfect humans". Making it simple for them to provide you meaningful telemetry is one such way.

Anyway, thanks for reading. This was my attempt at contributing what I can, but as I said, time and energy are severely limited. Thank you for your ongoing work in making Ionide better.
