### ISSUE TITLE
many errors in 4.2.0 and not 4.1.0

### ISSUE THREAD

**Issue by ctaggart** [ionide/ionide-vscode-fsharp#1232]
**Describe the bug**
4.2.0 shows a lot of compilation errors. It feels like the project references may not be working. I downloaded the vsix for 4.1.0 from the releases page and installed it, since that is working fine for me.

**To Reproduce**
Sorry, I don't yet have an open source solution I can point you to.

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - Ionide version: 4.2.0
 - VSCode version: 1.38.1
 - dotnet SDK version: 2.2.203 (in global.json)
 - mono / .Net Framework version:

**Additional context**
Not the best bug report.

**Comment by Krzysztof-Cieslak** [comment]
Try to clean cache (`F#: Clean Cache` command) or removing obj/bin dirs.

Then check what’s the status of project loading in Ionide’s solution explorer (F# icon on the action bar on left)
