### ISSUE TITLE
"Send to interactive" doesn't work with unicode on Windows

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1236]
Send the following line from ionide to fsi (Alt+Enter)

    "Üü" |> Seq.toArray |> Array.map int  |> printfn "%A"

and I get:

    Microsoft (R) F# Interactive, Version 10.5.0.0 for F# 4.6
    Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
    ...
    > "��" |> Seq.toArray |> Array.map int  |> printfn "%A";;
    [|65533; 65533|]
    val it : unit = ()

as you can see both characters are treated as the same. this does not seem to b a fsi bug because the fsi already gets both as the same.

**Comment by forki** [comment]
the same happens when I paste the line directly from clipboard into the F# Interactive terminal

**Comment by ronaldschlenker** [comment]
Same here. Stumbled across this right now.

When I revert to Ionide 4.1, the issue doesn't occur (with Ionide 4.1, FSI 4.5 is loaded instead of 4.7 / 4.6).

**Comment by ronaldschlenker** [comment]
Related:
https://github.com/dotnet/fsharp/issues/7733

**Comment by ronaldschlenker** [comment]
Any news on this one?

**Comment by Krzysztof-Cieslak** [comment]
This bug is reproduceable directly in the FSI running in command line. I.e it's not Ionide bug. Please track linked above issue in the dotnet/fsharp repo.

**Comment by larjo** [comment]
Even with F# 5 and net 5.0, this is still a problem out of the box.

But with this configuration it works!

```
  "FSharp.fsiExtraParameters": [
    "--fsi-server-input-codepage:28591",
    "--fsi-server-output-codepage:65001"
  ]
```

![image](https://user-images.githubusercontent.com/1218329/98907918-e2f51c80-24bf-11eb-8ea7-5bdf9c42b7ec.png)

It works with both fsi.exe and dotnet fsi.
