### ISSUE TITLE
"Build and Launch Extension" does not work on my windows 

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1239]
The ionide in the debug hive crashes immediately when I try to debug current master ionide.

![image](https://user-images.githubusercontent.com/57396/66562097-26fa4d00-eb5b-11e9-9b7b-ca99204e5cd5.png)

**Comment by Krzysztof-Cieslak** [comment]
Have you run `build.cmd Build` as first step before running `Build and Launch Extension`?

**Comment by LukeBurgessYeo** [comment]
I had the same issue, but once I'd built FSAC and referenced the FSAC .dll as described in the contributing guide if worked fine.
