### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by Samvrie** [ionide/ionide-vscode-fsharp#124]
Hello,

I just cloned the repo, and I got an issue on the build.
I followed the step : 
- Clone the repo
- Run build.cmd Build

I have an error on the RunScript task.
[Here is the log of the build](https://github.com/ionide/ionide-vscode-fsharp/files/402316/log.txt), it seems that Fable can't find a reference, but I have no idea on how to fix it.

Paket also show an error *paket.dependencies and paket.lock are out of sync, Please run 'paket install' ...*
I tried to delete the *paket.lock* and make a *paket install*, but the warning is still there.

Does there's any requirements on npm/nodejs/fsc version?

Mine are : 
 - Npm : 2.15.5
 - Node : 4.4.5
 - FSC : 14.0.23413.0

I'm running on Windows 10.

**Comment by cloudRoutine** [comment]
fixed
