### ISSUE TITLE
No intellisense / code lens on new file

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1245]
1. Configure VS Code to use F# as the default file type (`"files.defaultLanguage": "fsharp"`)
1. Create a new file in code (e.g. `CTRL + N`).
1. Start typing some F#. Observe that although Code knows it's F# (e.g. F# logo appears in the tab), no intellisense or codelens shows up.
1. Save the file, giving it an `.fsx` extension.
1. Everything starts to work.

**Comment by Krzysztof-Cieslak** [comment]
Duplicate of #1156

**Comment by isaacabraham** [comment]
Sorry for the dupe (from myself!) - forgot I added it.
