### ISSUE TITLE
Add Variable Explorer for fsi scripting

### ISSUE THREAD

**Issue by tforkmann** [ionide/ionide-vscode-fsharp#1251]
**Is your feature request related to a problem? Please describe.**
It would be nice to create an vs code extension/features which shows all variables from the fsi. This would be very helpful for fsi scripting. It would make it more easy to explore data. This feature is inpired by the python tool spyder.

**Describe the solution you'd like**
It would be nice to show the data/variables from the fsi script as on the right side next to the source code. 

**Describe alternatives you've considered**
Maybe a different editor has this feature

**Additional context**
Here is a screenshot of the variable explorer from the python tool spyder:
![image](https://user-images.githubusercontent.com/4168951/68020296-59045800-fc9e-11e9-8ffb-7009e96f5760.png)

**Comment by Krzysztof-Cieslak** [comment]
This is something I always wanted to do but it's not simple give current architecture of FSI.

**Comment by Krzysztof-Cieslak** [comment]
This was implemented in `4.8.0`
