### ISSUE TITLE
Info panel type inference does not work

### ISSUE THREAD

**Issue by masq6r** [ionide/ionide-vscode-fsharp#1252]
**Describe the bug**
Sometimes the Info Panel doesn't show correct type information.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone [elmish repo](https://github.com/elmish/elmish.git)
2. Run `paket install`, `dotnet restore` etc to setup the project.
3. Open `elmish` folder in VSCode.
4. Open `cmd.fs`. Click the function `Cmd.OfFunc.attempt`. The Info Panel shows the return type as `Unknown`.

**Expected behaviour**
`Cmd<'msg>` should be the correct return type as the screenshot shows (which is inferred correctly in the codelens). 

**Screenshots**
![image](https://user-images.githubusercontent.com/594939/68030159-c8586700-fcf3-11e9-9592-5a1d2209a6b6.png)
![image](https://user-images.githubusercontent.com/594939/68030210-e0c88180-fcf3-11e9-9be0-c9f61fde73d3.png)

**Environment (please complete the following information):**
 - OS: Windows 10 or CentOS 7
 - Ionide version: 4.2
 - VSCode version: 1.39.2
 - dotnet SDK version: 3.0.100
 - mono / .Net Framework version: None

**Additional context**
N/A

**Comment by Krzysztof-Cieslak** [comment]
This seems to be working nowadays

<img width="1239" alt="Screenshot 2020-03-26 at 18 35 56" src="https://user-images.githubusercontent.com/5427083/77677912-ad331000-6f90-11ea-90fa-ce0845c3914d.png">
