### ISSUE TITLE
Project loading errors if opening VS monorepo root folder

### ISSUE THREAD

**Issue by mmc41** [ionide/ionide-vscode-fsharp#1253]
**Describe the bug**
I get project loading errors if I open VS in root folder of a monorepo with mixed C# and F# projects placed in different subfolders.

P.S. Would be nice if I could configure extension to disable loading in main folder or to look in specific subfolders instead for projects when I open VS in the main folder.

**Environment (please complete the following information):**
 - OS: Mac OS X 10.14
 - Ionide version: 4.2.0
 - VSCode version: 1.39.9
 - dotnet SDK version: 3.0

**Comment by Krzysztof-Cieslak** [comment]
You can create multiple `.sln` files in same folder, Ionide will ask which one you want to use when opening Code in such folder. This way you choose what projects you want to load.

Closing as `by-design`

**Comment by lydell** [comment]
It would be awesome if the plugin supported multiple projects at the same time somehow.
