### ISSUE TITLE
F#: Get info for diagnostics command "not found"

### ISSUE THREAD

**Issue by paytonrules** [ionide/ionide-vscode-fsharp#1254]
**Describe the bug**
Running the Command Palette run the "F#: Get Info for diagnostics" command fails with a "command 'fsharp.diagnostics.getInfos' not found" error. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the command palette.
2. Choose F#: Get Info for diagnostics
3. Hit Enter
4. See error in the right hand corder "command 'fsharp.diagnostics.getInfos' not found" error

**Expected behaviour**
I expect it to show me the diagnostics necessary for a proper bug report and as mentioned in the Contributing guidelines.

**Screenshots**
See the lower right hand corner: 

![image](https://user-images.githubusercontent.com/21752/68135599-901a7980-fee9-11e9-8349-e78df36fe91f.png)

**Environment (please complete the following information):**
 - OS: MacOS Mojave
 - Ionide version: 4.2.0
 - VSCode version: 1.39.2
 - dotnet SDK version: 3.0.100
 - mono / .Net Framework version: 3.0.100 I assume

**Additional context**
I'm trying to use this to submit another defect, but this makes it a tad tricky.

**Comment by ZaymonFC** [comment]
Related: #1222
