### ISSUE TITLE
CrosswordSolver on ionide.io

### ISSUE THREAD

**Issue by emraeshine3** [ionide/ionide-vscode-fsharp#1255]
Hi there,

My name is Emily with CrosswordSolver.com, a sponsor of ionide.io.

We were hoping to get our logo & link added to your website. Is this possible? If so, would you need a certain logo file from us?

Let me know and thank you very much for your help!

Smiles,
Emily

**Comment by forki** [comment]
I think posting the link and a png here is probably fine. We would also like to learn how you are using ionide and F# in your company. We are always interested in such feedback.

**Comment by emraeshine3** [comment]
Some feedback from our developer below :)
use case: we are using websharper for experimentation and prototyping
pros: works great and on the go with visual code on windows
cons: the whole stack is kinda time consuming to start with our linux devs and sometimes the server crashes there, so we are sticking on windows there.

**Comment by Krzysztof-Cieslak** [comment]
Hey, I've updated both readme in this repo, and ionide.io page. Sorry for the delay.

**Comment by emraeshine3** [comment]
Hi there,

Great, thank you for your help and for letting me know :)

Smiles,
Emily

Quoting Krzysztof Cieślak <notifications@github.com>:

**Comment by emraeshine3** [comment]
Hi Krzysztof,

Sorry for reopening but can we use our new logo on http://ionide.io/ that's attached? Thank you!!
![en_dark-500px](https://user-images.githubusercontent.com/56983804/68600643-dbe09c00-0470-11ea-9bdd-adc62b0434ee.png)
