### ISSUE TITLE
Cancel Interactive Evaluation in FSI

### ISSUE THREAD

**Issue by mathias-brandewinder** [ionide/ionide-vscode-fsharp#1260]
FSI in Visual Studio has a feature, "Cancel Interactive Evaluation", triggered by Ctrl+Break or right-click on the F# Interactive window menu.

This is useful to interrupt a long-running process, without losing what is in memory in the session. As an example, I might want to interrupt a long calculation because I realized there was an error, without restarting the whole session and needing to reload data.

It would be nice to offer that feature, perhaps through an additional command, perhaps using a similar shortcut.

**Comment by baronfel** [comment]
Do you know of a way to perform this cancellation from the terminal running dotnet FSI itself? We only spawn a terminal so if there's not a way to do it via keystrokes then we might be out of luck.

**Comment by mathias-brandewinder** [comment]
Unfortunately, I do not. The `Ctrl+Break` shortcut in Visual Studio doesn't seem to do anything anywhere else. I tried `Ctrl+C`, but that seems to just stop the entire FSI session.
