### ISSUE TITLE
Option to disable Fantomas integration

### ISSUE THREAD

**Issue by blair55** [ionide/ionide-vscode-fsharp#1261]
**Is your feature request related to a problem? Please describe.**
I enjoy the vscode 'Format on save' setting. Its useful when working in languages other than F#. However, I don't enjoy the Fantomas formatting that is applied when working with F#.

**Describe the solution you'd like**
 I would like to keep the vscode 'format on save' setting _on_ for other languages and turn it _off_ for ionide/F#.

**Describe alternatives you've considered**
I have previous installed & uninstalled fantomas using `dotnet tool uninstall -g fantomas-tool` but the formatting behaviour remains. I guess fantomas is built-into ionide? 

Thanks :-D

**Comment by vbfox** [comment]
VSCode itself already support per-language settings like https://flaviocopes.com/vscode-language-specific-settings/

This case should look like:

```json
{
    "[fsharp]": {
        "editor.formatOnSave": false
    }
}
```

**Comment by blair55** [comment]
Perfect, thanks! Closing.
