### ISSUE TITLE
F#.: Run script command fails

### ISSUE THREAD

**Issue by kalvis77** [ionide/ionide-vscode-fsharp#1264]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
Try to execute any f# script with F# Run script command

**Expected behaviour**
Script output, but instead the following text is displayed on terminal:

_Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-fsi --fsi-server-input-codepage:65001 does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH._

**Screenshots**

**Environment (please complete the following information):**
 - OS: Win 10
 - Ionide version: 4.3.1
 - VSCode version: 1.40.1
 - dotnet SDK version: 3.0.101
 - mono / .Net Framework version:

**Additional context**
Fails with Ionide 4.3.1, 4.3.0, but works with 4.2,  
Command that Ionide tries to execute contains extra double quotes, terminal command history contains last command

cd "c:\....\source\repos\ELRS\src\slrutils" && cls && "C:\Program Files\dotnet\dotnet.exe" ""fsi" "--fsi-server-input-codepage:65001"" "c:\...\source\repos\ELRS\src\slrutils\CpfTest.fsx" && pause && exit

**Comment by dgrimmin** [comment]
Did you set “"Use SDK Scripts" to true in the ionide settings.”?

**Comment by kalvis77** [comment]
Yes. As I mentioned in  description,  problem is dotnet fsi command, which contains extra double quotes. Terminal stays opened with the error message and its possible to check this command in history buffer. After deleting extra quotes, command executes just fine.

**Comment by baronfel** [comment]
Have you set a custom `FSharp.fsiFilePath` setting or is that still on the default?

**Comment by kalvis77** [comment]
Default value.

**Comment by baronfel** [comment]
Thanks for confirming. Yay for windows quote escaping...

**Comment by Krzysztof-Cieslak** [comment]
Hey, this may be out of topic a bit but let me ask one question - why do you use `F#: Run script` rather than `FSI: Send file`? I've been considering removing `F#: Run script` to simplify stuff

**Comment by kalvis77** [comment]
FSI: Run Script is the  the first button in the row, convenient to use.

**Comment by matarillo** [comment]
[Ionide-fsharp 4.6.0](https://github.com/ionide/ionide-vscode-fsharp/releases/tag/4.6.0) will fix this problem.
