### ISSUE TITLE
LineLens update unstable

### ISSUE THREAD

**Issue by zhuangzhuang** [ionide/ionide-vscode-fsharp#1270]
**Describe the bug**
![GIF 2019-12-11 9-57-49](https://user-images.githubusercontent.com/521058/70584961-b2e13180-1bfd-11ea-97bf-0e8ec3dc7f2c.gif)

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
speedOfImpact linelens must has **float<m/s>** when save.

**Screenshots**

**Environment (please complete the following information):**
 - OS: 
 - Ionide version:
 - VSCode version:
 - dotnet SDK version:
 - mono / .Net Framework version:

**Additional context**

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce on latest Ionide 5.0 preview.
