### ISSUE TITLE
Find references leads to wrong places in source code

### ISSUE THREAD

**Issue by danyx23** [ionide/ionide-vscode-fsharp#1273]
**Describe the bug**
When using "Find all references" in VS Code in an Fsharp project then the number of references found is correct but the place in the source code that is linked to is wrong - both the point that you navigate to when double clicking it but also the fragment as seen in the find references panel is wrong.

**To Reproduce**
Steps to reproduce the behaviour:
1) I guess this occurs in many projects (it happens in several repos for me) but in case there is something specific about it this one for example exhibits the problem and you can clone it here: https://github.com/OpenRiskNet/registry
2) Navigate to ./src/Shared/Shared.fs and find the type ActiveServices, then execute "Find all References"
3) Observe that in Types.fs there are several references that all link to empty lines (there are some references in this file though at different places)

**Expected behaviour**
Find references should link to the correct place in the source file

**Screenshots**
![find-references-bug2](https://user-images.githubusercontent.com/2772449/71168296-a9d40e00-2256-11ea-91a2-d0426d1c7cba.PNG)

![find-references-bug](https://user-images.githubusercontent.com/2772449/71167610-49909c80-2255-11ea-8b9b-7ef1a755751c.PNG)

Here I searched for all references of the type Table. As you can see, at the bottom of the screen is the place that should have been found, but the highlighted place in the middle of the screen is the point that VS code directs me to.

**Environment (please complete the following information):**
 - OS: Windows 10, german version
 - Ionide version: 4.4.1 (but this happened for a few days maybe even weeks now)
 - VSCode version: 1.41.0
 - dotnet SDK version: 3.0.100
 - mono / .Net Framework version: 4.8

**Additional context**
Please let me know if I can help any further in debugging this issue - thanks for the great work, Ionide is a pleasure to use!

**Comment by Krzysztof-Cieslak** [comment]
This looks like a problems with symbols cache.
Please remove .ionide folder, open Code again, wait a while to repopulate the cache and try again

**Comment by danyx23** [comment]
Ah that did it, thanks! The rebuild process seems to be quite slow, it showed 0 references for everything for such a long time that I suspected something else being broken. But now it has recovered and works, thanks for the suggestion!
