### ISSUE TITLE
Unwanted code formatting

### ISSUE THREAD

**Issue by pkese** [ionide/ionide-vscode-fsharp#1274]
**Describe the bug**

Not having either installed nor configured Fantomas or any similar tools, I've had a large file unexpectedly reformatted.
I've consequently lost formatting (and git diffing) for a huge file that I now need to revert manually line by line.

**To Reproduce**
Steps to reproduce the behaviour:
1. Don't know how this happened (maybe there's a key binding that I accidentally pressed)

**Expected behaviour**
Code formatting should never happen automatically unless it is explicitly enabled (or if it is bound to some keys, user should be asked if they wish to enable such functionality).  
There should be a switch in F# settings that is OFF by default (since it can lead to unwanted and unrecoverable consequences, it should better be enabled explictely).

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Ionide version: 4.4.1
 - VSCode version: 1.41.0
 - dotnet SDK version: 3.1

**Comment by Krzysztof-Cieslak** [comment]
Ionide is integrated with VSCode formatting capabilities. VSCode has an option to do formatting on file save, and I believe it's turned off by default - check `editor.formatOnSave`.

Anyway, we don't control when formatting happens from Ionide, it's on editor side. So closing this one

**Comment by pkese** [comment]
@Krzysztof-Cieslak, fyi

It appeared to be the `[Ctrl]+[Shift]+I` keybinding.

It's the same keybinding that opens developer tools in browser.  
So whenever my mouse focus is in the wrong window and I toggle developer tools in browser, I get F# code garbled.

After I found that, I simply disabled the keybinding in vscode.
