### ISSUE TITLE
memory leak in FSI

### ISSUE THREAD

**Issue by jackfoxy** [ionide/ionide-vscode-fsharp#1276]
**Describe the bug**
Executing memory intensive script in FSI does not recover memory after execution.

**To Reproduce**
Steps to reproduce the behaviour:
1. use https://gist.github.com/jackfoxy/ba315d2190ae563f5a7d40cf72428fcf
2. open file
3. open Windows Task Manger, look at VS Code memory
4. highlight and alt-enter to execute in FSI
5. watch memory usage go up, but it never recovers.
6. execute again and watch more memory disappear

**Expected behaviour**
Expect memory recovery after execution.

**Environment (please complete the following information):**
 - OS: Windows 10 build 18363
 - Ionide version: 4.4.1
 - VSCode version:
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version: n/a

**Additional context**
This is not a problem in Visual Studio 16.4.2. Memory usage goes up during execution, but recovers when execution is done.

**Comment by baronfel** [comment]
We won't be able to solve this without a ton of work, because we only proxy your commands to a subprocess running dotnet FSI. VS and rider use the interactivity APIs provided by the Interactive session and manage the lifecycle of the fsi instance much more directly.

**Comment by Krzysztof-Cieslak** [comment]
Ionide is just calling `fsi.exe` / `dotnet fsi` directly and we don't plan to change it. So this unfortunately won't be fixed.
