### ISSUE TITLE
Difficulty opening a new project due to strange reference errors

### ISSUE THREAD

**Issue by mrakgr** [ionide/ionide-vscode-fsharp#1279]
I created a new console project through the command palette using `F# : New Project` in VS Code, but no matter what I try I am running into strange issues. For example, the `build.fsx` file has 6 type errors, the first of which is...

>The type referenced through 'System.TimeSpan' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib'.

I thought it might be due to not having up to date .NET Core SDK so I got the fresh one and it did not make a difference.

I am not sure what to do here. Since I am at it, let me document various issues I've run into apart from the one above.

1) https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode

I've created a project using `dotnet new console -lang F# -o FirstIonideProject`

```
// Learn more about F# at http://fsharp.org

open System

[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"
    0 // return an integer exit code
```

I am not getting an outright type error for the `open System` statement now that I've installed a new fresh .NET Core install. But when I hover the cursor over the `System`, this is what it says.

```
namespace System
Full name: System
Assembly: System.Xml.XPath.XDocument
```

No way is the assembly right here.

2) Clicking run in the F# Solution Explorer causes the terminal to get cleared immediately. This is regardless of here where it just prints "Hello World from F#!" for a fraction of the second before clearing, or in the other projects where it prevents me from seeing what the error is.

3) Creating a new project has issues. Even if I trigger it through the command palette, what happens is that the Ionide file getting created in the background seems to cancel it, and I have to retry it. I find this confusing.

4) I am trying to use the `> F# : New Project(ProjectScaffold)`. What happens is that the `.ionide` folder appears in the explorer window (apparently triggers by me using the command) and the project creation fails with the error `Creating project failed - directory is not empty`.

5) I can get it to create the project by deleting the `.ionide` folder manually.

6) `#r "paket: groupref FakeBuild //"` gives me the `is not valid assembly name` error.

7) Pretty much every file has errors on the open statements. For example in `init.fsx` the `open Fake.Core` gives me an error even though I have the plugin installed.

8) I am fiddling around with the standard project. For some reason `build.fsx` does not have any errors now, but only deprecated construct warnings. The boilerplate project that I've named `Test`'s `test.fs` has 3 type errors asking me to add references for .NET standard. 

9) I am wondering whether changing the `Fsharp: Use SDK Scripts` has anything to do with these errors? ...Yeah, it seems that the first error (with `build.fsx`) is caused by me checking this as per instructions on the Microsoft Docs.

At least the FSI Interactive itself works, but this hasn't been a great impression on me overall. The regular VS has been driving me crazy with how it autocompletes to keywords suddenly and arbitrarily when I type fast, but I am not sure whether I can do anything to make this run.

I am willing to give it a try though. What should I do here?

**Comment by mrakgr** [comment]
I forgot to mention, all of this is on Windows.

**Comment by mrakgr** [comment]
I forgot, the links to Forge on the http://ionide.io/ site are all broken.

**Comment by Krzysztof-Cieslak** [comment]
`F#: New Project` command has been reworked since this issue and is now using `dotnet new` templates
