### ISSUE TITLE
Ionide sometimes shows completely incorrect suggestions when accessing members

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1281]
Accessing members sometimes gives wrong suggestions:

![image](https://user-images.githubusercontent.com/1781813/71547770-b36f1b80-29a4-11ea-8fe7-6ea6b6a7e2d6.png)

It only seems to happen the first time you try to access members. Subsequent accesses seem to work fine.

**Comment by Krzysztof-Cieslak** [comment]
I'll close in favor of #1289
