### ISSUE TITLE
Missing indentition when using pattern matching via anonymous functions in a pipeline

### ISSUE THREAD

**Issue by maxmuen** [ionide/ionide-vscode-fsharp#1283]
When using `function` in a pipeline the actual patterns are not indented to the `function` keyword but instead are kept inline with it.

I looked into [FormattingConventions.md](https://github.com/fsprojects/fantomas/blob/master/docs/FormattingConventions.md), but have not anything directly related to this issue. The best i could find was the rule 

> Pattern matching of anonymous functions, starting by function, are indented with respect to the function keyword:
> ``` fsharpi
> List.map (function
>           | Abs(x, body) -> 1 + sizeLambda 0 body
>           | App(lam1, lam2) -> sizeLambda (sizeLambda 0 lam1) lam2
>           | Var v -> 1) lambdaList
> ```

**Example**
```fsharp
let expected =
    b
    |> function
       | Some c -> c
       | None -> 0
    |> id

let actual =
    b
    |> function
    | Some c -> c
    | None -> 0
    |> id

```

**Comment by baronfel** [comment]
In this case are you talking about the indent that's suggested when you press <enter> after the function keyword, or the formatting that occurs when you format the entire document?

**Comment by maxmuen** [comment]
after formatting the entire document

**Comment by baronfel** [comment]
Can you raise an issue on the fsprojects/Fantomas repo please? We use that library to do the formatting so any fixed need to happen there first.

In the meantime, if the formatting is causing you problems it can be disabled by adding the `editor.formatOnSave: false` setting to the `[fsharp]` section of your vscode settings.json.

**Comment by maxmuen** [comment]
will do
