### ISSUE TITLE
Types not showing with error "Cached typecheck results not yet available"

### ISSUE THREAD

**Issue by davecarpie** [ionide/ionide-vscode-fsharp#1286]
After installing VSCode and ionide, I expected to see types like I have on other machines, but there are no inline types, navigation or autocomplete.

The Console shows the error `Cached typecheck results not yet available` which seems to me like maybe fsac isn't running but I can see it in Task Manager
![image](https://user-images.githubusercontent.com/8252239/71756200-51e6fb00-2e43-11ea-9606-da3deebb7eb5.png)

It looks like a symbol cache is being created if that is helpful at all.
![image](https://user-images.githubusercontent.com/8252239/71756272-d0dc3380-2e43-11ea-86c2-fa5b821dd27b.png)

 - OS: Windows 10 
 - Ionide version: 4.4.2
 - VSCode version: 1.41.1
 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version: .NET 4.8.03752

**Comment by Krzysztof-Cieslak** [comment]
Issue lack reproduction instruction.
