### ISSUE TITLE
Floats are always reported with measures

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1287]
![image](https://user-images.githubusercontent.com/57396/71961274-4c006980-31f7-11ea-8dab-644ae1191e58.png)

**Comment by Krzysztof-Cieslak** [comment]
Yes, I can repro.

**Comment by Krzysztof-Cieslak** [comment]
This is happening also for decimals.

It seems like a FCS/compiler bug - every decimal and float are reported to have generic argument named `MeasureOne` - so it hits normal generic type formatting case in tooltip formatter. I'm 100% sure it's regression - it wasn't happening in earlier versions of FCS/compiler. 

CC: @cartermp

**Comment by forki** [comment]
@KevinRansom

Krzysztof Cieślak <notifications@github.com> schrieb am Fr., 17. Jan. 2020,
22:58:

**Comment by Krzysztof-Cieslak** [comment]
Fix (workaround hack) in https://github.com/fsharp/FsAutoComplete/pull/582
