### ISSUE TITLE
Intellisense does not show up on first member access

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1289]
Accessing member on a value doesn't appear to show when you first dot into a value - it appears that when you dot into it, the suggestion routine doesn't kick in until afterwards. Then you have to either hit CTRL + SPACE to "force" suggestions, or quickly hit backspace and dot again. If you're too slow between those two keypresses, nothing happens.

In the video below, the first suggestion only appears because I hit CTRL + SPACE. The second one only when I rapidly hit backspace + dot. It seems to be linked to when the red squigglies are shown - without them, nothing happens.

![dotinto](https://user-images.githubusercontent.com/1781813/72523150-76899c80-385f-11ea-8421-ba227428816c.gif)

I don't know if this is related to #1281 (replacing it) or nothing to do with that.

**Comment by Krzysztof-Cieslak** [comment]
Yeah, it's the same issue as #1281

**Comment by ronaldschlenker** [comment]
Any news on this? Since I updated to 4.8 and used all default settings, I have no intelli sense at all (always showing -32603 error in log).

**Comment by ronaldschlenker** [comment]
You are the best, @Krzysztof-Cieslak ! Quadro thumbs up :)

**Comment by isaacabraham** [comment]
And @ThisFunctionalTom !

**Comment by ThisFunctionalTom** [comment]
> 
> 
> And @ThisFunctionalTom !

And @pihai !

**Comment by ronaldschlenker** [comment]
Oh yes - please excuse me @ThisFunctionalTom and @pihai. I simply overlooked you. Thank you very much.
