### ISSUE TITLE
Error on console parsing fsx file

### ISSUE THREAD

**Issue by javiermolinar** [ionide/ionide-vscode-fsharp#1292]
**Describe the bug**
With a fresh install following this tutorial: https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode
I get tons of errors on console when opening an empty fsx file.

Trace error states: "Error opening binary file 'C:\Program Files\dotnet\shared/Microsoft.NETCore.App\3.1.1\Microsoft.DiaSymReader.Native.amd64.dll': C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.1\Microsoft.DiaSymReader.Native.amd64.dll: bad cli header, rva 0"

Use sdk scripts is checked
It works properly for regular fs files in a project.

**Expected behaviour**
Script files should work as fs files.

**Environment (please complete the following information):**
 - OS: Windows 10 professional build  18362
 - Ionide version: 4.5.0
 - VSCode version: 1.41.1
 - dotnet SDK version: 3.1.101

**Comment by Krzysztof-Cieslak** [comment]
CC: @baronfel Another fancy fsi refs case.

**Comment by baronfel** [comment]
@Krzysztof-Cieslak thoughts on bumping FSAC to sdk 3.1.x so we can use `dotnet fsi` and reenable the fsi tests for all platforms? might help catch these more often?

**Comment by javiermolinar** [comment]
After updating to version 4.6 it is working properly
