### ISSUE TITLE
Incorrect multi-line comment display

### ISSUE THREAD

**Issue by drguildo** [ionide/ionide-vscode-fsharp#1295]
"Nested" multi-line comments seem to confuse the parser, even though the compiler doesn't have a problem with them.

![image](https://user-images.githubusercontent.com/9282/73540940-17b04f80-4429-11ea-889c-31f189319f60.png)

**Comment by Krzysztof-Cieslak** [comment]
@MangelMaxime you'll like this one ;-)

**Comment by MangelMaxime** [comment]
The fix is ready in https://github.com/ionide/ionide-fsgrammar/pull/149
