### ISSUE TITLE
Can't add file to project using the tooling

### ISSUE THREAD

**Issue by mastoj** [ionide/ionide-vscode-fsharp#1297]
I can't add a new file to a project using the tooling. 

**To Reproduce**
1. Add a new fs file in a project folder
2. Execute `F#: Add Current File To Project"
3. Nothing happened

**Expected behaviour**
The file should be added to the fsproj file.

**Screenshots**
Gif animation showing that nothing happens.

![ionide error](https://user-images.githubusercontent.com/501424/73616743-94088580-4617-11ea-9b10-fd1a61fc27ae.gif)

**Environment (please complete the following information):**
 - OS: OSX: 10.15.2
 - Ionide version: 4.5.0
 - VSCode version: 1.42.0-insider
 - dotnet SDK version: 3.1.100

**Additional context**
There is a status message saying that the file isn't in a project, and that is accurate since I haven't added it yet.

**Comment by dkpsk** [comment]
I saw the same problem.  
Have you installed .NET core 2.1?

[Ionide calls Forge when adding files to project](https://github.com/ionide/ionide-vscode-fsharp/blob/6601f35eea75577f5fd697a804e558a52cd98efb/src/Components/Forge.fs#L71).   
and [Forge requires dotnetcore 2.1](https://github.com/ionide/Forge/blob/7f67fcdb8a023ad094261b6731976fdf82654089/src/Forge/Forge.fsproj#L4).  
After installed it, it works.

**Comment by mastoj** [comment]
@dkpsk, thanks, that worked.
