### ISSUE TITLE
FSX shows spurious errors when FSAC is on netcore

### ISSUE THREAD

**Issue by akdor1154** [ionide/ionide-vscode-fsharp#1300]
**Describe the bug**
When editing an FSX file, Ionide shows one of two sets of spurious errors related to being unable to find referenced DLLs or something.

**To Reproduce**
- Configure VSCode to use netcore for FSAC (it's like this by default)
- Open VSCode with Ionide in an empty folder
- create 'test.fsx', enter the following:
  ```fs
  open System
  
  printfn "hi"
  ```
- Observe the following highlighted errors:
  ```
  test.fsx:
  - The type 'Object' is required here and is unavailable. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
  - A reference to the type 'System.Object' in assembly 'System.Runtime' was found, but the type could not be found in that assembly
  - A reference to the type 'System.String' in assembly 'netstandard' was found, but the type could not be found in that assembly
  - The value or constructor 'printfn' is not defined.
  ```
- rename 'test.fsx' to 'renamed.fsx'
- observe the following, different, errors:
  ```
  renamed.fsx:
  - A reference to the type 'System.String' in assembly 'netstandard' was found, but the type could not be found in that assembly
  - The value or constructor 'printfn' is not defined.
  ```

**Expected behaviour**
I expect intellisense to work on my file.

**Screenshots**
![image](https://user-images.githubusercontent.com/6732831/73905981-5ba5c780-48f5-11ea-8164-e18494b91202.png)

**Other notes**
I tried building FsAutocomplete from master (fec547d) and pointing ionide at that, but the behaviour was the same.
The FSharp Language Server extension (https://marketplace.visualstudio.com/items?itemName=georgewfraser.fsharp-language-server) works fine
Setting FSAC to net mode works fine (no idea how as I thought I didn't have mono on my machine)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Ionide version: Ionide-fsharp 4.5.0
 - VSCode version: 1.41.1
 - dotnet SDK version: 3.1.101
 - mono / .Net Framework version: not installed

**Comment by baronfel** [comment]
Please make sure the `FSharp.useSdkScripts` setting is set to `true` and verify this case again.

**Comment by akdor1154** [comment]
Hey thanks for the quick reply. Yes, useSdkScripts is true.
Additionally I have tried setting ("Fsi File Path", "Fsi Extra Parameters") to ("dotnet", ["fsi"]), but this makes no difference.

**Comment by brpratt** [comment]
Does the problem go away if you set `FSharp.dotNetRoot` to the base path indicated by `dotnet --info`? I recently saw a similar problem that was resolved by properly setting this value:

https://github.com/ionide/ionide-vscode-fsharp/issues/1306#issuecomment-602059317

**Comment by Krzysztof-Cieslak** [comment]
Seems like setting `dotNetRoot` is indeed correct solution, I can reproduce it on fresh VM.

**Comment by akdor1154** [comment]
Awesome thankyou for looking into this. I'll verify on Monday on my work machine where I saw this.
