### ISSUE TITLE
"Failed to spawn FSI" even though dotnet is in PATH

### ISSUE THREAD

**Issue by drguildo** [ionide/ionide-vscode-fsharp#1307]
**Describe the bug**
When I hit Alt + Enter to send code to FSI I get `Failed to spawn FSI, please ensure it's in PATH`.

`C:\Program Files\dotnet\` is in my PATH and if I fire up PowerShell or cmd and run `dotnet fsi` it works fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new F# project using `dotnet new`
2. Open it in VS Code
3. Write some code
4. Select it and hit Alt + Enter

**Expected behaviour**
An FSI instance starts and evaluates the code that was selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/9282/74603004-956d8f80-50a6-11ea-8748-77df2512bf95.png)

**Environment (please complete the following information):**
 - OS: Windows 10 1909
 - Ionide version: 4.5.0
 - VSCode version: 1.42.1
 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version: N/A

**Comment by Krzysztof-Cieslak** [comment]
Have you set `useSdkScripts` to true?

**Comment by drguildo** [comment]
I hadn't as I didn't realise I had to; it works now. Thanks and sorry for the noise.

Is there a reason this can't be detected?

**Comment by Krzysztof-Cieslak** [comment]
There are some differences between old `fsi.exe` and `dotnet fsi` which could potentially break some users. So we decided in the initial stage keep the old default. 

In Ionide 5.0 we will use `dotnet fsi` as default.
