### ISSUE TITLE
Unable to use fsianycpu.exe which is show stopper when processing large data sets

### ISSUE THREAD

**Issue by denskh** [ionide/ionide-vscode-fsharp#131]
Should use FsiCpuAny.exe by default on windows or let user configure it.

FsiAnyCpu.exe is much more useful on 64bit machine with a lot of memory for data analyse and processing. Currently there is appear to be no way to switch to FsiCpuAny.exe (other than editing extension source code).

**Comment by cloudRoutine** [comment]
we'll gladly accept this enhancement as a PR

**Comment by denskh** [comment]
Sure, will look into it. Are you ok with FsiAnyCpu.exe be default file name for windows platform optionally overwritten in user configuration, ex:  "FSharp.fsiFileName": "fsi.exe".
Configuration override can work for all platforms, not just windows.

**Comment by cloudRoutine** [comment]
currently it'd only be needed for windows, it's `fsharpi` on mono

**Comment by denskh** [comment]
sounds good, will limit configuration to windows platform

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.2.17`
