### ISSUE TITLE
Possible incorrect message for namespace declaration

### ISSUE THREAD

**Issue by gsscoder** [ionide/ionide-vscode-fsharp#1310]
I've a solution (for now with few files) and in namespace statement is shown this error:
`Used to associate a name with a group of related types and modules, to logically separate it from other code.`.

This happens in both of two project files.

As you can see from this shot:
![Screenshot 2020-02-23 at 16 28 54](https://user-images.githubusercontent.com/1194228/75114855-1655f980-565a-11ea-8a4d-8f41e0e197ce.png)

I suppose it is generated from your great **VSCode** extension. If not I'm sorry to posting here.

Files are correctly added in project.
```csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Model.fs" />
    <Compile Include="Definition.fs" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>../../artifacts/TerraPipe.Core/Debug</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>../../artifacts/TerraPipe.Core/Release</OutputPath>
  </PropertyGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

The project **builds successfully**.

Thank you.
Regards,
Giacomo S. S.

**Comment by MangelMaxime** [comment]
Hello @gsscoder ,

the thing you are quoting is actually the tooltip message which provide a description for `namespace` keyword here.

The actual error is shown just below "No .fsproj or .fsx file references".

**Comment by gsscoder** [comment]
Thank you for replying @MangelMaxime,
yes file were in the right place.

I tried restarting VSCode various time, without effects. But at the next boot, problem automatically solved!
