### ISSUE TITLE
Add support for Jupyter Notebooks like the Python extension

### ISSUE THREAD

**Issue by ScottHutchinson** [ionide/ionide-vscode-fsharp#1311]
We now have F# in Jupyter Notebooks, but we still need an editor with auto-completion like Ionide.

**Comment by Krzysztof-Cieslak** [comment]
F# in notebooks is handled by MSFT

**Comment by texastoland** [comment]
My Google fu is failing me! Any reference for integration?

**Comment by baronfel** [comment]
https://github.com/dotnet/interactive is where all of that development takes place.

**Comment by texastoland** [comment]
My bad [I found it](https://github.com/dotnet/interactive/blob/fd0467903b9306fe402b17b2befa01a012b6888d/src/dotnet-interactive-vscode/insiders/README.md) immediately after (the doc had moved) 🤦🏼‍♂️
