### ISSUE TITLE
Link metadata element inside ItemGroup/Compile items should (maybe) be supported

### ISSUE THREAD

**Issue by maxild** [ionide/ionide-vscode-fsharp#1312]
Hi,

I am working with the Typeprovider SDK. The template contains

```xml
<ItemGroup>
    <Compile Include="..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fsi">
      <Paket>True</Paket>
      <Link>paket-files/ProvidedTypes.fsi</Link>
    </Compile>
    <Compile Include="..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs">
      <Paket>True</Paket>
      <Link>paket-files/ProvidedTypes.fs</Link>
    </Compile>
    .
    .
</ItemGroup>
```

when using paket to fetch the ProvidedTypes API from Github. Ionide cannot load a project with linked files. If a change the above to

```xml
<ItemGroup>
    <Compile Include="..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fsi" />
    <Compile Include="..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs" />
    .
    .
  </ItemGroup>
```

The project does load fine.

In the msbuild docs the `Link` metadata for the ConpileItem is documented as

> Link: Optional string. The notational path to be displayed when the file is physically located outside the influence of the project file.

This makes sense because the files are loaded from the `paket-files` subtree.

I can live without the Link metadata. I am just reporting the problem, so that the maintainers of the project system can decide if this should be supported.

## Addendum

Silly me. The compile items 

```xml
<ItemGroup>
    <Compile Include="..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fsi">
      <Paket>True</Paket>
      <Link>paket-files/ProvidedTypes.fsi</Link>
    </Compile>
    <Compile Include="..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs">
      <Paket>True</Paket>
      <Link>paket-files/ProvidedTypes.fs</Link>
    </Compile>
    .
    .
</ItemGroup>
```

are generated by paket. So ionide need to be able support those when `paket.dependencies` contain

```
github fsprojects/FSharp.TypeProviders.SDK src/ProvidedTypes.fsi
github fsprojects/FSharp.TypeProviders.SDK src/ProvidedTypes.fs
```

and `paket.references` contain

```
File:ProvidedTypes.fsi
File:ProvidedTypes.fs
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed with 5.0
