### ISSUE TITLE
Intellisense not always working when analyzers are enabled

### ISSUE THREAD

**Issue by Zaid-Ajaj** [ionide/ionide-vscode-fsharp#1314]
I am experiencing degraded intellisense experience when using **locally installed** in the workspace analyzers via Paket. Degraded in the sense that intellisense does not work unless I set `FSharp.analyzersPath` back to an empty array, in which case the intellisense starts to work again like nothing happend. 

I can't know for sure that analyzers the actual *cause* of degradation but I am guessing it has to do with them because when I disable them (via `FSharp.enableAnalyzers: false`) then intellisense starts to work again. 

I tried to restart VS Code. Tried to delete `.ionide`, `bin` and `obj`, then restart VS Code but with no luck. I look the logs of FSAC and I see
```
Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```
even though `.ionide\symbolCache.db` is just made fresh from the project after I deleted it. Are there any instructions to follow when I see these logs? 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/Zaid-Ajaj/AnalyzerTest
2. Clone the repo 
3. Install analyzers via `paket restore`
4. Open repo using VS Code
5. Observe that intellisense is not working

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.6.1
 - VSCode version: 1.42.1
 - dotnet SDK version: 3.1.101
 - mono / .Net Framework version: N/A

**Comment by Krzysztof-Cieslak** [comment]
I remember something like that happening to me when Ionide accidentally tried to load multiple versions of the same analyzer (one targeting netstandard2.0, not here if it’s connected). Can yo check if dirs you give to Ionide are not containing multiple dlls with same analyzer?

**Comment by Zaid-Ajaj** [comment]
Hello @Krzysztof-Cieslak, I have just checked that and there only one analyzer, even used the absolute path to my locally built analyzer which I used to test with but now doesn't work anymore. Maybe it has do with some FSAC version update that updated F# compiler services and now the versions are not aligned anymore?

**Comment by Krzysztof-Cieslak** [comment]
Heh, @baronfel, have we messed something?

**Comment by baronfel** [comment]
Quite likely that the analyzers SDK needs to be explicitly updated. I can take a look.

**Comment by baronfel** [comment]
Probably means we need to have an LSP test for analyzers to catch this in the future, similar to what we need to have for the FAKE features break.

**Comment by baronfel** [comment]
once https://github.com/ionide/FSharp.Analyzers.SDK/pull/15 is merged/released we should be able to update and have things just work

**Comment by Krzysztof-Cieslak** [comment]
@Zaid-Ajaj can you try updating SDK to `0.3.1` and Ionide to `4.6.3` ?

**Comment by Zaid-Ajaj** [comment]
@Krzysztof-Cieslak & @baronfel Thanks a lot for updating dependencies. However, still no luck 😞 I have updated the analyzer to the exact required dependencies and latest ionide was unable to parse/type-check the project. Unless I disable the analyzers feature, then intellisense and auto-complete comes back online again. 

I was to able to debug this a bit. In my unit tests, there is a "context bootstrapper" in file [Analyzer.fs](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer/blob/master/tests/NpgsqlFSharpAnalyzer.Tests/Analyzer.fs) that simulates what the SDK does to parse and type-check a F# file in a test project included in the repo. There, the project cracking is also failing (and all unit tests) in this [typeCheckFile](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer/blob/master/tests/NpgsqlFSharpAnalyzer.Tests/Analyzer.fs#L39-L51) function. Printing errors from the parse results will give the following error when cracking the project:

> startup (1,1)-(1,1) parameter error internal error: BuildFrameworkTcImports: no resolution of 'C:\projects\NpgsqlFSharpAnalyzer\tests\NpgsqlFSharpAnalyzer.Tests\bin\Debug\netcoreapp2.0\FSharp.Core.dll'

This looks very weird 🤔 it looks like project cracking fails because it can't find a reference to a dependency of the analyzer itself where as the project has no knowledge or reference to anything that has to do the analyzers. This is how the test project is defined:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="parameterTypeMismatch.fs" />
    <Compile Include="readAttemptIntegerTypeMismatch.fs" />
    <Compile Include="syntacticAnalysisSimpleQuery.fs" />
    <Compile Include="syntacticAnalysisExecuteScalar.fs" />
    <Compile Include="syntacticAnalysisProcessedList.fs" />
    <Compile Include="semanticAnalysis-missingColumn.fs" />
    <Compile Include="semanticAnalysis-missingParameter.fs" />
    <Compile Include="semanticAnalysis-typeMismatch.fs" />
    <Compile Include="syntacticAnalysis-literalStrings.fs" />
    <Compile Include="semanticAnalysis-redundantParameters.fs" />
    <Compile Include="syntacticAnalysis.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.FSharp" Version="3.0.0" />
  </ItemGroup>

</Project>

```

**Comment by Zaid-Ajaj** [comment]
If it helps you to debug the problem, I compiled my analyzer against the required versions of FCS and the analyzers SDK using `dotnet publish -c Release` and put the assembly files into [this repository](https://github.com/Zaid-Ajaj/AnalyzerReleaseDlls). This way, you could point the `FSharp.analyzersPath` config property to these dlls to debug the infrastructure. 

I know it is not secure to just download some random dlls from the internet on your computer, if you want I could push source code of the updated analyzer into the repository of `NpgsqlFSharpAnalyzer` and you could you build it yourself, let me know how I could help with this :pray: thanks in advance

**Comment by ctaggart** [comment]
I'm getting that same error, but I don't have analyzers enabled. IntelliSense is not working: Error:

```
[Error - 4:59:20 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

vscode 1.42.1
Ionide-fsharp 4.6.3
.net core 3.1.101
mono: not installed

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/
```

settings.json
```
    "FSharp.msbuildHost": ".net core"
```

**Comment by ctaggart** [comment]
It is a new day and it is now working for me. I don't know why. Sorry for the noise.

**Comment by Krzysztof-Cieslak** [comment]
Analyzers should be working again in `4.6.4`

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @Krzysztof-Cieslak and @baronfel :heart: I have confirmed that it works as expected now The logging seems much better now so we easily find what goes wrong quickly
