### ISSUE TITLE
Internal Error  destNullableTy

### ISSUE THREAD

**Issue by tick-rick** [ionide/ionide-vscode-fsharp#1315]
A bug appears (entire file red squiggles, see screenshot) when using OpenApiClientProvider. On hovering the error is `internal error: destNullableTy: not a Nullable type (Failure) F# Compiler(73)`. This does not occur when running dotnet build/run, so it appears that it may be ionide or FSAC related.

**To Reproduce**
Steps to reproduce the behaviour:
1. dotnet new console -lang F# && dotnet add package SwaggerProvider
2. Save this to folder as json [schema.txt](https://github.com/ionide/ionide-vscode-fsharp/files/4265308/schema.txt)
3. Use the following repro code:
```
open SwaggerProvider
type Api = OpenApiClientProvider<"schema.json">
let h = Api.Heartbeat([||], None)
```
4. dotnet build and reload vscode

**Expected behaviour**
There should be no errors.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/50384876/75512179-af16bb80-5a44-11ea-93b3-6d862b2b5378.png)

**Environment (please complete the following information):**
 - OS:  Debian
 - Ionide version: 4.6.2
 - VSCode version: 1.42.1
 - dotnet SDK version: 3.1.102

**Additional context**

**Comment by forki** [comment]
Can you please report this to https://github.com/dotnet/fsharp/issues? It's a bug in the compiler itself. Thank you

**Comment by tick-rick** [comment]
Moved, closing ty.
