### ISSUE TITLE
Version 4.6.1 has broken the FSharp.Data.Npgsql type provider in my project

### ISSUE THREAD

**Issue by JeffreyPalmer** [ionide/ionide-vscode-fsharp#1316]
**Describe the bug**
Up to and including 4.6.0, one of my projects that used the FSharp.Data.Npgsql Postgres type provider was able to properly represent database types and structure, but all versions after 4.6.0 fail with the following error:

```
The type provider '/Users/jeff/.nuget/packages/fsharp.data.npgsql/0.1.49-beta/lib/netstandard2.0/FSharp.Data.Npgsql.dll' 
reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers
to a designer assembly 'FSharp.Data.Npgsql.DesignTime' which cannot be 
loaded or doesn't exist. Could not load file or assembly 
'/Users/jeff/.nuget/packages/fsharp.data.npgsql/0.1.49-beta/lib/netstandard2.0/FSharp.Data.Npgsql.DesignTime.dll'. 
The system cannot find the file specified.
F# Compiler(3031)

Referenced assembly '/Users/jeff/.nuget/packages/fsharp.data.npgsql/0.1.49-beta/lib/netstandard2.0/FSharp.Data.Npgsql.dll'
has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute'
but no public type provider classes were found
F# Compiler(3005)
```

(That is the error message that pops up under the namespace declaration that contains the use of the type provider.) I looked in that location and it's true that there is no such named file in that directory (it's elsewhere in the package tree). However, there never has been and only recent versions fail in this manner.

**To Reproduce**

I can reproduce this behavior at will by downgrading/upgrading the Ionide version in VS Code.

**Expected behaviour**
No error is shown, and I am able to interact with the type provider types as expected.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS Mojave
 - Ionide version: 4.6.1+
 - VSCode version: 1.42.1
 - dotnet SDK version: 3.1.102
 - mono / .Net Framework version: 3.1.2

**Additional context**
Happy to try to help debug. I'm relatively new to this ecosystem, but I'm happy to try any suggestions you may have.

Thanks for the great project!

**Comment by baronfel** [comment]
When you say the file is elsewhere on the package tree, can you give us the actual path?

**Comment by JeffreyPalmer** [comment]
Absolutely. The file `FSharp.Data.Npgsql.DesignTime.dll` is actually present in 

```
~/.nuget/packages/fsharp.data.npgsql/0.1.49-beta/typeproviders/fsharp41/netcoreapp2.0
```

**Comment by Krzysztof-Cieslak** [comment]
This was moved to the FsAutoCompete repository, closing here
