### ISSUE TITLE
FSI "Rich" output panel 

### ISSUE THREAD

**Issue by pablofrommars** [ionide/ionide-vscode-fsharp#1317]
**Is your feature request related to a problem? Please describe.**

ionide is already a very valuable tool for data scientists and ML practitioner. It would benefit from a Panel where "objects" could be rendered to assist during data exploration. Potential use cases:

* Watch collections or variable
* Dump SVG charts
* Format evaluation metrics returned by ML.NET models...

A sort of light "jupyter notebook" without the bells and whistles.

**Describe the solution you'd like**

Be able to register functions formatting a type to rich content" (HTML fragment, SVG, etc...)
The extension would then send the content to be appended to a vscode webview (ie. panel).

Extend what FSI.AddPrinter does?

**Describe alternatives you've considered**

I am considering creating a separate extension that would "watch" a directory for new files to render to a vscode webview. A package would provide a display function to "push" content to this directory. 

I currently dump [charts](https://github.com/pablofrommars/GGNet) to disk and use the [vscode-svgviewer](https://github.com/cssho/vscode-svgviewer) to preview.

**Additional context**

Looks like the branch fsi-watcher provides good inspiration on how to implement the feature.

**Comment by ronaldschlenker** [comment]
Also, have a look at [Hydrogen for Atom](https://nteract.gitbooks.io/hydrogen/), where you can inline plots, tables, etc.

**Comment by pablofrommars** [comment]
Here is a little mock up of how it could look like (quick and dirty extension for now):

![image](https://user-images.githubusercontent.com/3967884/76170076-e5f47c00-617e-11ea-9e02-071f271713b6.png)

**Comment by Krzysztof-Cieslak** [comment]
> Also, have a look at Hydrogen for Atom, where you can inline plots, tables, etc.

I have another pretty good Atom example - http://tomasp.net/blog/2016/fslab-ionide/

**Comment by pablofrommars** [comment]
Hi!

The simple vscode extension I created does it for me. I can register my formats (calls to fsi.addPrinter that basically create files to a directory watched by the extension) in a script that gets loaded thanks to the setting FSharp.fsiExtraParameters. I can make it available if anyone is interested.

Feel free to close the issue if my feature request is beyond the scope of where ionide is heading.

Thanks to anyone involved, this is an amazing project!

**Comment by ronaldschlenker** [comment]
I’m interested in your extension @pablofrommars. Do you have it somewhere open sourced? Or can you publish the VS code extension directly?

**Comment by pablofrommars** [comment]
Hi @ronaldschlenker,

Have a look [here](https://github.com/pablofrommars/fsharp-notebook) and feel free to comment over there as I don't want to hijack this thread with too many details. Thanks for your interest.

![demo](https://user-images.githubusercontent.com/3967884/76450045-72947980-63cd-11ea-9aa7-b7b341fc8b52.gif)

**Comment by Krzysztof-Cieslak** [comment]
This is handled partially by F# Literate support, and partially by the F# support in .NET Notebooks.
