### ISSUE TITLE
Formatting doesn't respect tabSize setting in VSCode

### ISSUE THREAD

**Issue by nirvinm** [ionide/ionide-vscode-fsharp#1321]
Formatting an F# file using **Ctrl+Shift+I** does not respect **editor.tabSize** settings. I have following settings specific to my workspace if it matters.

`
    "editor.tabSize": 2,
    "FSharp.smartIndent": true
`

**Comment by Krzysztof-Cieslak** [comment]
Formatting in Ionide is not using VSCode settings but Fantomas settings - https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#--config-path-to-file-or-folder

**Comment by nirvinm** [comment]
Then Ionide should atleast provide settings to change `Fantomas` config path. Currently there's no way I can make `Ctrl + Shift + I` to respect 2 space tab.
