### ISSUE TITLE
Add hotkey or command to jump to .fsproj above current file location.

### ISSUE THREAD

**Issue by ZaymonFC** [ionide/ionide-vscode-fsharp#1323]
**Is your feature request related to a problem? Please describe.**
No. This is not a big issue but it would be really nice to have a hotkey or command to search up the file tree from the current directory and open the first found `.fsproj` file.

**Describe alternatives you've considered**
Just clicking the `.fsproj` file or using `cmd+p` to search for the file.

**Comment by Krzysztof-Cieslak** [comment]
Hey, thanks for the suggestion but I don't think we gonna do that - I just don't see too much value over just using solution/file explorer or using built-in file search. 

Actually there's even one more way. With F# file open in the status bar, on the right-hand side, there is a status bar item displaying project to which file belongs - if you click it, it'll open  `fsproj` file.

![image](https://user-images.githubusercontent.com/5427083/79228853-6a16df00-7e62-11ea-9919-3fc8a233324c.png)

**Comment by ZaymonFC** [comment]
I did not know that! Thanks @Krzysztof-Cieslak
