### ISSUE TITLE
I have Ionide-fsharp 4.7.0 and I can't move or rename files via the gui

### ISSUE THREAD

**Issue by bradphelan** [ionide/ionide-vscode-fsharp#1325]
I have Ionide-fsharp 4.7.0 and I can't rename files in my project. 

I try to rename the highlighted file from XOReport.fs to Report.fs and it doesn't do anything

![2020-03-16_08-01-56](https://user-images.githubusercontent.com/17650/76730911-825ce680-675c-11ea-8120-fce2f5cde5d3.gif)

Neither does moving a file up or down in the list. Seems to be a general problem with the project view

![2020-03-16_08-06-35](https://user-images.githubusercontent.com/17650/76731188-221a7480-675d-11ea-97bd-e9a784026592.gif)

_Originally posted by @bradphelan in https://github.com/ionide/ionide-vscode-fsharp/issues/1173#issuecomment-599375520_

**Comment by bradphelan** [comment]
For info the repository is an SVN repository. Maybe there is a problem here.

**Comment by Krzysztof-Cieslak** [comment]
Can you go to the `Output` tab, pick `Forge` and post anything that's logged there?

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed with 5.0
