### ISSUE TITLE
Load fails with top-level comment in .fsproj file

### ISSUE THREAD

**Issue by schorg** [ionide/ionide-vscode-fsharp#1331]
**Describe the bug**
A top-level XML comment in the .fsproj-file leads to "load failed".

**To Reproduce**
The following project cannot load.
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Here comes my license -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```
**Expected behaviour**
The project should load.
If I delete the top-level comment (my license) the project loads.
If move the comment inside the Project tags the project also loads.

**Environment:**
 - OS: MacOS Catalina
 - Ionide version: 4.8.1
 - VSCode version: 1.43.2
 - dotnet SDK version: 3.1.200
 - mono / .Net Framework version: 6.8.0.123

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed with 5.0
