### ISSUE TITLE
Building locally requires dotnet core 2.0 SDK

### ISSUE THREAD

**Issue by HoraceGonzalez** [ionide/ionide-vscode-fsharp#1333]
This is more of an issue with the CONTRIBUTING.md instructions than a bug. When cloning and running `./build.sh` on a fresh machine (w/t only the latest dotnet sdk installed), an error message appears:

```
Starting target 'RunScript'
src> "/usr/share/dotnet/dotnet"  fable webpack -- --config webpack.config.js (In: false, Out: false, Err: false)
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      3.1.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      5.0.0-preview.1.20120.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.0&arch=x64&rid=ubuntu.18.04-x64
```
As you can see, I've only got the 3.1 and 5.0 preview sdks installed. Installing the latest 2.0 sdk v2.1.202 fixed the issue. 

I'd be happy to update the documentation, but I'd wanted to get your advice on how to approach this. Currently, it appears ionide requires *two* versions of the sdk to be installed:

    - 3.1.101 per `global.json`
    - 2.0.0 for fable

My hunch is that most new devs probably won't have 2.0 installed on their machines (for example, if they installed using `apt-get` on ubuntu like me). In order to get this older version, I had to uninstall dotnet and reinstall using the `dotnet-install.sh` script. I could write up some instructions for this as well, but I'm wondering if there's a more user-friendly option. I know it's possible to install the missing sdk version from fake, but I'm not sure if it's actually persisted once the build script exits.

What do you suggest?

**Comment by baronfel** [comment]
@Krzysztof-Cieslak do you think we could bump FSAC up to netcoreapp3.1 and this repo accordingly? It's been a 2.1/2.0 app for _ages_.

**Comment by Krzysztof-Cieslak** [comment]
This shouldn't be a case any more.
