### ISSUE TITLE
Symbols cache is built on every project open with vscode

### ISSUE THREAD

**Issue by danielo515** [ionide/ionide-vscode-fsharp#1335]
Issue Type: <b>Bug</b>

I just installed Ionide-fsharp and on all the projects I had opened with VSCode a new folder `.ionide` with a `.db` file inside appeared. I think this should only happen for F# projects.

Regards

Extension version: 4.8.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv|-psn_0_381021|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by danielo515** [comment]
Probably a duplicate of #1041

**Comment by Krzysztof-Cieslak** [comment]
Yes, closing as duplicate
