### ISSUE TITLE
Massive slowdown in v 4.8

### ISSUE THREAD

**Issue by ntwilson** [ionide/ionide-vscode-fsharp#1337]
**Describe the bug**
Has anyone else experienced a massive slowdown in solution load time starting in v. 4.8?  In 4.7 my solution of 16 .fsproj files and 2 .csproj files can load in about 30 sec to a minute (as in all fsproj files are loaded in the solution explorer and Intellisense is working).  In v4.8 and v4.8.1 loading the same solution can take 15-30 min.  

**Environment (please complete the following information):**
 - OS: Windows 
 - Ionide version: 4.8.0 & 4.8.1
 - VSCode version: 1.43.2
 - dotnet SDK version: 3.1.101
 - mono / .Net Framework version: 4.7.2 is installed, but my solution is using 4.7.1

**Additional context**
Could this be related to the presence of the 2 C# projects in my solution?

**Comment by ntwilson** [comment]
Unfortunately I can't share my repo.  I'm happy using 4.7 for now, or if others are experiencing the problem and there's an interest in diagnosing this further, I can try to make an open repo that reproduces the issue.  (I don't want to do that if no one else is experiencing the problem though).

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in 4.11
