### ISSUE TITLE
Support new reference syntax in scripts (.NET 5)

### ISSUE THREAD

**Issue by secana** [ionide/ionide-vscode-fsharp#1341]
If the new reference syntax for NuGet packages in F# scripts with .NET 5 is used, the import is not recognized by the VS Code/Ionide.

Example: script.fsx
```fsharp
#r "nuget: SharpYaml"
open SharpYaml.Serialization
```

Gives the error message:

```powershell
The namespace or module 'SharpYaml' is not defined.F# Compiler(39)
The namespace or module 'SharpYaml' is not defined.(39: typecheck)
```

![image](https://user-images.githubusercontent.com/12230822/78935184-886c8b80-7aac-11ea-8775-82afbb58d536.png)

The script itself is executable with `dotnet fsi --langversion:preview .\script.fsx`. The reference is just not recognized by the IDE.

**Comment by baronfel** [comment]
This will be supported when FCS 35 releases along with the FSharp.DependencyManager.Nuget package. I'll try to do that this weekend. There will be a long tail of other dependencies, like fsharplint and fantomas, that also need to update, so this could take a while.

**Comment by realvictorprm** [comment]
@baronfel anything I could help with?

**Comment by baronfel** [comment]
This should be supported now

**Comment by Krzysztof-Cieslak** [comment]
It's not released due to https://github.com/fsharp/FsAutoComplete/issues/593 and https://github.com/fsharp/FsAutoComplete/issues/594

**Comment by realvictorprm** [comment]
Thanks for the update @baronfel & @Krzysztof-Cieslak. These bugs are really a blocker :(

**Comment by Krzysztof-Cieslak** [comment]
This should be enabled in `4.10`... but we'll probably need one more fix to support .Net 5 previews correctly.

**Comment by ovatsus** [comment]
I've tried this in 4.11.1 and it's still not working, even if I have "FSharp.fsiExtraParameters": [ "--langversion:preview" ] in settings.json

**Comment by ovatsus** [comment]
Re-instaling the .net core sdk 5 preview fixed it, so never mind

**Comment by secana** [comment]
Unfortunately doesn't work for me. I've Ionide 4.11.1 installed and set the "FSharp.fsiExtraParameters": [ "--langversion:preview" ] in settings.json. I've reinstalled .NET Core Preview 5.4 but I'm still getting

```
Package manager key 'nuget' was not registered in [c:\Users\x\.vscode\extensions\georgewfraser.fsharp-language-server-
0.1.27\src\FSharpLanguageServer\bin\Release\netcoreapp3.0\win10-x64\publish; c:\Users\x\.vscode\extensions\georgewfraser.fsharp-language-server-
0.1.27\src\FSharpLanguageServer\bin\Release\netcoreapp3.0\win10-x64\publish\], []. Currently registered: 
```

F# Snipped
```fsharp
#r "nuget: FSharpPlus"
open FSharpPlus
```
The script runs fine when executed from command line with the preview option.

Am I doing anything wrong or is there some more information you need to look into that?

**Comment by baronfel** [comment]
@secana your error message says that you're using fsharp-language-server here, not ionide. That is a completely different extension, and I'm not sure it has been updated to support #r nuget.

**Comment by secana** [comment]
@baronfel you are right! Uninstalling the `F# Language Server` extension solved the issue. Thx for pointing that out. Kind of obvious now...

**Comment by vilinski** [comment]
what can be wrong if I get no problems with `#r "nuget: FSharpPlus"`
but red understriked `open FSharpPlus`?
<img width="784" alt="grafik" src="https://user-images.githubusercontent.com/259479/84070458-76379c80-a9cc-11ea-866d-6c222d0d0e1a.png">

**Comment by baronfel** [comment]
It's important to understand that right now `#r "nuget"` is _slow_. The F# team has it on their work plan for the next three weeks to look at this in greater detail.

Aside from that detail, it's also important to understand that you'll never see red squigglies on the #r declaration itself if it is valid in structure. Instead you'll see red squigglies on the `open` statements if the restore hasn't occurred yet, or the nuget provider is still resolving dependencies, etc.  The best I can suggest is to wait for an additional time longer, or check the output logs for Ionide for more details. There should also be upcoming work from the F# team around logging/status of the nuget provider, so we can give you more details in these scenarios.  The feature is in preview, however, and there will be rough edges like these.
