### ISSUE TITLE
Colouration for functions incorrectly includes enclosing namespace, type and module

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1342]
The following code incorrect highlights the entire path in the "function" colour:

```fsharp
System.IO.Directory.GetFiles "myfolder"
```

![image](https://user-images.githubusercontent.com/1781813/79050588-503f8700-7c2b-11ea-8cbe-141f032d0aa8.png)

However, the following correctly understands that `Directory` is a type and highlights that differently to `GetFiles`

```fsharp
open System.IO
Directory.GetFiles "myfolder"
```

![image](https://user-images.githubusercontent.com/1781813/79050599-59c8ef00-7c2b-11ea-8ff2-6e83d0f0dd02.png)

**Comment by isaacabraham** [comment]
For methods on records and fields this also seems to get confused, where `row` is an anonymous record and e.g. `Recovered` is an `int` field.

![image](https://user-images.githubusercontent.com/1781813/79050710-25096780-7c2c-11ea-8311-4c838c45aa70.png)

**Comment by Krzysztof-Cieslak** [comment]
This seems to be working on latest Ionide 
<img width="522" alt="Screenshot 2021-11-19 at 16 53 34" src="https://user-images.githubusercontent.com/5427083/142652134-fdd44bf2-7fa7-4001-82ff-0a95e26d504f.png">
