### ISSUE TITLE
Colouration: Property accessors do not get highlighted

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1343]
Whilst definitions of properties get correctly highlighted, usages of properties do not:

![image](https://user-images.githubusercontent.com/1781813/79050662-e7a4da00-7c2b-11ea-8c98-c2aa14d4b070.png)

**Comment by Krzysztof-Cieslak** [comment]
Usages and definitions are now highlighted the same: 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/5427083/178490611-4a7ffdc8-7659-47b9-b769-135eab3d5948.png">
