### ISSUE TITLE
Disable semantic highlighting

### ISSUE THREAD

**Issue by charlieturndorf** [ionide/ionide-vscode-fsharp#1345]
Hi! I'm wondering if there's a way I can turn off semantic highlighting.

I appreciate how much work went into this feature, but sadly I find the colors distracting.

I don't see an existing way to turn off highlighting. Perhaps a setting could be added?

Thanks for your hard work!

**Comment by baronfel** [comment]
You can control semantic highlighting via the following setting: `"editor.semanticHighlighting.enabled"`

**Comment by MangelMaxime** [comment]
If you want to disable it only for F# you can use:

```fs
    "[fsharp]": {
        "editor.semanticHighlighting.enabled": false
    }
```
