### ISSUE TITLE
Formatting Settings

### ISSUE THREAD

**Issue by bmingles** [ionide/ionide-vscode-fsharp#1346]
I would like to be able to have more control over the auto formatting features provided by the Ionide plugin. For example, for some projects I'd like to be able to change the 4 spaces indentation to 2. I have read that Ionide uses fantomas under the hood which seems to surface more configuration options. Would it be possible to surface these via plugin settings?

**Comment by Krzysztof-Cieslak** [comment]
Ionide should automatically find and load Fantomas configuration file (https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#--config-path-to-file-or-folder) put in the root of your workspace/solution or next to the project file. We don't plan to expose Fantomas settings via plugin settings.

**Comment by Kingju777** [comment]
Old Link:
https://github.com/fsprojects/fantomas/blob/v4.7.9/docs/Documentation.md
New Doku:
https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html

Short:
file: `.editorconfig` in root of your workspace/solution or next to the project file
```.editorconfig
[*.{fs,fsx}]
max_line_length=100
```
