### ISSUE TITLE
Inconsistent syntax highlighting when matching brackets and using functions

### ISSUE THREAD

**Issue by Zaid-Ajaj** [ionide/ionide-vscode-fsharp#1349]
**Describe the bug**
Syntax highlighting gives inconsistent colors to brackets of lists and sometimes ignores the highlighting of the functions used inside the code.

Use this snippet to reproduce the problem:
```fs
module List =
    let create (xs: 'a list) = xs

module Func =
    let run f = f()

let example =
    List.create [
        List.create [
            Func.run (fun () -> printfn "Hello")
            unbox (fun () -> printfn "Hello")
        ]
    ]

```
**Expected behaviour**
 - Matching brackets should have the same color.
 - Functions inside these lists should have syntax highlighting

**Screenshots**
![example-list](https://user-images.githubusercontent.com/13316248/80026047-ca042a00-84e1-11ea-8a2e-ae181b2dead8.png)

Notice that the brackets have different colors (white, blue) and that the lambda within `Func.run` has no syntax highlighting at all. 
 
In practice, this kind highlighting issue shows up a lot in code written with Feliz

![feliz-braket-coloring](https://user-images.githubusercontent.com/13316248/80026117-e2744480-84e1-11ea-92d6-24f6a0fa6a37.png)

Of course, this is no big deal for me as a happy user of Ionide, just reporting to track the problem :smile: 

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.9.0
 - VSCode version: 1.44.1
 - dotnet SDK version: 3.1.1.0
 - mono / .Net Framework version: N/A

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce it on Ionide 5.0-preview03

![image](https://user-images.githubusercontent.com/5427083/102202765-026cd400-3ec8-11eb-87eb-8fdc6c3d93bd.png)

**Comment by Zaid-Ajaj** [comment]
It is indeed fixed in latest for a while, thanks a lot @Krzysztof-Cieslak ❤️
