### ISSUE TITLE
Create Guid Command

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-vscode-fsharp#135]
Basically what the VS tool does

![](http://i.imgur.com/J1oCUsM.png)

we don't need all of those formats, maybe some config options in the user prefs for a default format

the ux could be after the command is executed a notification bar appears at the top 
```
new Guid "{6D39E137-512B-4447-86E7-EAB1057215E1}" added to clipboard
```

as long as the notification can automatically dismiss itself after a few seconds.

**Comment by Krzysztof-Cieslak** [comment]
https://marketplace.visualstudio.com/items?itemName=nwallace.createGUID  ??

**Comment by cloudRoutine** [comment]
You want to take it as a dependency? It comes up enough in .net programming that we should have it OOB.

**Comment by Krzysztof-Cieslak** [comment]
I don't want it all if there is other plugin doing the same.
