### ISSUE TITLE
Encapsulation of arrows broken in tooltips

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1353]
![image](https://user-images.githubusercontent.com/57396/80524402-d5e36680-898f-11ea-9827-db3049d962fd.png)

**Comment by MangelMaxime** [comment]
When reworking the TipFormatter I removed the code which removed the escaped string and forgot to re-apply it.

https://github.com/fsharp/FsAutoComplete/pull/446/files#diff-327bfe77ac6aab16c76a86a920b8ea5aL308

Before sending the tooltip we need to do a place to replace these escaped characters:

```fs
"&lt;", "<"
"&gt;", ">"
```

and perhaps also these ones too:
```fs
"&quot;", "\""
"&apos;", "'"
"&amp;", "&"
```

**Comment by MangelMaxime** [comment]
I am finally taking a look at this issue.

**Comment by baronfel** [comment]
Closing this as Maxime has has fixed this for us:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/573979/119277119-63b97180-bbe3-11eb-8a5d-70ce924f55c3.png">
