### ISSUE TITLE
Info-panel does not show summary from triple-slash comments

### ISSUE THREAD

**Issue by dbrattli** [ionide/ionide-vscode-fsharp#1355]
**Describe the bug**
Info-panel does not show summary from triple-slash `///` comments. To get a description the comment must be inside `<summary></summary>` xml tags.

**Expected behaviour**
I would expect that comments like:

```fs
/// Create XML view
```
generates the same description as:
```fs
/// <summary>Create XML view</summary>
```

**Screenshots**

Triple-slash comments does not generate **Description** in info-panel:
<img width="657" alt="Screenshot 2020-05-01 at 11 51 16" src="https://user-images.githubusercontent.com/849479/80797563-701af880-8ba2-11ea-9773-422bff98b1c9.png">

Triple-slash with summary element generate **Description** in info-panel:
<img width="657" alt="Screenshot 2020-05-01 at 11 58 45" src="https://user-images.githubusercontent.com/849479/80797841-2848a100-8ba3-11ea-83dc-b5f78b16b34c.png">

**Environment (please complete the following information):**
 - OS: OS X Catalina
 - Ionide version: 4.10.0
 - VSCode version: 1.44.2
 - dotnet SDK version: 3.1.210
 - mono / .Net Framework version:

**Additional context**

**Comment by MangelMaxime** [comment]
Hello @dbrattli,

I think I fixed this issue when reworking the Tooltip system of FSAC.

I made a quick test locally and it seems to confirm the fix. Can you please check?

![ionide_info_panel_i_wokring](https://user-images.githubusercontent.com/4760796/110021298-d88ab700-7d2a-11eb-9c64-0dbe99868650.gif)

**Comment by dbrattli** [comment]
Yes, the issue looks to be fixed. Thanks a lot for the great work!
