### ISSUE TITLE
Add fsi watcher expects bool

### ISSUE THREAD

**Issue by mastoj** [ionide/ionide-vscode-fsharp#1356]
Under settings the setting "Add fsi watcher" is marked as error since it expects a `bool`. Setting it to true or false still states that it has invalid type. See screenshot.

**Environment (please complete the following information):**
 - OS: Windows
 - Ionide version: 4.10.0
 - VSCode version: 1.45.0-insider
 - dotnet SDK version: 3.1.201
 - mono / .Net Framework version: -

**Additional context**

![2020-05-02](https://user-images.githubusercontent.com/501424/80892969-87570480-8cce-11ea-8a60-14b91accdea8.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `4.10.1`
