### ISSUE TITLE
Auto-complete on attributes should remove "Attribute" from the annotation

### ISSUE THREAD

**Issue by njlr** [ionide/ionide-vscode-fsharp#1359]
If I start writing an attribute by typing `[`, `<` then choosing from the auto-complete pop-up (e.g. `RequireQualifiedAccessAttribute`) then the inserted text is literally that:

```fsharp
[<RequireQualifiedAccessAttribute>]
type T = string
```

But it should be this:

```fsharp
[<RequireQualifiedAccess>]
type T = string
```

**Environment (please complete the following information):**
 - OS: `Ubuntu 18.04`
 - Ionide version: `4.10.1`
 - VSCode version: `1.44.2`
 - dotnet SDK version: `3.0.103`
 - mono / .Net Framework version: `-`

**Comment by Krzysztof-Cieslak** [comment]
This is working on 5.0-preview03
