### ISSUE TITLE
reference to FSharp.Data.TypeProviders.dll gets red squiggly underline

### ISSUE THREAD

**Issue by fwaris** [ionide/ionide-vscode-fsharp#136]
'System.Core' did not contain the namespace, module or type 'IDynamicMetaObjectProvider' is the error that I see. 

I think this started happening with the latest update but I am not sure.

**Comment by cloudRoutine** [comment]
@fwaris  we need more information than this. Please provide a minimal reproduction via snippet, gist, or repo

**Comment by fwaris** [comment]
further digging indicates that its not an issue with referencing the type provider dll. It just so happens that the first line gets the squiggly for this error, maybe because a specific line number cannot be identified.

I think it has something to do with the DynamicInterop.dll. 

The following F# code is a minimum set that *occasionally* generates this error. 

`//#r "FSharp.Data.TypeProviders.dll"

#r @"C:\s\scripts\gs\gs\packages\Deedle\lib\net40\Deedle.dll"

        
#r @"C:\s\scripts\gs\gs\packages\DynamicInterop\lib\net40\DynamicInterop.dll"
#r @"C:\s\scripts\gs\gs\packages\R.NET.Community\lib\net40\RDotNet.dll"
#r @"C:\s\scripts\gs\gs\packages\RProvider\lib\net40\RProvider.Runtime.dll"
#r @"C:\s\scripts\gs\gs\packages\RProvider\lib\net40\RProvider.dll"
#r @"C:\s\scripts\gs\gs\packages\Deedle.RPlugin\lib\net40\Deedle.RProvider.Plugin.dll"


open System
open System.IO
open FSharp.Data

open RProvider.``base``
let v = R.c(1,2,3)
R.find_package("kohonen")
R.find_package("class")
R.require("kohonen")
R.require("class")
open Deedle
let s = []
let f = frame s
let data = R.as_matrix(f)
//let g = ``class``.R.somgrid(xdim=10,ydim=10,topo="rectangular")
`

**Comment by fabiomarreco** [comment]
Was this fixed ? I get the exact same error by only by loading the "FsLab.fsx" script that comes with FsLab Package.

![image](https://user-images.githubusercontent.com/1412643/38873634-a20b62ce-422c-11e8-8174-87f39d8bf921.png)


`[10:47:13 DEBUG] WebSocket message: '{"Kind":"errors","Data":{"File":"c:\\packages.fsx","Errors":[{"FileName":"c:\\packages.fsx","StartLine":1,"EndLine":1,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"The module/namespace 'System.Dynamic' from compilation unit 'System.Core' did not contain the namespace, module or type 'IDynamicMetaObjectProvider'","Subcategory":"typecheck"}]}}'
`
