### ISSUE TITLE
Autocomplete on 4.11.0 (and 4.10.0 & 4.10.1)

### ISSUE THREAD

**Issue by magnushammar** [ionide/ionide-vscode-fsharp#1362]
I would love to get the autocompletion to kick in upon typing the . instead of having to do the ctrl+space all the time. (edit: in a script file)

Also an observation regarding .Net 5.0 Preview 2 & 3.  On 4.10.0 and 4.10.1 I could not get any autocomplete (or type information whatsoever).

On 4.11.0 I could occasionally get autocompletion but not often enough so I could discern a pattern.

All tests performed on clean Win10 1909 VM with **only 5.0 preview (2 or 3)** installed.

**Comment by MangelMaxime** [comment]
It seems like the `.` completion works but only once the F# compiler did parse the file or something like that. In the following GIF, we see that only when `String` is coloured or the red-underlined is shown then the `.` completion works.

![autocomplete_demo](https://user-images.githubusercontent.com/4760796/81333458-f2c11d80-90a4-11ea-887d-bb2b0255a3c1.gif)

I am not providing a solution just a very quick analysis.

**Comment by magnushammar** [comment]
I should have mentioned that I have the problem in script files. I edited the initial post to reflect that.   
In a project it works as expected for me too.

**Comment by nicola-zen** [comment]
I have the same (or very similar) issue. I cannot get type comments nor autocomplete working with Iodide 4.10+. Downgrading to 4.9.0 solves the issue.

Let me know if I can help in any way in debugging this.

**Comment by Krzysztof-Cieslak** [comment]
`4.12.X` includes fixes for script files
