### ISSUE TITLE
[<RequireQualifiedAccess>] members should not show in intellisense unless fully qualified

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1364]
Given the following code:

```fsharp
namespace Blah
    [<RequireQualifiedAccess>]
    type Foo = Bar | Baz | Bop
```

When I access the `Blah` namespace, I would **not** expect `Bar`, `Baz` or `Bop` to show in intellisense, but they do:

![image](https://user-images.githubusercontent.com/1781813/81748993-1c19e900-94ab-11ea-8595-0dc0ec4326fe.png)

If you then reference one, the compiler (correctly) gives you a warning:

![image](https://user-images.githubusercontent.com/1781813/81749042-33f16d00-94ab-11ea-8dc7-bc20ce8ff897.png)

I feel that Ionide should not present suggestions that are "wrong" and / or will lead to warnings or errors. This is also important from a discoverablility point of view for library authors - if I mark something with RQA, I also don't want intellisense clogged up with suggestions of each union case.

The only workaround I can think of is to enclose the DU in a module of the same name:

```fsharp
namespace Blah
    [<RequireQualifiedAccessAttribute>]
    module Foo =
        type Foo = Bar | Baz | Bop
```

This then behaves as expected:

![image](https://user-images.githubusercontent.com/1781813/81749300-abbf9780-94ab-11ea-9044-420f7c3959d4.png)

However this is totally unidiomatic and I would not want to do this.

**Comment by Krzysztof-Cieslak** [comment]
Sounds like an issue in compiler / FCS? Can you check if its reproducible in VS?

**Comment by isaacabraham** [comment]
Indeed it is, it's visible in VS as well. Where do you think this issue should be moved to?

**Comment by Krzysztof-Cieslak** [comment]
dotnet/fsharp
