### ISSUE TITLE
Using certain symbols in identifiers enclosed in double-backticks causes VS Liveshare to fail

### ISSUE THREAD

**Issue by josh-degraw** [ionide/ionide-vscode-fsharp#1366]
<sup>I'm not sure if this is _exactly_ the right place to post this issue, so if this doesn't fit here just let me know. </sup>
**Describe the bug**
When collaborating VS Code in an F# project, when you have an identifier surrounded by backticks, that includes some (non-space) character that would otherwise be invalid, e.g.
```f#
let ``this is a sample function, with a comma inside the identifier`` () = ...
```
it causes VS Code to lock up and eventually crash, and ends the live-share session.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a Live-Share session in an F# project, and have at least one other editor connected
2. Start typing an identifier with a comma or dash in it (I have verified it happens with at least these two characters)
3. The screen will start freezing and eventually crash the session

**Expected behaviour**
You should be able to write any valid F# identifier without it crashing a live-share session

**Environment (please complete the following information):**
 - OS: `Windows 10`
 - Ionide version: `4.11.0`
 - VSCode version: `1.45.1`
 - dotnet SDK version: `3.1.201`
 - Live Share Version:  `1.0.2169`

**Additional context**
Sometimes it will even crash the session if you just click the name of an identifier with an otherwise invalid symbol inside it, i.e. one that was already present in the codebase.

**Comment by jhwohlgemuth** [comment]
I can confirm this issue. I thought I was going crazy...For the record, I am not using liveshare, just writing tests. When I type a comma into a "double backtick" string, freezes VSCode. I am also on Windows 10 with the VSCode 1.45.1.

**Comment by Krzysztof-Cieslak** [comment]
This is the same problem as #1073
