### ISSUE TITLE
Type annotations are missing

### ISSUE THREAD

**Issue by njlr** [ionide/ionide-vscode-fsharp#1367]
**Describe the bug**

 * Type annotations are missing
 * Projects stuck in "not yet loaded" state

**To Reproduce**

Steps to reproduce the behaviour:
1. Open VS Code in an F# solution folder
2. Open any F# file
3. Observe that no type annotations are available
4. Open the Ionide solution explorer tab
5. Observe that none of the projects are loaded

**Environment (please complete the following information):**

 - OS: `Ubuntu 18.04.4 LTS`
 - Ionide version: `4.11.0`
 - VSCode version: `1.45.1`
 - dotnet SDK version: `3.0.103`
 - mono / .Net Framework version: `NA`

**Additional context**

Sometimes it works then stops working on the same project after editor open / close so maybe a cache issue?

**Comment by Krzysztof-Cieslak** [comment]
Versions `4.12.X` included bunch of changes to project loading.
