### ISSUE TITLE
Editor features often only works after touching the file

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1374]
I have projects where we share common files between projects - let's say Domain.fs is used in Fable and Saturn.

If I open Ionide and press F12 (go to definition) then it often doesn't work - even when everything is already syntactically colored. it only works after touching the file.

**Comment by Krzysztof-Cieslak** [comment]
I can't repro this anymore, startup behaviour seems fine to me: 
![startup](https://user-images.githubusercontent.com/5427083/179628494-6d18ce26-cffa-404d-ba75-3ba33a59c793.gif)
