### ISSUE TITLE
Ident in fsharp explorer is not correct

### ISSUE THREAD

**Issue by albertwoo** [ionide/ionide-vscode-fsharp#1376]
**Describe the bug**
The indent is not correct which make the structure very hard to read

**Expected behaviour**
Should behavoir like the default explorer

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/8017681/83839427-9e09d480-a72e-11ea-817c-9f15d6e2966a.png)

The left side is the current wrong strcture. The right side is I made after change below code:
```fsharp
let icon, resourceUri =
    match node with
    | File (_, path, _, _)
    | ProjectNotLoaded (_, path, _)
    | ProjectLoading (_, path, _)
    | ProjectFailedToLoad (_, path, _, _)
    | ProjectNotRestored (_, path, _, _)
    | ProjectLanguageNotSupported (_, path, _)  ->
        ThemeIcon.File |> U4.Case4 |> Some, Uri.file path |> Some
    | Project (_, path, _, _, _, _, _, _)
    | Solution (_, path, _, _)
    | Folder (_, _, path, _,_) ->
        ThemeIcon.Folder |> U4.Case4 |> Some, Uri.file path |> Some
    | WorkspaceFolder _
    | ReferenceList _
    | ProjectReferencesList _ ->
        ThemeIcon.Folder |> U4.Case4 |> Some, None
    | Reference (_, path, _, _) | ProjectReference (_, path, _, _) ->
        p.light <- (plugPath + "/images/circuit-board-light.svg") |> U3.Case1
        p.dark <- (plugPath + "/images/circuit-board-dark.svg") |> U3.Case1
        p |> U4.Case3 |> Some, Uri.file path |> Some
    | Workspace _ ->
        None, None
```

For Project, Solution, ReferenceList, ProjectReferencesList, they should use ThemeIcon.Folder.
But after I change those the icon for those are lost, I did not figure out why. What is why I did not make a PR. I just list what I found, so someone else can help to improve this.

Thanks!

**Comment by misterspeedy** [comment]
In case it helps, I'm seeing exactly the same issue.

VS Code tree:

![image](https://user-images.githubusercontent.com/800686/84007645-a64d5400-a968-11ea-8747-6e26f38beecd.png)

Ionide tree:

![image](https://user-images.githubusercontent.com/800686/84007798-d268d500-a968-11ea-93c2-5db114187a6d.png)

Note how `View.fs` is missing from `Navbar`, and `Types.fs`, `State.fs` and `App.fs` appear to be nested under `Navbar` but should appear at top level.
