### ISSUE TITLE
Need to restart Code on creating a new project

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1377]
Creating a new F# app, Ionide shows red squigglies all the time on first open - save / build / edit etc. don't help. You need to completely restart Code to get things to work again.

Latest Ionide, dotnet core 3.x

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce this anymore - creating new projects seems to be working for me just fine
![startup-newProject](https://user-images.githubusercontent.com/5427083/179629426-58db9c17-353b-4cc7-b707-df1af662630c.gif)
