### ISSUE TITLE
Saving a script file terminates language sever

### ISSUE THREAD

**Issue by jbeeko** [ionide/ionide-vscode-fsharp#1378]
**Describe the bug**
Performing a Save As... of a .fsx file terminates the Language Server and then Intellisense and other editor features stop working. 

**To Reproduce**
Open a small script file using the "Open" command (i.e. don't open directory, workspace or project). Like so
<img width="281" alt="image" src="https://user-images.githubusercontent.com/4968704/84060809-ae5dc180-a971-11ea-8fcb-30cf927edb78.png">

Perform a Save As... and language services stop working. Like so (note absence of line lens)
<img width="267" alt="image" src="https://user-images.githubusercontent.com/4968704/84060938-e402aa80-a971-11ea-9686-b1ba1e76c31f.png">

OUTPUT Pane contains the following right after the Save As.
```
[10:21:47.579 ERR] [LSP] PositionHandler - Getting file checker options for /Users/joergbeekmann/Desktop/Scripting/bug1.fsx failed
[10:21:47.579 ERR] [LSP] PositionHandler - Getting file checker options for /Users/joergbeekmann/Desktop/Scripting/bug1.fsx failed
```

NOTE: This does not happen when simply saving. 

**Expected behaviour**
Language services should not stop.

**Environment (please complete the following information):**
 - OS: OSX
 - Ionide version: 4.11.1
 - VSCode version: 1.45.1
 - dotnet SDK version: 5.0 preview 4
 - mono / .Net Framework version: N/A

**Comment by jbeeko** [comment]
I've been investigating more. I think this issue as well as 
https://github.com/ionide/ionide-vscode-fsharp/issues/1375
https://github.com/ionide/ionide-vscode-fsharp/issues/1371

And the behaviour I was seeing here 
https://github.com/ionide/ionide-vscode-fsharp/issues/1357#issuecomment-633703701

Occur and persist when opening a script file outside a project directory. If in a project directory with the project opened they either don't occur or are asked by the Language Server recovering.

For example in the case of this issue performing a Save As.. when the script file is in a directory that has a .fsproj file results in Line Lens disappearing, and the following being written to the OUTPUT. But then the system seems to recover (though Line Lens is not refreshed till some editing takes place).

```
[20:19:04.628 ERR] [LSP] PositionHandler - Getting file checker options for /Users/joergbeekmann/Desktop/Scripting/Farmer1.fsx failed
[20:19:04.628 ERR] [LSP] PositionHandler - Getting file checker options for /Users/joergbeekmann/Desktop/Scripting/Farmer1.fsx failed
```

**Comment by Krzysztof-Cieslak** [comment]
As far as I can tell it doesn't terminate the language server. All you need to do is make single file edit to bring all tooling back again - it's a well-known issue with our (apparently incorrect) handling of FileOpened events.

**Comment by jbeeko** [comment]
Agreed it works fine in the case of the file having been opened with a folder open. In the case where no folder is open which is what I was observing tooling does not come back but that is #1381 

In that case the only thing this issue reports is the momentary glitch in tooling (e.g. line lens disappearing). 

Is the issue with FileOpen events reported? If so I'll ref and close this.

**Comment by Krzysztof-Cieslak** [comment]
Ref: #1374
