### ISSUE TITLE
Add JSON schema for fableconfig.json

### ISSUE THREAD

**Issue by alfonsogarciacaro** [ionide/ionide-vscode-fsharp#138]
This is a follow-up to @Krzysztof-Cieslak's suggestion. More info here: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation

I can write the schema myself and send PR. Please just tell me where you would like to put it. Or maybe it's better to add it to the [schema store](https://github.com/schemastore/schemastore/) and then include just the link in `contributes.jsonValidation.url`?

**Comment by cloudRoutine** [comment]
this seems like it'd belong in the `ionide-vscode-fable` extension we discussed a few days ago.

**Comment by cloudRoutine** [comment]
either way it's good to add it to schema store because I think that will enable VS to recognize it automatically

**Comment by alfonsogarciacaro** [comment]
We can try, but I'm not sure VSCode reads automatically all schemas in the JSON schema store. The link says the `contributes.jsonValidation.url` **can** point to the schema store: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesjsonvalidation

In any case, we can add temporarily the schema url to `inoide-vscode-fsharp` and then move it to `ionide-vscode-fable` when it's ready :+1:

**Comment by Krzysztof-Cieslak** [comment]
I'm OK with adding it to `ionide-vscode-fsharp` for now.
