### ISSUE TITLE
Unknown workspace edit change received:

### ISSUE THREAD

**Issue by mastoj** [ionide/ionide-vscode-fsharp#1385]
Trying to use "ctrl+." to add the `open` statement for a namespace but nothing happens. The error message is:

> Unknown workspace edit change received

Script file looks like:

```
#load ".paket/load/netcoreapp3.1/Snowflake.Data.fsx"

open Snowflake.Data
//open Snowflake.Data.Client

let test() =
    let connection = SnowflakeDbConnection()
    ()

test()
```

Paket.dependencies:

```
source https://api.nuget.org/v3/index.json

storage: none
framework: netcoreapp3.1, netstandard2.0, netstandard2.1
nuget Snowflake.Data
```

Let me know if more input is needed to triage this.

**Comment by Krzysztof-Cieslak** [comment]
Hey, @baronfel have we talked about it recently or memory fails me?

**Comment by baronfel** [comment]
Is this issue something like:

* Code is missing an open
* We provide the codefix for adding the open
* When using the codefix, the error message described is shown to the user

@Krzysztof-Cieslak I think we've been talking about instances where the codefix doesn't trigger at all (needs upstream fixes) vs instances where the codefix is triggered and fails

**Comment by Krzysztof-Cieslak** [comment]
> Unknown workspace edit change received

suggest that we send the edit but it's somehow wrong, maybe wrong range due to script file or something?

**Comment by seanamos** [comment]
I occasionally receive this in some files when using symbol renames (F2) as well. There will just be some files where it doesn't work.

**Comment by baronfel** [comment]
This is probably because workspaceEdits often require the version to be present and we weren't always honoring this. See https://github.com/rust-analyzer/rust-analyzer/issues/6654#issuecomment-735980787 for details, and https://github.com/fsharp/FsAutoComplete/pull/816 for our version of the same fix.
