### ISSUE TITLE
No auto completion etc. for F# Scripts

### ISSUE THREAD

**Issue by aspnetde** [ionide/ionide-vscode-fsharp#1386]
I just created that .fsx file in a random folder and opened it with VS Code and Ionide. While FSI with dotnet core works out of the box, I don't get any support besides syntax highlighting. `"Use Sdk Scripts` is enabled.

In the example, it's clear that `foo` doesn't exist and the execution will fail:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1322584/84912460-c0e6a200-b0b9-11ea-96ed-3a87e0c86cc8.png">

What do I miss?

---

macOS
Ionide 4.13.0
dotnetcore 3.1.300

**Comment by aspnetde** [comment]
I just noticed that the plugin doesn't seem to be loaded (can I trigger that manually?). When opening a Fable project (.fsproj), it comes up. Adding an F# script there will also bring the tooling up as expected:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1322584/84915660-618a9100-b0bd-11ea-9ba7-2a15d3ef4923.png">

**Comment by Krzysztof-Cieslak** [comment]
Judging by purple status bar on the first screenshot you've opened script directly without opening any folder first - for multiple reasons that have never been supported scenario in Ionide. What you need to do is to open the folder which contains your script file. Then Ionide should work just fine.

There's some additional discussions about it in https://github.com/ionide/ionide-vscode-fsharp/issues/1381

**Comment by aspnetde** [comment]
> Judging by purple status bar on the first screenshot you've opened script directly without opening any folder first - for multiple reasons that have never been supported scenario in Ionide. What you need to do is to open the folder which contains your script file. Then Ionide should work just fine.

That's right, I did open the file directly at first. But I had the idea to try it with a folder, too. And it doesn't work either. 

- I opened a new "Window" instance of VSCode, created an empty folder and added a script: Nothing.
- Then I closed that Windows, opened a new one and opened that existing folder again: Nothing. See: https://www.dropbox.com/s/rjb1mvhopderp41/Screen%20Recording%202020-06-17%20at%2018.05.15.mov?dl=0

The .ionide folder has been created, though.

**Comment by aspnetde** [comment]
I already forgot about that issue and ran into it again today. If anyone has any idea what to look after, please let me know.

**Comment by mcortvic** [comment]
I have the same issue on Linux. If I open a folder with some `test.fsx` already in there, there is no autocomplete or error detection. However if you rename `test.fsx` while vscode running to something other than `test.fsx` ionide will magically start working. If you create new script then it will work too.
![ionide-bug](https://user-images.githubusercontent.com/27336752/92932365-7d4bcc00-f44d-11ea-8584-3049028b796e.gif)

**Comment by Zaid-Ajaj** [comment]
@mcortvic I believe you only have to trigger a file change in order to get autocomplete to work again: add a space in the script file somewhere and save the file, then it should work again.

**Comment by mcortvic** [comment]
@Zaid-Ajaj no, file change in my case doesn't trigger it. Script file has to be renamed. Also as shown on gif:
1. launch vscode
2. rename `test.fsx` => `testing.fsx` - ionide works
3. rename `testing.fsx` => `test.fsx` - ionide doesn't work
4. rename `test.fsx` => `testing.fsx` - ionide works but then after you reload vscode, all scripts named `testing.fsx` won't work.

After playing around I also found out that:
1. Only the scripts that were in a visible editors, the moment I closed workspace last time, get broken. So if you you close all of the editors and reload window, all scripts work (yay!)
2. If you open/reload vscode and immediately open the script, it will also be broken. You have to wait 10 seconds for vscode to load fully or something,

In both cases broken scripts show up "too quickly" on the screen after startup, maybe? Is there some sort of synchronization issue?

**Comment by baronfel** [comment]
I'm almost certain this is the same delayed-configuration problem that has plagued script checking since we added .net core (see my comments [here](https://github.com/ionide/ionide-vscode-fsharp/issues/1357#issuecomment-633290308)). This really can't be fixed until:

* we remove .net framework support (or default script typechecking to use .net core) so that the correct default is used implicitly
* we figure out how to properly invalidate files

**Comment by Krzysztof-Cieslak** [comment]
This should be solved as we default to .NET SDK for scripts.

**Comment by cartermp** [comment]
I can confirm that this 100% works for me with the latest update + .NET 5 SDK installation

**Comment by aggieben** [comment]
I observed this problem today when the script was in a folder with other non-.NET-related stuff (powershell, sql, etc).  When I moved it from that folder to a new, empty folder and then opened that in Code, things worked.
