### ISSUE TITLE
Issue building project with referenced project

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1389]
Building a project on netcore31 for a clean SAFE v2 app (prototype at this point). Essentially the server project (netcore31) references a shared netstandard2 project. I see this error when building the solution:

![image](https://user-images.githubusercontent.com/1781813/85448188-b8e5a100-b596-11ea-9b31-a307fb0289af.png)

No clue what it means or where it's best to report this. It builds fine from dotnet build.

**Comment by Krzysztof-Cieslak** [comment]
I think the easiest way to work around this is cleaning obj/bin folders and reopening VSCode.

**Comment by Krzysztof-Cieslak** [comment]
I haven't seen this one in a while, closing.
