### ISSUE TITLE
giving parameters to run/debug the project with

### ISSUE THREAD

**Issue by yilmazdurmaz** [ionide/ionide-vscode-fsharp#1392]
**Is your feature request related to a problem? Please describe.**
going back and forth with vscode debug/run menus and f# solution explorer when I need to input parameters to my program from console is exhausting my coding energy.

**Describe the solution you'd like**
whatever you use to debug/run the project in vscode, give a setting to give parameters to my programs, either static or live. vscode itself has this capability in its "launch.json" file

**Describe alternatives you've considered**
as I mentioned, I use "launch.json" but going back and forth is exhausting.

**Additional context**

thanks

**Comment by Krzysztof-Cieslak** [comment]
Duplicate of #569
