### ISSUE TITLE
Info Panel's formatting doesn't use VS Code's style (font, colors...)

### ISSUE THREAD

**Issue by OkayX6** [ionide/ionide-vscode-fsharp#1393]
Hey, I'd be happy to help if it's easy to do. I just need a few pointers (how to write the correct CSS so that it picks up the values/colors configured in the VS Code tooling).

**Is your feature request related to a problem? Please describe.**
See title: the formatting is inconsistent with the rest of VS Code (while Quick Info is fine).

![image](https://user-images.githubusercontent.com/1169339/86133672-d2489900-bb12-11ea-9395-90fda4f087db.png)

**Describe the solution you'd like**
Just use the user's UI parameters in the generated CSS/HTML.

**Describe alternatives you've considered**
Don't do anything.

**Additional context**
N/A.

**Comment by baronfel** [comment]
Thanks for submitting! All of the formatting of the InfoPanel is rendered [here](https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/InfoPanel.fs#L60), and the raw textual data payload for the identifier being viewed comes from one of [these two functions](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/DocumentationFormatter.fs#L680-L833) in FsAutoComplete.  It looks like we're mainly using markdown to render this panel, so customizing the rendered markdown might be a bit of work.
