### ISSUE TITLE
Info panel shows only one version of methods with multiple overloads

### ISSUE THREAD

**Issue by ssiltanen** [ionide/ionide-vscode-fsharp#1394]
**Describe the bug**
Using info panel on a C# library with a class that has method overloading shows only one version of a method with multiple overloads instead of showing all the method overloads.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a project with a reference to a [Microsoft.Azure.Devices](https://www.nuget.org/packages/Microsoft.Azure.Devices/)
2. Construct a class of [RegistryManager](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager?view=azure-dotnet)
3. Open info panel of this class object to see its methods in info panel
4. See error of only one version of GetTwinAsync method [GetTwinAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager.gettwinasync?view=azure-dotnet#Microsoft_Azure_Devices_RegistryManager_GetTwinAsync_System_String_) method

**Expected behaviour**
See 4 overloads of GetTwinAsync:
GetTwinAsync(string)
GetTwinAsync(string, string)
GetTwinAsync(string, CancellationToken)
GetTwinAsync(string, string, CancellationToken)

**Screenshots**
<img width="1020" alt="Screenshot 2020-07-05 at 10 45 34" src="https://user-images.githubusercontent.com/10105521/86527997-decf4780-beac-11ea-9221-c0c8b3e6f7b4.png">

**Environment (please complete the following information):**
 - OS: MacOS Catalina v10.15.5
 - Ionide version: 4.14.0
 - VSCode version: 1.46.1
 - dotnet SDK version: 3.1.301

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/pull/628, will be included in next Ionide release
