### ISSUE TITLE
Intellisense quick fixes (CTRL+.) doesn't add code to document

### ISSUE THREAD

**Issue by shubash-chumber** [ionide/ionide-vscode-fsharp#1396]
**Describe the bug**
When I press `CTRL+.` for quick fixes or the click the light bulb (show fixes) I get the dialog in the below screenshot. However, when I press enter or click an item in the quick fixes dialog no code is added to my document i.e. nothing happens.

**Expected behaviour**
In the given example in the screenshot, I'd expect selecting "Open System" to add the line "open System" at the top of the document.

**Screenshots**
![image](https://user-images.githubusercontent.com/22809508/86543369-b4fe3b00-bf15-11ea-8733-a6412e1820ff.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.14.0
 - VSCode version: 1.46.1
 - dotnet SDK version: 3.1.301

**Comment by josefblaha** [comment]
I've got the issue as well, but only in script files (`.fsx`). The light bulb appears, there are three fixes offered, but none of them has any effect.

@shubash-chumber, in your case, is it `.fs` or `.fsx`?

**Comment by shubash-chumber** [comment]
@josefblaha, thanks for your response. The issue is with `.fsx` files. I recall I tested `.fs` and I thought it wasn't working there, but it works fine with `.fs` files now.

**Comment by Krzysztof-Cieslak** [comment]
@baronfel is that URI encoding issue again?

**Comment by Krzysztof-Cieslak** [comment]
The FSAC fix was released with the latest Ionide
