### ISSUE TITLE
Intellisense doesn't update or updates very slow on VS Code when types are in separate file

### ISSUE THREAD

**Issue by poctob** [ionide/ionide-vscode-fsharp#1397]
**Describe the bug**
When members are added or removed from a type. Intellisense doesn't update and underlines/not underlines when type members are referenced in another file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new dot net core project, classlib, console, asp.net core, doesn't matter
2. Create new file Service.fs
3. Add new type
```
type Service() =
    member this.A = "A"
```
4. Create new file Library.fs
5. Add new module 

```
module T =
    let s = Service()
    let a = t.A
```

6. Observe that code is underlined with syntax errors
7. Build the project on the command line.
8. Observe that project builds correctly with no errors.
9. Restart VS Code. Observe that errors are no longer shown.

When type is declared in the same file as the module, extension behaves properly.
Sometimes the errors do resolve after a long time period.
Note, that if Ionide extension is disabled in VS Code, types resolve correctly and false errors no longer show up.

**Expected behaviour**
Syntax errors update in timely manner on code changes

**Screenshots**
![image](https://user-images.githubusercontent.com/4343084/87102931-7fad6200-c221-11ea-996c-fc637750d16d.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: v4.14.0
 - VSCode version: 1.47.0
 - dotnet SDK version: 3.1.101
 - mono / .Net Framework version:

**Additional context**
F# Language server has strange output with paths not found on my system:
Exception in language server System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FSharpLanguageServer.Program.findMethodCallBeforeCursor(String lineContent, Int32 cursor) in **/Users/george/Documents/fsharp-language-server/src/FSharpLanguageServer/Program.fs:line 2**

at <StartupCode$FSharp-Core>.$Async.AwaitAndBindChildResult@1495-4.Invoke(AsyncActivation`1 ctxt) in **E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1495**

**D:\Programowanie\ionide\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 1077**

at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in **F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109**
  Code: -32603

**Comment by Krzysztof-Cieslak** [comment]
No actionable information in the issue.
