### ISSUE TITLE
Code action applying linter suggestions 

### ISSUE THREAD

**Issue by mjarosie** [ionide/ionide-vscode-fsharp#1398]
**Is your feature request related to a problem? Please describe.**
Cleaning up code by manually applying linter suggestions can be time-consuming.
That'd be really useful to be able to quickly apply linter suggestions with `ctrl + .`

Having this example piece of code:

```F#
open System
open System.Net

type MyType = 
    | MyTypeValue of DownloadStringCompletedEventArgs

let myFun (a: MyType) =
    printfn "%s" (string a)
    ()

let downloadCallback (url:Uri) : unit =      
    let client = new WebClient()
    client.DownloadStringCompleted 
        |> Event.add (fun args -> myFun (MyTypeValue args)) // <- here's where the linter suggests changes
    client.DownloadStringAsync url
```

Linter proposes to replace lambda with composition:

![image](https://user-images.githubusercontent.com/9082353/87234492-53cce080-c3c9-11ea-9f26-1a5ddeebb83d.png)

It gives just a general hint, and doesn't directly relate to your code, so it's not possible to just copy the suggestion and directly replace your code with it:

```
Lambda may be able to be replaced with composition. e.g. `fun x -> x |> isValid |> not` could be replaced with `isValid >> not`.
```

**Describe alternatives you've considered**
Currently the alternative is just to apply the suggestion manually. The hint disappears right after we start to modify the code - because of that and because currently linter doesn't show exact change to your code, but gives just a general suggestion, it can become non-obvious to apply the change correctly, especially for beginners.

**Additional context**
I'm requesting this feature as someone quite new to F# who's still learning the language. The described problem probably is not an issue for someone working with F# on a daily basis (or maybe it is?).

**Comment by Krzysztof-Cieslak** [comment]
This used to work... once upon atime
