### ISSUE TITLE
FAKE Build Not Running in VS Code on Mac

### ISSUE THREAD

**Issue by jwood803** [ionide/ionide-vscode-fsharp#14]
When I try to run a FAKE build in VS Code on the Mac, I seem to get a `No handler found for the command 'fake.buildDefault` message.

Not sure what I'm missing (or I'm just dumb :stuck_out_tongue:), but the screenshot should show the `build.sh` and `build.fsx` files. If anything else is needed, just let me know.

![VS Code](https://dl.dropboxusercontent.com/s/gjwlr9h3g2r52ix/code-fake.jpg?dl=0)

**Comment by Krzysztof-Cieslak** [comment]
Will be discussed in https://github.com/ionide/ionide-vscode-fake/issues/4
