### ISSUE TITLE
Publish to https://open-vsx.org/

### ISSUE THREAD

**Issue by kaashyapan** [ionide/ionide-vscode-fsharp#1406]
**Is your feature request related to a problem? Please describe.**
vscode is great and not a walled garden (but maybe a fenced garden ?)
I'd like to stay away from Microsoft as much as is possible considering I use FSharp.
Can we please also publish this extension to an open repo ?

**Describe the solution you'd like**
Publish this extension to https://open-vsx.org/ which is an open repository for vscode compatible IDEs like vscodium.

**Comment by baronfel** [comment]
I certainly have no problems with publishing to other repositories. Do you have any pointers to documentation about how to push to that repository? Right now we publish as part of the CI pipeline, so if you could figure out how to push to it as part of a github action that would be ideal.

**Comment by kaashyapan** [comment]
This has a github action
[https://github.com/HaaLeo/publish-vscode-extension#readme](https://github.com/HaaLeo/publish-vscode-extension#readme)

The 'How-to' to publish an extension is in 
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Create an account -> setup namespace -> Get a token -> Setup the above github action

**Comment by Krzysztof-Cieslak** [comment]
Sounds good to me, I think GitPod integrates open-vsx marketplace too

**Comment by OmanF** [comment]
Another promising editor using `open-vsx` exclusively, due to legal issues, is `[oni2](https://github.com/onivim/oni2l)` (previously `onivim`).

Would be great having Ionide there too for all VSCode-compatible editors.

Thanks.

**Comment by olivercoad** [comment]
+1 to publishing to open-vsx, but just wondering how does https://github.com/ionide/playground work in Gitpod currently?

**Comment by nirvinm** [comment]
I would love to install Ionide from open-vsix.org. But how do we handle C# extension dependency on open-vsx given that C# extension is only licensed to run under Microsoft's VSCode build.

**Comment by muhammadsammy** [comment]
I created a free fork 
<https://github.com/muhammadsammy/free-omnisharp-vscode> of the 
official C# extension that can be used as the C# dependency for Ionide 
on Open VSX <https://open-vsx.org/extension/muhammad-sammy/csharp>. I 
tried it for debugging a simple F# console and it worked fine.

> I would love to install Ionide from open-vsix.org. But how do we 
> handle C# extension dependency on open-vsx given that C# extension is 
> only licensed to run under Microsoft's VSCode build.
>
