### ISSUE TITLE
VSCode hangs

### ISSUE THREAD

**Issue by JonCanning** [ionide/ionide-vscode-fsharp#1407]
```
module Main

open System.Text.RegularExpressions

let foo s =
    Regex.Match(s, "foo(\d+)").Groups.[1].Value
```

When I type an opening bracket `(` on line 4, VS Code hangs and has to be restarted. Downgrading to 4.15.0 solves this.

**Comment by faldor20** [comment]
i have been having the same issue lately with vscode freezing when typing certain things.

**Comment by Krzysztof-Cieslak** [comment]
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/1073
