### ISSUE TITLE
unable to run F# on arm64 ubuntu due to  "command 'fsi.SendSelection' not found" error

### ISSUE THREAD

**Issue by sandeep-gh** [ionide/ionide-vscode-fsharp#1410]
Installed Ionide on vscode. The dotnet executable is in the global PATH variable. However get the error fsi:SendSelection not found. 

**Environment (please complete the following information):**
 - OS:   Linux arm64 5.4.0-1015-raspi
 - Ionide version: 4.16  
 - VSCode version:  1.48.0  
 - dotnet SDK version: 3.1.401
 - mono / .Net Framework version:

**Comment by 64J0** [comment]
I'm already facing this bug with almost the same environment related by @sandeep-gh.
