### ISSUE TITLE
#r Nuget seems completely broken in .NET 5 P8

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1411]
Using any hash r Nuget reference seems to crash Ionide with the errors:

Request textDocument/completion failed.
  Message: no type check results
  Code: -32603
Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603

**Comment by Krzysztof-Cieslak** [comment]
I suspect it may be exactly the same issue as https://github.com/fsharp/FsAutoComplete/issues/603

**Comment by jkone27** [comment]
News? Seems still broken

**Comment by Krzysztof-Cieslak** [comment]
> News? Seems still broken

I'm glad you volunteered to investigate and fix this issue.

**Comment by jkone27** [comment]
watching the videos on how to setup ionide environemnt locally, and try testing, but i am pretty sure this will take me some time 👍

**Comment by Krzysztof-Cieslak** [comment]
We track this in #1441
