### ISSUE TITLE
Sending text to FSI is very slow

### ISSUE THREAD

**Issue by ronaldschlenker** [ionide/ionide-vscode-fsharp#1412]
Sending text to fsi (can be strings or just code in general) takes a very long time compared to Rider or Visual Studio. You can see the behaviour here:

![demo](https://user-images.githubusercontent.com/472222/91954900-ba53e800-ed02-11ea-9084-95b35f8b095b.gif)

When sending larger sources to FSI, this can be very annoying and it lowers the "working with data in F#" experience drastically. I don't know where exactly this is coming from. What I can tell is that it makes my use cases almost unusable - sometimes output is even slower than shown in the GIF. This behaviour can also be seen when you run things like this:

```fsharp
seq {
    for x in 1..5000 do "test"
}
|> String.concat " "
```

...or when you display a response from a webserver.

When I simply send text to a vi (bash) in vscode, the text is displayed immediately.

I know that there was an issue like that here, but I don't find it anymore.

If I can assist you somehow, please let me know. 

*Hint:* This is independent from the usage of .Net 5 preview / .Net 461 / .Net Core version.

* Operating system: **Windows_NT**
* Arch: **x64**
* VSCode: **1.48.2**
* Runtime: **netcore**
* Dotnet version: **5.0.100-preview.8.20417.9**
* MSBuild version:
```shell
Microsoft (R)-Build-Engine, Version 15.9.21+g9802d43bc3 f�r .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
```

**Comment by Krzysztof-Cieslak** [comment]
TBF, not sure if we have any impact on this - we just call "send a text to terminal" API from VSCode 

Maybe @Tyriar can help us with this?

**Comment by Tyriar** [comment]
We made a change recently to fix a long standing issue where sent/pasted text would be truncated https://github.com/microsoft/vscode/issues/38137. The fix was to split up the text into chunks of 50 characters which seems to match your gif.

I think now you're hitting a known Windows perf problem as a result of running conpty on the UI thread which is tracked in https://github.com/microsoft/vscode/issues/74620

**Comment by isaacabraham** [comment]
I saw this and tried moving back to the standard terminal renderer - for some reason I was on the DOM one which was super slow.

**Comment by ronaldschlenker** [comment]
I guess it might really be a windows issue. When I send a bunch of text via the "Terminal: Run Selected Text in Active Terminal" to a Windows Powershell Terminal, it is also quite slow (like in the gif above).

Now when I run `bash -c “vi filename.txt”` and send the same text to it, it is really fast.

**Comment by isaacabraham** [comment]
@ronaldschlenker which terminal renderer are you using?

**Comment by ronaldschlenker** [comment]
I tried it with all 3 (canvas, dom and WebGL), but there is no significant difference. And I think the issue has definitely something to do with the used console host and maybe the communication with it, since using WSL/bash, it is really fast.

**Comment by Krzysztof-Cieslak** [comment]
Ok, I'm closing this one here, as it's nothing we can control/fix anyway.
