### ISSUE TITLE
Unable to disable linelens

### ISSUE THREAD

**Issue by tskj** [ionide/ionide-vscode-fsharp#1414]
### Problem

Ionide no longer respects my config

```
  "FSharp.lineLens.enabled": "never",
```

an still shows the types as "comments" as shown in this screenshot

![image](https://user-images.githubusercontent.com/25415972/92951432-9c9f2500-f45e-11ea-92ed-9f91813678d8.png)
![image](https://user-images.githubusercontent.com/25415972/92951518-c3f5f200-f45e-11ea-96b6-2c34fe00b6b3.png)

### Steps to reproduce

Turn off linelens in VS Code settings.
They still show up.

### Machine infos

* Operating system: **MacOS Cataline 10.15.4**
* VSCode: **1.49.0**
* Ionide-fsharp version: **v4.17.0**
* Runtime: **netcore**
* Dotnet version: **3.1.101**
* Runtime: **.Net**
* Mono version:
```shell
Mono JIT compiler version 6.4.0.198 (2019-06/fe64a4765e6 Wed Sep 18 14:14:51 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
* MSBuild version:
```shell
Microsoft (R) Build Engine version 16.3.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by tskj** [comment]
I've been made aware this happens because "Enable pipeline hints" was introduced in a new update. This is super annoying, please change it so that it respects the existing  "line lens" setting.

**Comment by Krzysztof-Cieslak** [comment]
LineLens and Pipeline Hints are two separate functionalities and users should be able to decide whether they want it on or off separately.
