### ISSUE TITLE
Add type hints for last line of a pipeline

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#1416]
the new type hints in pipelines are an excellent time saver. I really love them. 

One nice addition would be to add type hints for the last line of a pipe as well. 
So we can see the type without hovering over the let binding. 
This is especially useful for local pipelines (inside a function) since Ionide doesn't show type hints for those bindings.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/ionide/ionide-vscode-fsharp/pull/1453
