### ISSUE TITLE
Intellisense error - The type IOutputStream is required here and is unavailable

### ISSUE THREAD

**Issue by raghur** [ionide/ionide-vscode-fsharp#1422]
**Describe the bug**
I seem to have weird intellisense problems. It seems to work only for references - not for my own code. Get a very weird error that I don't know what to make of.
I'm on Ubuntu 20.04

![fsautocomplete](https://user-images.githubusercontent.com/516267/94337238-a9974900-0006-11eb-88f2-09798f67fc70.png)

**To Reproduce**
Try autocompletion of code - seems to have to do soemthing with computation expressions

**Expected behaviour**
autocomplete provides completions

**Screenshots**
see above.

**Environment (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Ionide version: 4.17.0
 - VSCode version: 1.49.2
 - dotnet SDK version: 3.1.402
 - mono / .Net Framework version: Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)

**Additional context**

**Comment by Krzysztof-Cieslak** [comment]
Can you provide reproduction for this issue?
