### ISSUE TITLE
wwwroot not copying to output dir on dubugging

### ISSUE THREAD

**Issue by ZergRushJoe** [ionide/ionide-vscode-fsharp#1426]
**Describe the bug**
On Debugging web application in F# not copying wwwroot files.

**To Reproduce**
Steps to reproduce the behaviour:
1. add a wwwroot folder to a f# web project
2. add static route for files in wwwroot
3. debug the project
4. fails to find the files

**Expected behavior**
should work. if you just run dotnet build and dotnet run it works fine

**Screenshots**
![image](https://user-images.githubusercontent.com/7153267/95620710-9c368180-0a3e-11eb-8e83-340a0056ee36.png)

**Environment (please complete the following information):**
 - OS: winodws
 - Ionide version: 4.17.0
 - VSCode version:  1.49.3
 - dotnet SDK version: core 3.1

**Comment by Krzysztof-Cieslak** [comment]
Make sure you've added files you want to copy to project files and set `CopyToOutputDirectory` to `Always`
