### ISSUE TITLE
Add highlighting for IDisposable objects

### ISSUE THREAD

**Issue by travis-leith** [ionide/ionide-vscode-fsharp#1428]
**Is your feature request related to a problem? Please describe.**
I would like to have some kind of notification that a particular object implements IDisposable so I can decide if I want to `use` it.

**Describe the solution you'd like**
VS 2019 highlights such objects in green. Can we get ionide to do the same?

**Describe alternatives you've considered**
None

**Additional context**
My ionide/vs code looks like this
![image](https://user-images.githubusercontent.com/29927084/95676797-d0ce4880-0bb8-11eb-9b94-739df64ea200.png)

My VS Community looks like this
![image](https://user-images.githubusercontent.com/29927084/95676804-ddeb3780-0bb8-11eb-80fd-ebfde1ee2d90.png)

**Comment by Krzysztof-Cieslak** [comment]
This is possible by adding colour customization for disposable token in your VSCode settings:
```
  "editor.tokenColorCustomizationsExperimental": {
    "mutable": {
      "fontStyle": "underline",
      "foreground": "#ff14eb"
    },
    "disposable": {
      "foreground": "#ff8b2c"
    }
  },
```

![image](https://user-images.githubusercontent.com/5427083/102118891-998e4900-3e40-11eb-9da7-edcff092ccd3.png)
