### ISSUE TITLE
#r 'nuget:' not working when using ionide buttons

### ISSUE THREAD

**Issue by aVikingTrex** [ionide/ionide-vscode-fsharp#1429]
Using the buttons at the top of vs code (run script or send file) results in the error: 
error FS0078: Unable to find the file 'nuget: Expecto'
This is true for any nuget reference I have tried. I have set 
--langversion:preview and it works if I manually copy + paste the file to a command line.

Steps to reproduce the behaviour:
1. Make a new script
2. Add a nuget reference #r 'nuget: Expecto'
3. Press the Run Script (play button)

Expected behaviour:
Script runs and loads the nuget reference correctly

Environment:
 - OS: Linux
 - Ionide version: 4.17
 - VSCode version:1.5
 - dotnet SDK version:3.1.108

**Comment by Krzysztof-Cieslak** [comment]
This works with .NET 5 SDK installed.
