### ISSUE TITLE
Show active project on information bar

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-vscode-fsharp#143]
Similar to -

![](http://i.imgur.com/ohpQU93.png)

Clicking on the button on the info bar opens/switches to an editor view of the `.fsproj`
### Implementation Issues
- How should the project be inferred for linked files?
- Which project should be shown for files in multiple projects?
- Should a project be shown for files that are associated with a project (listed in the fsproj) but are not compiled with it (fsx files, md files, etc)?
- Which icon should we use?
- Should this apply to `project.json`? Is it worth implementing for a file type that's going to die?
- What should be shown for files that are in project.json and an fsproj?

**Comment by Krzysztof-Cieslak** [comment]
Implemented in `3.15.5`
