### ISSUE TITLE
Errors from outside the project are shown

### ISSUE THREAD

**Issue by adam-becker** [ionide/ionide-vscode-fsharp#1431]
**Describe the bug**
Errors reported by the extension include temporary files, for example `/tmp/{long hash}/src/fsharp/FSharp.Core`, since these files aren't part of the project, they should be omitted.

**To Reproduce**
It seems to happen whenever it wants, but maybe `Go to definition` for a definition not in your project makes it happen?

**Expected behaviour**
Errors from files not explicitly in my `fsproj` shouldn't be shown to me, since there's nothing I can do about them anyways.

**Screenshots**
![Screenshot from 2020-10-23 08-58-47](https://user-images.githubusercontent.com/47185607/97019895-1de1e100-150e-11eb-802c-b6d08ec6020a.png)

**Environment (please complete the following information):**
 - OS: Debian 10 (From .NET Core SDK Docker Image)
 - Ionide version: 4.17.0
 - VSCode version: 1.47.2
 - dotnet SDK version: 3.1.403
 - mono / .Net Framework version: Unknown

**Additional context**

**Comment by adam-becker** [comment]
Another viable option would be to figure out why these errors are reported and add the necessary references to make the errors not appear at all.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/pull/689, will be available in next release (early next week, maybe Monday)
