### ISSUE TITLE
Stringinterpolation requires langVersion in .NET 5

### ISSUE THREAD

**Issue by NicoVIII** [ionide/ionide-vscode-fsharp#1433]
**Describe the bug**
If I want to use string interpolation from F# 5 in a new .NET 5 project, I get an error in the editor that tells me, that string interpolation is not available in F# 4.7. As far as I know, F# 5 is now the default language version and `dotnet build` runs successfully without this error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use string interpolation in an net5.0 project without LangVersion
```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>test</RootNamespace>
  </PropertyGroup>
```

```
let test = "test"
$"%s{test}"
```

**Expected behaviour**
I would expect that the language version is the same for editor and compiler.

**Screenshots**
![string_interpolation](https://user-images.githubusercontent.com/3983345/98786978-2dfb2b00-23ff-11eb-8d36-b8f983711f06.png)

**Environment (please complete the following information):**
 - OS: Windows (but inside of a mcr.microsoft.com/dotnet/sdk:5.0-focal dev container)
 - Ionide version: 4.17.0
 - VSCode version: Version: 1.51.0 (user setup)
 - dotnet SDK version: 5.0.100
 - mono / .Net Framework version: -

**Additional context**
I created a reproduction repo here: https://github.com/NicoVIII/repro-bug

I don't rule out that I do something wrong. If this is the case: Sorry!

**Comment by baronfel** [comment]
We're actively working on this, you can follow the status here: https://github.com/fsharp/FsAutoComplete/pull/656

**Comment by NicoVIII** [comment]
Thank you! I wasn't sure, if this is another thing, which belongs to FsAutoComplete and not directly to Ionide, so I opened the bug here :)

**Comment by Krzysztof-Cieslak** [comment]
This is fixed in Ionide 5.0 preview

**Comment by jkone27** [comment]
is this fixed also for linux/ubuntu ?  have v.5.5.4 installed running ubuntu on windows in this case (net 5 sdk)

![image](https://user-images.githubusercontent.com/10419217/118372298-41a36c00-b5b1-11eb-890c-0b4f234a9985.png)

**Comment by NicoVIII** [comment]
Works for me with 5.5.5 and on Manjaro with target framework net5.0.

**Comment by baronfel** [comment]
That's correct, this is implemented in all ionide 5.x versions.

**Comment by jkone27** [comment]
got the same error on windows 10 without running on WSL

![image](https://user-images.githubusercontent.com/10419217/118410976-8d7a1200-b692-11eb-844a-c1e61556ff8f.png)

will try uninstall vscode, and re install it from scratch

**Comment by jkone27** [comment]
it worked after uninstall of vscode and ionide as well and clean re'install, not sure what was causing it

**Comment by Darkle** [comment]
Can this be re-opened? I am running in to this too with the latest ionide. I've tried a bunch of things like uninstalling, then reinstalling ionide. Weirdly, if I open the project in Jetbrains Rider and let it load, then switch back to VSCode, the error goes away. 

My details:
- Ionide version: v7.5.4
- dotnet version: 7.0.302
- fable version: 4.1.4
- OS: debian bullseye

My `App.fsproj` file: 

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <LangVersion>7</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="index.html" />
    <Compile Include="fs/PropAlias.fs" />
    <Compile Include="fs/Tailwind.fs" />
    <Compile Include="fs/Utils.fs" />
    <Compile Include="fs/apiClient/OpenApiHttp.fs" />
    <Compile Include="fs/apiClient/Types.fs" />
    <Compile Include="fs/apiClient/Client.fs" />
    <Compile Include="fs/ApiClient.fs" />
    <Compile Include="fs/pages/Home.fs" />
    <Compile Include="fs/pages/404.fs" />
    <Compile Include="fs/admin-pages/AdminHome.fs" />
    <Compile Include="fs/admin-pages/AdminUtils.fs" />
    <Compile Include="fs/Router.fs" />
    <Compile Include="fs/Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="4.0.0" />
    <PackageReference Include="Fable.SimpleHttp" Version="3.5.0" />
    <PackageReference Include="Fable.SimpleJson" Version="3.24.0" />
    <PackageReference Include="Feliz" Version="2.6.0" />
    <PackageReference Include="Feliz.CompilerPlugins" Version="2.2.0" />
    <PackageReference Include="Feliz.Router" Version="4.0.0" />
    <PackageReference Include="Zanaptak.TypedCssClasses" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>
```

**Comment by goswinr** [comment]
@baronfel I still have this problem on net7. [The guides suggest using the `Update` keyword](https://github.com/dotnet/fsharp/blob/main/docs/fsharp-core-notes.md#how-to-explicitly-reference-fsharpcore). 
So when using  `<PackageReference Update ="FSharp.Core" Version="7.0.300"/>`  it fails, only `<PackageReference Include="FSharp.Core" Version="7.0.300"/>`  or no reference at all works.
