### ISSUE TITLE
Referencing F# project from C# project breaks intellisense.

### ISSUE THREAD

**Issue by codyrehm** [ionide/ionide-vscode-fsharp#1435]
**Describe the bug**
When referencing an F# project from a C# project in a multi-project solution intellisense for the F# types does not work in the C# project.

**To Reproduce**
1. Create a new sln.
2. Create a C# console project.
3. Create an F# classlib project.
4. References the F# classlib project from the C# project.
5. Use F# types from the classlib project in the C# application.
6. Intellisense for the F# project does not work.

**Expected behaviour**
Intellisense for an F# project in a C# project works.

**Screenshots**
<img width="469" alt="image" src="https://user-images.githubusercontent.com/7042703/99194190-d298a800-2732-11eb-867d-9942bca94a33.png">
<img width="703" alt="image" src="https://user-images.githubusercontent.com/7042703/99194221-f3f99400-2732-11eb-858e-8bf52ae58ec8.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/7042703/99194245-1ab7ca80-2733-11eb-81a2-b1e15e28ddf9.png">

**Environment (please complete the following information):**
 - OS: First noticed on macOS Catalina but now also an issue on Big Sur.
 - Ionide version: 4.17.0
 - VSCode version: 1.51.1
 - dotnet SDK version: 5.0.100
 - mono / .Net Framework version: net5.0

**Comment by cartermp** [comment]
Neither the C# plugin nor Ionide support multi-language solutions. Unfortunately it is a very complex thing to do, more so than a language service itself, so it's currently by-design to not do it (at least in the Ionide plugin).

In some distant future there may be a plugin-agnostic project system component that both could use, which would facilitate cross-language interop. But it's not a goal for Ionide to build that component.
