### ISSUE TITLE
fsi config object doesn't get Intellisense

### ISSUE THREAD

**Issue by brettrowberry** [ionide/ionide-vscode-fsharp#1440]
**Describe the bug**
The `fsi` configuration object in F# scripts is recognized in Visual Studio, but not in Ionide.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new file, `Script.fsx`
2. Start typing `fsi.ShowDeclarationValues <- false`
3. No Intellisense appears

**Expected behaviour**
Intellisense appears on the `fsi` object.

**Screenshots**
Here's what is looks like in Visual Studio:
![image](https://user-images.githubusercontent.com/10521647/100276478-9bdf4080-2f2f-11eb-891e-cdb10653e94c.png)

Here's Ionide:
![image](https://user-images.githubusercontent.com/10521647/100276536-b6b1b500-2f2f-11eb-875f-acda810a8d1a.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.17.0
 - VSCode version: 1.51.1
 - dotnet SDK version: 5.0.100

**Additional context**
There might be something I'm missing. I don't think the behavior needs to be identical to Visual Studio, but I couldn't figure it out.

**Comment by baronfel** [comment]
We need to make sure that the f# interactive settings DLL is part of the generated reference set. It was at one point in the past, but it's entirely possible it's slipped out again.

**Comment by Krzysztof-Cieslak** [comment]
@baronfel I can confirm it's broken on the latest preview

**Comment by Krzysztof-Cieslak** [comment]
Correction:

* We don't have access to it in build.fsx/FAKE script
* I can see it on normal .fsx file just fine:

![image](https://user-images.githubusercontent.com/5427083/102109432-529a5680-3e34-11eb-91b1-43d37611f111.png)

**Comment by Krzysztof-Cieslak** [comment]
Ok, this is working as described above in Ionide 5.0, and it's correct behaviour as far as I can tell.

**Comment by brettrowberry** [comment]
I was just about to close this. Yep, works great in v5.0.0. Thank you!
