### ISSUE TITLE
Squiggly lines on types imported on references with #r nuget

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#1441]
**Describe the bug**
I'm importing a nuget package using the the new #r syntax, and while everything works perfectly fine in FSI, the editor shows squiggly lines all over

**To Reproduce**
Put this code on a fsx file:

        #r "nuget: Microsoft.IdentityModel.Clients.ActiveDirectory, 3.19.8"

        open System
        open Microsoft.IdentityModel.Clients.ActiveDirectory

        let getCredentialsForCurrentUser() = 

            let aadLoginUrl = "https://login.windows.net/common/oauth2/authorize"
            let appId = "REDACTED"
            let redirectUri = Uri "urn:ietf:wg:oauth:2.0:oob"
            let substrateResourceId = "https://substrate.office.com"

            let authenticationContext = AuthenticationContext aadLoginUrl
            let authenticationResult = 
                authenticationContext.AcquireTokenAsync(substrateResourceId, appId, redirectUri, PlatformParameters PromptBehavior.Auto)
                |> Async.AwaitTask
                |> Async.RunSynchronously

            let userName = authenticationResult.UserInfo.DisplayableId
            let authToken = authenticationResult.AccessToken

Executing it will work (you will get a popup window saying REDACTED is an in valid app id)
But there are squiggly lines all over, as you can see in this screenshot:

![image](https://user-images.githubusercontent.com/738761/100439384-63f50c00-309b-11eb-953c-5c3263b12649.png)

**Environment (please complete the following information):**
 - OS: Windows 10, version 2004
 - Ionide version: 5.0.0-preview02 (though this also reproes with 4.17.0, but there you have an extra squiggly line on the #r line)
 - VSCode version: 1.51.1
 - dotnet SDK version: 5.0.100
 - mono / .Net Framework version: 5.0.100

**Additional context**
I have "FSharp.useSdkScripts": false, because that pinned old lib version uses Windows Forms underneath for the popups, and I cannot get the newest version that works on .Net core to work at all, but this reproes both with the FSAC netcore mode of either Ionide 5.0.0-preview02 or Ionide 4.17.0, or the FSAC net mode of Ionide 4.17.0

If I use paket to get the Nuget packages and reference the dll directly, this doesn't repro, so it's related to the new #r nuget feature

        #r "packages/Microsoft.IdentityModel.Clients.ActiveDirectory/lib/net45/Microsoft.IdentityModel.Clients.ActiveDirectory.dll"

**Comment by ThisFunctionalTom** [comment]
I have the same issue with preview 2 on Windows with "FSharp.useSdkScripts": true.
If I "Reopen in WSL" then everything is working fine.
Maybe it has something to do with windows paths.

If I can help somehow I would love to. Just please give me some direction where to search.

**Comment by beerai** [comment]
I've got the same issue with preview 2 with the script located in wsl (and not in a Windows mounted path either, it's in ~/source/repos) when running the VSCode remote - WSL extension.

**Comment by ThisFunctionalTom** [comment]
Yes, you a right. It does not work. Hmmm.

![image](https://user-images.githubusercontent.com/3315570/100536578-e3144c80-3221-11eb-9c86-07f0ebe26de7.png)

**Comment by ovatsus** [comment]
Still reproes on 5.0.0-preview03

**Comment by Krzysztof-Cieslak** [comment]
Yes, preview03 still doesn't include latest versions of Dependency Management stuff, waiting for F# team to release it (or rather updated FCS) on NuGet

**Comment by nhirschey** [comment]
Congrats on the official 5.0 release today. FYI, it still looks like intellisense with scripts is a problem with today's release

![image](https://user-images.githubusercontent.com/5226115/102793058-3ef56f80-43a1-11eb-9681-8ce3fe746131.png)

**Comment by baronfel** [comment]
Situation is the same, we're waiting on FCS 38.0.1 still for fixes to the dependencymanager infrastructure.

**Comment by matthewcrews** [comment]
Do we have an eta on FCS 38.0.1 or a ticket we can follow to know how that development is going?

**Comment by baronfel** [comment]
No tracked issue exists, but it's a process-level issue:

* MS's CI pipelines can build, tag and push the signed packages to Nuget
* Nuget fails the push because the MS organization isn't a co-owner of the package
* I've invited them as a co-owner
* Now we have to have whoever at MS controls that email/notification actually accept it before pushes can happen

Alternatively, @cartermp let me know that version `FSharp.Compiler.Service 38.0.1-beta.20607.1` from the nightly feed of FCS (which is public) was the last version that contains the necessary work _and_ doesn't introduce API breakages, so we can experiment with pulling in that version instead, so we don't have to wait. This _should_ be a non-binary-breaking change because the public surface area of the DLL should be backwards-compatible, but we'd have to verify that in testing.

**Comment by cartermp** [comment]
So after much stress and at one point a 5-way communication channel, we finally have package compliance established for the recent nuget.org changes and can publish changes. Hopefully this will get resolved soon, as it's now in our court to publish the 38.0.1 update to nuget.

**Comment by baronfel** [comment]
Ionide 5.0.3 is now available on the VSCode marketplace, and I'm happy to report that this issue and several others related to #r nuget support are now working!


![image](https://user-images.githubusercontent.com/573979/103024840-3a05fc80-4516-11eb-883b-5c3dbfe5129e.png)

**Comment by matthewcrews** [comment]
Are we supposed to be getting intellisense on libraries with native dependencies now?

**Comment by baronfel** [comment]
@matthewcrews I tested with Microsoft.ML, but depending on your exact situation we might still be waiting on a few additional fixes for native deps from upstream.

**Comment by matthewcrews** [comment]
@baronfel Thanks for the info. I'll keep checking as updates keep dropping!

**Comment by matthewcrews** [comment]
FYI, @baronfel and I found that the problem was with my work PC. Everything worked great on my personal workstation.
