### ISSUE TITLE
Allow to select all text in the FSI terminal

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#1442]
Sometimes it's useful to just copy past the whole FSI content to a text file to look at it better, or search for printf statements. Currently Ctrl+A doesn't work in the FSI window, and there is also no right click context menu, so currently the only way is to do the selection by drag the mouse from the bottom to the top, but when you have a long output, that's very cumbersome to do

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately, this is not doable due to limitations in VSCode extensions
