### ISSUE TITLE
[backer] Intellisense not working for *.fsx files (.NET 5)

### ISSUE THREAD

**Issue by blfuentes** [ionide/ionide-vscode-fsharp#1443]
**Describe the bug**
I get a lot of error messages from the IDE for all lines of the code I write in any .fsx file and the Intellisense is not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create F# Project
2. Add fsx file
3. Try to write any code and use intellisense.

**Expected behaviour**
I expect the IDE to offer intellisense

**Screenshots**

![image](https://user-images.githubusercontent.com/5121778/100482431-a0eeec00-30f7-11eb-94cc-93e58b1a62b1.png)

**Environment (please complete the following information):**
 - OS: Windows 10 20H2 19042.630
 - Ionide version: 4.17.0
 - VSCode version: 1.52.0-insiders user (I've tried also the 1.51)
 - dotnet SDK version: .NET 5
 - mono / .Net Framework version:

**Additional context**
I tried deleting the .ionide folder and opening the folder again, waiting for the extension to load and open the file again. Most of the time it shows the same issues and when it "works" it is only for one file. If I add a new one, it behaves incorrectly.

Settings:
```
{
    "FSharp.useSdkScripts": true,
    "FSharp.addFsiWatcher": true,
    "FSharp.dotNetRoot": "C:\\Program Files\\dotnet\\sdk\\5.0.100\\",
    "FSharp.externalAutocomplete": true,
    "FSharp.fsiSdkFilePath": "C:\\Program Files\\dotnet\\sdk\\5.0.100\\FSharp",
    "FSharp.analyzersPath": [
    
        "packages/Analyzers",
        "analyzers"
    ]
}
```

**Comment by ThisFunctionalTom** [comment]
I have the same problem. 
If I reopen the same directory in WSL everything is working fine.
I guess it has something to do with windows paths and '\'.

I would love to help on this issue, just please give me some directions where to search.

**Comment by prestontw** [comment]
I've run into the same problem. I am able to replicate the problem in the first `.fsx` file I open---each one after that works fine.

Settings:
```
  "FSharp.useSdkScripts": true,
  "FSharp.dotNetRoot": "/usr/local/share/dotnet"
```
`dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by prestontw** [comment]
Possibly same as https://github.com/ionide/ionide-vscode-fsharp/issues/1436

**Comment by ThisFunctionalTom** [comment]
Also possible duplicate #1441

**Comment by joshspicer** [comment]
I've noticed that I don't get LineLens when I have a second editor window open side by side.  Some people ending up here might want to try closing your other editor window to see if it helps

**Comment by realvictorprm** [comment]
I have no Problems under Ubuntu 20.10

**Comment by yetanotherlogonfail** [comment]
gone back to full visual studio, no issue there

**Comment by Krzysztof-Cieslak** [comment]
Scripting should work just fine with Ionide 5.0.X
