### ISSUE TITLE
SAFE template load error in vscode

### ISSUE THREAD

**Issue by heliconho** [ionide/ionide-vscode-fsharp#1445]
Hi All,
When I create a new project with the SAFE stack template and open the project in VSCode. the Ionide extension was not able to load the Client.fsproj

To Reproduce
Steps:
1. use dotnet new -I SAFE.Template to scaffold a project
2. run dotnet tool restore
3. open in vscode

Expected behavior:
The projects to be load correctly

**Screenshots**
![Bugs](https://user-images.githubusercontent.com/13492179/100816279-b873ff00-3480-11eb-9d56-fe9ba69ca4d9.jpeg)

OS: mac
Ionide version: v4.17.0
VSCode version: 1.51.1
dotnet SDK version: 3.1

Any help is appreciated!

Helicon

**Comment by baronfel** [comment]
Can you try restoring the project first, as the error asks you to do?

**Comment by heliconho** [comment]
@baronfel Thanks. I did restore it multiple times but this error still occurs.

**Comment by heliconho** [comment]
Actually, the project is reloaded somehow so I will close it. Sorry for the trouble.
