### ISSUE TITLE
F# Literate doesn't work (sometimes)

### ISSUE THREAD

**Issue by nhirschey** [ionide/ionide-vscode-fsharp#1446]
**Describe the bug**
I created a simple folder with a single test.fsx file in it. I put the example from FSharp.Formatting in it, hit command palette and "F# Literate" option, but all I get is a blank pane for the F# literate window. However, I have other folders where the F# literate command will work.

I have tried:
1. Install a project in the folder
2. Install fsdocs in the dotnet tool manifest
3. Use newest insider build and the newest ionide 5.0 dev extension.

![image](https://user-images.githubusercontent.com/5226115/101219918-a78fdd00-367c-11eb-9fa3-552220eb13af.png)

**Expected behaviour**
See preview of the script file like I do in this folder with the same install:
![image](https://user-images.githubusercontent.com/5226115/101220034-d908a880-367c-11eb-8c52-0cd3520c0d95.png)

**Environment (please complete the following information):**
Version: 1.52.0-insider (user setup)
Commit: 5e350b1b79675cecdff224eb00f7bf62ae8789fc
Date: 2020-12-04T10:15:27.849Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
 - Ionide version: 5.0.0-preview2
 - dotnet SDK version: 5.0.100

**Additional context**

**Comment by nhirschey** [comment]
"fsharp.formatting.commandtool": {
      "version": "7.2.9",
      "commands": [
        "fsdocs"
      ]

**Comment by nhirschey** [comment]
The bug is caused by the (*** include-value: numbers ***)  code.

See this screen shot. If I comment out the include comment, it works. But if I try to include the numbers result, it does not update the literate window.

![image](https://user-images.githubusercontent.com/5226115/101680752-10020400-3a59-11eb-9364-4bd2d1ca76c3.png)

**Comment by Krzysztof-Cieslak** [comment]
F# Literate integration was removed from Ionide a while ago, and I don't think we plan to bring it back.
