### ISSUE TITLE
Intellisense in 5.0 is struggling with some packages from the SciSharp ecosystem

### ISSUE THREAD

**Issue by nhirschey** [ionide/ionide-vscode-fsharp#1447]
**Describe the bug**
Intellisense works for regular F#, but it does not work for the tensorflow related code.

**To Reproduce**

```fsharp
#r "nuget: TensorFlow.Net"
#r "nuget: TensorFlow.Keras"
#r "nuget: SciSharp.TensorFlow.Redist"
#r "nuget: NumSharp"

open Tensorflow
open Tensorflow.Keras
open NumSharp

let tf = Binding.New<tensorflow>()
let W = tf.Variable(-0.06f,name = "weight")
tf.Variable()
```

See here for the comparison to the behavior in visual studio, where intellisense works (but fsi does not):
https://github.com/SciSharp/TensorFlow.NET/issues/656

**Environment (please complete the following information):**
Environment (please complete the following information):
Version: 1.52.0-insider (user setup)
Commit: 5e350b1b79675cecdff224eb00f7bf62ae8789fc
Date: 2020-12-04T10:15:27.849Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Ionide version: 5.0.0-preview2
dotnet SDK version: 5.0.100

**Comment by baronfel** [comment]
This is probably because the version of the #r handler for nuget we have in FSAC is behind the officially-released one. We can't do anything about that until the next version of the FCS package is published (which should be very soon, as Kevin Ransom is working on that right now.)

**Comment by nhirschey** [comment]
Got it, thank you.

**Comment by nhirschey** [comment]
@baronfel, perhaps this is still the FCS package thing affecting ionide 5.0, but I just discovered that everything (intellisense and code) works correctly on stable VS Code and ionide 4.17.0 with --langversion:preview enabled.

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by nhirschey** [comment]
This is probably the same issue as https://github.com/ionide/ionide-vscode-fsharp/issues/1441, so to help with housekeeping I will close this for now and then reopen it if the impending FCS fix doesn't fix this too.
