### ISSUE TITLE
F# scripts in subdirectories fail to load the core library

### ISSUE THREAD

**Issue by mrakgr** [ionide/ionide-vscode-fsharp#1449]
**To Reproduce**
1) Make a directory like `E:\F# Tests`. Open it in VS Code. In VS Code, create `test.fsx` with the line `let x = 1`. This works.
2) Create a subdirectory `qwe` with the file `asd.fsx` and the line `let x = 1`. This gives the following error:
![ionide bug](https://user-images.githubusercontent.com/6266635/101661574-bdb8e700-3a48-11eb-8e30-9bb7aaccd33a.png)

**Environment (please complete the following information):**

 - VSCode version:
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
 - dotnet SDK version: Core 5.0.101 (installed the .NET SDK today)
 - mono / .Net Framework version: Microsoft .NET Framework Version 4.8.03752 (from VS's About page)

**Comment by Krzysztof-Cieslak** [comment]
To work on .NET 5 SDK correctly you need preview version of Ionide 5.0 (installation instructions here:  https://github.com/ionide/ionide-vscode-fsharp/issues/1305#issuecomment-726854574)

I can't reproduce this issue on the latest preview:
![image](https://user-images.githubusercontent.com/5427083/102117431-95f9c280-3e3e-11eb-8da3-67e83a14418f.png)
