### ISSUE TITLE
Intellisense does not work for new tab

### ISSUE THREAD

**Issue by nicholas-brooks** [ionide/ionide-vscode-fsharp#145]
Not sure whether this is an issue or is just by design...

Intellisense does not work in a new f# tab in VSCode.  I've tested this using mono 4.4.2, VSCode 1.4.0, and ionide 2.2.7 on OSX 10.11.6.

How to reproduce:

1. Start a new Visual Studio Code instance
2. With a new tab, change language mode to F#
3. Try intellisense on List for example and you see this:

    ![no-intellisense](https://cloud.githubusercontent.com/assets/1787619/17843791/85e37894-6875-11e6-8850-9f98d540d885.png)

If you then save the file as .fsx for example, and try step 3 above, you then see:

![with-intellisense](https://cloud.githubusercontent.com/assets/1787619/17843847/ee453d46-6875-11e6-9b70-2b9b4e0a2b89.png)

**Comment by cloudRoutine** [comment]
by upstream constraint

**Comment by nicholas-brooks** [comment]
Thanks @cloudRoutine, thought it may be.
