### ISSUE TITLE
ionide5:  C# project references do not resolve namespaces

### ISSUE THREAD

**Issue by laenas** [ionide/ionide-vscode-fsharp#1457]
**Describe the bug**
In mixed-language solutions, ionide appears to not properly resolve the namespaces available in the C# projects in the solution, when being consumed by F#.

**To Reproduce**
Steps to reproduce the behaviour:

1. dotnet new sln
2. dotnet new classlib -lang F# -o consumer
3. dotnet new classlib -lang C# -o cslib
4. dotnet sln add consumer
5. dotnet sln add cslib
6. dotnet add consumer reference cslib
7. dotnet build
8. consumer\Library.fs <- open cslib
9. //red squiggles under 'cslib'
10. consumer\Library.fs <- Class1() |> ignore
11. //red squiggles under 'Class1' 
12. dotnet build

We get success in that second build, which confirms it's not actually an error or unknown reference, but something internal to how ionide is parsing these cross-language references.

This behavior does not occur in 4.17 - wherein the open directive is unflagged, and Class1 is visible to intellisense normally.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `5.0.1`
