### ISSUE TITLE
fsacRuntime setting removed?

### ISSUE THREAD

**Issue by mattstermiller** [ionide/ionide-vscode-fsharp#1462]
My environment:
- Ionide v5.0.3
- Windows 10 2004
- dotnet 5.0.101

I am working on a .NET Framework project and had the `fsacRuntime` setting on "net", otherwise VS Code would show errors all over my project, which I believe is due to the FsXAML type provider not being supported by the netcore runtime.

Today, I opened up my project, Ionide was updated to 5.0.3, and I got all the errors from the runtime using netcore. I saw that the `"FSharp.fsacRuntime"` setting is suddenly an unknown setting, and Ionide's settings list does not seem to offer any replacement. The only setting that seems relevant is "Use SDK Scripts", but toggling that off did not help and only produced the warning "You are running .Net Core version of FsAutoComplete, we recommend also using .Net Core version of F# REPL."

How do I go back to using .Net framework version of autocomplete without the fsacRuntime setting?

**Comment by Krzysztof-Cieslak** [comment]
As it was announced almost year ago in https://github.com/ionide/ionide-vscode-fsharp/issues/1305 Ionide starting from version 5.0 won't provide an option to run on mono or full framework but will depend on .NET SDK (.NET 5 SDK in case of Ionide 5.0)
