### ISSUE TITLE
Add file could use xml node other than Compile

### ISSUE THREAD

**Issue by v-zubritsky** [ionide/ionide-vscode-fsharp#1466]
### Describe the bug
`Add file` project context menu action seems to be using the tag of the nearest existing element. So if we have sth other than `Compile` in the project already, file will be added, but won't be included for compilation.

### Steps to reproduce
1. Create F# project with the only source file, which is `Program.fs`
2. Add `app.config` to the top of the project file as ` <None Include="app.config" />`
3. Invoke `Add file` context action and add the other `fs` file

Try to add any `fs` file to the attached project
[repro.zip](https://github.com/ionide/ionide-vscode-fsharp/files/5751476/repro.zip).

### Expected behaviour
File is added as `Compile` node and is visible in the solution explorer.

### Actual behavior
File is added as `None` and it's not obvious from the UX prospective that file was added at all (I've added it three times and checked the F# output before decided to look at the project file contents)

## Machine info

```
Ionide 5.0.3

.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

.NET SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
```

**Comment by baronfel** [comment]
This comes from FSAutoComplete, and I believe it happens [here](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/FsprojEdit.fs#L60-L69).

We clone the first element in the `ItemGroup` and only change its `Include` attribute, but to be honest we probably could be simpler here and create the `Compile` element directly.

**Comment by v-zubritsky** [comment]
@tboby I see you changed the logic a bit https://github.com/fsharp/FsAutoComplete/commit/caa7620a8198d5db721a17f26f8678b92401467e#diff-46601946d8b3fd05946722ab8c059f2fede8bac7d81efbe9cf420cac03b3f24a

Should it be closed now? I verified the behavior on the latest release and it works well for at least the scenario I described here.

**Comment by tboby** [comment]
Yes, that change was to handle your/this issue, this bug should now be fixed!

**Comment by v-zubritsky** [comment]
@tboby Cool, thank you. Closing then.
