### ISSUE TITLE
Active patterns + srtp seems to break colorization a bit

### ISSUE THREAD

**Issue by cartermp** [ionide/ionide-vscode-fsharp#1467]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/6309070/103332683-d7ce5f80-4a1f-11eb-8d7f-73867e95a484.png">

```fsharp
let inline (|PeePee|) x = (^a : (member PeePee: string) x)
let inline peepee (PeePee pp) = pp
let inline (|PooPoo|) x = (^a : (member PooPoo: string) x)
let inline poopoo (PooPoo pp) = pp

let inline yeet ((PeePee pp & PooPoo pp') as toilet) =
    peepee toilet = pp && poopoo toilet = pp'
```

After `PeePee` it seems to break function colorization. For some reason, `yeet` doesn't have this problem, but other parts of its body do.

**Comment by cartermp** [comment]
> priority support

You said it, not me! 💩 🟡

**Comment by Krzysztof-Cieslak** [comment]
>  If possible

;P

**Comment by cartermp** [comment]
Seems like if FSAC can expose data from ServiceSemanticClassification it should work out okay. Here's VS, which uses it:

![image](https://user-images.githubusercontent.com/6309070/103376280-1819f600-4a91-11eb-95dc-f98134fcaec6.png)

**Comment by baronfel** [comment]
here's what I get on an out-of-the-box ionide install on windows with the Dark+ theme:

![image](https://user-images.githubusercontent.com/573979/103376993-b31bcb80-4aa3-11eb-9c97-ab4b4f14b77d.png)

I guess the big things to look at would be:

* the coloration of the `string` typesigs in the srtp member constraints
* the coloration of the applications of the AP in the `yeet` parameters and the `peepee`/`poopoo` function parameters
*

**Comment by Krzysztof-Cieslak** [comment]
Why do I see something different? (also Dark+ theme)

![image](https://user-images.githubusercontent.com/5427083/103379640-95238a80-4ae6-11eb-97ce-3d08289aee8c.png)

**Comment by forki** [comment]
I'm very happy that we are adults with our examples :-)

**Comment by cartermp** [comment]
It's the only way I can  write srtp code

**Comment by cartermp** [comment]
Hmmm. Now I don't see the bad coloring I saw before. Doesn't matter the theme. I'll close this out.

@baronfel and I discussed this a bit and thing that there's still something _off_ in the active pattern as a parmaeter, because it does highlight everything as a single parameter when it's not. That's because there are several ranges, some of which are subranges that have more detailed information. Right now FSAC doesn't appear to dive into them and/or there's a capability in LSP lacking that doesn't allow for as much differentiation when compared with VS. But that's pretty minor.

**Comment by baronfel** [comment]
For posterity, I do think it's worth keeping this (or a related issue) open to capture the need for deduplication of the subranges (and show the difference).

**Comment by Krzysztof-Cieslak** [comment]
OK, this should be better with FSAC update.

**Comment by FelipeF1198** [comment]
Q
