### ISSUE TITLE
Disabling F# view on the sidebar doesn't prevent it from re-opening.

### ISSUE THREAD

**Issue by adam-becker** [ionide/ionide-vscode-fsharp#1469]
### Describe the bug
If you right click the side bar and uncheck "F#", the view will go away. However, on subsequent re-opening of a project with ionide the F# view will forcefully re-open. Clicking away from the view (Like when clicking the file explorer) causes it to disappear again.

### Steps to reproduce
See above.

### Expected behaviour
Once disabled, the F# view should never be shown again.

## Machine info
 - OS: Arch Linux
 - .NET SDK version: `5.0.101`
 - Ionide version: `5.1.0`

**Comment by tboby** [comment]
You should be able to resolve this by unticking the setting: `FSharp.showExplorerOnStartup`.

I've spent a bit of time looking at the VS Code API and as far as I can tell showing/hiding/pinning/unpinning activities/view containers isn't exposed to extensions, neither is viewing the current state of view containers. I can't see where the setting is persisted (it's not in settings.json). The extension view is shown using a command, so no obvious API object. So I'm not sure it's even possible to properly handle this.

**Comment by Krzysztof-Cieslak** [comment]
Yes, @tboby is right here. Disabling `FSharp.showExplorerOnStartup` is the correct solution here, and we can't do anything more about it.
