### ISSUE TITLE
f# solution explorer not loading

### ISSUE THREAD

**Issue by gapariha** [ionide/ionide-vscode-fsharp#1473]
I have the fsharp ionide-fsharp remote extension installed on my WSL2. 
When opening remote source location source code from my WSL2, from past few days, VS code is not able to load fsharp Solution Explorer on the blade on the left most side. 

Is there a known issue?

**Comment by loafingaround** [comment]
I am having the same issue. I'm also using Linux.

**Comment by baronfel** [comment]
We're going to need logs with the `Fsharp.verboseLogging` flag set to true before any kind of reasonable help can be offered here.

**Comment by loafingaround** [comment]
@gapariha Now when I load up a folder containing F# code the F# Solution Explorer does load on the blade. Does it load for you too now?

**Comment by gapariha** [comment]
Yes. I have had intermittent issues with F# ionide plugin on VS code. We can close this issue for now.

**Comment by baronfel** [comment]
Ok, I will do so. Please reopen with output logs if you have issues in the future.
