### ISSUE TITLE
Fable and Ionide disagree on whether Promise.map can be compiled

### ISSUE THREAD

**Issue by davedawkins** [ionide/ionide-vscode-fsharp#1476]
References to `Promise.map` are shown as being `not defined` in the editor (red squiggles) and in the solution browser (file displayed in red).

### Steps to reproduce

Open Promise.fs in VSCode from repo linked below.  Note how `Promise.map` and `Promise.catch` are shown as being undefined.

Screenshot included below.

```
clone https://github.com/davedawkins/Fable.Sveltish
dotnet tool restore
npm install
```

File is `src/Fable.Sveltish/Promise.fs`

https://github.com/davedawkins/Fable.Sveltish/blob/main/src/Fable.Sveltish/Promise.fs

I'm not sure if it will help, but I'll see what it takes to make the repo compatible with gitpod.

### Expected behaviour

Because this code compiles, I expect no errors to be showing in VS Code editor and solution file browser

### Screenshots

![image](https://user-images.githubusercontent.com/285421/104088563-ce36ca00-525f-11eb-97ca-648c8a50a39a.png)

## Machine info
 - OS: Mac
 - .NET SDK version: 5.0.101
 - Ionide version: 5.1.0

### Additional context

Have tried removing `bin`, `obj`, `.ionide` folders, reloading window.

Thank you!

**Comment by davedawkins** [comment]
Can't see how to add `backer` label, but it doesn't matter!

**Comment by alfonsogarciacaro** [comment]
Not sure why it worked in Fable but seems it was just a dependency missing, I think this can be closed :)
