### ISSUE TITLE
Ionide VSCode does not function anymore on Mac

### ISSUE THREAD

**Issue by l1x** [ionide/ionide-vscode-fsharp#1478]
### Describe the bug**

Ionide breaks on Mac VSCode

### Steps to reproduce

Open VSCode in a F# project folder

### Link to sample reproduction

https://gist.github.com/l1x/bc22ab461ccb88136e2f00d1501f6dd2

### Expected behaviour

Working ionide.

### Screenshots

https://gist.github.com/l1x/bc22ab461ccb88136e2f00d1501f6dd2

## Machine info
 - OS: Mac
 
 - .NET SDK version: [e.g. 5.0.100]

dotnet --list-sdks
2.2.402 [/usr/local/share/dotnet/sdk]
3.1.101 [/usr/local/share/dotnet/sdk]
5.0.100 [/usr/local/share/dotnet/sdk]

 - Ionide version:  5.1.0

**Comment by cartermp** [comment]
what happens if you do `dotnet build`?

**Comment by baronfel** [comment]
This issue is tracked over at https://github.com/ionide/proj-info/issues/95, and in fact impacts the F# compiler itself on OSX. In the meantime I suggest you revert to the 4.x branch of ionide, as we have no ETA for resolution of this error at this time.

**Comment by baronfel** [comment]
If you can reduce your project down to a minimal failing sample that could help us triage the issue faster.

**Comment by MangelMaxime** [comment]
This issue reminds me of https://github.com/ionide/ionide-vscode-fsharp/issues/1458

If possible for your project can you please try using dotnet `3.1.301` as it was working in my case?

**Comment by baronfel** [comment]
@MangelMaxime note that in this case the user has successfully launched Ionide (and Ionide has started project cracking). If the user had an issue with not having the .net SDK 5.0, there would be a different error entirely and project cracking would not even have started.

**Comment by MangelMaxime** [comment]
@baronfel Ah my bad I just focused on the error message being similar 😅

**Comment by l1x** [comment]
> what happens if you do `dotnet build`?

It works just fine. This works too: Ionide.Ionide-fsharp-4.17.0.vsix

**Comment by l1x** [comment]
> This issue reminds me of #1458
> 
> If possible for your project can you please try using dotnet `3.1.301` as it was working in my case?

How should I do that? I think I use version 3.1.xx.

**Comment by l1x** [comment]
> This issue is tracked over at [ionide/proj-info#95](https://github.com/ionide/proj-info/issues/95), and in fact impacts developing the F# compiler itself in Ionide on OSX. In the meantime I suggest you revert to the 4.x branch of ionide, as we have no ETA for resolution of this error at this time.

Thanks!

**Comment by l1x** [comment]
> If you can reduce your project down to a minimal failing sample that could help us triage the issue faster.

Ok I think I can try to do that. The only issue is that I have downgraded to Ionide 4.x and it works now.

**Comment by evgeniysharapov** [comment]
I have similar issues with VSCode on Windows. I could repeat it few times now. Install IONIDE on fresh VSCode. It works. Then install "Remote - WSL" extension, after some time Ionide doesn't work. There's no error (at least I don't see anything) or any other indication. .fs files are still parsed and colored but intellisense and any type hints are gone.

**Comment by Krzysztof-Cieslak** [comment]
This issue is a bit outdated, and we have had various fixes in this area, so I'm closing it.
