### ISSUE TITLE
Go to definition not working if there is a new line after a (

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1480]
### Describe the bug**

If there is a new line after a `(` we can't "Go to definition".

### Steps to reproduce

1. Copy/paste the this code

```fs
module Repro =

    type Replacer () =
        static member Replace(value : string, a : string, b : string) = ""

    let x = Replacer.Replace("", "", "")

    let y = Replacer.Replace(
                "", "", "")
```

2. Try to "Go to definition" by doing `Ctrl + Click` on `Replace` of the line `let y`
3. See nothing happen

### Expected behaviour

We should be able to go to definition.

### Screenshots

![ionide_go_to_def_bug](https://user-images.githubusercontent.com/4760796/105019345-495d6480-5a46-11eb-9ced-8d42c07cd0ae.gif)

## Machine info
 - OS: Linux
 - .NET SDK version: [e.g. 5.0.100] 5.0.101
 - Ionide version: [e.g 5.0.1, don't use descriptions like `latest` ] 5.2.0

**Comment by Krzysztof-Cieslak** [comment]
Cool! 😂

**Comment by not-rusty** [comment]
Happening as well with the following code:

```fsharp

// Errors.fs

module Errors =
    exception AuthError of message: string * code: string

// Main.fs

let login =
    promise {

        let! optionUser = Models.UsersModel.getUser ("user@test.com", None)

        let user =
            match optionUser with
            | Some u -> 1
            | None ->
                let error =
                    Errors.AuthError( // This is not recognized
                        message = "Provided email not found",
                        code = "Error.NOT_FOUND_EMAIL"
                    )

                1
                // raise error

        return user
    }
```

It is really strange that the order of match options affects the syntax colors aswell, which makes me suspicious. Sadly I can't find what exactly does cause this behaviour, I've seen it happens with exceptions and classes inside modules in other files.

**Comment by baronfel** [comment]
This is still active in 5.10.1.

**Comment by baronfel** [comment]
@yuri-potatoq I think your example might be slightly different - that's a type alias, and those are often wonky in tooling APIs and typically require some special handling.

**Comment by yuri-potatoq** [comment]
Thank you to quickly help me.
I see the difference, but what about this another case?
Basically, this happen with all implementations that i'm currently using in this sample project.

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/47803046/f1072296-6a03-41df-95ec-20529dbc8392)

**Comment by MangelMaxime** [comment]
It seems like my original issue is fixed.
