### ISSUE TITLE
"Dot Net Root" does not help Ionide find a dotnet.exe that is not on the PATH

### ISSUE THREAD

**Issue by Happypig375** [ionide/ionide-vscode-fsharp#1487]
### Describe the bug**
Due to not having admin access, https://dot.net/v1/dotnet-install.ps1 was used to install dotnet on the path `P:\dotnet\dotnet.exe`. However, Ionide cannot find it despite setting `P:\dotnet` as the setting "Dot Net Root".

### Steps to reproduce
1. Install Ionide without installing the .NET SDK
2. Use https://dot.net/v1/dotnet-install.ps1 with the `-InstallDir P:\dotnet`
3. Load up Ionide
4. `dotnet new console -lang F#`
5. The F# language server cannot be started because `dotnet` was not found.

### Link to sample reproduction
N/A, this is not a source code issue.

### Expected behaviour
The F# server can start successfully.

### Screenshots
![image](https://user-images.githubusercontent.com/19922066/105798180-85577300-5fcc-11eb-91ca-89e7b51c7729.png)

## Machine info
 - OS: Windows
 - .NET SDK version: 3.1.405
 - Ionide version: 5.2.0

### Additional context
N/A

**Comment by MangelMaxime** [comment]
Hello @Happypig375 you mentioned using .NET SDK version 3.1.405 but Ionide needs version .NET 5 to execute. You can still use version 3.1.405 for your project by using a `global.json` file to specify the version you want your project to use.

Can you try installing .NET 5 on your machine?

**Comment by Happypig375** [comment]
Then how to install .NET 5 using `dotnet-install.ps1`? I do not have admin rights, cannot install it via the installer.

**Comment by MangelMaxime** [comment]
In the script you listed it seems like you have a Version parameter:

```
.PARAMETER Version
    Default: latest
    Represents a build version on specific channel. Possible values:
    - latest - most latest build on specific channel
    - 3-part version in a format A.B.C - represents specific version of build
          examples: 2.0.0-preview2-006120, 1.1.0
```

Probably via `-Version` or `--version` argument

**Comment by Krzysztof-Cieslak** [comment]
Closing, as mentioned above Ionide requires .NET 5.0
