### ISSUE TITLE
The language server immediately crashes upon starting up

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#1489]
### Describe the bug**
As soon as I open VSCode, I am greeted with a message that the F# server crashed many times and will not be restarted.

### Steps to reproduce
1. Open VSCode.
2. Wait for at most 10 seconds.
3. Look at the bottom-right of the screen.

### Link to sample reproduction
https://github.com/teo-tsirpanis/Farkle (it crashes even with a clean repository so no need to build anything)

### Expected behaviour
The F# server would not crash.

### Screenshots
![image](https://user-images.githubusercontent.com/12659251/106168319-cd29f600-6196-11eb-9a0e-21cd401259e8.png)

![image](https://user-images.githubusercontent.com/12659251/106169152-bafc8780-6197-11eb-8c5f-114076de306c.png)

## Machine info
 - OS: Windows 10
 - .NET SDK version: 5.0.102
 - Ionide version: 5.2.0

**Comment by teo-tsirpanis** [comment]
It seems that my computer has a problem and cannot recognize any .NET SDK.

But still the tools could have shown a nicer message.

**Comment by baronfel** [comment]
We would welcome any contributions to the [startup flow](https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Core/LanguageService.fs#L649-L703) around giving users better error messages.

**Comment by teo-tsirpanis** [comment]
I found it. When I uninstalled an old .NET SDK it changed the PATH and Program Files (x86) was put before Program Files.

**Comment by OriginatorStar** [comment]
> I found it. When I uninstalled an old .NET SDK it changed the PATH and Program Files (x86) was put before Program Files.

I did this too, but what I get from the F# output is a reference to a folder path that ionide seems to send, and it breaks it:
(I've already set FSharp.dotnetRoot)

`Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'c:\repos\fs\FirstIonideProject\dotnet' with working directory 'c:\repos\fs\FirstIonideProject'. The system cannot find the file specified.`

That dotnet folder is not created by default when scaffolding a F# project. To me ionide seems to be failing to look for the dotnet.exe ?

Give me some clues please on where should I look to correct this. I've checked my system path env var, and the first thing there is the path to dotnet sdk.
