### ISSUE TITLE
intellisense not working

### ISSUE THREAD

**Issue by AkashGutha** [ionide/ionide-vscode-fsharp#149]
i'm having intellisense problems. 

main.fs  
``` fs
open System
open Instant

module main = 

    [<EntryPointAttribute>]
    let main argv =
        let a = 25.0
        let b = 5.0
        let res = math.power a b
        printfn "the power is %.2f" res
        //return 0. to indicate success
        0

```

and a library file at ./lib/math.fs

``` fs
namespace Instant

[<RequireQualifiedAccess>]
module math = 

    let add x y = x + y 
    let sub x y = x - y

    let abs x = 
        if(x<0) then x
        else x * -1
        
    let power x y : float = x ** y

    let sqr x:int = x * x
    let sqrt x:float = sqrt x
```

i get red squiggles over 
1. open Instant 
2. math.power

and the error is namespace or module not defined.
how do i make sure that ionide knows all the files and provide proper intellisense.

when i compile this using the following command i get the executable and it runs fine 
``` fs
tsc lib/math.fs main.fs
```

**Comment by cloudRoutine** [comment]
are files in an fsproj?

**Comment by AkashGutha** [comment]
No hand compiling them

**Comment by cloudRoutine** [comment]
you need to us fsproj files for tooling support with .fs files
