### ISSUE TITLE
Add Current File To Project

### ISSUE THREAD

**Issue by mohaalak** [ionide/ionide-vscode-fsharp#1490]
I'm new to F# I was watching some videos on youtube, the developer runs a command called 'Add current File To Project', I did not see this command anywhere, I was searching and found out there was a tool called Forge that is now deprecated that it was this tool job to add the file to project and move up and down the files.

I don't know if this command changed to something else or not

also, I'm reading the project right now if you think that this is a beginner task I can do it and send a pull request.

**Comment by v-zubritsky** [comment]
@mohaalak This doesn't answer your question, just to add some information. 
Forge is indeed [deprecated](https://github.com/ionide/Forge/issues/135) just like you said, while file related operations are provided by [FsAutoComplete](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/FsprojEdit.fs).

I might well be mistaken.

**Comment by baronfel** [comment]
You've got it correct @v-zubritsky. In addition, recently some contributors have massively reworked the file support in Ionide, so I'd check and see if your request is now part of the product.

**Comment by mohaalak** [comment]
there is also a bug just create a f# file but don't add it into fsproj this will show up in the status bar but when you click on it there is a message that says`fsharp.AddFileToProject not found`

<img width="794" alt="Screen Shot 2021-02-07 at 10 30 55 PM" src="https://user-images.githubusercontent.com/891975/107156721-4692c700-6995-11eb-8fb7-50937f479560.png">

I'm working on a pull request right now I found the solution using this [function](https://github.com/ionide/ionide-vscode-fsharp/blob/e68e92da62a1437b7c2fdab5f542ddbc8b210758/src/Core/FsProjEdit.fs#L33)
