### ISSUE TITLE
Support `Format Selection`

### ISSUE THREAD

**Issue by kevingentile** [ionide/ionide-vscode-fsharp#1499]
### Describe the bug**

Selecting a block of code and hot-keying "Format Selection" produces no behavior.

### Steps to reproduce

1. Write out a block of code
2. Highlight block
3. Format selection ( Windows `ctrl +k ctrl + f`)

### Expected behaviour

Block of code is formatted

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.102
 - Ionide version: 5.3.2

### Additional context
"Format document" works as expected. The "Format Selection" hotkeys work for other languages.

**Comment by nojaf** [comment]
Well, maybe 😸. I've done a bit of revamping of how selection works in Fantomas and the current `Fantomas.Client` does expose `FormatSelectionAsync`.

All LSP ranges should be converted to FCS ranges (well https://github.com/fsprojects/fantomas/blob/452064c6e05acd2eaa71520ea006c45cc0455783/src/Fantomas.Client/Contracts.fs#L48-L60, which have the same semantics).

If the selection worked (the scenarios are limited to https://github.com/fsprojects/fantomas/blob/master/docs-old/Documentation.md#format-selection), you get a `SelectedRange` to know what you really need to replace.(https://github.com/fsprojects/fantomas/blob/452064c6e05acd2eaa71520ea006c45cc0455783/src/Fantomas.Client/Contracts.fs#L69).

The best of luck I'd say.

**Comment by Krzysztof-Cieslak** [comment]
This has been implemented in https://github.com/fsharp/FsAutoComplete/pull/969 and will be available in the next Ionide release.
