### ISSUE TITLE
Unexpected changes in the .fsproj after adding new file

### ISSUE THREAD

**Issue by xloggr** [ionide/ionide-vscode-fsharp#1501]
### Describe the bug**
After adding a new file to a project using the F# side bar panel, some lines are removed from the .fsproj file.

For example, I placed `<SatelliteResourceLanguages>en</SatelliteResourceLanguages>` line into the PropertyGroup to prevent language resource creation. This line was removed after adding a new file. 

### Steps to reproduce
1. Open an F# project in VS Code
2. Switch to the F# side bar panel
3. Right-click on the project node, choose "Add file" menu item, type some name, e.g. `file1.fs`, and hit Enter

### Expected behavior
The .fsproj file should have a new entry: `<Compile Include="file1.fs" />` - this is the only expected change.

In addition to this change, there are a couple of unexpected ones:
1. `<?xml version="1.0" encoding="utf-8"?>` is removed from the top of the file
2. `<SatelliteResourceLanguages>en</SatelliteResourceLanguages>` is removed from the PropertyGroup

## Machine info
 - OS: Ubuntu 20.04
 - .NET SDK version: 3.1.406
 - Ionide version: 4.17.0

### Additional context
I realize that 4.17.0 is an old version of the plugin, however, this is the latest one that works with .Net Core 3.1 SDK. The latest plugin version, 5.3.2, doesn't have this bug, but it requires .Net 5.0 SDK which I don't plan to install on this machine. Since .Net Core 3.1 is LTS, and it will be officially supported until December 3, 2022, people may keep using it for quite a while without installing .Net 5.0, and thus, having this issue.

**Comment by baronfel** [comment]
We won't be backporting any fixes to the 4.x branch of the extension. You should know that you can install net5.0 and still _build_ for netcoreapp3.x, as the SDK used to build has nothing to do with the runtime environment of your app/library.

There's no technical reason why you can't upgrade, though of course you are free to do as you wish.
