### ISSUE TITLE
Repeated document formatting adds unnecessary new lines

### ISSUE THREAD

**Issue by not-rusty** [ionide/ionide-vscode-fsharp#1505]
### Steps to reproduce

Have the following setup:

`.editorconfig`

```
[*.fs]
indent_size=4
fsharp_max_array_or_list_width=20
fsharp_max_elmish_width=10
fsharp_single_argument_web_mode=true
fsharp_multi_line_lambda_closing_newline=true
fsharp_record_multiline_formatter=number_of_items
fsharp_max_record_number_of_items=1
fsharp_disable_elmish_syntax=false
```

Some random file, `App.fs` for example:

```fsharp
[<ReactComponent>]
let Dashboard () =
    Html.div [
        Html.div [
        ]
        Html.div [
            Html.text "hola muy buenas"
        ]
    ]
```

And just Ctrl + Shift + I multiple times

### Link to sample reproduction
I don't think it is necessary

### Expected behaviour

To be formated like this:

```fsharp
[<ReactComponent>]
let Dashboard () =
    Html.div [
        Html.div []
        Html.div [
            Html.text "hola muy buenas"
        ]
    ]

```

However, it gets formated like this:

```fsharp
[<ReactComponent>]
let Dashboard () =
    Html.div [
        Html.div [

        ]
        Html.div [
            Html.text "hola muy buenas"
        ]
    ]

```

Which I really don't mind, but the issue is whenever I reformat again the document without changing anything, the format output adds new unnecessary lines:

```fsharp
[<ReactComponent>]
let Dashboard () =
    Html.div [
        Html.div [


        ]
        Html.div [
            Html.text "hola muy buenas"
        ]

    ]

// And on, and on...

[<ReactComponent>]
let Dashboard () =
    Html.div [
        Html.div [




        ]
        Html.div [
            Html.text "hola muy buenas"
        ]



    ]


```

After some testing I found out that just passing an array with a null inside instead of an empty array solves the issue, but I'd expect to work both ways as expected

## Machine info
 - OS: Linux
 - .NET SDK version: 5.0.103
 - Ionide version: v5.3.2

**Comment by MangelMaxime** [comment]
Hello @not-rusty,

Ionide is using [Fantomas](https://github.com/fsprojects/fantomas/) for the formatting. I think you should open the issue there so @nojaf and others can take a look at it.

**Comment by nojaf** [comment]
Yes please, could you report an issue using https://fsprojects.github.io/fantomas-tools/#/fantomas/preview please?

**Comment by Krzysztof-Cieslak** [comment]
Closing as an upstream issue.
