### ISSUE TITLE
Ionide crashes on Apple Silicon

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#1506]
VS Code Insiders and .NET 6 (preview) both run natively on the Apple M1 chip.
I've been using both for the last week to develop C# with the C# VS Code plugin without any issues. Today I tried to install Ionide and it keeps crashing on startup on my machine.

Please let me know how to provide further diagnostics to investigate the issue. I checked the console and there was nothing there from Ionide in regards to the crashes.

**Comment by baronfel** [comment]
One thing that would help is the output from the `F#` output stream in VS Code. In addition, you can set the setting `"fsharp.verboseLogging": "true"` in your `settings.json` to log more to this output stream.

**Comment by baronfel** [comment]
@dustinmoris can you try with Ionide 5.4.0, released earlier today? It fixed a pretty critical issue that was effecting project loading in SDK 5.0.200 and upwards, so you might just be magically fixed now.

**Comment by dustinmoris** [comment]
Yaasssss! You're a champ!

Merci beaucoup 🙏

**Comment by baronfel** [comment]
Thanks for the confirmation :) Happy Hacking!
