### ISSUE TITLE
create new project doesn't work on VSCode 1.4

### ISSUE THREAD

**Issue by vanhp** [ionide/ionide-vscode-fsharp#151]
open VSCode 1.4
press ctrl+shift+p
press f and select f#:new project
select console
enter project directory c:\tmp\fsharp
enter project name testfs
press enter 
got message info project created
but there is no project folder on the directory
ps:
 but the same process work on VSCode insider version

**Comment by cloudRoutine** [comment]
make sure you have a folder open as the workspace root and enter a path relative to that root

**Comment by ThatsGobbles** [comment]
I'm also seeing this issue on VSC 1.17.2, with Ionide-fsharp 3.8.4.

I have a folder open as workspace root, and tried a relative path in the prompt, but I'm not seeing any files getting created.

**Comment by lukegeorg** [comment]
The same here.
VSC: 1.17.2
Ionide-fsharp: 3.9.0

**Comment by MFrat** [comment]
Same bug here.  3.18.0

**Comment by EuroEdit** [comment]
Same here, 3.18.0 - Happens on both my Mac and my Windows pc.
