### ISSUE TITLE
Auto comment doesn't always trigger

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1512]
### Describe the bug**

When pressing `Enter` on a line doc comment `/// ...` line Ionide should add `/// ` at each `Enter`. It seems to do it every other time 

![vscode_comment_not_done_every_time](https://user-images.githubusercontent.com/4760796/110020157-88f7bb80-7d29-11eb-824b-22ba67fdeb03.gif)

I didn't tested yet if this was a problem in Ionide or in VSCode as Ionide doesn't seems to do something special for this feature.

## Machine info
 - OS: Windows
 - .NET SDK version: [e.g. 5.0.100] 5.0.101
 - Ionide version: [e.g 5.0.1, don't use descriptions like `latest` ] v5.4.0

**Comment by MangelMaxime** [comment]
For info, I created an issue on https://github.com/microsoft/vscode/issues/121125 because even when using an empty extension I have this problem.

**Comment by Krzysztof-Cieslak** [comment]
This seems to be fixed in VSCode.
