### ISSUE TITLE
Ionide Solution Explorer wonkiness

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [ionide/ionide-vscode-fsharp#1514]
### Describe the bug**

I have a dotnet core solution with projects in my `src` directory. The hierarchy in the solution explorer changes based on if a project folder is expanded/collapsed. If other project folders are collapsed, the new project appears as a sibling. If the project above the new project is expanded, it appears as a child. There are also situations where the default `Library.fs` file appears as a parent of the child project. 

This is a dotnet core solution with projects in the `src` folder.

See the attached link for a gif that demonstrates this.

### Screenshots

[Solution Explorer Wonkiness](https://imgur.com/a/EWR5oUB)

## Machine info
 - OS: Mac
 - .NET SDK (5.0.103)
 - Ionide version: 5.4.0

### Additional context

I don't know if this relevant or not, the dev environment is based off of MS VSCode's devcontainer for dotnet core:

 mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-5.0

**Comment by kurt-mueller-osumc** [comment]
It turns out that the `Common` project appears as a child of the `Domain` project's `Library.fs`.

**Comment by baronfel** [comment]
This is only a formatting issue with the way VS Code renders icons in hierarchy views like this. You can fix it by

* changing to a different set of icons (some are better than others here), or
* not using icons at all

Here's an example of FSAC with no icons:

![image](https://user-images.githubusercontent.com/573979/110841910-16786580-826c-11eb-807f-a7decd4d6986.png)

**Comment by kurt-mueller-osumc** [comment]
![image](https://user-images.githubusercontent.com/66080261/110842438-14ff6b00-8275-11eb-9de9-44482d27e322.png)

Oops, you're right...
