### ISSUE TITLE
Remove file doesn't work

### ISSUE THREAD

**Issue by DoctorRyner** [ionide/ionide-vscode-fsharp#1517]
### Describe the bug**
"Remove file" does nothing for .fs files

### Steps to reproduce
1. Open an F#
2. Focus on solution explorer view
3. Right click on a .fs file
4. Click "Remove file"

### Link to sample reproduction
Any F# would be good

### Expected behaviour
A file being removed

### Screenshots
<img width="251" alt="スクリーンショット 2021-03-18 22 37 55" src="https://user-images.githubusercontent.com/24430919/111686862-a43eec80-883a-11eb-9086-6ca1b0a3b63d.png">

## Machine info
 - OS: Mac
 - 5.0.201
 - 5.4.0

**Comment by Rekeyea** [comment]
I can confirm this also happens in Windows. 
Is there any news on this? 
I am already a backer.

**Comment by subhashgorasiya** [comment]
The issue is still exists in the current version v5.10.2 in windows.

**Comment by golavr** [comment]
I checked on v6.0.6, still exists.
Guys, don't you think it's an essential feature?

**Comment by baronfel** [comment]
My dude, there are probably lots of essential features that haven't been implemented or have bugs. If it's crippling your workflow, I'd love to see a PR or something for it. Otherwise, we'll get to it when we get to it.
