### ISSUE TITLE
Accented letters not rendering correctly 

### ISSUE THREAD

**Issue by DigiOhhh** [ionide/ionide-vscode-fsharp#1519]
### Describe the bug

Accented letters are not correctly rendered.
I've tried using different fonts, each one of them has this same issue only in `F# Interactive (.Net Core)` terminals.

### Steps to reproduce

1. Open an F# file
2. Highlight a piece of code
3. Press `Alt + Enter` to execute it, or simply open a `F# Interactive (.Net Core)` terminal
4. Try entering accented letters, such as `à`, `è`, `ì`, `ò`, `ù`. This also happens with other characters: `£`, `é`, `ç`, `°`, `§`, …

### Expected behaviour

Every character should be rendered correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/37815914/114299846-c20c1400-9abd-11eb-8214-80b4e4eca2c8.png)

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.201
 - Ionide version: 5.4.1

**Comment by nhirschey** [comment]
I believe this is the same as https://github.com/ionide/ionide-vscode-fsharp/issues/1498

**Comment by DigiOhhh** [comment]
Yes it is, this also happens with paths.
in my case, every `#silentCd` directive fails because there's always an accented letter in the path it tries to `cd` to.
Should I close this?

**Comment by nhirschey** [comment]
Try the fsiExtraParameters fix here:
https://github.com/ionide/ionide-vscode-fsharp/issues/1236#issuecomment-725891973

**Comment by DigiOhhh** [comment]
> Try the fsiExtraParameters fix here:
> [#1236 (comment)](https://github.com/ionide/ionide-vscode-fsharp/issues/1236#issuecomment-725891973)

it works, thank you!
