### ISSUE TITLE
LineLens set to "never" behaves the same as set to "always"

### ISSUE THREAD

**Issue by jvcmarcenes** [ionide/ionide-vscode-fsharp#1522]
### Describe the bug**
In order to disable the inlined LineLens I changes the setting to "never", however, the line lens pomptly starte appearing at the top of functions and variables. as it should be when set to "always"

### Steps to reproduce
Open settings.json
Set "FSharp.lineLens.enabled" to "never"
Open a F# file

## Machine info
 - OS: Windows 8.1
 - .NET SDK 5.0.202
 - Ionide version: 5.4.1

**Comment by baronfel** [comment]
Are you sure that's not the `codeLens`? `codeLens` appear on top of functions/variables and are something provided by VSCode, but you can change their behavior with the `editor.codeLens` settings.

**Comment by jvcmarcenes** [comment]
> 
> 
> Are you sure that's not the `codeLens`? `codeLens` appear on top of functions/variables and are something provided by VSCode, but you can change their behavior with the `editor.codeLens` settings.

Thats's odd, I never had code lens show up for any other language that I use with vscode, I thought I had disabled it
but my bad then, sorry for the incovenience if anything. and thanks for the reply
