### ISSUE TITLE
member suggestion on "." partially broken after updated to 5.5.0

### ISSUE THREAD

**Issue by iwinux** [ionide/ionide-vscode-fsharp#1523]
## Describe the bug**

Member suggestion on `.` (e.g.: `System.`) does not work on Ionide-fsharp v5.5.0. It used to work fine on 5.4.1.

## Steps to reproduce

1. create a new F# file.
2. type `System.` and wait for suggestions.

## Expected behaviour

It suggest all members of the `System` namespace, with `DateTime` being the first suggestion.

## Actual behavior

It lists all global identifiers:

![image](https://user-images.githubusercontent.com/98864/115147676-b35dc800-a08e-11eb-9ac0-07c1c917aabc.png)

## Machine info
 - OS: macOS 10.15.7
 - .NET SDK version: 5.0.201
 - Ionide version: 5.5.0

## Additional context

Downgrading the extension back to 5.4.1 fixes the problem for now.

**Comment by iwinux** [comment]
It might be related to https://github.com/fsharp/FsAutoComplete/issues/762.

**Comment by baronfel** [comment]
Yep, the FSAC issue is the root cause of the issue you demonstrate in the editor here. I'm investigating.

**Comment by baronfel** [comment]
Happy to report that 5.5.1 has been released and fixes this issue.
