### ISSUE TITLE
The line lens prefix does not appear in the pipeline steps

### ISSUE THREAD

**Issue by omppye** [ionide/ionide-vscode-fsharp#1524]
### Describe the bug
The line lens prefix does not appear in the pipeline steps

### Steps to reproduce
- Create a `.vscode/settings.json` with `{ "FSharp.lineLens.prefix": " " }`
- Write a pipeline like

```fsharp
let parse (raw: string) =
        let payload =
            raw.Split([| " -" |], System.StringSplitOptions.None)
            |> Array.head

        payload
```

### Expected behaviour
I think the expected behaviour would be the line lens prefix being used in the pipeline steps as well

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/30958533/115150424-afa25500-a03e-11eb-9567-0f2d2cc82099.png)

## Machine info
 - OS `Linux`
 - .NET SDK version `v5.0.202`
 - Ionide version `v5.5.0`

**Comment by baronfel** [comment]
Probably related to the index changes introduced in ionide 5.5, similar to the other issue raised today.

**Comment by weslenng** [comment]
> Probably related to the index changes introduced in ionide 5.5, similar to the other issue raised today.

Reproductible in Ionide `v5.4.1`

**Comment by baronfel** [comment]
Oh, I believe this is a different setting. try setting `FSharp.pipelineHints.prefix` and see if that does what you want.

**Comment by weslenng** [comment]
> FSharp.pipelineHints.prefix

Worked well!
But does it make sense to separate both `lineLens` and `pipelineHints`?

**Comment by Krzysztof-Cieslak** [comment]
> But does it makes sense to separate both lineLens and pipelineHints?

Yes, those are 2 separate features. Users can have pipeline hints enabled while using code lenses rather than line lenses etc
