### ISSUE TITLE
Ionide does not work in the latest VSCode insider build.

### ISSUE THREAD

**Issue by nhirschey** [ionide/ionide-vscode-fsharp#1525]
### Describe the bug**
The latest insider build breaks ionide. I have confirmed on 2 PCs. The build from 3 days ago was fine, but as soon as I close vscode and update to this morning's build ionide is broken.

alt+enter will not send code to the terminal. 

Stable vscode is fine. Not sure how to tell if this is a change in vscode architecture that needs to be handled or if this is a vscode regression that should be fixed on their end.

Some logs from extension host:
```
2021-04-19 17:16:20.311] [exthost] [error] Error: No tooltip information
	at c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:160568
	at c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:160862
	at Immediate.<anonymous> (c:\Users\nicho\.vscode-insiders\extensions\ionide.ionide-fsharp-5.5.2\fsharp.js:2:161225)
	at processImmediate (internal/timers.js:461:21)
```

### Steps to reproduce
Install new insider build.
Version: 1.56.0-insider (user setup)
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:15:35.845Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

I'm using ionide 5.5.2.

1. Create a test file
```
mkdir test
cd test
code test.fsx
```

 
```fsharp
open System
```

2. Now  save the file
3. Open the file in vscode insider and try to run code by selecting a line and pressing alt+enter. The terminal is either all black or will open fsi but fails to send any code.

![image](https://user-images.githubusercontent.com/5226115/115270226-02aa0400-a134-11eb-903f-0f157ef26dd2.png)

**Comment by baronfel** [comment]
Can replicate, and yes I agree that this is related to the new tabbed terminal changes coming in the next version of VS Code.

**Comment by baronfel** [comment]
As a workaround, I was able to manually open the terminals on the output pane, which caused some kind of delayed initialization, after which I was able to send the file contents to the terminal session.

**Comment by baronfel** [comment]
Seems like this may have been fixed 6 days ago in https://github.com/fsharp/FsAutoComplete/pull/776/files#diff-623f1ba877835d6ebca36d15a96ec5c95875082a3a3235a65935e2136e3c02a4? So might be worth re-testing on the latest nightly.

**Comment by nhirschey** [comment]
Yes, seems fixed in my experiements.
