### ISSUE TITLE
Goto definition & rename don't work when the cursor is on the first char of the token

### ISSUE THREAD

**Issue by raghur** [ionide/ionide-vscode-fsharp#1526]
### Describe the bug**
Goto definition, rename etc do not work if you're on the first character of the token 

### Steps to reproduce
1. create a fsx file
2. define a function - let someFunction () = printfn "howdy"
3. use said fucntion - someFunction()
4. go the usage, with caret on the first letter (s) - press F12. tooltip saying no definition found; move one char to the right and press F12; goto definition works.

### Expected behaviour
Goto definition/rename etc all work on the first char as well.

### Screenshots

https://user-images.githubusercontent.com/516267/115721082-4f434880-a39b-11eb-844a-091d006bd95f.mp4

## Machine info
Linux & windows, VS Code
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-49-generic

Ionide - ionide.ionide-fsharp 5.5.2

**Comment by baronfel** [comment]
Thanks for reporting!thanks for reporting. Based on similar issues recently this should be a pretty simple fix, I'll see about fixing it and cutting a new release.
