### ISSUE TITLE
Type alias gives interface warning

### ISSUE THREAD

**Issue by OverlyExcessive** [ionide/ionide-vscode-fsharp#153]
As of 2.4.2 Ionide will give the following warning when defining type aliases.

![ionide](https://cloud.githubusercontent.com/assets/346756/18255876/80e8f794-73ae-11e6-8cf9-d7d70689777b.png)

**Comment by duckmatt** [comment]
Hi @OverlyExcessive, this is a bug in [FSharpLint](https://github.com/fsprojects/FSharpLint) rather in Ionide

**Comment by duckmatt** [comment]
I wasn't able to repeat this, but did see the warning appear when the type definition was incomplete, it looks like the linter hasn't run on the updated valid document. If you can repeat it does the warning disappear after a subsequent keystrokes?
