### ISSUE TITLE
Linter not available

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1533]
### Describe the bug
The FSLint integration appears to be broken. No lint warnings appear, although I have ensured that the linter is turned on.

### Steps to reproduce
1. Create an FSX (or FS) file.
2. Make a lint warning e.g. let x = [ 1 .. 10 ] |> List.map id |> List.map id
3. A lint warning should appear, but nothing does.

I've tested with the dotnet FS Lint tool and that still works.
## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.202
 - Ionide version: 5.5.3

**Comment by faldor20** [comment]
@baronfel  I think there is an argument to be made for being very conservative as far as removing large features. This would effect a huge number of people very negatively. If I was just coming to F# and I discovered it's primary IDE plugin didn't even have linting..... well I'd use C# and never look back.

**Comment by baronfel** [comment]
That certainly an option! The difference here as issues to C# primary comes down to linting and this tooling being OSS only, not MS-backed as they are for C#. That naturally means that available effort is limited.  As such, I have to prioritize remaining compatible with language features as they are released, or stagnating.

I choose to stay up to date with new compiler releases, while sending what updates I can to projects I do not directly control for external features. This strokes the best balance in my opinion, using the limited resources at my disposal.

**Comment by faldor20** [comment]
AHH I wasn't aware there had been a significant change to the language spec. I agree that not supporting current language features is a serious issue in its own right. 

I am very sorry for my undue criticism. You clearly have a difficult choice to make and I very much thank you for making it :).  Keep up the great work :) 

Would it maybe be worth looking at https://github.com/fsprojects/fsharp-language-server which does have working (though less sophisticated) linting or at least mentioning it somewhere along with a acknowledgment that linting is broken?

**Comment by MangelMaxime** [comment]
@faldor20 I think fsharp language server kind of offer the same level of linting as Ionide as it is not using FSharpLint in it. They display the hint coming from the F# compiler.

Also, fsharp language server is a bit behind Ionide in term of language features. There is a PR open https://github.com/fsprojects/fsharp-language-server/pull/93 to upgrade it to the latest version of FCS at the time of the PR.

**Comment by faldor20** [comment]
@MangelMaxime I know there was some discussion about merging the two projects. Yes it definitely doesn't cover the same features but it is many times faster and is much more reliable. I find big or complicated projects often just result in fsac throwing errors or working glacially slowly. I recently tried using the typeshape library it was agony. I assume it was related to reflection and generics and stuff but fsac just completely stopped. Had to switch to fsharp language server.

**Comment by seanamos** [comment]
It looks like FSharpLint has now been updated with version v0.19.0.

**Comment by baronfel** [comment]
yep! I've got a branch locally where I'm trying to update and reenable the tests. I've run into a couple issues though.
