### ISSUE TITLE
\t replaced by ASCII 9 on save when formatOnSave is enabled

### ISSUE THREAD

**Issue by stanciuadrian** [ionide/ionide-vscode-fsharp#1534]
### Describe the bug**

Escaped tabs (`\t`) are replaced by ASCII 9 if formatOnSave is enabled and Save is triggered.
Fantomas [configuration] issue?

### Steps to reproduce

1. Enable Format on Save in VsCode: `"editor.formatOnSave": true`
2. Add a line with escaped tabs: `printfn "Hello\tWorld"`
3. Save the F# file
4. The line becomes `printfn "Hello   World"`. A single `\t` is displayed as 1/2/3/4 spaces.

### Expected behaviour

Escape sequences should not be replaced.

### Screenshots

![image](https://user-images.githubusercontent.com/2334569/117045833-a68cd580-ad18-11eb-98c1-1e96d94cb97b.png)

## Machine info
 - OS: Windows 10 x64
 - .NET SDK version: 5.0.202
 - Ionide version: 5.5.4

Edit: rewording

**Comment by Krzysztof-Cieslak** [comment]
Cc: @nojaf

**Comment by baronfel** [comment]
I do think this is in fantomas. The same source code in the [v4 tools](https://fsprojects.github.io/fantomas-tools/#/fantomas/v4?data=N4KABGBEDGD2AmBTSAuKAHATgSwHYBcAzXMAHUgAlEAba2U0-AdVk2vnMgBpwoBnRPnx4A5n1RgA2rwigI8qABJ8AT3TI0kPPm4z5kRQDcAhtQCuGqXoUAGHgoWQAkriQEAytgBeyew4gALNZgALp6AL5%2BssEGquoSWgS6-gYm5pbS-hAAjFEOkACyxgAeADJ4iKWIuCL4ABbJWdkATDbBYQqRenL5ymqWkABGsLDUjY5GphYSmVnNeY7uiAC22HB0uACC%2BACirgDyhOW4vsEQhKYC7RF5PRNxA8Oj4-qT6TNnYADMC-ru6MZoIgAEKIQisRAABWMmGMy0EiEwLwU%2BEwFmunVuMT68U0TzGv1SUwynwCvwgkH%2BgJBYIhpVgAHdEdBjAIXIZYCzhLBcMj5Kj0f4OvIugo7q8Hgl8Xyie80LN-ABWclQKlA0HgzCIACq6HUmBZbNwHK52B5fPOl0QGJFWJSOMeIwJ2LS03lnwAbCrKQD1bStQBhaisvgBnl8AXQfCsC1gC7UK5Cm7dbGSvFOmVvN1WLJgADs3rVNM1iAKK0GiNj8cTDmFEFF8nFFIdUozhKzJNzAA5C77ixCwxsq1abfW7b001Bpe3XZ2sgBOXvUzaEfCIsPLZbGWMC61JzEp%2B2ToZtl3Ej657J2T4%2B6kaiFLVbrc0q6t72vJsWp-qt54z8-upeuQ3kWK5rpgj5rKML6fLuo5gA20RHj%2B6Z-meco5k08w3i4bj4PsuAACqYCoTDYPUw4Ju%2BCh1gh473ChU6nvas4Xk0PwgX2myYLAZiuAAIjQ2CrOBO5otR8i0YhYBNkox7aJmrGAU0ZI3kUxROIQhF1NUOxUe4dSsMw2DwBRKoBG0%2B62oeE6MYkOj-hhCoONkypqSULiENgxT7PqxjRpgOzFFgiB8HwZq8iqiqWR%2BB5fshuJQApjnZs5CjZF67nFAASogcCYPAZGmQ05kxTRn6Nt%2BiX2YpAGYf42QFlluX5fAAByZjLBWmCHE4a7LOIKrZPB0mybEdnLGY1DCNQFQAGKsFuQiIoRP4pXODU9jeLWsPABRTTN82Lf5onetAdQwoC4EAPoMiZFEjfREp2cl6GpZ82SLll3Gwio%2ByYOUEZFWZpJlZJFVIbZ1WvSxdVpfIrTeupP3GH9APYBGHVdYivX9YNH2PTZDHVZN03YLNJwLZgS3gat8TrWx-jNMBuaQCjaOA-g%2B1kxTiBUzTlZnRdsJRoit33Q0hPxVDAww70Sn1Q4zTYaz6kAGrEsCeDwKIwMlaDUuVQlstJAzylMxxqslHNfFRhFWuuLrEuxhZhuQ8TJsOW9G1K6pVvFPxsD4AA4oIQUhWFEV67G0VuzJVWOmhsNOZ8zRuarB3kxUwJ0NAADWwIi3ngh8AR7hwogg6dZFnxvnHY0tqhzrJ%2B9ubNJlrNtYgDK86C%2BBMtUdOIIJXm4OREWbK4ZbY5g%2BO5nXVljkTz3VdO3uM0rTWswA0ogiDoJp2nVC45fwscpzzyOi90cvzbyab6-m0rW3%2B3pqx8HU0elfXCe-s38tw1Tl9VmngajUEQNxEQnVqjMEQIMAoCAL5ZAXrFay0sPZ-1qinXMXxrys02LNEQuAba4DtjyTwRD-JmC1IRWAuEYH%2BQipRGs5U4pGxlpgs2isFBfBZlkNm01ES4EYYYSoPIRDT26iPPA49wzMIkhAKST0752TXi3H2PCVb8O5sIc%2BpQ4SDHgMYIMsBwo1C7j3Co8if7G04Y-bh8gviW34fxDGxhBjgLfhjOo7gVAEBKNY6%2Bo1f6aGqPAQ4593CqHAVg1uWQvh%2B34XscJRwrFnTYIQSANiOFN1iRoxx6d%2BFRJwFGBBSBAmoPrLwEIfgtB8DmuFCQddwhAA) shows that the formatted text includes an additional apsace after the `\t` character.

**Comment by nojaf** [comment]
This is Fantomas' doing indeed. In short, the string was not recognized as trivia so the string from the AST was printed back out.
Please open an issue via the red button in [the online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAHATgSwHYBcAzXMAHUgAlEAba2U0-AdVk2vnMgBpwoBnRPnx4A5n1RgA2rwigI8qABJ8AT3TI0kPPm4z5kRQDcAhtQCuGqXoUAGHgoWQAkriQEAytgBeyew4gALNZgALp6AL5%2BssEGquoSWgS6-gYm5pbS-hAAjFEOkACyxgAeADJ4iKWIuCL4ABbJWdkATDbBYQqRenL5ymqWkABGsLDUjY5GphYSmVnNeY7uiAC22HB0uACC%2BACirgDyhOW4vsEQhKYC7RF5PRNxA8Oj4-qT6TNnYADMC-ru6MZoIgAEKIQisRAABWMmGMy0EiEwLwU%2BEwFmunVuMT68U0TzGv1SUwynwCvwgkH%2BgJBYIhpVgAHdEdBjAIXIZYCzhLBcMj5Kj0f4OvIugo7q8Hgl8Xyie80LN-ABWclQKlA0HgzCIACq6HUmBZbNwHK52B5fPOl0QGJFWJSOMeIwJ2LS03lnwAbCrKQD1bStQBhaisvgBnl8AXQfCsC1gC7UK5Cm7dbGSvFOmVvN1WLJgADs3rVNM1iAKK0GiNj8cTDmFEFF8nFFIdUozhKzJNzAA5C77ixCwxsq1abfW7b001Bpe3XZ2sgBOXvUzaEfCIsPLZbGWMC61JzEp%2B2ToZtl3Ej657J2T4%2B6kaiFLVbrc0q6t72vJsWp-qt54z8-upeuQ3kWK5rpgj5rKML6fLuo5gA20RHj%2B6Z-meco5k08w3i4bj4PsuAACqYCoTDYPUw4Ju%2BCh1gh473ChU6nvas4Xk0PwgX2myYLAZiuAAIjQ2CrOBO5otR8i0YhYBNkox7aJmrGAU0ZI3kUxROIQhF1NUOxUe4dSsMw2DwBRKoBG0%2B62oeE6MYkOj-hhCoONkypqSULiENgxT7PqxjRpgOzFFgiB8HwZq8iqiqWR%2BB5fshuJQApjnZs5CjZF67nFAASogcCYPAZGmQ05kxTRn6Nt%2BiX2YpAGYf42QFlluX5fAAByZjLBWmCHE4a7LOIKrZPB0mybEdnLGY1DCNQFQAGKsFuQiIoRP4pXODU9jeLWsPABRTTN82Lf5onetAdQwoC4EAPoMiZFEjfREp2cl6GpZ82SLll3Gwio%2ByYOUEZFWZpJlZJFVIbZ1WvSxdVpfIrTeupP3GH9APYBGHVdYivX9YNH2PTZDHVZN03YLNJwLZgS3gat8TrWx-jNMBuaQCjaOA-g%2B1kxTiBUzTlZnRdsJRoit33Q0hPxVDAww70Sn1Q4zTYaz6kAGrEsCeDwKIwMlaDUuVQlstJAzylMxxqslHNfFRhFWuuLrEuxhZhuQ8TJsOW9G1K6pVvFPxsD4AA4oIQUhWFEV67G0VuzJVWOmhsNOZ8zRuarB3kxUwJ0NAADWwIi3ngh8AR7hwogg6dZFnxvnHY0tqhzrJ%2B9ubNJlrNtYgDK86C%2BBMtUdOIIJXm4OREWbK4ZbY5g%2BO5nXVljkTz3VdO3uM0rTWswA0ogiDoJp2nVC45fwscpzzyOi90cvzbyab6-m0rW3%2B3pqx8HU0elfXCe-s38tw1Tl9VmngajUEQNxEQnVqjMEQIMAoCAL5ZAXrFay0sPZ-1qinXMXxrys02LNEQuAba4DtjyTwRD-JmC1IRWAuEYH%2BQipRGs5U4pGxlpgs2isFBfBZlkNm01ES4EYYYSoPIRDT26iPPA49wzMIkhAKST0752TXi3H2PCVb8O5sIc%2BpQ4SDHgMYIMsBwo1C7j3Co8if7G04Y-bh8gviW34fxDGxhBjgLfhjOo7gVAEBKNY6%2Bo1f6aGqPAQ4593CqHAVg1uWQvh%2B34XscJRwrFnTYIQSANiOFN1iRoxx6d%2BG733vQggLhC7GFIfrS%2BVFskYNyVw%2BGEAvgd34TnSpedz58G4rxVwXcIyID2pnXm4ctSRzkSqOCQTlFyVUcxAB2D4lb34VEnAUYEFIECag%2BsvAQh%2BC0HwOa4UJB13CEAA).

**Comment by Krzysztof-Cieslak** [comment]
This was fixed in Fantomas.
