### ISSUE TITLE
Wrong autocomplete when create record type 

### ISSUE THREAD

**Issue by vietnt** [ionide/ionide-vscode-fsharp#1536]
### Steps to reproduce

```
type RecordX = {
     in(put)   :  int 
     //<-- auto complete for type trigger here 
     // but no suggestion after ":" 
}

```
### Expected behaviour
Autocomplete for type should trigger after ":" 

### Screenshots
![image](https://user-images.githubusercontent.com/286320/118991278-ca554a00-b9ad-11eb-81f8-b7dd584ee3f6.png)
![image](https://user-images.githubusercontent.com/286320/118991603-14d6c680-b9ae-11eb-9e4e-9bb8a7fbf584.png)

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.100
 - Ionide version: 5.5.5

**Comment by baronfel** [comment]
In the meantime, you can manually invoke autocomplete with `CTRL/CMD + Space`.

**Comment by MangelMaxime** [comment]
I think this issue can be closed

https://user-images.githubusercontent.com/4760796/185082310-fee70d54-bf31-47d2-bc69-2dc86d2e03fc.mp4
