### ISSUE TITLE
Does not respect .fantomasignore when formatting

### ISSUE THREAD

**Issue by MCluck90** [ionide/ionide-vscode-fsharp#1537]
### Describe the bug
Ionide uses Fantomas for formatting files. It does not respect the `.fantomasignore` file and formats those files anyway.

### Steps to reproduce
1. Create a `.fantomasignore` file
2. Add a line pointing to a file you would not like to format
3. Save `.fantomasignore`
4. Open that file in VS Code
5. Run `Format Document`

### Link to sample reproduction
[MCluck90/ionide-does-not-respect-fantomasignore](https://github.com/MCluck90/ionide-does-not-respect-fantomasignore)

### Expected behaviour
The file should not have any formatting changes applied.

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.203
 - Ionide version: 5.5.5

**Comment by Krzysztof-Cieslak** [comment]
Integration with Fantomas has been massively improved since this was reported.
