### ISSUE TITLE
syntax highlighting is not working

### ISSUE THREAD

**Issue by sharshith** [ionide/ionide-vscode-fsharp#1539]
### Describe the bug**
syntax highlighting is not working
![image](https://user-images.githubusercontent.com/48102853/121158570-189c9100-c868-11eb-90d0-a4720e6e7658.png)

### Steps to reproduce
download .net sdk 5.0 and install it
install ionide-fsharp extension in vscode
open an F# file in vscode

### Expected behaviour
syntax should be highlighted

## Machine info
 - OS: Windows
 - .NET SDK version:  5.0.300
 - Ionide version: 5.5.5

**Comment by mridsole** [comment]
It might be another extension interpreting the `.fs` filetype as something else. In my case it was the `Shader languages support for VS Code` extension interpreting it as a fragment shader.

**Comment by baronfel** [comment]
@mridsole that's quite possible.  @sharshith there are a few things you can do to test the theory out:

* If you use the `Inspect Editor Tokens and Scopes` command from your command palette, F# types and such should have a fairly detailed dialog box appear, with the `language` set to `fsharp`:
![image](https://user-images.githubusercontent.com/573979/126078550-70337ccc-8e22-4885-9546-895d70fc508c.png)

In addition, at the bottom-right of your editor there's a button that tells you what language was detected for the file, you should make sure that F# was detected.

**Comment by Krzysztof-Cieslak** [comment]
A likely solution was provided, without any response. Closing

**Comment by josephlarralde** [comment]
@mridsole good catch, thanks ! It worked for me after I disabled the Shader languages support for VS Code extension. Cheers
