### ISSUE TITLE
Errors not propagating to other consuming files / projects

### ISSUE THREAD

**Issue by not-rusty** [ionide/ionide-vscode-fsharp#1544]
### Describe the bug**

As the title says, errors are not propagating through my projects, but only on the same file.

### Steps to reproduce

Let's say I have this file:

```fsharp
// Users.ids.fs
namespace Users

type Ids =
    | Id
    | CategoryId
    | SellerId
```

And other consuming file:

```fsharp
// Users.Test.fs
namespace Users

type Test = Users.Ids
```

If I rename `Ids` to `Ids2`, the errors are not automatically shown in `Users.Test.fs`. I have to manually insert a line and save the file `Users.Test.fs` to trigger a recompile or something.

### Link to sample reproduction

Is it necessary? This one is really simple. My rep consists of a solution file and two projects, from [this tutorial](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line).

### Expected behaviour

I'd expect to see all files marked with errors in the Ionide solution explorer

## Machine info
 - OS: Ubuntu 20.04
 - .NET SDK version: 5.0.103
 - Ionide version: v5.5.9

### Additional Context

Realistically, I'm pleased with what ionide does, even with all the bugs that it has. I just need a simple and fast way to see all errors in the whole project, so I that I can sell fsharp to my teammates :)

**Comment by baronfel** [comment]
I think this is actually a bug in the underlying Compiler Services that may have been resolved in FCS 40. FSAC is still working through that update, so we can re-check this after that work is done.

**Comment by Krzysztof-Cieslak** [comment]
This seems to be working fine for me on latest Ionide/FSAC
