### ISSUE TITLE
VSCode IntelliSense not working with .fsx files

### ISSUE THREAD

**Issue by rebiiin** [ionide/ionide-vscode-fsharp#1558]
VSCode intellisense and tooltip not working only with **.fsx** files and I don't get errors message about that I have no idea what is the main reason in VSCode ! but it works fine with **.fs** files.

**Comment by 64J0** [comment]
Hey @rebiiin. Which version of Ionide are you using? 

I'm using ```Ionide v5.6.0``` in ```Ubuntu 20.04``` with ```dotnet version 5.0.201``` and those features are working here for the .fsx files.

**Comment by baronfel** [comment]
Also @rebiiin do you have the .net 6 previews installed? Currently FSX support in ionide is completely broken if they are. It's something we're looking into for the next release.

**Comment by rebiiin** [comment]
@64J0  thank you for your replay  Ionide v5.6.0 , dotnet version 5.0.302 and 6.0.100-preview.5.21302.13

**Comment by rebiiin** [comment]
@baronfel  thank you for replay, as you mentioned I have installed the .net 6 previews along .net 5.0.302 I got your answer.
