### ISSUE TITLE
Invalid __SOURCE_DIRECTORY__ on first "FSI: Send Selection"

### ISSUE THREAD

**Issue by ThisFunctionalTom** [ionide/ionide-vscode-fsharp#1562]
### Describe the bug**

When sending selection to FSI the first time (Ionide opens fsi terminal) the __SOURCE_DIRECTORY__ has the wrong value so #load does not work correctly. Sending the same selection the second time (fsi terminal is already open) works correctly and __SOURCE_DIRECTORY__ is set to the directory of the fsx script file.

### Steps to reproduce
1. Create fsx script in a subdirectory with "__SOURCE_DIRECTORY__" as content
2. Close all fsi terminals
3. Select "__SOURCE_DIRECTORY__" in fsx script and press alt+enter (FSI: Send selection)
4. do it again and see that the two outputs are different

### Expected behaviour

Sending __SOURCE_DIRECTORY__ first and second time to fsi should generate the same outcome.

### Screenshots
![image](https://user-images.githubusercontent.com/3315570/128490937-db6add7d-1f6d-473d-af59-1bff7f93787e.png)

## Machine info
 - OS: Windows 10
 - .NET SDK version:
    .NET SDKs installed:
      2.2.402 [C:\Program Files\dotnet\sdk]
      3.0.102 [C:\Program Files\dotnet\sdk]
      3.1.300 [C:\Program Files\dotnet\sdk]
      3.1.403 [C:\Program Files\dotnet\sdk]
      5.0.302 [C:\Program Files\dotnet\sdk]
 - Ionide version: v5.7.1

**Comment by DaveJohnson8080** [comment]
Verified that this works correctly after switching to previous version 5.6.0.

**Comment by baronfel** [comment]
this makes sense given the new shared terminal behavior. all of the terminal state for setting up the source directory happens on the `terminalDidOpen` event handler, so we should wait to send your input to the terminal until that handler has completed. in the meantime you can easily work around this by starting a terminal with the `FSI: Start` command and _then_ sending your selections.

**Comment by DaveJohnson8080** [comment]
That works. I see you made a lot of improvements this week. I appreciate your work on the project!
Thanks!

**Comment by cgravill** [comment]
This one embarrassingly often trips me up when I'm giving demos despite knowing the workaround, as I clear the fsi instance ready. For context, we have some internal built libraries which we `#r` in at the top, which fail to load due to the path not being adjusted yet. Easily fixed but it would be great if it just worked.

The fix sounds ideal, happy to help test if that's useful?

**Comment by MangelMaxime** [comment]
If I understand this issue correctly then I cannot reproduce it.

https://user-images.githubusercontent.com/4760796/185075163-4e103871-ddb8-46fa-b1fa-1d24fa45a920.mp4

I think it can be close now.

**Comment by Krzysztof-Cieslak** [comment]
@MangelMaxime,  I can still repro - please note that script needs to be in the subdirectory, not in the root folder opened in VSCode.

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak Sorry I missed the part about the subdirectory
