### ISSUE TITLE
Project templates missing

### ISSUE THREAD

**Issue by TheLogan** [ionide/ionide-vscode-fsharp#157]
I'm on Ubuntu, in vs code, I have Ionide sharp and paket installed, but when I try to create a new f# project I get the error, wrong template,
If I go to the template folder, it is indeed empty, so I tried refresh templates, which gives the following log:

forge refresh --no-prompt
﻿Getting templates...
Deleting contents of /home/master/.vscode/extensions/Ionide.Ionide-fsharp-2.4.3/bin_forge/../templates
git clone -b templates --single-branch https://github.com/fsprojects/forge.git templates

But the folder is still empty, if I go download the templates manually and unpack the file in the templates folder, and then go create new project it suddenly works, but if I refresh templates or restart vscode, the vanish again. I'm not sure what the problem is though.

**Comment by yreynhout** [comment]
Maybe a silly Q, but do you have git on your path?

**Comment by TheLogan** [comment]
Derp, that was the problem, sorry about that :D
Once I added git to PATH everything's just dandy at least I can suggest adding an error message if that's the case in the future ;P
