### ISSUE TITLE
commands 'fsharp.scriptrunner.run' and 'fsi.SendFile' not found

### ISSUE THREAD

**Issue by tobiasweede** [ionide/ionide-vscode-fsharp#1573]
### Describe the bug**
Using the green icons give the following messages:

- command 'fsi.SendFile' not found
- command 'fsharp.scriptrunner.run' not found

Is there a way to manipulate these values?

### Steps to reproduce
Steps to reproduce the behaviour:

-Load a fsharp script *.fsx
-Click on the green triangle icon OR click on the curved green arrow icon

--> error message:
    command 'fsi.SendFile' not found or command 'fsharp.scriptrunner.run' not found

### Related bugs
https://github.com/ionide/ionide-vscode-fsharp/issues/1086

## Machine info
 - OS: (Arch) Linux
 - aur/dotnet-sdk-bin 5.0.9.sdk400-1 (+29 0.24) (Installed)
 - aur/dotnet-runtime-bin 5.0.9.sdk400-1 (+29 0.24) (Installed)
 - aur/dotnet-host-bin 5.0.9.sdk400-1 (+29 0.24) (Installed)
 - code: 1.45.0
 - Ionide version: 5.7.1

**Comment by kMutagene** [comment]
Got the same on a clean install

**Comment by Krzysztof-Cieslak** [comment]
Both of those commands seem to be working fine for me on macOS

**Comment by Krzysztof-Cieslak** [comment]
Still working for me on both macOS and Windows. Closing.
