### ISSUE TITLE
Project loading failed

### ISSUE THREAD

**Issue by jaylenka** [ionide/ionide-vscode-fsharp#1574]
We have written the needed data into you
Issue Type: <b>Bug</b>

f# projects wont load. I am using Remote-SSH. All files say "Not in a F# project"

Extension version: 5.7.1
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

<summary>A/B Experiments</summary

```

</details>

<!-- generated by issue reporter -->r clipboard because it was too large to send. Please paste.

**Comment by Krzysztof-Cieslak** [comment]
Please try the latest version of Ionide, check Ionide's solution explorer on the activity bar and check logs there.
I'll reopen the issue when more details are provided.
