### ISSUE TITLE
Disable completion (and hover) in string literals (except holes in interpolated strings)

### ISSUE THREAD

**Issue by alfonsogarciacaro** [ionide/ionide-vscode-fsharp#1575]
When you request completion (Ctrl+Space) inside a string literal, Ionide gives you completion suggestions as if it were normal code (and sometimes tooltips are also displayed on hovering). Normally this is not an issue because users don't trigger autocompletion within a string literal. But the [F# template highlighting](https://marketplace.visualstudio.com/items?itemName=alfonsogarciacaro.vscode-template-fsharp-highlight) now forwards completion requests so they're captured by built-in language providers (html or css). But this is also triggering autocompletion by Ionide and the suggestions seem to interfere with the ones coming from the html/css providers (if I disable Ionide I get better autocompletion).

I can try to fix this but I'd like to ask what's the best way to identify whether the cursor is in a string literal (and not a hole). Or we just need to use regular expressions? Is this something that can be fixed here or does it need to be done in FsAutocomplete?

**Comment by alfonsogarciacaro** [comment]
I see that this needs to be solved on the FsAutocomplete side but I cannot find an obvious way to get the current semantic context. I found also a workaround at least for triple quoted interpolated strings (what the highlight extension deals with) by attaching middleware to the [LanguageClient options](https://github.com/ionide/ionide-vscode-fsharp/blob/0e478a31dd0476348b6a9de13aa12b0cbdbb00b1/src/Core/LanguageService.fs#L623):

```js
// @ts-check

opts.middleware = {
    provideCompletionItem: (document, position, context, token, next) => {
        function findNonNestedBraces(text, addLastNonClosedBraceIfAny = false) {
            const results = [];
            const braces =
                [
                    Array.from(text.matchAll(/(?<!\{)\{(?!\{)/g)).map(m => ({ index: m.index, isOpen: true })),
                    Array.from(text.matchAll(/(?<!\})\}(?!\})/g)).map(m => ({ index: m.index + 1, isOpen: false })),
                ]
                    .flat()
                    .sort((x, y) => x.index > y.index ? 1 : x.index == y.index ? 0 : -1);

            let nestedLevel = 0;
            let lastOpenBrace;
            for (let brace of braces) {
                if (brace.isOpen) {
                    if (lastOpenBrace == null) {
                        lastOpenBrace = brace.index
                    } else {
                        nestedLevel++;
                    }
                } else {
                    if (nestedLevel === 0) {
                        if (lastOpenBrace != null) {
                            results.push({ start: lastOpenBrace, end: brace.index });
                            lastOpenBrace = null;
                        }
                    } else {
                        nestedLevel--;
                    }
                }
            }

            if (lastOpenBrace != null && addLastNonClosedBraceIfAny) {
                results.push({ start: lastOpenBrace });
            }

            return results;
        }

        function isTemplateHole(text) {
            const braces = findNonNestedBraces(text, true);
            return braces.length > 0 && braces[braces.length - 1].end == null;
        }

        function tryTripleQuotedTemplate(text) {
            const pattern = /\$"""(?:(?!""")[\s\S])+$/;
            const match = text.match(pattern);
            return match != null ? match[0] : null;
        }

        const text = document.getText().slice(0, document.offsetAt(position));
        const template = tryTripleQuotedTemplate(text);
        if (template == null || isTemplateHole(template)) {
            return next(document, position, context, token);
        }
    },
}
```

I can send a PR if this an acceptable solution for now 👍

**Comment by baronfel** [comment]
You're right in that context-aware completions are a bit of a gap right now. TBH they're not great in VS either. Right now we have two completion contexts:
* hash-directives, and
* everything else

so in order to properly give you that context we'd have to be a bit better about the 'everything else' case. I think it would be relatively simple to answer the question 'is the current position within a format string literal portion' and not return any completions in that case though, because that information is readily available in the parse tree and wouldn't require a ton of processing.
