### ISSUE TITLE
FSI output containing `xA` is incorrectly rendered as a newline

### ISSUE THREAD

**Issue by rmunn** [ionide/ionide-vscode-fsharp#158]
VSCode 1.5.3, Ionide-fsharp 2.4.3, Linux Mint. If I select a variable assignment where the variable name contains the characters `xA` and press Alt+Enter:

```fsharp
let idxAtEnd = List.length data - 1
```

Then the output I get is:

```
> let id
tEnd = List.length data - 1
;;

val id
tEnd : int = 11
```

Clearly the `xA` character sequence is getting interpreted as a newline, probably by something in VS Code. There's probably a means to escape that sequence so that VS Code doesn't mangle the variable name, but I haven't yet delved into VS Code to see why this is happening.

If this bug should better be reported in the VS Code issue tracker, let me know.

**Comment by Krzysztof-Cieslak** [comment]
Can reproduce on Windows. This looks super weird, I *think* it may be an issue on VSCode side (all we do in Ionide is send strings to the output panel)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.5.0`... As Terminal doesn't have same error. I'm pretty sure it's some bug in VSCode Output panel.

**Comment by rmunn** [comment]
This is (was) being caused by https://github.com/Microsoft/vscode/issues/12108, incidentally.

**Comment by rmunn** [comment]
And https://github.com/Microsoft/vscode/issues/12108 was closed as "working as designed", but I dug into the VS Code source and discovered that it's not; it's actually been buggy since VS Code's first public commit. More details in https://github.com/Microsoft/vscode/issues/12608 if anyone is interested.
