### ISSUE TITLE
Generic type parameter not displayed correctly on the info panel

### ISSUE THREAD

**Issue by Evangelink** [ionide/ionide-vscode-fsharp#1583]
### Describe the bug

Generic type parameters are not displayed correctly in the Info Panel but correctly in the over tooltip. The signature of the function defines the type as `Binding<'model, 'a>` and is rendered as `Binding<'model'a>`.

### Link to sample reproduction

See https://github.com/elmish/Elmish.WPF/issues/417#issue-978682895

### Expected behaviour

I would expect the type to be displayed as defined (e.g. `Binding<'model, 'a>`).

### Screenshots

![image](https://user-images.githubusercontent.com/11340282/133145516-55f517ce-ef81-4562-948c-7bc00e8b0b68.png)

## Machine info
 - OS: Windows
 - .NET SDK version: net5.0-windows;netcoreapp3.1;net461
 - Ionide version: v5.7.3

**Comment by Krzysztof-Cieslak** [comment]
I believe this was fixed by the linked FSAC PR.
