### ISSUE TITLE
Script type checking does not work when dotnet 6 sdk is installed

### ISSUE THREAD

**Issue by nhirschey** [ionide/ionide-vscode-fsharp#1584]
### Describe the bug**
**Summary:** Typechecking in .fsx files seems to break after I install dotnet 6 preview sdk. Type checking in .fs files is fine. Perhaps related to https://github.com/ionide/ionide-vscode-fsharp/pull/1559/ not covering scripts? 

**More detail:** Script type checking worked for me last week. Today I noticed type checking wasn't working on one of my windows PCs that I installed dotnet 6 sdk on last week. Reinstalling vscode and ionide (and reverting to old ionide versions including 5.7.1) did not help.

I had another PC that still had sdk 5.0.400 on it with a working ionide install. As an experiment I installed sdk 6 on it and that broke script type checking on it, so it might be dotnet sdk 6 that is breaking script type checking.

The log errors:

```
[19:06:21.468 INF] [LSP] TextDocumentHover Request: {"TextDocument": {"Uri": "file:///c%3A/temp/scriptfail/test2.fsx", "$type": "TextDocumentIdentifier"}, "Position": {"Line": 0, "Character": 17, "DebuggerDisplay": "(0,17)", "$type": "Position"}, "$type": "TextDocumentPositionParams"}
[19:06:21.468 VRB] [Checker] Current Queue Length is 0
[19:06:21.468 INF] [Checker] TryGetRecentCheckResultsForFile - "c:\temp\scriptfail\test2.fsx"
[19:06:21.468 INF] [LSP] PositionHandler - Cached typecheck results not yet available for c:\temp\scriptfail\test2.fsx
[Error - 7:06:21 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

I also tried this global.json but it did not fix type checking:
```
{
    "sdk": {
      "version": "5.0.400",
      "rollForward": "latestMajor"
    }
  }
```

### Steps to reproduce

```
mkdir scriptfail
cd scriptfail
dotnet new classlib -lang f#
'let fruit = "apple"' > test.fsx
code .
```

![scriptfail](https://user-images.githubusercontent.com/5226115/133311270-224765bc-4c1e-4b56-b054-df290a6d1002.gif)

## Machine info
 Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
 - .NET SDK version: 6.0.100-preview.7.21379.14
 - Ionide version: 5.7.3, 5.7.1

**Comment by baronfel** [comment]
It currently does not, that's correct. The work in [this MR](https://github.com/fsharp/FsAutoComplete/pull/825) should resolve this, and is part of our longer work towards full .Net 6 support overall.

**Comment by nhirschey** [comment]
Got it, thank you for the prompt reply and all your work on this project.

**Comment by baronfel** [comment]
Thank you for reporting this! It's one of the things that's been stuck in the back of my mind since I made that MR.

**Comment by baronfel** [comment]
I pinned this and renamed it to be more declarative so that others would have better visibility into it.

**Comment by baronfel** [comment]
This should be resolved in Ionide 5.9.0, which release just a few moments ago.

**Comment by dsyme** [comment]
Yay!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by nhirschey** [comment]
My sincere thanks for all the hard work involved to make this happen!
