### ISSUE TITLE
F# Script File: No Errors Displayed in Code, No Pipe Lens

### ISSUE THREAD

**Issue by bytesource** [ionide/ionide-vscode-fsharp#1585]
### Describe the bug**
I've been working on a script file, and Ionide worked perfectly, until suddenly the following happened:

- Errors in the code weren't displayed anymore (no red squiggles). Only running the code revealed any errors. 
- Pipe lenses stopped working (I didn't change the settings).

I have tried the following:
- Clear cache: `F#: Clear cache` resulted in an error and therefore didn't work
- ![grafik](https://user-images.githubusercontent.com/610307/133549770-f8d185ed-0026-4371-8017-ffca2c9a673c.png)
- Delete `obj/` folder and reload VS Code
- Run command: `dotnet restore --no-cache` and reload VS Code
- Get the logs with `F#: Ionide logs` (but the log file was empty)

None of the above solved the problem or provided any more insights.

I got the red squiggles working after enabling "extensive logging" in the settings and reloading VS Code. However, after another reload, again, no errors were displayed in the code (and the pipe lenses hadn't re-appeared anyway).

The issue seems to be related to this script file, because when I opened another project, Ionide just worked as expected.

Is there anything else I can do?

### Link to sample reproduction
This is the code of the `fsx` file that shows both issues described above:
https://gist.github.com/bytesource/b187945430aa7ee2b9be605b2b4667bf

### Expected behavior
Errors should be displayed in the code, and pipe lenses should work. 

### Screenshots

Here is a screenshot showing both errors.

![grafik](https://user-images.githubusercontent.com/610307/133548612-7eb1adb1-64e5-47b7-a88c-88dbc5202cb3.png)

## Machine info
 - OS: Windows 11
 - .NET SDK version: 5
 - Ionide version: 5.7.3 (can't remember when Ionide was updated, though)

**Comment by bytesource** [comment]
Update:

I uninstalled `ionide-fsharp` and then installed the plugin again. At this point (_without_ reloading VS Code), all errors appeared in the script (but not the pipe lens annotations). 

However, after _reloading_ VS Code, once again all errors were gone, and the code again looked as shown in the screenshot above.

**Comment by bytesource** [comment]
Update:

I opened a `fsx` file (`File -> Open File...`) from _another_ project in the same VS Code window, and Ionide is working perfectly on this file. 

This is a rather curious situation, where I now have two files open side-by-side in different tabs, one of which is working with Ionide (the one opened from another project) while the other one (the original file of this project) is not.

**Comment by bytesource** [comment]
Update:

Based on my previous observation, I opened _**another**_ project and imported the file that was not working with Ionide into it (`File -> Open File...`). 

To my surprise, Ionide was suddenly working fine with this file (although the pipe lens annotation are still not showing):

![image](https://user-images.githubusercontent.com/610307/133574165-b5c72190-4741-4631-83e6-d8f39768bbce.png)

I'm really not sure what to make out of this. This must be the least-reproducible issue ever. 

But maybe you have encountered a similar issue before that might give me an idea of what might be going on here.

**Comment by bytesource** [comment]
Update:

After rebooting Windows, Ionide shows type errors in the code ("red squiggles"), but haven't found a way to get the pipeline lines to work again.

**Comment by bytesource** [comment]
The pipeline lenses are back!

I'll tell you all the details in a second, but first this is what I think happened regarding the overall problem:

The two issues described in my first post seemed to be unrelated. At least different actions made them go away:

**Issue 1**: No type errors displayed in code
Solution: Reboot Windows

**Issue 2**: Missing pipeline type hints
As for the second issue, the pipeline lenses magically re-appeared the moment I removed the last type error in the script.

For example, this file contains type errors and doesn't show any pipeline lenses: https://gist.github.com/bytesource/cbac1c216a19e8ca6ef480b07f6602ba
Both `getRawProducs` (line 199) and `getRawProducts2` (line 222) have type errors.

On the other hand, after correcting the type errors, the pipeline lenses where displayed again (literally on the last keystroke that fixed the remaining type error): https://gist.github.com/bytesource/223226d53bf2bcb9ed7d2fd272f6f9d8

I have no idea how this is possible, but from my observation, it seems the actual code of a `fsx` file is able to mess with the display of pipeline type hints. 

Have you come across a similar issue before?

**Comment by Krzysztof-Cieslak** [comment]
Can you please try on the latest version of Ionide? Script files are working fine for me.

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce this, script files are working fine for me (and I belive we had some fixes in this area on FSAC side)
