### ISSUE TITLE
Is it possible to add a bit better IntelliSense for type providers in VS Code?

### ISSUE THREAD

**Issue by fuszenecker** [ionide/ionide-vscode-fsharp#159]
When I'm using a type provider, i.e. HTML Type Provider, I cannot see the table names in Visual Studio Code.

```
#reference "packages/FSharp.Data/lib/net40/FSharp.Data.dll"
open FSharp.Data

type HupTrackerType = HtmlProvider<"""http://hup.hu/tracker""">
let tracker = HupTrackerType()
```

When I'm typing `tracker.Tables.`, I cannot see the name of the table in the list, even though with Visual Studio 2015 it works perfectly.

After having copy-pasted the table name from VS2015 to the VS Code, the code works further perfectly.

```
tracker.Tables.``Friss tartalom``.Rows
|> Seq.map (fun row -> row.Tartalom)
|> Seq.distinct
|> Seq.iter (printfn "TypeProviders.HTML1: %A")
```

Btw. Ionide-FSharp is one of my facourite plugins in VS Code :-)

**Comment by Krzysztof-Cieslak** [comment]
Hmm... I can't reproduce this behavior: 
![image](https://cloud.githubusercontent.com/assets/5427083/18815243/b4a8ff44-832a-11e6-80c5-474c0a678577.png)

Can you enable logging (as described in https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting) and check if there are any errors in there?

**Comment by fuszenecker** [comment]
Thank you very much, Krzysztof, with the new Ionide-FSharp plugin (2.6.x) it works perfectly.
Now, we can close the issue.

**Comment by fuszenecker** [comment]
Thank you very much for this brilliant plugin. It is my favorite :-)
