### ISSUE TITLE
Backtick methods / types are missing the backticks after selecting from intellisense

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#16]
I'm testing here the Azure Type Provider but I imagine that this problem isn't just TPs. If you select e.g. a property from the intellisense pop-up, it is entered into the code editor but without backticks. You have to manually enter them yourself, otherwise the code does not compile.

In the example below, I'm trying to select the ```SampleFiles/``` property.

![1](https://cloud.githubusercontent.com/assets/1781813/11500089/25d9cef0-982b-11e5-92bc-3b41683036d9.png)

You'll see it is entered in the code editor without backticks. When I hit dot, I get incorrect suggestions.

![2](https://cloud.githubusercontent.com/assets/1781813/11500069/0a2d9cb8-982b-11e5-8d4d-0fe41d53ec9c.png)

If I manually enter backticks around the symbol, it all works again.

![3](https://cloud.githubusercontent.com/assets/1781813/11500070/0b560648-982b-11e5-8129-388efe004cdc.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.0.6`
