### ISSUE TITLE
Missing Error Highlighting in Erroneous Code

### ISSUE THREAD

**Issue by sebastto** [ionide/ionide-vscode-fsharp#1602]
### Describe the bug**

The code in the attached gist is erroneous , yet Ionide-fsharp is unable to highlight the errors before running the code.
There is both an issue in the pattern match expression and when calling the custom option map function with a regular string.

### Steps to reproduce

1. Open an F# interactive script in VSCode
2. Copy code from gist
3. Select and run code in F# Interactive mode (alt + enter)

### Link to sample reproduction

https://gist.github.com/sebastto/dc11b5cffc90625cccdd054017ab47f2

### Expected behaviour

Expected the errors to be highlighted before running the code.
When writing the same script in Visual Studio, the error is detected before running,
see attached screenshot.

### Screenshots

Screenshot from Visual Studio
![image](https://user-images.githubusercontent.com/7560693/136655585-2c2ae005-5dd5-4fd1-ba18-15f157c61775.png)

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.401  
 - Ionide version: 5.7.3

**Comment by isaacabraham** [comment]
Also seeing this in latest Ionide with .NET 6 for even trivial scripts. The following invalid F# shows no errors in the code editor.

```fsharp
let x = 123jfdsj
```

.NET 6.0 on Windows 11, v5.10.2.

**Comment by Krzysztof-Cieslak** [comment]
Everything seems to be working fine for me: 

<img width="670" alt="image" src="https://user-images.githubusercontent.com/5427083/178495917-2c5d1cc8-699d-4e77-a520-2dc77aabc003.png">
