### ISSUE TITLE
Return values not displayed in info-box on hover over method

### ISSUE THREAD

**Issue by pkese** [ionide/ionide-vscode-fsharp#1603]
### Describe the bug**

This is what Ionide displays when hovering over HashSet.Add method
![image](https://user-images.githubusercontent.com/278492/137390761-a4005cd8-63b6-4883-a2f2-3ab872800179.png)

This is the actual documentation of function:
![image](https://user-images.githubusercontent.com/278492/137390912-f0e27460-4217-48f2-b749-5759971b3f05.png)

Notice how `true` and `false` are not displayed in Ionide's Return section...

**Documentation says:**  
  `true` if the element is added to the HashSet<T> object; `false` if the element is already present.  
**Ionide says:**  
  if the element is added to the HashSet<T> object; if the element is already present.  

### Steps to reproduce
Hover over a method.

**Comment by MangelMaxime** [comment]
Indeed, it seems like I didn't saw the `langword` or this is something new.

Adding support for it, would consist on doing something like that:

*Code not tested*

```fs
    let private see =
        let getCRef (attributes : Map<string, string>) = Map.tryFind "cref" attributes
        let getLangword (attributes : Map<string, string>) = Map.tryFind "langword" attributes
        {
            TagName = "see"
            Formatter =
                function
                | VoidElement attributes ->
                    match getCRef attributes, getLangword attributes with
                    | Some cref, Some langword ->
                        // TODO: Generate a link executing a command to redirect to the cref link
                        "`" + langword + "`"
                        |> Some

                    | Some cref, None ->
                        // TODO: Generate a link executing a command to redirect to the cref link
                        "`" + extractMemberText cref + "`"
                        |> Some

                    | None, Some langword ->
                        "`" + langword + "`"
                        |> Some

                    // Unkown syntax?
                    | None, None ->
                        None

                | NonVoidElement (innerText, attributes) ->
                    if String.IsNullOrWhiteSpace innerText then
                        match getCRef attributes with
                        | Some cref ->
                            // TODO: Add config to generates command
                            "`" + extractMemberText cref + "`"
                            |> Some

                        | None ->
                            None
                    else
                        "`" + innerText + "`"
                        |> Some
        }
        |> applyFormatter
```

**Comment by baronfel** [comment]
This was fun, because it surfaced an issue with the `member text` portion of processing, where member names can have backticks. you see this primarily with generic types, like ``System.Collections.Generic.HashSet`1``.

Anyway, this was easy enough to get fixed, and it's orthogonal to the big changes coming for .Net 6, so maybe we can get it released earlier.
![image](https://user-images.githubusercontent.com/573979/137534917-67335dda-68cc-42b4-94a5-3e3eeb446b56.png)

**Comment by MangelMaxime** [comment]
Yes, I never took the time to strip the backtick from the name

https://github.com/fsharp/FsAutoComplete/issues/775
