### ISSUE TITLE
Fails to find a compatible version of .NET when restricted by global.json

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1615]
Hello

### Describe the bug**

I have this `global.json` file:

```json
{
    "sdk": {
        "version": "5.0.202",
        "rollForward": "minor"
    }
}
```

and those SDKs installed:

```
3.1.415 [/usr/share/dotnet/sdk]
5.0.403 [/usr/share/dotnet/sdk]
6.0.100 [/usr/share/dotnet/sdk]
```

When Ionide tries to start it fails to find a compatible version of dotnet.

```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [5.0.202] from [/home/maximemangel/Documents/Workspaces/Github/MangelMaxime/fable-quest/global.json] was not found.
      Install the [5.0.202] .NET SDK or update [/home/maximemangel/Documents/Workspaces/Github/MangelMaxime/fable-quest/global.json] with an installed .NET SDK:
[Error - 15:03:24] Connection to server got closed. Server will not be restarted.
```

However if I run `dotnet --list` it succeed to show `5.0.403` and `dotnet build` succeeds too.

If I change the global.json to:

```fs
{
    "sdk": {
        "version": "5.0.*"
    }
}
```

Then Ionide works but I think this is because `dotnet` doesn't constraint the version at all. If I run `dotnet --version` it returns `6.0.100` which I don't think should match the requested version.

## Machine info
 - OS: Linux
 - .NET SDK version: [e.g. 5.0.100]
 - Ionide version: 5.9.0

**Comment by Krzysztof-Cieslak** [comment]
1. `"version": "5.0.*"` syntax is not supported by .NET SDK
2. And to the original issue... it seems like it is some kind of issue with detecting your `dotnet` installation or something like that... could you try to set `FSharp.dotnetRoot` setting to your dotnet directory.

**Comment by MangelMaxime** [comment]
> 1. `"version": "5.0.*"` syntax is not supported by .NET SDK

You are right indeed.

Hum, I cannot reproduce my problem with Ionide 5.9.1 so perhaps this has been fixed with this version of Ionide.

I will re-open, if needed.
