### ISSUE TITLE
Missing reference when loading a net5.0 project

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1618]
### Describe the bug

Loading a project setup for `net5.0` framework report an error about missing references.

> You must add a reference to assembly 'netstandard'.

### Steps to reproduce

1. Create a new F# project `dotnet new classlib -lang f#`
2. Configure the `TargetFramework` to be `<TargetFramework>net5.0</TargetFramework>`
3. See that Ionide reports an error

![image](https://user-images.githubusercontent.com/4760796/140944477-47e799cf-779d-46a7-afb4-dc0d94e80e23.png)

Textual code:

**Library.fs**

```fs
namespace testIonide

module Say =
    let hello name =
        printfn "Hello %s" name
```

**MyProject.fsproj**

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>
```

If you change `TargetFramework` to `net6.0` or `netstandard2.0` it works.

### Expected behaviour

Ionide should not report an error

## Machine info
 - OS: Windows/Mac/Linux
 - .NET SDK version:
    - 3.1.415 [/usr/share/dotnet/sdk]
    - 5.0.403 [/usr/share/dotnet/sdk]
    - 6.0.100 [/usr/share/dotnet/sdk]
 - Ionide version: 5.9.0

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce this one.
