### ISSUE TITLE
__SOURCE_DIRECTORY__ and __SOURCE_FILE__ aren't evaluating properly in MacOS

### ISSUE THREAD

**Issue by smoothdeveloper** [ionide/ionide-vscode-fsharp#162]
```fsharp
printfn "%s" __SOURCE_DIRECTORY__
printfn "%s" __SOURCE_FILE__
```

Evaluated from VSCode / ionide, this will print:

```
/Users/myuser
stdin
```

although the file is not in that folder.

this work fine if I invoke the same script with `fsharpi` giving the actual directory so I think it is either ionide or FCS or FSAC which handle that wrongly in some way.

Similarly, I can't seem to `#load` scripts due to same issue, if I fix the script to load relatively from `/Users/myuser` then it will find the files.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.5.1`

**Comment by smoothdeveloper** [comment]
Thanks, I'll give it a try soon when I can get hand on that same computer!

**Comment by smoothdeveloper** [comment]
Works!
