### ISSUE TITLE
Changing types in a referenced project does not get updated until a restart

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1621]
### Describe the bug
If you have an F# project referenced by another one, changes in the first are not cascaded to the second. You need to do a soft-reset of VSCode to get it to notice the changes.

### Steps to reproduce
I reproduced it by create a new SAFE Stack app (dotnet new --install safe --> dotnet new safe) and then making a change to the ITodosApi file in Shared.fs. The changes were not cascaded in either the client or server projects.

### Expected behaviour
The changes should be reflected immediately.

## Machine info
 - OS: Windows
 - .NET SDK version: 6
 - Ionide version: 5.9.0

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `5.10`
