### ISSUE TITLE
Booleans are not tokenized as such and thus not being colorized via the textmate scopes

### ISSUE THREAD

**Issue by JustinGrote** [ionide/ionide-vscode-fsharp#1623]
![image](https://user-images.githubusercontent.com/15258962/141023696-8dbc2356-c836-405d-8cab-5014acb4d9ec.png)

**Comment by MangelMaxime** [comment]
Hello,
good catch.

A fix is ready in https://github.com/ionide/ionide-fsgrammar/pull/159

**Comment by JustinGrote** [comment]
@MangelMaxime thank you!
