### ISSUE TITLE
Exported logs are empty

### ISSUE THREAD

**Issue by kentcb** [ionide/ionide-vscode-fsharp#1627]
### Describe the bug
I'm trying to understand why my Ionide tooling has stopped working (probably related to VS upgrades). However, when I export logs, the log file is empty.

### Steps to reproduce
1. Open my project
2. Wait for it to load and show hints etc
3. Export logs via `F#: Get Ionide Logs`
4. Open the log file (it's empty)

### Expected behaviour
The log should be helpful in diagnosing what is going on.

## Machine info
 - OS: Windows 10
 - .NET SDK version: I can't know because the logs don't tell me. It's either 5.0.209, 5.0.403, or 6.0.100
 - Ionide version: 5.9.0

**Comment by HerrNiklasRaab** [comment]
Can confirm this, using macOS and .net 6

**Comment by Krzysztof-Cieslak** [comment]
Duplicate of #1617

**Comment by kentcb** [comment]
@Krzysztof-Cieslak I don't think those issues are the same as the one I reported. In my case, the export works, but the exported file is empty.
