### ISSUE TITLE
Autocompletes doesn't pop up, and if it does it hangs after typing a few characters

### ISSUE THREAD

**Issue by HerrNiklasRaab** [ionide/ionide-vscode-fsharp#1630]
In the video I first show that "Analytics" is a type that exists.
I then show that the autocomplete doesn't pop up.
I then show that the autocomplete hangs after typing a few characters.

What I also noticed is that the autocomplete only shows the "Loading..."  label after hitting the shortcut a few times (00:12).

Saw that there are some problems with .NET 6 so, thought that i might be important to know for you guys, that I am using .NET 6

https://user-images.githubusercontent.com/28401593/141700024-0b585fb6-c2e0-4d08-9ca8-3c64f0895b47.mov

**Comment by faldor20** [comment]
This appears to be the same issue I posted about some time ago https://github.com/fsharp/FsAutoComplete/issues/805

**Comment by faldor20** [comment]
Copying from the referenced issue in FSAC
@HerrNiklasRaab 
If this is still a problem for you I have just updated the alternative vscode extension fsharp-langauge-server to support dotnet 6.0 and the latest f# stuff.
It has a few less features (Though I have been working on that) but the completion does work for me.
https://marketplace.visualstudio.com/items?itemName=faldor20.fsharp-language-server-updated

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `5.10`
