### ISSUE TITLE
Seeing errors from .fsx file even after renaming

### ISSUE THREAD

**Issue by HerrNiklasRaab** [ionide/ionide-vscode-fsharp#1632]
If I rename .fsx file with errors to a .fs file, I still see the errors of the .fsx file, which doesn't exist anymore.

![image](https://user-images.githubusercontent.com/28401593/142283173-e2be8ad3-0262-4931-a81f-232a8a2815ec.png)

**Comment by Krzysztof-Cieslak** [comment]
TODO: investigate didRenameFiles notification
