### ISSUE TITLE
Intellisense only work after typing something

### ISSUE THREAD

**Issue by Fubuchi** [ionide/ionide-vscode-fsharp#1633]
### Describe the bug
When I open a project intellisense doesn't work right away, it only works after I type something.

### Steps to reproduce

1. Open a F# project
2. intellisense doesn't work
3. Try to type something
4. intellisense start to work

### Screenshots
![bug](https://user-images.githubusercontent.com/42483897/142428929-dccc01cb-e78a-4606-b41b-7fc93c5efd75.gif)

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.403
 - Ionide version: 5.9.1

**Comment by baronfel** [comment]
At first glance this is a timing issue between when the file is opened and type checking is queued, and when the request for highlighting, etc, is sent. We should make some kind of top-level 'wait for at least one type check result for this file' method that we could use in highlighting, references, etc, to ensure that this doesn't happen.

**Comment by witoldsz** [comment]
I think it _might_ be somehow connected to #1622? Not sure though.

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce this anymore - startup behaviour seems to be correct.
![startup](https://user-images.githubusercontent.com/5427083/179623733-c9884300-2daf-4845-a47c-3c2f0b082497.gif)
