### ISSUE TITLE
Improve UX regarding adding files in new (nonexistent) folders

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1640]
### Discussed in https://github.com/ionide/ionide-vscode-fsharp/discussions/1639

<div type='discussions-op-text'>

<sup>Originally posted by **inputusernamehere** November 20, 2021</sup>
Thank you for your work on Ionide! I have a minor improvement suggestion:

So right now it's possible to create a new folder in the regular file explorer, then switch to the F#/Ionide view, and create a new file in that folder. Let's say I call the folder `new_folder`, and input `new_folder/new_file.fs` when I create a new file. It will work as expected.

However if I do not create the folder my self first, I get hit with this error:

Error running command fsharp.explorer.addFile: Could not find a part of the path 'd:\code\ionide-folder-test\new_folder\new_file.fs'.. This is likely caused by the extension that contributes fsharp.explorer.addFile.

I think it would be smoother if Ionide just created the new folder for me.</div>

This is a good first issue. The code implementing this is [over in fsautocomplete](https://github.com/fsharp/FsAutoComplete/blob/0ae2225632792463d00444e2bd692d8d0fcb67d1/src/FsAutoComplete.Core/Commands.fs#L646-L697), specifically the three [File.Open](https://github.com/fsharp/FsAutoComplete/blob/0ae2225632792463d00444e2bd692d8d0fcb67d1/src/FsAutoComplete.Core/Commands.fs#L655-L656) calls on the three highlighted methods. I think there should be a helper that parses the passed in file name and creates any necessary directories that are included in the file name.

@inputusernamehere - would you be interested in submitting a PR to fix these? I'd be happy to walk you through the process.

**Comment by inputusernamehere** [comment]
I appreciate you investigating this issue and outlining what needs to be done. I'll be pretty busy for the forseeable future so if someone else wants to give it a go you don't have to wait for me!

**Comment by jcmrva** [comment]
I've made a little progress on this.

**Comment by kevinbarabash** [comment]
This seems to be work for me.  I added a new file from the solution explore named `foo/bar/baz.fs` and it recursively created the directories that were needed as well as the file.

**Comment by baronfel** [comment]
Oh great! I'll close this one, then.
