### ISSUE TITLE
Line Lens 'never' doesn't get rid of Line lens

### ISSUE THREAD

**Issue by Degubi** [ionide/ionide-vscode-fsharp#1648]
### Describe the bug
When the Line Lens setting gets set to 'never' the type hints don't disappear on functions.
File extension is '.fsx'

### Expected behaviour
When set to 'never' the type hint disappears completely.

### Screenshots
The setting:
![image](https://user-images.githubusercontent.com/13366932/143915495-dc75c904-2935-45cf-ac4c-8c4d355d7b4b.png)
When set to 'never'
![image](https://user-images.githubusercontent.com/13366932/143914951-d60dd60e-7ec2-49b3-a5bd-04f229882b82.png)
When set to 'replaceCodeLens'
![image](https://user-images.githubusercontent.com/13366932/143915019-151075ae-d8bd-4f8e-af62-77d1f63c6137.png)
When set to 'always'
![image](https://user-images.githubusercontent.com/13366932/143915159-f841b429-a833-44e5-b51f-7c6821a18423.png)

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.301
 - Ionide version: 5.10.1

**Comment by cartermp** [comment]
@Degubi You need to disable codelenses in VSCode if you don't want any type hints. This setting does get rid of the line lenses, but it doesn't get rid of code lenses.

**Comment by Degubi** [comment]
Disabling Editor:Code Lens helped, thank you @cartermp !

**Comment by cartermp** [comment]
One thing that might be worth looking into (I might just snipe myself into doing this) is having a separate setting for disabling type hints in code lenses independently of the global code lenses setting. Happy this worked for you though!
