### ISSUE TITLE
Feature: Autocomplete - sort by most invoked

### ISSUE THREAD

**Issue by kontomondo** [ionide/ionide-vscode-fsharp#165]
This would apply when auto-completing on member variables of a class/static functions of a module.

Not sure if this would be possible as it would require keeping a sort of an index either on the VSCode side or the FsAutcompleteService side. 

The idea is that the most used methods show at the top, the more often a certain method is invoked, the higher in the list it is.

Say if you do List.[Invoke Autocomplete] and you've mostly used .map & .filter, they would show at the top, followed by the rest of the functions.

**Comment by Krzysztof-Cieslak** [comment]
We don't plan to implement this.
