### ISSUE TITLE
Formatter breaks Map indexing

### ISSUE THREAD

**Issue by nicholas-p1** [ionide/ionide-vscode-fsharp#1655]
### Describe the bug

The formatter adds a space between the Map variable name and the index square brackets.

### Screenshots

Before format (code works):
![image](https://user-images.githubusercontent.com/53228351/149392919-7180eb90-910c-428d-88b0-ae4cb7fb5a8a.png)

After format (code no longer works):
![image](https://user-images.githubusercontent.com/53228351/149392997-caa28881-a2be-4fcd-ba30-ffa37ca21211.png)

## Machine info

 - OS: Windows
 - .NET SDK version: 6.0.101
 - Ionide version: v5.10.2

**Comment by baronfel** [comment]
what version of fantomas is being invoked here? it should be in your `.config/dotnet-tools.json` file.

**Comment by baronfel** [comment]
ah ok. can you try updating your global version to a more recent fantomas? the latest is `4.6.0-beta-001` and should support this syntax.
