### ISSUE TITLE
Suggestion for "Use substraction instead of negation" produces incorrect result

### ISSUE THREAD

**Issue by jasiozet** [ionide/ionide-vscode-fsharp#1657]
When using suggestion "Use substraction instead of negation" the code that gets generated is incorrect.

### Steps to reproduce
In any F# file try this sample code:
```
let getListWithoutFirstAndLastElement list =
    let l = List.length list
    list[1 .. l -1]
```
The Ionide correctly suggests to "Use substraction instead of negation"
But the result is this:
```
let getListWithoutFirstAndLastElement list =
    let l = List.length list
    list[1 .. l -- ]
```
### Expected behaviour
```
let getListWithoutFirstAndLastElement list =
    let l = List.length list
    list[1 .. l - 1]
```
### Screenshots
![image](https://user-images.githubusercontent.com/18668118/149953121-33d6a253-f865-43a9-a0b5-8ca4d7a6bd69.png)
![image](https://user-images.githubusercontent.com/18668118/149953207-52ebffaf-62ca-4154-b5ec-eea607d4f058.png)

## Machine info
 - OS: Mac
 - .NET SDK version: 6.0.100
 - Ionide version: v5.10.2

### Additional context
Visual Studio 2022 does this correctly. Rider doesn't know about the suggestion and suggests something else instead.

**Comment by baronfel** [comment]
Looks like we might have an off by one error in the logic for this codefix, would you be interested in trying to fix it? The line should be around [here](https://github.com/fsharp/FsAutoComplete/blob/main/src/FsAutoComplete/CodeFixes/NegationToSubtraction.fs#L21) in the FsAutoComplete project.

**Comment by jasiozet** [comment]
I would be honored to try :)

**Comment by jasiozet** [comment]
Okay I have the local fix, but I've never setup any draft PR could you help me out with it?

**Comment by jasiozet** [comment]
I hope I did it correctly :)

**Comment by baronfel** [comment]
It looks great!
