### ISSUE TITLE
Feature: "Override" autocomplete

### ISSUE THREAD

**Issue by kontomondo** [ionide/ionide-vscode-fsharp#166]
As far as I can tell right now there's no way to override the current value by an autocomplete invocation, say in the following example:

``` fsharp
let trainingPath = @"..."
let trainingAnotherPath = @"..."
let result = id training[Cursor Here]Path
```

if I invoke autocomplete at that location of the cursor, and I want to select `trainingAnotherPath` and override the `trainingPath` I can't do it (instead you get `trainingAnotherPathPath`, normally this is done in IDEs by having Enter & Space insert the selection, and `Tab` override the existing word with the selection.

If you believe that this could be a useful addition I'm happy to take on this.

**Comment by Krzysztof-Cieslak** [comment]
Not currently possible with VSCode API
