### ISSUE TITLE
Virus detection?

### ISSUE THREAD

**Issue by dam0** [ionide/ionide-vscode-fsharp#1661]
### Describe the bug

Bitdefender alerted the following on installation - 
```
"An infected file attempted to run on your device.
Threat name: Trojan.GenericKD.48133082
Path: /Users/xxx/.vscode/extensions/ionide.ionide-fsharp-5.10.2/bin/fsautocomplete.backgroundservices.exe
We deleted the file to prevent malicious commands from being executed on your device."
```
prob. an overzealous antivirus? funny about the .exe on the Mac install though..

## Machine info
 - OS: Mac M1
 - .NET SDK version: 6.0.1
 - Ionide version: 5.10.2 via https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp

**Comment by cartermp** [comment]
compilers (which this ultimately involves) tend to make antivirus programs unhappy. Lots of mucking around with temp files and whatnot. So that's likely the reason.

As for `.exe`, this is just a .NET thing. `.exe` files have never actually been a Windows-only thing.
