### ISSUE TITLE
Cannot read property 'subscriptions' of undefined

### ISSUE THREAD

**Issue by halcwb** [ionide/ionide-vscode-fsharp#1667]
- Issue Type: `Bug`
- Extension Name: `Ionide-fsharp`
- Extension Version: `5.11.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.64.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 53,
		"activateCallTime": 1,
		"activateResolvedTime": 12,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Ionide.Ionide-fsharp",
				"_lower": "ionide.ionide-fsharp"
			},
			"activationEvent": "onLanguage:fsharp"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'subscriptions' of undefined"
		}
	],
	"runningLocation": 1
}
```

dotnet --info:

.NET SDK (reflecting any global.json):
 Version:   5.0.402
 Commit:    e9d3381880

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.402/

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

.NET SDKs installed:
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.402 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.1.700 [/usr/local/share/dotnet/sdk]
  2.2.301 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100-preview3-014645 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]
  3.1.401 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]
  3.1.411 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  5.0.401 [/usr/local/share/dotnet/sdk]
  5.0.402 [/usr/local/share/dotnet/sdk]

I have checked the C# extension, but that is running without errors. 

The result of the above error is no F# language support.

Using dotnet build, there is no problem in the build, restarting VS results in:

- Issue Type: `Bug`
- Extension Name: `Ionide-fsharp`
- Extension Version: `5.11.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.64.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 82,
		"activateCallTime": 0,
		"activateResolvedTime": 2843,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Ionide.Ionide-fsharp",
				"_lower": "ionide.ionide-fsharp"
			},
			"activationEvent": "workspaceContains:**/*.fs,**/*.fsx,**/*.fsproj,**/*.sln"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'content' of null"
		}
	],
	"runningLocation": 1
}
```

**Comment by Krzysztof-Cieslak** [comment]
This is fairly old issue and I can't reproduce at the latest Ionide. Closing.
