### ISSUE TITLE
Pipeline hints not appearing in 5.12.0

### ISSUE THREAD

**Issue by aaronmaslen** [ionide/ionide-vscode-fsharp#1673]
### Problem

Pipeline hints no longer appear in 5.12.0. Downgrading to 5.11.2 seems to fix it.

### Steps to reproduce

Update to Ionide 5.12.0

### Expected behaviour

Pipeline hints should appear if `"FSharp.pipelineHints.enabled": true` is set (the default)

### Screenshots

5.11.2:
![image](https://user-images.githubusercontent.com/5466817/160043292-b479b1f3-23c3-43b5-a891-a86b5e23603f.png)

5.12:
![image](https://user-images.githubusercontent.com/5466817/160043362-9b4428fc-545b-4ab1-a9cf-0c4efb450a32.png)

### Machine info

* Operating system: **Windows 11**
* VSCode: **1.65.2**
* Ionide: **5.12.0**
* Runtime: **.NET Core**
* Dotnet version: **6.0.300-preview.22154.4**

**Comment by baronfel** [comment]
This is a result of data changes in FSAC, we'll need to fix it there. I'll take a look at that and get the area under test.
