### ISSUE TITLE
Feature: Type-aware snippets for collections

### ISSUE THREAD

**Issue by kontomondo** [ionide/ionide-vscode-fsharp#169]
Would be nice if you could do:

``` fsharp
myArray |> map[Press Tab Here]
```

And this would expand to Array.map if myArray is an array, List.map if it's a list, Seq.map if it's a sequence, etc., The same for other functions in collections, as well as things like toArray, toSeq, toList available to all of them.

**Comment by Krzysztof-Cieslak** [comment]
We don't plan to implement this.
