### ISSUE TITLE
Renaming symbols is broken in v6.0.0

### ISSUE THREAD

**Issue by leovalencia10** [ionide/ionide-vscode-fsharp#1690]
When I try to rename a symbol sometimes it works and sometimes the new name goes into the wrong place. This only started to happen after the update to v6.0.0

(a simple code example):

```fsharp
//
// Perform the actual command
//
let goGetUrl (url: string) =
    let query = goGetUrlAsync url
    query.Wait()
    query.Result

let fromCSV csv =
    CsvFile.Parse(csv, hasHeaders = false, ignoreErrors = true)
```

If I try to renamed the fromCSV function to something like fromCSVBad I get this:

```fsharp
//
// Perform the actual command
//
let goGetUrl (url: string) =
    let query = goGetUrlAsync url
    query.Wait()
    fromCSVBadesult

let fromCSV csv =
    CsvFile.Parse(csv, hasHeaders = false, ignoreErrors = true)
```

Notice that the line was inserted on the last line of the previous functions (it looks like query was replaced as well) and that the symbol that I wanted to rename is unchanged.

**Comment by baronfel** [comment]
Yeah, I've seen this off and on for a few versions now - we may have an off by one hiding around.

**Comment by yuuuxt** [comment]
I'm having this issue with 6.0.6 (vscode 1.68.1, win x64, tried reinstalling ionide, tried restarting vscode&PC)
![temp](https://user-images.githubusercontent.com/3153534/174202908-6076ea4e-6122-452d-b371-68f5d40241d9.gif)
