### ISSUE TITLE
Limit max length of inlay hints (when followed by more code)

### ISSUE THREAD

**Issue by piaste** [ionide/ionide-vscode-fsharp#1694]
When working with anonymous records or type providers, it is possible to have implicitly-named types that are extremely long. User code will generally alias them if it needs to refer to them, but the tooling can't autonomously decide to use an alias.

(Type hint tooltip for a TP value:

![image](https://user-images.githubusercontent.com/12280683/164410423-fad5098b-2541-444a-a166-15cbc2053b5b.png)
)

With inlay hints enabled (by default), these can literally push the rest of the line off-screen.

Type providers:

![image](https://user-images.githubusercontent.com/12280683/164410651-e8ab3863-047b-4a79-873c-0d8e081fb468.png)

Anonymous records:

![image](https://user-images.githubusercontent.com/12280683/164411043-f9223798-a50b-41b1-8a94-4ca27a3ae581.png)

Inlay hint should have a reasonable max length set, and longer type names truncated with '...'.

Possible exception: even long hints are IMO pleasant when they aren't hiding extra code:

![image](https://user-images.githubusercontent.com/12280683/164412062-85a14b96-d38d-42eb-88d4-f01e623873c4.png)

So maybe the truncation can be triggered only if there are at least two non-whitespace characters after the hint? Or at least one character that isn't a `=`, `;`, or a closing brace/bracket/parenthesis?

**Comment by baronfel** [comment]
As of 6.0.2, InlayHints are now truncated to 30 characters, based on consulting similar code in the TypeScript and Rust language servers.
