### ISSUE TITLE
If dotnetRoot is set but dotnet program doesn't exist at that location no error is displayed to the user

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1709]
Hello,

it happened that I had `FSharp.dotnetRoot` set to an invalid location and was experiencing a silent error from Ionide.

### Steps to reproduce

1. Set `FSharp.dotnetRoot` to `fake_path_to_dotnet`
2. Open an directory containing an F# project
3. See that Ionide doesn't start and doesn't report any error

Additionally, you can see a log from Ionide:

`[Extension Host] DOTNET PATH: fake_path_to_dotnet\dotnet.exe`

I can have a look at how to improve `dotnet` program existence but I am not sure where or how we want to do it.

Do we want to check for the program existence here:

https://github.com/ionide/ionide-vscode-fsharp/blob/6993276a154c764499f5d56adbf4050baace77d7/src/Core/LanguageService.fs#L801-L809

I don't think we can do it here the Environment file because otherwise it will just try to find `dotnet` anywhere in the system:

https://github.com/ionide/ionide-vscode-fsharp/blob/6993276a154c764499f5d56adbf4050baace77d7/src/Core/Environment.fs#L50-L57

```fs
let dotnet =
    Configuration.tryGet "FSharp.dotnetRoot"
    |> Option.map (fun root ->
        promise {
            let dotnetPath = root </> (if isWin then "dotnet.exe" else "dotnet")

            if exist dotnetPath then // Pseudo code
                return Some dotnetPath
            else 
                return None
        }
    )
    // Because we return none if the dotnetPath doesn't exist, we will default to `tryGetTool "dotnet"` 
    // Which is probably not what the user want if he setted `FSharp.dotnetRoot` setting
    |> Option.defaultWith (fun () -> tryGetTool "dotnet")
```

## Machine info
 - OS: Windows
 - .NET SDK version: 

```
4.1.418 [C:\Program Files\dotnet\sdk]
5.0.407 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.104 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
```

 - Ionide version: 6.0.3

**Comment by baronfel** [comment]
I think you're right: instead of `Option.defaultWith` we should do something more like

```fsharp

/// check the FSharp.dotnetToot setting and attempt to find dotnet(.exe) at that path either directly as specified or with the `dotnet` binary appended, 
/// if the config is not set the Result.Ok None else Result.Ok Some path.
/// if not found then show an error dialog to the user explaining what happened and return Result.Error
let tryResolveFromConfig () : Result<string option, string> = ...

let tryResolveFromPath() = tryGetTool "dotnet"

let dotnet = 
  match tryResolveFromConfig () with
  | Ok None -> tryResolveFromPath()
  | Ok Some path -> Some path
  | Error -> // bail out?

```

or something like that.

**Comment by MangelMaxime** [comment]
Perhaps, we could make it easier to read by using a custom DU?

```fs
type DotnetConfigResult =
    | FoundFromDotnetRoot of string
    | NotFoundFromDotnetRoot
    | FoundFromPath of string
    | NotFoundFromPath

let dotnet () =
    promise {
        match Configuration.tryGet "FSharp.dotnetRoot" with
        | Some dotnetRoot ->
            let program =
                if isWin then "dotnet.exe" else "dotnet"

            let dotnetFullPath =
                root </> program
            
            if exist dotnetFullPath then
                return FoundFromDotnetRoot dotnetFullPath
            else
                returnNotFoundFromDotnetRoot dotnetFullPath
        | None ->
            match! tryGetTool "dotnet" with
            | Some dotnetFullPath ->
                return FoundFromPath dotnetFullPath

            | None ->
                return NotFoundFromPath
    }
```

I made the distinction between `NotFoundFromPath` and `NotFoundFromDotnetRoot` but if we don't have a different message for each of them we can just have a single `NotFound`.

**Comment by Krzysztof-Cieslak** [comment]
@MangelMaxime, will you send PR with the suggested changes?

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak I still plan to send a PR yes, just not sure of when it will be.

If someone want to do it before I do please just write a message in this issue so we are 2 to work on it.
