### ISSUE TITLE
'Cannot start .NET Core language services because `dotnet` was not found.', followed by 'Not in a F# project (still loading....)'

### ISSUE THREAD

**Issue by d4span** [ionide/ionide-vscode-fsharp#1712]
### Describe the bug
When I open an F# project in WSL 2, the Ionide plugin is not loaded. Instead, I see the following error:         

> Cannot start .NET Core language services because `dotnet` was not found.
> Consider:
> * setting the `FSharp.dotnetRoot` settings key to a directory with a `dotnet` binary,
> * including `dotnet` in your PATH, or
> * installing .NET Core into one of the default locations.

When I set the`FSharp.dotnetRoot` settings key and restart VS Code, I see a second error, `Not in a F# project (still loading....)` in the status bar as soon as I open a *.fs file.

### Steps to reproduce

1. In WSL, create a new F# project in a folder of your choice: `dotnet new classlib -lang F#`
2. Open VS Code in that folder: `code .`
3. When the error `Cannot start .NET Core language services because dotnet was not found.` appears, set the `FSharp.dotnetRoot` settings key and restart VS Code.
4. Now, the second error appears.

### Expected behaviour
The Ionide plugin should load as soon as VS Code opens in an F# project.

## Machine info
* I am using the most recent versions of VS Code and the Ionide plugin.
* WSL 2 on Windows 11 with the following `dotnet` installation:
  ```
  .NET SDK (reflecting any global.json):
   Version:   6.0.300
   Commit:    8473146e7d
  
  Runtime Environment:
   OS Name:     ubuntu
   OS Version:  20.04
   OS Platform: Linux
   RID:         ubuntu.20.04-x64
   Base Path:   /usr/share/dotnet/sdk/6.0.300/
  
  Host (useful for support):
    Version: 6.0.5
    Commit:  70ae3df4a6
  
  .NET SDKs installed:
    6.0.300 [/usr/share/dotnet/sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  ```

**Comment by pkese** [comment]
I had the same problem on normal Ubuntu Linux.

After manually setting `FSharp.dotnetRoot` to `/usr/bin` it started working for me.  
Previously `FSharp.dotnetRoot` was empty.

**Comment by wiredsister** [comment]
Having this problem with

```sh
gina@SurfaceBaby:~$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.301/

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
![image](https://user-images.githubusercontent.com/3818802/180204687-73ac0b45-aa8e-4afa-a4e0-344d0148c32d.png)

and latest VS Code with an FSharp project. I'm probably doing something dumb, but figured I'd ask here.

**Comment by baronfel** [comment]
No, you're right! I somehow lost track of doing and releasing this in an ionide update, but it's in the upcoming MEGA UPDATE that includes the update to vscode-languageclient@8.
