### ISSUE TITLE
toggle inlay with mouse

### ISSUE THREAD

**Issue by djmisterjon** [ionide/ionide-vscode-fsharp#1719]
hi, is it possible to make custom bindkey for toggle inlay ?
i use a macro mouse and i need this feature bind to my mouse.
Or is it possible add a toggle option with the middle mouse button ?

When i need inlay, is because am reading code, and when reading code i only use my mouse.
I would like able to just hold middle button to show inlay.

**Comment by baronfel** [comment]
Unfortunately, I don't believe it's possible. It seems to be a hard-coded limitation of the editor currently: https://github.com/microsoft/vscode/issues/128162#issuecomment-1088497398

**Comment by Krzysztof-Cieslak** [comment]
Closing - we don't control this behaviour.
