### ISSUE TITLE
Can't add file to project

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1725]
### Describe the bug
I have a .NET 6 console add. I can't use the "Add Current File to Project" feature.

### Steps to reproduce
1. Create a new console app
2. Create a new .fs file.
3. Navigate to the file.
4. Choose the aforementioned action.

You get an error as follows:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1781813/173870162-8f3cf67c-e024-49ff-a21d-d009a6ca19ac.png">

### Expected behaviour
The file is added to the project.

## Machine info
 - OS: Windows 11
 - .NET SDK version: 6.0.23
 - Ionide version: 6.0.6

**Comment by baronfel** [comment]
Missing project explorer info (and presumably by extension project info at all due to failures during project cracking/workspace initialization) _would_ lead to this behavior. It would be nice if the we could add a condition like 'projects are loaded' to the commands to hide them until we're initialized.

**Comment by mhays118** [comment]
Just wanted to add that I have the same issue on Mac. 

![image](https://user-images.githubusercontent.com/12106180/180408822-9ea14fa0-5712-4f95-998d-b379654e4866.png)

-----
OS: macOS Monterey 12.4
.NET SDK Version: 6.0.104
Ionide version: v6.0.6

**Comment by isaacabraham** [comment]
@mhays118 is your project explorer also not showing up?

@baronfel if you want me to use a "diagnostics" version of Ionide to get you debug info, just let me know.

**Comment by mhays118** [comment]
@isaacabraham Both the normal project/file explorer in VSCode and the F# Solution Explorer are showing up for me.

**Comment by isaacabraham** [comment]
@mhays118 ok, so this is a separate thing for me - i'll raise a separate issue

**Comment by isaacabraham** [comment]
Linked to #1753

**Comment by isaacabraham** [comment]
I can't even see the option in Ionide any more:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1781813/188486485-ff26cd69-e10b-4d4e-902f-1bb77439335d.png">
