### ISSUE TITLE
Feature: Smart grow/shrink selection

### ISSUE THREAD

**Issue by kontomondo** [ionide/ionide-vscode-fsharp#174]
An important feature when it comes to refactorings, selection based quickfixes & surround with functionality. The idea is that given an initial placement of the cursor, activating the smart selection grow would intelligently expand the selection based on the context, to be as useful as possible for a given context.

If you're on string or variable, it starts with Camel/Pascal case selection and selects only the part of the word, then extends into the word, then if it's a string, it extends to encompass the interior of the string, then the string + quotes.
That is so far:
1. "helloWorld Hello!".Split(' ') (cursor is on first "e")
2. "**hello**World Hello!".Split(' ') (bold represents the selection) after first activation
3. "**helloWorld** Hello!".Split(' ') next activation
4. "**helloWorld Hello!**".Split(' ') next activation
5. **"helloWorld Hello!"**.Split(' ') next activation
6. **"helloWorld Hello!".Split(' ')** next activation

Then it would proceed to any next ".", ")", "]", "}" or the whole line (there will be lots of variations of this, so it'll likely need a lot of iterations until we get this right).
Afterwards it expands into the current function, then the let, then the outer scope of that, whatever it is (fun, if, while, match, member, type, struct, etc.) .

Special accommodations could be made for pipes and such.

There would be a separate shortcut for shrink that goes the opposite way (kind of an undo for selection expansion)

Note that there are some extensions already for VSCode that do this, but they don't work well for F# as they're not context aware.

**Comment by kontomondo** [comment]
see https://github.com/Microsoft/vscode/issues/4795 and https://github.com/Microsoft/vscode/labels/smart-select

**Comment by Krzysztof-Cieslak** [comment]
OK, I've implemented the SelectionRange Provider in https://github.com/fsharp/FsAutoComplete/commit/cf76ab63f28c5854fdd8e815e14593e1a6424d7f and https://github.com/ionide/ionide-vscode-fsharp/commit/32b673478fab08a9090c11a1e2a189786a92c598

It's still not perfect, but it should be usable
