### ISSUE TITLE
Feature: Surround with ...

### ISSUE THREAD

**Issue by kontomondo** [ionide/ionide-vscode-fsharp#175]
Would allow to surround a selection with:
1. `if` 
2. `while`
3. `match`
4. `async`
5. `try ... with` 
6. `if else` ?

First implementation could just trivially include surround with "if"

**Comment by Krzysztof-Cieslak** [comment]
We don't plan to implement this. In F#, very often it's enough to press tab to indent section, go line above, and write your control mechanism.
