### ISSUE TITLE
[Regression 7.0.0] Adding #load or #r instruction now require a restart for Ionide to pick up the new APIs

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1754]
Hello

### Describe the bug

Adding #load or #r instruction now require a restart for Ionide to pick up the new APIs

This is a regression compared to version 6.0.6.

### Steps to reproduce

*FileA.fsx*
```fs
let upper (text : string) = text.ToUpper()
```

*FileB.fsx*
```fs
let name = "Stormblessed"
```

1. Open an `FileB.fsx` file
2. Wait for Ionide to load (hover should be working or you should see the linelense)
3. Add `#load "./FileA.fsx`
4. Try to add `FileA.upper`
5. See that `FileA.upper` doesn't exist
6. Reload Ionide
7. Wait for Ionide to load
8. See that now in `FileB.fsx`, `FileA.upper` is recognised

### Expected behaviour

Ionide should recognised the new module available without a reload.

## Machine info
 - OS: Linux / Pop!_OS 22.04 LTS
 - .NET SDK version: 6.0.301
 - Ionide version: 7.0.0

**Comment by Tangent-90** [comment]
Maybe [this](https://github.com/fsharp/FsAutoComplete/issues/1055) is the way to fix it.

**Comment by baronfel** [comment]
With adaptive server enabled and/or version 7.5.1 I can't repro this.
