### ISSUE TITLE
Syntax highlight bug due to presence of use keyword

### ISSUE THREAD

**Issue by kirse** [ionide/ionide-vscode-fsharp#1755]
### Describe the bug
Syntax highlighting turns wonky with the presence of the `use` keyword in variables.    See attached screenshots.

### Steps to reproduce
Sample code chunk
```fsharp
let registrationHandler : HttpHandler = 
    fun (next : HttpFunc) (ctx : HttpContext) ->
        task {
            let form = ctx.TryBindFormAsync<RegistrationForm>().Result
            match form with
            | Error _ -> 
                return! razorHtmlView "User/Login" None None None next ctx
            | Ok form ->
                let userMgr = ctx.GetService<UserManager<User>>()
                let user = new User(Email = form.Email, UserName = form.Email)
                let! result = userMgr.CreateAsync (user, form.Password)
                
                if result.Succeeded then
                    return! redirectTo false "/live" next ctx
                else
                    return! redirectTo false "/live" next ctx
        }
````
Doesn't work:

![image](https://user-images.githubusercontent.com/3741903/181425829-80e6b476-8e7f-44a7-ab9e-b9c36a951fee.png)

Does work (change vars to something without `use` in them):

![image](https://user-images.githubusercontent.com/3741903/181425927-a5c1ba04-b592-42ae-935c-a9f98472e0d0.png)

### Expected behaviour
Syntax highlights according to F# rules

## Machine info
- Win10
- dotnet 6.0.300
- VScode 1.69.2
- Ionide v7.0.0

**Comment by Krzysztof-Cieslak** [comment]
This has been fixed by https://github.com/ionide/ionide-fsgrammar/pull/179; it will be available in the next Ionide release.

**Comment by enriquein** [comment]
Hi, not to be pushy or anything, but I noticed that this change didn't make it into the 7.1.0 release. Do you know if it will be included in the next release?

**Comment by baronfel** [comment]
Great catch, and thanks for asking. I just didn't update all dependencies when I did 7.1.0, which is why this wasn't included. I've just done this and pushed it up, so the next release _will_ include the fix. That release should be within a week - I've got some fixes to proj-info that I want to flow into FSAC and do a new release with.
