### ISSUE TITLE
alt-enter opens zsh instead of FSI

### ISSUE THREAD

**Issue by cartermp** [ionide/ionide-vscode-fsharp#176]
I'm using a basic template - I've written some code in the F# script file, select the whole file, and hit alt+enter.  Sometimes, it opens FSI as expected.  However, today it started opening zsh:

<img width="678" alt="screen shot 2016-09-28 at 12 02 18 pm" src="https://cloud.githubusercontent.com/assets/6309070/18928088/79adf73c-8573-11e6-8c77-38e7d8d2b118.png">

Using `>fsi: Send Selection` from the command palette does the same thing.

I'm using a mac with macOS Sierra.

**Comment by Krzysztof-Cieslak** [comment]
It's probably same bug as mentioned by @kirill-gerasimenko  in https://github.com/ionide/ionide-vscode-fsharp/issues/161#issuecomment-249674690. 

> I've got powershell as a terminal, and with my custom profile it takes ~4-6 seconds to just load. So 1.5 seconds is not enough.

I'll be probably able to fix it when new stable version of Code will be released - https://github.com/Microsoft/vscode/issues/547#issuecomment-249707904

**Comment by cartermp** [comment]
Sounds good!

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.6.8`

**Comment by cartermp** [comment]
😄
