### ISSUE TITLE
Does Ionide support showing reference count via code lenses when using line lense for signature info ?

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1764]
Is it possible to have the "5 References" shown when using line lense?

![Screenshot 2022-08-16 233119](https://user-images.githubusercontent.com/4760796/184989024-b2d4d9d5-bb2c-4368-a68d-194b3931488d.png)

If not, would you consider it as a new feature? And what would need to be done?

**Comment by TheAngryByrd** [comment]
This seems to work with both settings on. 

<img width="758" alt="image" src="https://github.com/ionide/ionide-vscode-fsharp/assets/1490044/a845b59e-6b8d-415a-9c11-d9fc5a180d5a">
<img width="396" alt="image" src="https://github.com/ionide/ionide-vscode-fsharp/assets/1490044/dda85e61-6333-49a6-b44e-b5a284451f75">

---

Let me know if there's something I missed here!

**Comment by MangelMaxime** [comment]
I can't reproduce anymore either.
