### ISSUE TITLE
Diagnostics are not cleared when removing a file from a project

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1768]
### Describe the bug

@baronfel Mentioned that diagnostics are not cleared when removing a file from a project.

### Steps to reproduce

1. Have a file with errors in it
2. Remove that file from the Project using the Solution Explorer
3. See that the diagnostics are still there

### Expected behaviour

Diagnostics should be removed

### Screenshots

https://user-images.githubusercontent.com/4760796/185739183-bbdb1d71-34d9-4775-990a-d0d32bc473ff.mp4

## Machine info
 - OS: Windows
 - Ionide version: [e.g 5.0.1, don't use descriptions like `latest` ] 7.1.0

**Comment by MangelMaxime** [comment]
@baronfel 

I don't know how to fix this problem any guidance?

**Comment by Krzysztof-Cieslak** [comment]
Call https://github.com/fsharp/FsAutoComplete/blob/main/src/FsAutoComplete/FsAutoComplete.Lsp.fs#L196 in `fsproj/removeFile` handler in FSAC.
