### ISSUE TITLE
Errors persist even if the code is fine again

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1769]
### Describe the bug

Since upgrading to version of Ionide 7.1.0,
I am experimenting some strange behaviour from the intellisense and diagnostics.

See this error message:

![image](https://user-images.githubusercontent.com/4760796/185740576-8193618f-cb7c-4013-ab1d-92f0e00aa0be.png)

It is complaining about a `projlet` variable while the actual variable name is `proj`. If I reload Ionide the problem disappear.

---

One way to produce a similar problem is to type a bunch of random text very quickly. And then clean the random text and see that even if the code should be fine there are errors persisting.

https://user-images.githubusercontent.com/4760796/185741028-b94f8ff5-5599-4d12-bbde-67c084e000af.mp4

*See how once Ionide is related the code is indeed valid*

Here I demonstrated it for errors, but this also impact the intellisense because it doesn't auto complete what we would expect it to. Something providing no intellisense at all or something result for another line.

I suspect that this is related to the introduction of [Incremental text sync](https://github.com/fsharp/FsAutoComplete/pull/981)

## Machine info
 - OS: Windows
 - .NET SDK version: [e.g. 5.0.100]
 - Ionide version: 7.1.0

**Comment by razzmatazz** [comment]
I have registered a related FSAC issue here:
- https://github.com/fsharp/FsAutoComplete/issues/996

**Comment by kevingentile** [comment]
I am seeing a similar behavior since upgrading to 7.1.0

**Comment by MangelMaxime** [comment]
I think this issue has been fixed
