### ISSUE TITLE
Adding the same file twice to a project will add the compile tag 2 times

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1771]
### Steps to reproduce

1. Use the solution explorer to "Add file" > `new.fs`
2. Use the solution explorer to "Add file" > `new.fs`
3. See that the fsproj has 2 lines `<Compile Include="new.fs" />`

### Expected behaviour

The `<Compile Include="new.fs" />` should only be added if the file not already present.

### Screenshots

https://user-images.githubusercontent.com/4760796/185758975-c20072f2-1581-472c-8a1d-61daf2b273af.mp4

## Machine info
 - OS: Windows
 - Ionide version: [e.g 5.0.1, don't use descriptions like `latest` ] 7.1.0

**Comment by MangelMaxime** [comment]
Would this behaviour be ok:

https://user-images.githubusercontent.com/4760796/185793117-bffc3e2a-2617-4af0-a9ad-37a633e793d7.mp4

If the file already exist in the fsproj an error is reported saying "File already exist".

**Comment by baronfel** [comment]
Could you try adding validation in the text box where the user can put the file name? I think it would be easier to just stop the bad behavior before the user can even submit the bad value.

**Comment by MangelMaxime** [comment]
This is indeed possible to do, however when loading the prompt even if the file `new.fs` exist and we return the error VSCode doesn't show it in the textbox. This is probably a bug in VSCode when they are loading the textbox.

![image](https://user-images.githubusercontent.com/4760796/185795924-8ecf4fb4-25b3-4ca3-8826-e18d072f43b1.png)

I see 2 possibilities:

1. We don't put `new.fs` in the textbox just keep it as a placeholder because user will most probably not use `new.fs` as the file name
2. Don't care about this small edge case and perhaps it will be fixed in the future in a VSCode release.

Demo:

https://user-images.githubusercontent.com/4760796/185796091-2261a02e-c2dd-4f19-8da7-53c58f8ec753.mp4

**Comment by Krzysztof-Cieslak** [comment]
Yeah, I don't think we need to worry about new.fs case, I guess most people won't name their files like that

**Comment by MangelMaxime** [comment]
@baronfel @Krzysztof-Cieslak 

I made a PR preventing the user from submitting the input if the file already exist in the project.

This indeed provide a better UX experience. 

However, because FsAutoComplete is not tied specifically to Ionide I think we should still handle the case on FsAutoComplete too.
For example, if people using Sublime Text or Emacs implements the `fsproj/addFile` commands they would still have the correct behaviour without duplication. And if they want to provide nice UX from the client they can implement it like done with Ionide.

What do you think?

**Comment by baronfel** [comment]
Yeah, that's a completely reasonable thing. Let's do it.

**Comment by MangelMaxime** [comment]
I created an issue to keep track of it.

I should work on it this weekend or next week.
