### ISSUE TITLE
You must add a reference to mscorlib

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#179]
First of all I want to say many thanks for developing Ionide! Its been really great so far!

Now to my problem...

Since I updated Ionide to the latest version all my source code is underlined red and I get the same message saying that I need to add a reference to mscorlib.

I used Ionide to work on an F# console app in .NET Core and previously it worked fine and now I am getting those errors everywhere which makes it very difficult to work because everything is literally red now.

Let me know if you need more information and I will attach it to this issue. Thanks!

![image](https://cloud.githubusercontent.com/assets/4580714/19093637/dac0a406-8a83-11e6-89f3-aef2e75da9bf.png)

**Comment by lukemerrett** [comment]
@dustinmoris @Krzysztof-Cieslak have you found any workarounds to this?  I'm getting the same issue and message in VS Code on Ionide-fsharp 2.6.3.

Strangley on mine it doesn't highlight the whole file but just the type declaration:

![image](https://cloud.githubusercontent.com/assets/1067457/19151097/b9b6a7b6-8bc2-11e6-8143-1af6ddabd2f5.png)

**Comment by dustinmoris** [comment]
No, my workaround is to use a different editor in the mean time and wait for a fix :)

**Comment by cloudRoutine** [comment]
(technically .net isn't officially supported yet)

@lukemerrett  & @dustinmoris can you link repos that reproduce the error? 
Have you checked the references in your project files? Is mscorlib included?
Are the `.fs` files you're coding in listed in the fsproj?
@lukemerrett have you tried building your project using the dotnet cli?

**Comment by lukemerrett** [comment]
@cloudRoutine answers:

- Repo is a work project unfortunately, any specific code snippets that may be useful I can send over?
- How would you add `mscorlib` to the `project.json` file?  That would be ideal if it resolves the issue
- No fsproj; it's a .Net Core project using `project.json` and fsc.  The files are all included however
- It builds and runs absolutely fine using `dotnet build` pointing to `fsc`

I've attached my `project.json` file for reference:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "compilerName": "fsc",
    "emitEntryPoint": true,
    "compile": { 
      "includeFiles": [
        "0-Models.fs",
        "1-Configuration.fs",
        "2-Repositories.fs",
        "3-Program.fs"
      ]
    },
    "debugType": "portable"
  },
  "tools": {
    "dotnet-compile-fsc": {
      "version": "1.0.0-*",
      "imports": [
        "dnxcore50"
      ]
    }
  },
  "dependencies": {
    "Microsoft.FSharp.Core.netcore": "1.0.0-alpha-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.Extensions.Configuration":"1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions":"1.0.0",
    "Microsoft.Extensions.Configuration.Json":"1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Newtonsoft.Json": "9.0.1",
    "System.Net.Http": "4.1.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by dustinmoris** [comment]
@cloudRoutine You can see the issue with this repo: https://github.com/dustinmoris/NewsHacker

It is a .NET Core console app and you are correct that Ionide doesn't officially support .NET Core yet, but despite this fact I raised the issue because it still worked pretty well before I upgraded and after the latest upgrade it turned into what you can see above in my screenshot. Otherwise I can echo what @lukemerrett said, the project doesn't have an .fsproj, there is no reference to mscorlib in project.json and it builds and runs fine from the .NET CLI.

**Comment by dustinmoris** [comment]
Update: I just got an update for 2.6.4 and it seems to be fine again. Will have to check at home as well, but looks good now.

**Comment by cloudRoutine** [comment]
it's not just that Ionide doesn't officially support .NET Core, it's that F# doesn't officially support .NET Core

**Comment by reinux** [comment]
I'm still having this issue.
