### ISSUE TITLE
Signature-as-code-lens should not show argument names

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#180]
It's just a mess:

![image](https://cloud.githubusercontent.com/assets/873919/19105130/0e0bc7b8-8ae9-11e6-9c5c-1f9c130c5cdb.png)

**Comment by Horusiath** [comment]
Two options I could see there:

1. Add signature as popup when hover over method definition or call.
2. Add settings key to show / hide signature as code lens.

**Comment by Krzysztof-Cieslak** [comment]
You get full signature in tooltip when you hover mouse cursor over definition or call.
And also printed in bottom "quick info" bar when you put text cursor over definition or call.

**Comment by vasily-kirichenko** [comment]
@Horusiath I'm afraid you don't understand what I was talking about. I suggested to remove parameter _name_ from the signature, not the signature itself (so signatures would be like ones in Haskell).

**Comment by tldrlol** [comment]
fwiw I agree that the argument names add superfluous noise, and would prefer to see only the types.

if this causes too big of a divide at least make it a user settable option.

**Comment by taimila** [comment]
Initially i disagreed with this proposal, but after taking a quick look to my codebase with code lens I must say I agree with @vasily-kirichenko here. 

When it comes to code lens signatures, I would remove variable names. However, I wouldn't touch how the mouse-over works currently (showing variable names).

**Comment by jackmott** [comment]
agree with taimila.

**Comment by TIHan** [comment]
I agree. You already see the variable names anyway, so removing them will make it a bit cleaner.

**Comment by tamizhvendan** [comment]
+1 For removing argument name.

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.6.3`
![image](https://cloud.githubusercontent.com/assets/5427083/19131185/bbd1614a-8b4e-11e6-96d2-a4bc2324c6eb.png)

**Comment by moodmosaic** [comment]
>Add settings key to show / hide signature as code lens.

Is this possible at the moment?
