### ISSUE TITLE
Ionide incorrectly highlights that a namespace is not defined

### ISSUE THREAD

**Issue by biergit** [ionide/ionide-vscode-fsharp#1800]
### Describe the bug
Ionide complains about "The value, namespace, type or module 'Http' is not defined."

### Steps to reproduce

1. `docker run -it --name dotnet mcr.microsoft.com/dotnet/sdk:6.0-jammy`
2. Open container as remote devcontainer in VS code
3. Create a folder with a file `playground.fsx` containing
> #r "nuget:FSharp.Data,4.1.1"
open FSharp.Data
let html = Http.RequestString("http://www.google.com")
printf $"{html}"

### Screenshots
![grafik](https://user-images.githubusercontent.com/1071968/199471582-6c06d399-93f2-4c66-8fb3-3e223a99b4cc.png)

## Machine info
 - OS: Docker on Windows
 - .NET SDK version: 6.0.402
 - Ionide version: 7.3.1

**Comment by secana** [comment]
Same issue on Linux and MacOS with .NET 7.0.102 and Ionide 7.4.0

Script works perfectly fine, it's just Ionide that complains. If I can do anything to help, just ping me.

![image](https://user-images.githubusercontent.com/12230822/213391613-58219f09-db3f-42fa-becc-29b77d88349d.png)

**Comment by da9l** [comment]
Downgrading to 7.2.3 solves the problem so this is likely a regression.

**Comment by baronfel** [comment]
This doesn't repro for me with 7.5.1, which was released today.
