### ISSUE TITLE
After opening diff editor, analysis temporary goes wrong

### ISSUE THREAD

**Issue by vain0x** [ionide/ionide-vscode-fsharp#1810]
### Describe the bug

When I open a diff editor of F# file and go back to a text editor, analysis (diagnostics, hover, rename) doesn't work, until I input in text editor.

### Steps to reproduce

- Assume an F# file (say `Program.fs`) is committed to git repository
- Open `Program.fs` in a text editor tab
- Open source control side bar, click `Program.fs` in it
- Diff editor of `Program.fs` will be opened. Close it
- In a text editor tab of `Program.fs`, hover doesn't work correctly

### Expected behaviour

Analysis work as usual

### Screenshots

https://user-images.githubusercontent.com/6957032/209672788-1994e720-bb8e-4194-a4d2-b39bb5e68a4c.mp4

## Machine info

* Operating system: **Linux**
* Arch: **x64**
* VSCode: **1.74.2**
* UI Kind: **Desktop**
* Ionide: **7.4.0**
* Runtime: **netcore**
* Dotnet version: **6.0.404**

### Additional context

In trace, VSCode sent a didOpen message with `git:` scheme URI to server:

```
[Trace - 22:17:08] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "git:/home/owner/repo/fs-playground/Program.fs?%7B%22path%22%3A%22%2Fhome%2Fowner%2Frepo%2Ffs-playground%2FProgram.fs%22%2C%22ref%22%3A%22~%22%7D",
        "languageId": "fsharp",
        "version": 1,
        "text": "module Program\r\n\r\nlet someFun () = ()\r\n\r\n[<EntryPoint>]\r\nlet main _ =\r\n    someFun ()\r\n    0\r\n"
    }
}
```

and didClose later:

```
[Trace - 22:17:12] Sending notification 'textDocument/didClose'.
Params: {
    "textDocument": {
        "uri": "git:/home/owner/repo/fs-playground/Program.fs?%7B%22path%22%3A%22%2Fhome%2Fowner%2Frepo%2Ffs-playground%2FProgram.fs%22%2C%22ref%22%3A%22~%22%7D"
    }
}
```

I guess, that didOpen message has written contents of text document in server cache, perhaps due to ignoring scheme.

**Comment by baronfel** [comment]
That's a good guess - I think we'd need to make sure in FsAutoComplete that git-schemed URIs are just entirely ignored for open/close/etc notifications

**Comment by TheAngryByrd** [comment]
https://github.com/fsharp/FsAutoComplete/issues/1031 FSAC issue

**Comment by sjohnsonaz** [comment]
I'm having a similar issue as well.  Any time I open the a file from the "Source Control" panel for comparison, the original version is picked up for compilation instead of the current version.

**Comment by TheAngryByrd** [comment]
As a workaround for noq, you should be able to save the file and type checking should come back.

**Comment by vain0x** [comment]
Resolved at v7.4.1. Thank you!

**Comment by sjohnsonaz** [comment]
Thank you for fixing this!  I saw the GitHub release, but it's not available in the Marketplace yet.

**Comment by mrboring** [comment]
I also can't find this release in the Marketplace. Will installing it manually affect future auto updates?

**Comment by baronfel** [comment]
We're having an issue with the release pipeline that we're digging into, but it is perfectly safe to install from the vsix on the GitHub release - VSCode will seamlessly pick up future updates.

**Comment by Krzysztof-Cieslak** [comment]
`7.4.2` is now available in VSCode Marketplace
