### ISSUE TITLE
Make F# Solution Explorer optional

### ISSUE THREAD

**Issue by ilog2000** [ionide/ionide-vscode-fsharp#1817]
I often use VSCode for working with C#, and I have a number of addons including "vscode-solution-explorer". My problem with Ionide is that F# Solution Explorer catches any solution file, even if the solution does not contain any single `fsproj` inside, then (after some time) it forcibly switches the focus on Ionide Solution Explorer. This is very annoying.

I suggest to make F# Solution Explorer part optional with a flag in addon settings defaulted to true. In the documentation it worth mentioning that turning it off requires manual import file ordering in `fsproj` file.

**Comment by MangelMaxime** [comment]
Can't you hide the F# explorer panel using `Right click > Hide`?

<img width="302" alt="image" src="https://user-images.githubusercontent.com/4760796/213456414-96445255-07bd-479b-b689-cc66c0d9e2c0.png">

**Comment by ilog2000** [comment]
It re-appears
![image](https://user-images.githubusercontent.com/4150856/213485863-339af58d-a024-49d2-8544-801423ce92df.png)

**Comment by baronfel** [comment]
There's a configuration setting for this: `FSharp.enableTreeView`. Try setting that to false and see how you like the experience.

**Comment by baronfel** [comment]
From the docs at https://ionide.io/Editors/Code/options.html:

> FSharp.enableTreeView
> 
> Enables the solution explorer view of the current workspace, which shows the workspace as MSBuild sees it
>
> **Type**: bool
>
> **Default**: true

**Comment by ilog2000** [comment]
Yes, this helped, thank you. Apologies that did not match this option to my case.

Resolved.
