### ISSUE TITLE
FSharp › Code Lenses › References: Enabled

### ISSUE THREAD

**Issue by ShalokShalom** [ionide/ionide-vscode-fsharp#1822]
This setting has multiple issues: 

**1.) It doesnt describe its relationship to other settings.**

As an example, **Editor: Code Lens** does disable it. This could be mentioned in the description. 

**2.) It doesnt work.**

Disabling it does not disable the References.

![Screenshot_35](https://user-images.githubusercontent.com/6344099/217893927-d3678f0b-b471-4fb9-b14b-0b5e62f59508.png)

**Comment by TheAngryByrd** [comment]
Thanks for reporting this. This is [already fixed in FSAC](https://github.com/fsharp/FsAutoComplete/pull/1052) and is in main. We're dealing with some release issues currently but should be out soon.

**Comment by ShalokShalom** [comment]
I would also like to add a comment about the involvement of Editor: Code Lens. 

Could you show me, where I find that text?
