### ISSUE TITLE
Code lens shows broken signature

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#184]
![image](https://cloud.githubusercontent.com/assets/873919/19153178/0cb74662-8bde-11e6-848b-dec04b087b46.png)
Real signature is
![image](https://cloud.githubusercontent.com/assets/873919/19153217/3926ca38-8bde-11e6-9a4a-66c7adae4165.png)
```fsharp
let inline notNull name arg =
  match arg with
  | null -> raise (ArgumentNullException name)
  | _ -> arg
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.6.4`
