### ISSUE TITLE
No tooltip, no quick info, no code lens for ``double backticked functions``

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#185]
![image](https://cloud.githubusercontent.com/assets/873919/19153630/07049736-8be0-11e6-9790-14205a6e7316.png)

**Comment by vasily-kirichenko** [comment]
However, if there're no spaces in function name, tooltip and quick info works, but code lens still does not:
![image](https://cloud.githubusercontent.com/assets/873919/19153730/57f34a48-8be0-11e6-9d3a-16c0b5d411ac.png)

**Comment by cloudRoutine** [comment]
related https://github.com/ionide/ionide-vscode-fsharp/issues/147

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.6.6`
