### ISSUE TITLE
No code lens on the last function in file

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#186]
![image](https://cloud.githubusercontent.com/assets/873919/19153935/185920c8-8be1-11e6-92a6-9a304b7e12cf.png)
after adding an empty line at the end:
![image](https://cloud.githubusercontent.com/assets/873919/19154018/734625f8-8be1-11e6-8a7b-f7cb923e41c5.png)

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce it with current version. Let's assume we've fixed it accidentally ;)

**Comment by vasily-kirichenko** [comment]
I confirm that the bug is gone :) However, without a test suite it may return.
