### ISSUE TITLE
XML code comment tooltips error on extended characters (e.g., >) 

### ISSUE THREAD

**Issue by darranhayes** [ionide/ionide-vscode-fsharp#1863]
### Describe the bug
XML Code comments that contain extended characters cause "An error occurred when parsing the doc comment" error when hovering over the commented symbol.

### Steps to reproduce
1. Create an F# script file (bugreport.fsx)
2. Define a code commented function: 

```
/// <summary>
/// function fn
/// </summary>
/// <example id="example-1">
/// <code lang="fsharp">
/// fn (fun i -> i <= 3) 2
/// </code>
/// Evaluates to "true"
/// </example>
let fn p x = if p x then "true" else "false"
```

3. Hover over the function definition and observe the error tooltip

### Workaround
HTML Encode characters such as > as `&gt`;

```
/// <summary>
/// function fn'
/// </summary>
/// <example id="example-1">
/// <code lang="fsharp">
/// fn' (fun i -&gt; i &lt;= 3) 2
/// </code>
/// Evaluates to "true"
/// </example>
let fn' p x = if p x then "true" else "false"
```

### Expected behaviour
Should correctly render the comments without requiring encoding of characters.

Code comments on the fsharp lang codebase are not encoded to compensate for these types of errors:

[https://github.com/dotnet/fsharp/blob/main/src/FSharp.Core/string.fsi](https://github.com/dotnet/fsharp/blob/main/src/FSharp.Core/string.fsi)

```
/// <example id="collect-2"> How to show the ASCII representation of a very secret text
/// <code lang="fsharp">
/// "Secret" |> String.collect (fun chr -> int chr |> sprintf "%d ")
/// </code>
/// The sample evaluates to <c>"83 101 99 114 101 116 "</c>
/// </example>
```

### Screenshots
![TooltipError](https://user-images.githubusercontent.com/2190584/231164169-8908b3b2-8514-460d-a4fd-55988f0e7d90.JPG)

## Machine info
 - OS: Windows 10
 - .NET SDK version: 7.0.102
 - Ionide version: v7.5.2

[bugreport - rename to fsx.txt](https://github.com/ionide/ionide-vscode-fsharp/files/11200459/bugreport.-.rename.to.fsx.txt)

**Comment by MangelMaxime** [comment]
The problem is caused by that specific character `<`.

You can use `>` without escaping it.

This is because, we are using an XML parser to parse the doc comment and it detect `<` as an opening tag.

I see 2 ways of fixing this problem:

- Be able to identify `<` that are not part of the doc comment structure, and escape them before the parser
- Implement a doc comment parser which doesn't rely on an XML parser

Unfortunately, neither of these solutions are easy to implements. Last time I checked, other editors had the same limitation as Ionide right now and I decided at the time that it was better to make the user use escaped syntax when having this problem otherwise the doc comment is not useful to the end user.

**Comment by darranhayes** [comment]
That all makes sense. Thank you. 

Given the use of a standard XML parser, I've changed my code block to be a CDATA section as follows:

```
/// <summary>
/// function fn
/// </summary>
/// <example id="example-1">
/// <code lang="fsharp"><![CDATA[
/// fn (fun i -> i <= 3) 2
/// ]]></code>
/// Evaluates to "true"
/// </example>
let fn p x = if p x then "true" else "false"
```

This avoids the parsing error and renders a usable tooltip. The only issue is that CDATA enclosing mark-up is also rendered.

![image](https://user-images.githubusercontent.com/2190584/231257314-f1dd8a9f-6bbd-447e-b6db-b060abf2d86c.png)

Could there be a simpler fix to render the contents of a CDATA section when detected?

If not, I'm happy to see this issue closed anyway as I have a workaround that I'm happy to use.

**Comment by baronfel** [comment]
I don't think we'd support CDATA here given that no where else in the .NET space that I'm aware of supports that syntax. The generally-accepted solution for all .NET languages is to escape the angle bracket when you need it to appear as a literal.
