### ISSUE TITLE
TypeError on startup

### ISSUE THREAD

**Issue by ismail** [ionide/ionide-vscode-fsharp#187]
Using VS Code 1.5.3 and using ionide-fsharp 2.6.3 (but I can reproduce this for the last 5-6 releases) I am getting this error on startup:

> shell.ts:428 Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
    at mapResult (C:\Users\ismail\.vscode\extensions\Ionide.Ionide-fsharp-2.6.3\Components\Errors.js:34:10)
    at C:\Users\ismail\.vscode\extensions\Ionide.Ionide-fsharp-2.6.3\Components\Errors.js:43:12
    at process._tickCallback (internal/process/next_tick.js:103:7)

This only happens on Windows, Linux is fine.

**Comment by Krzysztof-Cieslak** [comment]
It's just logged in console, right? It doesn't stop any functionality from working?

**Comment by ismail** [comment]
It's logged in console and no F# functionality works. No tooltips etc.

**Comment by Krzysztof-Cieslak** [comment]
Try installing https://www.microsoft.com/en-us/download/details.aspx?id=40760

**Comment by ismail** [comment]
That fixed the issue, thanks a lot!
