### ISSUE TITLE
dotnet ionide process doesn't stops on close vscode

### ISSUE THREAD

**Issue by enzonun** [ionide/ionide-vscode-fsharp#1877]
### Describe the bug
After closes the vscode , the dotnet process started by ionide remains live consuming much ram 

### Steps to reproduce
1. Open relatively short project
2. Closes vscode after ionide finish loading the project

### Expected behaviour
The dotnet process have to finish once vscode is closed

## Machine info
 - OS: Linux
 - .NET SDK version: 6.0.408
 - Ionide version: 7.5.4

**Comment by bonjune** [comment]
I suspect this bug is due to `--adaptive-lsp-server-enabled` option. With this option turned off, the ionide process stops as expected when I close VSCode.

**Comment by enzonun** [comment]
> I suspect this bug is due to `--adaptive-lsp-server-enabled` option. With this option turned off, the ionide process stops as expected when I close VSCode.

Yes. I just tested this and when it's disabled,it finishes correctly

**Comment by rmunn** [comment]
Reported upstream: https://github.com/fsharp/FsAutoComplete/issues/1117

Please add your experiences to that bug if you have more confirmation.

**Comment by TheAngryByrd** [comment]
This should be fixed in [7.8.2](https://github.com/ionide/ionide-vscode-fsharp/releases/tag/7.8.2) and [FSAC 0.61.0](https://github.com/fsharp/FsAutoComplete/releases/tag/v0.61.0)
