### ISSUE TITLE
Remove CodeLenses for `unit -> unit`

### ISSUE THREAD

**Issue by robkuz** [ionide/ionide-vscode-fsharp#188]
In cases where you dont have any useful type information (for example test functions) remove the type information

**Comment by Krzysztof-Cieslak** [comment]
I guess they question is how to reliably decide which signature is "useful"

**Comment by robkuz** [comment]
I understand your reluctance - yet on `unit -> unit` it should be a clear cut ;-)

**Comment by robkuz** [comment]
plus - at the moment it is not shown anyway. however the additional row for showing the CodeLens is there
<img width="650" alt="bildschirmfoto 2016-10-06 um 16 24 45" src="https://cloud.githubusercontent.com/assets/954793/19156234/7adfeba0-8be1-11e6-973e-653bcaa3ee2f.png">

**Comment by rojepp** [comment]
Imho `unit -> unit` is useful information, though perhaps not for a test.

**Comment by vasily-kirichenko** [comment]
It should not be removed since it's useful, especially for tests where it's a common mistake to make a test function return something non-`unit`, which compiles OK, but test runners don't launch such tests, yielding errors or ignoring them silently.

**Comment by robkuz** [comment]
@vasily-kirichenko wouldnt that be something more appropriate for FSLint?
@rojepp I agree that it is useful as it definitely hints to a sideeffectfull functions. However having said that. I personally never have such instances in my code apart from test functions and also here I think FSlint could be a better way

**Comment by vasily-kirichenko** [comment]
We are on .NET and `unit -> unit` is (unfortunately) a perfectly sensible type.

**Comment by Krzysztof-Cieslak** [comment]
I think we won't go with it. Mostly because we don't have a way to decide which signature is useful (and saying anything `unit -> unit` is useless is not a good idea IMO).
