### ISSUE TITLE
Extreme memory/RAM usage (on MacOS w/ Apple Silicon)

### ISSUE THREAD

**Issue by drhumlen** [ionide/ionide-vscode-fsharp#1881]
### Describe the bug
RAM usage frequently exceeds 20GB for a single project on my macbook pro with apple silicon.

### Steps to reproduce
Just normal usage, but over time it consumes more and more RAM. If it runs for a full day, it can reach >50GB usage. Since it accumulates over time, I suspect it some sort of memory leakage?

### Screenshots
<img width="1065" alt="image" src="https://github.com/ionide/ionide-vscode-fsharp/assets/4758115/01c2203c-ba8c-4b3a-afb4-b1bf8d2a335c">

## Machine info
 - OS: Mac
 - .NET SDK version: 7.0.202
 - Ionide version: 7.5.4
 - VSCode version: 1.79.0-insider  (using VSCode insider version atm to use Copilot Chat. But I have the same problem with normal VSCode)

**Comment by Choc13** [comment]
I'm also experiencing this issue. If I check the runtime status tab in the extensions pane then I see a lot of errors like this (can be 10s of thousands after running all day):

```sh
An item with the same key has already been added. Key: file:///path/to/project/SomeModule.fs -- -- <base64 string>
```

This is more of a hunch than anything conclusive, but I feel these are output each time I save a file. So I wondered if it might be related to the code formatter running. 

## Machine Info
* OS: macOS 13.4 (22F66)
* Chip: Apple M1 Pro
* .NET SDK: 7.0.200
* Ionide: 7.5.4
* Fantomas: v6.0.5+d8e7276795204e9e8a06d3974bf187fe8d60b0f0

**Comment by baronfel** [comment]
@Choc13 do you have any more log context for those messages^? Something like a stack trace? That would help a bunch. Also, there are some Ionide updates that update the compiler services, container tweaks to the adaptive LSP server, and include new settings for managing memory use. All of those might impact your experience now.

**Comment by Choc13** [comment]
Hi @baronfel 

I don't have any more output but I have noticed that since upgrading to one of the newer versions a few weeks that the problem no longer occurs. I wanted to give it a while before reporting the fix to make sure it was definitely no longer leaking and since updating I've not had to restart Ionide once. So I think it's good now 👍

**Comment by TheAngryByrd** [comment]
There was a known issue with type providers which was fixed in FCS so that might have been it.
