### ISSUE TITLE
Ionide not working with dotnet 8

### ISSUE THREAD

**Issue by francotiveron** [ionide/ionide-vscode-fsharp#1888]
### Describe the bug
Ionide doesn't work in my system. Can this be due to the fact that I am working with .NET SKD 8-preview 4 (while officially ionide supports up to dotnet 7)?

**Comment by MangelMaxime** [comment]
@francotiveron This is probably related yes.

In general, with every new release of .NET there are some adaptation to make. 

Perhaps, you can try using a `global.json` to force your project to stay on .NET 7 or below.

**Comment by baronfel** [comment]
I've been using Ionide with .Net 8 previews for months now, we'd need to see more specifics as to why your project in particular isn't working. Do you have any logs from the extension, or binlogs from project loading, that we can look at?

**Comment by mxj4** [comment]
I'm having similar issues on .NET 8 preview 5, here is my test project.
[learn-fsharp.zip](https://github.com/ionide/ionide-vscode-fsharp/files/11804571/learn-fsharp.zip)

VSCode bottom bar showing `Not in a F# project (still loading ...)`
extension output has
```
Starting OmniSharp server at 6/20/2023, 10:31:37 AM
    Target: /home/yue/dev/playground/learn-fsharp/learn-fsharp.sln

OmniSharp server started with .NET 8.0.100-preview.5.23303.2
.
    Path: /home/yue/.vscode-oss/extensions/ms-dotnettools.csharp-1.25.9-linux-x64/.omnisharp/1.39.6-net6.0/OmniSharp.dll
    PID: 24182

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 8.0.100 17.7.0 - "/usr/share/dotnet/sdk/8.0.100-preview.5.23303.2/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 8.0.100 17.7.0 - "/usr/share/dotnet/sdk/8.0.100-preview.5.23303.2/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/yue/dev/playground/learn-fsharp'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/home/yue/dev/playground/learn-fsharp/learn-fsharp.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/yue/dev/playground/learn-fsharp'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/yue/dev/playground/learn-fsharp' on host 23816.
```
```

**Comment by TheAngryByrd** [comment]
Time to go spelunking in msbuild again

![drg-spenlunking](https://github.com/ionide/ionide-vscode-fsharp/assets/1490044/07032e32-0bb8-4a05-b3f3-106dbf3a46d2)

**Comment by francotiveron** [comment]
> @francotiveron This is probably related yes.
> 
> In general, with every new release of .NET there are some adaptation to make.
> 
> Perhaps, you can try using a `global.json` to force your project to stay on .NET 7 or below.

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/8280970/b9b623b1-9990-4524-80cb-772689549a4a)
This typecheck error occurs for every F# file I open in the editor

**Comment by mxj4** [comment]
> I'm having similar issues on .NET 8 preview 5, here is my test project. [learn-fsharp.zip](https://github.com/ionide/ionide-vscode-fsharp/files/11804571/learn-fsharp.zip)
> 
> VSCode bottom bar showing `Not in a F# project (still loading ...)`
> 
> extension output has (this seems to be C# extension output, I don't see any output about F#)
> 
> ```
> Starting OmniSharp server at 6/20/2023, 10:31:37 AM
>     Target: /home/yue/dev/playground/learn-fsharp/learn-fsharp.sln
> 
> OmniSharp server started with .NET 8.0.100-preview.5.23303.2
> .
>     Path: /home/yue/.vscode-oss/extensions/ms-dotnettools.csharp-1.25.9-linux-x64/.omnisharp/1.39.6-net6.0/OmniSharp.dll
>     PID: 24182
> 
> [info]: OmniSharp.Stdio.Host
>         Starting OmniSharp on Unknown 0.0 (Unknown)
> [info]: OmniSharp.Services.DotNetCliService
>         Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
> [info]: OmniSharp.Services.DotNetCliService
>         Using the 'dotnet' on the PATH.
> [info]: OmniSharp.Services.DotNetCliService
>         DotNetPath set to dotnet
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Located 1 MSBuild instance(s)
>             1: .NET Core SDK 8.0.100 17.7.0 - "/usr/share/dotnet/sdk/8.0.100-preview.5.23303.2/"
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Registered MSBuild instance: .NET Core SDK 8.0.100 17.7.0 - "/usr/share/dotnet/sdk/8.0.100-preview.5.23303.2/"
> [info]: OmniSharp.WorkspaceInitializer
>         Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Detecting Cake files in '/home/yue/dev/playground/learn-fsharp'.
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Did not find any Cake files
> [info]: OmniSharp.MSBuild.ProjectSystem
>         Detecting projects in '/home/yue/dev/playground/learn-fsharp/learn-fsharp.sln'.
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Detecting CSX files in '/home/yue/dev/playground/learn-fsharp'.
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Did not find any CSX files
> [info]: OmniSharp.WorkspaceInitializer
>         Configuration finished.
> [info]: OmniSharp.Stdio.Host
>         Omnisharp server running using Stdio at location '/home/yue/dev/playground/learn-fsharp' on host 23816.
> ```
> 
> runtime status of Ionide for F# extension:
> 
> ```
> Activation Event:Startup
> Activation Time:33ms
> Activated By:Ionide.mechanic
> Uncaught Errors (9)
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> File already included in the project
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> No typecheck results for /home/yue/dev/playground/learn-fsharp/UseTypeProviders/Program.fs
> Messages (1)
> Command `fsharp.explorer.renameFile` already registered by Ionide for F# (Ionide.Ionide-fsharp)
> ```

Sorry this example is wrong. I'm new to F# ecosystem so there are lots of tooling details not obvious to me. It turns out you have to call
```
dotnet sln add xxx.fsproj
```
after you created new project through
```
dotnet new console -lang "F#" -o BasicSpreadsheet
```
Ideally, when creating a new project using `dotnet` CLI tools, it should automatically add the created project to the sln file at monorepo root.

I no longer see "not a F# project error" after manually called the CLI command and added the project to the monorepo solution file.

**Comment by mxj4** [comment]
Creating a new project within the `F# Solution Explorer` pane does not automatically add the new project to the solution. This might be a bug, since the UI makes it feels like the project creation happens within the solution.

**Comment by TheAngryByrd** [comment]
@baronfel and I bounced some idea around and came up with a workaround.

Set the [environment variable ](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_roll_forward)`DOTNET_ROLL_FORWARD=LatestMajor` before opening `code .`.

**Comment by francotiveron** [comment]
Even with this workaround, no changes. If it can be of any help this status bar shows as below and never changes

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/8280970/01a9bbc0-1fd0-494b-8b8d-988bc8ca565d)

**Comment by TheAngryByrd** [comment]
unfortunately that's not useful for debugging this. what logs do you get? Please make sure to include the msbuild logs.

**Comment by francotiveron** [comment]
Not sure what log you are after. Here the ionide:MSBuild (which is empty)
![image](https://github.com/ionide/ionide-vscode-fsharp/assets/8280970/c3e8e76a-b216-4a5f-9f28-6827cb96b670)

**Comment by francotiveron** [comment]
This is the version of VS Code I am using

![image](https://github.com/ionide/ionide-vscode-fsharp/assets/8280970/8529c0f7-d758-426e-8e5b-a6110cab2e8c)

**Comment by baronfel** [comment]
We'll be pushing out a new release of Ionide later today that should fix this issue.

**Comment by baronfel** [comment]
Version 7.7.1 was released just now - @francotiveron would you mind testing with it and seeing if that fixes your experience?

**Comment by francotiveron** [comment]
Fixed thanks.
