### ISSUE TITLE
Hyperlink for error code leading to a non-existent resource

### ISSUE THREAD

**Issue by RonaldTM9999** [ionide/ionide-vscode-fsharp#1893]
### Describe the bug
When I click on the hyperlink on the error code for the error FS1241 I'm led to https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-messages/fs1241 which gives an HTTP 404 error.

### Steps to reproduce

1. Write code in VS Code that generates a compiler
2. Click on the error shown in the problem pane as shown below

### Screenshot
<img width="580" alt="image" src="https://github.com/ionide/ionide-vscode-fsharp/assets/106024131/17b6dc3c-99c7-4892-8467-a6983b602cab">

### Expected behaviour
Link to resource that documents the error instead of HTTP 404.

## Machine info
 - OS: Mac
 - .NET SDK version: 7.0.305
 - Ionide version: 7.7.1

**Comment by TheAngryByrd** [comment]
👋 This is not something we directly control.  You'll want to open an issue on https://github.com/dotnet/docs/issues

**Comment by baronfel** [comment]
Having said that, we could potentially probe for if the link is valid and only linkify the code if it is valid. We'd want to cache this data to prevent a ridiculous amount of HTTP calls, though.
