### ISSUE TITLE
Path not shown to downloaded dotnet 

### ISSUE THREAD

**Issue by ShalokShalom** [ionide/ionide-vscode-fsharp#1916]
### Describe the bug

Ionide installed dotnet for me, since it did not find it on my PATH. I really like that inclusion, but a) after a restart, it doesn't find it, and still complains about it being absent. 

It does not, however, attempt to install it anymore. Now I am asking myself where the binary went, so I can either put the path to it, or install dotnet from my system's repository. 

I recommend to a) show the path, where it gets installed at and b) look into why this hasn't picked up after the restart of the app. 

Thanks a lot

### Steps to reproduce
1.) Install Ionide without having dotnet installed on Linux. 
2.) See Ionide installing dotnet.
3.) Ask yourself where. 

### Expected behavior

Clearly shown, where installation went. Does pick up the binary after restart (and ideally suggests the restart as well.)

## Machine info
 - OS: Garuda Linux (Arch, rolling)
 - 7 (I did not see which one exactly)
 - Ionide version: 7.9.0

### Additional context
If that makes any difference, I installed this bundle: 
https://marketplace.visualstudio.com/items?itemName=spencer-farley.ionide-and-vscode-solution-explorer

**Comment by baronfel** [comment]
Ionide doesn't do any .Net downloads at all, so I'm not sure what you're talking about here.

**Comment by ShalokShalom** [comment]
Hnn, then I am wondering, what did it. Probably the solutions explorer. Thanks for the heads up.

**Comment by baronfel** [comment]
I took a look at the solution explorer extension repo and didn't see anything that jumped out at me - it's possible that some other extension you have is using the vscode-dotnet-runtime extension, which downloads a copy of the .NET Runtime to a private folder for just that extension to use. That extension is what I would expect to cause the behavior you describe.

**Comment by ShalokShalom** [comment]
It is the C# extension. It downloaded dotnet the way you describe it. 
And it is a dependency of Ionide.

**Comment by baronfel** [comment]
Gotha - we've actually got a PR out that breaks that explicit dependency (though of course the C# will be required if debugging is desired).

The C# extension in the coming months will also be changing to reuse the global install of the SDK/Runtime. My team at work is busy rewriting vscode-dotnet-runtime to make that happen right now.

**Comment by ShalokShalom** [comment]
Can we not host the version of Ionide with the Debugger from Samsung next to the current one?
I would love that. 
Thanks for your work at the vscode runtime 👍🏻

**Comment by ShalokShalom** [comment]
And I know that we already provide a link to OpenVSX, for that second Ionide. I just think, that fewer people are willing to jump through the hoops. I am at least not, and still, I like to use the Samsung version, also to avoid the dependency.

Is it significantly more work to maintain? Since it seems like the necessary packaging is already done, so it would be just a second upload to the marketplace, I assume.

**Comment by baronfel** [comment]
Once we break the explicit C# dependency users would be free to install whichever build of a C# extension they'd like - Ionide won't care if it's the MS one or the muhammedsammy one, or if you packaged your own. So we wouldn't _need_ to bundle two extension variants.

**Comment by ShalokShalom** [comment]
Oh, thats nice. Ideal solution!
