### ISSUE TITLE
No space after code before type lense is shown

### ISSUE THREAD

**Issue by peheje** [ionide/ionide-vscode-fsharp#1924]
### Describe the bug
Before there was a space after the code before the type lense is shown.

Now this is gone:
<img width="295" alt="Screenshot 2023-09-07 at 20 25 10" src="https://github.com/ionide/ionide-vscode-fsharp/assets/7273366/0d33c49c-63a2-46d5-b6c9-82a6d76cb6ba">
Notice the `b//` used to be `b //`

This look especially wierd when font-ligatures is enabled:
<img width="199" alt="Screenshot 2023-09-07 at 20 26 32" src="https://github.com/ionide/ionide-vscode-fsharp/assets/7273366/7de64cd3-e983-4236-acd2-87eaf50c1660">

Notice the `=//` which should be `= //`

I'm on Ionide V 7.11.0 - 06.09.2023 and MacOS. But I think the issue was also present 1 version back, but just a hunch.

**Comment by Numpsy** [comment]
Hopefully fixed in 7.12.0
