### ISSUE TITLE
[Code lens] Completely wrong signatures for interface members

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#193]
![screenshot from 2016-10-09 13-46-34](https://cloud.githubusercontent.com/assets/873919/19219851/e84ef37e-8e26-11e6-80d8-78fe8e10f639.png)

https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharp.Editing/ProjectSystem/SolutionProvider.fs#L15-L19

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.6.7`
