### ISSUE TITLE
[Code lens] Inconsistent spacing after arrow

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#194]
Sometimes it's a single space, sometimes - no space:

![screenshot from 2016-10-09 13-57-28](https://cloud.githubusercontent.com/assets/873919/19219896/7f408daa-8e28-11e6-94e1-be5ed429c1bd.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.6.7`
