### ISSUE TITLE
Continuous error notifications

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [ionide/ionide-vscode-fsharp#1950]
### Describe the bug
Pestering, undisabable error notifications

### Steps to reproduce
1. Create a new mvc project
2. Go to an .cshtml file
3. Start modifying, typing etc
4. Receive a lot of notifications like on the screenshot

### Expected behaviour
No errors, or ability to disable/hide notifications

### Screenshots
![image](https://github.com/ionide/ionide-vscode-fsharp/assets/74532770/8a11fb9d-18ba-467a-8778-eeb3c84564fe)

## Machine info
 - OS: Linux fedora 38 workstation
 - .NET SDK version: 7.0.11
 - Ionide version: 7.15.0

**Comment by TheAngryByrd** [comment]
Your errors show for the C# extension. You'll want to open an issue in their repo.
