### ISSUE TITLE
VSCode sometimes "loses" intellisense.

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#196]
Latest VSCode (1.6.x) sometimes stops working with intellisense. I have to restart Code to get it back. I know that this is a woefully inadequate bug report - I have no clue why it happens or when. But I just wanted to report this - maybe have a eye on it.

**Comment by slang25** [comment]
Occasionally I see the same thing, it happens rarely. I'm going to enable logging (instructions here: https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting) and see if I get something useful when this happens again.

**Comment by isaacabraham** [comment]
When it loses intellisense, doing a `CTRL + SPACE` (to "force" intellisense) when hovering over a symbol leads to this error in the debug console: -

```
Extension Host] [IONIDE-FSAC] RES (2091) <- {completion} ERROR in 4 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O
```

**Comment by TeaDrivenDev** [comment]
I've seen it too, on two different machines (Windows 7 and 10). It didn't seem to work again *immediately* after a restart, but did a few minutes later.

**Comment by CodEFouR** [comment]
I can confirm this issue. It happens so often that I could observe this many times a day. I don't have complicated code and don't work with Ionide intensively, but it breaks too many times. 
I don't know what breaks it, but seems when I have some compiler complains (red wave lines), it may break. By break, I mean the CodeLens doesn't work, the autocomplete doesn't work, F12 doesn't work etc... 
If I toggle the developer tools I see the error `Cannot read property 'data' of null: TypeError: Cannot read property 'Data' of null at /Users/user/.vscode/extensions/Ionide.Ionide-fsharp-2.7.1/Components/CodeLens.js:83:66`.

**Comment by Krzysztof-Cieslak** [comment]
I *think* it should also be fixed by https://github.com/ionide/FsAutoComplete/pull/17

Closing for now, please let me know if it repeats.

**Comment by fsoikin** [comment]
Happens to me too on VSCode 1.8.1, Ionide 2.17.1.

```
[Extension Host] [IONIDE-FSAC] RES (031) <- {completion} ERROR in 6 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O
```
