### ISSUE TITLE
Can't BuildPackage on Linux

### ISSUE THREAD

**Issue by azumikav** [ionide/ionide-vscode-fsharp#20]
build.fsx is looking for npm in /usr/local/bin/ but in my machine npm in in /usr/bin/ (and it's supposed to be there in most distros if you install npm via the package managar)

**Comment by azumikav** [comment]
it should use whatever npm is in PATH, no need for an absolute path.

**Comment by Krzysztof-Cieslak** [comment]
Fixed with #21
