### ISSUE TITLE
Experimental instance failed to start language service

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#200]
![image](https://cloud.githubusercontent.com/assets/873919/19341104/b7e1b076-9134-11e6-83b8-fa579366e3e0.png)

The build tools are installed:

![image](https://cloud.githubusercontent.com/assets/873919/19341124/ce79f564-9134-11e6-9f93-0fa5fbc510d9.png)

The machine was just rebooted.

**Comment by Krzysztof-Cieslak** [comment]
Need to run `build.cmd Build` to copy FSAC executable to right dir. Described in readme.
