### ISSUE TITLE
v7.19.0 not available in VS Code

### ISSUE THREAD

**Issue by mrboring** [ionide/ionide-vscode-fsharp#2006]
### Describe the bug
v7.19.0 is not available in VS Code.

### Steps to reproduce
1. Open VS Code
2. Open Extensions
3. Click ellipsis
4. Click `Check for Extension updates`

### Expected behaviour
v7.19.0 would be installed.

## Machine info
 - OS: Windows 10 (10.0.19045)
 - .NET SDK version: 8.0.204
 - Ionide version: v7.18.2

**Comment by TheAngryByrd** [comment]
Yeah there's an issue with a publish token expiring. Fixing soon.

**Comment by TheAngryByrd** [comment]
Fixed: https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp&ssr=false#version-history
