### ISSUE TITLE
Prevent Ionide from triggering VSCode window focus on project load

### ISSUE THREAD

**Issue by tymokvo** [ionide/ionide-vscode-fsharp#2008]
Hello,

My team works primarily in F# across a number of related repositories. This means that we frequently need to have multiple VSCode instances running and loading different fsproj files.

When using several different windows, it can be extremely distracting to have one of them unexpectedly take focus. This is especially true if they are spread across desktops/spaces in the OS.

Is there a way to prevent Ionide from causing its hosting VSCode instance from taking focus when a project is loaded?

**Comment by TheAngryByrd** [comment]
I think you can disable this with `FSharp.showExplorerOnStartup`.

**Comment by tymokvo** [comment]
Thanks for the tip! I think that's working for me. 

Though, it does seem possible that someone may want to configure the behavior to show the explorer and not take window focus.

**Comment by TheAngryByrd** [comment]
> Thanks for the tip! I think that's working for me.

Of course!

> Though, it does seem possible that someone may want to configure the behavior to show the explorer and not take window focus.

Possibly. If you're willing to do the work we'd be open to a pull request.
