### ISSUE TITLE
<IsTestProject>false</IsTestProject> is ignored in test explorer 

### ISSUE THREAD

**Issue by JohnnyFasching** [ionide/ionide-vscode-fsharp#2014]
### Describe the bug
I wanted to ignore a project from testing with "<IsTestProject>false</IsTestProject>". But it looks like the Attribute is not considered in the test explorer when loading projects

https://github.com/ionide/ionide-vscode-fsharp/blob/4586785a8ecbaf2c9811b373e0cfc22bffb089e8/src/Components/TestExplorer.fs#L965

**Comment by Numpsy** [comment]
Dup of #1970 ?
