### ISSUE TITLE
Reference counts appearing in really odd places

### ISSUE THREAD

**Issue by ryanworsley** [ionide/ionide-vscode-fsharp#2019]
### Problem

With the most recent versions, all from 7.20 onwards I get References counts rendered in all sorts of strange places including comments etc. This bug isn't immediately present, but appears after a little time coding.

### Steps to reproduce

1. Install a version 7.20 or higher
2. After a time of coding these weird references appear

### Machine infos

* Operating system: **Darwin**
* Arch: **arm64**
* VSCode: **1.90.2**
* UI Kind: **Desktop**
* Ionide: **7.20.3**
* Runtime: **netcore**
* Dotnet version: **8.0.101**
<img width="693" alt="Screenshot 2024-06-26 at 12 29 57" src="https://github.com/ionide/ionide-vscode-fsharp/assets/19852717/a05657ac-48a6-44ac-9a06-ed7981afaf89">
<img width="693" alt="Screenshot 2024-06-26 at 12 30 18" src="https://github.com/ionide/ionide-vscode-fsharp/assets/19852717/43ab3b38-52db-4704-8a6c-30ea678d8209">

**Comment by OnurGumus** [comment]
I have seen the same problem.

**Comment by rmh54** [comment]
Same here using latest version 7.20.3. 
![image](https://github.com/user-attachments/assets/d09b7b1f-b601-4a10-8eda-86e9d6b453cb)

When navigating and editing a file the code flickers up and down and moves about as edits are made which makes it pretty much unusable.
