### ISSUE TITLE
Code lens should not disappear/appear while user is changing code

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#202]
It annoys a lot.

**Comment by Krzysztof-Cieslak** [comment]
I think we need to cache last good results of code lens (both position and content) and use it if for some reason (for example syntax error in file when you're in middle of typing) doesn't return value.

**Comment by cloudRoutine** [comment]
There should also be an indication that the cached results are stale, e.g.  

`string * string * string option -> int`
to
~~`string * string * string option -> int`~~

**Comment by baronfel** [comment]
I think I will investigate this starting Wednesday, if no one else has picked it up then.

**Comment by TeaDrivenDev** [comment]
I think even leaving empty spaces there would be okay if that helps avoid the jumping.

**Comment by Krzysztof-Cieslak** [comment]
Trying to fix it in `2.8.6`. Please let me know if it's still the case.

**Comment by haf** [comment]
Still jumping a lot.


https://vimeo.com/215830120/3a6e270dc8
