### ISSUE TITLE
Clicking to references broken since 7.20.2

### ISSUE THREAD

**Issue by OnurGumus** [ionide/ionide-vscode-fsharp#2027]
When I click to references highlight in the code editor in order to see referencing code, I see a red error popup coming as 

`Cannot read properties of undefined (reading 'Start')`

Downgrading to 7.20.1 fixes the problem.

## Machine info
 - OS: Windows/Mac/Linux: Linux
 - .NET SDK version: 8.0.300 
 - Ionide version: 7.20.2, 7.20.3

**Comment by OnurGumus** [comment]
I thought this repros everywhere as it repros 2 different machines I had.

**Comment by OnurGumus** [comment]
The problem is still going on by the way in all newer versions

**Comment by TheAngryByrd** [comment]
yeah nothing has been done to address this issue yet. Would be willing to accept a PR here!

**Comment by OnurGumus** [comment]
I thought it would be simple fix for you since the regression version is well known

**Comment by TheAngryByrd** [comment]
It's not an issue of simple, it's an issue of time.

**Comment by OnurGumus** [comment]
Seems working, thanks a million 👍
