### ISSUE TITLE
Formatting document when dotnet tools folder is not ~/.dotnet

### ISSUE THREAD

**Issue by MikaelUmaN** [ionide/ionide-vscode-fsharp#2032]
### Describe the bug
When installing dotnet global tools to specified `DOTNET_CLI_HOME` location as specified in: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables it is not possible to run formatting from within VS Code using Ionide.

### Steps to reproduce
Install steps in docker file

```docker
# Install dotnet.
RUN apt install -y dotnet-sdk-8.0 dotnet-sdk-7.0

# Enable detection of running in a container
ENV \
  # Enable detection of running in a container.
  DOTNET_RUNNING_IN_CONTAINER=true \
  # Enable correct mode for dotnet watch (only mode supported in a container).
  DOTNET_USE_POLLING_FILE_WATCHER=true \
  # Skip extraction of XML docs - generally not useful within an image/container - helps performance.
  NUGET_XMLDOC_MODE=skip \
  # Opt out of telemetry.
  DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT=true \
  # Make F# projects default for dotnet new cli.
  DOTNET_NEW_PREFERRED_LANG=F# \
  # Skip messages on telemetry.
  DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE=true \
  # Used for nuget cache etc.
  DOTNET_CLI_HOME=/opt/dotnet \
  # Install path for dotnet. 
  # The default location on Ubuntu 22.04 is /usr/share/dotnet (when installed from packages.microsoft.com) or /usr/lib/dotnet (when installed from Jammy feed). 
  DOTNET_ROOT=/usr/lib/dotnet

# Create dotnet directory.
RUN mkdir $DOTNET_CLI_HOME

# Source code formatter
RUN dotnet tool install fantomas --tool-path ${DOTNET_CLI_HOME}/tools
```

Then try to format document from the command line (works)

```bash
(base) jovyan@mikael-surface5:~/dev/tmp/fsharp/FSharpTestApp$ fantomas Test.fsx
Test.fsx was formatted.
```

versus from inside Vs Code (does not work).

### Expected behaviour
File is formatted.

### Screenshots
![image](https://github.com/user-attachments/assets/e4969936-19e1-441e-a2a0-da87b913a21f)

## Machine info
 - OS: Linux
 - .NET SDK version: 8.x.x
 - Ionide version: 7.20.3

### Additional context
As I am developing from a container and want to bind mount the home folder, I set a different tools path than the regular ~/.dotnet. I believe this is what causes the issue, and should be resolved by Ionide inspecting the DOTNET_CLI_HOME env variable.

I don't think this is a fantomas issue as I can run fantomas from the command line just fine.

### Workaround

```bash
ln -s /opt/dotnet/tools /home/jovyan/.dotnet/tools
```

**Comment by baronfel** [comment]
In this case I think this is a fantomas issue, but an issue with the Fantomas.Client library that the Fantomas project provides. This library handles locating the fantomas binary to run. Can you raise an issue there for them to investigate?

**Comment by MikaelUmaN** [comment]
Sure, thanks for quick reply. I will add it there. Close this if you feel it appropriate.

**Comment by baronfel** [comment]
For clarity - once Fantomas.Client implements this change, then ionide/fsautocomplete will need to bump their version of that library and release, then we will need to bump our bundled version of fsautocomplete to get the fix deployed to all ionide users as well as raw fsautocomplete users.
