### ISSUE TITLE
[Code lens] Wrong signature

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#204]
![image](https://cloud.githubusercontent.com/assets/873919/19351585/0f5c6064-9165-11e6-84bf-d4d067739c67.png)

**Comment by sergey-tihon** [comment]
One more sample
![image](https://cloud.githubusercontent.com/assets/1197905/19660287/cf993e9e-9a37-11e6-9164-c811e4a9120d.png)

- No CodeLens for Property
- Incorrect for field


```

    type ``Rewrite me``() =
        [<Microsoft.FSharp.Core.DefaultValue>]
        val mutable _field : System.DateTime

        member x.Property
            with get () = x._field
            and set (v) = x._field <- v
```

**Comment by sergey-tihon** [comment]
One more sample
![image](https://cloud.githubusercontent.com/assets/1197905/19769999/492eaf52-9c66-11e6-83eb-43d03fda0ecf.png)

```fsharp
type MyType =
    static member requireType (actual, expected, fn) =
        match actual with
        | expected -> fn()
        | _ -> failwith ""
```

**Comment by vasily-kirichenko** [comment]
FSAC returns wrong range for `_field`, which results with wrong "tooltip" request:

![image](https://cloud.githubusercontent.com/assets/873919/19770845/76c9e4f6-9c69-11e6-8e0b-6a321bab443b.png)

```json
{
        "UniqueName": "Rewriteme_1_of_1",
        "Name": "_field",
        "Glyph": "Field",
        "GlyphChar": "F",
        "IsTopLevel": false,
        "Range": {
          "StartColumn": 26,
          "StartLine": 5,
          "EndColumn": 41,
          "EndLine": 5
        },
        "BodyRange": {
          "StartColumn": 26,
          "StartLine": 5,
          "EndColumn": 41,
          "EndLine": 5
        },
        "File": "e:\\github\\Test1\\Test1\\Test2.fs",
        "EnclosingEntity": "C",
        "IsAbstract": false
      }
```

**Comment by vasily-kirichenko** [comment]
Fixed in FCS here https://github.com/fsharp/FSharp.Compiler.Service/pull/662 and in Ionide
![image](https://cloud.githubusercontent.com/assets/873919/19781101/7f1c5bb2-9c90-11e6-8beb-9590dc6f8624.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/ionide/ionide-vscode-fsharp/pull/251
