### ISSUE TITLE
Update FSAC used in Ionide to the 9.0.100 version

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#2048]

**Comment by goswinr** [comment]
Maybe related:
I just installed .NET9 sdk , now I get
`Unrecognized option: '--checknulls+'. `
reported for the top of my files, on Ionide v7.21.2
the fsproj has `<TargetFramework>net8.0</TargetFramework>`

**Comment by TheAngryByrd** [comment]
> Maybe related: I just installed .NET9 sdk , now I get a `Unrecognized option: '--checknulls+'. ` error reported for the top of my files, on Ionide v7.21.2 the fsproj has `<TargetFramework>net8.0</TargetFramework>`

Yeah 9 is not supported yet. You'll have to use a `global.json` to constrain it to the 8 runtime.

Something like:

```json
{
    "sdk": {
        "version": "8.0.100",
        "rollForward": "latestMinor"
    }
}
```

**Comment by goswinr** [comment]
@TheAngryByrd  🙏 thanks that helped !

**Comment by baronfel** [comment]
Done, check out the newest release :)
