### ISSUE TITLE
Cannot Toggle Types with Keys

### ISSUE THREAD

**Issue by aabbtree77** [ionide/ionide-vscode-fsharp#2056]
I am struggling with the ability to show/hide F# types in .fs files.

Adjusting manually a local (per project) `.vscode/settings.json` does the job, e.g. "editor.inlayHints.enabled": "on" will show the types. I can also hide them with "off". 

How to achieve this automatically with the keyboard shortcut?

Running ctrl+k ctrl+s and searching for "inlay" reveals the property 'fsharp.inlayHints.hideAll' whose keys I can set and it seems to work. It changes `.vscode/settings.json` to"editor.inlayHints.enabled": "off", or may even wrap it inside like this:

```
{
  "editor.inlayHints.enabled": "offUnlessPressed",
  "[fsharp]": {
    "editor.inlayHints.enabled": "off"
  }
}
```

 However, there is no 'fsharp.inlayHints.showAll' or anything to adjust these properties afterwards, one cannot set anything to "on" with keyboard shortcuts subsequently.

After some messing around I did manage to get "fsharp.inlayHints.showAll" appear in the search for "inlay" in ctrl+k ctrl+s. I have added 
"editor.inlayHints.enabled": "on" inside a global `.config/Code/User/settings.json`, but I am not entirely sure that this is what made it appear in the search. The problem is, setting the keys such as ctrl+f ctrl+s still would not work:

```
command 'fsharp.inlayHints.showAll' not found.
```

There is also "fsharp.inlayHints.setToToggle", it is recognized and executed when its keys are set, but it does nothing.

Also note that when the local `.vscode/settings.json` has "editor.inlayHints.enabled": "offUnlessPressed", pressing ctrl+alt shows the types for a split second, and only once. Pressing ctrl+alt afterwards does nothing, the types will remain hidden forever.

**Comment by aabbtree77** [comment]
I am using the latest VS Code on Ubuntu 22.04 (at least it shows "No Updates Available" after navigating to "Help/Check for Updates"). Ionide for F# v7.22.0 with Auto Update All.

**Comment by MangelMaxime** [comment]
If you remove all your `inlayHints` settings you should see this tooltip when hovering an inlay:

![Image](https://github.com/user-attachments/assets/b6865c15-c817-4b5e-8186-4a3585cb4c87)

You can then choose which behavior you would like, in theory setting only `"editor.inlayHints.enabled": "offUnlessPressed",` will make it so you can use `Ctrl+Alt` to toggle the inlay when pressing those keys.

**Comment by aabbtree77** [comment]
I did as you wrote and everything works now. A great tool this Ionide is, by the way. I could not expect that the whole dotnet and F# thing would install and run smoothly on Ubuntu 22.04. I have not tried accessing Unity3D from F# yet ;).

It works both ways now. Inside my project's .vscode/settings.json 

```json
{
  "editor.inlayHints.enabled": "onUnlessPressed"
}
```

will show all the type annotations. ctrl+alt will hide them while the keys are kept pressed.

```json
{
  "editor.inlayHints.enabled": "offUnlessPressed"
}
```

will hide them by default with ctrl+alt showing them while the keys are pressed. 

So a take away message is not to mess with the VS Code keyboard shortcuts, esp. the global settings.json, and do it the Ionide way initially as you describe here. Wish this was stated somewhere in the docs more clearly.

P.S. The only caveat is that Ionide does not toggle types without an extra mouse click on the code page, so Ionide works like old Linux terminal windows, you need to extra click on the editor window with the mouse to activate the keys repetitively, just "mouse hover" or being present over the code does not activate them. 

So, say, I see the types ("onUnlessPressed" mode):

ctrl+alt keeping pressed -> types become hidden,

the keys released -> types reappear.

ctrl+alt keeping pressed again -> types ARE NOT hidden.

I click with the mouse anywhere on the code window.

ctrl+alt keeping pressed -> types are hidden (correct).

the keys released -> types reappear (correct).

I then need to click with the mouse somewhere in the file to toggle again, and so on and so forth.

This is a minor thing so do not worry too much about it. I suspect this is so because VS Code is Electron/browser based, e.g. to play sound in an html page one also needs that extra mouse click to unlock AudioContext restrictions in a modern browser, there is simply no way to add sound in an html page with only a mouseenter or mousehover events without a click event, which is a really dumb restriction come to think of it.
