### ISSUE TITLE
Types and modules are not colored

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#207]
![screenshot from 2016-10-15 17-49-31](https://cloud.githubusercontent.com/assets/873919/19410917/df4544d0-92ff-11e6-8186-d5c3bfe80f1c.png)

Interesting that they are properly colored in tooltips.

**Comment by cloudRoutine** [comment]
the syntax highlighting is regex based - https://github.com/ionide/ionide-fsgrammar

it should be possible to do syntax highlighting like we do in VFPT using decorators for colorization

https://code.visualstudio.com/Docs/extensionAPI/vscode-api#TextEditorDecorationType
https://code.visualstudio.com/Docs/extensionAPI/vscode-api#DecorationRenderOptions

but FSAC doesn't have the functionality for it. (Another reason why we should keep working on fsharp.editing 😉 )
