### ISSUE TITLE
Code lens type incorrect for Map

### ISSUE THREAD

**Issue by taimila** [ionide/ionide-vscode-fsharp#209]
Code lens shows type wrongly for `Map<string, string>`. See below. If I move cursor over function, the tooltip shows the type correctly.

![bug](https://cloud.githubusercontent.com/assets/1727790/19415699/c2e442d8-9380-11e6-8d2c-b8e92d59caf6.png)

**Comment by taimila** [comment]
I'm not sure that I understand your reasoning here. As the screenshot shows there is a star (*) in Code Lens when it should be comma (,) instead.

I think you are using FSI here to prove that it works, but I have no issue with FSI or tooltips. This bug seems to be specific for Code Lens feature.

I'm using the latest version of Ionide-fsharp (2.6.12)

Please, reconsider opening this bug.

**Comment by cloudRoutine** [comment]
My mistake, I misinterpreted what you meant. You should have mentioned the `,` in your first post, I totally overlooked it 😆

**Comment by taimila** [comment]
Thanks for reopening! 👍 

 I'll try to improve my issue reporting skills. I realized I didn't mention versions or anything else that could be useful.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/ionide/ionide-vscode-fsharp/pull/264
