### ISSUE TITLE
Send references to F# Interactive

### ISSUE THREAD

**Issue by sergey-tihon** [ionide/ionide-vscode-fsharp#211]
Would be nice to be able to load on FSI all references from the project current open file belong to.
Similar like VS/plugin can do:
![image](https://cloud.githubusercontent.com/assets/1197905/19436541/68ea357c-9479-11e6-959b-d8d239d7471b.png)

I really hope that using Forge you can identify current project and get list of all referenced assemblies,

## Use case:
I have F# project developed in VS, that has pretty long list of dependencies (see below) 
Right now, I want to update the code using VS Code + Ionide and test that my changes work as expected in FSI. 

Would be nice to be able `Ctrl+Shift+P` type `FSI: Send references from project` and `Alt+Enter` my code to FSI

![image](https://cloud.githubusercontent.com/assets/1197905/19436699/6da8cb68-947a-11e6-9a7e-a921385e12f1.png)

**Comment by kirill-gerasimenko** [comment]
I could try adding this one.

**Comment by Krzysztof-Cieslak** [comment]
@kirill-gerasimenko: Would be really cool :)

`project` request to FSAC returns list of files and references in given project file (https://github.com/ionide/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CommandResponse.fs#L81-L88). Currently we ignore it (https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Core/Project.fs#L76-L78 and https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/Errors.fs#L41-L43) and don't store anywhere in memory - I guess we could just storing `project` responses and use this info to: 

1. Find project for current file
2. Get list of references

**Comment by kirill-gerasimenko** [comment]
@Krzysztof-Cieslak thanks for the details! It's really going to give me a better start, since I'm only starting to learn all this stuff!

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.7.0`

**Comment by sergey-tihon** [comment]
Wow! This works! Thank you @kirill-gerasimenko & @Krzysztof-Cieslak !

**Comment by kirill-gerasimenko** [comment]
You are welcome :)
