### ISSUE TITLE
Using "F#: Add Current File To Project" in VSCode does not actually do that thing.

### ISSUE THREAD

**Issue by stevenranney** [ionide/ionide-vscode-fsharp#212]
On Friday 14 October 2016 I was able to use *ctrl+shift+p* and use the commend *F#: Add Current File To Project* and have the file open in the editor automatically added to my *.fsproj* file.  

On Monday morning 17 October, after an update to Ionide-fsharp, the *Add Current File To Project* no longer works.

**Comment by kirill-gerasimenko** [comment]
Hi, 
What's the add-on version you are using?

**Comment by stevenranney** [comment]
The Ionide-fsharp version currently installed is *Ionide-fsharp 2.6.13*.

**Comment by kirill-gerasimenko** [comment]
Can you try installing version 2.6.11 manually from https://github.com/ionide/ionide-vscode-fsharp/releases/download/2.6.11/Ionide-fsharp-2.6.11.vsix and tell if it fixes your problem? 

![image](https://cloud.githubusercontent.com/assets/3036330/19443938/c724bc4c-948e-11e6-8e83-6916c95dc4c9.png)

**Comment by stevenranney** [comment]
Yes.  Installing *v2.6.11* allowed me to add the file to the *.fsproj* file.

**Comment by kirill-gerasimenko** [comment]
It looks like it is related to https://github.com/ionide/ionide-vscode-fsharp/issues/213

**Comment by stevenranney** [comment]
Thanks for your help.  I'll stick with Ionide-fsharp v2.6.11 for now but will monitor new versions for remedies.

**Comment by Krzysztof-Cieslak** [comment]
Can you try `2.6.14` ?

**Comment by stevenranney** [comment]
`v2.6.14`  worked as expected.

**Comment by psfblair** [comment]
I am using ionide-fsharp-2.23.0 and am seeing this issue (also unable to remove files from the project). Should I create a new issue or should this one be reopened?
(MacOS 10.12 + VS Code 1.9.1)
