### ISSUE TITLE
Can't get intellisence/tooltips working after 2.6.11 version

### ISSUE THREAD

**Issue by kirill-gerasimenko** [ionide/ionide-vscode-fsharp#213]
I've noticed the issue it earlier and fall back to 2.6.11 version, where everything works for me. 
What I see in the devtools for the versions higher than 2.6.11: 
![image](https://cloud.githubusercontent.com/assets/3036330/19443500/402683d4-948d-11e6-99bf-db540ce715e6.png)

It shows that Linter.fs handlerOpen fails with exception. I tried to debug it but got weird results - when I hit breakpoint and examine "event" variable via hover-over tooltip - it shows that the "document" property is undefined. But if enter "event.document" into the console - it shows the document properly. 

PS: I used vscode 1.6 and Insiders versions - result is the same. There is some regression after 2.6.11.

**Comment by kirill-gerasimenko** [comment]
It looks like things break in b91455df4a55ed09ebc63669e9a0d06970673314

**Comment by kirill-gerasimenko** [comment]
Offender is src/Components/Errors.fs

**Comment by Krzysztof-Cieslak** [comment]
Can you try `2.6.14` ?

**Comment by kirill-gerasimenko** [comment]
It works now, thanks! The solution was simple :)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for spotting the issue, @kirill-gerasimenko! It will be fixed in next Fable's version. Ionide must return a value in the active pattern for the time being, sorry!

**Comment by kirill-gerasimenko** [comment]
No problem :) It was a helpful accident
