### ISSUE TITLE
Make tooltips awesome, like in Rusty Code

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#214]
![screenshot from 2016-10-18 23-24-18](https://cloud.githubusercontent.com/assets/873919/19494979/28589ee2-958a-11e6-9943-bdff35588ab2.png)

https://github.com/saviorisdead/RustyCode/blob/master/src/services/suggestService.ts#L200

**Comment by cloudRoutine** [comment]
Configurable tooltips would be a boon, where xml attributes and additional information can be opted into, e.g.
* dll name
* remarks
* fully qualified name (on the bottom, not in the signature)
* etc

**Comment by vasily-kirichenko** [comment]
https://github.com/ionide/ionide-vscode-fsharp/pull/216

**Comment by leolorenzoluis** [comment]
@vasily-kirichenko I assume this doesn't include the fix for handling html tags inside the tooltip such ass <c> or <para>?

**Comment by vasily-kirichenko** [comment]
@leolorenzoluis it does not. I tried to convert <c></c> to spans and it does not work. I need to look at the RustyCode approach more carefully.

**Comment by Krzysztof-Cieslak** [comment]
I guess this may be closed - with all recent changes to tooltips they're (IMO) on acceptable level ;)
