### ISSUE TITLE
Tabs instead of Spaces when VSCode is set to Auto

### ISSUE THREAD

**Issue by xdaDaveShaw** [ionide/ionide-vscode-fsharp#22]
Not sure if this is a VSCode issue of something that can be fixed in ionide. Hopefully it can be solved in ionide.

When I work on a .fs or .fsx file (I guess others too) the editor inserts Tabs instead of spaces which causes compiler errors:

> TABs are not allowed in F# code unless the #indent "OFF" option is used

I have VSCode set to:

    "editor.insertSpaces": "auto",

Which says *If set to "auto", the value will be guessed when a file is opened.* but that doesn't seem to changing to spaces for fsharp.

Is there a way to get VSCode to insert spaces without using Workspace settings (I don't need a Workspace for every FSX) or changing the User Settings?

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately, we can't do this right now. Similar problem discussed in VSCode repo - https://github.com/Microsoft/vscode/issues/1073

**Comment by Krzysztof-Cieslak** [comment]
Closing right now, to be reopened if necessary features will be implemented in VSCode
