### ISSUE TITLE
[Code lens] Values declared within a function

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#226]
Code Lens don't appear to show for values declared within a function, but only for module-level bindings.

**Comment by Krzysztof-Cieslak** [comment]
Personally I think it would be too much noise. But feel  free to convince me that I'm wrong ;)

**Comment by isaacabraham** [comment]
You're right - it might be. Perhaps make it a config setting? Certainly from an educational point of view the automatic inference is *very* useful; if it works well for module-level values, why not nested ones?

**Comment by vasily-kirichenko** [comment]
It's not that simple to implements, we would need to create new FSAC endpoint just for this feature, copy-pasting and customizing "declarations" one.

And yes, I agree that it would be too much noise. It'd be better to show code lenses for all symbols while, say, `Alt` key is being pressed or something like that.

**Comment by Krzysztof-Cieslak** [comment]
I think there is no easy way to get "I press `Alt` and I see only some of CodeLenses" behavior with current VSCode API. TBH, I don't think it's currently possible at all.

And since I believe that showing those additional CodeLenses always would be too much noise I'll just close it for now.
