### ISSUE TITLE
Better signature formatting in tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#228]
What we have now:

![image](https://cloud.githubusercontent.com/assets/873919/19606418/c124a142-97ca-11e6-9d93-8bc9fbcdee19.png)

what XS can do:

![image](https://cloud.githubusercontent.com/assets/873919/19606475/3dfc8180-97cb-11e6-9220-f8cf11218371.png)

**Comment by vasily-kirichenko** [comment]
I've ported tooltip formatting from MD and now we have 

![image](https://cloud.githubusercontent.com/assets/873919/19618036/52183466-9848-11e6-9637-6d952b8b87f1.png)

instead of

![image](https://cloud.githubusercontent.com/assets/873919/19618014/1f5262d6-9848-11e6-8a10-9088160564ec.png)

But we lost parameters info.

(yes, signatures are not formatted yet, no idea how MD does it)

**Comment by Krzysztof-Cieslak** [comment]
Any idea why there is no parameters info?

**Comment by vasily-kirichenko** [comment]
https://github.com/ionide/FsAutoComplete/pull/19

**Comment by vasily-kirichenko** [comment]
@Krzysztof-Cieslak MD does not show param info on hover, but does show when it "inside signature", on a specific parameter:

![image](https://cloud.githubusercontent.com/assets/873919/19618076/76c2693e-9849-11e6-89eb-a03c2ddb80ae.png)

![image](https://cloud.githubusercontent.com/assets/873919/19618077/847c0b34-9849-11e6-93f7-be68545014ce.png)

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/19618643/3087a654-9859-11e6-979a-85653478c253.png)
![image](https://cloud.githubusercontent.com/assets/873919/19618647/42352124-9859-11e6-9471-59e1d4676aee.png)
![image](https://cloud.githubusercontent.com/assets/873919/19618649/4cd7dec8-9859-11e6-9408-b9a4fc342b79.png)
![image](https://cloud.githubusercontent.com/assets/873919/19618656/6813e13c-9859-11e6-8253-46d3b2250305.png)
![image](https://cloud.githubusercontent.com/assets/873919/19618664/a6d23a0e-9859-11e6-8f24-30db96ab3dc5.png)
![image](https://cloud.githubusercontent.com/assets/873919/19618674/d966d16e-9859-11e6-91ab-c216e9fd4566.png)

**Comment by vasily-kirichenko** [comment]
Unfortunately, it fails sometimes (same in MD):

![image](https://cloud.githubusercontent.com/assets/873919/19618865/07b52214-985f-11e6-8113-cd76727afe70.png)

was:

![image](https://cloud.githubusercontent.com/assets/873919/19618868/18d32d84-985f-11e6-9670-8060b06818ea.png)

taking all these into account (no parameters info and occasional failing to provide proper type info), I think we should not switch to this.

**Comment by vasily-kirichenko** [comment]
https://github.com/ionide/ionide-vscode-fsharp/pull/233

**Comment by vasily-kirichenko** [comment]
https://github.com/fsharp/FSharp.Compiler.Service/issues/658

**Comment by Krzysztof-Cieslak** [comment]
Implemented in `3.9.0`
