### ISSUE TITLE
Raw string literal: closing parentheses are automatically inserted

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#229]
Type the following characters into Ionide:

```
let a = "(
let b = @"(
```

Automatic insertion turns them into:

```
let a = "("
let b = @"()" // bug
```

I would expect the following instead:

```
let b = @"(" // correct
```

**Comment by cloudRoutine** [comment]
[The issses with autoclosing go far beyond this](https://github.com/Microsoft/vscode/issues/10242) and aren't particularly addressable at the moment.
