### ISSUE TITLE
Running websharperserverclient - lacking documentation

### ISSUE THREAD

**Issue by jeffreyjw** [ionide/ionide-vscode-fsharp#230]
I generated a `websharperserverclient` project in ionide, and... I have no idea how to run it on linux (I guess on any OS). In `suave` you have an executable, in `websharperspa` you can run `xsp4` in the project directory containing `Web.config`, but how do you run this one? I read about OWIN which this project uses, but there are really no good examples on the web how to simply run a server in CLI for an OWIN app (or I just couldn't find one - only some old tutorials with combining it with nginx or katana).

Anyways, the generated projects are lacking a basic README file that would show how to run them just to get started. I could provide some basic linux READMEs for those project templates which I know how to run ;), I think that a general rule that there should be a README file with run instructions in the generated project root would be not only a nice thing to have, but a necessity for new users like me.

**Comment by cloudRoutine** [comment]
Feel free to submit a PR. There are lots of templates for types of F# projects I never have and probably never will use. Mind you, [this should be a PR to Forge](https://github.com/fsharp-editing/Forge) not to this repo.
