### ISSUE TITLE
Wrong initial CodeLens on large files and no tooltips at all

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#234]
Open FCS folder, then open `TypeChecker.fs` file. After everything stabilized, we got the following CodeLens:

![image](https://cloud.githubusercontent.com/assets/873919/19624918/41706064-9912-11e6-9263-74bf3095b96d.png)

No tooltips at all, all requests return this:

```
[11:18:46 INFO ] REQ (077) -> {tooltip}, File = "~\src\fsharp\TypeChecker.fs"
[11:18:46 DEBUG] RES (077) <- {tooltip} in 8 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
```

Now insert a single space anywhere in the file. After about 3 seconds everything is perfect:

![image](https://cloud.githubusercontent.com/assets/873919/19624928/b7252f92-9912-11e6-8d9e-0867e5d7dcf1.png)

**Comment by Krzysztof-Cieslak** [comment]
I think I've fixed it by delaying CodeLens activation in some release in meantime.
