### ISSUE TITLE
Find all references does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#235]
MD:

![image](https://cloud.githubusercontent.com/assets/873919/19625168/c3868a7c-9919-11e6-8c6e-7a522c396d24.png)

VFPT:

![image](https://cloud.githubusercontent.com/assets/873919/19625175/f8bf55de-9919-11e6-8f7f-09c608e17cde.png)

Code:

![image](https://cloud.githubusercontent.com/assets/873919/19625170/d07f4cdc-9919-11e6-898d-0370ff2fdfbd.png)

**Comment by vasily-kirichenko** [comment]
VFPT and FSAC code looks exactly the same. Debugger shows that project options are different, FSAC has `ProjectFileNames` empty:

![image](https://cloud.githubusercontent.com/assets/873919/19625466/0a0fd5b8-9922-11e6-9ac6-5f0d871610e4.png)

whereas VFPT has it properly filled:

![image](https://cloud.githubusercontent.com/assets/873919/19625471/46d0d038-9922-11e6-9634-f5fc4c887ba7.png)

![image](https://cloud.githubusercontent.com/assets/873919/19625474/5a80f680-9922-11e6-82c0-da3103d3355b.png)

@7sharp9 can it cause FSAC's misbehavior?

**Comment by 7sharp9** [comment]
Probably, let me check in XS.

Also, probably better to calculate the project dependency tree as in: https://fsharp.github.io/FSharp.Compiler.Service/project.html#Analyzing-multiple-projects

**Comment by 7sharp9** [comment]
https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/blob/c3b2632255d295da31856648d123f9f7a06eb6ba/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs#L327

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsharp/FSharp.Compiler.Service/pull/659, https://github.com/ionide/FsAutoComplete/pull/22

In short, Ionide project has source file refs with wrong slashes:

```xms
<Compile Include="Core/Logging.fs" />
<Compile Include="Core/DTO.fs" />
<Compile Include="Core/Utils.fs" />
<Compile Include="Core/LanguageService.fs" />
<Compile Include="Core/Project.fs" />
<Compile Include="Components/Errors.fs" />
...
```
Which caused paths like "d:\foo\...\...\Core/Logging.fs" appear in one place in FCS and proper paths - in other places, which resulted with `<symbol to find's range>` <> `<resolved symbol's range>`.

**Comment by vasily-kirichenko** [comment]
Also fixed in https://github.com/ionide/FsAutoComplete/pull/23 (works with old FCS).
