### ISSUE TITLE
FAKE not added to project

### ISSUE THREAD

**Issue by Qudware** [ionide/ionide-vscode-fsharp#236]
I'm using the latest VS Code (1.6.1). When creating a New Project, opting in for FAKE, I only get the normal scaffold but without FAKE. So no `build.fs`, and no `build.cmd`.

Tried reinstalling all Ionide packages, with no success. 

(PS: I actually solved this by completely resetting VS Code (deleted .vscode) but wanted to bring this to your attention in case someone else has the problem.)

**Comment by Krzysztof-Cieslak** [comment]
I guess it was just some kind of hiccup during plugin installation. Not much we can do about it.
