### ISSUE TITLE
Send to FSI doesn't make terminal session visible (if hidden)

### ISSUE THREAD

**Issue by piers7** [ionide/ionide-vscode-fsharp#238]
If terminal window is not running at all, 'send to FSI' brings up terminal window focused on FSI. However:

- if FSI previously launched and terminal pane closed (but terminal session not killed - ie fsi still running), send to FSI doesn't reopen terminal.
- if terminal open, but on a different session (say I'm running a console session and an FSI session), send to FSI won't bring the terminal back to the FSI session.

Both can be very confusing - I though that FSI integration in VS Code had just gone back to not working for me, whereas in fact I'd just executed the thing I needed done several time in frustration...

**Comment by Krzysztof-Cieslak** [comment]
Hmm...

I wonder if @kirill-gerasimenko  can take a look at it.

**Comment by kirill-gerasimenko** [comment]
Hi,

Yep, I can look at it :)

**Comment by kirill-gerasimenko** [comment]
That one was easy :)

**Comment by Krzysztof-Cieslak** [comment]
Fix released in `2.8.3`. Thanks @kirill-gerasimenko !

**Comment by kirill-gerasimenko** [comment]
Np.

It looks like the terminal is focused after you send text there. I haven't noticed that during testing. Let me check if parameters to terminal.show fixes it.

**Comment by Krzysztof-Cieslak** [comment]
I think there is parameter for that in `terminal.show`

**Comment by kirill-gerasimenko** [comment]
Yes, will PR it now.
