### ISSUE TITLE
evaluation failure on vscode 0.10.3

### ISSUE THREAD

**Issue by simra** [ionide/ionide-vscode-fsharp#24]
Installed the latest f# package and afaik Code is fully up to date. Sending the snippet below yields this message:
> Running the contributed command:'fsi.SendSelection' failed.

```` 
let l = [1; 2; 3]
l
```` 

Help->About: 
>Version 0.10.3
>Commit 783ecf841a2b21edca6d86853670cae89b4c244f
>Date 2015-11-26T14:06:31.538Z
>Shell 0.34.1
>Renderer 45.0.2454.85
>Node 4.1.1

[edit: running on windows 10 fall update]

**Comment by Krzysztof-Cieslak** [comment]
Probably, F# interactive (fsi.exe) is not in PATH.

**Comment by simra** [comment]
Yes, that's the problem- I was installing the extension following instructions on a blog post which neglects to mention the necessary PATH setting. Thanks for the quick response.
