### ISSUE TITLE
Errors are not disappear immediately

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#254]
![1](https://cloud.githubusercontent.com/assets/873919/19816114/a57c6b58-9d4e-11e6-9b43-aaddc0f080c9.gif)
1. Everything is fine, no errors
2. Make code not compilable
3. Red squiggles appear
4. Revert the change
5. Code is fine
6. Red squiggles **have not disappear**

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce it on current master. Either we've fixed it by accident or it was just some weird hiccup /shrug

**Comment by vasily-kirichenko** [comment]
I confirm it's gone on master.
