### ISSUE TITLE
Linter hints do not appear until file is edited

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#255]
![1](https://cloud.githubusercontent.com/assets/873919/19817048/80f6d468-9d52-11e6-8223-2df905ac6cc8.gif)
1. Open a file
2. Wait for code lenses
3. No FSharpLint hints
4. Insert a space anywhere 
5. Hints appear

**Comment by vasily-kirichenko** [comment]
OK, linter make request to FSAC in parallel (actually, before) with "parse". On this line https://github.com/ionide/FsAutoComplete/blob/master/src/FsAutoComplete.Core/Commands.fs#L172 check results are not yet available, hence the bug.

**Comment by vasily-kirichenko** [comment]
Hm. I think the whole way on which this feature works is wrong. When a document changed, "parse" and "lint" are also sent to FSAC and "lint" gets last known parse and check results via `TryGetRecentCheckResultsForFile`, again. So this must be synchronized:

1. Document opened / changed 
2. "parse" is sent and result was received 
3. "lint" is sent

**Comment by vasily-kirichenko** [comment]
I added "parse" request before every "lint" and got interesting results. It's clear that "parse" returned some results, but "lint" get nothing by calling `TryGetRecentCheckResultsForFile`. May it be that `ParseProject` clears previous result from FSC cached?

[22:05:22 DEBUG] got FSAC line, is it the started message? true
[22:05:22 DEBUG] FSAC stdout: [I] 2016-10-28T19:05:22.6537941Z: listener started in 16.018 ms with binding 127.0.0.1:8396 [Suave.Tcp.tcpIpServer]

**[22:05:22 INFO ] REQ (001) -> {parse}, File = "~\Library1\File1.fs"**
[22:05:22 INFO ] REQ (002) -> {project}, File = "~\Library1\Library1.fsproj"
**[22:05:22 INFO ] REQ (003) -> {parse}, File = "~\Library1\File1.fs"**
[22:05:23 DEBUG] RES (002) <- {project} in 567 ms: Kind={"project"}
Data={"Project":"d:\\github\\VFPTTest\\Library1\\Library1.fsproj","Files":["d:\\github\\VFPTTest\\Library1\\AssemblyInfo.fs","d:\\github\\VFPTTest\\Library1\\Library1.fs","d:\\github\\VFPTTest\\Library1\\File1.fs"],"Output":"d:\\github\\VFPTTest\\Library1\\bin\\Debug\\Library1.dll","References":["d:\\github\\VFPTTest\\packages\\ExtCore.0.8.45\\lib\\net45\\ExtCore.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\FSharp\\.NETFramework\\v4.0\\4.4.0.0\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{"d:\\github\\VFPTTest\\Library1\\Library1.fsproj":""}}
**[22:05:23 INFO ] REQ (004) -> {parse}, File = "~\Library1\File1.fs"**
**[22:05:25 DEBUG] RES (001) <- {parse} in 3070 ms: Kind={"errors"}**
Data=[{"FileName":"d:\\github\\VFPTTest\\Library1\\File1.fs","StartLine":15,"EndLine":15,"StartColumn":7,"EndColumn":10,"Severity":"Error","Message":"Value restriction. The value 'foo' has been inferred to have generic type\n    val foo : '_a when '_a : null    \nEither define 'foo' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.","Subcategory":"typecheck"}]
**[22:05:25 INFO ] REQ (005) -> {lint}, File = "~\Library1\File1.fs"**
**[22:05:25 DEBUG] RES (003) <- {parse} in 2784 ms: Kind={"errors"}**
Data=[{"FileName":"d:\\github\\VFPTTest\\Library1\\File1.fs","StartLine":15,"EndLine":15,"StartColumn":7,"EndColumn":10,"Severity":"Error","Message":"Value restriction. The value 'foo' has been inferred to have generic type\n    val foo : '_a when '_a : null    \nEither define 'foo' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.","Subcategory":"typecheck"}]
[22:05:25 INFO ] REQ (006) -> {declarations}, File = "~\Library1\File1.fs"
**[22:05:25 DEBUG] RES (005) <- {lint} in 15 ms: Kind={"info"}
Data="Cached typecheck results not yet available"**
**[22:05:26 DEBUG] RES (004) <- {parse} in 3184 ms: Kind={"errors"}**
Data=[{"FileName":"d:\\github\\VFPTTest\\Library1\\File1.fs","StartLine":15,"EndLine":15,"StartColumn":7,"EndColumn":10,"Severity":"Error","Message":"Value restriction. The value 'foo' has been inferred to have generic type\n    val foo : '_a when '_a : null    \nEither define 'foo' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.","Subcategory":"typecheck"}]
[22:05:26 INFO ] REQ (007) -> {parseProjects}
[22:05:26 DEBUG] RES (007) <- {parseProjects} in 110 ms: Kind={"errors"}
Data=[{"FileName":"d:\\github\\VFPTTest\\Library1\\Library1.fs","StartLine":32,"EndLine":32,"StartColumn":9,"EndColumn":10,"Severity":"Error","Message":"Value restriction. The value 'r' has been inferred to have generic type\n    val r : Choice<int,obj>    \nEither define 'r' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.","Subcategory":"typecheck"},{"FileName":"d:\\github\\VFPTTest\\Library1\\Library1.fs","StartLine":45,"EndLine":45,"StartColumn":9,"EndColumn":11,"Severity":"Error","Message":"Value restriction. The value 'r'' has been inferred to have generic type\n    val r' : Choice<int,obj>    \nEither define 'r'' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.","Subcategory":"typecheck"},{"FileName":"d:\\github\\VFPTTest\\Library1\\File1.fs","StartLine":15,"EndLine":15,"StartColumn":7,"EndColumn":10,"Severity":"Error","Message":"Value restriction. The value 'foo' has been inferred to have generic type\n    val foo : obj    \nEither define 'foo' as a simple data term, make it a function with explicit arguments or, if you do not intend for it to be generic, add a type annotation.","Subcategory":"typecheck"}]
[22:05:26 INFO ] REQ (008) -> {project}, File = "~\Library1\Library1.fsproj"
[22:05:26 DEBUG] RES (008) <- {project} in 2 ms: Kind={"project"}
Data={"Project":"d:\\github\\VFPTTest\\Library1\\Library1.fsproj","Files":["d:\\github\\VFPTTest\\Library1\\AssemblyInfo.fs","d:\\github\\VFPTTest\\Library1\\Library1.fs","d:\\github\\VFPTTest\\Library1\\File1.fs"],"Output":"d:\\github\\VFPTTest\\Library1\\bin\\Debug\\Library1.dll","References":["d:\\github\\VFPTTest\\packages\\ExtCore.0.8.45\\lib\\net45\\ExtCore.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\FSharp\\.NETFramework\\v4.0\\4.4.0.0\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{"d:\\github\\VFPTTest\\Library1\\Library1.fsproj":""}}

**Comment by vasily-kirichenko** [comment]
@Krzysztof-Cieslak I think this should be solved in your https://github.com/ionide/FsAutoComplete/pull/21 PR this way:

1. Code sends "parse" asynchronously (which really means "a file changed, please parse and check it and when you are done, send back whatever useful info you can calculate on the results")
2. FSAC subscribe for FSC's `FileChecked` event
3. When a file is checked, FSAC sends "declarations", "lint", "errors" and other results (for example, colorizations, in the future) via WebSocket
4. Code never sends "lint", "declarations" or other requests explicitly, only listens for events

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.27.3`
