### ISSUE TITLE
Wrong code lens after last update

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#257]
![image](https://cloud.githubusercontent.com/assets/873919/19831633/a5837e38-9e17-11e6-83a0-ce79e94d349f.png)

**Comment by Krzysztof-Cieslak** [comment]
It looks like results from different file or something like that. I know that there are some problems if you have multiple files opened in different panels at start of plugin. Maybe that's the case?

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/ionide/ionide-vscode-fsharp/pull/259

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.8.9`
