### ISSUE TITLE
Codelens shows wrong signature when switching files

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-vscode-fsharp#258]
For soothsayer I recorded this gif which shows the issue:

![codelens bug](https://cloud.githubusercontent.com/assets/588746/19838099/a5892f24-9ebf-11e6-81c9-4ad3eae73e85.gif)

**Comment by 7sharp9** [comment]
memoization issue?  Looks like the sigs from the first file are shown on the seconds, indeantion looks out too.

**Comment by vasily-kirichenko** [comment]
duplicated https://github.com/ionide/ionide-vscode-fsharp/issues/257

**Comment by vasily-kirichenko** [comment]
https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/CodeLens.fs#L14 :))))

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/ionide/ionide-vscode-fsharp/pull/259

**Comment by Krzysztof-Cieslak** [comment]
Released in `2.8.9`

**Comment by 7sharp9** [comment]
The wrong signatures are no longer show, instead I get no signatures for the second file...
