### ISSUE TITLE
Upgrading to v2.8.9 no longer updates my .fsproj file when installing new libraries

### ISSUE THREAD

**Issue by stevenranney** [ionide/ionide-vscode-fsharp#262]
I upgraded this morning to `v2.8.9` and added two new libraries with `ctrl+shift+P` and `Paket: Add Nuget Package (to current project)`.  The packages are downloaded successfully and added to my paket.references file but are _not_ added to my `.fsproj` file.  This causes compiler errors.

If I create a brand new project with `v2.8.9` and add libraries with the same command, the `.fsproj` file is amended correctly.

**Comment by Krzysztof-Cieslak** [comment]
Can you copy-paste here everything logged in paket output panel?

**Comment by stevenranney** [comment]
Apologies.  Operator error.
