### ISSUE TITLE
Wrong completion of partially typed member after a method call

### ISSUE THREAD

**Issue by nightroman** [ionide/ionide-vscode-fsharp#263]
Code completion of `x.ToString().` works fine in this case:

````fsharp
    let x = 42
    x.ToString().
````

and gets expected members of `System.String`.

But if we partially type a member in the above example, e.g. `x.ToString().C`

````fsharp
    let x = 42
    x.ToString().C
````

and try to complete it then instead of expected `Chars`, `Clone`, `CompareTo`,
etc. we get all global symbols starting with `C`.

**Comment by Krzysztof-Cieslak** [comment]
Problem reported in https://github.com/fsharp/FsAutoComplete/issues/120
