### ISSUE TITLE
HTML chars are wrongly displayed 

### ISSUE THREAD

**Issue by aloisdg** [ionide/ionide-vscode-fsharp#266]
- VSCode Version: 1.7.0
- OS Version: Windows 10 (Version 1607 (OS Build 14393.351)

Steps to Reproduce:

1. clone https://github.com/aloisdg/Summary2Pages.git
2. open it with vscode

The problem may come from @vscode.

I should see `string -> unit` but I get `string -&gt; unit`:

![bug-vscode](https://cloud.githubusercontent.com/assets/3449303/19948694/3f82918e-a14e-11e6-9021-e3d1538176e3.PNG)

[on vscode](https://github.com/Microsoft/vscode/issues/14880)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.8.10`

**Comment by aloisdg** [comment]
You are fast! Thank you!
