### ISSUE TITLE
Code stops working on master

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#267]
1. Open FCS repo folder
2. Open `TypeChecker.fs` file
3. Tooltips start working almost immediately (wow)
4. Few seconds after that Code UI stops working completely (no reaction on mouse / keyboard)

![image](https://cloud.githubusercontent.com/assets/873919/20028181/d6bf8c8e-a33b-11e6-8399-d204d0509e68.png)

Pressing "Reopen" does not help. Something with just merged websockets maybe?

**Comment by vasily-kirichenko** [comment]
Last thing it outputs:

![image](https://cloud.githubusercontent.com/assets/873919/20028208/88f7a26a-a33c-11e6-9cce-25cc5946a985.png)

**Comment by Krzysztof-Cieslak** [comment]
Nothing happening in plugin should be able to kill whole VSCode (plugins are running in separate processes).

Only time I've seen this, was when someone showed me some super long CodeLenses. Maybe that's the problem? Try turning off CodeLens in settings and then check if error can be reproduced.

**Comment by vasily-kirichenko** [comment]
No, turning off CodeLens does not help. Code loads 1 CPU core at 100%:

![image](https://cloud.githubusercontent.com/assets/873919/20030201/1ec0842c-a371-11e6-90c8-d86e91f4a742.png)

**Comment by vasily-kirichenko** [comment]
I doubt it's performance related.

**Comment by Krzysztof-Cieslak** [comment]
The only thing I've noticed when I was trying to reproduce it was noticeable performance problem (on editor side) when FSAC was returning many errors for multiple files. My current theory right now is that crash can be extreme example of it /shrug.

**Comment by Krzysztof-Cieslak** [comment]
Should be better in `2.9.4`
