### ISSUE TITLE
Cannot send code to FSI

### ISSUE THREAD

**Issue by TeaDrivenDev** [ionide/ionide-vscode-fsharp#268]
When trying to send a line (just an `open` statement) from an `.fsx` file to FSI with Alt-Enter, I get the following error:

![2016-11-06 00_16_07-fibonaccinumbers fsx - hackerrank - visual studio code](https://cloud.githubusercontent.com/assets/2247219/20034254/82a08a42-a3b6-11e6-9acc-5a272758d50a.png)

The output window then shows this:

![2016-11-06 00_20_12-fibonaccinumbers fsx - hackerrank - visual studio code](https://cloud.githubusercontent.com/assets/2247219/20034256/e0362464-a3b6-11e6-99e4-788d69bd4852.png)

The same three lines with respective changing paths are added every time a different document tab is activated. I can type and execute F# code in the FSI window normally.

Ionide is 2.8.10, Code is 1.7.1.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `2.9.0`
