### ISSUE TITLE
Extensions not working due to folder names of extensions with version number.

### ISSUE THREAD

**Issue by ad1ttya** [ionide/ionide-vscode-fsharp#27]
It seems that with the latest updates to VSCode , extensions are installed with version numbers in the folder name,

such as Ionide.Ionide-fsharp-1.1.0
and this causes problem with the plugins not being able to find the path to the extension files..

The autocompletions and paket features only work when there are no version numbers in the extension folder name..

I was having problems in both windows 10 and linux(mint), and renaming the folders fixed these problems...

The problem is due to this part of the code in LanguageService.fs (line 112) : 
```fsharp
let start () =
        let path = (VSCode.getPluginPath "Ionide.Ionide-fsharp") + "/bin/FsAutoComplete.Suave.exe"
```

Similarly for paket:

```fsharp
if Process.isWin () then
            (VSCode.getPluginPath "Ionide.Ionide-Paket") + @"\bin\paket.exe"
        else
            (VSCode.getPluginPath "Ionide.Ionide-Paket") + @"/bin/paket.exe"
```

**Comment by Krzysztof-Cieslak** [comment]
Solution is to use `getExtension` function (https://code.visualstudio.com/docs/extensionAPI/vscode-api#extensions.getExtension) and use extension path from returned object.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in latest releases of all Ionide-vscode plugins.

**Comment by nikonthethird** [comment]
Thank you very much.

Can confirm it works now.
