### ISSUE TITLE
Show info / errors / linter suggestions as inline "decorators"

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#270]
It turns out Code supports "decorators", implemented in this PR https://github.com/Microsoft/vscode/pull/7181. I've not found any documentation or usage examples of this feature though. 

I suggests to use them to implements "inline" errors / infos / suggestions, like it does Sublime Text. I find such error reporting extremely better than just squiggles + info on hover + separate window. Look at it:

![image](https://cloud.githubusercontent.com/assets/873919/20039939/c15a9d9c-a45e-11e6-8161-116103f68de1.png)

![image](https://cloud.githubusercontent.com/assets/873919/20039958/05060568-a45f-11e6-87bb-7f5b7a8ff920.png)

![image](https://cloud.githubusercontent.com/assets/873919/20039961/1b4ac7aa-a45f-11e6-855e-af779768a9c2.png)

**Comment by Krzysztof-Cieslak** [comment]
I'm OK with this idea as long as feature will be opt-in.

**Comment by vasily-kirichenko** [comment]
I could try to implement it if you help with finding info about those "decorators". I cannot find anything :(

**Comment by Krzysztof-Cieslak** [comment]
Haven't played with this part of API yet, but I guess it'd need to use `setDecorations` from `TextEditor` object https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametexteditoraspan-classcodeitem-id294texteditorspan

**Comment by baronfel** [comment]
If it's alright with you all, I'd like to look into this.

**Comment by vasily-kirichenko** [comment]
@baronfel Go ahead! I'm complete newbie in Code and JS.

**Comment by vasily-kirichenko** [comment]
@baronfel see https://github.com/Microsoft/vscode/pull/7181#issuecomment-259085945

**Comment by Krzysztof-Cieslak** [comment]
I think that instead creating custom viewer for something like that (using decorations API) it would be cool if VSCode would support it natively using same UX as current navigation between diagnostics (`F8` and `Shift + F8` ) - I've created issue on VSCode repo about it: https://github.com/Microsoft/vscode/issues/19749

**Comment by Krzysztof-Cieslak** [comment]
Closing here, it will work out of the box when VSCode feature is implemented

**Comment by baronfel** [comment]
That's great news! Thanks for starting the discussion on this on the VSCode repo.
