### ISSUE TITLE
My memory is being eaten alive ...

### ISSUE THREAD

**Issue by yreynhout** [ionide/ionide-vscode-fsharp#275]
![image](https://cloud.githubusercontent.com/assets/142834/20223433/f9bb84f6-a839-11e6-995a-2f613ad2ef51.png)

![image](https://cloud.githubusercontent.com/assets/142834/20223538/70ecc9fe-a83a-11e6-828a-1e2609430597.png)

OS: Windows 10 (64 bit)
.NET: I have pretty much everything up until 4.6.2 installed + .NET Core

Reopening VsCode causes it to eat 1GB in about 15 seconds.

Can't give you my project (.NET 4.6), but a common theme seems to be that I have a lot of compilation errors due to overhauling what I'm coding rather drastically. I also have quite some deps in that particular project (akka, nodatime, windowsazure sdk, servicefabric, newtonsoft, streamstone, serilog etc...). I know that's not a lot to go on. Willing to help pin point if you can point me in the right direction. Turning on the logging in VsCode does not shown anything out of the ordinary. I'll try downgrading and see whether that changes anything.

**Comment by vasily-kirichenko** [comment]
That's a completely normal behavior because Ionide type check on start _all project it can find in the directory and all subdirectories_.

**Comment by yreynhout** [comment]
There's only one project to be found ...

**Comment by Krzysztof-Cieslak** [comment]
Try downgrading to `2.8.10` and check if behavior is the same. `2.9.0` introduced background checking, maybe I've done something wrong there.

**Comment by yreynhout** [comment]
Okay, things seem to be much more reasonable after I've uninstalled the latest version and installed `2.8.10` 

![image](https://cloud.githubusercontent.com/assets/142834/20227777/31f3cb1c-a84e-11e6-9594-ac36f45792e2.png)

![image](https://cloud.githubusercontent.com/assets/142834/20227815/76101ec2-a84e-11e6-853a-89781be4b8ab.png)

**Comment by Krzysztof-Cieslak** [comment]
Should be better in `2.9.4`
