### ISSUE TITLE
Feature Request: New FSI Command: `Send Last Selection`

### ISSUE THREAD

**Issue by fbehrens** [ionide/ionide-vscode-fsharp#276]
Hi, 
thanks for this great plugin, to begin with.

This feature would be very useful to me in `highly interactive` (tm) f# development, because:

When I'm working on some function, either I like to have some code in another window which reloads the file, opens and calls the function with some value. (Or calls a specific fuchu testcase).

With such functionality I can stay in the implementation file, and call my function with one keystroke to `FSI: Send Last Selection`. 

Without the feature I have to 
* change editor window
* select code
* `FSI: Send selection`
* switch Editor window back back.

Just want to ask if you would accecpt a merge request on that feature ?

**Comment by Krzysztof-Cieslak** [comment]
Sounds good for me.
