### ISSUE TITLE
Syntax coloring not working for destructuring assignments

### ISSUE THREAD

**Issue by TeaDrivenDev** [ionide/ionide-vscode-fsharp#281]
When using `let` with destructuring assignments for arrays, lists or tuples (with parentheses), it is not highlighted as a keyword and retains the default text color. The names being bound are also not highlighted.

With a simple tuple destructuring, coloring is correct:
`let a, b = 1, 2` has `let` highlighted as a keyword and `a` and `b` as names bound here.

Coloring does not work for the following:
```
let [| a; b |] = [| 1; 2 |]
let [ a; b ] = [1; 2]
let (a, b) = 1, 2
```
All of these will have `let` as well as `a` and `b` in the default text color.

**Comment by cloudRoutine** [comment]
this belongs on https://github.com/ionide/ionide-fsgrammar
