### ISSUE TITLE
Rename popup splits on apostrophe

### ISSUE THREAD

**Issue by TeaDrivenDev** [ionide/ionide-vscode-fsharp#282]
Pressing F2 on an identifier containing an apostrophe shows the renaming popup with only the part of the name that the caret is in. This also appears to be the value used for change detection, so changing one of the typical "derivative" names ending in an apostrophe to the same name without the apostrophe is not possible directly.

Examples:
`name'`
- Pressing F2 with the caret on any of the characters (including the apostrophe) shows the popup with `name` in it.
- Pressing Enter or making changes and then reverting them back to `name` and then pressing Enter cause no change, with the name remaining `name'`.
- Any actual changes made are correctly applied.
- Changing to a name ending in an apostrophe is possible.
- Pressing F2 with the caret directly after the apostrophe causes no popup to show.

`first'second`
- Pressing F2 on any character up to and including the apostrophe causes the popup to show `first`.
- Pressing F2 on any character after the apostrophe, including the one *after* the name causes the popup to show `second`.
- Pressing Enter or making changes in either part, reverting them and then pressing Enter cause no change to the full name.
- Any actual changes made to one part cause the *whole* name to be changed to that. e.g. pressing F2 on `second` and changing it to `xsecond`, then pressing Enter cause the complete name to change to `xsecond`.
- Changing to a name containing an apostrophe is possible.

I also noticed this while testing:
- Names *starting* with an apostrophe are not allowed in F#. Ionide permits changing a name to start with an apostrophe, though. Should that be prevented?

**Comment by Krzysztof-Cieslak** [comment]
Thanks for really detailed bug report! :)

I guess it's (as https://github.com/ionide/ionide-vscode-fsharp/issues/97) caused by using default `wordPattern` and `LanguageConfiguration`
