### ISSUE TITLE
Autocomplete proposes "failwith" when "with" should be used

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#283]
type Status =
    | Ok
    | Error of string
    | Done

    let x = Status.Ok

    match x |

put the cursor to |and write "with" and press Enter to go to new line.

Ionide will autocomplete to failwith.

I know this is not easy, but maybe we should not autocomplete if the code is already good.

I assume Ionide autocomplete just doesn't know about the keyword "with". /cc @vasily-kirichenko

**Comment by Krzysztof-Cieslak** [comment]
Yeah, looks like for some reason keyword autocomplete is not working.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.10.0`

**Comment by forki** [comment]
works like a charme! thx
