### ISSUE TITLE
function type signature up to last complete/correct code

### ISSUE THREAD

**Issue by Indy9000** [ionide/ionide-vscode-fsharp#285]
Type signature tips are super useful and thanks for all the hard work. :) 
It would be excellent if the type signature remains for the last known good code while writing the rest of the function

For example:
![screenshot from 2016-11-20 21-03-32](https://cloud.githubusercontent.com/assets/11760964/20466173/b3a2afd4-af65-11e6-9f24-54f0b7c32f9a.png)
![screenshot from 2016-11-20 21-04-12](https://cloud.githubusercontent.com/assets/11760964/20466175/b7192396-af65-11e6-8c18-e61a3d041379.png)

**Comment by Krzysztof-Cieslak** [comment]
I think I like current behavior: If you typed `array.iter` compiler knows that it will return `unit` even if you haven't finished code. So IMO it's correct behavior. 

Anyway, thanks for suggestion! :)
