### ISSUE TITLE
Line 34: Syntax error: unexpected end of file

### ISSUE THREAD

**Issue by simax** [ionide/ionide-vscode-fsharp#287]
When I choose to make a new `F# project` and then choose `Suave` the project seems to be created correctly. 

I then choose command `FAKE: build` and then `build` I get 

**Line 34: Syntax error: unexpected end of file** in build.sh file

If I run the penultimate line of the `build.sh` file in the terminal 
i.e. `mono packages/FAKE/tools/FAKE.exe $@ --fsiargs -d:MONO build.fsx` 

It builds the app and I can run it at the terminal and browse to `http://127.0.0.1:8083/` and see `Hello World` as expected.

I have limited knowledge of `bash` scripts, but this looks ok to me.

```#!/bin/bash
if test "$OS" = "Windows_NT"
then
  # use .Net

  .paket/paket.bootstrapper.exe
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
  	exit $exit_code
  fi

  .paket/paket.exe restore
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
  	exit $exit_code
  fi

  packages/FAKE/tools/FAKE.exe $@ --fsiargs build.fsx
else
  # use mono
  mono .paket/paket.bootstrapper.exe
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
  	exit $exit_code
  fi

  mono .paket/paket.exe restore
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
  	exit $exit_code
  fi
  mono packages/FAKE/tools/FAKE.exe $@ --fsiargs -d:MONO build.fsx
fi
```

Any idea why it's throwing an error?

**Comment by Krzysztof-Cieslak** [comment]
It's probably some issue with line endings. Try to using something like `dos2unix`

**Comment by simax** [comment]
Ok, thanks
