### ISSUE TITLE
Send 'silentCd' and # line/file to support current-directory-is-script

### ISSUE THREAD

**Issue by dsyme** [ionide/ionide-vscode-fsharp#29]
When sending interactions to F# interactive, it's normal to  send ``# silentCd``, ``# dbgbreak`` and ``# line filename``

This gives the same effect as F# Interactive in Visual Studio where errors report their file/line w.r.t the source document, and relative paths are interpreted w.r.t. the containing folder of the source document too, see this code: https://github.com/Microsoft/visualfsharp/blob/2d413fb940aa1677688454c50b8ec05cd3b6f78f/vsintegration/src/vs/FsPkgs/FSharp.VS.FSI/fsiSessionToolWindow.fs#L556

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.2.0`
