### ISSUE TITLE
intellisense window auto resize to accomodate more text

### ISSUE THREAD

**Issue by jackfoxy** [ionide/ionide-vscode-fsharp#298]
Intellisense window should expand to accommodate more horizontal and vertical text. Having to use the scroll bars is really inconvenient. Visual Studio resizes its intellisense window to show the whole text.

This could also be a user setting, if some people always prefer a smaller window.

**Comment by cloudRoutine** [comment]
I looked through [the vscode API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Hover) and I didn't see any way to do this
