### ISSUE TITLE
build.sh on OSX has default Windows line endings (^M)

### ISSUE THREAD

**Issue by vsinha** [ionide/ionide-vscode-fsharp#301]
`build.sh` as produced by the visual studio command `F#: New Project` has ^M line endings.

Throws the following error on first run (using zsh as my shell)
`zsh: ./build.sh: bad interpreter: /bin/bash^M: no such file or directory`

Using a tool like dos2unix works to fix it (I replaced line endings in vim and it works nicely now)

**Comment by Krzysztof-Cieslak** [comment]
This is problem with Forge templates and should be reported there.

**Comment by vsinha** [comment]
@Krzysztof-Cieslak is this the correct project? https://github.com/cloudRoutine/Forge
