### ISSUE TITLE
Implement view metadata as source (i.e., cannot navigate to definitions in compiled assemblies)

### ISSUE THREAD

**Issue by kflu** [ionide/ionide-vscode-fsharp#304]
Visual Studio has this feature for C# and F# where "go to definition" on a symbol in a compiled assembly brings up a temporary metadata file showing the type definitions of the symbols in the target assembly. This is call [metadata as source](https://msdn.microsoft.com/en-us/library/ms236403.aspx). 

For a fsx file like below

```
open System

let seed = Random()
let chart = 
    [0 .. 1000] |> List.map (fun x -> (x, seed.Next()))
    |> Chart.Point
```

In Visual Studio if you "go to navigation" on `List.map`, it brings up the meta data file like so:

![image](https://cloud.githubusercontent.com/assets/1031978/21071781/5d019126-be61-11e6-9536-674ef9c0b332.png)

But in Visual Studio Code with Ionide, that give you the error:

![image](https://cloud.githubusercontent.com/assets/1031978/21071793/8fd80cf6-be61-11e6-8bad-79e53051cf1f.png)

And language service debug output was:

```
[22:47:42 INFO ] REQ (032) -> {finddeclaration}, File = "c:\Users\...\Tutorial.fsx"
[22:47:42 DEBUG] RES (032) <- {finddeclaration} in 16 ms: Kind={"error"}
Data="Could not find declaration"
```

I wonder if this is a limitation with Ionide itself, or FsAutoComplete, or the language service? As a long time C#/F# developer, this is an immensely useful feature to have. Can we have this feature please 😄 .

**Comment by cloudRoutine** [comment]
This is actually a [VisualFSharpPowerTools feature](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharp.Editing/CodeGeneration/SignatureGenerator.fs), the metadata signature files are generated using FCS. To have this functionality in ionide it would need to be added to FSAC. 

Submit your PR to [ionide/FsAutoComplete](https://github.com/ionide/FsAutoComplete) 😉

**Comment by kflu** [comment]
@cloudRoutine thanks for the information!

**Comment by realvictorprm** [comment]
Hello world :wave:

**Comment by 7sharp9** [comment]
Would this be a failover command, e.g. when an error is returned from`finddeclaration` or modify find declaration to return a signature view.  It feels like it should be a separate command.

**Comment by Krzysztof-Cieslak** [comment]
It could probably be added as part of `finddeclaration` command on the FSAC side - we have pretty some information from FCS already there - https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L58-L61

**Comment by Titaye** [comment]
Will be ok when this FSAC PR https://github.com/fsharp/FsAutoComplete/pull/270 will be merged. It's not exactly metadata view but it should cover the needs

**Comment by kflu** [comment]
> Will be ok when this FSAC PR fsharp/FsAutoComplete#270 will be merged. It's not exactly metadata view but it should cover the needs

Checking back. Is this functionality present in Ionide now?
