### ISSUE TITLE
Record Stub Generation

### ISSUE THREAD

**Issue by JonCanning** [ionide/ionide-vscode-fsharp#306]
The one thing I miss from Power Tools in VS

https://fsprojects.github.io/VisualFSharpPowerTools/recordstubgeneration.html

Is this possible?

**Comment by cloudRoutine** [comment]
The Record stub generation is split into two parts - 
* [Using FSharp.Compiler.Service to determine the content to generate](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharp.Editing/CodeGeneration/RecordStubGenerator.fs)
* [Determining where the smart tag indicator should appear within the editor buffer](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharp.Editing.VisualStudio/CodeGeneration/RecordStubGeneratorSmartTagger.fs) 

The former would need additionally functionality added to FsAutocomplete, submit your PR to [ionide/FsAutoComplete](https://github.com/ionide/FsAutoComplete)
The latter would be implemented using the [vscode CodeAction API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#CodeActionContext) and submitted to this repo.
