### ISSUE TITLE
Signature Files are Treated as Implementation files

### ISSUE THREAD

**Issue by pblasucci** [ionide/ionide-vscode-fsharp#309]
### Steps to reproduce

1. Create a file named `SigTest.fsi` with the following implmementation:
```
namespace SigTest

open System

type Number

module SigTest =
  val add : int -> int -> int
```
2. Notice the errors on `type Number` and `val add : int -> int -> int`.

### Additional info

While the steps above use a stand-alone file, the same behavior occurs if opening a full project.

**Comment by cloudRoutine** [comment]
making a git repo, committing it once you've achieved your error state, and archiving it with `git archive -o myBugSituation.zip HEAD` and dropping the zip in your comment is the best way to provide a repro

**Comment by Krzysztof-Cieslak** [comment]
Can reproduce on Suave repo.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed (at least works with Suave right now) in `2.24.0`

**Comment by pblasucci** [comment]
Can confirm. This looks to be fixed now. Thanks!

**Comment by Krzysztof-Cieslak** [comment]
🎉
