### ISSUE TITLE
Project Template for AWS Lambda

### ISSUE THREAD

**Issue by mario-campos** [ionide/ionide-vscode-fsharp#311]
In [F# on AWS Lambda](http://lukemerrett.com/fsharp-on-aws-lambda/), Luke shows that it's possible to run F# on AWS Lambda, since [AWS Lambda now supports .NET Core](https://aws.amazon.com/blogs/compute/announcing-c-sharp-support-for-aws-lambda/). 

Can this project template be incorporated into Ionide so that developers can easily write and deploy AWS Lambda Functions?

**Comment by Krzysztof-Cieslak** [comment]
Project templates available in Ionide are defined in Forge (https://github.com/fsharp-editing/Forge), it should be reported there.

**Comment by mario-campos** [comment]
To follow along, It's [Forge issue 21](https://github.com/fsharp-editing/Forge/issues/21).
