### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by CodEFouR** [ionide/ionide-vscode-fsharp#314]
When I hover the pointer on the function or when the quick info shows up in Visual Studio + F# Power Tools, I see the quick info in my local language and even the error messages are shown in local language. Would it be possible to have i18n support in Ionide? Thank you.

Intellisense/Quick info localized message:
![default](https://cloud.githubusercontent.com/assets/594939/21299059/d6c504f2-c5d2-11e6-8734-e4f6db300415.png)

Localized error message:
![default](https://cloud.githubusercontent.com/assets/594939/21299066/e6961cae-c5d2-11e6-93a9-67912a99c5c1.png)

**Comment by Krzysztof-Cieslak** [comment]
I don't think it's possible for us. Translation in VS is done on VS side, not compiler / language services so we cannot use it (and it's not OSSed anyway). And translating error messages (and maintaining this translation) is definitely not in scope (or possibilities, given limited resources) of Ionide.

**Comment by CodEFouR** [comment]
I thought this is compiler/language facility as it changes based on my selection of my system locale when I'm using Visual Studio.
Anyway it's not an essential feature. Thanks.
