### ISSUE TITLE
F# interactive shows random characters when editing a line

### ISSUE THREAD

**Issue by egamma** [ionide/ionide-vscode-fsharp#315]
_From @basvdlinden on December 19, 2016 20:34_

- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Ionide-fsharp|Ionide|2.13.2|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Type a few characters
2. Press backspace a few times

or

1. Type a few characters
2. Use mouse to select a character in the middle
3. Type a few characters

_Copied from original issue: Microsoft/vscode#17557_

**Comment by Krzysztof-Cieslak** [comment]
@egamma F# Interactive is using terminal integration (`createTerminal` with `shellPath` set to `fsi.exe`) so as far as I understand Ionide shouldn't have any impact on stuff that happens when user is typing in directly in it.

IMO either:
1. It's bug in Code's terminal (and this should be reproducible with normal terminal, not only FSI -@basvdlinden, please try that)
2. It's bug in F# Interactive (and then it should be reproducible outside of VSCode, using FSI in command line - again, @basvdlinden, please try that)

**Comment by egamma** [comment]
@Krzysztof-Cieslak agreed, if this can be reproduced outside of the F# interactive, then please move the issue back to vscode.

**Comment by basvdlinden** [comment]
Test executed. Number 3 resulted in the same behavior:
1) Use "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe" outside VSCode: No random characters. Can't reproduce the problem. 
2) Use normal terminal (cmd.exe) from VSCode terminal: No random characters. Can't reproduce the problem.
3) Use normal terminal (cmd.exe) from VSCode terminal AND then start FSI.exe. "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe". Random characters. I can reproduce same behavior as using "ALT Enter" and then editing line.
4) Run cmd.exe and then "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe" outside VSCode: No random characters. Can't reproduce the problem.

**Comment by basvdlinden** [comment]
Retested. Same behavior for extensions:

|Extension|Author|Version|
|---|---|---|
|Ionide-fsharp|Ionide|2.19.4|
|csharp|ms-vscode|1.6.2|

**Comment by egamma** [comment]
@basvdlinden I cannot reproduce the behaviour given the above steps in the latest insider version. Please see the attached recording.

![terminal](https://cloud.githubusercontent.com/assets/172399/22037997/c89352ec-dcf9-11e6-989c-cb721d66b5cf.gif)

Can you pls try to reproduce in the insider build as well https://code.visualstudio.com/insiders

**Comment by basvdlinden** [comment]
@egamma I can reproduce it doing exactly the same. (Although reproducing it with just 10 characters on one line may take a few retries)

I have a different F# interactive version ... 

> Microsoft (R) F# Interactive version 14.0.23413.0
> Copyright (c) Microsoft Corporation. All Rights Reserved.
>
> For help type #help;;

I have also installed VS2015 and the Visual F# 4.0 extension

**Comment by egamma** [comment]
@basvdlinden can you please add an animated gif. This will help with coming up with a repro.

// FYI @tyriar

**Comment by Tyriar** [comment]
If this is about the prompt going out of sync with the backend after pressing backspace I expect it to be fixed in v1.9 as part of the winpty upgrade. See https://github.com/Microsoft/vscode/issues/14613 and https://github.com/Microsoft/vscode/issues/7345

**Comment by basvdlinden** [comment]
FSI works, but VSCODE has the problem:

![fsi](https://cloud.githubusercontent.com/assets/775650/22481024/d46cd5a2-e7f3-11e6-854f-311939960450.gif)

![vscode](https://cloud.githubusercontent.com/assets/775650/22481031/de97e972-e7f3-11e6-8716-93b3b4ceaa43.gif)

**Comment by Tyriar** [comment]
@basvdlinden that's the stable build (1.8.1). Can you test on [Insiders](https://code.visualstudio.com/insiders)?

**Comment by basvdlinden** [comment]
Could **not** reproduce the problem with VSCODE insiders. 

_(What you can't see on the animated gif is that the cursor jumps to random locations, within the input string, for a very short time on ever backspace key input.)_

![vscode_insiders](https://cloud.githubusercontent.com/assets/775650/22481514/dbf556b2-e7f5-11e6-81aa-a0fc0eb65d66.gif)

**Comment by egamma** [comment]
Closing - works in insiders build and will be pushed to stable soon.
