### ISSUE TITLE
Sometimes, invalid warnings and errors appear.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#318]
I have observed that while editing a project, the warnings and errors are increased like the picture below.
![image](https://cloud.githubusercontent.com/assets/12659251/21470843/de8353f4-caa2-11e6-87a4-bc8ae3ae0b90.png)
Yet, no errors are there at all. All these fake errors belong to an imaginary file of the form of "numbers\". I guess they are temporary files and they were parsed independently with some errors produced. And in order to delete them, I have to restart the editor.

**Comment by lucasmreis** [comment]
I think I'm having the same problem here. Ionide is not "recovering" from a compile error. It usually happens in the second or third error I type. For instance, if I define a type: 

```fsharp
type State = On | Off
```

And then type the following error and wait for Ionide to underline it:

```fsharp
let x = Of
```

It never "recovers" from the error, even if I correct it with `let x = Off`:

<img width="269" alt="screen shot 2016-12-27 at 12 46 49 am" src="https://cloud.githubusercontent.com/assets/8304008/21489108/fd443200-cbcd-11e6-81cd-dd64145b484e.png">

I then have to quit and start VS Code again.

**Comment by Krzysztof-Cieslak** [comment]
I think those are 2 different errors - 
1. thing reported by @teo-tsirpanis is probably result of sending parse request for some wrong temporary files (I would bet on git diff preview windows) - probably we need some additional check when to do parse request. 

2. @lucasmreis report suggest total crash of FSAC, which is weird and hard to diagnose

**Comment by Krzysztof-Cieslak** [comment]
Also, @lucasmreis, I think your issue is same as #313 rather than a problem reported by @teo-tsirpanis

**Comment by lucasmreis** [comment]
Ok, thanks @Krzysztof-Cieslak !

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.15.4`
