### ISSUE TITLE
FSI Improvements

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-vscode-fsharp#32]
Implement more FSI Commands :
- [ ] Interrupt
- [x] Reset

stop blocking the GUI thread
`while true do printf "bye"` will crash vscode

**Comment by bjornbaverfjord** [comment]
> while true do printf "bye" will crash vscode
This bug hit me again and it is very annoying when locks up and eats the unsaved source.

**Comment by isaacabraham** [comment]
There's already reset - in Code, it's known as fsi.Start. Adding the following keybinding to ``keybindings.json`` will do the trick: -

```json
{
   "key": "ctrl+alt+r",
   "command": "fsi.Start"
}
```

**Comment by colinbull** [comment]
I minor issue is that it always appends to the Output menu, 

![image](https://cloud.githubusercontent.com/assets/585546/17431547/7d84e984-5af2-11e6-845c-1b4b49c66354.png)

**Comment by isaacabraham** [comment]
@colinbull Yeah - that's the same as paket and fake commands too.

**Comment by Krzysztof-Cieslak** [comment]
I think I've already fixed it in Fake. Should be also easy fix for Paket and FSI

**Comment by Krzysztof-Cieslak** [comment]
Fixed problem with FSI output panels in `2.2.12`

**Comment by colinbull** [comment]
Nice... :)
