### ISSUE TITLE
Feature Request: Make auto-complete add attribute names without the "Attribute" suffix (if there is)

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#322]

**Comment by czifro** [comment]
I'm having the same issue:

![screenshot 2016-12-29 13 35 55](https://cloud.githubusercontent.com/assets/5378541/21555309/dd6fd10a-cdcb-11e6-8acf-94bef87310c5.png)

![screenshot 2016-12-29 13 36 11](https://cloud.githubusercontent.com/assets/5378541/21555315/ee9c64d4-cdcb-11e6-9cd7-39376ce5f0bd.png)

As you can see `Attribute` is not stripped. Could this be an FSAutoComplete problem?

**Comment by czifro** [comment]
I think the function in question is [FsAutoComplete Commands.Completion](https://github.com/ionide/FsAutoComplete/blob/master/src/FsAutoComplete.Core/Commands.fs#L171) ? 

/cc @cloudRoutine @Krzysztof-Cieslak

**Comment by Krzysztof-Cieslak** [comment]
I think changes for that should be made in FSharpComilerServices. I know similar feature was just added to VS2017, no idea if it will be ported to FCS.

**Comment by czifro** [comment]
I would be willing to try and fix it, but I may need some guidance. I am a little new to FCS.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.15.2`
