### ISSUE TITLE
Lint suggestion misses a bracket

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#326]
Not sure if this is a lint or Ionide error - happy to close if wrong place.

```fsharp
[ 1 .. 5]
|> List.map ((+) 1)
|> List.map ((*) 2)    
```

The above code is correctly given a lint fix. However, the fix does not compile: -

```fsharp
List.map ((+) 1) >> ((*) 2)) [ 1 .. 5]    
```

Note the missing opening bracket. In addition, I would have liked the use of the pipe to have stayed (although this is not critical).

**Comment by Krzysztof-Cieslak** [comment]
It should go to https://github.com/fsprojects/FSharpLint

**Comment by isaacabraham** [comment]
Created at https://github.com/fsprojects/FSharpLint/issues/198
