### ISSUE TITLE
Nothing works on Visual F# Tools repository

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#332]
Working on Visual F# Tools in Visual Studio is very hard due to 32-bit nature, huge codebase and blocking GC. I'm considering Ionide as an escape for editing the compiler / FCS parts of VFT. Unfortunately, after a short pause, no features work:

![image](https://cloud.githubusercontent.com/assets/873919/21798162/10b4adea-d724-11e6-88c7-1218a2c22704.png)

**Comment by Krzysztof-Cieslak** [comment]
Works for me on FCS solution

**Comment by vasily-kirichenko** [comment]
"works on my computer"
