### ISSUE TITLE
Syntax color for partially applied functions

### ISSUE THREAD

**Issue by jpierson** [ionide/ionide-vscode-fsharp#336]
When working with somebody yesterday day on an F# koan in VS I realized that one frustration we both have as we are picking up functional programming is picking up the types and function signatures by scanning code especially in places that use partial application. We both had similar problems initially in C# with the introduction of the `var` keyword until we adapted.

What I think may help is to provide a visual queue that a particular function is fully or only partially applied. Perhaps coloring or some other form of emphasis could be use to differentiate. Looking briefly through VS 2015 settings, resharper, and of course VSCode/Ionide but I haven't found anything that exists for this yet.

In order to more clearly express what I'm talking about I've mocked up a little example. Notice below how the partial application of `Seq.item`, `getRunLength` and `getRunLengthForShow` all have a slightly different color than the normal syntax?

![image](https://cloud.githubusercontent.com/assets/1467146/21960625/bc253246-dabf-11e6-8d98-7aa211d14fee.png)

Here is the raw code from the sample:

```f#
type Episode = { name:string; runLength:int }
type Show = { name:string; seasons:seq<seq<Episode>> }

let strangerThings = { 
    name = "Stranger Things"
    seasons = seq { 
        yield seq {
            yield { name = "Chapter One: The Vanishing of Will Byers"; runLength = 60 }
            yield { name = "Chapter Two: The Weirdo on Maple Street"; runLength = 60 }
            yield { name = "Chapter Three: Holly, Jolly"; runLength = 60 }
            yield { name = "Chapter Four: The Body"; runLength = 60 }
            yield { name = "Chapter Five: The Flea and the Acrobat"; runLength = 60 }
            yield { name = "Chapter Six: The Monster"; runLength = 60 }
            yield { name = "Chapter Seven: The Bathtub"; runLength = 60 }
            yield { name = "Chapter Eight: The Upside Down"; runLength = 60 }
        }
    }
}

let getRunLength show season episode = 
    let episode = 
        show.seasons
        |> Seq.item (season - 1)
        |> Seq.item (episode - 1)
    episode.runLength

let getRunLengthForStrangerThings =
    getRunLength strangerThings

let getRunLengthOfFirstEpisode show =
    let getRunLengthForShow = show |> getRunLength
    let getRunLengthForFirstSeason = getRunLengthForShow 1
    let getRunLengthForFirstEpisode = getRunLengthForFirstSeason 1
    
    getRunLengthForFirstEpisode
    
Dump <| getRunLengthOfFirstEpisode strangerThings
```

Slack conversations: 

* https://functionalprogramming.slack.com/archives/fsharp-beginners/p1484135647000438
* https://functionalprogramming.slack.com/archives/beginners/p1484136118000267

**Comment by jpierson** [comment]
Playing around a little more with _F# PowerTools_ in _Visual Studio 2015_ I noticed that there is the ability to assign a different background/foreground color to _F# Functions / Methods_ which I think helps a lot but doesn't go all to distinguish between fully saturated function applications and partial function applications.

![image](https://cloud.githubusercontent.com/assets/1467146/21987216/8f50a5e0-dbd0-11e6-9c70-e79ae2ee2f33.png)

**Comment by Krzysztof-Cieslak** [comment]
VFPT are using semantic highlighting using FCS. We can't do this since VSCode highlighting is RegEx based.

**Comment by jpierson** [comment]
@Krzysztof-Cieslak, thanks for your explanation. I followed up on the topic of semantic highlighting in https://github.com/ionide/ionide-atom-fsharp/issues/1 but haven't found anything to indicate current work to produce more intelligent highlighting mechanism for VSCode. If there is such an effort I would love to follow along and get involved.

**Comment by faldor20** [comment]
As of 2 days ago vscode now supports semantic syntax highlighting YAY!!. This should now be possible.
