### ISSUE TITLE
Feature request: implement goto definition for #load directives

### ISSUE THREAD

**Issue by smoothdeveloper** [ionide/ionide-vscode-fsharp#339]
It would be great to use F12 / Go to definition menu to open files pointed by `#load` directives.

The implementation was done in VFPT:

https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharp.Editing.VisualStudio/Navigation/GoToDefinitionFilter.fs#L36-L73 (integration in UI)

https://github.com/fsprojects/VisualFSharpPowerTools/blob/ed0903551a211cdff5c69bd099c51700a3aaa385/src/FSharp.Editing/Common/UntypedAstUtils.fs#L628-L727 (bulk of the logic)

https://github.com/fsprojects/VisualFSharpPowerTools/blob/03c613acd3aa67cb5e3a339d3dcf1c7c783f30c2/tests/FSharp.Editing.Tests/GoToDefinitionTests.LoadDirective.fs (tests)

I think FSharp.Editing project (with the logic) can be referenced without VS stuff if we want to keep a single codebase.

**Comment by realvictorprm** [comment]
Is this still valid?

**Comment by Krzysztof-Cieslak** [comment]
Yes

**Comment by realvictorprm** [comment]
Seems like a good point to start contributing. I'll try to get into it.

**Comment by vbfox** [comment]
A (hackish) version has been included from https://github.com/ionide/ionide-vscode-fsharp/pull/517
