### ISSUE TITLE
`F#: New Project` fails silently when no folder is open inside VS Code

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#345]
Windows 10: When calling 'F#: New Project' inside VS Code without a folder open, the operation appears to succeed, but no project is created.

Expected behaviour: a helpful error message.

**Comment by lilred** [comment]
Behaviour is slightly different in Ubuntu. The project is indeed created, in the user's home directory.

**Comment by Krzysztof-Cieslak** [comment]
Well, that's bad.
