### ISSUE TITLE
Problem Sending Code to F# Interactive

### ISSUE THREAD

**Issue by bytos** [ionide/ionide-vscode-fsharp#348]
When I press Alt+Enter to send selected F# code to F# Interactive terminal, a "Microsoft Visual C++ Runtime Library" dialog window appears.

The window has a disabled close button and have to terminate it in Task Manager. The window also has a white frame.

I can run Fsi.exe from the command prompt (system path) and these are my settings:

    "FSharp.toolsDirPath": "C:/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0",
    "FSharp.fsiFilePath": "C:/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0/Fsi.exe",

![s](https://cloud.githubusercontent.com/assets/16452541/22401403/2c9e8796-e5a8-11e6-9627-22d5ffa3f132.png)

- VSCode Version: 1.8.1
- OS Version: Windows 8.1
- Extension: Ionide 2.21.1

**Comment by Krzysztof-Cieslak** [comment]
It looks super wired... All we do is passing path to fsi to VSCode's Terminal API.

@Tyriar, any idea what should I investigate? (and sorry for pinging you on all those issues)

**Comment by Tyriar** [comment]
No idea what's going on there, there was no error message in the box?

Does it appear when you run `C:/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0/Fsi.exe` in cmd?

**Comment by bytos** [comment]
Solved it by setting "FSharp.legacyFSI": true.

**Comment by bytos** [comment]
Removed the ["FSharp.legacyFSI": true] setting in Code 1.9.0 and it is working fine now.

Maybe it was an issue with Code 1.8.1.
