### ISSUE TITLE
Paket fails during build 

### ISSUE THREAD

**Issue by vrotaru** [ionide/ionide-vscode-fsharp#35]
When I call `FAKE Build` from within VS Code it fails with 

```
Paket failed with:
	Fetching the git cache at C:\Users\user\.paket\git\db\ionide-vscode-helpers failed.
Message: Could not run "git clone git@github.com:ionide/ionide-vscode-helpers.git".
Error: 
Cloning into 'ionide-vscode-helpers'...
Permission denied (publickey).
```

**Comment by cloudRoutine** [comment]
You need to an ssh-agent running and your public key tied to your github account to clone using `git@github.com...`

https://help.github.com/articles/generating-an-ssh-key/

https://help.github.com/articles/error-permission-denied-publickey/

**Comment by vrotaru** [comment]
Thanks. Makes sense
