### ISSUE TITLE
warning FS0058: Possible incorrect indentation

### ISSUE THREAD

**Issue by vzkosov** [ionide/ionide-vscode-fsharp#352]
Linux Mint 18
VSC 1.9.0
Ionide 2.22.0
fsharpi 4.0
Every time I write some code, I get an error.
Even if I copy paste real working sample.
It may work on first attempt, but if I hit Alt Enter again (without any changes in code) - error occurs.
![image](https://cloud.githubusercontent.com/assets/25537623/22608077/b8283468-ea0f-11e6-91cd-95264bb51ab5.png)
But it works in fsharpi without any issues.

**Comment by reximus** [comment]
Its a bug.
That because of "?^?^?^?^?^?" symbols in terminal window.
Those symbols add automatically each time after pressing alt enter.
I have this issue also on my mac
OS X 10.11.6
VSC 1.9.0
Ionide 2.22.1
fsharpi 4.1

**Comment by Krzysztof-Cieslak** [comment]
This is problem on VSCode side. Please take a look at https://github.com/Microsoft/vscode/issues/19766
