### ISSUE TITLE
Inconsistent syntax highlighting: printf vs. printfn

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#354]
Repro:

create `test.fs`, and put the following code inside:

```
printf  ""
printfn ""
```

Expected behaviour: the quotes should have the same color

Actual behavior: 
![image](https://cloud.githubusercontent.com/assets/1834919/22621418/70de2814-eaf1-11e6-998b-2fc775263337.png)

`ionide-fsharp` 2.22.0, reproducible on OS X and Windows 10, VS Code stable and insiders.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.22.1`
