### ISSUE TITLE
Inconsistent syntax highlighting: destructuring let

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#355]
Repro:

create `test.fs`, and put the following code inside:

```
type T = C of int
let m = C 3
let (C n) = C 3
```

Expected behaviour: the `let` keywords should have the same color; `m` and `n` should have the same color.

Actual behavior: 
![image](https://cloud.githubusercontent.com/assets/1834919/22621959/c10190ea-eafd-11e6-90f1-81fac733e2b8.png)

`ionide-fsharp` 2.22.0, reproducible on OS X and Windows 10, VS Code stable and insiders.

**Comment by Krzysztof-Cieslak** [comment]
Please report problems with syntax highlighting in https://github.com/ionide/ionide-fsgrammar

**Comment by lilred** [comment]
See https://github.com/ionide/ionide-fsgrammar/issues/24
