### ISSUE TITLE
Send to Interactive adds extra characters after VSC 1.9.0

### ISSUE THREAD

**Issue by AndreasHassing** [ionide/ionide-vscode-fsharp#358]
After Visual Studio Code bumped to 1.9.0, sending FSharp code to FSI fails, as extra characters are added ('^?' a number of times).

This seems to occur only on *nix machines (Linux and OS X tested), and works correctly on Windows.

## How to reproduce (in VS Code)
1. Create a new `.fsx` file (`BugTest.fsx`)
2. Add code:
```fsharp
let sometest n =
    n + 5;;

sometest 3;;
```
3. Press `Cmd+Shift+P`, type in `>fsi: send file` and press `Enter`
4. Do step 3. again
4. ![image](https://cloud.githubusercontent.com/assets/639843/22691559/57313446-ed3b-11e6-8d7f-8f9d1c0e115a.png)

## My versions
| Product                   | Version |
|--------------------|---------|
| Visual Studio Code | 1.9.0     |
| ionide-fsharp          | 2.22.1   |

**Comment by Krzysztof-Cieslak** [comment]
Reproduce of  #352

**Comment by AndreasHassing** [comment]
Ah, sorry @Krzysztof-Cieslak, looked for the issue but couldn't find it :). Thanks!
