### ISSUE TITLE
Can't scroll in FSI with mouse wheel until I resize the integrated terminal window.

### ISSUE THREAD

**Issue by stevenranney** [ionide/ionide-vscode-fsharp#359]
When I send lines to FSI with `alt+enter` there is no scroll bar and I cannot scroll up or down with my mousewheel.  I can scroll with `ctrl+up/down`.  When I resize the FSI window, the scroll bar appears and I can then scroll with my mousewheel.

[Screenshot gif here.](http://i.imgur.com/fNMGjlV.gifv)

I updated to ionide-fsharp `2.22.1` this morning but this problem existed yesterday, too.  I am using `FSI.exe 4.0` on Windows 7 and VSCode `v1.9.1`

**Comment by cloudRoutine** [comment]
Is this the case for FSI only or does it happen with other integrated terminals as well? 
Does it happen in the integrated terminal when Ionide isn't installed?
If it does it's probably a vscode issue and you should report it @ https://github.com/Microsoft/vscode/issues

**Comment by Krzysztof-Cieslak** [comment]
CC: @Tyriar

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/Microsoft/vscode/issues/20505

Thanks for the report :smiley:

**Comment by Krzysztof-Cieslak** [comment]
Thanks, closing it here.
