### ISSUE TITLE
Broken type reporting, error reporting since 2.22.2

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#363]
Users are not getting parsing errors, types on their declarations.

![16735630_10210393713014951_696462366_o](https://cloud.githubusercontent.com/assets/1834919/22892665/616182b8-f1e1-11e6-823e-ee61af3de3c3.png)
![16735500_10210393662173680_116299856_o](https://cloud.githubusercontent.com/assets/1834919/22892666/6164478c-f1e1-11e6-9a6f-dcb1d3f7f26d.png)

_________________

Seen on all major platforms, with VS Code 1.8.1, 1.9.1, 1.10-insiders. Probably a regression in 2.22.2, though for some people it doesn't break anything.

**Comment by lilred** [comment]
@pepoandra and @delexi report having the same issues. Interesting that @pepoandra reports having this issue with VS Code 1.8.1.

**Comment by alexboii** [comment]
I can confirm I'm having the same issue as well.

**Comment by pepoandra** [comment]
I started having the problem when updated ionide 2.21.1 to 2.22.1 with VSC 1.81.
Updated to VSC 1.9.1 didnt solve it.

**Comment by lilred** [comment]
The change from 2.22.1 to 2.22.2 is just an upgrade of FSAC. There's probably a bug or a breaking change in the new version of FSAC.

**Comment by Krzysztof-Cieslak** [comment]
Well, I can't reproduce it... is there anything common for the cases it breaks? OS, mono version? Anything? ;)

**Comment by lilred** [comment]
I can't reproduce it either, and I can't seem to find any commonalities ;_; IIRC we've seen this issue on Ubuntu 16.04, Windows 10, and the latest OS X. I'll point the students to this issue in case they want to chime in with their particular setups.

**Comment by alexboii** [comment]
Seen on Fedora 25 & Windows 10 from my side.

**Comment by pepoandra** [comment]
vscode Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
ionide 2.22.1
ubuntu 16.04

started when updated ionide from 2.21.1 to 2.22.1

**Comment by Krzysztof-Cieslak** [comment]
Can you try updating to latest? In meantime, there were couple of fixes in FCS and maybe it got fixed too.

**Comment by lilred** [comment]
I found a machine I could reproduce this issue on, upgraded from 2.22.2 to 2.23.5, and then I could not reproduce anymore.

So that's encouraging. I'd love to hear from @pepoandra, @alexboii or @delexi on this.

**Comment by alexboii** [comment]
I upgraded to 2.23.5 and the issue has now disappeared on 4.9.10-200.fc25.x86_64 (Fedora 25).

**Comment by pepoandra** [comment]
Upgrated to 2.23.5 on ubuntu 16.04, issue is gone. 
Thank you.
