### ISSUE TITLE
Arrow symbol was broken in font with ligatures (FiraCode)

### ISSUE THREAD

**Issue by CompleteBrains** [ionide/ionide-vscode-fsharp#364]
Main reason to use `VSCode` over `VS` for me was that former displays fonts with ligatures better (`FiraCode` v1.204).
But some time ago (1 or 2 months) one of the most lovely symbols was suddenly broken here too:
![image](https://cloud.githubusercontent.com/assets/5301844/22922215/64715af4-f2a5-11e6-99f4-d05dee56ec0a.png)
To return back previous beauty I need to use a workaround with parenthess, but this is the exact thing which I really don't like:
![image](https://cloud.githubusercontent.com/assets/5301844/22922253/9b91af02-f2a5-11e6-84d9-76d24206f390.png)
In other places everything is ok:
![image](https://cloud.githubusercontent.com/assets/5301844/22922605/24016bec-f2a7-11e6-99ca-e20b5611f722.png)
Also, with two symbols it displays correctly:
![image](https://cloud.githubusercontent.com/assets/5301844/22922527/cdd56eee-f2a6-11e6-9394-639c3d561f3e.png)
If commented it looks better, but it's too cruel alternative:
![image](https://cloud.githubusercontent.com/assets/5301844/22922780/bf1498d4-f2a7-11e6-844f-34bd1c4b0bc8.png)
The rest symbols are ok too:
![image](https://cloud.githubusercontent.com/assets/5301844/22922807/d2ccc3d8-f2a7-11e6-8dd0-aa2357fbda13.png)

**Comment by CompleteBrains** [comment]
I decided to report the issue here because the only place it's broken is the lambda functions. 
So I've concluded it dependeds on syntax or compiler of `F#`, not some common `VSCode` infrastructure.

**Comment by Krzysztof-Cieslak** [comment]
Reported in https://github.com/ionide/ionide-fsgrammar/issues/27

**Comment by CompleteBrains** [comment]
@Krzysztof-Cieslak Thank you.
