### ISSUE TITLE
Expecto runner no longer works with Expecto 4

### ISSUE THREAD

**Issue by rmunn** [ionide/ionide-vscode-fsharp#367]
I created a new project copied from ProjectScaffold, and adjusted it to run tests with Expecto instead of NUnit. Since I didn't specify a version for the Expecto packages, Paket automatically grabbed Expecto version 4, which has just been released. But when I go to run Expecto tests within VS Code, or use the new Watch mode, I get the error "ERROR unknown options: ". There's nothing after the colon except a single space, followed by a newline. If I downgrade the Expecto dependencies (Expecto, Expecto.BenchmarkDotNot, and Expecto.FsCheck) in my `paket.dependencies` to version 3 by adding `~> 3` after each of them, then running a Paket update, then I can run Expecto tests within VS Code without any problems.

So Expecto version 3 works, but version 4 is giving me an error I can't (yet) track down when I try to run tests from within VS Code.

This is with VS Code 1.9.1, Ionide-fsharp 2.23.0, on Linux Mint Debian Edition (based on Debian Jessie).

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `2.23.5` and latest Expecto
