### ISSUE TITLE
Ionide is a zombie

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#374]
<img width="954" alt="screen shot 2017-02-25 at 08 12 12" src="https://cloud.githubusercontent.com/assets/193115/23329154/2768613a-fb32-11e6-97ca-f5a5b7ef5725.png">

VSCode isn't running.

**Comment by Krzysztof-Cieslak** [comment]
Is it something that's reproducible for you? I can't repro neither on Windows machine nor OSX VM.

**Comment by haf** [comment]
Happens every other day. I tend to close vscode a lot, approximately 10 times an hour, because the intellisense freezes, and sometimes when doing that the process lingers and drains my battery.

**Comment by haf** [comment]
Happened today

```
h                60748   2.1  0.4  2666572  64176   ??  S     7:28PM   0:28.50 mono /Users/h/.vscode/extensions/Ionide.Ionide-Paket-1.6.3/bin/paket.exe find-packages
h                 4945   0.0  0.1  2632792  15948   ??  S    Sun08PM   0:56.96 mono /Users/h/.vscode/extensions/Ionide.Ionide-Paket-1.6.3/bin/paket.exe find-packages
h                95868   0.0  0.1  2630604  16608   ??  S    Sun07PM   6:06.23 mono /Users/h/.vscode/extensions/Ionide.Ionide-Paket-1.6.3/bin/paket.exe find-packages
h                37742   0.0  0.0  2434840    796 s000  S+   11:24AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn mono
```

**Comment by rmunn** [comment]
I have seen this too. I don't have a good reproduction yet, but on my Linux Mint desktop where I've been doing a lot of F# work recently, I noticed high memory usage and ran a `ps auxw` to see what was going on. Most of it was having too many Chrome tabs open, but I also noticed several occurrences of `mono`, most of them Ionide. Here's my most recent run of `ps auxw | grep mono` (with the `ps` header added for clarity):

```plaintext
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
rmunn     3865  0.0  0.0 564600  1100 ?        Sl   May07   0:00 mono /home/rmunn/.vscode/extensions/Ionide.ionide-fsharp-2.25.11/bin/FsAutoComplete.Suave.exe 8464
rmunn     7784  0.2  0.1 1280556 15344 ?       Sl   Apr03 200:55 mono /home/rmunn/.vscode/extensions/Ionide.Ionide-Paket-1.6.3/bin/paket.exe find-packages
rmunn    12294  0.0  0.0  12732  2072 pts/0    S+   12:34   0:00 grep --colour=auto mono
rmunn    14668  0.0  0.1 470088 14444 pts/6    Sl+  Apr17   7:30 /usr/bin/mono /usr/lib/mono/fsharp/fsi.exe --exename:fsharpi
rmunn    16282  1.1  0.2 1592404 30412 ?       Sl   May23  73:04 mono /home/rmunn/.vscode/extensions/Ionide.Ionide-Paket-1.6.3/bin/paket.exe find-packages
rmunn    16384  0.1  0.1 1683032 15912 ?       Sl   Apr17  94:19 mono /home/rmunn/.vscode/extensions/Ionide.Ionide-Paket-1.6.3/bin/paket.exe find-packages
rmunn    24269  1.7  0.4 1890488 54644 ?       Sl   Apr11 1180:51 mono /home/rmunn/.vscode/extensions/Ionide.Ionide-Paket-1.6.3/bin/paket.exe find-packages
```

Between @haf's bug report from April 18 and mine, it looks like the Ionide-Paket extension is the most likely one to not terminate properly when VS Code is closed.

I can't tell you precisely what I was doing on April 3rd, or 11th, or 17th when I closed VS Code, so this won't be the most useful bug report for tracking down the problem -- but if I notice more details, I'll add them.

**Comment by Krzysztof-Cieslak** [comment]
This looks weird - Code should kill all any child process when it's closed (just like any node.js process does). I wonder if problem is not somewhere on paket side - maybe it has something that "locks" the process and makes it not responding to normal kill signals.

**Comment by enricosada** [comment]
added PR https://github.com/fsharp/FsAutoComplete/issues/190 to fix this.
I get some zombies too from time to time.

**Comment by Krzysztof-Cieslak** [comment]
From the `ps` infos shown by @rmunn and @haf it looks like that FSAC is not a problem here, but rather Paket
