### ISSUE TITLE
New projects lack System.Runtime

### ISSUE THREAD

**Issue by nestordemeure** [ionide/ionide-vscode-fsharp#375]
I am using vsCode on an Ubuntu with mono. I noticed (roughly two weeks ago) that when I create a new project, it lacks System.Runtime. Meaning that any `open System` or `let rng = System.Random()` (etc) will raise an error at compile time : 
`The type 'ValueType' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Here is the associated [fsproj](https://github.com/ionide/ionide-vscode-fsharp/files/801394/Myproj.fsproj.txt), it is the project file created by default (with `f1 / F# : new project / console / myproj / Myproj`) without any modification (I added a .txt so that GitHub would let me upload it).

My current fix is to add System.Runtime.dll at the root of the project and in the fsproj's references but it is a fix, not a solution.

**Comment by Krzysztof-Cieslak** [comment]
fsproj templates are provided by Forge - https://github.com/fsharp-editing/Forge, please report issue over there
