### ISSUE TITLE
Ionide build failure: Fable not found

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#380]
See [here](https://gist.github.com/lilred/8fc2f6f21031c9872bb7c80b0a06ef72#file-ionide_build-log-L683)

Windows 10 Insiders, VS Code 1.9.1, latest ionide (commit [3d13495](https://github.com/ionide/ionide-vscode-fsharp/commit/3d1349528f238ecc11772d8e645bf1459a788465))

**Comment by Krzysztof-Cieslak** [comment]
Do you have fable installed globally? (`npm install -g fable-compiler`)

**Comment by lilred** [comment]
I didn't! If that's required, maybe add it to [the instructions](https://github.com/ionide/ionide-vscode-fsharp#how-to-contribute)?

I just installed it and now I fail with the following error:

"Fable.Core 0.7.28 required, please upgrade the project reference"

I'm guessing I should downgrade my installed Fable to 0.7.28?

**Comment by lilred** [comment]
I downgraded to 0.7.28, and it asked me for 0.7.20. I downgraded to 0.7.20, and it asked me for 0.7.15. Something strange is going on 🤔

**Comment by Krzysztof-Cieslak** [comment]
Actually.... I **believe** that global installation shouldn't be necessary.  We define fable as `devDependency` in `package.json` - https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L423

Go to `release` folder, delete `node_modules` and try to run `npm install` in it. After that check if there exists `node_modules\.bin\fable` file

**Comment by lilred** [comment]
That fixed it, thanks.
