### ISSUE TITLE
Editor freezes while compiling

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#382]
Start a sufficiently large F# project.

Start editing.

Start a xbuild session in the background, compiling the solution.

Watch the editing capabilities of VSCode freeze; you can't navigate with `h, j, k, l` or change text or do anything until the compilation is done. Sometimes the cursor agrees to a single action, like writing a character.

The debug output doesn't contain any information about the freeze (nothing is printed meanwhile)

**Comment by Krzysztof-Cieslak** [comment]
Do you start `xbuild` using Ionide (`MsBuild` commands) ?

I don't see how this is Ionide issue, we're not responsible for navigation or text editing... maybe xbuild is using 100% CPU or something weird happens?

**Comment by haf** [comment]
No, I run it in the background/a terminal.

The 8 cores are not close to saturated.

I don't see how it can be anything but, since it only happens when F# is being compiled. Why would not other type of compiler trigger the same problems?

**Comment by Krzysztof-Cieslak** [comment]
Can you try reproducing behavior with Ionide disabled?

**Comment by haf** [comment]
Yes, I just tried. The editor is really smooth when disabling ionide-fsharp and doesn't freeze.

**Comment by baronfel** [comment]
re: the msbuild integration - it actually doesn't work on non-Windows ATM, which should be addressed in #390.

**Comment by haf** [comment]
I can share a screen if that helps?

**Comment by haf** [comment]
I've created a bug report in the main repo https://github.com/Microsoft/vscode/issues/25183 because it's not necessarily this issue.

**Comment by haf** [comment]
I've only ever seen this in the F# extension of vscode. Any pointers on how it can be debugged?

**Comment by haf** [comment]
<img width="519" alt="screen shot 2017-05-12 at 17 30 17" src="https://cloud.githubusercontent.com/assets/193115/26005228/b807d0c6-3738-11e7-84a7-e0548fe23b80.png">

This is displayed in the log

**Comment by Krzysztof-Cieslak** [comment]
Can you please try `2.25.13` ? I think I found one place with crazy CPU leak [file watcher watching on *any* file change in opened workspace] which I think could cause this problem.

(But don't expect much, it's kind of blind shot ;) )
