### ISSUE TITLE
FSI repl not working on mac

### ISSUE THREAD

**Issue by t3dodson** [ionide/ionide-vscode-fsharp#383]
I cannot identify what keyboard shortcut should be sending the code to the repl

F1 -> fsi doesn't show the command either.

I have fsharp installed.

I tried creating symlinks which are in the path

    bash-3.2$ which fsc
    /usr/local/bin/fsc
    bash-3.2$ which fsharpc
    /Library/Frameworks/Mono.framework/Versions/Current/Commands/fsharpc 
    bash-3.2$ which fsi
    /usr/local/bin/fsi
    bash-3.2$ which fsi
    /usr/local/bin/fsi
    bash-3.2$ echo $PATH
    /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands

**Comment by smoothdeveloper** [comment]
@t3dodson not sure but `fsi` doesn't ship with dotnet core yet, on mac you should search for `fsharpi` which comes with mono.

**Comment by t3dodson** [comment]
Sorry I had a typo in my command output. fsharpi is on my machine.

I've searched in the vscode command window for both "fsi" and "fsharpi" but nothing happens.
