### ISSUE TITLE
Can't add files to project after all files have been removed

### ISSUE THREAD

**Issue by psfblair** [ionide/ionide-vscode-fsharp#385]
I'm using Ionide 2.23.7 on VS Code 1.10.1 (on macOS Sierra). 

I notice when I create a new F# class lib project and then remove the ProjectName.fs and Script.fsx files from it, I can't then add new files to the project. There's an empty <ItemGroup /> tag in the .fsproj file that apparently can't any longer have entries added to it.

**Comment by Krzysztof-Cieslak** [comment]
It's problem with [Forge](https://github.com/fsharp-editing/Forge) please report it there
