### ISSUE TITLE
"Namespace not defined" issues

### ISSUE THREAD

**Issue by psfblair** [ionide/ionide-vscode-fsharp#386]
I have a project containing two modules, each in its own file; one depends on the other. The project builds with FAKE, and the order in the .fsproj file is correct.

However, I'm still getting red squigglys and errors from Ionide:

![ionidenamespaceissue](https://cloud.githubusercontent.com/assets/176193/23540591/289a6ed6-ffb0-11e6-8710-dbf2d144f8b1.jpeg)

Ideas?

**Comment by Krzysztof-Cieslak** [comment]
Can you try running Project Cracker on your `fsproj` file? `FSharp.Compiler.Service.ProjectCrackerTool.exe --text <path to>/console.fsproj true`. `FSharp.Compiler.Service.ProjectCrackerTool.exe` is present in extension installation folder in `bin` directory.

**Comment by psfblair** [comment]
Unfortunately, this stopped happening after a certain point and I'm not sure why.  I suppose I should just close the issue...?
