### ISSUE TITLE
CodeLense Stopped Working

### ISSUE THREAD

**Issue by bytos** [ionide/ionide-vscode-fsharp#391]
Only using VSCode (updated) and Ionide (updated) on Win8.1.

I noticed recently and the only thing that has changed is the latest updates to both.

Checked settings and it is active. Working with .fs and .fsx files.

**Comment by adam-becker** [comment]
I don't know if it's related but I have an issue with `2.25.2` where CodeLens stops working. To reproduce it, just open a file with a single module that has a lot of functions and delete all but one of the functions. Intellisense appears to be working still, but CodeLens disappears. If I undo the deletion then CodeLens returns. It returns if I close and reopen the file also.

**Comment by bytos** [comment]
Did a fresh install of everything and tried what you suggested, but saw no difference.

**Comment by bytos** [comment]
CodeLens is working again after upgrading to Ionide 2.25.7.
