### ISSUE TITLE
Intellisense is broken after literals.

### ISSUE THREAD

**Issue by OnurGumus** [ionide/ionide-vscode-fsharp#395]
If you type: 
`1.  
`
You see all classes instead of integer members.
Similarly typing:
`"aaa".`
Shows all classes. For string literal case pressing  backspace and pressing dot again fixes the issue.

**Comment by Krzysztof-Cieslak** [comment]
Known problem in FSAC, reported in https://github.com/fsharp/FsAutoComplete/issues/120

**Comment by OnurGumus** [comment]
Yes sorry for missing it though in my case it also doesn't work for string literals too.
