### ISSUE TITLE
Notify restore is required, for new fsproj

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#396]
new fsproj require the project is restored (just a `dotnet restore`), until then the intellisense doesnt work.

This can be a bit annoying for users, because doesnt know about it.
Also this can take a bit of time (if multiple p2p references to navigate it), so a progress somewhere should be shown maybe (just a "initializing f# in progress...")

For example, c# notify users, proposing to restore it.

![image](https://cloud.githubusercontent.com/assets/147243/24084828/c2cc18b2-0cf1-11e7-95c3-eacfc5b27439.png)

As a note, this special error case in FSAC atm (ionide 2.25.1) is just a normal failure with error (so cannot be distinguished), but i can make it special (dunno what is the best way to do that in FSAC)

**Comment by enricosada** [comment]
@Krzysztof-Cieslak what's the best way for this?

return a specific error (code? message?) from FSAC, and use that for show info notification?
Do you have an already implemented code i can use as example?

**Comment by adamchester** [comment]
It would be nice if this message was pushed from FSAC, because in the future we want to show this same message whenever the `fsproj` is modified (and a restore is required again).

**Comment by enricosada** [comment]
We can use a standard message with that error (but awesome is the button to call restore, so is ide specific)

The `dotnet restore` shouldn't ben called always if fsproj changes, maybe you just change a property. 
Atm the user know when do it (maybe there is a warning but cannot check now)

**Comment by adamchester** [comment]
@enricosada I was not suggesting the *text* of the message should come from FSAC. What I meant was that, ideally, FSAC should be the component that notifies the editor when a `dotnet restore` might be required. I also was not suggesting that *all* modifications to the `fsproj` should cause the restore message.

If you try Omnisharp, you will see what I mean. Here, I am editing the `csproj` directly. When I modify  the package references, Omnisharp tells the VSCode to display this message, allowing me to restore with a simple single click:
![image](https://cloud.githubusercontent.com/assets/570470/24131942/6567bec2-0e3d-11e7-8aed-fea8b3e5eb4c.png)

The important thing is that the language service is *pushing* this message to the IDE/Editor.

**Comment by enricosada** [comment]
> The important thing is that the language service is pushing this message to the IDE/Editor

@Krzysztof-Cieslak @rneatherway something like that already exists in FSAC?

**Comment by adamchester** [comment]
I thought there was a websocket thing some time back that allowed events to push from FSAC.

Anyway, if the "push from FSAC" thing is too complicated, it would still be a big improvement to detect and a run `dotnet restore` on a new proj as you originally suggested.

**Comment by Krzysztof-Cieslak** [comment]
How should I detect that restore is required?

**Comment by enricosada** [comment]
It's enough to check if `obj/project.assets.json` exists

**Comment by enricosada** [comment]
The almighty project.lock.json renamed :)
It's a temp file, but created for both all (nuget/paket/fable)

**Comment by cloudRoutine** [comment]
btw the default setting for VS is to automatically run nuget restore when a project/sln is loaded with missing or out-of-date packages, but this can be disabled.

> The dotnet restore shouldn't ben called always if fsproj changes, maybe you just change a property.

as long as it's called before build. we should also clean the `/obj/` dir before restore, this doesn't happen automatically but it really should. detritus in the `/obj/` dir can break builds in weird ways

**Comment by enricosada** [comment]
will be fixed by #455 , with autorestore option too

**Comment by Krzysztof-Cieslak** [comment]
Automatic restore added by 3.14
