### ISSUE TITLE
Ask users if need build/debug assets

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#397]
Some assets are useful to have:

- build: `.vscode/tasks.json` (template `.NET Core` is ok)
- debug/launch: `.vscode/launch.json` (template `.NET Core` is ok)

Atm VSCode ask for these when starting a debug (F5), but this is not optiomal

- three F5 are required (F5 -> create launch.json -> F5 -> create tasks.json -> F5)
- user maybe doesnt know what to choose (msbuild task? netcore task?)
- the launch.json create is the default template, so some info need to be updated (targetconfiguraion and app name).

If possible should be nice to have it created after vscode open, or after FSAC is initialized.
C# for example, ask users

![image](https://cloud.githubusercontent.com/assets/147243/24084893/acbcfb94-0cf2-11e7-960a-9888ff8c8d05.png)

after the template are generated, should be update with correct info about where path are (for example find console app, and set the `.dll` as `configurations.program`

**Comment by Krzysztof-Cieslak** [comment]
Some changes to task system in VSCode are coming (https://github.com/Microsoft/vscode/issues/22069) which should make this (partially) unnecessery / solvable differently. I'll wait with any decisions until it's officially released
