### ISSUE TITLE
The extension does not start unless *.fs file is opened

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#399]
Ionide starts only opening a `.fs` (or `.fsx`, `.fsi`) file

repro:

```
dotnet new console -lang f# -n app
cd app
code .
```

=> ionide doesnt start

open `app.fsproj` => ionide doesnt start

open `Program.fs` => ionide starts 🎉 

ref https://github.com/Microsoft/vscode/issues/944

**Comment by Krzysztof-Cieslak** [comment]
Latest version includes new activation events that can be used for this - https://code.visualstudio.com/updates/v1_13#_glob-patterns-for-workspacecontains-activation-event
