### ISSUE TITLE
Wrong colorization of `internal` keyword

### ISSUE THREAD

**Issue by maestrow** [ionide/ionide-vscode-fsharp#400]
`internal` keyword highlited like an identifier, not like keyword. 

**Expected**: `internal` keyword highlided like `private`

![image](https://cloud.githubusercontent.com/assets/671853/24321873/5507dfe8-1168-11e7-861d-a72508dccc14.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.25.6`
