### ISSUE TITLE
Intellisense shows everything

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#402]
Dotting into `123` below shows basically everything from intellisense. However, if you dot into `x` then it shows the correct items.

```fsharp
let x = 123
```

No errors are emitted into the developer mode log.

**Comment by Krzysztof-Cieslak** [comment]
This issue was reported before in FSAC - https://github.com/fsharp/FsAutoComplete/issues/120 ;-)

**Comment by isaacabraham** [comment]
Ooops :-)
