### ISSUE TITLE
Not finding modules in other files in .net core

### ISSUE THREAD

**Issue by Kurren123** [ionide/ionide-vscode-fsharp#403]
- dotnet 1.0.1
- ionide 2.25.7
- Windows 10
- [Repository that I'm getting the bug on](https://github.com/Kurren123/IionideBug1)

I made this repository by running the following:

```
dotnet new sln
mkdir project1
dotnet new classlib -lang f# -o .\project1\
dotnet sln add .\project1\project1.fsproj
```

I add a file which references the one already added and add the entry into the fsproj as shown [here](https://github.com/Kurren123/IionideBug1/blob/master/project1/project1.fsproj). I then `dotnet restore` and `dotnet build`. It builds fine.

The second file I added however can't find the reference to the first:

![image](https://cloud.githubusercontent.com/assets/3525980/24583164/43df7f88-1739-11e7-8185-1596e9a71e52.png)

**Comment by Krzysztof-Cieslak** [comment]
It's known bug in underlying tooling we use that's happening due to space in your windows username. The workaround is suggested here https://github.com/ionide/ionide-vscode-fsharp/issues/398#issuecomment-290362515. Hopefully @enricosada will fix it soon.

**Comment by Kurren123** [comment]
Thank you. Is there an issue in F# SDK to track this?

**Comment by enricosada** [comment]
@Kurren123 https://github.com/fsharp/FsAutoComplete/issues/152

**Comment by Kurren123** [comment]
@enricosada looks like that issue has been fixed now, however this bug is still there

**Comment by Kurren123** [comment]
I see now, the changes have been pushed to this repo and will be there on the next release. Thanks!
