### ISSUE TITLE
Signature File shows compilation errors but build passes

### ISSUE THREAD

**Issue by Stefanpu13** [ionide/ionide-vscode-fsharp#404]
Hi, I found the following issue: Building a FsUnit project that contains signature file is successful but there are compile time errors in signature file.

1. Create new FsUnit project in VS Code
2. Add a "fsi" file.
3. Import signature and implementation from [here](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/signatures)
4. Add fsi file to fsproj file 
5. run build command

Ionide-Fsharp version is 2.25.7
Am I correct that this is an error or I am missing something?
Thanks.

![fsharpsignaturefile](https://cloud.githubusercontent.com/assets/2702308/24676933/a0ad6e86-198d-11e7-843c-2b5b25341ddd.PNG)

**Comment by Krzysztof-Cieslak** [comment]
This is solved by putting `.fsi` file before `.fs` file in `fsporj`
