### ISSUE TITLE
Consider integrating .NET Core Debugger

### ISSUE THREAD

**Issue by lambdakris** [ionide/ionide-vscode-fsharp#405]
Would it make sense to integrate the .NET Core Debugger into Ionide? Doing so would remove the need for users to install the OmniSharp C# extension in order to be able to use the .NET Core Debugger. To start with at least, the [omnisharp-vscode package.json file](https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L152) contains the urls to the debuggers for the supported platforms.

**Comment by lambdakris** [comment]
I went ahead and opened https://github.com/OmniSharp/omnisharp-vscode/issues/1364 in the OmniSharp vs code repo to float the idea there too. Please check that issue out if you have interest in this idea.

**Comment by ctaggart** [comment]
If the .NET Core [Debugger enables source link support](https://github.com/OmniSharp/omnisharp-vscode/issues/373), this would be a great feature to have.

**Comment by enricosada** [comment]
@Krzysztof-Cieslak do you think there is an easy way (on ionide init maybe, or before FSAC init) to check if that package is installed? just to give a meaningfull error message
