### ISSUE TITLE
unable to use the extension with fs version 4.1.

### ISSUE THREAD

**Issue by tensor-programming** [ionide/ionide-vscode-fsharp#407]
When I try to start the server or send any code to the fsi, I get an error along the lines of; `FsiAnyCpu.exe --fsi-server-input-codepage:65001` failed to launch`.

Is this because FS 4.1 is not supported? I went to the experimental branch of FS because it includes better support in Visual Studio.  

I am on windows 10 and am running from the visual studio 2017 build.

**Comment by 2moveit** [comment]
I know I had the same issue but on Windows 7. I'm not sure but if I remember it correctly it was a wrong path in the PATH system variable. Can you check if your PATH variable is set correctly, please?
On the [getting started page](https://github.com/ionide/ionide-vscode-fsharp) the directories are for 4.0. For 4.1 you need
`C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0`

**Comment by mizzle-mo** [comment]
I had the same issue on Windows 10

**Comment by 2moveit** [comment]
I reproduced it what I said before. @tensor-programming  and @mizzle-mo please check you PATH system var. I just added `c:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\;C:\Program Files\Microsoft SDKs\F#\4.0\Framework\v4.0\` (depending on your installed SDKs), restart vscode and it will work.

**Comment by celsojr** [comment]
@tensor-programming I had the same problem. I believe you must have the version 4.0 installed as well. With only the 4.1 version it won't be able to find the folder now. I tried to make the fix, but as I could not test on my local PC yet I did not send the PR. Look at this:
https://github.com/ionide/ionide-vscode-fsharp/blob/4e6b0f9467d2368c16fb5369f36512d5c528749e/src/Components/LegacyFsi.fs#L29
https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/Environment.fs#L49

**Comment by Krzysztof-Cieslak** [comment]
You can either set PATH to correct installation locations or use `FSharp.toolsDirPath` and `FSharp.fsiFilePath` settings.
