### ISSUE TITLE
Debug xunit tests

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#408]
I don't think it is possible to debug .NET Core xunit tests from VS Code at the moment with the Ionide extension. Would it be possible to add a similar [functionality like OmniSharp](https://github.com/OmniSharp/omnisharp-vscode/pull/382) has it?

**Comment by Krzysztof-Cieslak** [comment]
We don't support debugger at all. All debugging capabilities are provided by Omnisharp extension
