### ISSUE TITLE
long running autocomplete

### ISSUE THREAD

**Issue by mawasak** [ionide/ionide-vscode-fsharp#409]
Hi,
When I try to use autocomplete on classes from http://accord-framework.net/ it takes a lot of time to show properties/methods. I don't try it or all classess but MulticlassSupportVectorMachine take about 2-3 minutes. Another long running class is SequentialMinimalOptimization<Gaussian>. 
I have to admit that I also try use VS 2015 and it hang in infinity.... so maybe there is hope to make it work in ionide:)

Regards,
Mariusz
![autocomplete](https://cloud.githubusercontent.com/assets/1379060/25066258/819b13c6-2221-11e7-8495-b7ab56855559.png)

**Comment by Krzysztof-Cieslak** [comment]
Please report problem in https://github.com/fsharp/FsAutoComplete
