### ISSUE TITLE
Wrong method call coloring

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#410]
![image](https://cloud.githubusercontent.com/assets/873919/25070144/9ffbb2da-229e-11e7-803c-b972d6f921a8.png)

**Comment by czifro** [comment]
I have seen this, often when passing a record as an arg to a function/method. I wonder if it thinks its an `async`,`promise`,etc. builder? Here's another pic: 

![screenshot 2017-05-08 16 56 00](https://cloud.githubusercontent.com/assets/5378541/25830106/7d025324-340f-11e7-8c2b-749b32d608c2.png)

**Comment by vasily-kirichenko** [comment]
Ionide uses a bunch of regexes to highlight code, so there is no way to distinguish comp expressions from function calls where a record construction is passed.

**Comment by czifro** [comment]
I checked Xamarin, and it doesn't appear to be an issue there. Surely it is possible to fix here?

**Comment by vasily-kirichenko** [comment]
No, it's impossible.

**Comment by vasily-kirichenko** [comment]
Code is a very simple editor and it does not allow plugin authors to color symbols arbitrary.

**Comment by czifro** [comment]
Well that is a bummer 😞 . Good to know though about VSCode. Thanks for the insight.
