### ISSUE TITLE
UX of parentheses matching, swallowing.

### ISSUE THREAD

**Issue by raould** [ionide/ionide-vscode-fsharp#411]
(similar to https://discuss.atom.io/t/how-to-stop-atom-from-auto-closing-and-swallowing-braces-and-quotes/2566/20)

I often write code outside-in, and add () inside already existing (), or add () inside a line of code that so far only has one open paren at the start, etc. etc., various variations,

So it is confusing and frustrating to me that (I am guessing it is Ionide, not just VSCode itself? I dunno.) the close paren I type sometimes doesn't get added, but rather an already existing close paren is used in its place, leaving me off by one in terms of the # of paren I literally typed on the keyboard vs. what ends up in the buffer.

```
(foo^) (* ^ represents the text caret. *)
(foo(^) (* just typed an open paren because i want (foo()). *)
(foo()^) (* expected. *)
(foo()^ (* actual: it re-used the existing paren instead of inserting the one i just typed. *)
```

Is there a way for me to disable the auto-paren-stuff? Might this behaviour be something that can be "fixed" (from my perspective)?

thank you.
Linux Ubuntu 16.04 LTS 64 bit
VSCode 1.11.12
Ionide-fsharp 2.25.9

**Comment by Krzysztof-Cieslak** [comment]
The behavior of paren autocomplete is controlled by VSCode, all we do is defining which characters are treated as parens
