### ISSUE TITLE
Improve discoverability of logs

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#415]
Atm if someone want to diagnose FSAC related stuff, need to enable log to see the panel (it's hidden by default)

The instruction how to do so are clear and easy to follow https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting but hard to discover (i got multiple requests about where are logs)

![image](https://cloud.githubusercontent.com/assets/147243/25235202/c4838396-25e4-11e7-8bdf-fedbf33b8743.png)

So adding a command `Ionide: Show Ionide Extensions Logs` to add config and enable this panel

![image](https://cloud.githubusercontent.com/assets/147243/25235029/36466008-25e4-11e7-9fc9-ad40a9b3f448.png)

I dont know is is easy/medium/hard to show better the error/info messages in the panel.
Something like

```
[info]: initializing project `/path/to/my.fsproj`
[error]: error message
            { json data }
````

Or dunno the format, any idea about other good examples @Krzysztof-Cieslak ?

/cc @alfonsogarciacaro @forki

**Comment by Krzysztof-Cieslak** [comment]
@adamchester is ours logs specialist ;)

But yes, in generally we can add some command forcing opening panel

**Comment by adamchester** [comment]
All sounds like good ideas :) I like the idea of making logs more discoverable without being required to read doco; a command to show logs panel is a great idea.

Regarding improving log messages, it could be hard or easy depending on the specific suggestions, shall we discuss that separately?

**Comment by Krzysztof-Cieslak** [comment]
OK, so I've thought a bit about state of logging:

1. I think logs would need some more formatting, maybe adding some line breaks etc. would help. Adding coloring would be cool... but i think it's not really possible, would need to check the API docs.
2. I think the log level system (INFO / DEBUG) is bit overkill for us - in 99% of cases you just needs all logs to debug anything, and that's what people should posted
3. There shouldn't be a way to turn off logging (right now it can be done by setting `none` on `logLanguageServiceRequests` )
4. `logLanguageServiceRequests` should be set up to `output` as default - users still need to opt-in to see a logs by going to output tab, and selecting right output channel. So no need to have double opt-in as we have right now
5. Adding command is fine, I guess....

**Comment by enricosada** [comment]
ehnanced log with #467 for errors
