### ISSUE TITLE
MsBuild commands should run dotnet CLI for new fsproj

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#423]
Same behavior was implemented for Expecto commands in https://github.com/ionide/ionide-vscode-fsharp/pull/413

@baronfel, would you be interested adding this or should we leave it for some other volunteers? :-)

**Comment by baronfel** [comment]
I'll take a stab, but I won't be able to look until tomorrow or Wednesday :)

**Comment by enricosada** [comment]
i implemented that as part of #455 will send a separate PR.
added also a command `MSBuild: switch msbuild host` to change the current msbuild host (.net `msbuild.exe` or .net core `dotnet msbuild`)
