### ISSUE TITLE
automatic (standard) document generation

### ISSUE THREAD

**Issue by chantisnake** [ionide/ionide-vscode-fsharp#425]
I have looked around many tools, none of them seems to support this...

I think it will be pretty cool if you guys can support automatic xml document generation

for example:
in fsi
```fsharp
val add: int -> int -> int
```
in fs 
```fsharp
let add a b =
    a + b
```

and when I do `right click -> generate document` in fsi file, it gives me this:

```fsharp
/// <summary>  
/// 
///</summary>
/// <param name="a"> 
///</param>
///<param name="b"> 
///</param>
///<returns> 
///</returns>
val add: int -> int -> int
```

**Comment by rmunn** [comment]
I'd rather have an automatic doc generator, if such a tool were added, support Markdown in a format that FSharp.Formatting can turn into XML docs. But first, https://github.com/tpetricek/FSharp.Formatting/issues/44 would need to be implemented. That is a feature I'd really love to see -- XML embedded in code comments has always struck me as ugly -- but there's quite a bit of work that would have to happen first.

So I'd be :-1: on generating XML doc comments: they're one of C#'s less good ideas that I think F# is well served by staying away from. But I'd be :+1: on generating good **Markdown** doc comments.

**Comment by chantisnake** [comment]
never the less, the official documentation of F# uses Xml document.
https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/xml-documentation

actually I don't really care which document format to use, the important thing is there is a document generation for a standard format of documentation.

**Comment by Krzysztof-Cieslak** [comment]
Initial implementation in `2.29.0`.

![docgen](https://user-images.githubusercontent.com/5427083/28812292-e3a18b88-7648-11e7-82bc-7786346ec2a0.gif)

**Comment by rmunn** [comment]
That demo looks great! I'll be certain to give feedback once I've gotten a chance to play with it a little.
