### ISSUE TITLE
Missing ".paket/paket.bootstrapper.exe" when creating a new F# project

### ISSUE THREAD

**Issue by oopbase** [ionide/ionide-vscode-fsharp#429]
When running "> F#: New Project -> Class Library" on **Mac OS**, the .paket folder doesn't contain the paket.bootstrapper.exe. Therefore, I was unable to run the automatically generated build script. (Copying the paket.bootstrapper.exe manually into that folder obviously solved the issue for me)
When running the same commands on Windows, everythings works as expected.
I can reproduce this with the latest version of ionide-fsharp (2.25.11) on Mac OS.

_Edit: After taking a closer look at this repository, this is apparently a forge issue._

**Comment by Krzysztof-Cieslak** [comment]
Yeah, looks like a Forge issue.

**Comment by lloydmeta** [comment]
Sorry, I'm running into this issue as well. I'm not sure what you mean by this is a Forge issue: what can I do to resolve it?
