### ISSUE TITLE
Autocomplete doesn't work for modules (with new project)

### ISSUE THREAD

**Issue by mateuszlewko** [ionide/ionide-vscode-fsharp#430]
I've created a new project, added file with a simple module and autocomplete doesn't work e. g. in main file (entry point). However it works fine for functions / modules created inside file (as long as we try to use them from the same file).

### Steps to reproduce 
1. Command Palette: `New Project (Without FAKE)`
2. Add `test.fs` file with contents: 
```
module Test 
    let fn x = x * 2
```
3. Add file to .fsproj 
4. Inside some other file (that is below test.fs in build order)
```
open Test

[<EntryPoint>]
let main argv =
    printfn "%d" <| fn 5
```
5. Issue:
![image](https://cloud.githubusercontent.com/assets/6179597/25874270/187e8b6c-3512-11e7-97b0-7b8cbc8aae90.png)
6. Also project is building without any problems. 
7. I've also restarted VS Code and the issue persists. 

Some logs form developer tools:

> [Extension Host] last output: [object Map]
extensionHost.ts:285 [Extension Host] [IONIDE-FSAC] RES (049) <- {completion} ERROR in 41 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O
extensionHost.ts:285 [Extension Host] [IONIDE-FSAC] RES (050) <- {completion} ERROR in 23 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O

I'm on Windows 10, with the latest version of Ionide plugin for VS Code. 
I'm having the exact same problem for all other projects (but they are much bigger). I've started experiencing this issue some time ago, so I switched to VS, but now I really want to go back to using VS Code. Without Ionide working properly it's hard. 

Just in case, please take a look at the entire [project](https://github.com/mateuszlewko/Ionide-issue-repro). 
Please let me know if you need any other info.

**Comment by Krzysztof-Cieslak** [comment]
Project file looks fine for me, I can't repro problem. Have you installed all Ionide's requirements specified in the readme?

**Comment by mateuszlewko** [comment]
I think I have everything needed already installed. I suppose if the cause of this was missing requirements Ionide wouldn't work at all. Is just doesn't provide completion for symbols from other files. 

Also I switched to ubuntu and completion for my bigger projects didn't work as well. So I replaced every project file with the new one generated by vs code and added back all references. Now everything works fine (although sometimes it takes a lot of time for ionide to pop autocompletion, like more than 10 seconds).

I think the cause of this could be Visual Studio that also modified my .fsproj files. I'll investigate this issue later when I'll have time. 
This issue is probably related to these: https://github.com/ionide/ionide-vscode-fsharp/issues/386 https://github.com/ionide/ionide-vscode-fsharp/issues/421

**Comment by Krzysztof-Cieslak** [comment]
Please be sure that that you have right version of MsBuild tools installed. If you have installed it using `choco` check if version is right - some time ago they've bumped version, and installing right one requires implicit passing version number.

**Comment by mateuszlewko** [comment]
I installed fresh Windows 10 on a new laptop and did following steps:
1. Installed VS 2017 with F# support
2. choco install windows-sdk-8.0 -y
3. choco install visualfsharptools -y
4. choco install microsoft-build-tools -y
5. choco install visualstudiocode -y
6. Installed ionide plugins for vs code

Issue still persists, event in new projects (created by vs code).
I'm probably doing something wrong (as no one is complaining about ionide on windows).

**Comment by mateuszlewko** [comment]
Ah! I thought that MsBuild 15.x is from 2015. I just installed MsBuild 14.x and everything works fine! 
It turns out that I was actually missing something. Anyway, thanks.

Are there any plans to support MsBuild 15?
