### ISSUE TITLE
Surface Linter Configuration file errors

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [ionide/ionide-vscode-fsharp#431]
[For fable especially](https://github.com/ionide/ionide-vscode-fsharp/issues/148#issuecomment-296712843) 

The linter in ionide supports using a Settings.FSharpLint file. (see )
After using ProcessMonitor I see it reads from `Settings.FSharpLint`

It took some doing, but I managed to hook into the linter, and call the methods to read the configuration file that were there. it responded with detailed information about what was wrong with the file.

Can we surface this somewhere/somehow? 

I had no idea there was just something wrong with the xml file. I thought ionide's integration was faulty. (turns out I was reading an issue ticket that used a now-defunct xml schema for FSharpLint's configuration (https://github.com/fsprojects/FSharpLint/issues/83) .

**Comment by ImaginaryDevelopment** [comment]
perhaps I'm just encountering it failing to analyze entirely when the file is present, since my file only attempts to disable a specific naming rule, but nothing is showing up now also see https://github.com/Eoksni/ionide-lint-test where it appears in his tests, the file wasn't exactly ignored, the presence of it seems to disable the linter. (is what I interpret due to what I've noticed in my usage today)

**Comment by Krzysztof-Cieslak** [comment]
You're using outdated FSharpLint settings file - here's how `NamingRules` looks like in latest version (https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/DefaultConfiguration.FSharpLint#L142-L237)

**Comment by ImaginaryDevelopment** [comment]
ok, but that does nothing to address the request/suggestion. Can we make these errors show up in vscode rather than the linter just stop working?
