### ISSUE TITLE
Question: How can i use F# interactive 64 bits in VS Code on MacOS ?

### ISSUE THREAD

**Issue by FaguiCurtain** [ionide/ionide-vscode-fsharp#434]
<img width="2048" alt="capture d ecran 2017-05-12 a 17 40 03" src="https://cloud.githubusercontent.com/assets/11316512/25998251/1e172412-375b-11e7-8afd-81da6a59f1ed.png">

Hi i've created a file called fsharpi64 as described here
http://bluemountaincapital.github.io/FSharpRProvider/mac-and-linux.html

I'm then trying to configure VS Code so as to be able to run FSI in 64 bits as per the screenshot above, however its still 32 bits it seems.

PS. If i run fsharpi64 in a terminal window, its in 64 bits indeed.

Thanks for your help

**Comment by czifro** [comment]
It may or may not be of use, but it is worth noting a similar issue has occurred in Xamarin: https://bugzilla.xamarin.com/show_bug.cgi?id=56097 . The environment variable [noted in this comment](https://bugzilla.xamarin.com/show_bug.cgi?id=56097#c18) enabled 64bit mode in Xamarin. Perhaps you need to pass extra params to fsi? (`MONO_ENV_OPTION=--arch=64`)
