### ISSUE TITLE
Expecto interation causes "Error: Cannot ready 'substring' of null"

### ISSUE THREAD

**Issue by chicocode** [ionide/ionide-vscode-fsharp#436]
Any task I execute with ionide expecto causes an error.

![error](https://cloud.githubusercontent.com/assets/23087864/26032472/33d2496a-386b-11e7-88b5-cb89a6eeaebc.PNG)

Although everthing works the alert is annoying. 
Do you know what it can be?

**Comment by Krzysztof-Cieslak** [comment]
Can you please open developer console ( `Help |> Toggle Developer Tools` ) and check if there are any errors reported there?

**Comment by Krzysztof-Cieslak** [comment]
Can you please try on `2.25.13`
