### ISSUE TITLE
Pressing space before an open bracket inserts an incorrect close bracket

### ISSUE THREAD

**Issue by rmunn** [ionide/ionide-vscode-fsharp#437]
When I have an opening bracket or parenthesis on a line by itself, with the corresponding closing bracket or parenthesis on a different line, pressing the space bar anywhere on that line inserts an incorrect closing bracket or parenthesis.

```fsharp
// The | character below represents the cursor position
let foo = |[
]
// Press space, and I get:
let foo =  |][
]
```

Same thing happens with parentheses:

```fsharp
// The | character below represents the cursor position
let foo = |(
)
// Press space, and I get:
let foo =  |)(
)
```

But it does not happen with braces:

```fsharp
// The | character below represents the cursor position
let foo = |{
}
// Press space, and I get:
let foo =  |{
}
```

This happens no matter where the cursor is in the line. If it's at the start of the line, I get ` |]let foo = [`, and if it's after the `[`, I get `let foo = [ |]`. None of which are correct since the closing bracket already exists in my source code, one line below. (Or, in the case of my lists of Expecto tests, many pages below).

I've tried to reproduce this behavior in other VS Code languages with dedicated plugins (C#, Javascript) and haven't been able to reproduce it; it only seems to happen in F#. So I suspect the cause of this behavior is something in Ionide rather than in VS Code.

**VS Code version:** 1.12.1, 2017-05-04T21:40:39.245Z
**Ionide version:** 2.25.12
**OS version:** LinuxMint Debian Edition 2 ("Betsy"), based on Debian Jessie

**Comment by rmunn** [comment]
https://github.com/Microsoft/vscode/issues/26012 might be related to this issue.

**Comment by Krzysztof-Cieslak** [comment]
I believe that's VSCode issue and we can't do anything with that (as far as I understand). Can you please report problem  in VSCode repo?

**Comment by DanTup** [comment]
FWIW, I raised the Code issue linked to above. I added some additional characters to trigger the completionItemProvider and it appears to have worked around this issue (because the completions are now re-evaluated by the language service); it may also work for you:

https://github.com/Dart-Code/Dart-Code/commit/03ea03845657472f62d2681be82fc1cc991ceed9
