### ISSUE TITLE
Blank F# Interactive

### ISSUE THREAD

**Issue by reinux** [ionide/ionide-vscode-fsharp#438]
I can tell that FsiAnyCPU is running, because it's in Task Manager, and because if I either send `System.Console.Beep(440, 100)` using alt+enter or type it in the Terminal directly, it beeps. But it's blank, even if I type in it.

![image](https://cloud.githubusercontent.com/assets/5127297/26239697/eb3e5c72-3c32-11e7-8e43-6a35331b7804.png)

Not sure what started this problem. Tried reinstalling F#/.NET 4.7 SDK, clearing %appdata%\code, and .vscode. Any idea what's going on?

**Comment by Krzysztof-Cieslak** [comment]
No idea... if `alt-enter` works, it means that Ionide is sending content correctly yo FSI process.  We don't control displaying stuff in Terminal tab - VSCode is responsible for that.

Please check if same bug is reproducible on latest VSCode Insiders release, and if it is please report issue in VSCode repository.
