### ISSUE TITLE
Not working after installation: turned out to be a clash with 'vscode-shader' extension

### ISSUE THREAD

**Issue by taylorjg** [ionide/ionide-vscode-fsharp#441]
I recently installed mono and this VSCode extension but it didn't seem to be doing anything (no syntax highlighting, etc.). I spent a while trying to figure out what the problem was. Eventually, I opened the developer tools in VSCode and found the following warning:

```
Overwriting extension <<.fs>> to now point to mime <<text/x-glsl>>
```

I uninstalled the `vscode-shader` extension and restarted VSCode and everything was fine. This might help somebody else if they have a similar problem.

**Comment by Krzysztof-Cieslak** [comment]
Thanks for info. Unfortunately nothing can be done - that's `by design` behavior of Code plugin system.
