### ISSUE TITLE
Type 'IAsyncAction' is required here and is unavailable. You must add a reference to assembly 'Windows, Version=255.255.255.255...'

### ISSUE THREAD

**Issue by aggieben** [ionide/ionide-vscode-fsharp#442]
I've got a fairly simple console app that targets `netcore1.1`, and when I open it in VSCode (with Ionide) I get the red error squiggles on every line of code, and the bizarre message in the title.  Here's a screenshot:

<img width="1248" alt="screen shot 2017-06-04 at 2 04 13 am" src="https://cloud.githubusercontent.com/assets/1321/26759663/1f18d182-48ca-11e7-9e23-079b3e30be40.png">

I'm using Paket in this project.  Here's my paket.dependencies:

```
source https://api.nuget.org/v3/index.json
source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
source https://dotnet.myget.org/F/cli-deps/api/v3/index.json

nuget FSharp.Core
nuget FSharp.NET.Sdk
nuget Microsoft.Extensions.Logging
nuget Microsoft.NET.Test.Sdk
nuget System.Net.WebSockets.Client

nuget Argu
nuget FAKE
nuget Newtonsoft.Json
nuget serilog
nuget Serilog.Sinks.Literate
nuget Suave
nuget xunit ~> 2.3 prerelease
nuget xunit.runner.visualstudio ~> 2.3 prerelease
```

and my paket.references for this project:
```
FSharp.Core
FSharp.NET.Sdk
Microsoft.Extensions.Logging
System.Net.WebSockets.Client

Argu
Newtonsoft.Json
Serilog
Serilog.Sinks.Literate
```

I have a classlib project in the same solution, also opened in the same session in VSCode, that doesn't have this problem.

My `dotnet --info`:

```
02:00 $ dotnet --info
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
 Version:            2.0.0-preview2-005905
 Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1
```

**Comment by aggieben** [comment]
It looks like this may be caused by the `System.Net.WebSockets.Client` nupkg - however, it compiles just fine.

**Comment by enricosada** [comment]
@aggieben the `2.0.0-preview2` is a development version.
See https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-2.0.0-preview2#notes because there are some changes if you want tot use it.

The .net sdk 1.0 works https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0

**Comment by aggieben** [comment]
FWIW, it looks like this was resolved when I added this to my `.fsproj`:
```
<PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
```

I did this for other reasons, but after reloading the window, the red squiggles were gone.
