### ISSUE TITLE
"Build of Expecto tests failed" while msbuild build it without errors

### ISSUE THREAD

**Issue by Neftedollar** [ionide/ionide-vscode-fsharp#444]
![image](https://cloud.githubusercontent.com/assets/1009015/26788279/68d6a3f2-4a15-11e7-80d5-24614c06d673.png)
I've created `Expecto` project with `F#: New Project` and try to run it with `Expecto:  Run`
And I've got error `Build of Expecto tests failed`. What should I do to fix it?
`msbuild.exe` build this test project without any problems.

**Comment by Neftedollar** [comment]
I've just moved my test project to the `Tests` folder and Expecto start work!
I think this behavior should be more obvious.
VSCode 1.13.0  Ionide 2.26.1

**Comment by Krzysztof-Cieslak** [comment]
TBF, that's not expected behavior ;) 

Anyway, closing for now, will investigate what's wrong when I'll find some time
