### ISSUE TITLE
intellisense doesnt work referencing a c# csproj

### ISSUE THREAD

**Issue by NinoFloris** [ionide/ionide-vscode-fsharp#445]
Problem reading assembly 'ReferencedCsProject/bin/Debug/netstandard1.6/ReferencedCsProject.dll': Build was not evaluated, expected the results to be ready after 'Eval'.

Might this be because the referenced assembly is from a C# project?

**Comment by enricosada** [comment]
@NinoFloris can you share a repro? 
If is F# + C# is not supported atm, see https://github.com/fsharp/FsAutoComplete/issues/171

**Comment by NinoFloris** [comment]
Sorry for the late reply, life got in the way. 

Yep it's mixed F# and C#  :/
Thanks a lot for your work in this space. I see we just have to wait a little for https://github.com/fsharp/FsAutoComplete/pull/173 to get mainlined right?

**Comment by enricosada** [comment]
@NinoFloris yes

**Comment by Krzysztof-Cieslak** [comment]
Fixed in latest FSAC version.

**Comment by NinoFloris** [comment]
New ionide coming soon with it? Thanks for the work, very useful fix.

**Comment by Krzysztof-Cieslak** [comment]
It was just released

**Comment by enricosada** [comment]
@NinoFloris https://github.com/ionide/ionide-vscode-fsharp/wiki/Version-2.27.12#fix-csproj-p2p require the c# project to be built and assembly generated. see notes
