### ISSUE TITLE
Brand new project, and the build fails - MSB4057: The target "Build" does not exist in the project. 

### ISSUE THREAD

**Issue by SirEel** [ionide/ionide-vscode-fsharp#447]
Trying Ionide for the first time. Running Code on Windows 10 with all 3 Ionide extensions, latest versions. F# was installed on the machine as part of Visual Studio 2017, has latest nightly build. I used F#:New Project command, ran Fake: Default Build command, fails with MSB4057: c:\...\foo.fsproj(0,0): The target "Build" does not exist in the project. 

The project builds fine if I run build.cmd from Developer Command Line. From the command line FAKE calls MSBuild at  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Cloud\MSBuild\15.0\bin\MSBuild.exe.

When trying to build in Ionide FAKE calls MSBuild at c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe. I don't understand why that is different.

This appears to be same or similar to issue #439, https://github.com/ionide/ionide-vscode-fsharp/issues/439

As in #439, I tried overriding settings.json, but it didn't do anything.
{
     "FSharp.msbuildLocation": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Cloud\\MSBuild\\15.0\\bin\\MSBuild.exe",
     "FSharp.toolsDirPath": "C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.1\\Framework\\v4.0"
}

Is there some workaround I don't know about, or is it a bug?

**Comment by SirEel** [comment]
Found answer in MSBuildHelper.fs : 51. It looks for an environment variable (on Windows) named MSBUILD containing path to the file or folder. In this case I created the environment variable and set it to  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Cloud\MSBuild\15.0\bin\ Now FAKE builds correctly in Code (Ctrl+F5). 

I don't see this documented outside the source code. But you may close this issue.

**Comment by JamesFaix** [comment]
This seems like its still an issue. Why did you close it?
