### ISSUE TITLE
update the chocolatey install command for ms build tools

### ISSUE THREAD

**Issue by fradav** [ionide/ionide-vscode-fsharp#449]
As for today, the official and latest release of Microsoft-build-tools package is for ms build tools 2017, which isn't compatible with projectcracker. The correct command should be now:
`choco install microsoft-build-tools --version 14.0.25420.1 -y`

The link for the tools is also outdated (and I can't find an updated one).

Regards

**Comment by Krzysztof-Cieslak** [comment]
Thanks for info!

**Comment by Krzysztof-Cieslak** [comment]
Just for a record - looks like workaround download link is https://my.visualstudio.com/Downloads?pid=1796 and as far as I know old link will be active again, too.
