### ISSUE TITLE
No handler found for the command: 'webpreview.Show'

### ISSUE THREAD

**Issue by 2moveit** [ionide/ionide-vscode-fsharp#45]
If I start the command "Ionide: Show Web View" I get the following error:
![error](https://cloud.githubusercontent.com/assets/2593392/13571804/6adef28a-e477-11e5-8b8c-d9567f445ce9.PNG)

I tried to add `onCommand:webpreview.Show` into the file `<userfolder>\.vscode-insiders\extensions\Ionide.Ionide-fsharp-1.3.0\package.json`
Now I do not get any error but the window is still not shown. I guess something else is missing.

I'm not sure for what the activationEvents part in the packages.json is for but in case all commands need to be there then ff.Show and webpreview.Refresh are missing, too.

I tried it with vscode 0.10.8 and 0.10.10-insider both with ionide-fsharp 1.3.0

**Comment by MangelMaxime** [comment]
Hello, I am trying to execute the command "Show Web View" and "F#: Formatting Show" but I got an error.

"Show Web View" :
`No handler found for the command: 'ff.Show'. An extension might be missing an activation event.`

"F#: Formatting Show":
`Running the contributed command:'webpreview.Show' failed.`

Do I need to install something before ?
