### ISSUE TITLE
Quick install guide failing because Suave.exe is not found in release

### ISSUE THREAD

**Issue by NinoFloris** [ionide/ionide-vscode-fsharp#452]
Trying to contribute a bugfix to the project explorer (with a deeper project hierarchy ionide does not append the projectpath so vscode fails to open the file on click) 

But sadly after following the steps, and turning on debugging I get from the language server:
```
Cannot open assembly '/Users/me/Projects/ionide-vscode-fsharp/release/bin/FsAutoComplete.Suave.exe': No such file or directory.
```

Fyi there is no bin folder in release

**Comment by Krzysztof-Cieslak** [comment]
You need to run `build.cmd Build` that should copy FSAC into right place

**Comment by Krzysztof-Cieslak** [comment]
Oh, `build.sh Build` obviously in your case ;)

Updated DEVGUIDE to include this step.
