### ISSUE TITLE
Only show the project explorer when an F# project is open

### ISSUE THREAD

**Issue by Kurren123** [ionide/ionide-vscode-fsharp#454]
When I open a folder containing projects in other languages, the F# project explorer panel is still there. Is there any way to scan the current folder for F# source files and only show the project explorer if F# files exist?

Thanks

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately that's not something we can control. VSCode adds to UI all tree explorers that are defined in plugins manifests and then just lazily initialize content.

I guess you can try to create issue in VSCode repo

**Comment by Kurren123** [comment]
A work around is to disable the ionide plugin for that workspace.
