### ISSUE TITLE
Can't disable linter with `"FSharp.linter": false` in settings

### ISSUE THREAD

**Issue by EdAyers** [ionide/ionide-vscode-fsharp#456]
# Reproduce
 - Set `"FSharp.linter": false` in vscode's user settings.
 - Reload
 - Open an Fsharp file with a linting error (eg, make a type with lowercase name)

# Expected behavior

No linting errors in the problems pane.

# Actual behaviour

Linting errors

# Investigation

https://github.com/ionide/ionide-vscode-fsharp/commit/3a268cd5a1d16c8f1d8e9083e6982f7602beece1#diff-3cb7d479be19ebb6d5fbdfb0239264a4

In commit 3a268cd5a1d16c8f1d8e9083e6982f7602beece1 in the file Linter.fs, the `isLinterEnabled` function is no longer called anywhere. If I search the repo, `isLinterEnabled` appears to be the only place in the source that polls the `FSharp.linter` setting.

**Comment by Krzysztof-Cieslak** [comment]
Thanks for report. Fixed in `2.27.6`
