### ISSUE TITLE
(Fable) Project issues are not shown until a file is opened and modified.

### ISSUE THREAD

**Issue by stweb** [ionide/ionide-vscode-fsharp#458]
Example code https://github.com/stweb/fable-suave-scaffold/commit/ac9834ca597e5aae90e7645970c208f8cf181e46

When i open the project in VSCode no problems are showing until I open e.g. Messages.fs - then it only shows issues in that file. However, as soon as I edit that file and save to disk, it suddenly brings up more issues in other files.
So it looks like I run into this issue when I resume unfinished work... I was hoping IonIde would do a full background build at startup and show all issues.

**Comment by Krzysztof-Cieslak** [comment]
Looks like there are 2 different issues here:
1. No problems at all before any file is open
2. No global problems before F# file is saved

---

First is connected with the way Code plugins are initialized - they are initialized lazily, after certain "activation events" happens (and there exists certain limited set of events that can be defined). In case of Ionide the activation events are:
1. Opening F# file
2. Using one of the few F# commands.

This can be solved by using `workspaceContains` activation event that got introduced in latest release of Code - it's high on my to-do list.

---

Second problem is probably the bug in our startup behavior.

**Comment by Krzysztof-Cieslak** [comment]
Cross-project problems should be shown after opening the first file. We can't show them before opening any files for performance reasons.
