### ISSUE TITLE
Debugging F# code works only after debugging a C# project

### ISSUE THREAD

**Issue by luminescent** [ionide/ionide-vscode-fsharp#466]
Steps to reproduce:

- fresh install of VSCode, with FSharp-ionide and C# extensions added 
- open F# on .NET Core project, attempt debug. It won't start, saying the debugger is not initialized 

Workaround:
- create C# project on .NET Core 
- debug said project 
- reopen F# project => debugging will work this time

**Comment by Krzysztof-Cieslak** [comment]
This happens only on fresh install of C# extension. C# extension initializes some of its dependencies lazily, and there is nothing we can do about it.

As a workaround - running `Debug: Download .Net Core Debugger` command solves the problem.

**Comment by enricosada** [comment]
@Krzysztof-Cieslak is possible to reopen? 
maybe is possibile to catch the error somehow to invoke that command prorgammatically. 
or just give a graceful error message.
i'll try ask the omnisharp team
