### ISSUE TITLE
Feature request: Disable IntelliSense prompts while pressing the dot key inside a comment.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#474]
While writing code documentation, pressing dot at the end of a sentence, an auto-complete box appears. Sometimes, it doesn't get immediately noticed and the user presses the Enter key, adding the first identifier at the list (usually `abs`) and requiring a `Ctrl-Z`.

**Comment by enricosada** [comment]
yes, is annoying.

closing as dupe of https://github.com/ionide/ionide-vscode-fsharp/issues/74
