### ISSUE TITLE
">F#: Add Current File To Project" doesn't work

### ISSUE THREAD

**Issue by oleksandr-bilyk** [ionide/ionide-vscode-fsharp#478]
In VSCode I have installed 3 ionide extensions: Ionide-fshart, Ionide-FAKE, Ionide-Paket. But on my machine may be reproduced in any small solution for example on "https://github.com/ionide/DebugSample"
I create some file in "/src/DotNetCore/" folder for example "File1.fs" and try to add it to project using ">F#: Add Current File To Project" but nothing happens. Other ">F#:..." commands also don't work like ">F#: Move File Up/Down". 
I was uninstalling extensions and VSCode and nothing helped. I have to edit DotNetCore.fsproj project file manually. Please help.

**Comment by Krzysztof-Cieslak** [comment]
new `fsproj` file format is not yet supported by Forge and hence commands modifying project files are not working at the moment. This will be fixed when full version of Forge 2.0 gets released (it's work in progress, at the moment).
