### ISSUE TITLE
1.5.0 -> 1.5.1 on Mac OS X breaks all F# goodness.

### ISSUE THREAD

**Issue by deapsquatter** [ionide/ionide-vscode-fsharp#48]
After upgrading ionide-vscode-fsharp extension from 1.5.0 -> 1.5.1 on Mac OS X I can no longer get any ionide functionality working. No tooltips, quick info toolbar, autocomplete etc.

**Comment by Samvrie** [comment]
I just updated too and got some same issue on Windows 10 (Not insider build).

**Comment by Krzysztof-Cieslak** [comment]
Can you try `1.5.2` ?

**Comment by Samvrie** [comment]
I works for me! Thanks for the quick reply and fix, love the Ionide stuff!

**Comment by deapsquatter** [comment]
Works for me too. Thank you!
