### ISSUE TITLE
Incorrect inference  obj instead of the actual type

### ISSUE THREAD

**Issue by amsterdamharu** [ionide/ionide-vscode-fsharp#481]
First of all; thank you for all your effort.
I tried to reproduce this is a minimal example but was not able to do so, Maybe you can reproduce the bug when opening the following code:
https://github.com/amsterdamharu/programmingbook/tree/ionideproblem
opening src/modules/pausableStopWatch/handlers.fsx
It shows an error at line 19 
This expression was expected to have type
    'StartDate'    
but here has type
    'obj'
At line 11 when hovering over "start" it tells me it is of type: SinglePausableStopWatchState.start: obj
but in type definition it is StartDate
The code compiles with fable without errors using the command:
node ./node_modules/fable-compiler/index.js --projFile ./src/main.fsx -s true -o ./js/

I am Using: 
vscode
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
with extensions
Ionide-fsharp 2.31.0
Ionide-fake 1.2.3
Ionide-Paket 1.7.3
On Fedora 25

If you need any more information or if you think I can do something to improve this product then please let me know.

**Comment by Krzysztof-Cieslak** [comment]
This is probably breaking change in type inference between F# versions - Ionide always uses latest one (i.e latest FCS), while building uses compiler version defined in the project file (or in this case, whatever Fable uses)
