### ISSUE TITLE
Trouble with the build

### ISSUE THREAD

**Issue by lambdakris** [ionide/ionide-vscode-fsharp#483]
Hello, I ran into a problem when following the "How to contribute" instructions in the readme. Upon running build.cmd Build, the build eventually fails due to what appears to be a problem parsing the Forge.fsproj file. More precisely, it says...
```
...\paket-files\github.com\fsharp-editing\Forge\src\Forge\Forge.fsproj(77,3): The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
```
So I took a look at the Forge.fsproj in the specified location and found the following...
```
<Import Project="$(FSharpTargetsPath)" />
```
To verify, I added a target with a message task to print out FSharpTargetPath and it printed this...
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\FSharp\Microsoft.FSharp.Targets
```
So I'm not sure why it is ending up empty when invoked by the fake build...

I am on Windows 10 and have VS 2015 and VS2017 installed (and just in case I also installed the MS Build Tools 2015).

Any help or ideas would be greatly appreciated.

**Comment by tforkmann** [comment]
Hello,

we were just running into the same error.
![msbuild](https://user-images.githubusercontent.com/4168951/29108690-54110806-7ce0-11e7-81fb-1de2d73cf1c8.png)

My first though was to install MSBuild new...

I might be wrong.

@CVogel89

**Comment by lambdakris** [comment]
This seems to be happening when the version of MS Build 15.0 included with/under Visual Studio 2017 is used instead of MS Build 14.0. I still have to figure out what about MS Build 15.0 is causing this, but I'm going to go ahead and close since I don't think it is really an issue with this repo.

**Comment by lambdakris** [comment]
For posterity, issue seems to have been that I recently had uninstalled F# language support from my VS 2017 installation but since during the build the version of VS is the highest available, it tries to look for the F# targets file under the VS 2017 location, which did not exist, so the FSharpTargetsPath property never gets defined and thus `<Import Project="$(FSharpTargetsPath)" />` fails with said error.
