### ISSUE TITLE
Project Explorer - Move Up/Down, Add new File

### ISSUE THREAD

**Issue by n00b42** [ionide/ionide-vscode-fsharp#484]
Using Profile Explorer to change the order of my *.fs files to solve dependencies is neither reflected visually (Files remain in the same order) nor do the reference errors update/go away.

"Project - Reload" does not help nor does opening the same folder again. Only closing VSC and reopening updates the Project Explorer list and reference errors.

Furthermore, adding a new file to the project using "F# Add Current File to Project" does not update "Project Explorer" or references.

> Ubuntu 1604 64bit, VSC 1.14.2, Ionide-fsharp 2.31.0, Ionide-FAKE 1.2.3

**Comment by Krzysztof-Cieslak** [comment]
1. Check output of the Forge (`View: Toggle output` and then choose `Forge` from the list)
2. If possible, please post here the project file you try to modify

**Comment by n00b42** [comment]
1. Forge output
> forge move file -n /data-sync/Projects/2017-Memory-Verificator/Project/WMV/WMV.fs -d --no-prompt
﻿﻿
2. Note: The project has been created using "Project Explorer - F# New Project"
fsproj file: https://pastebin.com/hGd3RNqS

**Comment by desjardinsm** [comment]
Not sure if this is the same issue, but I'm also unable to get any forge-related commands work.  Forge output is:
> forge move file -n c:\test\foo.fs -d --no-prompt
> Unhandled error:
> Object reference not set to an instance of an object.

**Comment by Krzysztof-Cieslak** [comment]
> Object reference not set to an instance of an object.

You probably use "new" fsproj (SDK-based) which is not yet supported by Forge. Forge 2.0 (preview can be downloaded from Forge's repo) should solve this problem but it's still WIP.
