### ISSUE TITLE
How to use FSharp.Core, Version=4.4.1.0 from *.fsx in VSCode?

### ISSUE THREAD

**Issue by maestrow** [ionide/ionide-vscode-fsharp#485]
Autocompletion used FSharp.Core, Version=4.4.0.0, while fsi - 4.4.1.0 version. At the below screenshot we can see successfull script execution in fsi console (in VSCode) and at the same time error, displaing in editor. This single line script uses feature from FSharp.Core, Version=4.4.1.0 - the Result type **Ok** union case.
![image](https://user-images.githubusercontent.com/671853/29143676-9fbb2420-7d5e-11e7-9571-78ada3c9ddae.png)

My question is: **How to make ionide autocomplete use FSharp.Core 4.4.1.0** by default (without \#r)?

**Comment by Krzysztof-Cieslak** [comment]
It's probably not perfect workaround but using `fs` file and `.fsproj` targeting 4.1 (or adding 4.1 by Paket) should work.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.34.3`
