### ISSUE TITLE
VSCode is jumping the code all over the place

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#492]
Still jumping a lot.

https://vimeo.com/215830120/3a6e270dc8

**Comment by Danl2620** [comment]
Getting this as well. It scrolls my file upwards as I type until the current line is pinned to the top of the window.

**Comment by Krzysztof-Cieslak** [comment]
As a temporary workaround you can disable CodeLenses if their performance is not good enough (`"editor.codeLens": false` in Code's settings)

**Comment by Krzysztof-Cieslak** [comment]
As an other temporary workaround you can use new LineLenses that add signatures without changing vertical alignment of code (so no jumping if the disappear)

**Comment by vbfox** [comment]
```json
{
    "FSharp.lineLens.enabled": "replaceCodeLens",
    "[fsharp]": {
        "editor.codeLens": false
    }
}
```

Then forget about CodeLens 🤣

**Comment by haf** [comment]
How do I use line-lenses?

**Comment by StachuDotNet** [comment]
Go to your user settings, then use the configuration noted in the post
right  before yours. :) ctrl+shift+p, then settings. Override the two
noted.

**Comment by Krzysztof-Cieslak** [comment]
`3.3.3` includes next attempt to make CodeLenses faster, please let me know if it have any impact.

**Comment by Krzysztof-Cieslak** [comment]
OK, I believe that latest updates (including bump of FCS version) makes CodeLenses as fast as it is possible given state of FCS, we can't do anything more.
