### ISSUE TITLE
Compilation time – drains battery and doesn't finish compiling

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#493]
While editing code, you naturally break a function or two while editing. The problem is that ionide doesn't finish compiling, so code-completion is broken forever, until VSCode is restarted.

<img width="571" alt="screen shot 2017-08-14 at 10 46 17" src="https://user-images.githubusercontent.com/193115/29264559-e1bd236e-80dd-11e7-8336-5eaccdb15348.png">

<img width="656" alt="screen shot 2017-08-14 at 10 53 12" src="https://user-images.githubusercontent.com/193115/29264813-cdacea8e-80de-11e7-9c29-d16527f185dc.png">

<img width="800" alt="screen shot 2017-08-14 at 10 53 04" src="https://user-images.githubusercontent.com/193115/29264825-da4001d2-80de-11e7-8b98-9086c9cd0bd9.png">

The number is the "Energy impact" column.

**EDIT**: If this is Suave's fault, I may have a real-world example to fix performance because of.

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed with request cancelling we've added recently
