### ISSUE TITLE
Problem with project references on .NET Core 2.0

### ISSUE THREAD

**Issue by gsomix** [ionide/ionide-vscode-fsharp#496]
Ionide doesn't see library reference on .NET Core 2.0 solution with two projects.

#### Repro steps

1. Create solution with two projects: classlib and console

```
mkdir netcore2-vscode
cd  .\netcore2-vscode\
dotnet new sln
dotnet new classlib -lang f# -o .\lib\
dotnet new console -lang f# -o .\app\
dotnet add .\app\app.fsproj reference .\lib\lib.fsproj
dotnet sln add .\app\app.fsproj
dotnet sln add .\lib\lib.fsproj
dotnet restore
```

2. Put following code into `.\app\Program.fs`

```fsharp
open System
open lib

[<EntryPoint>]
let main argv =
    Say.hello "World"
    0 // return an integer exit code
```

3. Build and check that's everything is OK

```
dotnet build
dotnet run --project .\app\app.fsproj
```

4. Open solution in VSCode

#### Expected behavior

Everything is fine. No errors in VSCode.

#### Actual behavior

Errors in VSCode:

- Problem reading assembly 'c:\Users\m1k3y\Documents\netcore2-vscode\lib\bin\Debug\netstandard2.0\lib.dll': Build was not evaluated, expected the results to be ready after 'Eval'.'
- The namespace or module 'lib' is not defined.
- The value, namespace, type or module 'Say' is not defined.

![vscode-screenshot](https://user-images.githubusercontent.com/832449/29315447-5dd7ad88-81d4-11e7-9703-3081a5788679.png)

Sorry for translated version of VSCode.

#### Related information 

* Operating system: Windows 8.1
* .NET Core 2.0
* Visual Studio Code 1.15.0, Ionide 2.32.2

Please find attached repro: [netcore2-vscode.zip](https://github.com/ionide/ionide-vscode-fsharp/files/1224953/netcore2-vscode.zip)

Thanks!

**Comment by Krzysztof-Cieslak** [comment]
CC: @enricosada

**Comment by enricosada** [comment]
Issue is `netstandard2.0` intellisense doesnt work atm, `netcoreapp2.0` works.

We need to upgrade FSC used by FSAC. ref https://github.com/fsharp/FsAutoComplete/issues/180

**Comment by Krzysztof-Cieslak** [comment]
Closing this one since it's tracked on FSAC repo.

**Comment by gsomix** [comment]
OK, thanks a lot!

**Comment by leocavalcante** [comment]
I'm getting this issue on `netcoreapp2.1` had to downgrade to `netcoreapp2.0`.

**Comment by xdaDaveShaw** [comment]
I had this issue just now after changing one project from netstandard to netcoreapp.

Doing a `git clean -xdf` and a full rebuild seems to have sorted it.
