### ISSUE TITLE
Intellisense not working for classlib project in .NET Core 2.0

### ISSUE THREAD

**Issue by priort** [ionide/ionide-vscode-fsharp#497]
Hi there,

Thanks for the great work supporting .NET Core 2.0
I can create console and xunit projects and everything works fine. However, when I create a classlib project, I don't get any intellisense.

Windows 10
VsCode
Ionide 2.32.2

dotnet new classlib -o MyLibrary -lang f#
cd MyLibrary
dotnet restore
dotnet build
code .
![capture](https://user-images.githubusercontent.com/13556648/29338273-64995a80-820c-11e7-999d-4c07511cfdb7.PNG)

**Comment by Krzysztof-Cieslak** [comment]
Maybe it's same case as in this Tweet - https://twitter.com/mavnn/status/897493762510815232 - missing Sdk reference in project file?

**Comment by cartermp** [comment]
I can repro with a new .NET Core SDK 2.0-based project.  No language service hookup for the library.  Works just fine with a console app though.

**Comment by cartermp** [comment]
No real difference in the project files:

**Console:**

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

**Library:**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>
```

**Comment by lambdakris** [comment]
I ran in to this and as best as I can tell is that if the target framework is netstandards2.0, it doesn't work, but if it is netcoreapp2.0, it works.

**Comment by lambdakris** [comment]
...and actually the project type doesn't matter, it could be a console and as long as the target framework is netstandard2.0, it seems like intellisense doesn't activate. The reason you notice with classlib is that the target framework automatically gets set to netstandard2.0 while for the app style templates the target framework gets set to netcoreapp2.0.

**Comment by Krzysztof-Cieslak** [comment]
Can someone post output from Ionide's logs ?

**Comment by lambdakris** [comment]
Well, all I see is an error parsing the fsproj file, but no details as to why that is...

```
[21:36:25 DEBUG] REQ (001) -> {project}, File = "~\tryouts.fsproj"
Data={"FileName":"c:\\Users\\admin\\Code\\tryouts\\tryouts.fsproj"}

[21:36:26 DEBUG] RES (001) <- {project} in 1040 ms: Kind={"error"}
Data={"Code":1,"Message":"MSBuild failed with exitCode 1 Working Directory: 'c:\\Users\\admin\\Code\\tryouts' Exe Path: 'dotnet' Args: 'msbuild c:\\Users\\admin\\Code\\tryouts\\tryouts.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\\Users\\admin\\AppData\\Local\\Temp\\tmp312B.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\\Users\\admin\\AppData\\Local\\Temp\\tmp312C.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\\Users\\admin\\AppData\\Local\\Temp\\tmp314C.tmp.GetProperties.txt /nologo /verbosity:quiet'","AdditionalData":{}}

[21:36:26 ERROR] Project loading failed, MSBuild failed with exitCode 1 Working Directory: 'c:\Users\admin\Code\tryouts' Exe Path: 'dotnet' Args: 'msbuild c:\Users\admin\Code\tryouts\tryouts.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\admin\AppData\Local\Temp\tmp312B.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\admin\AppData\Local\Temp\tmp312C.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\admin\AppData\Local\Temp\tmp314C.tmp.GetProperties.txt /nologo /verbosity:quiet' 
```

**Comment by priort** [comment]
[Extension Host] vscode-icons is active!
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] REQ (001) -> {project}, File = "~\MyLib.fsproj"
Data=Object
extensionHost.ts:335 [Extension Host] [msbuild] MSBuild (.NET) found at C:\Program Files (x86)\\MSBuild\14.0\Bin\MSBuild.exe
extensionHost.ts:335 [Extension Host] [msbuild] Dotnet cli (.NET Core) found at C:\Program Files\dotnet\dotnet.exe
extensionHost.ts:335 [Extension Host] [msbuild] MSBuild (.NET) activated
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] RES (001) <- {project} in 503 ms: Kind={"project"}
Data=Object
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] REQ (002) -> {parse}, File = "~\Library.fs"
Data=Object
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] RES (002) <- {parse} in 1549 ms: Kind={"error"}
Data=Object
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] Cannot execute parse, The file 'c:\Users\prior\OneDrive\d\dotnetCoreProjs\MyLib\Library.fs' was not part of the project. Did you call InvalidateConfiguration when the list of files in the project changed? 
extensionHost.ts:335 [Extension Host] [icons] Loading icon theme from C:\Users\prior\.vscode\extensions\robertohuertasm.vscode-icons-7.12.0\out\src\icons.json
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] REQ (003) -> {project}, File = "~\MyLib.fsproj"
Data=Object
extensionHost.ts:335 [Extension Host] Output omitted for a large object that exceeds the limits
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] RES (003) <- {project} in 7 ms: Kind={"project"}
Data=Object
extensionHost.ts:335 [Extension Host] Startup took: 2584.000000 ms
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] REQ (004) -> {declarations}, File = "~\Library.fs"
Data=Object
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] REQ (005) -> {lint}, File = "~\Library.fs"
Data=Object
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] RES (005) <- {lint} in 12 ms: Kind={"info"}
Data=Cached typecheck results not yet available

**Comment by priort** [comment]
that was on window reload

**Comment by priort** [comment]
Then when I type . as in System. in my fs source file in my class library, logs are:

[Extension Host] [IONIDE-FSAC] REQ (013) -> {parse}, File = "~\Library.fs"
Data=Object
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] RES (013) <- {parse} in 29 ms: Kind={"error"}
Data=Object
extensionHost.ts:335 [Extension Host] [IONIDE-FSAC] Cannot execute parse, The file 'c:\Users\prior\OneDrive\d\dotnetCoreProjs\MyLib\Library.fs' was not part of the project. Did you call InvalidateConfiguration when the list of files in the project changed?

**Comment by priort** [comment]
My fsproj does include Library.fs though
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>

**Comment by Krzysztof-Cieslak** [comment]
Known bug tracked in https://github.com/fsharp/FsAutoComplete/issues/180

**Comment by priort** [comment]
Okay no worries, thanks for investigating.
