### ISSUE TITLE
Ionide prevent commands to be shown on command palette

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#499]
Seems like the bug reported here https://github.com/Microsoft/vscode/issues/32673 is caused by latest version of ionide-fsharp.

The problem, is commands from extensions are not shown when ionide-fsharp is installed.

- ionide-fsharp version: 2.33.0
- OS: Linux Mint 18.2, Window Pro x64
- VSCode: 1.15.1 x64

**Comment by Krzysztof-Cieslak** [comment]
Can you check if anything is reported in VSCode Developer Console?
