### ISSUE TITLE
Single keyboard shortcut to "send line to FSI" and "send selection to FSI"

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#502]
Rider has single shortcut for the both actions, which is very convenient: anytime you want to send anything to FSI you just press `Ctrl+\`.

**Comment by Krzysztof-Cieslak** [comment]
I think `send selection to FSI` will work as `send line` if nothing is selected.

**Comment by Krzysztof-Cieslak** [comment]
Yeah, it definitely should:
https://github.com/ionide/ionide-vscode-fsharp/blob/15a3a7dfeb6666161967b9eafed1de53fb52eece/src/Components/Fsi.fs#L103-L114
