### ISSUE TITLE
No XML doc comment in tooltips for BCL symbols

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#503]
VS

![image](https://user-images.githubusercontent.com/873919/29493791-02449780-85a6-11e7-826c-cad7376fc358.png)

Ionide

![image](https://user-images.githubusercontent.com/873919/29493795-1b6167de-85a6-11e7-95a8-c4d27ee155c2.png)

It's on same file opened in VS and Code at the same time.

**Comment by Krzysztof-Cieslak** [comment]
Working in `2.34`:
![image](https://user-images.githubusercontent.com/5427083/29754096-cf0aef34-8b7e-11e7-98fb-0a85d4b92f93.png)
