### ISSUE TITLE
Stale project in F# Project Explorer when moving the fsproj

### ISSUE THREAD

**Issue by theimowski** [ionide/ionide-vscode-fsharp#509]
Steps to reproduce:
* Create new F# Project (console)
* **Move** contents of the project level up, to the root: `mv Project/* .`
* Remove empty directory
* Duplicate projects appear in the `F# Project Explorer`, and files in both fail to open:

![image](https://user-images.githubusercontent.com/5909015/29649213-0744fadc-8893-11e7-816e-b3fbe89ce8b2.png)

Workaround is to rename the fs file manually and afterwards reload VS Code workspace

**Comment by Krzysztof-Cieslak** [comment]
I think it should be fixed by 3.14
