### ISSUE TITLE
Ionide displays wrong type annotation for functions

### ISSUE THREAD

**Issue by jakzale** [ionide/ionide-vscode-fsharp#518]
When writing the following code
```fsharp
let f g =
    g ()
```
Ionide displays the following type annotation of `unit -> 'a -> 'a`
<img width="132" alt="type_annotation" src="https://user-images.githubusercontent.com/2419109/29912011-75590584-8e30-11e7-9263-a712bfba83d2.png">

which is incorrect, as the type of `f` is `(unit -> 'a) -> 'a`

When binding `f` to a different variable, the type annotation is displayed correctly
<img width="127" alt="type_annotation_2" src="https://user-images.githubusercontent.com/2419109/29912139-ee3cc404-8e30-11e7-8de2-f97c9b681430.png">

**Comment by enricosada** [comment]
can repro.

FSAC seems to answer correctly with

```
[13:06:46 DEBUG] RES (134) <- {signatureData} in 14 ms: Kind={"signatureData"}
Data={"OutputType":"'a","Parameters":[[{"Name":"g","Type":"unit -> 'a"}]]}
```

**Comment by Krzysztof-Cieslak** [comment]
Bug is in this function- https://github.com/ionide/ionide-vscode-fsharp/blob/8846652917f657acb0f1abac0c7139b47a3db1dd/src/Components/CodeLens.fs#L49-L60. PRs welcomed

**Comment by vbfox** [comment]
Fixed by https://github.com/ionide/ionide-vscode-fsharp/pull/527 no ?

**Comment by enricosada** [comment]
yes, closing
