### ISSUE TITLE
"Add Current File To Project" command not working

### ISSUE THREAD

**Issue by alexfoxgill** [ionide/ionide-vscode-fsharp#521]
Executing the "Add Current File To Project" task does nothing in a fresh Fable project (created using the instructions [here](http://fable.io/pages/getting-started.html)). I don't know how to provide more information than this, since nothing happens!

**Comment by Krzysztof-Cieslak** [comment]
SDK based projects are not yet supported by Forge (it's WIP) so no project modifications commands work yet with them

**Comment by alexfoxgill** [comment]
Fair enough. Thanks for your hard work on this project!
