### ISSUE TITLE
Wishlist: generate SLN

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#523]
...for `dotnet restore` to gawk at. Otherwise it's a pretty meaningless format.

Could be done as a command in VSCode.

**Comment by enricosada** [comment]
`dotnet new sln` in terminal? using `dotnet sln` you can add projects, remove it, etc, see `dotnet sln --help`

Anyway full sln support (readonly) will be merged with #480 

i'll follow that with another PR, for modify sln files (create, add projects, add folder, move files, etc)

**Comment by enricosada** [comment]
basic:

- `dotnet new sln` to create it
- `dotnet sln add` and `dotnet sln remove` to modify it

advanced with https://github.com/enricosada/sln/issues/1

**Comment by enricosada** [comment]
Closing.

Works already with `dotnet new sln` or can be added as forge template maybe

**Comment by Krzysztof-Cieslak** [comment]
I guess we could add Command for it, and maybe some button somewhere in project explorer
