### ISSUE TITLE
'Rename' refactoring can cause incorrect indentation

### ISSUE THREAD

**Issue by alexfoxgill** [ionide/ionide-vscode-fsharp#525]
In the following snippet:

```fsharp
let circle = { shape = Circle(64. * 0.75)
               lineStyle = lineStyle
               fillStyle = fillStyle }
```

using the Rename refactoring on `circle` and renaming to a different length string will mean that the indented properties below it are incorrectly offset. It would be cool if the refactoring automatically adjusted indentation too!

**Comment by enricosada** [comment]
probably need https://github.com/Microsoft/visualfsharp/pull/3542

**Comment by Krzysztof-Cieslak** [comment]
I don't think it's possible to implement given the current state of F# Compiler Services, FSAC, and state of art in code formatting/code generation with F#.
