### ISSUE TITLE
Code Lens broke after "Line Lens" PR merged

### ISSUE THREAD

**Issue by xuanduc987** [ionide/ionide-vscode-fsharp#526]
Commit 6b759479045387831cf2ae7eec9bf9f66df0204e broke Code Lens, because Code Lens expected ` formatSignature` has signature `SignatureData -> string`, not `string -> string`

ref 51cab65a4fbd729e20513c40bfebb5e37460019c

cc @vbfox

**Comment by vbfox** [comment]
Ah thanks, I messed up my rebase/squash as the change was already in my branch.

I'll PR a change to `LanguageService` to add types to the methods as the only reason it compiled and didn't raise any errors after my rebase is because everything in there return `Promise<'a>`.
