### ISSUE TITLE
Pressing Backspace after pressing Tab erases only one space.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#529]

**Comment by enricosada** [comment]
Cannot repro with a `.fs` file, what file are you editing?

can you check your vscode configuration? https://stackoverflow.com/questions/29972396/how-to-set-tab-space-style

**Comment by teo-tsirpanis** [comment]
@enricosada Sorry for being late. Here is a reproduction ...ish: https://youtu.be/6ng4gvhySEo

That is my config file:
``` json
{
    "workbench.colorTheme": "Darcula",
    "workbench.iconTheme": "vscode-icons",
    "editor.fontSize": 12,
    "editor.fontFamily": "Ubuntu Mono",
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "files.associations": {
        "*.FSharpLint": "xml"
    },
    "workbench.commandPalette.history": 5,
    "typescript.check.npmIsInstalled": false,
    "editor.renderControlCharacters": false,
    "editor.renderWhitespace": "none",
    "window.zoomLevel": 0
}
```

**Comment by teo-tsirpanis** [comment]
In Version 2.25.14, the change log says: `Default config for Tab Stops`. I think something that happened then is the problem. I remember Tabs were working fine in the past.

**Comment by Krzysztof-Cieslak** [comment]
To restore previous behavior use: `"editor.useTabStops": true`

**Comment by teo-tsirpanis** [comment]
It is `true` by default. I tried to set it to `false`, yet nothing did happen.

**Comment by Krzysztof-Cieslak** [comment]
It's overrided by extension settings to `false` (https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L726-L730) so it's not `true` by default. Setting `true` restores previous behavior

**Comment by teo-tsirpanis** [comment]
I have set it to `false` and still it doesn't work.
