### ISSUE TITLE
Define a custom color for LineLens

### ISSUE THREAD

**Issue by vbfox** [ionide/ionide-vscode-fsharp#530]
VSCode allow definition of extension-provided themable colors since 1.16, LineLens should use them !

> Extension can now contribute new themable colors. These colors can be used in decorators and in the Status Bar.
> 
> ```json
>   "colors": [{
>       "id": "superstatus.error",
>       "description": "Color for error message in the status bar.",
>       "defaults": {
>           "dark": "errorForeground",
>           "light": "errorForeground",
>           "highContrast": "errorForeground"
>       }
>   }]
> ```
> Once defined, user can customize the color in the workspace.colorCustomization setting. User themes can set the color value.

**Comment by enricosada** [comment]
linelens cannot use the same codelens theme?

**Comment by vbfox** [comment]
By default they do but I allowed for it to be configurable as I like them to be darker than what LineLens looks.

I created this issue to remember to convert the existing custom setting for colors to themable color now that VSCode support them.

**Comment by ScottHutchinson** [comment]
So, as far as I can figure out, this issue did not get addressed in the master branch. Somehow the low contrast for lineLense in the dark scheme makes it difficult to see. This could be a problem, especially for a demonstration on a big screen in a classroom, etc. A configurable "FSharp.lineLens.color" setting would be helpful. I could probably help with this, if needed.

**Comment by vbfox** [comment]
The color is now themable. It can either come from a theme (Well if any care about F#) or from an user override in user setting:

```json
{
  "workbench.colorCustomizations": {
    "fsharp.linelens": "#FF0000"
  }
}
```

(Maybe red isn't the absolute best choice 😉)

**Comment by ScottHutchinson** [comment]
That works. Thanks!
