### ISSUE TITLE
add smoke tests for ionide extension

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#534]
ref http://vscode-docs.readthedocs.io/en/stable/extensions/testing-extensions/
ref https://code.visualstudio.com/docs/extensions/testing-extensions

to add basic smoke test for os, in travis/appveyor

**Comment by alfonsogarciacaro** [comment]
@enricosada There's Fable.Template.Jest: https://github.com/jgrund/fable-template-jest

**Comment by Krzysztof-Cieslak** [comment]
As the vast majority of logic nowadays is in FSAC and Ionide is a rather thin client, this is no longer needed
