### ISSUE TITLE
problem with Forge 2.0 

### ISSUE THREAD

**Issue by EHotwagner** [ionide/ionide-vscode-fsharp#542]
See https://github.com/fsharp-editing/Forge/issues/87 and https://github.com/ionide/ionide-vscode-fsharp/issues/540

**Comment by enricosada** [comment]
@EHotwagner i am going to close this, is tracked in https://github.com/fsharp-editing/Forge/issues/87

Is a bug in forge or forge templates (can be repro'ed by forge command line), not directly in the vscode integration with forge.
