### ISSUE TITLE
Generated types are not seen in other projects

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#546]
![image](https://user-images.githubusercontent.com/873919/30537789-d5e6fc8e-9c73-11e7-9f6b-5dc136138c1e.png)

It was fixed long ago in VFT repo (and used in Rider, too), see https://github.com/Microsoft/visualfsharp/issues/3234

**Comment by enricosada** [comment]
@vasily-kirichenko the fix (afaik) is in https://github.com/Microsoft/visualfsharp/commit/82c9492ed9a1c2dbe118220c13dae525936f2f63 and should be already merged in latest FCS with https://github.com/fsharp/FSharp.Compiler.Service/pull/793

**Comment by Krzysztof-Cieslak** [comment]
Can someone check if that's still a case? Latest FSAC is using latest FCS version (`16.0.2`) so I assume it should be fixed.

**Comment by Krzysztof-Cieslak** [comment]
We're using latest FCS build from VF#, so it should be fixed for sure if it was fixed in VF#
