### ISSUE TITLE
Code Lens is misplaced horizontally

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#547]
![image](https://user-images.githubusercontent.com/873919/30538196-867bc81c-9c75-11e7-8fd8-8fddc0d937f6.png)

**Comment by Krzysztof-Cieslak** [comment]
I believe that's it's by-design VSCode behaviour when CodeLens content is wider than editor wight - it tries to fit CodeLens as well as possible on screen ignoring horizontal position.
