### ISSUE TITLE
Error highlighting updates very slowly compared to other editors

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#549]
Rider

![1](https://user-images.githubusercontent.com/873919/30539015-340c0cc8-9c79-11e7-9c13-09fc76a608ef.gif)

VS 2017

![1](https://user-images.githubusercontent.com/873919/30539117-a7ffaeaa-9c79-11e7-800d-2425cbcd858c.gif)

Ionide

![1](https://user-images.githubusercontent.com/873919/30539179-e60741e0-9c79-11e7-8f1e-8fe5a3eb49ea.gif)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.5.0`
![delay](https://user-images.githubusercontent.com/5427083/31317803-a57b4134-ac47-11e7-8024-63ba454f49ba.gif)

**Comment by vasily-kirichenko** [comment]
Excellent! Thanks you 👍
