### ISSUE TITLE
Code/LineLens does not display explicitly chosen type aliases

### ISSUE THREAD

**Issue by varon** [ionide/ionide-vscode-fsharp#550]
![image](https://user-images.githubusercontent.com/1936994/30540152-2776b16e-9c76-11e7-9ae4-289d8d438b56.png)

For an explicitly specified alias, this should probably display the alias.

**Comment by Krzysztof-Cieslak** [comment]
Seems to work for me
![image](https://user-images.githubusercontent.com/5427083/31316147-dc9e7c8c-ac27-11e7-8a46-fa20c1525f19.png)
