### ISSUE TITLE
Nothing work on any file in a project

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#551]
![image](https://user-images.githubusercontent.com/873919/30541089-85ef2db4-9c82-11e7-9641-67bf846c3516.png)

**Comment by enricosada** [comment]
@vasily-kirichenko can you please:

- type of fsproj (old or new). if new, what .net core version (`dotnet --info`)
- check if project was loaded correctly? in the `F# project explorer` -> right click proj -> show error info
- paste here the diagnostic log (see https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting about how to enable it)

**Comment by enricosada** [comment]
@vasily-kirichenko ping

**Comment by vasily-kirichenko** [comment]
Same

![image](https://user-images.githubusercontent.com/873919/31120053-cbdfa32a-a83b-11e7-8b0d-f5d3414b3dd9.png)

**Comment by enricosada** [comment]
Ok closing.

@vasily-kirichenko feel free to reopen and add more info ( some Q in https://github.com/ionide/ionide-vscode-fsharp/issues/551#issuecomment-330217630 )

**Comment by vasily-kirichenko** [comment]
?

**Comment by enricosada** [comment]
There is no info there to diagnose the issue, just two screenshots.

It should be related to project loading and initialization, but need more info to known what is going wrong.

I added some questions in https://github.com/ionide/ionide-vscode-fsharp/issues/551#issuecomment-330217630 who can help find the issue:

- type of fsproj (old or new). if new, what .net core version (`dotnet --info`)
- check if project was loaded correctly? in the `F# project explorer` -> right click proj -> show error info
- paste here the diagnostic log (see https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting about how to enable it)
