### ISSUE TITLE
F# Language Service (server) crashes on initialization

### ISSUE THREAD

**Issue by n074v41l4bl34u** [ionide/ionide-vscode-fsharp#552]
I have a default installation with the following options set as:

>  "FSharp.logLanguageServiceRequestsOutputWindowLevel": "DEBUG",
>  "FSharp.logLanguageServiceRequests": "both"

**F# Language Service Output prints:**

> Resolving startup promise because FSAC printed the 'listener started' message
> [I] 2017-09-20T01:49:03.5996710Z: listener started in 48.032 ms with binding 127.0.0.1:8851 [Suave.Tcp.tcpIpServer]
> Unhandled error - Object reference not set to an instance of an object. 
>     at FsAutoComplete.CommandResponse.project(FSharpFunc`2 serialize, String projectFileName, FSharpList`1 projectFiles, FSharpOption`1 outFileOpt, FSharpList`1 references, FSharpMap`2 logMap, ExtraProjectInfoData extra, FSharpMap`2 additionals)
>    at <StartupCode$FsAutoComplete-Core>.$Commands.Project@103.Invoke(Unit unitVar)
>    at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)

Any ideas?

**Comment by Krzysztof-Cieslak** [comment]
Run `F#: Clear Cache` command
