### ISSUE TITLE
Project explorer icons not working on mono

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#554]
From @cartermp talk on DotNet Conf

![image](https://user-images.githubusercontent.com/5427083/30722757-40f3a4ca-9f33-11e7-988d-4fee4a40b127.png)

CC: @vbfox

**Comment by vbfox** [comment]
I'll look into it as soon as I'm back on a mac :)

**Comment by vbfox** [comment]
My first guess was correct it's not really a bug more of a missing feature in vscode.

The theme used is vs-set-icon-theme and [they are using icon fonts](https://github.com/Microsoft/vscode/blob/cc732bcb2baed59d004a67fd60feb17c8db3c7f4/extensions/theme-seti/icons/vs-seti-icon-theme.json) instead of svg/png but we can't do that in the contributed tree.

**Comment by vbfox** [comment]
![screen shot 2017-09-24 at 21 13 00](https://user-images.githubusercontent.com/131878/30785838-4eda9c56-a16d-11e7-96ee-c0eaad447102.png)
![screen shot 2017-09-24 at 21 13 17](https://user-images.githubusercontent.com/131878/30785840-50d3f7dc-a16d-11e7-9ab6-299d9a3bf2cb.png)

**Comment by Krzysztof-Cieslak** [comment]
@cartermp, what icon pack do you use in VSCode ?

**Comment by vbfox** [comment]
*If really needed we could do it by creating a canvas, displaying the glyph, saving it to file and providing that to use for vscode but that would upgrade the icons from hack to "hack over a hack with a little hack on the side"*

**Comment by Krzysztof-Cieslak** [comment]
I guess I'll just close it for now. I don't want to do even more hacky solution, and the workaround is simple - just use different icon theme.

**Comment by cartermp** [comment]
@Krzysztof-Cieslak Sorry for not getting back here - I don't use any icon pack ATM.  I used to use one a while back, but it disappeared and I haven't bothered with another since.
