### ISSUE TITLE
Writing code directly to RELP (F# Interactive)

### ISSUE THREAD

**Issue by bilekt3** [ionide/ionide-vscode-fsharp#56]
It might be very helpful to have full ability to write code directly in REPL window and have instant feedback. I do not want to always write something into file to send it into repl. 

I would like experiment in CLI and have benefits of VS code in REPL (autocomplete, docs etc.).

**Comment by Krzysztof-Cieslak** [comment]
It's not really possible with current VSCode extension API. But as far as I know adding REPL support is investigated by VSCode team.

**Comment by Krzysztof-Cieslak** [comment]
@milesfrain, yes. Current implementation of F# REPL is here - https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/Fsi.fs
