### ISSUE TITLE
Failed to start language services on 3.2.0

### ISSUE THREAD

**Issue by yreynhout** [ionide/ionide-vscode-fsharp#562]
![image](https://user-images.githubusercontent.com/142834/30902133-76ce3ee4-a36a-11e7-99b5-984ecafeaa9b.png)

F# Language Service output window displays:

> [09:35:15 ERROR] Failed to start language services. spawn C:\Users\yvesr\.vscode\extensions\Ionide.ionide-fsharp-3.2.0/bin/fsautocomplete.exe ENOENT

When I look into the extension's folder, indeed, there's no `fsautocomplete.exe` in the `bin` folder.

![image](https://user-images.githubusercontent.com/142834/30902335-2b15c6c4-a36b-11e7-8fe7-e25550c34f70.png)

This is what my top level extension folder looks like

![image](https://user-images.githubusercontent.com/142834/30902317-182f42e2-a36b-11e7-9662-80df64ab355c.png)

**Comment by Krzysztof-Cieslak** [comment]
Try to reinstall extension maybe

**Comment by Krzysztof-Cieslak** [comment]
I've just confirmed that package we've released contains all necessary files by downloading `.vsix` file from GitHub releases, changing it to `.zip` and opening. So it sounds like an installation problem for me.

**Comment by yreynhout** [comment]
Yup, can confirm reinstall did the trick.

**Comment by Potmos** [comment]
I would just like to add that Avast loves to think that fsautocomplete.exe is a virus and sometimes delete it without warning.
