### ISSUE TITLE
Error: l is not a function

### ISSUE THREAD

**Issue by davidtme** [ionide/ionide-vscode-fsharp#563]
When trying the new "Debug Default Project" I get the following error:

![image](https://user-images.githubusercontent.com/1804141/30913837-77bc789c-a389-11e7-9b6c-2c823ba94f12.png)

![image](https://user-images.githubusercontent.com/1804141/30913831-70eceb28-a389-11e7-865e-f32de207dfb4.png)

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce, I've also haven't seen anyone else reporting  same problem... 

Is it reproducible? Or just happened once?

**Comment by davidtme** [comment]
@Krzysztof-Cieslak Sadly it happens all the time but my work computer is being flattening and rebuild at the weekend so I'll have a fresh windows install to try again this with.
