### ISSUE TITLE
Change `sln` default behaviour

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#568]
- load the solution if exists only one (like now), **and is in root**
- save the `F#: Change Solution or Workspace` choice between restarts

How to save between restarts:

https://github.com/ionide/ionide-vscode-fsharp/blob/b53b55d9e35777c97d158569bf7dd6be6f3b13bd/src/Components/Degugger.fs#L112-L117

**Comment by Krzysztof-Cieslak** [comment]
That's how we initialize `startup` and `context` variables:
https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/Degugger.fs#L167-L173
