### ISSUE TITLE
Special documentation tags not being stripped from tooltips

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#572]
I'm on Ionide-fsharp 3.3.4 and VSCode 1.16.1

![image](https://user-images.githubusercontent.com/738761/31232520-077594ce-a9e2-11e7-8421-492e717fd0ac.png)

VS2017 for comparison:

![image](https://user-images.githubusercontent.com/738761/31232485-e9acecda-a9e1-11e7-8b5c-26702b076df1.png)

**Comment by ovatsus** [comment]
In VS the params then show up when filling up the parameters:

![image](https://user-images.githubusercontent.com/738761/31232623-583bc61c-a9e2-11e7-9e07-5789253f1d04.png)

**Comment by enricosada** [comment]
related to https://github.com/ionide/ionide-vscode-fsharp/issues/228

**Comment by Krzysztof-Cieslak** [comment]
Nah not really #228. It looks like it's a bug / missing case in our Markdown utils:

https://github.com/ionide/ionide-vscode-fsharp/blob/df48b4e79baea4c4ac020b4e3d7c0b388dea0f90/src/Core/Utils.fs#L163-L188

Since it's fairly easy, I'll mark it as up-for-grabs :-)

**Comment by ovatsus** [comment]
I'll try to fix it then
