### ISSUE TITLE
Can we make the space reserved for type annotations on the AutoComplete box wider?

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#573]
I'm on Ionide-fsharp 3.3.4 and VSCode 1.16.1

Not sure if this is something that Ionide can customize or if it's something hardcoded in VSCode.
With type providers, because the type name is a bit long, the type of members doesn't fit most of the time:

![image](https://user-images.githubusercontent.com/738761/31233376-73434eb0-a9e4-11e7-83ba-45f09fae38f5.png)

I have to always click the (i) to see the rest, but then there's a lot of wasted space on the dropdown it selft and an extra tooltip that wraps to two lines

![image](https://user-images.githubusercontent.com/738761/31233425-84fde1ec-a9e4-11e7-8489-99ff614bd176.png)

VS2017 for comparison:

![image](https://user-images.githubusercontent.com/738761/31233279-2803080a-a9e4-11e7-985e-73c55ec3f5f9.png)

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately it's not something we can control.  So I'm going to close issue.

But one additional pro tip ;) - instead of clicking "i" icon, you can press `Ctrl+space` again to see extra info.
