### ISSUE TITLE
F# keywords don't appear in the autocomplete list

### ISSUE THREAD

**Issue by ezolotko** [ionide/ionide-vscode-fsharp#58]
For example, when typing keyword "with", autocomplete list appears with items like "failWith" etc, and no actual "with" keyword, so I have to hit escape to continue typing.

**Comment by Krzysztof-Cieslak** [comment]
https://github.com/fsharp/FsAutoComplete/issues/108

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.1.0`
