### ISSUE TITLE
FSI window is blank until you resize the panel

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#580]
In the latest VSCode release (orange icon!), when I start FSI (even reset FSI), the contents of the panel are blank until I start to resize the panel vertically (even by 1 px), immediately after which the contents become visible. The only reason I'm raising this in this repo rather than Code is that other panels e.g. console Terminal don't seem to suffer from this issue.

**Comment by Krzysztof-Cieslak** [comment]
I'm pretty sure that's not Ionide issue....

CC: @Tyriar

**Comment by Krzysztof-Cieslak** [comment]
@Tyriar, FYI - "Start FSI" = creating terminal with `window.createTerminal`  and passing path to executable in it.

**Comment by isaacabraham** [comment]
I've also now noticed that resetting FSI sometimes gets into a state when no commands can be sent to it from the code editor - need to reload Code to fix it.

**Comment by Tyriar** [comment]
Looks like https://github.com/Microsoft/vscode/issues/35728

**Comment by Krzysztof-Cieslak** [comment]
Perfect, closing it here since issue is tracked in Code's repo
