### ISSUE TITLE
`.` don't trigger auto completion

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#584]
I just updated to the latest version of Ionide and auto completion isn't trigger by `.` any more. Same, if I start typing a value something.

I need to explicitly use `Ctrl+Space` to get the auto completion box to display. 

## Expected behavior

Have auto-completion trigger by `.` or when starting to write a the word. Get back the same behavior as previous versions.

## Versions

Ionide: 3.5.0
OS: Kubuntu 17.04

**Comment by Krzysztof-Cieslak** [comment]
I can reproduce it - it's probably connected with the fact that `completion` request is send before `parse` request (and hence is getting cancelled on the `parse` request)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.5.1`

**Comment by MangelMaxime** [comment]
Awesome :heart:
