### ISSUE TITLE
Add a command to enable diagnostics and prepare info for report the issue

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#589]
When there are issue, usually FSAC log and env version helps a lot.

Is common for diagnose issue to enable the diagnostic log ( ref https://github.com/ionide/ionide-vscode-fsharp/blob/master/README.md#how-to-get-logs-for-debugging--issue-reporting )

Proposed: 

- add a command `F#: enable diagnostics` or something like that, to enable these props (and `disable` too, if are enabled, to revert back)
- add a command: `F#: get info for diagnostics` who get all info about env (os/mono/msbuild/.netcoresdk) + fsac log.

So that user can code/paste here the info, without multiple steps of Q/A ( an example is https://github.com/ionide/ionide-vscode-fsharp/issues/582 )

**Comment by MangelMaxime** [comment]
I would like to take this issue.
