### ISSUE TITLE
Multiple backtick properties on the same line kills intellisense.

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#59]
This code works fine:

``` fsharp
let x = [ foo.``My Backtick Property``
          foo.``My Other Backtick Property`` ]
```

but if you try to put the code on one line (separated with `;`), intellisense dies: -

``` fsharp
let x = [ foo.``My Backtick Property``; foo.``My Other Backtick Property`` ]
```

**Comment by Krzysztof-Cieslak** [comment]
Sounds like FSAC / FCS problem. CC: @rneatherway

**Comment by rneatherway** [comment]
Can you explain the expected behaviour versus what you are seeing? And exactly what operations you are performing?

**Comment by isaacabraham** [comment]
@rneatherway so when I type the following:- 

```fsharp
let x = [ foo.``My Backtick Property``; foo.``My Other Backtick Property`` ]
```fsharp

intellisense disappears after the ``;`` in the list separator. I have switch to multi-line list elements.

**Comment by rneatherway** [comment]
Seems likely it is the same problem. If it is a problem with FSAC you should be able to reproduce easily by creating a new integration test based on one of the existing ones, just have a single script file containing the relevant text and send completion requests. If you can submit that as a repro I'll have something to work with.

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce on latest. I guess it got accidentally fixed somewhere else

![image](https://user-images.githubusercontent.com/5427083/27284743-56cb4ca4-54fa-11e7-8371-8da93d48d1ae.png)

**Comment by isaacabraham** [comment]
Yes. Instead we now don't get intellisense on backtick members :-(

![image](https://user-images.githubusercontent.com/1781813/27303281-9cfc869e-553a-11e7-84c4-6a4a09b5a448.png)

**Comment by Krzysztof-Cieslak** [comment]
I think that was never a case ;) - another very old issue https://github.com/ionide/ionide-vscode-fsharp/issues/147

**Comment by isaacabraham** [comment]
Should I raise a new issue then?

**Comment by Krzysztof-Cieslak** [comment]
Just add additional sample to #147
