### ISSUE TITLE
StackOverflowException on the Language Service (server)

### ISSUE THREAD

**Issue by vslynko** [ionide/ionide-vscode-fsharp#592]
F# Language Service gives "Process is terminated due to StackOverflowException."
```Running: C:\Users\____\.vscode\extensions\Ionide.ionide-fsharp-3.5.1/bin/fsautocomplete.exe --mode http --port 8397 --hostPID=15084
[I] 2017-10-13T08:29:56.8366022Z: tracking host PID 15084 [FsAutoComplete]
Resolving startup promise because FSAC printed the 'listener started' message
[I] 2017-10-13T08:29:56.8946490Z: listener started in 30.025 ms with binding 127.0.0.1:8397 [Suave.Tcp.tcpIpServer]

Process is terminated due to StackOverflowException.

Process is terminated due to StackOverflowException.

Process is terminated due to StackOverflowException.

Process is terminated due to StackOverflowException.
```
FSharp Language Service 
```
[10:29:57 DEBUG] REQ (002) -> {project}, File = "~\SomeProj.fsproj"
Data={"FileName":"c:\\Users\\____\\Source\\Repos\\SomPathe\\SomeProj.fsproj"}
[10:29:57 DEBUG] RES (002) <- {project} in 288 ms: Kind={"error"}
Data={"Code":1,"Message":"Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''. ","AdditionalData":{}}
[10:29:57 ERROR] Project loading failed, Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.  
```

As the result non of the *.fsproj files in solution are lodade - (load failed)

**Comment by enricosada** [comment]
@vslynko can you add the `.fsproj` there? just the fsproj, not the source files (doesnt matter)

also some info:

- OS
- mono version ( `mono --version` ) if on unix/mac
- .net core version ( `dotnet --info` ) if you are using that

**Comment by vslynko** [comment]
Windows 1703 (OS Build 15063.674)
Mono - not installed
.net core 
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
Here is one of 4 project files that I have:
[ClearingMatrix.zip](https://github.com/ionide/ionide-vscode-fsharp/files/1386645/ClearingMatrix.zip)

**Comment by enricosada** [comment]
I tried locally and load for me:

![image](https://user-images.githubusercontent.com/147243/31604534-e9984890-b263-11e7-87e3-36a3564cd80e.png)

@vslynko can you try do:

- `> F#: Clear Cache`

![image](https://user-images.githubusercontent.com/147243/31604579-0d11c7a6-b264-11e7-8e00-1ba82c4ae4b6.png)

- `> Reload Window`

?

**Comment by vslynko** [comment]
Yes, I tried. It did not help.

**Comment by Krzysztof-Cieslak** [comment]
Do you have MsBuild 14 (2015) installed?

**Comment by vslynko** [comment]
@Krzysztof-Cieslak - to my best knowledge, no, MsBuild 14 is not installed.

**Comment by Krzysztof-Cieslak** [comment]
Readme specifies set of requirements, including MsBuild 14. Installing it should solve the problem.

**Comment by vslynko** [comment]
Adding MSBUILD_PATH var, that I didn't have, but still using MsBuild 15.0 resolved the issue.
Although, somewhere in between I've also installed MsBuild 14, but it's not in environment variable, neither it is in the PATH.
Thanks a lot.
