### ISSUE TITLE
Feature: Optionally keep function declaration visible at top of screen if it would have scrolled out of view

### ISSUE THREAD

**Issue by rmunn** [ionide/ionide-vscode-fsharp#593]
In functions that pattern match across large DUs, such as the `update` function in many Fable.Elmish apps, you can get vertically-large functions like:

```fsharp
let update msg model =
    match msg with
    | Case1 ->
        // Code to handle case 1, about five lines long

    | Case2 ->
        // Code to handle case 2, about ten lines long

    | Case3 ->
        // Code to handle case 3, about five lines long
```

And by the time you're handling case 5 or 6, the top line with the function signature has scrolled off the top of the screen. It would be nice to have the function signature "stick" to the top of the screen when scrolling through a long function. Obviously this will not be desirable in every situation, so it should be controlled by an option in the Ionide settings.

### Use Case

I discovered that I wanted this feature when I used <kbd>Ctrl+Shift+F</kbd> to search for the DU case `Logout` in some Fable demo code that was unfamiliar to me. I found it in the middle of a long function that I suspected was the `update` function, but I had to scroll up to be sure. If I had had the option of asking Ionide to show me the declaration of the function I was currently in the middle of, then I would have been certain without needing to scroll, and my mental workflow wouldn't have been interrupted.

### Workaround

In current versions of Ionide, it can still be possible to "jump" to the current function declaration, if it's top-level in the file (that is, it's not indented, that so the `let f x =` declaration starts at text column 1), even without the "sticky lines" feature I'm requesting. One way to do this is to perform three commands in sequence:

1. **Fold all** (default shortcut <kbd>Ctrl+K Ctrl+0</kbd> on Linux). This will cause the cursor to jump from the current line to the first line of the fold, which will be the declaration of the function the cursor was in.
1. **Unfold all** (default shortcut <kbd>Ctrl+K Ctrl+J</kbd> on Linux). The cursor will stay put on the function declaration. If you want it back where you were:
1. **Go Back** (default shortcut <kbd>Ctrl+Alt+-</kbd> on Linux, which I usually remap to <kbd>Alt+Left</kbd> since browser shortcuts are easier for me to remember). This brings the cursor back to where you were, and you can go on editing the function.

### Which project?

It's possible that this feature could be implemented by VS Code, in which case it would be "show the first line of a large code block if it scrolls off the top of the screen" rather than "keep the function declaration visible". But I think I'm less interested in seeing *any* first line of a large code block, but rather specifically in the function declaration that I'm currently inside.

### Further ideas

Perhaps if the innermost function declaration in the current block of code isn't at the top level of indentation, then more lines than one could be shown. E.g., a large member method inside a class inside a module might show three lines at the top of the screen:

```fsharp
module Foo = // ...
    type BigClass(params) = // ...
        member this.Update moreParams = // ...
            // Those three lines are locked to top of screen
            // Rest of screen scrolls normally
```

Alternately, if we look at code blocks rather than function declarations, all the "parent" lines of the current line could stick to the top of the screen. E.g., in an Elmish-style `update` function, it's likely that the first line of the function is a `match` expression, so if you've scrolled deep into the guts of the function, you might see the following at the top of the screen:

```fsharp
let update msg model = // ...
    match msg, model.SubModel with // ...
        | LoginMsg msg, LoginModel m -> // ...
            // Those three lines are locked to top of screen
            // Rest of screen scrolls normally
```

It's hard to define what a "parent" line would be. If it's defined only by indentation, then it's possible that a VS Code feature (or extension) could do this. But I think it would need to be defined by semantics of F# code, which means this would need to be implemented in Ionide. Thoughts?

**Comment by Krzysztof-Cieslak** [comment]
What would you think about putting current function signature in the status bar at the bottom? Maybe next to the current symbol signature?

Or adding some keyboard shortcut that would switch between current symbol, and current scope for the signature we currently display on the status bar?

**Comment by rmunn** [comment]
Function signature in the status bar sounds like a great idea. It wouldn't fix the one use case where I wanted to see the first line of the `match` expression as well, but it's the simplest solution that would fix 80-90% of the use cases.

And a keyboard shortcut for "jump to current scope declaration" would also be quite useful, in more usage scenarios than the one I just described (can't see the top line). E.g., I'm twenty lines into the function and I discover I need to change the function signature to add one more parameter. If I can hit Ctrl+Shift+something and jump to the function signature, great! I then add the new parameter, hit the Ctrl+Alt+minus shortcut for "Go back", and I'm back in the depths of the function, exactly at the point where I was typing before. No need to reach for the mouse, which means I don't break my flow nearly as much and I can keep my focus on the code.

Both of those ideas sound great. Either one of them would be enough to satisfy me, but I'd love to see both of them.

**Comment by Krzysztof-Cieslak** [comment]
This is partially solved by the VSCode built-in breadcrumbs.
