### ISSUE TITLE
Intellisense doesn't work for new style fsproj targeting .NET target framework on osx/linux (mono)

### ISSUE THREAD

**Issue by duncanmak** [ionide/ionide-vscode-fsharp#597]
https://github.com/duncanmak/azure-functions

I have a project here, it compiles fine after running `msbuild /t:Restore`, `msbuild /t:Build` on Mono 5.4 (Mac). It also opens okay in VS for Mac.

When I open it in VSCode running Ionide, the paket references don't show up and I get red squiggles for all the types I imported via Paket.

![image](https://user-images.githubusercontent.com/4791/31746856-83467de8-b437-11e7-963b-ac3645540f98.png)

**Comment by AkosLukacs** [comment]
I think I have the same issue, just a note: Same project, same code in .fsx looks just fine (refactoring from .fsx to .fs right now), and the build is ok.

Also `#load "Stuff.fs"` and the highlights, etc in fsx works too.

Running Win 10

**Comment by enricosada** [comment]
@duncanmak @AkosLukacs the project loaded correctly? can you check on bottom left, in the `F# project explorer` the project?

there you should see it, and right right click `Show info about failed loading` will add more info

**Comment by enricosada** [comment]
@duncanmak atm ionide to parse that project use .net core cli (the `dotnet`), not `msbuild`.

if you do `dotnet restore` and `dotnet build` works? should fail

Using a .net frameowkr (like `net45` or `net461`) on mono need a workaround ( https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0#using-net-framework-as-targets-framework-the-osxunix-build-fails ) to see the `net461` reference assembly of .NET Framework)

As a note, locally on me on windows works.

![image](https://user-images.githubusercontent.com/147243/31865539-48eda7e8-b770-11e7-89dd-9fe96a6b09bc.png)

**Comment by AkosLukacs** [comment]
Ok, my issue was probably different: a referenced C# project (old-style csproj) did not load correctly. Migrated that csproj to "Microsoft.NET.Sdk", and everything works fine. Sorry for the confusion.
