### ISSUE TITLE
Highlight union cases and active patterns

### ISSUE THREAD

**Issue by cmeeren** [ionide/ionide-vscode-fsharp#599]
Coming from VS 2017, one feature I miss with Ionide in VS Code is coloring of union cases and active patterns. Is this possible to configure? If not, could you consider implementing this?

**Comment by Krzysztof-Cieslak** [comment]
Coloring in Ionide is limited due to the fact that VSCode doesn't have API for semantic highlighting. All the syntax highlighting is based on Regular Expressions and it's difficult to create as good highlighting as in VS

**Comment by cmeeren** [comment]
Seems like things are finally happening: https://github.com/microsoft/vscode/issues/77133
