### ISSUE TITLE
Coloring issues when union case wraps a record type

### ISSUE THREAD

**Issue by cmeeren** [ionide/ionide-vscode-fsharp#600]
Take a look at the following picture. In the definition of `x1`, the `C` case is shown in blue. This is inconsistent with the other examples.

![colorerror](https://user-images.githubusercontent.com/7766733/31760996-c92d0744-b4b6-11e7-91ce-8abe3c16d886.png)

**Comment by Krzysztof-Cieslak** [comment]
Moved to https://github.com/ionide/ionide-fsgrammar/issues/35
