### ISSUE TITLE
False positive "simplify name" code fix

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#601]
Ionide

![image](https://user-images.githubusercontent.com/873919/31762985-94b3c46c-b4c5-11e7-9810-5e4250178be8.png)

VS

![image](https://user-images.githubusercontent.com/873919/31763010-aa1ea4ca-b4c5-11e7-8965-42317fd9b7f5.png)

(note that the feature is turned on in VS (`System` is grayed out))

**Comment by enricosada** [comment]
@Krzysztof-Cieslak  move to https://github.com/fsprojects/FSharpLint ?

**Comment by Krzysztof-Cieslak** [comment]
Simplify name is provided by FSAC (https://github.com/fsharp/FsAutoComplete/pull/230)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.10.1`
