### ISSUE TITLE
Keyword+apostrohpe names in match expressions are colored as keywords

### ISSUE THREAD

**Issue by cmeeren** [ionide/ionide-vscode-fsharp#603]
I have a value named `match'` that I'm performing a pattern match on, and the `match` part of the name (not the apostrophe) is colored as a keyword. This is also the case if I name the value e.g. `return'`.

![image](https://user-images.githubusercontent.com/7766733/31765928-605fbe2c-b4c6-11e7-98ba-2b6affd7ae01.png)

Ionide 3.8.0.

**Comment by Krzysztof-Cieslak** [comment]
Moved to https://github.com/ionide/ionide-fsgrammar/issues/36
