### ISSUE TITLE
Project Explorer: clicking on a file outside the project (/../) collapses the tree

### ISSUE THREAD

**Issue by 0x53A** [ionide/ionide-vscode-fsharp#605]
![a616ef10-3582-4d9a-b84e-19905cc76b88](https://user-images.githubusercontent.com/4236651/31837468-2adff5b4-b5d9-11e7-9903-20eb3eb9e696.gif)

```Xml
    <!-- Common between Server / Client -->
    <Compile Include="../../../Common/Domain.fs" />
    <Compile Include="../../../Common/ServerUrls.fs" />
```

**Comment by Krzysztof-Cieslak** [comment]
Uhhh... I'm using such files and haven't experienced similar problems

**Comment by 0x53A** [comment]
I copied the directory to reduce for a reproduction ...


Now the Project Explorer shows the full path __to the original directory__.

![image](https://user-images.githubusercontent.com/4236651/31837898-d7939eae-b5da-11e7-938c-3a4adeae7d33.png)


(The project is in ___D:\temp\repro#ionide#605\Client\GitToP4Client___).

**Comment by Krzysztof-Cieslak** [comment]
Try `F#: Clear cache` and reload

**Comment by 0x53A** [comment]
In a quick test it happened also with a new project ``dotnet new lib -lang F#``.

But it only collapses if the file was not already open.
If it was already open, then it just switches to the file and everything is ok.

[repro#ionide#605.zip](https://github.com/ionide/ionide-vscode-fsharp/files/1403035/repro.ionide.605.zip)

**Comment by Krzysztof-Cieslak** [comment]
I can repro

**Comment by Krzysztof-Cieslak** [comment]
I can't repro with latest version of plugin. We might have fixed it while making other changes to solution explorer.
