### ISSUE TITLE
Active Pattern is marked as "this value is unused"

### ISSUE THREAD

**Issue by psiLearn** [ionide/ionide-vscode-fsharp#607]
Active Pattern is marked as value not used.
simple example:

```fsharp
    let (|Foo|_|) v = if v = "foo" then Some "foo" else None
    match "fo0" with
    | Foo v -> printfn "%A" v
    | _ -> ()
```

expected behaviour:
no green underlining
observed behaviour:
in the defenition Foo is underlined and marked as this value is not used.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.10.1`
