### ISSUE TITLE
add code lens for `run test` & `debug test`

### ISSUE THREAD

**Issue by ctaggart** [ionide/ionide-vscode-fsharp#609]
This is a feature from OmniSharp that I would love to see in Ionide.

https://youtu.be/BLLt14xOkY8

![image](https://user-images.githubusercontent.com/80104/31861729-1ad6f1ac-b72a-11e7-9feb-861857ff88b7.png)

You can see the related code by checking out what was fixed for this bug:
https://github.com/OmniSharp/omnisharp-vscode/issues/1733

**Comment by americofreitasjr** [comment]
I'm having the same problem in vs-code on Ubuntu. Has this also been resolved? Thank you. See @asilferreira.

**Option "debug test"**
![image](https://user-images.githubusercontent.com/11709838/32255928-e059da9c-be92-11e7-9c5b-9b5a913eba3e.png)


**Error:**
An exception occurred while test discoverer 'VsTestRunner' was loading tests. Exception: Object reference not set to an instance of an object.

**Info:**

xunit version 2.3.1

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by Krzysztof-Cieslak** [comment]
It's something that's part of my work-in-progress separate plugin which maybe will be released (or included in Ionide) in next month or so... I hope.

**Comment by Krzysztof-Cieslak** [comment]
@neptunao Testing integration (Including code lenses) is provided by paid extension I've created - https://github.com/LambdaFactory/Neptune-public
