### ISSUE TITLE
error MSB4057: The target "_Inspect_FscArgs" does not exist in the project

### ISSUE THREAD

**Issue by Alxandr** [ionide/ionide-vscode-fsharp#610]
I started getting this error today. Googling led me to an error on this repository where someone had the same error, but that was about projects being parsed as Sdk projects that were not Sdk projects. I have a Sdk project though. I have 3 such projects that all fail to load.

Also, when I look at the `proj-info.targets`, I see the `_Inspect_FscArgs` target there.

**Comment by enricosada** [comment]
@Alxandr try remove the `obj` dir and redo `dotnet restore`

**Comment by Alxandr** [comment]
Worked :)
Any idea why this is needed?

**Comment by enricosada** [comment]
renamed the project? dunno.
what actions have you done?

anyway i'll improve that (removing the temporary file) with https://github.com/enricosada/dotnet-proj-info/issues/10

**Comment by Alxandr** [comment]
I don't think I did anything in particular. I just came back to the project after a month of not touching it.

**Comment by colinbull** [comment]
As an FYI, I was having this issue. Removing the `obj` dir did nothing. However I had an explicit reference to `FSharp.NET.Sdk` as soon as I removed this and ran `dotnet restore` everything started working.

**Comment by s952163** [comment]
> @Alxandr try remove the obj dir and redo dotnet restore

Yeah, this works!

**Comment by s952163** [comment]
as per the comments above, `dotnet restore` on the CLI, then reload the project in ionide./

> best workflow for big issues is:
> - remove `obj`/`bin` dir (usually also `dotnet clean` works)
> - `dotnet restore`
> - `code .`
> 
> if just deps seems missing from intellisense:
> - `F#: clear cache`
> - `Reload window` (edited)
> 
> 
> s952163 [6:57 PM] 
> yeah, i know, i try to not start new projects in VS2017
> 
> 
> [6:57] 
> ok
> 
> 
> [6:58] 
> i just created a new project in ionide F# New Project
> 
> 
> [6:58] 
> then did `dotnet restore` on the CLI
> 
> 
> [6:58] 
> then `Reload Window` in ionide
> 
> 
> [6:58] 
> it loaded the project
