### ISSUE TITLE
fsharpi input dies intermittently 

### ISSUE THREAD

**Issue by xenocons** [ionide/ionide-vscode-fsharp#615]
Using the command palette, 'FSI: Send Selection' always works.

However, using the keybinding for this (Currently bound to Windows + Enter for me), sometimes stops working. No error occurs, it is as if the keybinding is unbound. When this occurs, using the command palette shortcut works.

This appears to occur randomly, and I haven't a way to reproduce it reliably. 

Environment is mono for fsharpi, running on linux.

**Comment by enricosada** [comment]
you have maybe the search/replace box open?

**Comment by xenocons** [comment]
Hi @enricosada , this indeed, seems to be the problem! When the search box is open (I often leave it open), the send to FSI does not work.

**Comment by Krzysztof-Cieslak** [comment]
I think it's `by-design` for some reason ;-)

**Comment by xenocons** [comment]
When you say by design, do you mean that VsCode causes this problem? If so, should this issue be raised on the vscode repo?

**Comment by Krzysztof-Cieslak** [comment]
Nah, it’s our choice. We’ve defined this behavior in package.json.
