### ISSUE TITLE
Rename Quick Fix does not work with backtick members.

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#617]
The Rename Refactor correctly suggests a rename based on the compiler error. However, the renamed member loses the backticks, which leads to another compiler error:

![ioniderename](https://user-images.githubusercontent.com/1781813/32144872-c1b8a732-bcbf-11e7-8bd0-d25b2dff542f.gif)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.15.4`
