### ISSUE TITLE
[Feature Request] Add 'Generate FSI Scripts' to project explorer

### ISSUE THREAD

**Issue by xenocons** [ionide/ionide-vscode-fsharp#619]
Currently, the command palette offers the ability to generate FSI References from the currently opened project. 

It would be nice to see this command exposed via the F# Project Explorer. This would be consistent with the functionality of F#+VFPT via Visual Studio (in the good old days when F# + Visual Studio actually worked.)

**Comment by Krzysztof-Cieslak** [comment]
Implemented in `3.10.0`
