### ISSUE TITLE
Ionide 3.9.0: failed to start language services

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#620]
With the new Ionide version: 3.9.0

I am having this error when starting VSCode.

> Failed to start language services. Please check if Microsoft Build Tools 2013 are installed

![image](https://user-images.githubusercontent.com/4760796/32163627-2e99ddf6-bd5d-11e7-9d2a-12605cc0f09e.png)

In the *F# Language Service* output I got this message:

> [10:29:03 ERROR] Failed to start language services. spawn C:\Users\mange\.vscode\extensions\Ionide.ionide-fsharp-3.9.0/bin/fsautocomplete.exe ENOENT

In *F# Language Service (Server)* ouput:

> Running: C:\Users\mange\.vscode\extensions\Ionide.ionide-fsharp-3.9.0/bin/fsautocomplete.exe --mode http --port 8312 --hostPID=15328
spawn C:\Users\mange\.vscode\extensions\Ionide.ionide-fsharp-3.9.0/bin/fsautocomplete.exe ENOENT

In *Forge* output: 

> forge refresh --no-prompt
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn C:\\Users\\mange\\.vscode\\extensions\\Ionide.ionide-fsharp-3.9.0\\bin_forge\\Forge.exe","path":"C:\\Users\\mange\\.vscode\\extensions\\Ionide.ionide-fsharp-3.9.0\\bin_forge\\Forge.exe","spawnargs":["refresh","--no-prompt"]}

I installed: https://www.microsoft.com/en-US/download/details.aspx?id=40760 and even with this I got the same error.

I am using: Windows 10

**Comment by Krzysztof-Cieslak** [comment]
Please check if FSAC and Forge exes exist.

**Comment by MangelMaxime** [comment]
Ah...

You are right they were missing. Removing and installing again the plugin fixed it.

Thank you :)

At least I know, I prefer Ionide to Rider. :)
