### ISSUE TITLE
Support "Collapse all" in the code outline view

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#622]
The code outline view, become quickly hard to use when you use classes or nested modules.

![code_outline_collapsable](https://user-images.githubusercontent.com/4760796/32334152-0946fed2-bfea-11e7-92bd-d4c7bdeaf5fc.gif)

I would like to add a button "Collapse all" to the tree view and/or make the "Code outline tree view" collapse by default. It's seems to be the default behaviour for the tree view (see SolutionExplorer, and File explorer for examples).

The problem, is we are regenerating all the tree view element from scratch. So we can't iterate over all the tree item and collapse them. Would you be ok to change the implementation of the "Code outline" to keep a reference to the Tree Items ?

Also, if we make this changes we also could maintain the state of the "Code outline" items when switching from File1 to File2 and going back to File1.

![code_outline_collapsable2](https://user-images.githubusercontent.com/4760796/32334610-2d446652-bfeb-11e7-87d1-e3fab5f73d38.gif)

**Comment by Krzysztof-Cieslak** [comment]
I'm OK with adding a button to collapse all - it should be fairly simple - just generate new tree view with all elements collapsed.

For the default behaviour - if a user pressed collapse all, next view should be generated as collapsed. If a user hasn't (or Ionide is just starting)... maybe we should go with something in between - collapsing types? This should remove most noise, and still give a good overview. 

We could also add setting to control startup behaviour - collapse all, collapse types, don't collapse at all.

**Comment by Krzysztof-Cieslak** [comment]
Since it seems fairly simple, I'm marking it as up-for-grabs ;)

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak Ok thanks for the info. I already have something working more or less in my repo. Will create a PR when ready.
