### ISSUE TITLE
Failed to start language services. Please check if Microsoft Build Tools 2013 are installed

### ISSUE THREAD

**Issue by lambdakris** [ionide/ionide-vscode-fsharp#628]
After a recent Ionide upgrade, I am getting the following message "Failed to start language services. Please check if Microsoft Build Tools 2013 are installed". I do not have Build Tools 2013, but I do have Build Tools 2015, and I thought that was the requirement as per the [Readme: Quick Install instructions] https://github.com/ionide/ionide-vscode-fsharp#quick-install-guide. 

...I also wonder whether it is related to https://github.com/ionide/ionide-vscode-fsharp/issues/577

**OS Version**
Windows 10 1511
**.NET Framework Version**
4.6.1
**.NET Core Version**
2.0
**Ionide Version**
3.11.0

Here is the F# Language Service (server) output
```
Running: C:\Users\cax9124\.vscode\extensions\Ionide.ionide-fsharp-3.11.0/bin/fsautocomplete.exe --mode http --port 8919 --hostPID=9156
spawn C:\Users\cax9124\.vscode\extensions\Ionide.ionide-fsharp-3.11.0/bin/fsautocomplete.exe ENOENT
```

Here is the F# Language Service output
```
[11:22:18 ERROR] Failed to start language services. spawn C:\Users\cax9124\.vscode\extensions\Ionide.ionide-fsharp-3.11.0/bin/fsautocomplete.exe ENOENT
```

**Comment by lambdakris** [comment]
Launching vs code from command line inside project dir did not make a difference

**Comment by Krzysztof-Cieslak** [comment]
Please check if the file `C:\Users\cax9124\.vscode\extensions\Ionide.ionide-fsharp-3.11.0/bin/fsautocomplete.exe` for sure exists. If not try reinstalling extension (and make sure that antivirus or something like that is not messing with installation)

**Comment by lambdakris** [comment]
You were correct, fsautocomplete.exe was missing and the issue went away after re-installing the extension (did not have to adjust antivirus so it must have been a botched extension update). Appreciate your help.

**Comment by daz10000** [comment]
I just got a similar message suddenly.  Was working earlier today and then restarted vscode on a project and it was gone.  i suspect maybe antivirus took it out (avast loves to stomp on fsautocomplete.exe for some reason), but I didn't see it warn me.   Would be nice if the project startup could diagnose this more specifically.  The message MSbuild tools 2013 missing is a real red herring

**Comment by tymokvo** [comment]
This is happening for me after the latest VSCode update. `fsautocomplete.exe` exists in the extensions directory. Have tried reinstalling ionide too.

VSCode info:
```
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063
```

Checking the Language Server log shows:

```
...
It was not possible to find any compatible framework version

The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.

  - Check application dependencies and target a framework version installed at:

      \

  - Alternatively, install the framework version '2.1.0'.
```

Looks like the minimum version is now .NET Core 2.1.0? Not sure how this changed, but it was working before VSCode updated itself this morning for me.

**Comment by MangelMaxime** [comment]
This is probably related to this PR: https://github.com/fsharp/FsAutoComplete/pull/335

**Comment by tymokvo** [comment]
Installing [.NET Core](https://dotnet.microsoft.com/download) runtime > 2.1 (2.1.7) solved this for me. The MSBuild tools message is very confusing. Also annoying that Visual Studio Installer doesn't let you select a version of the runtime to install. 🙄

**Comment by Krzysztof-Cieslak** [comment]
Yes, I think I've silently upgraded the .Net Core requirement, sorry for that. And we definitely should have a better error message in this case. PRs welcomed? ;-)
