### ISSUE TITLE
Auto-open namespace for required type overwrites #load

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#629]
Per the attached video. Brought in one type but the open statement kills a `#load` statement. 
![weird](https://user-images.githubusercontent.com/1781813/32538358-05123a54-c466-11e7-91f9-2421153b7614.gif)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.12.1`

**Comment by isaacabraham** [comment]
Thank you for fixing so quickly.
