### ISSUE TITLE
Backslashes mixed with quotes in @-escaped strings break syntax highlighting

### ISSUE THREAD

**Issue by simra** [ionide/ionide-vscode-fsharp#63]
Repro:
```
let foo = @"""\""" 
```
This represents the string "\" (including quotes).  It looks like Ionide interprets the backslash as escaping the closing quote, and then the subsequent pair of quotes as a second escaped quote, so the full quoted string is never closed. Subsequent lines of code are interpreted by ionide as part of the string.

**Comment by Krzysztof-Cieslak** [comment]
Moved to https://github.com/ionide/ionide-fsgrammar/issues/3
