### ISSUE TITLE
unused local function should not be renamed to `_`

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#630]
Add an unused function

```fsharp
let main _ =
        let isSourceFile (n: string) =
            not(n.StartsWith "-") && n.EndsWith(".fs")
        ()
```

the quick is shown

![image](https://user-images.githubusercontent.com/147243/32542106-ea30f35e-c471-11e7-9149-e54c3834a53e.png)

The `Prefix with _` is ok.
The `Replace with _` is wrong because create an invalid function

```fsharp
        let _ (n: string) =
            not(n.StartsWith "-") && n.EndsWith(".fs")
```

![image](https://user-images.githubusercontent.com/147243/32542272-50160d3a-c472-11e7-9f66-3fcc39db048d.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.15.0`
