### ISSUE TITLE
can user customize Expecto to not use --summary arg

### ISSUE THREAD

**Issue by lust4life** [ionide/ionide-vscode-fsharp#631]
because sometimes just focus on a few tests for testing. when use `--summary`, the output is very verbose.

**Comment by Krzysztof-Cieslak** [comment]
Ionide is printing out whatever Expecto is printing out. Any suggestions to change the Expecto output should be suggested in its repository.

**Comment by lust4life** [comment]
@Krzysztof-Cieslak  what i mean is not change output in expecto itself, but change the default behavior ionide told expecto do. see pr : #647
