### ISSUE TITLE
Suggestion to open a namespace that is already opened

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#632]
It seems like sometimes Ionide offers to open namespaces that are already opened (and will happily open the same namespace again).

![weird](https://user-images.githubusercontent.com/1781813/32554938-ab0eb1fa-c49b-11e7-82a4-a374d8aed44d.gif)

**Comment by enricosada** [comment]
@isaacabraham can you add a repro project? git repo will be the best

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.15.0`
