### ISSUE TITLE
Completion inserts open declaration in a very wrong place

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#636]
![1](https://user-images.githubusercontent.com/873919/32691930-7552db4a-c720-11e7-8f1f-7dc7d5ddf82c.gif)

**Comment by vasily-kirichenko** [comment]
(it works OK in VS)

**Comment by vasily-kirichenko** [comment]
@Krzysztof-Cieslak https://github.com/Microsoft/visualfsharp/blob/6358145209f9fc6d619ea76f76b2f1d78e7e6950/src/fsharp/vs/ServiceAssemblyContent.fs#L971-L996 should help.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.12.3`
