### ISSUE TITLE
Unused declaration code fix suggest wrong identifier

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#637]
![image](https://user-images.githubusercontent.com/873919/32691943-aa444a50-c720-11e7-9e8b-f14df11bc6ab.png)

In this case it should suggest `__` instead. 

It works OK in VS

![image](https://user-images.githubusercontent.com/873919/32691952-dcbd545e-c720-11e7-9e21-4659b9bf20e6.png)

This is a special case and handled in VFT here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/CodeFix/RenameUnusedValue.fs#L70

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.12.4`
