### ISSUE TITLE
Attribute tooltips do not contain full info

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#638]
Code

![image](https://user-images.githubusercontent.com/873919/32692008-c1bfca78-c721-11e7-96a9-46512c1a1d6f.png)

VS

![image](https://user-images.githubusercontent.com/873919/32692003-a3b36db4-c721-11e7-8960-3a87da2ae827.png)

Code 

![image](https://user-images.githubusercontent.com/873919/32692007-b562110a-c721-11e7-8d43-3b860d27af83.png)

VS

![image](https://user-images.githubusercontent.com/873919/32692011-d9e756e8-c721-11e7-8581-4e4b4c3c7cc6.png)

**Comment by 7sharp9** [comment]
Looks like ionide/fsac is using the constructor summary only.  VS is using the constructor summary followed by the type summary.  e.g. for `SealedAttribute`:

```
    /// <summary>Adding this attribute to class definition makes it sealed, which means it may not
    /// be extended or implemented.</summary>
    [<AttributeUsage (AttributeTargets.Class,AllowMultiple=false)>]  
    type SealedAttribute =
        inherit System.Attribute
        /// <summary>Creates an instance of the attribute.</summary>
        /// <returns>The created attribute.</returns>
        new : unit -> SealedAttribute
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/commit/22c02d9239a77e38f878058c9208a4f29dcfbb53
