### ISSUE TITLE
Tooltips do not contain generic parameters specialization

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#639]
VS

![image](https://user-images.githubusercontent.com/873919/32692030-141486ec-c722-11e7-9cbe-b65faaa165f3.png)

Code

![image](https://user-images.githubusercontent.com/873919/32692039-2603cfca-c722-11e7-8f7e-41fb39921180.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.15.0`
