### ISSUE TITLE
Default constructor all colored as type

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#640]
Code 

![image](https://user-images.githubusercontent.com/873919/32702856-fc190496-c7fd-11e7-9c8c-a6f92dd1c4be.png)

VS

![image](https://user-images.githubusercontent.com/873919/32702865-1f9cfe40-c7fe-11e7-86da-3d1d7f6456b9.png)

**Comment by enricosada** [comment]
Closing, moved to https://github.com/ionide/ionide-fsgrammar/issues/38
