### ISSUE TITLE
Using Ionide with 32 bit TypeProviders does not work

### ISSUE THREAD

**Issue by 2moveit** [ionide/ionide-vscode-fsharp#642]
To use the Fsharp.Data TypeProvider for MSACCESS 2016 you need to install either the Access Database Engine 2010 in 32bit or 64bit (Microsoft.ACE.OLEDB.12.0).

Visual Studio runs in 32bit and uses FSI with 32bit that is shipped with Visual Studio so you cannot use the 64bit version of the Access Database Engine otherwise you will get the error: `The Microsoft.ACE.OLEDB.12.0 provider is not registered on the local machine`

The Ionide plugin for VSCode uses FSIANYCPU and as my Window 7 is a 64 bit machine it will run in 64 bit. This will not work with the 32 bit Access Database Engine. You will again get the error `The Microsoft.ACE.OLEDB.12.0 provider is not registered on the local machine`

As a workaround I tried to rename the fsi.exe form the sdk folder (on 64bit Windows it is C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsc.exe) to fsianycpu.exe (so you make it 32 bit) then you can use fsi and msbuild in VScode and Visual Studio. But you will still get red lines saying the `The Microsoft.ACE.OLEDB.12.0 provider is not registered on the local machine`. The same error as mentioned before that you will get when using the wrong 64 bit ADB /32bit VS combination.  
So it looks like the red lines are generated by a tool using anycpu -> 64bit, too. 
Do you know what tool is used for it? Is it e.g. fsautocomplete from the user/.vscode folder that is used for this? There is just one fsautocomplete (anycpu) so you cannot do the workaround by renaming the 32bit exe to the exe file.

In short you currently have three options:
1. User 64bit providers and just use VSCode and you are fine. VS no fun
2. Use 32bit providers and use Visual Studio and you are fine. VSCode no fun
3. Rename the fsi.exe as described and use VS without problems and VSCode with red lines everywhere but it will still compile and you can use the FSI.

If someone is starting with F# often they will come with a C# and Visual Studio background. To help them starting to use the great features of Ionide we should find a solution for this scenario. Otherwise they will not only stop VSCode but also might stop using F# at all as most of the F# Community seems to use Ionide but they are not able to use it in those scenarios.

Any suggestions what to do? Or maybe there is a solution/configuration in Ionide that I missed which just needs a better documentation?

VSCode: 1.18.0
Ionide-FSharp: 3.12.2
VS: 2017
FSharp.Data: 2.4.2

**Comment by enricosada** [comment]
@2moveit 

to change the  `fsi` used you can use this setting

```
  // The path to the F# Interactive tool used by Ionide-FSharp
  "FSharp.fsiFilePath": "",
```

about intellisense (that's by fsautocomplete), i'll check

**Comment by 2moveit** [comment]
Thanks @enricosada for the hint with the settings. I set the settings to:
`"FSharp.fsiFilePath": "C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.1\\Framework\\v4.0\\fsi.exe"`
and it works now without renaming but still the prob with intellisense.

**Comment by enricosada** [comment]
@2moveit issue is fsautocomplete, as you said, fsac is compiled as `AnyCPU`.
i checked but i didnt found a good way to run a .net console app (compiled as `AnyCPU`) as 32bit. There is a workaround using `CorFlags.exe` but is not that good for end users.

please open an issue in https://github.com/fsharp/FsAutoComplete/issues/ maybe we can just compile fsautocomplete.exe as 32bit too (just the exe) so can be bundled in ionide.

**Comment by 2moveit** [comment]
Thanks @enricosada. I've just opened the issue: https://github.com/fsharp/FsAutoComplete/issues/249

**Comment by Krzysztof-Cieslak** [comment]
Closing it here since it's tracked in FSAC repo
