### ISSUE TITLE
New module not picked up in dependent project by intellisense

### ISSUE THREAD

**Issue by mvkra** [ionide/ionide-vscode-fsharp#648]
Steps to reproduce:

- Set up two .NET Core projects (I'm using netstandard2.0 and netcoreapp2.0) and make the netcoreapp project reference the netstandard2.0 one.
- Create a module with a function (1)
- dotnet build
- use (1) in the netcoreapp2.0 project
- build
- create another module with a function in the netstandard project (2)
- try using (2) in the netcoreapp project

The Intellisense doesn't pick up the new module. Restarting VS Code doesn't make it resolve either although "dotnet build" picks up the new code fine. Deleting /obj/fsac.cache in the netcoreapp2.0 project and restarting VS Code fixes the issue.

Wondering if it is possible to "refresh the cache" somehow manually at the very least, or detect a "dotnet build" has occured. I'm using Linux btw. I have noticed the Intellisense for other functions is much faster now; is this fsac.cache new?

**Comment by Krzysztof-Cieslak** [comment]
`fsac.cache` has been around for quite a while, tho we have some known problems with invalidation. There exists command `F#: Clear Cache`. Usually clearing cache and reloading the window fixes the problems.

**Comment by enricosada** [comment]
👍 magic trick for me usually is:

- `F#: Clear cache`
- `Reload window`

this usually helps with most issues about projects/intellisense.

**Comment by mvkra** [comment]
Yep that workaround does make it useable. At least I understand why it's happening and can work around it. Thanks.

If you like I can close the issue; unless you want to address it at some point with more than a workaround.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in 3.14
