### ISSUE TITLE
Option to disable auto-opening namespaces/modules

### ISSUE THREAD

**Issue by nozzlegear** [ionide/ionide-vscode-fsharp#650]
Hey, I'm looking for a way to disable the auto-open feature for namespaces and modules. While I do find it a very useful feature, the fact that the auto-opens are at the top of the intellisense list has led to me accidentally opening namespaces and modules I didn't mean to numerous times.

**Comment by Krzysztof-Cieslak** [comment]
We've recently added `FSharp.externalAutocomplete` setting controlling it.

**Comment by nozzlegear** [comment]
Cool, thank you!
