### ISSUE TITLE
FSharp.lineLens.enabled line lenses can't replace code lense

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-vscode-fsharp#651]
Just tried to use line lenses. But the setting `"FSharp.lineLens.enabled"` has inconsistent effects.
Or did I just not understand the purpose of `"replaceCodeLens"`? Sorry if it is expected behavior.
The code lenses are not away if `"editor.codeLens"` is `true`:

__"never"__: 
![image](https://user-images.githubusercontent.com/259479/33081469-b9ebb3dc-ceda-11e7-8db4-30aeba5e2cb0.png)
__"replaceCodeLens"__:
![image](https://user-images.githubusercontent.com/259479/33081548-e824e0a2-ceda-11e7-9f1b-adeacf2b6242.png)
__"always"__:
![image](https://user-images.githubusercontent.com/259479/33081739-5368f9b6-cedb-11e7-9d2e-5f5b889623ad.png)

VSCode 1.18.1
Ionide: 3.13.0
Windows 10

**Comment by enricosada** [comment]
ref https://github.com/ionide/ionide-vscode-fsharp/wiki/Version-3.0.0#linelenses-inlined-codelenses-replacement

>For now it's disabled by default when code lenses is enabled.

it's not enough to use `replaceCodeLens`, seems you need to add:

```json
    "editor.codeLens": false,
    "FSharp.lineLens.enabled": "replaceCodeLens"
```

**Comment by Krzysztof-Cieslak** [comment]
@enricosada's suggesting is good, indeed. Should be easy fix, marking as up for grabs
