### ISSUE TITLE
Project is been created placed under --no-prompt sub-folder

### ISSUE THREAD

**Issue by xdaDaveShaw** [ionide/ionide-vscode-fsharp#652]
VS Code: 1.18.1
Ionide-fsharp 3.13.0

**Repro Steps**
 - Open a Folder in VS Code
 - Run the `F#: New Project` command
 - Press [Enter] to select `console`
 - Press [Enter] for the Project Directory
 - Type a Project Name

**Expected**
A folder with the Project Name is added to the root of the Open Folder.

**Actual**
A folder with the Project Name is added to a folder called `--no-prompt` in the root of the Open Folder.

**Workaround**
Move the project folder from `--no-prompt` to the root yourself and delete `--no-prompt`.
Edit the following line from the fsproj file:
`<Import Project="..\..\.paket\Paket.Restore.targets" />`
to
`<Import Project="..\.paket\Paket.Restore.targets" />`

**Comment by enricosada** [comment]
added PR #654 to fix this

**Comment by gitnix** [comment]
This is still an issue for me.
Ionide: 3.18.2
VS Code: 1.22.1
Dotnet SDK: 2.1.103
Mono: 5.10.0.160

**Comment by dprokop** [comment]
Same here ^^
