### ISSUE TITLE
An implementation of the file or module 'Controller___3' has already been given

### ISSUE THREAD

**Issue by severisv** [ionide/ionide-vscode-fsharp#657]
I have an F#-project running on .NET Core. I use wildcard imports in my project file like this: 
```xml
<Compile Include="Features/*/Functions/*.fs" />
<Compile Include="Features/*/*.fs" />
```

The project runs fine, but for files that are imported using wildcard and share names with other files, the editor complains that `An implementation of the file or module '<filename>___<number>' has already been given.`

![Screenshot](https://raw.githubusercontent.com/severisv/fsharp-bug-repro/1b2bcf02229b3f937bd5faebde64ac3e3576cd8d/repro.png)

I am using VS Code 1.18.0, .NET Core SDK 2.0.3 and ionide version 3.13.0 on Windows.
My friend running the same setup on OSX also has the issue.

Here's a repro: https://github.com/severisv/fsharp-bug-repro
Note that the error only shows up after having the files in question open for a little while in the editor (and possibly also editing them a little).

**Comment by enricosada** [comment]
I can repro. thx a lot for the amazing repro repo @severisv  , helps a lot!

- opening `Features/App/Controller.fs`
- wait parse is finished
- opening `Features/NewStuff/Controller.fs` => error

**Comment by severisv** [comment]
So I understand this is a problem with the compiler service, but do we have any idea idea when it will be fixed? :)

**Comment by noelmcgrath** [comment]
Having same issue, any fix?

**Comment by Krzysztof-Cieslak** [comment]
I believe this is caused by the globing in `fsproj` file. Fix is not to use globing, as F# depends on the order of files. VS has also disabled globing support for F#.

**Comment by severisv** [comment]
Hey, thanks for replying - sorry I took me so long to check this out.

I'm afraid the error is not caused by wildcard imports:

<img width="1771" alt="fileormodule" src="https://user-images.githubusercontent.com/966063/42870257-9cfaa112-8a77-11e8-8643-7c9aa7c8c3cd.png">

Repro: https://github.com/severisv/fileormodulerepro

(not sure the exact steps to reproduce, but after building, editing both of the Types.fs files and waiting a few seconds it does occur)

OS: Windows 10
VS Code: 1.25.1
Ionide-fsharp: 3.22.3
dotnet sdk: 2.1.302
