### ISSUE TITLE
Does Ionide work with .NET Core? (Mac OS X)

### ISSUE THREAD

**Issue by sivabudh** [ionide/ionide-vscode-fsharp#66]
Hi,

I'm following this tutorial [Getting Started with F# on .NET Core](https://channel9.msdn.com/Events/Build/2016/T661), and when I launched Visual Studio Code + Ionide extension installed, I couldn't get F# REPL to run properly.

I don't have Mono installed as I want to stick with .NET Core.

Is my question too early? Eg. .NET Core is not supported yet by Ionide / Visual Studio Code.

Thanks!

**Comment by takemyoxygen** [comment]
As far as I know, F# on .NET Core is still under development and it's not supported by Ionide, so you need to use Mono. VS Code itself supports .NET Core but only for C#

**Comment by Krzysztof-Cieslak** [comment]
Ionide understands .Net Core projects (both `project.json` and `fsprojs` targeting .Net Core). But you still need to have mono to run language services.

**Comment by sivabudh** [comment]
Just to help others that might stumble upon this issue while Googling.

So I just installed `brew install mono` and now F# REPL works in Visual Studio Code.
