### ISSUE TITLE
Suave template uses net461 on linux as opposed to netcoreapp2.0

### ISSUE THREAD

**Issue by aeshthetic** [ionide/ionide-vscode-fsharp#660]
After using the Ionide Suave template and facing build failures, I realized that wherever I typically expected `netcoreapp2.0` I found `net461` instead. After manually changing all occurrences to `netcoreapp2.0` and reinstalling packages, the project built just fine. If possible, I think the template should be wary of the platform it's running on and decide whether it should use net461 or netcoreapp2.0 accordingly.

**Comment by Krzysztof-Cieslak** [comment]
It’s by design behavior. The problem with building is a bug in `dotnet` CLI workaround described here - https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0.1

**Comment by haf** [comment]
Shouldn't we revisit this, now that people are using the v2.x SDK and we don't have to use this workaround any longer? I just tried creating a Suave site and it failed with:


```
/Users/h/.local/share/dotnetcore/sdk/2.0.2/Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/h/dev/impressionist/Impressionist/Impressionist.fsproj]
```
