### ISSUE TITLE
Projects that fail to open break the FSharp project explorer

### ISSUE THREAD

**Issue by daz10000** [ionide/ionide-vscode-fsharp#662]
I had a broken test project causing it to fail to load.   Once that had happened, I was unable to open any of the subtrees in the project explorer.  More precisely they would briefly open, when the little triangle is clicked, but then close themselves immediately.  You should be able to replicate by taking a solution with more than one project,  break one project (mine was the lower one) trivially, then open the whole folder and see how it affects the fsharp project explorer.   Workaround is to not have broken project files but in real life :(

**Comment by enricosada** [comment]
i can repro. working on it

**Comment by Krzysztof-Cieslak** [comment]
Fix released in `3.14.2`
