### ISSUE TITLE
Type signature not fully rendering in bottom left statusbar

### ISSUE THREAD

**Issue by gerardtoconnor** [ionide/ionide-vscode-fsharp#665]
As mentioned on slack, Type signature not fully rendering in bottom left status bar such that the type/member name renders but its appended signature does not.

If you hover over it, the full type and signature is rendered so specific to how it's rendered in the bar

![capture](https://user-images.githubusercontent.com/5388991/33374334-9dc8d6fc-d4fd-11e7-9abf-c623dcd505c4.PNG)

![capture2](https://user-images.githubusercontent.com/5388991/33374364-c5a26ab2-d4fd-11e7-8ebe-d844bd2f7d02.PNG)

**Comment by Krzysztof-Cieslak** [comment]
I think it should work structured signature info we can get instead of taking first line from tooltips

**Comment by enricosada** [comment]
some hints:

https://github.com/ionide/ionide-vscode-fsharp/blob/5709f05df5a1adba848d15405f32b64a756cc8dd/src/Components/QuickInfo.fs#L34

and

https://github.com/ionide/ionide-vscode-fsharp/blob/5709f05df5a1adba848d15405f32b64a756cc8dd/src/Components/QuickInfo.fs#L51

the `.[0]` is why just the first line of tooltip is shown)
