### ISSUE TITLE
Problem with string evaluation in interactive mode

### ISSUE THREAD

**Issue by cezarypiatek** [ionide/ionide-vscode-fsharp#668]
Hi
I'm observing  a very strange behavior when I'm trying  to evaluate string variable in interactive mode.
For example when I select the following code and press "alt+enter"

```fsharp
"3093	749	3469	142	2049	3537"
```
I see like VSCode is typing this string part after part into console and I hear my laptop speaker beeping. The same situation when I try to past this string directly into console.

![ionide_string](https://user-images.githubusercontent.com/7759991/33515760-57d6f70c-d767-11e7-8ba0-45d4325660c4.gif)

Is this  expected behavior?

**Comment by Krzysztof-Cieslak** [comment]
It's not expected behaviour, obviously. ;-)

I can reproduce.

**Comment by Krzysztof-Cieslak** [comment]
CC: @Tyriar

All we do is calling `sendText` , any idea?

**Comment by Tyriar** [comment]
This is happening because it's literally sending a tab keypress which causes a beep in powershell, this is as designed but if it doesn't make sense to do this I'd like to hear alternative behaviors.

**Comment by Krzysztof-Cieslak** [comment]
Oh, I haven't noticed original strings have tabs in it... 🤦‍♂️ 

I agree, it's "by design"
