### ISSUE TITLE
Referencing a .fs file in a different folder kills all hints & intellisense

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#669]
The following script, `test.fsx` does not show any intellisense, tooltips or code lenses:

```fsharp
#load "../foo.fs"

let x = 5
```
Assume that `foo.fs` is a file living in the folder directly above the script. It doesn't matter if the code in `foo.fs` is valid or not.

![weird](https://user-images.githubusercontent.com/1781813/33525606-4878603a-d833-11e7-8437-b609b162edb2.gif)

There are two "workarounds" I have found that fixes the issue:

1. Move `foo.fs` to the same folder level as `test.fsx`.
2. Renaming `foo.fs` to `foo.fsx`.

However, neither are viable solutions when e.g. working with file dependencies sourced from paket.

**Comment by larjo** [comment]
I have been having the same issue for the last few versions.

My workaround is to include the project's root folder with an absolute path:
`#I "C:/Source/ProjectA"`

Then I can reference packages and load .fs-files with intellisense still working:

`#r @"packages\FSharp.Data\lib\net45\FSharp.Data.dll".`
...

`#load @"Reporting\src\MetaData.fs"`
...

**Comment by turbohz** [comment]
Maybe something has changed since this was reported, but I'm experiencing this issue with a `.fsx` loading a `.fs` in the very same directory, either by using the filename or a relative path.

Using an absolute path fixes the issue.

**Comment by isaacabraham** [comment]
@turbohz I'm noticing it now for .fsx files **even with** absolute paths :-(

**Comment by isaacabraham** [comment]
Ignore that last message - that was because the referenced .fsx file had a relative `#load` in it.

**Comment by isaacabraham** [comment]
Pinging this as it's quite old - just wondering if anything has changed in the ecosystem in this time to fix it - or if not, what steps are required to solve it?

**Comment by isaacabraham** [comment]
@Krzysztof-Cieslak in new Ionide 4 world, is there any chance that this is "fixable"? :-)
![](https://media.giphy.com/media/Q94xQWspTUkShljj8P/giphy.gif)

**Comment by Krzysztof-Cieslak** [comment]
This seems to be working for me

![image](https://user-images.githubusercontent.com/5427083/72642847-98714500-396d-11ea-901e-b9e448ffa9c4.png)

**Comment by Krzysztof-Cieslak** [comment]
Or not

**Comment by Krzysztof-Cieslak** [comment]
Fixed in FSAC, will be in next Ionide release.
