### ISSUE TITLE
No intellisense on OSX

### ISSUE THREAD

**Issue by danslapman** [ionide/ionide-vscode-fsharp#67]
Hi!
I'm facing trouble after mono reinstallation on OSX 10.11.5, intellisense just stopped to work after mono update. Ionide-sharp version is 1.7.0, vscode version is 1.1.1
Mono & fsharpi are in path:
`Daniils-iMac:~ danslapman$ echo $PATH`
`/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin`
`Daniils-iMac:~ danslapman$ which fsharpi`
`/usr/local/bin/fsharpi`
`Daniils-iMac:~ danslapman$ which mono`
`/usr/local/bin/mono`
I also tried to reinstall both the extension in vscode two times, it didn't help.
How to figure out the root of the issue?

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.8.2`

**Comment by danslapman** [comment]
It worked for some time after Ionide update, now all the same
