### ISSUE TITLE
Unused open statement showing wrong information

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#670]
I get a lot of `Unused open statement` messages even though they are being used. 

For example `open Newtonsoft.Json.Serialization` is used by `CamelCasePropertyNamesContractResolver` and yet I get the wiggly green line with the suggestion to remove it:

![image](https://user-images.githubusercontent.com/4580714/33530563-3d695884-d879-11e7-94ef-5857387ef9ea.png)

**Comment by dustinmoris** [comment]
I don't really seem to reproduce it with another project, but when you pull the latest Giraffe code from the master branch and open the `Common.fs` file you will be able to see the issue from the screenshot.

**Comment by dustinmoris** [comment]
By the way I figured out when this is happening now. If you open two modules or namespaces in a file which end with the same name then it always shows the second as unused even though it is used (and therefore required).

The easiest reproduction is:

```
dotnet new console -lang F#
```

Add to the fsproj:

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.*" />
</ItemGroup>
```

then replace everything in Program.fs with:

```fsharp
open Microsoft.AspNetCore.Http.Headers
open Microsoft.Net.Http.Headers


let someFunction (requestHeaders : RequestHeaders) =
    let cookie = requestHeaders.Cookie.ToString()
    let accept = HeaderNames.Accept
    sprintf "%s%s" cookie accept

[<EntryPoint>]
let main _ =
    printfn "Hello World from F#!"
    0
```

You will get the green squiggly line:

![image](https://user-images.githubusercontent.com/4580714/36066814-d2ade90e-0ea8-11e8-9512-e6b4ee491e55.png)

But when I remove it my code breaks:

![image](https://user-images.githubusercontent.com/4580714/36066820-e4e04c02-0ea8-11e8-99f5-e4b3cb26806d.png)

**Comment by Szer** [comment]
It marks only last open statement
For example on this picture it shows `Microsoft.AspNetCore.Http` is unsed. Commenting this open will produce error with `HttpRequest` type

![image](https://user-images.githubusercontent.com/10308233/41774544-d2f5df9c-7628-11e8-8522-aaef4d4e27e6.png)

Lets switch two last open statements:
![image](https://user-images.githubusercontent.com/10308233/41774602-0ddab93e-7629-11e8-8332-5caf6b4e0f5c.png)

Now another open is being marked. Commenting it will produce error on `AuthorizationLevel` enum.

This is the project with only one package installed: `Microsoft.NET.Sdk.Functions`
