### ISSUE TITLE
"Generate Refefences For FSI" command generate invalid reference if project is targeting .net core/standard

### ISSUE THREAD

**Issue by oleksandr-bilyk** [ionide/ionide-vscode-fsharp#671]
In VSCode I clicked "Generate references for FSI" and got long references.fsx file.
In the first line of this file which looks like below I have error:

```
#r @"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\Microsoft.CSharp.dll"
error FS0193: The module/namespace 'System.IO' from compilation unit 'System.Runtime' did not contain the namespace, module or type 'FileStream'
```

What can I do to fix it?

I have console application and want to have few satellite tools scripts. I could to ref  Console application "*.fs" files directly but found this magic references generator. Does anyone use it without problems?

Steps to reproduce:

- You may download my project from https://1drv.ms/u/s!AgszF6pgNgsShrYPwm0GKCXmdoStDQ
- In VSCode execute "Paket: Install" to restore packages.
- "Generate references for FSI" and you will see error in first line:
    ```
    "The module/namespace 'System.IO' from compilation unit 'System.Runtime' did not contain the 
    namespace, module or type 'FileStream'"
    ```

**Comment by enricosada** [comment]
Thanks @oleksandr-bilyk .

So .net core projects cannot be used to send references to FSI, because FSI support only .NET Framework.

The only way to fix it atm is to disable (make it hidden) the `Generate references for FSI` for project targeting .net core or .net standard.

**Comment by oleksandr-bilyk** [comment]
Disabling may make VSCode slower. IMHO just show error "Cannot generate FSI references for .NET Core project" will be enough.

**Comment by enricosada** [comment]
Some coding notes:

commands are defined here https://github.com/ionide/ionide-vscode-fsharp/blob/2139f2df555a994e1361a0b4cbe9e764c3e7105f/release/package.json#L91-L98

so the interested command are 

- `fsi.SendProjectReferences` , implemented https://github.com/ionide/ionide-vscode-fsharp/blob/80902953efd62e8db448d14871f8657aa8a5be75/src/Components/Fsi.fs#L138-L141

- `fsi.GenerateProjectReferences` implemented https://github.com/ionide/ionide-vscode-fsharp/blob/80902953efd62e8db448d14871f8657aa8a5be75/src/Components/Fsi.fs#L155

after the `Project.tryFindLoadedProjectByFile`, you have the Project. that record contains the info if is a .net core project or not.
properties are https://github.com/ionide/ionide-vscode-fsharp/blob/80902953efd62e8db448d14871f8657aa8a5be75/src/Core/DTO.fs#L166-L167

**Comment by Krzysztof-Cieslak** [comment]
The potential fix should apply to both `FSI: Generate script file with references from project` and `FSI: Send references from project` commands.

**Comment by Krzysztof-Cieslak** [comment]
This should work now just fine when targetting `dotnet fsi`
