### ISSUE TITLE
How do I get VSCode to recognize other files without a project file

### ISSUE THREAD

**Issue by axu2** [ionide/ionide-vscode-fsharp#676]
![image](https://user-images.githubusercontent.com/20757319/33910503-f4898d60-df5c-11e7-92f6-7ede6ce47b23.png)

I want to get my code to recognize the stuff in other files but I'm not sure how.

Also, is this even the right place to post this question?

**Comment by enricosada** [comment]
you are missing the project file, the one with extension `.fsproj`. that's the most common way to use multiple files (and libraries/options)

or you compile these files manually throught `fsc` (the compiler) ?

**Comment by axu2** [comment]
How do I make the .fsproj file?

I'm making do with compiling manually but this is not ideal...

**Comment by enricosada** [comment]
@axu2 you can follow these guides:

- https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode
- https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line
