### ISSUE TITLE
vscodevim plugin breaks ionide

### ISSUE THREAD

**Issue by Ran4** [ionide/ionide-vscode-fsharp#678]
### Problem
Ionide doesn't work when the vscodevim plugin is installed

### How to reproduce

1. Install vs code
2. Install the ionide plugin
3. Open an fsharp file. E.g. the ionide hover-over works, and shows type signatures and documentation.
4. Install the vscodevim plugin
5. Now ionide is broken. It might work for a few seconds at most, then it will crash and never properly resume again.

#### Version info

    VS Code version: 1.18.1
    vscodevim plugin version: 0.10.6
    OS: Windows 10 (version 1511, OS Build 10586.1295)

Note: My settings.json file is empty

**Comment by enricosada** [comment]
Cannot repro.

can you please attach some logs?

info about how enable it in https://github.com/ionide/ionide-vscode-fsharp/blob/master/README.md#how-to-get-logs-for-debugging--issue-reporting

The `Help -> Toggle Developer Tools -> console tab` log will be nice too.
