### ISSUE TITLE
Ionide on .NET Core (without Mono)

### ISSUE THREAD

**Issue by ctaggart** [ionide/ionide-vscode-fsharp#68]
I added VSCode and Ionide to the .NET Core Docker image. Here is my current evaluation of it:

* https://youtu.be/qjH1yaWcUHI
* https://github.com/ctaggart/dotnet-vscode/issues/3#issuecomment-221028292

Terrific work so far!

**Comment by Krzysztof-Cieslak** [comment]
Thanks! :)
