### ISSUE TITLE
Expecto Build fails when there are spaces in the project path

### ISSUE THREAD

**Issue by jzworkman** [ionide/ionide-vscode-fsharp#680]
https://github.com/ionide/ionide-vscode-fsharp/blob/212312f4895de8d26eadee94509bda0eb8115f7d/src/Components/Expecto.fs#L242

Having my project in the following path fails: C:/Source Code/Project

If I switch it to C:/SourceCode/Project then it works fine. 

Output:
MSBUILD : error MSB1008: Only one project can be specified.

This seems to be the case because the project path is not being quoted during the call to msbuild.

**Comment by Krzysztof-Cieslak** [comment]
Should be fairly simple fix, marking as up-for-grabs
