### ISSUE TITLE
Add warning if `.fs` file doesn't belong to any project

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#681]
Usually `.fs` files should belong to project, `.fsx` files are used standalone. The additional warning may be useful against the typos (wrongly named file/wrong include entry in project file) or as an information for new F# users.

**Comment by 7sharp9** [comment]
For orphaned files in MonoDevelop we used to treat them as an fsx for parsing or type checking.

**Comment by enricosada** [comment]
Lots of time, is more an user error because ppl forget to add it to fsproj or add the wrong name/path.

so a warning message is more than welcome

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/ionide/ionide-vscode-fsharp/commit/eb47479d070a186381fea336e416c35e5306c7b3
