### ISSUE TITLE
Inline generic parameters in tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#685]
![image](https://user-images.githubusercontent.com/873919/34319163-17f1db30-e7ec-11e7-87f3-f9a527591c62.png)
![image](https://user-images.githubusercontent.com/873919/34319165-3b635e72-e7ec-11e7-8cc3-6aa639e32f01.png)

It'd be much more readable if the generic parameters concrete types were just inlined into the signature itself, like C# editors do. I.e. the above signature should look like this:

![image](https://user-images.githubusercontent.com/873919/34319183-cc849e2a-e7ec-11e7-92db-8f94e9a75cd1.png)

Or maybe something like `Flow<'t: int, 'u: int, 'mat: obj>` would be even better.

**Comment by isaacabraham** [comment]
I would imagine that we would keep the argument names though (in your sample screenshot they appear to have been removed)?

**Comment by Krzysztof-Cieslak** [comment]
We can do this.

**Comment by vasily-kirichenko** [comment]
@isaacabraham yes, the latter screenshot is real :) 

I do think that `Flow<'t: int, 'u: int, 'mat: obj>` is the best approach. 

@Krzysztof-Cieslak how are you gonna do this (don't tell me by text replace :)?

**Comment by Krzysztof-Cieslak** [comment]
By text replace

**Comment by Krzysztof-Cieslak** [comment]
:)

**Comment by isaacabraham** [comment]
@vasily-kirichenko What I meant was, I'd like to keep the argument names rather than just the types. But yes, showing concrete types is nice.

**Comment by enricosada** [comment]
i 👎 this. a lot.

while is nice in c#, in f# ihmo is bad

- type def can become really really long. just one nested generic and become really bad
- lot of repetition
- doesnt with the generic signature, if reusing same type for multiple generic args in that instance
- layour is easier with current `'t` and `'t: int` below

**Comment by 7sharp9** [comment]
This is probably an artifact of inference anyway, the flow function, if polymorphic, accepts arbitrary types, its probably clearer is they are not made rigid in the function definition.

**Comment by Krzysztof-Cieslak** [comment]
I think I like current state of the tooltips, and this would have some disadvantages as mentioned by @enricosada
