### ISSUE TITLE
Intellisense is wrong when dotting into an "inline" expression.

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#686]
When you "dot into" an symbol you get correct intellisense immediately e.g.

```fsharp
let x = "foo"
```

Dotting into `x` here works without a problem. However, dotting into the string `"foo"` directly gives incorrect intellisense suggestions. However, if you "force" intellisense with `ctrl` + `space`, you get the correct intellisense!

This is especially annoying when working with e.g. chained method calls or fluent APIs etc.. In the video clip below, the first time intellisense is suggested, it's from simply "dotting into" the string, and is incorrect. The second time, I use `ctrl` + `space` on the same value, which works. Lastly, I bind the string to the symbol `x` and dot into that - this also works.

![weird](https://user-images.githubusercontent.com/1781813/34319619-42d012ae-e7e7-11e7-9b1e-5dfebfb9b395.gif)

**Comment by Krzysztof-Cieslak** [comment]
We even have `TODO` comment about that in FSAC - https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete/FsAutoComplete.Suave.fs#L59

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.28.0`
