### ISSUE TITLE
function signatures (codelens) are not shown

### ISSUE THREAD

**Issue by pronetag** [ionide/ionide-vscode-fsharp#687]
In previous version it is showing function signature here but now it cannot!

![image](https://user-images.githubusercontent.com/3295084/34332484-f61c82fe-e96b-11e7-9986-7fa2302d2a13.png)

**Comment by pronetag** [comment]
IntelliSense also not working...

below are the logs..


[16:50:16 DEBUG] REQ (003) -> {project}, File = "~\AdventOfCode2017\AdventOfCode2017.fsproj"
Data={"FileName":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\AdventOfCode2017.fsproj"}
[16:50:16 DEBUG] RES (003) <- {project} in 24 ms: Kind={"project"}
Data={"Project":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\AdventOfCode2017.fsproj","Files":["c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\AdventOfCode2017.fs"],"Output":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\bin\\Debug\\net461\\AdventOfCode2017.exe","References":["C:\\Users\\28851642\\.nuget\\packages\\fsharp.core\\4.2.3\\lib\\net45\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Data.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Drawing.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.IO.Compression.FileSystem.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Runtime.Serialization.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Xml.Linq.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Xml.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{},"OutputType":"exe","Info":{"SdkType":"dotnet/sdk","Data":{"IsTestProject":false,"Configuration":"Debug","IsPackable":true,"TargetFramework":"net461","TargetFrameworkIdentifier":".NETFramework","TargetFrameworkVersion":"v4.6.1","RestoreSuccess":true,"TargetFrameworks":[],"RunCmd":{"Command":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\bin\\Debug\\net461\\AdventOfCode2017.exe","Arguments":""},"IsPublishable":true}},"AdditionalInfo":{}}
[16:50:16 DEBUG] REQ (004) -> {parse}, File = "~\AdventOfCode2017\HelloWorld.fsx"
Data={"FileName":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\HelloWorld.fsx","IsAsync":true,"Lines":["let CheckDigitMod10 (imei:string) = \r","    (imei\r","    |> Seq.map (string >> int)\r","    |> Seq.mapi (fun i e -> if i % 2 = 0 then e elif e * 2 > 9 then e * 2 - 9 else e * 2)\r","    |> Seq.sum) % 10 = 0\r","\r","let check (i:string) = (i |> Seq.map (string>>int) |> Seq.mapi (fun i e -> if i % 2 = 0 then e elif e * 2 > 9 then e * 2 - 9 else e * 2) |> Seq.sum) % 10 = 0\r","\r","let result = check \"356579075303613\"\r","\r",""],"Version":1}
[16:50:16 DEBUG] REQ (005) -> {declarations}, File = "~\AdventOfCode2017\HelloWorld.fsx"
Data={"FileName":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\HelloWorld.fsx","Lines":["let CheckDigitMod10 (imei:string) = \r","    (imei\r","    |> Seq.map (string >> int)\r","    |> Seq.mapi (fun i e -> if i % 2 = 0 then e elif e * 2 > 9 then e * 2 - 9 else e * 2)\r","    |> Seq.sum) % 10 = 0\r","\r","let check (i:string) = (i |> Seq.map (string>>int) |> Seq.mapi (fun i e -> if i % 2 = 0 then e elif e * 2 > 9 then e * 2 - 9 else e * 2) |> Seq.sum) % 10 = 0\r","\r","let result = check \"356579075303613\"\r","\r",""],"Version":0}
[16:50:17 DEBUG] RES (005) <- {declarations} in 105 ms: Kind={"declarations"}
Data=[{"Declaration":{"UniqueName":"HelloWorld_1_of_1","Name":"HelloWorld","Glyph":"Module","GlyphChar":"N","IsTopLevel":true,"Range":{"StartColumn":1,"StartLine":1,"EndColumn":1,"EndLine":11},"BodyRange":{"StartColumn":1,"StartLine":1,"EndColumn":37,"EndLine":9},"File":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\HelloWorld.fsx","EnclosingEntity":"M","IsAbstract":false},"Nested":[{"UniqueName":"HelloWorld_1_of_1","Name":"CheckDigitMod10","Glyph":"Field","GlyphChar":"F","IsTopLevel":false,"Range":{"StartColumn":5,"StartLine":1,"EndColumn":25,"EndLine":5},"BodyRange":{"StartColumn":5,"StartLine":1,"EndColumn":25,"EndLine":5},"File":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\HelloWorld.fsx","EnclosingEntity":"M","IsAbstract":false},{"UniqueName":"HelloWorld_1_of_1","Name":"check","Glyph":"Field","GlyphChar":"F","IsTopLevel":false,"Range":{"StartColumn":5,"StartLine":7,"EndColumn":158,"EndLine":7},"BodyRange":{"StartColumn":5,"StartLine":7,"EndColumn":158,"EndLine":7},"File":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\HelloWorld.fsx","EnclosingEntity":"M","IsAbstract":false},{"UniqueName":"HelloWorld_1_of_1","Name":"result","Glyph":"Field","GlyphChar":"F","IsTopLevel":false,"Range":{"StartColumn":5,"StartLine":9,"EndColumn":37,"EndLine":9},"BodyRange":{"StartColumn":5,"StartLine":9,"EndColumn":37,"EndLine":9},"File":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\HelloWorld.fsx","EnclosingEntity":"M","IsAbstract":false}]}]
[16:50:17 DEBUG] RES (004) <- {parse} in 434 ms: Kind={"info"}
Data="Request cancelled (exn was System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.\r\nFile name: 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'\r\n   at Microsoft.FSharp.Compiler.CompileOps.GetDefaultSystemValueTupleReference()\r\n   at Microsoft.FSharp.Compiler.CompileOps.DefaultReferencesForScriptsAndOutOfProjectSources@1805.GenerateNext(IEnumerable`1& next)\r\n   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()\r\n   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)\r\n   at Microsoft.FSharp.Compiler.CompileOps.BasicReferencesForScriptLoadClosure(Boolean useFsiAuxLib, Boolean assumeDotNetFramework)\r\n   at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.CreateScriptSourceTcConfig[a](Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, CodeContext codeContext, Boolean useSimpleResolution, Boolean useFsiAuxLib, FSharpOption`1 basicReferences, FSharpFunc`2 applyCommandLineArgs, Boolean assumeDotNetFramework)\r\n   at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.GetFullClosureOfScriptSource(CompilationThreadToken ctok, Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, String source, CodeContext codeContext, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCommmandLineArgs, Boolean assumeDotNetFramework)\r\n   at Microsoft.FSharp.Compiler.CompileOps.LoadClosure.ComputeClosureOfSourceText(CompilationThreadToken ctok, Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, String source, CodeContext implicitDefines, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCompilerOptions, Boolean assumeDotNetFramework)\r\n   at <StartupCode$FSharp-Compiler-Service>.$Service.GetProjectOptionsFromScript@2728-2.Invoke(ErrorScope _arg30)\r\n   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableBuilder.Using[c,d](c resource, FSharpFunc`2 e)\r\n   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.delay@751.Invoke(CancellationToken ct)\r\n   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@174-2.Invoke(CompilationThreadToken ctok)\r\n\r\nWRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n)"
[16:52:35 DEBUG] REQ (006) -> {project}, File = "~\AdventOfCode2017\AdventOfCode2017.fsproj"
Data={"FileName":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\AdventOfCode2017.fsproj"}
[16:52:35 DEBUG] RES (006) <- {project} in 27 ms: Kind={"project"}
Data={"Project":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\AdventOfCode2017.fsproj","Files":["c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\AdventOfCode2017.fs"],"Output":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\bin\\Debug\\net461\\AdventOfCode2017.exe","References":["C:\\Users\\28851642\\.nuget\\packages\\fsharp.core\\4.2.3\\lib\\net45\\FSharp.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Core.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Data.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Drawing.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.IO.Compression.FileSystem.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Numerics.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Runtime.Serialization.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Xml.Linq.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.Xml.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\System.dll","C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.1\\mscorlib.dll"],"Logs":{},"OutputType":"exe","Info":{"SdkType":"dotnet/sdk","Data":{"IsTestProject":false,"Configuration":"Debug","IsPackable":true,"TargetFramework":"net461","TargetFrameworkIdentifier":".NETFramework","TargetFrameworkVersion":"v4.6.1","RestoreSuccess":true,"TargetFrameworks":[],"RunCmd":{"Command":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\bin\\Debug\\net461\\AdventOfCode2017.exe","Arguments":""},"IsPublishable":true}},"AdditionalInfo":{}}
[16:52:35 DEBUG] REQ (007) -> {parse}, File = "~\AdventOfCode2017\HelloWorld.fsx"
Data={"FileName":"c:\\Lime\\Projects\\FSharp Projects\\AdventOfCode2017\\HelloWorld.fsx","IsAsync":true,"Lines":["let CheckDigitMod10 (imei:string) = \r","    (imei\r","    |> Seq.map (string >> int)\r","    |> Seq.mapi (fun i e -> if i % 2 = 0 then e elif e * 2 > 9 then e * 2 - 9 else e * 2)\r","    |> Seq.sum) % 10 = 0\r","\r","let check (i:string) = (i |> Seq.map (string>>int) |> Seq.mapi (fun i e -> if i % 2 = 0 then e elif e * 2 > 9 then e * 2 - 9 else e * 2) |> Seq.sum) % 10 = 0\r","\r","let result = check \"356579075303613\"\r","\r",""],"Version":1}
[16:52:35 DEBUG] RES (007) <- {parse} in 9 ms: Kind={"info"}
Data="Request cancelled (exn was System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.\r\nFile name: 'System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'\r\n   at Microsoft.FSharp.Compiler.CompileOps.GetDefaultSystemValueTupleReference()\r\n   at Microsoft.FSharp.Compiler.CompileOps.DefaultReferencesForScriptsAndOutOfProjectSources@1805.GenerateNext(IEnumerable`1& next)\r\n   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()\r\n   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)\r\n   at Microsoft.FSharp.Compiler.CompileOps.BasicReferencesForScriptLoadClosure(Boolean useFsiAuxLib, Boolean assumeDotNetFramework)\r\n   at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.CreateScriptSourceTcConfig[a](Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, CodeContext codeContext, Boolean useSimpleResolution, Boolean useFsiAuxLib, FSharpOption`1 basicReferences, FSharpFunc`2 applyCommandLineArgs, Boolean assumeDotNetFramework)\r\n   at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.GetFullClosureOfScriptSource(CompilationThreadToken ctok, Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, String source, CodeContext codeContext, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCommmandLineArgs, Boolean assumeDotNetFramework)\r\n   at Microsoft.FSharp.Compiler.CompileOps.LoadClosure.ComputeClosureOfSourceText(CompilationThreadToken ctok, Resolver legacyReferenceResolver, String defaultFSharpBinariesDir, String filename, String source, CodeContext implicitDefines, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCompilerOptions, Boolean assumeDotNetFramework)\r\n   at <StartupCode$FSharp-Compiler-Service>.$Service.GetProjectOptionsFromScript@2728-2.Invoke(ErrorScope _arg30)\r\n   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableBuilder.Using[c,d](c resource, FSharpFunc`2 e)\r\n   at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.delay@751.Invoke(CancellationToken ct)\r\n   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@174-2.Invoke(CompilationThreadToken ctok)\r\n\r\nWRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n)"

**Comment by pronetag** [comment]
After I copied the System.ValueTuple.dll from the F# 4.1 dir (C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0) to C:\Users{MyUser}.vscode\extensions\Ionide.ionide-fsharp-3.15.6\bin, the issue was solved.

![image](https://user-images.githubusercontent.com/3295084/34454558-af5eb9fe-eda8-11e7-89cb-2c10ec5ee251.png)

**Comment by HoraceGonzalez** [comment]
@pronetag, I believe this was fixed in 3.15.7 per https://github.com/ionide/ionide-vscode-fsharp/issues/683. Would you mind verifying?
