### ISSUE TITLE
"New Project (ProjectScaffold)" fails silently on existing git repositories

### ISSUE THREAD

**Issue by CameronAavik** [ionide/ionide-vscode-fsharp#689]
## Steps to reproduce:

1. Create new directory
2. Run `git init` inside that directory
3. Open the directory in vscode with the Ionide plugin installed
4. In the Command Palette, run "New Project (ProjectScaffold)"

## Expected:
A Project Scaffold template is created inside the current directory

## Actual:
A popup/toast notification appears saying "Project created", however no project was created. When looking at the Forge output window in vscode I see the following error:

```
forge new scaffold --no-prompt
Cloning project scaffold...
C:\Program Files\Git\cmd\git.exe clone -b master --single-branch https://github.com/fsprojects/ProjectScaffold.git "d:\Projects\IssueRepro"
Unhandled error:
Could not run "git clone -b master --single-branch https://github.com/fsprojects/ProjectScaffold.git "d:\Projects\IssueRepro"".
Error: 
fatal: destination path 'd:\Projects\IssueRepro' already exists and is not an empty directory.
```

## Other information:
* VS Code 1.20.0-insider
* Ionide-fsharp 3.15.6

**Comment by Krzysztof-Cieslak** [comment]
Fixed by d20f30b64b30d72002dd0a46389721a8892dd55c
