### ISSUE TITLE
Not parsing file

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#692]
Why is not my F# file being parsed? Completed with Ionide?

The language server log is filled with messages like:

```
[11:54:59 DEBUG] RES (045) <- {tooltip} in 4 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/DTOs.fs' not parsed","AdditionalData":{}}
[11:54:59 ERROR] Cannot execute tooltip, File '/DTOs.fs' not parsed 
```

Ionide 3.15.7, Mono v5.4
  
Then I restart, now I do get parse information, but it can't resolve any symbols:

<img width="404" alt="screen shot 2018-01-10 at 11 58 55" src="https://user-images.githubusercontent.com/193115/34769296-b1c397a2-f5fd-11e7-8571-efbbab8b5923.png">

**Comment by enricosada** [comment]
@haf the project parsing is correct? is old or new sdk?

Can you post here the diagnostic message of the log about project parsing (or if not possible, the `F# solution explorer` on bottom left).

Also, can you try

```
> F# Clear cache`
Reload Window
```

**Comment by haf** [comment]
I've tried clear cache, it makes no difference.

I don't know about the project parsing. I'm not using .net core in this case either, so what SDK are you referring to?

**Comment by haf** [comment]
I've sent you the log over Skype, don't want it indexed by google.

**Comment by haf** [comment]
Solving the msbuild issue gives errors like:

```
 error FS0039: The field, constructor or member 'create' is not defined
```

Despite:

<img width="953" alt="screen shot 2018-01-10 at 12 19 30" src="https://user-images.githubusercontent.com/193115/34770209-931e1810-f600-11e7-99be-b4cdc1fcc23c.png">

**Comment by haf** [comment]
So the core issue was an old F# targets-file import.

The real issue here is that there was no way of knowing that unless you knew to look in the "msbuild" output pane; it didn't show up in the F# output pane.

The third issue is that HTTP.fs contains a type and a DU of the same name, and the above intellisense is faultily for the type, but the compiler selects the DU-case name (for some reason) which of course doesn't have any functions on it.

**Comment by enricosada** [comment]
> The real issue here is that there was no way of knowing that unless you knew to look in the "msbuild" output pane; it didn't show up in the F# output pane.

ok added https://github.com/ionide/ionide-vscode-fsharp/issues/693 to track the help user in that scenario.

> The third issue is that HTTP.fs contains a type and a DU of the same name, and the above intellisense is faultily for the type, but the compiler selects the DU-case name (for some reason) which of course doesn't have any functions on it.

can you open a bug in https://github.com/Microsoft/visualfsharp/issues ? with a minimal repro if possibile, so can be possibile to cross check VS/rider if is a FCS bug or not

Closing after vf# issue is created.

**Comment by haf** [comment]
I think someone just did https://github.com/Microsoft/visualfsharp/issues/4185
