### ISSUE TITLE
Add hint for user when project load fails, so opening a .fs will not work

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#693]
in the https://github.com/ionide/ionide-vscode-fsharp/issues/692#issuecomment-356576215 an issue was a failed project loading.
there was no error, just a type not found error => caused by a .fs file not parsed => caused by project load failed. 
Root cause was not easy to untangle.

User didnt see the error about project parsing, because is buried in:

- `F# language service` log = >a panel not with always focused.
    - some project cracker errors show up there
    - diagnostic mode is not enabled by default
- `F# Solution Explorer` => collapsed by default, and hard to spot (bottom left, with others too usually)

To make more visible is possibile to add an info/warning message notification when all projects loading is complected, but there is a failure. Something like

```
Error loading project(s), see msbuild log panel and/or f# solution explorer on bottom left + right click [Dismiss][Link for more info]
```

Adding a `[Link for more info]` button to open ionide docs about how to diagnose this common scenario

**Comment by MangelMaxime** [comment]
I think #857 solved this issue
