### ISSUE TITLE
Integrate fsdn.azurewebsites.net as command

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#695]
the http://fsdn.azurewebsites.net/ website is awesome to search for stuff

Proposed

BASIC a command `F#: FSDN` who open a searchbox, and results as list.

BEST: integrated as command, like intellisense, based on current type for input

```
let x = [1;2;3] //x is an 'int list'
```

right click on `x` -> FSDN, and use type of `x` as input, and in search box just the expected return type.

/cc @pocketberserker @kekyo @hafuu

**Comment by alanmbarr** [comment]
I'd like to claim this issue for FSharp Foundation mentorship project.

**Comment by Krzysztof-Cieslak** [comment]
Sounds good to me!

**Comment by alanmbarr** [comment]
I'm trying to build the project but cannot seem to succeed on multiple systems. https://ci.appveyor.com/project/alanmbarr/ionide-vscode-fsharp/build/1.0.4
I keep getting a git tag error? Any suggestions?

**Comment by enricosada** [comment]
this is hoogle (haskell similar to fsdn) integration 

by @7Sharp9

I had highlighted `zip`, then `shift option h` would show this:

https://files.slack.com/files-pri/T0432GV8P-F9E4BSNE4/screen_shot_2018-02-26_at_11.43.22.png

**Comment by enricosada** [comment]
@alanmbarr if is not too much work, as suggestion, can you please do the logic inside https://github.com/fsharp/FsAutoComplete/ ? so an additional request + list in FSAC, and ionide call that.

that will help other editors too, who need to just call the new command, and integration is slim. Plus side, you get a simple integration framework to add tests in FSAC
