### ISSUE TITLE
error MSB4066: The attribute "xmlns" in element <Choose> is unrecognized

### ISSUE THREAD

**Issue by urbanhop** [ionide/ionide-vscode-fsharp#696]
After creating a scaffold project, I received the error:

error MSB4066: The attribute "xmlns" in element <Choose> is unrecognized

I assume this is an MSBuild version problem. I configured the MSBUILD_PATH to MSBuild 14.0.

**Comment by Krzysztof-Cieslak** [comment]
Projects created by Forge are using new, SDK-based project format which requires MSBuild 15. I think that changing the path or removing `MSBUILD_PATH` completely will solve it.
