### ISSUE TITLE
Unable to run project built with Ionide osx

### ISSUE THREAD

**Issue by adamgajzlerowicz** [ionide/ionide-vscode-fsharp#698]
I just started learning F# and I am having issues running built project. 

I am using VSCode tools palette  to create an empty console project and building it with `FAKE: Build Default`. Build succeeds, but when I try to run the file with dotnet I get the following error:

```
$ dotnet MyConsole/bin/Debug/net461/MyConsole.exe
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/adam/projects/IonideProject/MyConsole/bin/Debug/net461/'.
```

I am running MacOs High Sierra. 
```
dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

```

Any help will be appreciated. 
Thanks

**Comment by Krzysztof-Cieslak** [comment]
Try running `dotnet run PATH_TO_FSPROJ_FILE`. 

Also, you can build and run (and debug) projects using Ionide's project explorer:
![image](https://user-images.githubusercontent.com/5427083/34951337-392f0d4a-fa16-11e7-970f-07d3263dca35.png)

**Comment by adamgajzlerowicz** [comment]
Hi, thank you for your response, but using `run` command doesn't seem to work.
I'd love to start using F# but I am having a really hard time getting base config to work.

![image](https://user-images.githubusercontent.com/675615/34960530-8822ee10-fa3b-11e7-8421-468dc21fdfc4.png)

**Comment by TheAngryByrd** [comment]
@adamgajzlerowicz You can't use `dotnet run` on a net461 app on osx.  You'll either have to convert it the project a `netcoreapp2.0` (TargetFramework in the fsproj) or use `mono MyApp.exe`

**Comment by Krzysztof-Cieslak** [comment]
🤦‍♂️, should have noticed that.

**Comment by adamgajzlerowicz** [comment]
Yeah - that is it. Thanks guys!
