### ISSUE TITLE
Incorrect message "This value is unused" for members definition of a class

### ISSUE THREAD

**Issue by livioc** [ionide/ionide-vscode-fsharp#699]
![img](https://user-images.githubusercontent.com/6544383/34935723-1df12950-f9df-11e7-90e1-cfe39bf4efb2.gif)

hi, using the "class" syntax the "instancePrefix." of the member is incorrectly marked with the error info message "This value is unused"

i'm using ionide-fsharp 3.15.8

**Comment by Krzysztof-Cieslak** [comment]
The value `this` is not used anywhere inside of the functions, hence it's unused. You can replace it with `__` - the identifier is necessary only if you use another member of the class inside a member function. For example:
```
member this.Value = "abc"

member this.Display() = 
   "Hello" + this.Value
```

wouldn't show a warning for `member this.Display()` (it would still show warning for `member this.Value = "abc"` which can be replaced with `member __.Value = "abc` [or any other wildcard identifier])

**Comment by livioc** [comment]
@Krzysztof-Cieslak  if there's a way to distinguish between this case from the others "This value is unused" cases can we improve the info message with this __ note? It will help newbie as mine to know about its existence, i have opened this issue because i failed to use the single _ wildcard

**Comment by Krzysztof-Cieslak** [comment]
We provide different quick fix action for this case so we have enough information to change the warning message too. It should be done here - https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/UnusedDeclarations.fs#L21-L22

**Comment by livioc** [comment]
how do i see/apply quick fix action?  Maybe it's not helpful to improve the info message because the same additional info about __ wildcard is already in the quick fix description but i cannot find the way to see in studio code the cmd.title 
https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/UnusedDeclarations.fs#L58

**Comment by livioc** [comment]
I did a full vs code + ionide reinstall and now the quick fix icon appears with the 'Replace with __' suggestion so i don't think that it's helpful to add the same info in the warning message.
I don't get why the quick fix icons wasn't displayed before in my vs code instance
