### ISSUE TITLE
Syntax highlighting consistency

### ISSUE THREAD

**Issue by et1975** [ionide/ionide-vscode-fsharp#70]
Types/modules/vars all have inconsistent appearance depending on where they are in the code. It makes the highlighting counterproductive.

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately syntax highlighting in VSCode is RegEx based what can lead to such behavior. Not really much we can do about it I guess. 

But any suggestions how to make highlighting grammar better are appreciated - feel free to take a look at  https://github.com/ionide/ionide-fsgrammar
