### ISSUE TITLE
Dlls not being copied to bin dir

### ISSUE THREAD

**Issue by harrisse** [ionide/ionide-vscode-fsharp#701]
Hello, I'm not really sure where my issue belongs, but I'm having an issue with Ionide that wasn't present when I was using Visual Studio so I figured this'd be a good place to start. The gist of my issue is that I've installed MonoGame.Framework.WindowsDX using Paket in VS Code. When I run my program, I get an error that the dependencies of MonoGame.Framework are unable to be found, and I can confirm that they are not copied to the bin dir of my application. If I manually copy the missing dlls from <root>/packages/MonoGame.Framework.WindowsDX/lib/net40, the program runs as expected.

I suspect this might be user error and I'm just used to Visual Studio copying my dependencies for me, but I wasn't able to find any guidance on this subject in the FAKE docs, the Ionide docs, the MSBuild docs, or StackOverflow.

**Comment by enricosada** [comment]
Hi @harrisse , can you add an repro? a git repo, an fsproj?
source files doesnt matter, so is ok with an empty main

**Comment by enricosada** [comment]
ping @harrisse

**Comment by enricosada** [comment]
Closing, no reproduction.

@harrisse feel free to reopen after adding more info (see https://github.com/ionide/ionide-vscode-fsharp/issues/701#issuecomment-359444172 )
