### ISSUE TITLE
Keep FSI output if FSI crashs.

### ISSUE THREAD

**Issue by psiLearn** [ionide/ionide-vscode-fsharp#704]
Sometimes the FSI crashes, especially when it interacts with native DLLs. If the F# interactive window can keep the output, it would be easier to find the errors.

**Comment by Krzysztof-Cieslak** [comment]
FSI window is implemented using Terminal API. We have no control over what's displayed or when things are cleared - in principle we just create new terminal window spawning FSI in there on startup.
