### ISSUE TITLE
DOS line endings in automated build.sh

### ISSUE THREAD

**Issue by nestordemeure** [ionide/ionide-vscode-fsharp#71]
I am unsure if it is the right place to repport that problem but I just noticed that using "new project" creates a build.sh that contains DOS line endings (^M wich can be seen using "cat -v build.sh") making it unable to build on ubuntu.
"fromdos build.sh" solves the problem easily but it would be better if it was fixed at the source.

Nestor

P.S. I am new to F# and struggling to understand fake but so far ionide for vscode has been a pleasure to use :)

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed in `2.0.0`

**Comment by Systemcluster** [comment]
I encountered this issue with the current version 2.9.4. build.sh was created with `\r\n` line endings, breaking the build step (from command line or with ionide-vscode-fake) on OSX.

**Comment by nestordemeure** [comment]
I just add the issue with the current version.

**Comment by nestordemeure** [comment]
Does anyone knows where the culprit build.sh is ? I would be happy to upload a fixed version :)

**Comment by smoothdeveloper** [comment]
@nestordemeure @Krzysztof-Cieslak says it is over https://github.com/fsharp-editing/Forge/tree/templates

**Comment by nestordemeure** [comment]
Thank you, I just proposed change for the two build.sh that were in that repository.

**Comment by Krzysztof-Cieslak** [comment]
Thanks, both PR merged. You should get updated templates by running `F#: Refresh Project Templates` from Code's command palette.

**Comment by nestordemeure** [comment]
It now builds without problems :)

Is there a way to add a regression test for that problem ? 
(It artificially raises the bar of entry for non Windows users)
