### ISSUE TITLE
Setting to disable underscore warning

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#710]
Browsing popular F# code I often see variables or functions being defined with underscores, but unfortunately I get a linter warning in VS Code:

![image](https://user-images.githubusercontent.com/4580714/36067112-a5b096e4-0eae-11e8-8e18-ac78153d3f25.png)

The message is:

```
Lint: Consider changing `SWITCHING_PROTO` to remove any underscores.
```

Since this seems to be a valid naming convention in F# would it be worth to add a setting in Ionide which can turn all these warnings off - either by default or by overriding the default setting?

**Comment by Krzysztof-Cieslak** [comment]
Lint messages are provided by https://github.com/fsprojects/FSharpLint, and they can be configured using FSharpLint settings file (http://fsprojects.github.io/FSharpLint/ and default file - https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/DefaultConfiguration.FSharpLint#L142-L237)
