### ISSUE TITLE
Packages added through dotnet cli are not recognized without explicit restore and reload

### ISSUE THREAD

**Issue by lambdakris** [ionide/ionide-vscode-fsharp#711]
This is probably a known issue, but I could not find an actual github issue tracking it. 

When a package is added to a project through `dotnet add package`, the package is not recognized by the editor until one runs `dotnet restore` and `ctrl+shift+p > Reload Window`.

Repro steps:
1. `dotnet new console -lang f# -o example`
2. `cd example`
3. `code .`
4. `dotnet add package BenchmarkDotNet`
5. Add `open BenchmarkDotNet` in Program.fs and notice the error `The namespace or module 'BenchmarkDotNet' is not defined`
6. `ctrl+shift+p > Reload Window`
7. Notice error is still there
8. `dotnet restore`
9. Notice error is still there
10. `ctrl+shift+p > Reload Window`
11. Notice error is gone

I had expected that package additions through the dotnet cli would be automatically recognized by the editor.

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce with the latest release, we probably fixed that while fixing some other bugs around project handling.
