### ISSUE TITLE
Expecto watch mode do not pick up on changes in referenced C# project

### ISSUE THREAD

**Issue by Vidarls** [ionide/ionide-vscode-fsharp#713]
This may very well be by design, but I thought I'd mention it:

When using Expecto watch mode, any changes in referenced C# project under test is not picked up, IE does not trigger a new build / test.

This is different from running `dotnet watch run` [The tool referenced in this tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch), which when run on the same F# Expecto test project does pick up on changes in referenced C# projects.

Note: I have not tested if referenced F# project changes are picked up.

**Comment by Krzysztof-Cieslak** [comment]
Expecto watch mode predates `dotnet watch` tool and is using our custom thing to detect changes - hence differences in behavior.

But not detecting changes in C# is rather by-design. Ionide has no knowledge about C# projects, and C# code at all. And I don't think it will change any time soon.

**Comment by Vidarls** [comment]
Thank you for taking the time to explain.
