### ISSUE TITLE
unhandled error for ionide-fsharp 3.17.1

### ISSUE THREAD

**Issue by cxk99** [ionide/ionide-vscode-fsharp#717]
I just install ionide-fsharp 3.17.1 in vscode 1.20.1 (windows 10). 
the following error appears in the Forge output when I try to create a new project.

unhandled error:
cannot find path "... \.vscode\extensions\Ionide.ionide-fsharp-3.17.1\bin_forge\templates\.fake"

I check the directory, ".fake" directory does not exist.

However, when I update the ionide-fsharp 3.16 to 3.17.1 on another computer, it does not have this error.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `3.17.2`
