### ISSUE TITLE
Code Outline collapse buttons don't do anything

### ISSUE THREAD

**Issue by Rhywun** [ionide/ionide-vscode-fsharp#719]
The buttons in the Code Outline panel reading "Collapse to default state" and "Collapse all" don't appear to work. Nothing happens when I click or alt-click
 them regardless of the state of the items in the tree. Debug log attached.

[log.txt](https://github.com/ionide/ionide-vscode-fsharp/files/1754561/log.txt)

ionide-fsharp 3.17.1
VS Code 1.20.1
MacOS 10.12.6

**Comment by Rhywun** [comment]
After playing with the buttons some more, I have noted that sometimes they work and sometimes they don't. When they do work it often takes multiple clicks on the button, or maybe it's just working very slowly (?).

I don't know if the log I attached reveals anything, but when I made the log I just clicked each button once.

**Comment by Krzysztof-Cieslak** [comment]
CC: @vbfox

**Comment by Krzysztof-Cieslak** [comment]
We're not going to fix Code Outline bugs since it's going be replaced by new specific view that's being implemented in VSCode.
