### ISSUE TITLE
F#: New Project complains about missing templates. Refresh templates throws exception.

### ISSUE THREAD

**Issue by atlemann** [ionide/ionide-vscode-fsharp#720]
I'm trying to create a new project in VSCode via `Ctrl+Shift+P` and `F#: New Project`, but:

![image](https://user-images.githubusercontent.com/16226914/36635163-8c0886c2-19b0-11e8-94b3-428666e07f4e.png)

Then I try `F#: Refresh Project Templates` and I get the following message in the Forge terminal:

---

forge refresh --no-prompt

Unhandled Exception:
System.BadImageFormatException: Could not resolve field token 0x04000008, due to: Could not load type of field '<StartupCode$Forge>.$Forge.App:parser@27' (2) due to: Could not load file or assembly 'Argu, Version=3.7.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Argu, Version=3.7.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none> assembly:/home/atle/.vscode/extensions/Ionide.ionide-fsharp-3.17.1/bin_forge/Forge.exe type:App member:<none>
File name: 'Forge'

---

My `dotnet --info`

.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

Any ideas?

**Comment by atlemann** [comment]
I'm getting the same error message for `forge add project` as well.

**Comment by atlemann** [comment]
Looks like it's a duplicate of https://github.com/fsharp-editing/Forge/issues/90.

**Comment by atlemann** [comment]
The `bin` folder next to `Forge.exe` in the ionide .vscode/extensions folder is with small letters. Adding a symlink with capital `B` (`ln -s bin Bin`) removes the error at least. But now it is showing me the `No templates found` message even if it lists the templates.

![image](https://user-images.githubusercontent.com/16226914/36645279-817fa18e-1a66-11e8-9c40-dcdb21d5caca.png)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `3.17.2`
