### ISSUE TITLE
Backslash character unprintable in swedish macOS keyboard

### ISSUE THREAD

**Issue by kliron** [ionide/ionide-vscode-fsharp#721]
The default binding to "fsi.SendLine" command is "shift+alt+7" which on swedish MacOS keyboard is the backslash character. So typing "\\" is impossible when editing .fs/.fsx files. 

It is easily fixed by rebinding to something else like "shift+alt+1" as per the [official documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule) 
but maybe a different default is possible for convenience?

**Comment by Krzysztof-Cieslak** [comment]
Hey, 

We can't make sure that the default key bindings works on every possible keyboard layout. As such we focus on making them working on US/UK keyboard, and VSCode provides easy way to rebind any keyboard shortcut so users with different keyboard layout can override them themselves.
