### ISSUE TITLE
CodeLens does not display in val declaration

### ISSUE THREAD

**Issue by wk-j** [ionide/ionide-vscode-fsharp#722]
This is strange looking code because `[<DefaultValue>]` was separated by empty CodeLens line

![localcontext_fs_ _captureservice](https://user-images.githubusercontent.com/860704/36654307-454a3f5c-1aee-11e8-9731-448830af858e.png)

**Comment by 7sharp9** [comment]
I get this in a net standard project too, just a new console app with this type:
```
type LocalDbContext() =

  [<DefaultValue>]
  val mutable private test : int
```

**Comment by 7sharp9** [comment]
The following does work though:
```
type LocalDbContext() =

  [<DefaultValue>]
  let mutable test : int
```

**Comment by 7sharp9** [comment]
This is an upstream issue with FCS as it does not return a valid property Symbol for a val defined like:
```
val mutable private test : int
```

**Comment by 7sharp9** [comment]
scratch that, on further investigation its an issue with the interesting symbol function returning the `int` part rather than the `test` part symbol.

**Comment by 7sharp9** [comment]
![Screenshot 2019-10-04 at 15 37 35](https://user-images.githubusercontent.com/588746/66216178-e9aa4100-e6bc-11e9-82b9-2420767e12a3.png)

Im getting a Lens with this ^

**Comment by 7sharp9** [comment]
Maybe the interim month have fixed this in FCS.

**Comment by Krzysztof-Cieslak** [comment]
I’ll test that later today

**Comment by Krzysztof-Cieslak** [comment]
I'm still not getting the code lenses for type signature and I'm getting wrong reference code lenses
![image](https://user-images.githubusercontent.com/5427083/66310506-a514e480-e90c-11e9-9bb8-cafa2895d820.png)

In case of reference numbers (and I guess in the screenshot @7sharp9 posted) FSAC thinks that the symbol for which lens should be displayed is `int` rather than `test`

**Comment by 7sharp9** [comment]
If you take out the CR between the attributes and val they seem to appear, I had to restart though.

**Comment by Krzysztof-Cieslak** [comment]
As expected - this is indeed a bug in FCS, I've fixed that with https://github.com/dotnet/fsharp/pull/10727 which means that in a few months time we will have this in Ionide.

**Comment by Krzysztof-Cieslak** [comment]
![image](https://user-images.githubusercontent.com/5427083/102229117-b764b800-3eeb-11eb-99d0-071d26e5d8d7.png)
