### ISSUE TITLE
Paket: Init command fails to download paket

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#723]
VSCode version 1.20.1, Ionide-Paket versoin 1.9.1

When I run the command `Paket: Init`, it creates an empty packages folder and the paket.dependencies file, but then fails with this error

      C:\Users\guguer\.vscode\extensions\Ionide.ionide-paket-1.9.1\bin\paket.exe
      Paket version 3.33.4
      Saving file c:\Work\SubstrateSearch\private\Scripts\paket.dependencies
      Paket failed with:
        Error occured while downloading from https://github.com/fsprojects/Paket/releases/latest.

Replacing paket.bootstrapper.exe in C:\Users\guguer\.vscode\extensions\Ionide.ionide-paket-1.9.1\bin with the latest version fixed the issue

**Comment by guguer** [comment]
Recently repro'ed this in two colleagues' machines, they had the same issue when first trying to use Ionide-Paket

**Comment by ovatsus** [comment]
Just realised I filed this on the wrong repo, should have been on ionide-vscode-paket

**Comment by mclang** [comment]
Well, I got my issue fixed.

I'm running Solus, and to update the needed mono certificate things I needed to run:
```
$ sudo usysconf run -f
```
