### ISSUE TITLE
Autocomplete auto-backticks

### ISSUE THREAD

**Issue by sergey-tihon** [ionide/ionide-vscode-fsharp#726]
I expect that Ionide put backticks around name automatically when this isrequired.

when I press enter after
```fsharp
let fileName = Common.PaketFiles.ope
```
I expect to have
```fsharp
let fileName = Common.PaketFiles.``opennlp.sourceforge.net``
```
instead of 
```fsharp
let fileName = Common.PaketFiles.opennlp.sourceforge.net
```

Sample uses `FileSystemProvider` from `FSharp.Management`
![feb-28-2018 13-12-31](https://user-images.githubusercontent.com/1197905/36782345-bb00c166-1c89-11e8-86df-ac2b20c7d973.gif)

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/commit/8b588283ee5a8638ec6c255cba13ecfd626691e3
