### ISSUE TITLE
Compile errors on removed files are still listed in "Problems" after a rebuild

### ISSUE THREAD

**Issue by tlycken** [ionide/ionide-vscode-fsharp#730]
Steps to reproduce:

1. Create a new F# project, e.g. with `dotnet new classlib -lang f#` and open the project folder in VS Code.

2. Introduce a compile error in the generated `Library.fs` file, e.g. by adding `let x =` without finishing the statement. (optionally build the project with `dotnet build` to see it fail).

3. Look in the "problems" pane of VS Code (Ctrl + Shift + M). The error introduced above is correctly listed.

4. Delete the `Library.fs` file and remove its reference from the project file.

5. Rebuild the project. It now succeeds, but the compile error from before is still listed in the problems panel.

The incorrectly listed error disappears upon reloading the window, but it would be even smoother if I didn't have to do that :)

**Comment by tlycken** [comment]
I just realized this might not be Ionide's fault - I just had the same behavior happen on a Dockerfile. (Of course, it might just be that the Docker extension has the same bug...)

**Comment by Krzysztof-Cieslak** [comment]
I do kinda feel it should be handled in VSCode... but it may be by-design, and we definitely can work around that - file watcher looking for deleted event, and removing errors from diagnostic collections would do a trick.

**Comment by vbfox** [comment]
> Diagnostics are “owned” by the server so it is the server’s responsibility to clear them if necessary. The following rule is used for VS Code servers that generate diagnostics:

&

> When a file changes it is the server’s responsibility to re-compute diagnostics and push them to the client. If the computed set is empty it has to push the empty array to clear former diagnostics. Newly pushed diagnostics always replace previously pushed diagnostics. There is no merging that happens on the client side.

So I suspect that VS Code answer to that is : Nop, handle it in your extensions / LSP servers :)

**Comment by Krzysztof-Cieslak** [comment]
Fair enough

**Comment by tlycken** [comment]
@vbfox Thanks for the reference; I'll go ahead and file a bug report with the Docker extension too :)

**Comment by MangelMaxime** [comment]
I would like to work on this issue.
