### ISSUE TITLE
Ionide damages the TargetFrameworks line in .Net Core-style .fsproj

### ISSUE THREAD

**Issue by rmunn** [ionide/ionide-vscode-fsharp#737]
Related to #679, but a different problem so it might or might not be a duplicate, depending on whether the root cause is the same.

## To reproduce:

1. Install https://github.com/TheAngryByrd/MiniScaffold (`dotnet new -i MiniScaffold`)
1. Create a new project with `dotnet new mini-scaffold -o repro -lang F#`
1. Edit the project in VS Code+Ionide
1. Hit the keyboard shortcut for "F#: Move File Up" (<kbd>Ctrl + Shift + Up arrow</kbd> on Linux, probably <kbd>Cmd + Shift + Up arrow</kbd> on OS X) to trigger Forge re-writing the .fsproj file
1. The line `<TargetFrameworks>netcoreapp2.0;netcoreapp1.1;net461</TargetFrameworks>` changes to `<TargetFrameworks>netcoreapp2.0netcoreapp1.1net461</TargetFrameworks>` (note the missing semicolons).

**Comment by pver** [comment]
I noticed the same happens when adding or removing files to the project.
This looks like an issue in Forge, I've created a PR that should fix this issue

**Comment by Krzysztof-Cieslak** [comment]
Fixed in https://github.com/fsharp-editing/Forge/pull/110
