### ISSUE TITLE
Quickfix for adding >> changing to much

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#738]
Ionide-fsharp 3.17.3

If I have some code like this:

    let array = [| "A"; "B"; "C"|]

    let foo (s: string) = s

    let bar = 
        array
        |> Array.map (sprintf "something %s")
        |> Array.map foo

There's a quick fix suggestion that turns it into this:

    let bar = 
        Array.map ((sprintf "something %s") >> foo) array

However I think the correct fix should be to this to keep the existing style

    let bar = 
        array
        |> Array.map ((sprintf "something %s") >> foo)

**Comment by Krzysztof-Cieslak** [comment]
I've moved the issue to F#Lint repo - in Ionide we just use whatever suggestion we get from it.

https://github.com/fsprojects/FSharpLint/issues/261
