### ISSUE TITLE
Intellisense in comments

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#74]
If you're inside a (\* *) code you wouldn't expect intellisense or autocomplete to happen, but it does - this can be frustrating as you have to keep escaping out.

**Comment by Krzysztof-Cieslak** [comment]
That should be probably handled in FSAC or FCS - no idea why FCS returns completion for comments ;)

**Comment by kirill-gerasimenko** [comment]
Hi,

I'm looking into this one. I've got some almost working solution locally, and still learning FSAC/FSC to the level of acceptable PR.

**Comment by lilred** [comment]
@kirill-gerasimenko are you still working on this?

Best

**Comment by kirill-gerasimenko** [comment]
@lilred not at the moment sorry :(

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `3.15.2`
