### ISSUE TITLE
Lots of errors when using WPF

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#743]
VSCode 1.21.1
Ionide-fsharp 3.17.3

I have a `displayutils.fsx` file with this content:

    #r "PresentationFramework.dll"

    namespace global

    [<AutoOpen>]
    module DisplayUtils =

        let mutable lastDisplayedValue = Unchecked.defaultof<obj>

        open System.Windows
        open System.Windows.Controls

        let display x =     
            lastDisplayedValue <- x
            let w = Window()
            let tb = Controls.TextBox()
            ScrollViewer.SetVerticalScrollBarVisibility(tb, ScrollBarVisibility.Auto)
            w.Content <- tb
            tb.Text <- sprintf "%O" x
            w.ShowDialog()

And I get squiggly lines all over, even though everything works fine on FSI:

![image](https://user-images.githubusercontent.com/738761/37534551-0f299cd0-293d-11e8-90b6-20453e9904da.png)

**Comment by Krzysztof-Cieslak** [comment]
I've followed suggestions about missing references that were displayed in error messages and this code works fine for me:
```
#r "PresentationFramework"
#r "PresentationCore"
#r "WindowsBase"

namespace global

[<AutoOpen>]
module DisplayUtils =

    let mutable lastDisplayedValue = Unchecked.defaultof<obj>

    open System.Windows
    open System.Windows.Controls

    let display x =
        lastDisplayedValue <- x
        let w = Window()
        let tb = Controls.TextBox()
        ScrollViewer.SetVerticalScrollBarVisibility(tb, ScrollBarVisibility.Auto)
        w.Content <- tb
        tb.Text <- sprintf "%O" x
        w.ShowDialog()
```

**Comment by ovatsus** [comment]
Odd, none of the errors I got mentioned missing references:

![image](https://user-images.githubusercontent.com/738761/37928229-1388a61e-3134-11e8-9b48-218b1239028d.png)

And the code actually works fine in FSI

But changing from `#r "PresentationFramework.dll"` to `#r "PresentationFramework"` then I started getting the proper errors. The problem was the `.dll` then, though there was no error message about it saying invalid reference
