### ISSUE TITLE
vs code only runs Program.fs in unit tests

### ISSUE THREAD

**Issue by saadshams** [ionide/ionide-vscode-fsharp#746]
vs code only runs Program.fs in unit tests

Using VS Code to run .net core app and ms unit tests. I've couple of unit tests files along with default Program.fs thats provided as default file. If I put breakpoint on this line, it works but not in any of the other unit test files.

module Program = let [<EntryPoint>] main _ = 0

Output:

The program '[3910] MyProject.Tests.dll' has exited with code 0 (0x0).
Seems like vs code only executes one unit test file, Program.fs in this case. In my fs proj I've references to the other files as well, how can I have the other unit test files run as well.

VSCode Version: 1.21.1
OS Version: Mac 10.13.3
Steps to Reproduce:

Create couple of test files within .net core project f#
Run tests. vs code only runs Program.fs in unit tests

**Comment by rmunn** [comment]
You might be running into .Net Core's "Just My Code" debugging feature: if any of the code that your project links is compiled in Release mode or doesn't have debugging symbols available (.pdb files), then the .Net Core debugger assumes that that's an external dependency that you don't want to debug, and the debugger skips right over it. You can't step into those functions, can't set breakpoints in there, and so on.

See https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#just-my-code for more details, including how to turn that feature off.

**Comment by saadshams** [comment]
I've added the line `"justMyCode": false,` in launch.json under the configuration `"name": ".NET Core Launch (console)"`. Previously it wasn't there and I was getting and I was noticing justMyCode references in the console so it could be one of the issues.

Issue is persisting though. I'm debugging tests against a library project and referencing the library project as a dependency in MyLib.Tests.fsproj

```
  <ItemGroup>
    <ProjectReference Include="..\MyLib\MyLib.fsproj" />
  </ItemGroup>
```

**Console output**

> Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Private.CoreLib.dll'. Cannot find or open the PDB file.
> Loaded '/Users/path-to-mylib/MyLib.Tests/bin/Debug/netcoreapp2.0/MyLib.Tests.dll'. Symbols loaded.
> Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.0.5/System.Runtime.dll'. Cannot find or open the PDB file.
> The program '[1274] MyLib.Tests.dll' has exited with code 0 (0x0).

For some reason no word about loading `MyLib` itself in the console output, is there a step I'm missing?

**Comment by saadshams** [comment]
@rmunn any updates on this please?

Just to reiterate, My solution exists of two projects, one is F# Library Project and the other is MS Test project.

- MyLib. 
- MyLib.Tests (MyLib as dependency)

Works: Detects all Unit Tests

```
cd MyLib.Tests
dotnet test
```

Doesn't Work as execpted: Debugging Unit Test (accessible from left menu Debug -> Debug Play button)

Only Program.fs is executed, I can set breakpoints there and program exists after that with the code 0. Debugging with other IDEs works fine though.

**Comment by rmunn** [comment]
@saadshams I'm not involved with the Ionide project, I just mentioned the "Just My Code" feature because I've run into that before. I won't be able to give you further advice on this, sorry.

**Comment by saadshams** [comment]
@rmunn I see, Can you tag someone or give it a label for bug something for priority.

**Comment by Krzysztof-Cieslak** [comment]
Ionide is not providing any debugging capabilities, debugging story is provided by and supported by C# extension.
