### ISSUE TITLE
Type of function arguments highligths as variables

### ISSUE THREAD

**Issue by Szer** [ionide/ionide-vscode-fsharp#749]
1)
Add this to user settings:

```
    "editor.tokenColorCustomizations": {
        "types": "#FF0000"        
    },
```
Actual behaviour:
![image](https://user-images.githubusercontent.com/10308233/37759038-722e3d56-2dc3-11e8-8aac-238495c9ea85.png)

Expected:
MyType should be red on both strings.

2)
Add this to user settings:
```
    "editor.tokenColorCustomizations": {
        "variables": "#FF0000"
    },
```
Actual behaviour:
![image](https://user-images.githubusercontent.com/10308233/37759112-b33d3414-2dc3-11e8-90fa-ee9187f8e6dd.png)

Expected:
MyType should stay same color on both strings (default green)

**Comment by Krzysztof-Cieslak** [comment]
Inaccurate syntax highlighting is caused by the fact that VSCode supports only regex based highlighting (unlike other IDEs which are using language service for more accurate syntax highlighting). So we can't do much about it.
