### ISSUE TITLE
Upgrade to MSBuild 14

### ISSUE THREAD

**Issue by ChrSteinert** [ionide/ionide-vscode-fsharp#75]
Currently MSBuild 12 is a dependency for the Ionide for VS Code. Because of this I had troubles setting up Ionide as I had VS 2015 U2 only installed with comes (seemingly) with MSBuild 14, therefore the autocomplete does not work. The package descriptons page (https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp) states that it is enough to have VS 2015 to use Ionide, which, for me, seems not true. 

So i'm suggesting to upgrade to MSBuild 14 to go around this issue (or clearify on the package descriptions page).

**Comment by Krzysztof-Cieslak** [comment]
Related to https://github.com/fsharp/FsAutoComplete/issues/107
