### ISSUE TITLE
Strange Extension host Notify messages

### ISSUE THREAD

**Issue by landy** [ionide/ionide-vscode-fsharp#751]
Is it normal that this kind of messages is generated to the dev console all the time (maybe when opening diferent file)? 
![untitled](https://user-images.githubusercontent.com/56007/37820051-c8171974-2e7f-11e8-9113-66ddb4c51228.png)

**Comment by vbfox** [comment]
https://github.com/ionide/ionide-vscode-fsharp/blob/b16dac0f63b91562fb95c20b37988415b7560de0/src/Components/Errors.fs#L130 ;)

**Comment by Krzysztof-Cieslak** [comment]
Just don't run git blame on this line, please ;)
