### ISSUE TITLE
Error about #r not supported is reported on fs files even when inside #if INTERACTIVE block

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#754]
VSCode 1.21.1
Ionide-fsharp 3.18.0

![image](https://user-images.githubusercontent.com/738761/37930012-679a3e34-3139-11e8-961d-ea95b319c301.png)

![image](https://user-images.githubusercontent.com/738761/37930191-f5f271d8-3139-11e8-8126-b04e7665e433.png)

**Comment by Krzysztof-Cieslak** [comment]
This seems to be fixed
