### ISSUE TITLE
Problem debuging ionide

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#757]
Hi,

I've done this before and it worked, but with the latest master after running all build steps described in the contributing.md file and start code, Ionide fails to start fsautocomplete:

`[IONIDE-FSAC] Failed to start language services. spawn C:\Git\ionide-vscode-fsharp\release/bin/fsautocomplete.exe ENOENT`

My release folder doesn't have any `bin` or `bin_netcore` folder, and in fact I can't find `fsautocomplete.exe` anywhere inside my repo root. Am I missing a build step?

**Comment by Krzysztof-Cieslak** [comment]
`build.cmd Build` should copy FSAC (and other deps) into right place.

**Comment by ovatsus** [comment]
Humm, turns out the Default target doesn't actually run the Build target, so just doing `build` doesn't actually build. Fake output:

    Shortened DependencyGraph for Target Default:
    <== Default
       <== RunScript
          <== Clean

    The running order is:
      - Clean
      - RunScript
      - Default

If have to run `build Build` instead. Fake output:

    Shortened DependencyGraph for Target Build:
    <== Build
       <== CopySchemas
          <== CopyGrammar
             <== CopyForge
                <== CopyFSACNetcore
                   <== CopyFSAC
                      <== RunScript
                         <== Clean
                         <=? YarnInstall
                         <=? DotNetRestore

    The running order is:
      - Clean
      - YarnInstall
      - DotNetRestore
      - RunScript
      - CopyFSAC
      - CopyFSACNetcore
      - CopyForge
      - CopyGrammar
      - CopySchemas
      - Build

**Comment by ovatsus** [comment]
But even that is not enough, because CopyFSAC is trying to copy from `paket-files/github.com/fsharp/FsAutoComplete/bin/release` and there is no bin folder inside `paket-files/github.com/fsharp/FsAutoComplete`

**Comment by landy** [comment]
If it doesn't copy the files then the problem can be that you have the project too deep on file system because the paket runs build scripts on the dependencies in the paket-files folder and it fails some MaxLengthPathException or something. for this reason I can't have ionide in folder `C:\projects\private\ionide-vscode-fsharp` but I have to have it in `C:\projects\private\ionide`

**Comment by landy** [comment]
go to `paket-files/github.com/fsharp/FsAutoComplete` and run `build.cmd LocalRelease` to see the real error

**Comment by ovatsus** [comment]
Ok, the real error returned by `build.cmd LocalRelease` inside `paket-files/github.com/fsharp/FsAutoComplete` is the following:

    MSBUILD : error MSB1040: ToolsVersion is not valid. The tools version "14.0" is unrecognized. Available tools versions are "15.0", "2.0", "3.5", "4.0".
    Switch: 14.0
    Running build failed.
    Error:
    Building ./FsAutoComplete.sln failed with exitcode 1.

**Comment by wilt00** [comment]
This issue happens for me as well when building FsAutoComplete on its own from source. FsAutoComplete builds correctly in Visual Studio (15.6.4), but not when using the standalone build tools (MSBuild version 15.6.82).

**Comment by ovatsus** [comment]
Sent a PR for FSAutocomplete - https://github.com/fsharp/FsAutoComplete/pull/287

@Krzysztof-Cieslak, can you merge that and then update Ionide to consume it?

**Comment by Krzysztof-Cieslak** [comment]
This should be easier on current master
