### ISSUE TITLE
Error when building/running default project

### ISSUE THREAD

**Issue by jlogar** [ionide/ionide-vscode-fsharp#759]
I created a project in VS Code with the ionide-fsharp plugin (as described [here](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode?tabs=windows), but a console app). The project seems to have been created OK. I added the following packages:
- FSharp.Data
- ClosedXML

The issue I'm having is actually running the project. When running using "F#: Run default project" (I only have 1 project) I get the following error from msbuild: 

> [19:15:45 INFO ] invoking msbuild from C:\Program Files\dotnet\dotnet.exe on "c:\_tlaka\oss\yearch\yearch\yearch.fsproj" for target Build
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

> c:\_tlaka\oss\yearch\yearch\yearch.fs(68,13): error FS3033: The type provider 'ProviderImplementation.CsvProvider' reported an error in the context of provided type 'FSharp.Data.CsvProvider,Sample="c:\\_tlaka\\oss\\yearch\\yearch\\..\\..\\invoice-sent_2017_on_2018-3-24.csv",Separators=";",PreferOptionals="True"', member 'Load'. The error: Failed to bind type 'System.IO.TextReader' in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'Parameter name: tcName [c:\_tlaka\oss\yearch\yearch\yearch.fsproj]

If I open the same solution in VS 2017 and run (debug) it it runs executes just fine. I can also build (invoking msbuild directly) and run from the command line, no issues there. The only thing is a couple of reference conflicts (for which I also don't know how they're there since I'm really running vanilla here).

I'm running on windows 10, have VS 2017 Community installed. Ionide is latest, so is VS Code. .NET 4.7.1 is installed (as part of VS install) & the environment variables are set as described in the ionide install instructions.

What am I doing wrong here?

If I left out any crucial info please let me know.

**Comment by Krzysztof-Cieslak** [comment]
Run `F#: Pick MsBuild host` (it can be found in the project explorer) and choose `.Net`. This is necessary because you're trying to use TypeProvider and building such projects is not possible directly with `dotnet build` (what Ionide tries to do by default). Using .Net host will make Ionide run `msbuild.exe` directly, which should solve the problem. 

![screenshot from 2018-03-27 19-36-27](https://user-images.githubusercontent.com/5427083/37984461-9d0833e2-31f6-11e8-8278-41b5ffe06450.png)

**Comment by Krzysztof-Cieslak** [comment]
In general our docs are here - https://github.com/ionide/docs (http://ionide.io/docs/). It's pretty much works in progress, so any updates are appreciated. We could put this in "General Info" section.
