### ISSUE TITLE
Auto-property with get and set being marked as unused

### ISSUE THREAD

**Issue by SirUppyPancakes** [ionide/ionide-vscode-fsharp#761]
Consider:
```
type Test() =
    let mutable a = 123
    member _this.A
        with get() = a
        and set(value) = a <- value
    member val B = 123 with get
    member val C = 123 with get, set
```
A is a regular get, set property and is fine.
B is an auto-property with just get and is fine.
C is an auto-property with both get and set, but is marked as unused by Ionide.

I'm thinking this is probably a bug with detecting the strange syntax, although it somehow manages to detect the get-only auto-property...

**Comment by Krzysztof-Cieslak** [comment]
Can't repro on `4.4.5`

![image](https://user-images.githubusercontent.com/5427083/72651292-38859900-3983-11ea-9729-f9070dd4f3df.png)
