### ISSUE TITLE
Creating a new project results in a false positive.

### ISSUE THREAD

**Issue by RonaldTinashe** [ionide/ionide-vscode-fsharp#762]
Creating a new project with Ionide 3.18.0 on Windows 10 in Visual Studio Code 1.21.1 results in the error "Incorrect template number or name" being printed in Forge's Output tab yet the notification indiciates the project has been created successfully. No project is created at all as a result.

Would you please assist?

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `3.18.1`
