### ISSUE TITLE
Expecto Run Disappeared on OSX

### ISSUE THREAD

**Issue by tobyhede** [ionide/ionide-vscode-fsharp#763]
I am pretty new to the ecosystem so I might be doing something wrong. 

I have a new Classlib and Expecto project setup, configured to `netcoreapp2.0` on OSX. 
 
My problem is that the Expecto Run command has disappeared from VS Code. I cannot access via the command shortcut at all. 

I saw it working over the weekend and today it's just gone. Projects compile a-ok. 

I am on latest build of VS Code and ionide-fsharp.

**Comment by tobyhede** [comment]
Enabling logging I can see an error is occuring on startup:

```
mainThreadExtensionService.ts:43 [Ionide.Ionide-fsharp]Cannot read property 'document' of null
```

**Comment by Krzysztof-Cieslak** [comment]
Expecto integration has been removed from Ionide. Refined Expecto support is now part of my new extension focused on adding great unit testing experience to VSCode - [Neptune](https://github.com/LambdaFactory/Neptune-public)

**Comment by tobyhede** [comment]
Ah. My bad. Didn't read the instructions.

 :+1:
