### ISSUE TITLE
Type highlighting includes trailing whitespace

### ISSUE THREAD

**Issue by hstk** [ionide/ionide-vscode-fsharp#764]
Highlighting / underlining applied to type declarations trails until the `=`.

![type highlighting](https://user-images.githubusercontent.com/12897758/38096634-038d07e4-3339-11e8-9e5b-9193b7d4b67b.JPG)

**Comment by ShalokShalom** [comment]
This is a very nice theme, what is its name? ^-^
/offtopic

**Comment by moonPtr** [comment]
@ShalokShalom It's the default Monokai theme that comes with VS Code.

**Comment by gdziadkiewicz** [comment]
I have copied the issue to ionide/ionide-fsgrammar/issues/40 and proposed a fix.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in https://github.com/ionide/ionide-fsgrammar/pull/41
