### ISSUE TITLE
Unused value warning is not being displayed

### ISSUE THREAD

**Issue by jbeeko** [ionide/ionide-vscode-fsharp#77]
The line `hmacsha.Key = helloBytes` is not showing a warning of unused boolean value. See below
![image](https://cloud.githubusercontent.com/assets/4968704/16057090/2fb13138-322d-11e6-9c3a-8f72f1c32982.png)

In the case of VisualStudio this is displayed:
![image](https://cloud.githubusercontent.com/assets/4968704/16057130/69f2958a-322d-11e6-8d3d-38a4e841bc79.png)

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce anymore, let's assume it got fixed accidentally with some other fixes.
