### ISSUE TITLE
Evaluating line ending with comment in FSI doesn't work correctly

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#770]
VSCode 1.21.1
Ionide 3.18.2

If you have a line like this: `let x = 2 // comment` and press Alt+Enter either without selection or selecting the whole line, you don't get the proper result in FSI, because the `;;` added at the end is ignored:

![image](https://user-images.githubusercontent.com/738761/38219540-f91d4ccc-36cd-11e8-927c-e5b50629213d.png)

You have to select just the bit until the 2 to get the evaluation to work:

![image](https://user-images.githubusercontent.com/738761/38219550-0231ebb0-36ce-11e8-8d98-de2ccbfb3c23.png)

I'm not 100% sure, but I think this worked before in Ionide.

In real code this isn't much of a problem, but when using Ionide to do a small demo introduction to F# to newcomers it's really annoying

**Comment by Krzysztof-Cieslak** [comment]
Hey, @vbfox. That’s why `;;` were put on new line ;-)

**Comment by Krzysztof-Cieslak** [comment]
Bug was introduced as part of #766

**Comment by ovatsus** [comment]
Ideally you would only put on the new line when there is a comment, but keep on the same line generally

**Comment by vbfox** [comment]
Sorry
