### ISSUE TITLE
Intellisense issue when target relative DLL

### ISSUE THREAD

**Issue by klettier** [ionide/ionide-vscode-fsharp#776]
Hello,

I don't manage to get intellisense (in .fsx) on **ManagementScope** with the code below

```fsharp
#r "System.Management.dll"
open System.Management

let scope = ManagementScope("")
```

To be able to get it I need to reference the full path to the **Management dll**

```fsharp
#r @"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Management.dll"
open System.Management

let scope = ManagementScope("")
```

The interesting part is the fact that both codes are working and target the same dll

**Do you know why there is no intellisense for the first sample ?**

Thanks,

kévin

**Comment by vbfox** [comment]
I think you have to remove the ".dll" part for intellisense to work on GAC assemblies

**Comment by klettier** [comment]
It was quick, thanks!
