### ISSUE TITLE
Run Script vs Send File

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#779]
What's the difference? Don't do they basically the same, evaluate the entire file?

**Comment by vbfox** [comment]
Send:
* Run in the context of your current FSI session
* Get variables, state, loaded libraries, ... from previous commands you run
* Affect the FSI environment, changes are still there after so you can explore things easily

Run:
* Create a fully separate session that doesn't get affected by FSI state
* Exactly the same as running FSI on the script, so you can test exactly what you would get running this script later/on another dev machine/...
* Doesn't affect your FSI session, you can continue to iterate on the code while something long runs
* FSI run in non interactive mode, so you can use console functions that draw at specific position to the screen that would break the interactive mode

So yes they evaluate the entire file but the context is slightly different and
