### ISSUE TITLE
run ionide with .NET Core 

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#78]
Following twitter discussion, what's missing to run ionide with .NET Core?

**If it's in the roadmap to use .netcore, otherwise just close this issue, np**
I understand atm .net core seem in flux, but works, netcore is going rtm end of month.
Tooling instead it's not going to improve a lot soon, so is project.json for some time until c# start use msbuild instead of project.json, and we need time after that to use it.
But support need time, so i understand if people want to wait.
- [x] FCS ref https://github.com/fsharp/FSharp.Compiler.Service/issues/465

from `paket.dependencies`
- [ ] `ionide/ionide-vscode-helpers`
- [ ] `ionide/FSharpFormatting.CLI`
- [ ] `ionide/FsAutoComplete`
- [ ] `fsprojects/Forge` (or can be excluded for now)
- [ ] `ionide-fsgrammar`
- [ ] ... ?

@Krzysztof-Cieslak  i'd like to help to bootstrap the .net core support of F# projects, but i dont know what prioritize atm after suave.

**Comment by Krzysztof-Cieslak** [comment]
I guess most important is FCS and FsAutoComplete. Would leave Forge out of equation for now. Changes in plugins would be really small. Big thing is making our language services working without mono installed.

**Comment by ncave** [comment]
Is adding support for the .NET Core debugger possible? That would be so awesome!

**Comment by Krzysztof-Cieslak** [comment]
I think normal .Net Core debugging extension should / will work with F#.

**Comment by 7sharp9** [comment]
FCS just needs a port of fsyacc and fslexx, but other than that it works thanks to @enricosada last night for helping me with that.

**Comment by 7sharp9** [comment]
@Krzysztof-Cieslak Running without mono, would that just require a change to the command called by the plugin?

**Comment by Krzysztof-Cieslak** [comment]
@7sharp9, yes. It should be really easy to change.

**Comment by 7sharp9** [comment]
I started on porting fsautocomplete core, first issues are projectcracker and Fsharp.lint

**Comment by Krzysztof-Cieslak** [comment]
I think we can ignore FSharpLint for now ( just comment it out). ProjectCracker is important I guess.

**Comment by 7sharp9** [comment]
Yeah its a real pain for me working with no tools at all. :-(

**Comment by 7sharp9** [comment]
I started it here anyway if anyone want to help out: https://github.com/7sharp9/FsAutoComplete/tree/dotnetcore
Still 16 errors relating to cracker and lint

**Comment by 7sharp9** [comment]
@enricosada / @Krzysztof-Cieslak 
Down to one error:
```
Process ID: 12564
    FSharpMethodGroupItem
is not compatible with type
    Overload
The type 'FSharpMethodGroupItem' is not compatible with the type 'Overload'
/usr/local/share/dotnet/dotnet compile-fsc @/Users/7sharp9/fsharp/FsAutoComplete/src/FsAutoComplete.Core/obj/Debug/netstandard1.5/dotnet-compile.rsp returned Exit Code 1
/Users/7sharp9/fsharp/FsAutoComplete/src/FsAutoComplete.Core/CompilerServiceInterface.fs(154,5): warning FS0044: This construct is deprecated. Renamed to TryGetRecentCheckResultsForFile
/Users/7sharp9/fsharp/FsAutoComplete/src/FsAutoComplete.Core/CompilerServiceInterface.fs(154,5): warning FS0044: This construct is deprecated. Renamed to TryGetRecentCheckResultsForFile
/Users/7sharp9/fsharp/FsAutoComplete/src/FsAutoComplete.Core/CommandResponse.fs(259,56): error FS0193: Type constraint mismatch. The type

Compilation failed.
```
Its hard to figure out what its complaining about?

**Comment by enricosada** [comment]
projectcracker see https://github.com/fsharp/FSharp.Compiler.Service/issues/582#issuecomment-226945575
I'll try to help with projectcracker

@7sharp9 amazing fast!

**Comment by enricosada** [comment]
@7sharp9 let me check the error

**Comment by 7sharp9** [comment]
@enricosada projectcracker is done, I just hadn't added the package via -f yet.

**Comment by enricosada** [comment]
@7sharp9 has issue, it's not using the right dependencies i think, see https://github.com/fsharp/FSharp.Compiler.Service/pull/583
we need to use preview1 dependencies only, published on nuget. bleeding edge is bad

**Comment by 7sharp9** [comment]
@enricosada I just used a new project then added the files from fsauto to the list.

The erro here seems to be `o.IsStaticArguments` no longer exists I think.

**Comment by enricosada** [comment]
@7sharp9 cloning you repo atm

**Comment by 7sharp9** [comment]
Its hard to tell, it looks like the error message form the compiler has been clipped short.

**Comment by enricosada** [comment]
@7sharp9 https://github.com/fsharp/FSharp.Compiler.Service/commit/73c07965e07f3900bbc6d47f33b3948de2df5e16

it's remotes, check StaticParameters

**Comment by 7sharp9** [comment]
Yeah just added an array length, that must be an API change in FCS, just pushed anyway.

**Comment by 7sharp9** [comment]
@enricosada Theres some TODO's and warnings left but it does build, ran out of time for now.  fixes welcome :-)

**Comment by Krzysztof-Cieslak** [comment]
Guys, try also merging https://github.com/fsharp/FsAutoComplete/pull/110 up to dotnetcore branch. It's version currently used by Ionide.

**Comment by 7sharp9** [comment]
Ive ran out of time for now, if anyone gets a chance to forge ahead then that would be great.
(Or fix the TODO's or anything Ive screwed up :-) )

**Comment by enricosada** [comment]
i'll do a build to check in your repo

**Comment by 7sharp9** [comment]
Ok, down to last error on the suave project:
```
/Users/7sharp9/fsharp/FsAutoComplete/src/FsAutoComplete.Suave/FsAutoComplete.Suave.fs(41,33): error FS0039: The field, constructor or member 'SetMinThreads' is not defined
```
After that, just the todo's.

**Comment by enricosada** [comment]
I'll continue tomorrow.
Btw we should if possible do

```
#if NETSTANDARD1_5
```

Easier to merge as pr

**Comment by Krzysztof-Cieslak** [comment]
I'm pretty sure `SetMinThreads` was due to some mono problem, it might not be needed at all with .Net Core. 

Also I would like to think how to deploy it with plugin. Omnisharp team produces separate releases for each platform (https://github.com/OmniSharp/omnisharp-roslyn/releases) and downloads appropriate version during plugin start. 

Why not create one release for all platforms? 

How big would be FSAC.Suave with all dependencies (in comparison to current)? 

Should we use .Net Core version also on Winodws?

**Comment by Krzysztof-Cieslak** [comment]
I've tried running `dotnet restore` after clean clone of Dave's repo. 

```

Errors in D:\Programowanie\Projekty\FsAutoComplete\src\FsAutoComplete.Core\project.json
    Unable to resolve 'Microsoft.FSharp.Core.netcore (>= 1.0.0-alpha-160509)' for '.NETStandard,Version=v1.5'.
    Unable to resolve 'FSharp.Compiler.Service.netcore (>= 1.0.0-alpha-00001)' for '.NETStandard,Version=v1.5'.
    Unable to resolve 'FSharp.Compiler.Service.ProjectCracker.netcore (>= 1.0.0-alpha-00001)' for '.NETStandard,Version=v1.5'.
    Unable to resolve 'Microsoft.FSharp.Compiler.netcore (>= 1.0.0-alpha-160318)' for '.NETCoreApp,Version=v1.0'.

Errors in D:\Programowanie\Projekty\FsAutoComplete\src\FsAutoComplete.Suave\project.json
    Unable to resolve 'FSharp.Compiler.Service.netcore (>= 1.0.0-alpha-00001)' for '.NETStandard,Version=v1.5'.
    Unable to resolve 'FSharp.Compiler.Service.ProjectCracker.netcore (>= 1.0.0-alpha-00001)' for '.NETStandard,Version=v1.5'.
    Unable to resolve 'Microsoft.FSharp.Compiler.netcore (>= 1.0.0-alpha-160318)' for '.NETCoreApp,Version=v1.0'.
```

Do I need to do something more?

**Comment by enricosada** [comment]
> Why not create one release for all platforms?

Because it's easier do that for multiple plat. With `dotnet publish` you can create an xcopy ready directory with all deps and program. 
Also because each os need a different corehost.exe (renamed as `program.exe`) to run `program.dll` (your console app). And dpendencies may vary on each platform.

So is better to have multiple versions, less disk size. 

Otherwise you need dotnet core installed in the PATH (not the experience you want, because you want to pin to a specific dotnet sdk)


> Do I need to do something more?

check what feed `dotnet restore` use (the output), fsharp-daily is required and you need the built FCS package (after that you can `dotnet restore -f /path/to/FCS/packages` )

**Comment by 7sharp9** [comment]
I built fcs and cracker locally and used the -f option as Enrico mentioned.  I guess when the PR is finished for fcs the nugget  can be published. Not sure why it isn't yet.

**Comment by Krzysztof-Cieslak** [comment]
@7sharp9: Could you upload compiled version somewhere? I don't want to go through hole fcs building process.

**Comment by enricosada** [comment]
@Krzysztof-Cieslak check FCS appveyor build artifact or add FCS appveyor feed.

**Comment by 7sharp9** [comment]
```
[I] 2016-06-19T16:27:58.5944620Z: listener started in 135.120 ms with binding 127.0.0.1:8088 [Suave.Tcp.tcpIpServer]
```

**Comment by 7sharp9** [comment]
```
[Extension Host] [E] 2016-06-19T23:10:08.7645650Z: request failed [Suave.Web.defaultErrorHandler] exn:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.FSharp.Compiler.ToolLocationHelper.ResolveAssemblyReference..ctor()
   at Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore$cont@273(String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, ResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String outputDirectory, FSharpFunc`2 logWarning, FSharpFunc`2 logMessage, FSharpFunc`2 logError, String implicitIncludeDir, String fsharpCoreExplicitDirOrFSharpBinariesDir, String frameworkRegistryBase, FSharpList`1 explicitIncludeDirs, String assemblyFoldersSuffix, String assemblyFoldersConditions, Boolean allowRawFileName, Unit unitVar)
   at Microsoft.FSharp.Compiler.MSBuildResolver.Resolve(ResolutionEnvironment resolutionEnvironment, IEnumerable`1 references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String outputDirectory, String fsharpBinariesDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, String frameworkRegistryBase, String assemblyFoldersSuffix, String assemblyFoldersConditions, FSharpFunc`2 logmessage, FSharpFunc`2 logwarning, FSharpFunc`2 logerror)
   at Microsoft.FSharp.Compiler.CompileOps.Resolve@3005-2(TcConfig tcConfig, ResolveAssemblyReferenceMode mode, range errorAndWarningRange, String targetFrameworkMajorMinor, String targetProcessorArchitecture, String outputDirectory, FSharpList`1 targetFrameworkDirectories, IEnumerable`1 references, Boolean showMessages)
   at Microsoft.FSharp.Compiler.CompileOps.TcConfig.TryResolveLibsUsingMSBuildRules(TcConfig tcConfig, FSharpList`1 originalReferences, range errorAndWarningRange, ResolveAssemblyReferenceMode mode)
   at Microsoft.FSharp.Compiler.CompileOps.TcAssemblyResolutions.Resolve(TcConfig tcConfig,
threadService.ts:207 [Extension Host]  FSharpList`1 assemblyList, FSharpList`1 knownUnresolved)
   at Microsoft.FSharp.Compiler.CompileOps.GetAssemblyResolutionInformation(TcConfig tcConfig)
   at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.GetFullClosureOfScriptSource(String filename, String source, CodeContext codeContext, Boolean useMonoResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCommmandLineArgs)
   at Microsoft.FSharp.Compiler.CompileOps.LoadClosure.ComputeClosureOfSourceText(String filename, String source, CodeContext implicitDefines, Boolean useMonoResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCompilerOptions)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$Service.GetProjectOptionsFromScript@2526.Invoke(CancellationToken _ct)
   at <StartupCode$FSharp-Compiler-Service-netcore>.$Reactor.EnqueueAndAwaitOpAsync@139-2.Invoke(Unit unitVar0)
```
I get that error, looks like msbuild stuff is still in there.

**Comment by ncave** [comment]
Yes, [#581](https://github.com/fsharp/FSharp.Compiler.Service/issues/581) is still an open issue.

**Comment by duckmatt** [comment]
I'll try to get fsharplint running on dotnet core this week

**Comment by 7sharp9** [comment]
@duckmatt If there are not many dependencies if should only take ten mins :-)

**Comment by 7sharp9** [comment]
Just ported the main fable project too
>dotnetcore all the things!

**Comment by Krzysztof-Cieslak** [comment]
So now, we just need to port ionide to Fable ;)

**Comment by enricosada** [comment]
i added some notes, pls fix nuget.config and project.json as per https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-preview1.
Btw it helps because preview2 is near, and the preview1 had some issue when released (dev feed in nuget, the compile-fsc version range was too big) and i dont want to break people build.
I hope (i'll check) that next preview2 doesnt do the same errors (no devs feed needed, only nuget.org).

i'll send the pr to suave.

**Comment by enricosada** [comment]
I added some FAQ (netcore vs f#) in https://github.com/dotnet/netcorecli-fsc/wiki/FAQ

@7sharp9 if you have a feedback about that, i'd really like to hear it because you converted already two proj (and that mean a solid second position as migrator :smile: )

Anyway, pls check the deps of the project, like in the faq:

`netstandard1.5` for libraries, with `NETStandard.Library` dependency (no `NetCore.App`)
`netcoreapp1.0` for console app, with NetCore.App` (that already reference `NETStandard.Library`)

otherwise ionide bundle it's going to be big :smile:

**Comment by 7sharp9** [comment]
@enricosada So you want me to tweak some settings, I'll have a look now.  I think there are still msbuild ref issues in FCS too :-(

**Comment by 7sharp9** [comment]
@enricosada Im also using:
```
  "runtimes":{
    "osx.10.11-x64": { }
```
For publish to work in fsauto.suave

**Comment by duckmatt** [comment]
I've got fsharplint running on dotnet core, are any projects using paket to create a nuget package, or is packaging to be done as a separate step with `dotnet pack`?

**Comment by enricosada** [comment]
See suave (rake) or chessie (fake). But process is the same. 
Ping me if you need help

**Comment by enricosada** [comment]
Let me review it. For example build tools dev feed is not needed

**Comment by duckmatt** [comment]
Thanks that'll be really helpful :) I'll take a look at using the same approach as chessie tonight

**Comment by kontomondo** [comment]
@7sharp9 @duckmatt anything I can do to help move this forward?

**Comment by duckmatt** [comment]
@kontomondo fsharplint should be nearly ready to go once we have a dotnet core version of FCS on nuget

**Comment by gulshan** [comment]
Is it possible to use Ionide with only dotnet core F# now? Do I have to change any configuration for this? I'm using VSCode.

**Comment by Krzysztof-Cieslak** [comment]
It's not. You can use Ionide with dotnet core projects but you still need mono / .Net Framework to run language services.

**Comment by Korbin73** [comment]
Will fsAutocomplete also have a problem understanding .Net core lib namespaces like AspnetCore? I'm assuming FsAutoComplete is assuming the namespaces in core are organized the same way they are in Mono right?

**Comment by cotyar** [comment]
@Krzysztof-Cieslak, first of all great thanks for the great work you're doing with Ionide!
A quick one please, for .Net Core project is it possible to use REPL (on Mac), sorry haven't found a simple way of doing so.
And if not, is this support planned for any near future please?

**Comment by enricosada** [comment]
@cotyar no repl on .net core 1.0. will be implemented for .net core 2.0, ref roadmap https://github.com/Microsoft/visualfsharp/issues/2400

**Comment by cotyar** [comment]
Thank you Enrico.

**Comment by enricosada** [comment]
FSAC on .net core is WIP in https://github.com/fsharp/FsAutoComplete/pull/224

**Comment by enricosada** [comment]
@duckmatt do you need help/review for `FsharpLint` netstandard/netcore?
i'd like to have a `netstandard2.0` version if possibile to use in FSAC

**Comment by enricosada** [comment]
WIP in https://github.com/ionide/ionide-vscode-fsharp/issues/78
