### ISSUE TITLE
Cannot disable value signatures from displaying

### ISSUE THREAD

**Issue by moonPtr** [ionide/ionide-vscode-fsharp#788]
![code_2018-04-13_19-06-08](https://user-images.githubusercontent.com/32428601/38748257-ccf77ff4-3f4d-11e8-992b-80b6bd5bece7.png)

I'm guessing the settings for these signatures are FSharp.lineLens.prefix and FSharp.lineLens.enabled, but no matter how I edit these settings (even after reloading Code), the appearance of these signatures doesn't change

Is there any proper way to disable / edit these?
Edit: Managed to disable it by turning off codeLens for F# files alltogether, but I'm still confused as to what the line lens options actually do

**Comment by vbfox** [comment]
LineLens are an alternative to CodeLens that show the type signatures at the end of the declaration line as a decoration that looks like a comment.

They look like that: 

![2018-04-13 21_38_03- languageservice fs - ionide-fs - visual studio code](https://user-images.githubusercontent.com/131878/38754643-f67c4728-3f62-11e8-962c-58d657a475bf.png)


You can enable them in your configuration like that :

```json
"FSharp.lineLens.enabled": "always",
```

(Better to disable codelens before or the signatures will appear twice)

**Comment by vbfox** [comment]
Also the prefix allow you to change the "comment-like" appearance :

![2018-04-13 21_40_51-languageservice fs - ionide-fs - visual studio code](https://user-images.githubusercontent.com/131878/38754783-6f0744f4-3f63-11e8-8323-824e9937bbb0.png)

**Comment by moonPtr** [comment]
Ooooohhh...
I see, thank you!

**Comment by vbfox** [comment]
>  Can we have a suffix too?

Not yet, I believe it would be a relatively simple PR :)

**Comment by moonPtr** [comment]
Maybe, but I'm not super familiar with git and too afraid to mess something up xD
