### ISSUE TITLE
Inconsistent signatures of class properties

### ISSUE THREAD

**Issue by moonPtr** [ionide/ionide-vscode-fsharp#789]
![code_2018-04-14_14-40-24](https://user-images.githubusercontent.com/32428601/38768293-cdbf2078-3ff1-11e8-84f8-6bccf7e62bfd.png)

CodeLens/LineLens shows the property as having the type unit -> int, while hovering over the property shows it as having type int

**Comment by 7sharp9** [comment]
Technically `unit -> int` is the correct signature for a property, Im not sure if the line/lens is using the symbols to render, if so it should be easy to detect the presence of a property and renderer differently.

**Comment by priort** [comment]
I had a look at this. I might be able to give it a go over the next couple of days with some guidance - might be a good one for a first time open source contribution :) I have the ionide codebase building and running locally and I can see where the code lens signatures get resolved at formatSignature in CodeLens.fs - we don't seem to have access to the type of symbol at that point so it may need to be passed down to this function somehow. I notice that hover and code lens seem to call different FSAC apis - with hover calling "signature" and code lens using "signatureData" but I could be wrong on this :)

**Comment by Krzysztof-Cieslak** [comment]
Probably problem is somewhere in here - https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L152-L173

**Comment by priort** [comment]
okay, I haven't tried to get FSAC building yet 😄 If I get some time over next couple of days, I'll give it a go.

**Comment by priort** [comment]
@Krzysztof-Cieslak 
I got FSAC building locally and I was able to make a change to make the type signature the same as SignatureData that we see on code lens - see screenshot below.  I tried this first because, as @7sharp9 said, unit -> int is the correct signature for a property. Should I put in a pr in FSAC for this change or should I put it back so that the type signature is Y: int and change SignatureData instead for code lens.

The change I made in FSAC is in SignatureFormatter.fs line 203
https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/SignatureFormatter.fs#L202-L203
Changed 
```
| [[p]] when  maybeGetter && formatParameter p = "unit" -> //Member or property with only getter
  modifiers ++ functionName + ":" ++ retType
```

to

```
| [[p]] when  maybeGetter && formatParameter p = "unit" -> //Member or property with only getter
  modifiers ++ functionName + ": unit ->" ++ retType
```

![image](https://user-images.githubusercontent.com/13556648/39071762-31c89df4-44e0-11e8-89e7-8e24644eea22.png)

**Comment by 7sharp9** [comment]
Technically it is the right signature, however, we format the symbol to
look like a .net property.  I believe the lens code should change that
match.  They are both correct signature.

**Comment by priort** [comment]
Cool, Ill have a look at SignatureData in FSAC. Thanks.

**Comment by priort** [comment]
I made the signatureData consistent in FSAC with that which is returned from signature for getter properties. 
I submitted a PR to FSAC here: https://github.com/fsharp/FsAutoComplete/pull/289

Here is a screen shot of the fix i vscode ionide:
![image](https://user-images.githubusercontent.com/13556648/39086165-9750efb4-4585-11e8-9a1f-55b508d4562d.png)

**Comment by priort** [comment]
Ah, I broke something in SignatureFormatter in FSAC - I closed the PR and will re-submit when I fix.

**Comment by Krzysztof-Cieslak** [comment]
Released in `3.19.4`, thanks a lot @priort!

**Comment by 7sharp9** [comment]
+1

**Comment by priort** [comment]
Awesome thanks a million!
