### ISSUE TITLE
command 'fsharp.getHelp' not found

### ISSUE THREAD

**Issue by Rhywun** [ionide/ionide-vscode-fsharp#790]
I am attempting to access the "Go to MSDN help" feature mentioned on the extension info page. I found a command called "F#: Get Help" so I placed my cursor on a word and called the command but received the error shown above as a Notification in VSCode. No output appeared in the log.

ionide-fsharp 3.19.2
VS Code 1.22.2
MacOS 10.12.6

**Comment by inosik** [comment]
https://github.com/ionide/ionide-vscode-fsharp/blob/0552a4757279830c41105bf9d0f4c24e1cbbbf14/release/package.json#L194

https://github.com/ionide/ionide-vscode-fsharp/blob/2161aa9f8120a1fe5d862ea3eeb99361c212ef19/src/Components/Help.fs#L41

Are command names case sensitive in VS Code?

**Comment by Krzysztof-Cieslak** [comment]
I think it was not the case in the past, but maybe something has changed on Code side.

**Comment by Krzysztof-Cieslak** [comment]
Funny fact - it's working fine for me when pressing `Shift+F1`, it's not working for me when using `F#: Get Help` from command palette

**Comment by Krzysztof-Cieslak** [comment]
Fixed by 95cf0ef52c57e2c4b466132b95f4c3df3f2e94d8
