### ISSUE TITLE
Upgrade Fable dependencies version

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#794]
In `paket.dependencies`, we are locking the Fable dependencies versions:

```fs
clitool dotnet-fable 1.2.4
nuget Fable.Core 1.2.4
nuget Fable.Import.Node 0.1.5
nuget Fable.Import.Browser 0.1.2
```

I am working on adding [Html to Elmish](https://mangelmaxime.github.io/html-to-elmish/) in Ionide, would you be ok if I upgrade the Fable dependencies to latest version ?

Or do I need to lower the requirements from my libraries ? `Thoth.Json` and `Fable.HtmlConverter`?

**Comment by Krzysztof-Cieslak** [comment]
I believe I've hit some breaking changes in compiled JS code last time I've tried to bump version. And since I was too busy to investigate I've chosen simplest option - pinning versions.

I'd be happy to see PR updating those deps to latest versions and fixing any potential problems

**Comment by MangelMaxime** [comment]
Ok, I will try to update the dependencies then and see the result :)
