### ISSUE TITLE
Incorrect(?) assembly for top level namespaces

### ISSUE THREAD

**Issue by moonPtr** [ionide/ionide-vscode-fsharp#796]
![code_2018-04-25_17-21-33](https://user-images.githubusercontent.com/32428601/39255639-469c8080-48ad-11e8-80ab-b24afac40223.png)
![code_2018-04-25_17-22-16](https://user-images.githubusercontent.com/32428601/39255642-487b65e2-48ad-11e8-91f4-b858e6706e93.png)

Guessing this has to do with several assemblies defining the same namespaces and the extension just picking the first it finds, maybe remove that line when it's actually ambiguous?

**Comment by Krzysztof-Cieslak** [comment]
I think it's bit by design, that's how compiler resolves those opens.
