### ISSUE TITLE
Feature Request: Sync with active document 

### ISSUE THREAD

**Issue by davidtme** [ionide/ionide-vscode-fsharp#801]
The new F# side project explorer button is great :) Would you be able to add a button/keyboard shortcut that acts like the "Sync with Active Document" in VS2017 and highlights the active file in the project explorer?

![image](https://user-images.githubusercontent.com/1804141/39814686-32082bca-538d-11e8-92a7-2b02ddeccc18.png)

**Comment by Krzysztof-Cieslak** [comment]
Something like that, and code for it is already merged. Unfortunatly due to some bugs on Code side we can't enable feature yet.
