### ISSUE TITLE
F# activity is always added to the activity bar

### ISSUE THREAD

**Issue by inosik** [ionide/ionide-vscode-fsharp#802]
For now, I'd prefer to use the project explorer in the explorer activity, but even when setting `"FSharp.showProjectExplorerIn": "explorer"`, the activity is added to the activity bar. I have also set `"FSharp.codeOutline": false`, because I use another extension for code outlines, but even with `"FSharp.showCodeOutlineIn": "explorer"`, the F# activity is always added.

**Comment by Krzysztof-Cieslak** [comment]
Cc: @vbfox

**Comment by vbfox** [comment]
Yes, there is no way to remove them in code, it must be done manually. Right click on the activity bar and uncheck **F#** vscode will remember your preference.

Suggestions on how vscode could solve this are tracked by the following issues in vscode repo :

* https://github.com/Microsoft/vscode/issues/48704
* https://github.com/Microsoft/vscode/issues/49145

**Comment by mrkaspa** [comment]
Having the same problem here, I tried this

"FSharp.enableTreeView": false,
"FSharp.codeOutline": false,

but did not work

**Comment by vbfox** [comment]
@mrkaspa :

Set 
```
"FSharp.showCodeOutlineIn": "explorer",
"FSharp.showProjectExplorerIn": "explorer"
```

In settings then reload the window, right click on the F# icon on the left and select "Hide".

**Comment by mrkaspa** [comment]
@vbfox it works the first time then I tried another project and made "code ." inside the folder through the cmd and the fsharp icon came back again

**Comment by vbfox** [comment]
@mrkaspa I re-tested it and it works for me, I had a single vscode instance, changed the activity to hidden and closed vscode. Now whenever I start it via the command line or the shell it's kept hidden.

If you it doesn't work for you it might be a vscode bug, maybe raise it on their repo.

**Comment by mrkaspa** [comment]
@vbfox seems to work after updating the vscode
