### ISSUE TITLE
Multi Cursor Broken

### ISSUE THREAD

**Issue by decapo01** [ionide/ionide-vscode-fsharp#805]
The multiple cursor functionality is broken for *.fs files with this plugin enabled.  I'm on Ubuntu 16.04 with vscode 1.23.1 and plugin version 3.20.3.

I disabled this plugin, got it to work then enabled and tried again and it didn't work.  My key bindings are Ctrl+Alt+Up Arrow and Ctrl+Alt+Down Arrow

**Comment by MangelMaxime** [comment]
This is really strange because there is no shortcut attached by Ionide to `Ctrl+Alt+Up` or `Ctrl+Alt+Down`.

**Comment by Krzysztof-Cieslak** [comment]
I can't repro, multi cursors works just fine for me. :/

**Comment by decapo01** [comment]
Sorry about this one guys.  My key bindings were for both Ctrl+Alt arrow and Ctrl+Shift arrow and I wasn't paying attention to what keys I was selecting.  Ctrl+Shift arrow appears to move an F#: file up and down in the project.  I've removed that and got it working again.
