### ISSUE TITLE
Code Outline jump to line in focused editor, not the correct file editor.

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#811]
Two-column layout, different files opened.
Have focus in right editor.
Code Outline shows correct outline for left editor.
Click on anything in the outline while focused on right editor.
Right editor jump to correct line for the clicked item, just in the wrong editor.

**Comment by Krzysztof-Cieslak** [comment]
Closing this since we are going to deprecate our implementation of CodeOutline as it's now built-in feature of VSCode
