### ISSUE TITLE
.Net Framework projects fail to load

### ISSUE THREAD

**Issue by SCullman** [ionide/ionide-vscode-fsharp#816]
Created a fresh F# Net framework library in VS2017.
When I open the project with Ionide/vscode, 
the Project explorer fails with "Microsoft.Build, Version=12.0.0.0 not found"

- The environment variable is set: ``MSBUILD_PATH = "c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\"``
- "F#: Pick MsBuild Host" links also with the same MsBuild host.

I have no idea why it is looking for version 12.0.0.0. 

Vscode 1.23.1, Ionide FSharp 3.20.4. It used to work few weeks ago.

**Comment by SCullman** [comment]
Ok, when I create the project of type in Ionide, it has already the new project format and it works just fine and it still targets .Net Framework.
So the old format is now deprecated in Ionide?

**Comment by Krzysztof-Cieslak** [comment]
Old format is not deprecated, but is unstable (as always) and have some weird dependencies that no one understands. Using new format is recommended.
