### ISSUE TITLE
Improve inlined icon in project explorer

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#818]
1. Run icon shouldn't be inlined for not executable project (libraries).
2. For projects that failed there should be icon for going to status page.
3. Maybe? there should be build icon.

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak @enricosada 

I have a NetCore project and when I display the "Project status" it says:

> Output Type: lib
> Output: /Users/maximemangel/Workspaces/Github/ionide/ionide-fsgrammar/sample-code/bin/Debug/netstandard2.0/SampleCode.dll
> 
> Project Type: .NET Sdk (dotnet/sdk)

So it's considered a`lib`, however [here](https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Core/Project.fs#L504) we consider that all the NetCore project are executable.

For me an executable NetCore project is when the fsproj contains something like:

```xml
<OutputType>Exe</OutputType>
<TargetFramework>netcoreapp2.1</TargetFramework>
```

Is the current implementation of current or should it consider this particular project as a lib?

If you want to take a look at the project, it is the one from [Ionide grammar](https://github.com/ionide/ionide-fsgrammar/blob/master/sample-code/SampleCode.fsproj)

**Comment by baronfel** [comment]
That makes sense to me, we should be looking for the correct OutputType in that case because libraries may choose to target netcoreapp TFMs in order to make use of TFM-specific types.

**Comment by MangelMaxime** [comment]
I am asking this question because of point 1:

> 1. Run icon shouldn't be inlined for not executable project (libraries).

As Ionide, already show the Run icon only if the project is an executable: [source](https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L940-L949)

**Comment by enricosada** [comment]
an executable has set the `OutputType`, for old sdk and .NET sdk.
FSAC has the info already, and that should be in the response of the info
