### ISSUE TITLE
All code turned comment color after a '///' comment

### ISSUE THREAD

**Issue by vanceism7** [ionide/ionide-vscode-fsharp#828]
### Problem
I'm getting a real weird error with ionide's syntax highlighting this morning. Any code taking place immediately after a markdown comment '///' is colored as comment. The tool-tips are still registering, but I'm getting no auto-completion on anything comment colored  
  
![ionidecomment](https://user-images.githubusercontent.com/2016375/40558398-0e378682-6008-11e8-82dd-aded30288c44.PNG)

If I put newlines after the '///' lines, then the normal functionality comes back, but otherwise it's all coming out like this in every project I open. Has anyone else ever seen this?

### Steps to reproduce
I have no idea. I haven't updated anything and it was working fine just last night.

### Machine infos

* Operating system: **Windows 10 Home - 64 bit**
* VSCode: **1.23.1**
* MSBuild version:
```shell
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```

[20180525-105213.log](https://github.com/ionide/ionide-vscode-fsharp/files/2040431/20180525-105213.log)

**Comment by MangelMaxime** [comment]
Ok, I am able to repo this error.

Wrong color:
```fs
/// Maxime test
namespace Fable.Markdown
```

Ok when:
```fs
/// Maxime test
/// 
namespace Fable.Markdown
```

I will look to fix this

**Comment by vanceism7** [comment]
Thanks, that's what I've been doing for the moment. It's more of an annoyance than anything just when having to read through other code. But no biggie, thanks for looking into this

**Comment by MangelMaxime** [comment]
I am kind of the author of this bug so... :)

A fix is ready and should be included in the next release

**Comment by Krzysztof-Cieslak** [comment]
Fix released in `3.20.8`

**Comment by alfonsogarciacaro** [comment]
A comment like this also changes the color of the rest of the file.

```fsharp
    (** Flow control *)
    | BasicPatterns.FastIntegerForLoop(Transform com ctx start, Transform com ctx limit, body, isUp) ->
        match body with
        | BasicPatterns.Lambda (BindIdent com ctx (newContext, ident), body) ->
```

Turning it to `(* Flow control *)` or `// Flow control` fixes the issue. Comments starting with `(**` [are used for FSharp.Formatting](https://fsprojects.github.io/FSharp.Formatting/literate.html). I'm not using it to generate docs now, so it's not a problem to change the comment but I wanted to let you know.

**Comment by MangelMaxime** [comment]
Thanks for the report @alfonsogarciacaro 

Note sure, if I will be able to fix the single line version of `(** *)` I will give it a try.

For reference, if the comments are indented then it's also failing.

Code:
```fs
    (**
    # First-level heading
    Some more documentation using `Markdown`.
    *)
    module SampleCode.SimpleTypes
```

**Comment by alfonsogarciacaro** [comment]
I don't know how the VS Code grammar works, but maybe replacing [this line](https://github.com/ionide/ionide-fsgrammar/blob/7ac2813fa6f40d59e8f078738db2d4f9485c4978/grammar/fsharp.json#L120) with the following works?

```
                    "name": "comment.block.fsharp",
                    "begin": "(\\(\\*+(?!\\)))",
                    "end": "(\\*\\))",
```

> I just added `+` after `\\*` in the second line.

**Comment by MangelMaxime** [comment]
I think if we do that then, we will stop supporting the markdown highlighting. Because `(**` will match

**Comment by MangelMaxime** [comment]
Oh, I think I can detect the failing case and don't active the markdown support if the line start by `(** ..... *)`

**Comment by alfonsogarciacaro** [comment]
Another funny behavior with new coloring ;)

<img width="507" alt="screen shot 2018-05-30 at 5 19 31 pm" src="https://user-images.githubusercontent.com/8275461/40729938-ce9bca4a-642d-11e8-9e1d-030a419f06c7.png">

**Comment by MangelMaxime** [comment]
The fix is already added to the grammar: https://github.com/ionide/ionide-fsgrammar/pull/67

We just need to new release of Ionide to fix the `of....` thing.

We also already know the bug about tuple declaration: https://github.com/ionide/ionide-fsgrammar/issues/68

**Comment by alfonsogarciacaro** [comment]
Nah, don't worry. I'm just reporting things I see here to help you. The new Ionide features are awesome, thanks a lot for your hard work! :clap: 🥇 :clap:
