### ISSUE TITLE
Unable to load on mac

### ISSUE THREAD

**Issue by danielo515** [ionide/ionide-vscode-fsharp#834]
Hello,

For some reason this fantastic extension is not loading on macOS within VSC:
Here is the error I'm getting:

```

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2255 command 'fsharp.NewProject' not found
e.onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2255
```

Regards

**Comment by zaaack** [comment]
Hi, I hit this problem, too. It worked after I changed a setting:

```json
    "FSharp.fsacRuntime": "net",
```

**Comment by danielo515** [comment]
Hello @zaaack ,
I tried changing that same setting to "netcore" (it was already on "net" ) and restart and it does not work neither.

Very sad
