### ISSUE TITLE
Incorrect editor colourisation of `application` in value name

### ISSUE THREAD

**Issue by bentayloruk** [ionide/ionide-vscode-fsharp#836]
### Problem

The text "application" is being coloured blue when your code refers to a let bound value name.

![screen shot 2018-06-04 at 14 27 04](https://user-images.githubusercontent.com/189409/40920304-03cc744c-6804-11e8-860f-cfb7f3ecc88d.png)

### Steps to reproduce

Open an F# file, define and use a value with "application" in it's name.

### Machine infos

* Operating system: **Darwin**
* Arch: **x64**
* VSCode: **1.23.1**
* Runtime: **.Net**
* Mono version:
```shell
Mono JIT compiler version 5.12.0.226 (2018-02/9824e260f56 Mon Apr 30 18:45:52 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```
* MSBuild version:
```shell
Microsoft (R) Build Engine version 15.7.0.0 (xplat-master/402b4b23 Wed Mar 28 23:51:55 EDT 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by Krzysztof-Cieslak** [comment]
CC: @MangelMaxime

**Comment by MangelMaxime** [comment]
Hum this is strange the only rules using `application` directly in the regex is [the one for cexprs](https://github.com/ionide/ionide-fsgrammar/blob/master/grammar/fsharp.json#L589)

@Krzysztof-Cieslak As a side note, I will probably slow down contribution on the grammar because NDC Oslo is coming and I need to finish slides :)

**Comment by Krzysztof-Cieslak** [comment]
Slides.... damn, I know i forgot about something

**Comment by inosik** [comment]
See ionide/ionide-fsgrammar#71.
