### ISSUE TITLE
How to change CodeLens font in VSCode?

### ISSUE THREAD

**Issue by boyedarat** [ionide/ionide-vscode-fsharp#837]
I am using the FiraCode font for the editor in VS Code. The autocomplete and code tips use the same font as the editor, except for:
![capture](https://user-images.githubusercontent.com/22816484/40953992-09a4785e-68b5-11e8-8c49-622fcac94dd0.JPG)

How do I change the font above to FiraCode and enable ligatures there?

**Comment by inosik** [comment]
Not possible at the moment, see Microsoft/vscode#16038.
