### ISSUE TITLE
"of" keyword is wrongly highlighted

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#838]
![image](https://user-images.githubusercontent.com/57396/40960976-913ce062-68a1-11e8-95d5-e9982eca9b98.png)

/cc @MangelMaxime

**Comment by MangelMaxime** [comment]
Already fixed in ionide-fsgrammar: https://github.com/ionide/ionide-fsgrammar/pull/67

Waiting for a new release of Ionide.

And sorry, there is a lot of small bugs with the new grammar...
