### ISSUE TITLE
Multiple forge output windows

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#84]
Forge creates multiple output windows and leaves them open (rather than reusing an existing one). You quickly end with a whole list of Forge entries in the select control of the output pane.

**Comment by Krzysztof-Cieslak** [comment]
Already fixed in Fable version... which will be merged and release soon-ish.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.0.0`
