### ISSUE TITLE
Files are not parsed 

### ISSUE THREAD

**Issue by cxk99** [ionide/ionide-vscode-fsharp#842]
Win10 + vscode 1.24.0 + Ionide fsharp 3.22.0

All my F# projects which can be parsed correctly are not parsed after ionide is updated.
When I create a new project in a new directory,  the file is not parsed either.
-------------------------------------
In f# language service channel, the following information is shown

```
[11:35:40 INFO ] Logging to output at level INFO. If you want detailed messages, try level DEBUG.
[11:35:43 INFO ] listening notification on /notify started
[11:35:43 INFO ] listening notification on /notifyWorkspace started
[11:35:44 ERROR] Cannot execute unusedOpens, File 'c:\Exercism\fsharp\binary-search\BinarySearch.fs' not parsed 
[11:35:44 ERROR] Cannot execute lint, File 'c:\Exercism\fsharp\binary-search\BinarySearch.fs' not parsed 
[11:35:44 ERROR] Cannot execute simplifiedNames, File 'c:\Exercism\fsharp\binary-search\BinarySearch.fs' not parsed 
[11:35:44 ERROR] Cannot execute unusedDeclarations, File 'c:\Exercism\fsharp\binary-search\BinarySearch.fs' not parsed 
[11:35:44 ERROR] Project loading failed, Project not restored 'c:\Exercism\fsharp\binary-search\BinarySearch.fsproj'
[11:35:45 ERROR] Cannot execute tooltip, File 'c:\Exercism\fsharp\binary-search\BinarySearch.fs' not parsed 
[11:35:45 ERROR] Cannot execute tooltip, File 'c:\Exercism\fsharp\binary-search\BinarySearch.fs' not parsed 
```

**Comment by s153083** [comment]
I had this problem as well. Neither type inference nor Intellisense was working. I fixed the issue by upgrading Mono. I was running version 4.2.1 ( I think, I can't remember) for some reason. Now I'm running 5.12.0 and both type inference and Intellisense are working again. 

If I've understood correctly, Mono is required for VSCode regardless of the OS, so this might be a fix for you too. Please correct me if I'm wrong. 

I have to be honest: I'm not exactly sure what was wrong, but I'll give my best guess:

I enabled debugging in VSCode, by setting the properties : "FSharp.logLanguageServiceRequestsOutputWindowLevel": "DEBUG", "FSharp.logLanguageServiceRequests": "both"
in the preference file and switching to the "F# language service" tab in the output pane. 

An error message stating that the method "EventSource.WriteEvent" was not found appeared every time I wrote something. Apparently, the method was overloaded, and not all overloads were implemented. It appears to have been fixed: https://bugzilla.xamarin.com/show_bug.cgi?id=27337

**Comment by cxk99** [comment]
Problem solved.  After uninstall dotnet-sdk-2.2 and 2.1 (I installed two version before),    then reinstall dotnet-sdk-2.1.3, then the problem disappeared and everthing works fine.

**Comment by cxk99** [comment]
Thanks for your help.

After re-install dotnet-sdk-2.1.3, I solved the problem.

I install both dotnet-sdk-2.2 and dotnet-sdk-2.1 before, maybe there is something wrong, I'm not sure.

But F# and Inoide work fine now, thank you for your information!




________________________________
发件人: Tord Stordalen <notifications@github.com>
发送时间: 2018年6月12日 17:01
收件人: ionide/ionide-vscode-fsharp
抄送: cxk99; Author
主题: Re: [ionide/ionide-vscode-fsharp] Files are not parsed (#842)


I had this problem as well. Neither type inference nor Intellisense was working. I fixed the issue by upgrading Mono. I was running version 4.2.1 ( I think, I can't remember) for some reason. Now I'm running 5.12.0 and both type inference and Intellisense are working again.

If I've understood correctly, Mono is required for VSCode regardless of the OS, so this might be a fix for you too. Please correct me if I'm wrong.

I have to be honest: I'm not exactly sure what was wrong, but I'll give my best guess:

I enabled debugging in VSCode, by setting the properties : "FSharp.logLanguageServiceRequestsOutputWindowLevel": "DEBUG", "FSharp.logLanguageServiceRequests": "both"
in the preference file and switching to the "F# language service" tab in the output pane.

An error message stating that the method "EventSource.WriteEvent" was not found appeared every time I wrote something. Apparently, the method was overloaded, and not all overloads were implemented. It appears to have been fixed: https://bugzilla.xamarin.com/show_bug.cgi?id=27337

27337 C Missing overloads of EventSource.WriteEvent<https://bugzilla.xamarin.com/show_bug.cgi?id=27337>
bugzilla.xamarin.com
Did you know you can report issues with Visual Studio 2017 or Visual Studio for Mac directly within the IDE? Just use Help > Report a Problem to file your issue.



―
