### ISSUE TITLE
Strange bin/obj folders created

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#844]
I'm not *sure* if this is an Ionide thing, but lately I've noticed that in my code folder (in which all my repositories live), `bin` and `obj` folders keep getting created. I've tracked it down to something to do with Code - I delete the folders, but when I open a new Code, they shortly reappear.

The bin folder contains an empty `debug\netcoreapp2.0` folder.
The obj folder contains two files in `debug\netcoreapp2.0`:

`Repos.AssemblyInfo.fs` which contains the following:

```fsharp
// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: System.Reflection.AssemblyCompanyAttribute("Repos")>]
[<assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")>]
[<assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")>]
[<assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")>]
[<assembly: System.Reflection.AssemblyProductAttribute("Repos")>]
[<assembly: System.Reflection.AssemblyTitleAttribute("Repos")>]
[<assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")>]
do()
```

and `Repos.AssemblyInfo.cache` which just contains a GUID.

Any ideas?

**Comment by Krzysztof-Cieslak** [comment]
I don't think it has anything to do with Ionide.... maybe it's something with out auto restoring process? Lot of things in Ionide assume that you open root of your repo/solution, not folder that contains lot of subfolders with different repos/solutions.

**Comment by isaacabraham** [comment]
That's what's strange - I *am* opening the folder of the repo, and not the parent folder.
