### ISSUE TITLE
Failed to start language services. Please check if mono is in PATH

### ISSUE THREAD

**Issue by ghost** [ionide/ionide-vscode-fsharp#847]
Hi, I'm trying to get Ionide setup on LinuxMint 18.3 but I keep getting the folowing message when attempting to create a new project "Failed to start language services. Please check if mono is in PATH"

in the debug console for Language service (SERVER) I'm getting this message.

"Running: dotnet /home/USER/.var/app/com.visualstudio.code/data/vscode/extensions/ionide.ionide-fsharp-3.22.1/bin_netcore/fsautocomplete.dll --mode http --port 8982 --hostPID=455
spawn dotnet ENOENT"

And for language service it says.

[16:36:23 ERROR] Failed to start language services. spawn dotnet ENOENT

I have the following settings set

"FSharp.fsacRuntime": "netcore"
"FSharp.monoPath": "/usr/bin/mono"

Any help would be greatly appreciated.

Thanks..

**Comment by Krzysztof-Cieslak** [comment]
Do you have .Net Core installed and in PATH if you're using `"FSharp.fsacRuntime": "netcore"` ?

**Comment by BecksTech** [comment]
Yes. to both of those questions sir.

**Comment by Krzysztof-Cieslak** [comment]
Does the fsautocomplete.dll file exist in the path shown in console?

**Comment by BecksTech** [comment]
Not sure if it is of any help, but here are the logs from Forge as well...

forge new project -n test -t suave --folder /home/User/PICTURES  --no-prompt
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn mono","path":"mono","spawnargs":["/home/gee5ive/.var/app/com.visualstudio.code/data/vscode/extensions/ionide.ionide-fsharp-3.22.1/bin_forge/Forge.exe","new","project","-n","test","-t","suave","--folder","/home/User/PICTURES","--no-prompt"]}

**Comment by BecksTech** [comment]
Yes. the file is present.

**Comment by MangelMaxime** [comment]
Last time, I add a similar problem I needed to uninstall Ionide, restart VSCode, and re-install Ionide.

In my case, it was because the update process had gone wrong.

**Comment by Krzysztof-Cieslak** [comment]
This is probably outdated due to Ionide 4.0 changes
