### ISSUE TITLE
Can't figure out how to start FSI

### ISSUE THREAD

**Issue by WildYorkies** [ionide/ionide-vscode-fsharp#851]
From everything that I read in the docs, FSI just comes with Ionide. So how do you start the FSI feature? I can't see this anywhere. 

In a video tutorial, I saw that it's an option in the terminal. Is this in the docs anywhere?

**Comment by vilinski** [comment]
https://fsharp.org/use/windows/
https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/fsharp-interactive/
