### ISSUE TITLE
Project Explorer Not Available

### ISSUE THREAD

**Issue by BecksTech** [ionide/ionide-vscode-fsharp#853]
Hi, I am using Ionide with vscode 1.25 and there i no project explorer available?
Am I missing something?do need to do anything to activate it?
![screenshot from 2018-07-17 16-06-46](https://user-images.githubusercontent.com/40680941/42842554-83ae5812-89db-11e8-83b2-5c7a26f08677.png)

Thanks..

**Comment by Krzysztof-Cieslak** [comment]
It's under F# button on activity bar - lowest button on your left bar.
