### ISSUE TITLE
Contributing-First Time Build is failing on first dotnet restore

### ISSUE THREAD

**Issue by brucemontegani** [ionide/ionide-vscode-fsharp#859]
When I try and build the repo for the first time the build is failing when I run `dotnet restore` just after the `yarn install` command. I am runing on MacOS High Sierra. 
Here is the first message:
 `Project "/Users/bruce/Developer/github/ionide-vscode-fsharp/paket-files/github.com/fsharp-editing/Forge/src/Forge.Core/Forge.Core.fsproj" (2:3) is building "/Users/bruce/Developer/github/ionide-vscode-fsharp/paket-files/github.com/fsharp-editing/Forge/src/Forge.ProjectSystem/Forge.ProjectSystem.fsproj" (3:5) on node 1 (default targets).
/usr/local/share/dotnet/sdk/2.1.302/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets(58,5): error MSB4062: The "GetDependsOnNETStandard" task could not be loaded from the assembly /usr/local/share/dotnet/sdk/2.1.302/Microsoft/Microsoft.NET.Build.Extensions/tools/net46/Microsoft.NET.Build.Extensions.Tasks.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/Users/bruce/Developer/github/ionide-vscode-fsharp/paket-files/github.com/fsharp-editing/Forge/src/Forge.ProjectSystem/Forge.ProjectSystem.fsproj] [/Users/bruce/Developer/github/ionide-vscode-fsharp/src/Ionide.FSharp.fsproj]`

There are others but maybe someone can figure out what is wrong based on the first one.

**Comment by MangelMaxime** [comment]
You can find some instruction in [CONTRIBUTING.md](https://github.com/ionide/ionide-vscode-fsharp/blob/master/CONTRIBUTING.md#first-time-build)

We don't really know what is causing this problem. 

> 
> If a git dependency fails to build paket won't re-do it you can run their build scripts manually:
> 
>     In paket-files\github.com\fsharp\FsAutoComplete run build LocalRelease
>     In paket-files\github.com\fsharp-editing\Forge run build Build
>
