### ISSUE TITLE
[Find All References] does not show errors

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-vscode-fsharp#86]
On VFT solution, if you try to launch Find all references, you will get the following exceptions:

![image](https://cloud.githubusercontent.com/assets/873919/16546836/40deb4fc-4160-11e6-8600-2a1c47694500.png)

errors:

![image](https://cloud.githubusercontent.com/assets/873919/16546843/5a63487a-4160-11e6-8fc1-76e7ca4a2900.png)

The first one on these four is:

```
internal error: BuildFrameworkTcImports: no successful import of d:\github\visualfsharp\Debug\net40\bin\FSharp.Core.dll
```

It does not matter why the error occurred, the problem is that the UI behaves in a wrong way, it hangs in Find all references dialog forever, showing nothing:

![image](https://cloud.githubusercontent.com/assets/873919/16546851/d142e478-4160-11e6-9a6a-ba648955fe3a.png)

 What I would like it to do is to close the dialog and show another one, containing the error message.

**Comment by Krzysztof-Cieslak** [comment]
Currently it's not possible due to limitations to VSCode extension API
