### ISSUE TITLE
"Project parsing failed" always there

### ISSUE THREAD

**Issue by vbfox** [ionide/ionide-vscode-fsharp#866]
The vast majority of our projects can't be parsed because they use advanced msbuild concept and the project-cracker parser can't work on them. That's ok I don't care we don't use ionide as our main editor on theses, they require an editor that is aware of C#/F# cross-language solutions anyway (Even VS is barely there).

1. It's now showing ~70 notifications each time I open the folder/solution in VS code (could be acceptable even if very annoying, one notification for the solution would be largely enough)
    ![image](https://user-images.githubusercontent.com/131878/43311329-6cb99fa2-918a-11e8-98fb-6a35239a7e45.png)
2. Each time I switch files to one that is in such projects or type in it It show the popup, ALWAYS. I want to review git files changed, check something fast or fix a typo faster that opening the file in VS and this is in my way
    ![image](https://user-images.githubusercontent.com/131878/43311036-91c5a972-9189-11e8-9c80-a6bdd06c5749.png)

Suggestions:
* Show startup errors as a bundle per-solution/folder/root of the FSAC loading
* Don't show an error again for a project unless the project file itself changed
* Maybe Optionally disable the popups via a setting
* Maybe reuse the "Solution" status bar indicator to be solution + Current file project and become red when the project loading failed

(Sorry for the ranty issue, being annoyed by popups 😜)

**Comment by Krzysztof-Cieslak** [comment]
`3.24.1` added `FSharp.disableFailedProjectNotifications` setting

**Comment by tonyx** [comment]
I have the same problem here. It looks like it started after I opened the project with Xamarin and updated the packages from there.

**Comment by SteveGilham** [comment]
Applying `FSharp.disableFailedProjectNotifications` and restarting VSCode has reduced, but not entirely eliminated this issue for me; there is nothing that stands out as to why two of my projects still show parse failures, yet others with similar customizations do not.

**Comment by SteveGilham** [comment]
Hmm.  Returning after a break, and checking the status (i.e. clicking the "Show status" button) of those two projects finally yielded up a success, with a remark about dependencies having been restored, which may have been the "why those two" at that precise moment in time.

**Comment by SteveGilham** [comment]
I think I've tracked down what is making this happen -- when a build is running (a FAKE script launched from a separate console) and its starts compiling the affected projects, that is the point where the `Project parsing failed:` messages arise.

As noted, this is with `FSharp.disableFailedProjectNotifications` (a flag whose existence I discovered only from this issue) already applied.

**Comment by rojepp** [comment]
What are the 'advanced concepts' that don't work? Ionide has been like this for a few months for me now, even for really simple projects.
