### ISSUE TITLE
Error messages are not removed when a file gets renamed

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#867]
Issue Type: <b>Bug</b>

## Steps to reproduce

1. Write a file like this:
``` fsharp
let x = 111 * "555"
printfn "%s" x
```

2. After you see the errors, rename the file.

3. Now you should see the errors twice.

![The file errors being shown twice](https://user-images.githubusercontent.com/12659251/43357849-5d1bc19a-9290-11e8-9fef-9b87844539e6.png)

Extension version: 3.24.2
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by MangelMaxime** [comment]
We fixed this kind of issue when deleting a file [here](https://github.com/ionide/ionide-vscode-fsharp/blob/8a0c5f1c57d110d94037f87ff42f559622548172/src/Components/Errors.fs#L158).

Perhaps renaming a file do not delete it and create a new one. However, if we use the change property we need to check that it's not trigger when changing the file content I think.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/commit/58fdaf891f13ccaf21929e975a43fd54171b76fb
