### ISSUE TITLE
Outline panel doesn't show project for a plain dotnet project

### ISSUE THREAD

**Issue by vastcloud** [ionide/ionide-vscode-fsharp#870]
### Steps to reproduce

1. Create a fresh F# dotnet core project from the command line, as with  
`dotnet new console -lang F#`.
1. Open the folder in VSCode, and notice that the outline panel shows the contents of any .fs file, but it doesn't show the project.
1. If you add a new .fs file, you need to put it in the right order manually in the .fsproj file; the ordering buttons do not appear.

The behaviour is the same with or without the Ionide Mechanic extension. 

### Machine infos

* Operating system: **Darwin**
* Arch: **x64**
* VSCode: **1.25.1**
* Runtime: **.Net**
* Mono version:
```shell
Mono JIT compiler version 5.10.1.57 (2017-12/ea8a24b1bbf Tue Apr 24 14:53:01 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```
* MSBuild version:
```shell
Microsoft (R) Build Engine version 15.6.0.0 (xplat-master/ca830585 Sun Mar 25 19:24:09 EDT 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by Krzysztof-Cieslak** [comment]
Outline viewer is showing only content of the current file.

The project explorer is under F# icon in the activity bar:
![image](https://user-images.githubusercontent.com/5427083/43546961-313f8f28-95da-11e8-91cf-4b2aa2db2ef7.png)
