### ISSUE TITLE
GetHelp fails with "Unable to open 'dev14.query': resource is not available."

### ISSUE THREAD

**Issue by cpbotha** [ionide/ionide-vscode-fsharp#871]
With Ionide-fsharp 3.25.0 and vs.code 1.25.1 on macOS 10.13.6 I get the following when invoking `F#: Get Help` (Shift-F1) on the following example code, with the cursor on Compare:

``` fsharp
open System
System.DateTime.Compare
```

Error: `Unable to open 'dev14.query': resource is not available.`

I had a quick look at the `Help.fs` source code: I can access the mentioned URL without errors, but I do get redirected.

**Comment by Krzysztof-Cieslak** [comment]
@cartermp any idea what's the correct URL for online help nowadays?

**Comment by cartermp** [comment]
From VS 15.8:

```
msdn.microsoft.com/query/dev15.query?appId=Dev15IDEF1&l=EN-US&k=k(System.DateTime.Compare);k(DevLang-FSharp)&rd=true
```
