### ISSUE TITLE
ProjectCracker missing

### ISSUE THREAD

**Issue by mkast** [ionide/ionide-vscode-fsharp#873]
Hi, since installing v3.25.0 (Windows 1803/64, VSCode 1.25.1), I'm getting an error on all the .fsproj Files:
Project parsing failed: xyz.fsproj

Status: failed to load
Error:
ProjectCracker exe not found at: C:\Users\...\.vscode\extensions\ionide.ionide-fsharp-3.25.0\bin\FSharp.Compiler.Service.ProjectCrackerTool.exe it must be next to the ProjectCracker dll.

Thanks for your work! Martin

**Comment by carmenquan** [comment]
+1 I'm seeing this too. I've manually installed 3.23.0 and have had to turn off auto upgrading for extensions in VS Code

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `3.25.1`
