### ISSUE TITLE
Improve module tooltips

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-vscode-fsharp#874]
![screen shot 2018-07-31 at 10 43 08](https://user-images.githubusercontent.com/588746/43452100-8775865e-94ae-11e8-9576-b150be8e8a13.png)
Currently only the first line is coloured and the formatting can be quite hard to read

**Comment by Krzysztof-Cieslak** [comment]
In `3.25.1` we display just the module name. I'm working on some other way of exploring modules through UI.

Current tooltip:
![image](https://user-images.githubusercontent.com/5427083/43546402-d2984f10-95d8-11e8-97ac-4fd5d4607d5e.png)

**Comment by 7sharp9** [comment]
That's nice, listing only 11 things seems daft anyway.
