### ISSUE TITLE
Hovering over an `=` and moving the mouse left/right produces enhanced tooltip requests at the server for each mouse move.

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-vscode-fsharp#875]
For normal tips there is only ever one enhanced tooltip request, probably because once it is returned the sticky tooltip window is shown which suppresses further requests on mouse move?

Perhaps tooltips that are not found _(like `=`)_ should also be cached as these all hit the server for processin./

**Comment by mvsmal** [comment]
What if we show an empty tooltip? Like this:
![empty-hover](https://user-images.githubusercontent.com/3872761/44389283-b5aca480-a52a-11e8-904d-5649d47be156.gif)

Looks like we actually have to show some tooltip to prevent `provideHover` method from executing. 
The tooltip above contains a space. With just empty string VSCode considers the tooltip as absolutely empty and doesn't show it, hence triggers `provideHover` again and again on mouse move.

PS. I used light theme just to make the tooltip more visible.

**Comment by 7sharp9** [comment]
Might as well as the tip for it rather than a space, most keywords and operators do have a textual tip: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/

**Comment by mvsmal** [comment]
According to the documentation, "equals" symbol (`=`) has this description:

> Returns `true` if the left side is equal to the right side; otherwise, returns `false`.

Might be confusing in binding statements. Furthermore, then language service should return this information, but currently it doesn't. Shall we upstream this issue?

**Comment by 7sharp9** [comment]
It looks like they skipped the definition in binding and only detailed arithmetic operations.  

Maybe it should be detailed like this, or similar:
>Returns true if the left side is equal to the right side; otherwise, returns false, Used in a let binding to associates an identifier with a value or function

**Comment by Krzysztof-Cieslak** [comment]
Fixed by FSAC update, I don't think we need any other caching. Consecutive calls to FSAC are cheap anyway, thanks to all FCS caching. We could probably theoretically cache tooltips values in FSAC to not call FCS but I don't see huge potential performance gains in this as tooltips are pretty fast anyway.

**Comment by 7sharp9** [comment]
Interestingly textual tips are cached inside FCS but not the symbol ones.
