### ISSUE TITLE
Alt+Enter without selection should invoke current line

### ISSUE THREAD

**Issue by AmadeusW** [ionide/ionide-vscode-fsharp#88]
As a new user to ionide, I was confused when `Alt + Enter` just invoked `;;` and didn't do anything - it turns out I didn't select any F# code. I would like to use `Alt + Enter` without selection to invoke current line. 

In Visual Studio, `Alt + Enter` invokes the current line and moves the caret to the next line. This means that user can just repeatedly hit `Alt + Enter` to invoke consecutive lines of the script.

Would you accept a PR if I attempted to implement this?

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.2.0`
