### ISSUE TITLE
Visual Studio Code Ionide does not detect Settings.FSharpLint file when building with dotnet core

### ISSUE THREAD

**Issue by vrobinson** [ionide/ionide-vscode-fsharp#880]
This is a very basic setup that I expect would work out-of-the box. Here's how my machine is configured:

**Configuration:**
Ionide-fsharp: 3.25.0

Visual Studio Code configuration (from about dialog):
Version: 1.25.1
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Windows 10
dotnet --version
> 2.1.103

And here's the entire project. It is an extremely basic F# console app by running:
> dotnet new console -lang F#

**LintTest.fsproj:**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```
I edited the default Program.fs slightly to introduce an underscore linting problem.

**Program.fs**
```fsharp
open System

[<EntryPoint>]
let main argv =
    let hello_world = "Hello world"
    printfn "%s from F#!" hello_world
    0 // return an integer exit code
```

Next I created a Settings.FSharpLint file and placed it alongside LintTest.fsproj and Program.fs.

I've tried a variety of content options in that file to change the settings and get rid of the underscore linting errors without success including:
- One like: https://github.com/Eoksni/ionide-lint-test/blob/master/Settings.FSharpLint
- One like: https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Core/DefaultConfiguration.FSharpLint#L142-L237 with the settings changed to AllowAny underscores
- One where I created invalid xml to see if I could get a different error
- And various other toying with the content

I closed and reopened Visual Studio Code each time to ensure settings were freshly loaded each time. None had any effect in removing the underscore linting error.

I would expect linting to work with such a simple out-of-the-box configuration. How can I customize the linting settings given this configuration?

**Comment by Krzysztof-Cieslak** [comment]
Seems to be working fine on Ionide 5.0 

![image](https://user-images.githubusercontent.com/5427083/102905091-f0180a80-4472-11eb-8bc0-c119720f6a56.png)
