### ISSUE TITLE
XML comments not formatted anymore

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#885]
## Description

I am currently on a Windows machine, but I have the same problem with latest VS Code + latest Iionide on macOS.

Previously this code would have nicely formatted my comments:

```fsharp
module Say =
    /// ** Description **
    /// This is a test description
    /// ** Parameters **
    ///     - name: The name to say hello to.
    /// ** Output **
    /// Prints "Hello {name}" into the console.
    let hello name =
        printfn "Hello %s" name
```

but now it doesn't line break between `**Description**` and the new line and it also doesn't format it in bold anymore when I `**` something.

This certainly worked before, because initially I didn't have such XML comments and only after seeing them in a different F# repository and seeing how they created nice tooltips I started to adopt the same style to all my code.

## Current result:

![image](https://user-images.githubusercontent.com/4580714/44259158-a7981480-a208-11e8-98c2-c35a4b4dd5c3.png)

## Steps to reproduce:

1. Download latest VS Code
2. Download latest Ionide
3. `dotnet new classlib -lang F#`
4. Copy the code from above

**Comment by MangelMaxime** [comment]
An easy way to see if the markdown formatting is correctly is that the comment becomes highlighted:

![image](https://user-images.githubusercontent.com/4760796/44285586-31c29600-a266-11e8-87de-835ce76ebf1b.png)

**Comment by dustinmoris** [comment]
Ok I agree that the markdown in my example isn't correct, but this worked before, which is annoying, because now I have to go through dozens of files and correct everything.

Also `test` doesn't get formatted anymore which it did beforehand. Now it just prints the "`" without formatting it as code.

**Comment by dustinmoris** [comment]
Here's what I mean:

Notice how `role` is not formatted, but `HttpHandler` is:

![image](https://user-images.githubusercontent.com/4580714/44297439-513eda80-a2c9-11e8-8e84-29c0345588af.png)

When I remove the line break then it formats it in the editor:

![image](https://user-images.githubusercontent.com/4580714/44297450-8ba87780-a2c9-11e8-84db-fb0ddc1d85c4.png)


But still not formatted in the actual tooltip.

I feel like this is definitely buggy and I don't want to change all my XML docs now and later after this has been fixed find out that I have to change them all again.

**Comment by dustinmoris** [comment]
And here's another bug:

When I remove the indentation of the list:

![image](https://user-images.githubusercontent.com/4580714/44297476-feb1ee00-a2c9-11e8-97ca-73f61a378007.png)


Then it formats the `role` and `authFailedHandler` as code blocks now, but it also indents everything afterwards, which is wrong again:

![image](https://user-images.githubusercontent.com/4580714/44297491-4d5f8800-a2ca-11e8-9eec-8e83dd5da18a.png)

**Comment by dustinmoris** [comment]
Sorry for spamming here, but I get it to work if I remove all the whitespace after the ///, however I really hate to remove the whitespace, because it just gets a lot more unreadable and I think it is sort of against general coding conventions to not have a space between // or /// and the actual text.

**Comment by dustinmoris** [comment]
In summary, if I format the markdown correctly then it works as long as there is no whitespace between /// and the content. I think this should be fixed and then it might be all good again. It's a bit annoying that I have to change it all, but I guess it was a mistake that it formatted wrong markdown before and I should have not just mindlessly copied the XML style from somewhere I saw it being done this way.

**Comment by dustinmoris** [comment]
Also, is there a way to change the colouring of the comments?

Currently it shows me the bold text in blue and my code blocks as a string content:
![image](https://user-images.githubusercontent.com/4580714/44297599-26a25100-a2cc-11e8-971f-8b570544e423.png)

I would like to change that in the settings somehow without affecting the formatting of my actual fsharp code, because the highlighted comment text sort of messes with my eyes. I quite like that comments are a bit darker and greyed out and not super highlighted and shiny, since that let's me quickly distinguish between actual code and comments when scrolling through a file.

**Comment by MangelMaxime** [comment]
Ok, I have a fix ready. 

We prepare the different PRs.

**Comment by MangelMaxime** [comment]
With the fix, in theory any valid Markdown should works now.
