### ISSUE TITLE
How to use FSI included in .Net Core?

### ISSUE THREAD

**Issue by boyedarat** [ionide/ionide-vscode-fsharp#889]
The latest release of .Net Core (2.1.400) finally includes a working FSI:
```
dotnet "C:\Program Files\dotnet\sdk\2.1.400\FSharp\fsi.exe"

Microsoft (R) F# Interactive version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>
```

How do I set it in `FSharp.fsiFilePath`?

TIA

**Comment by cartermp** [comment]
.NET SDK 2.1.400 does not include a working FSI - you'll find soon that anything beyond trivial code execution will fail, such as using an API from an assembly. It's an artifact of the build of the F# compiler SDK for .NET Core. When F# Interactive works properly for .NET Core, we'll make an announcement and have commands such as `dotnet fsi` available.

**Comment by Krzysztof-Cieslak** [comment]
As such there won’t be any effort to integrate it with Ionide in its current shape - we will wait for any true public preview / beta / release candidate.

**Comment by abk-x** [comment]
@boyedarat if you are adventurous, create a /usr/bin/fsharpi file that is on your PATH, (remember to chmod +x it) that contains:
  
    dotnet ~/.dotnet/sdk/`dotnet --version`/FSharpi/fsi.exe

**Comment by dariens** [comment]
To extend @abk-x 's comment for windows:

1. create a .cmd file that that contains:
    dotnet "{path to fsi.exe within dotnet-sdk }"
    #### Example fsi.cmd file : 
             dotnet "C:\Users\darien.shannon\scoop\apps\dotnet-sdk\2.1.403\sdk\2.1.403\FSharp\fsi.exe"
             
2. In VS Code settings, set the 'Fsi File Path' to reference this .cmd file:
    #### Example custom user setting in VS Code :
        "FSharp.fsiFilePath": "C:\\Users\\darien.shannon\\scoop\\apps\\dotnet-sdk\\2.1.403\\sdk\\2.1.403\\FSharp\\fsharpi\\fsi.cmd"

For me this looked like:

**Comment by lydell** [comment]
`dotnet fsi` is a thing these days. I put this in `/usr/local/bin/fsharpi` on my mac:

```
#!/usr/bin/env bash
dotnet fsi
```
