### ISSUE TITLE
Ionide defaults to 32bit FSI now?

### ISSUE THREAD

**Issue by nhirschey** [ionide/ionide-vscode-fsharp#893]
Did the fix for new paths change FSI defaults? Perhaps [this](https://github.com/ionide/ionide-vscode-fsharp/commit/754b7e290c1de484b7132c0bbdc268f1084b4440)?

I tried setting the fsi path to  `"FSharp.fsiFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsianycpu.exe"`. Unfortunately, then fsi will not launch.

Using Windows 10, VSCode 1.26.1, ionide 3.25.3

**Comment by baronfel** [comment]
Yes you're right the introduced changes broke this. I'll submit a PR reproducing the old behavior soon.

**Comment by ricardozimmer** [comment]
I'm experiencing the same behavior, can't run FSI from shortcuts or FSI:Start. File path is .

**Comment by ricardozimmer** [comment]
Sorry, file path is "FSharp.fsiFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsi.exe",
### Machine infos

* Operating system: **Windows_NT**
* Arch: **x64**
* VSCode: **1.26.1**
* MSBuild version:
```shell
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Framework
Ionide 3.25.3

**Comment by nhirschey** [comment]
@ricardozimmer  if you delete your custom FSharp.fsiFilePath, it will probably work except in 32bit mode. If that suffices (it doesn't for me).

**Comment by ricardozimmer** [comment]
@nhirschey Tks for the tip, just tried, no luck. Thanks again.

**Comment by baronfel** [comment]
Alternatively, you should be able to point `FSharp.fsiFilePath` to the parent directory of `fsianycpu.exe` and get the 64-bit version, at least until the linked PR gets merged.

**Comment by ricardozimmer** [comment]
Suggestion from @baronfel worked. Up and running now.

**Comment by nhirschey** [comment]
Ah, thanks @baronfel , that did work. I had been trying to point the path variable to the executable, not the executable parent directory. Thanks for the tip and for working on the PR!
