### ISSUE TITLE
Paket Integration 

### ISSUE THREAD

**Issue by leolorenzoluis** [ionide/ionide-vscode-fsharp#90]
Using the latest version, when I do `Paket: Add NuGet Package` and type in `FAKE` or any other packages, it doesn't return any results and always shows `No matches found`.

![meh](https://cloud.githubusercontent.com/assets/15150044/16737926/8e60f486-4761-11e6-81a8-0a9d2e992f68.png)

**Comment by Krzysztof-Cieslak** [comment]
You need to install `Ionide-FAKE` and `Ionide-Paket` plugins.

**Comment by leolorenzoluis** [comment]
I have them installed. It looks like it's able to find packages if it was built from Visual Studio then add one reference using Paket and load it in atom. However, using the scaffold tools to create an empty F# project, it doesn't find any.
