### ISSUE TITLE
13.25.3 breaks FSharp.Data.Npgsql type provider

### ISSUE THREAD

**Issue by daz10000** [ionide/ionide-vscode-fsharp#900]
A recent ionide update has broken intellisense inside ionide for this type provider (confirmed on Mac and PC platforms).   Reverting to 13.25.1 resolves the issue.   The simplest project below causes the Npgsql type provider to give an error about a missing dll.  

```The type provider 'FSharp.Data.Npgsql.NpgsqlProviders' reported an error: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.  ```

The database credentials don't need to be real to trigger the problem.  [ Minimal project to reproduce in this repo](https://github.com/daz10000/ionide_npgsql_tp_bug).  Am testing with dotnet skd 2.1.400 and Visual studio 15.8 installed.  The project has the magic workaround to allow it to compile under dotnet with other compilers at design time.    The project compiles correctly and intellisense works on Visual Studio and Rider.  I'm guessing there is something specific in this particular type provider that is interacting poorly with Ionide,  (@dmitry-a-morozov has been looking at it),  but the other IDEs don't seem to be affected.    We have seen this on 4 different machines (2 PCs, 2 Macs).  The only fix was reverting to older version of Ionide.

```open FSharp.Data.Npgsql

type Db = NpgsqlConnection<"Host=localhost;Username=foo;Password=bar;Database=mydb">

[<EntryPoint>]
let main argv =
    0

 ````

**Comment by baronfel** [comment]
I need to check, but it's possible that we could be adding wrong references/compiler flags (like --no-framework) in a project context instead of just in a script context

**Comment by daz10000** [comment]
Of course.  It was working since I downgraded to 13.25.1, so I have added that trace (still gets error because database credentials are fake but otherwise working fine).  When I upgrade ionide, the other trace for the new version 13.25.1 gets the dll not found error.

[.ionide_npgsql_broken.txt](https://github.com/ionide/ionide-vscode-fsharp/files/2320973/default.ionide_npgsql_broken.txt)
[ionide_npgsql_working.txt](https://github.com/ionide/ionide-vscode-fsharp/files/2320974/ionide_npgsql_working.txt)

**Comment by Dzoukr** [comment]
The same here for different type provider having problem on .NET core (in `add_AssemblyResolve` method):

    System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, 
    Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies 
    should not be loaded for execution. They can only be loaded in the Reflection-only loader context.

I just tried to downgrade to 3.25.1 and it works again. I don't know if it helps but by desperate investigation we found that different dlls are loaded in edit time and during build. The same as in @daz10000 log files - see in `broken.txt` there are dlls from `.nuget\packages\microsoft.netcore.app\2.1.0\ref\` folder. The rest is the same - compiles ok, works in Raider, VS. I wish I could help more, but don't have a clue what could cause this.

**Comment by Krzysztof-Cieslak** [comment]
Can you please check on the `3.25.4`?

**Comment by daz10000** [comment]
Same behavior with 3.25.4 unfortunately.

**Comment by Dzoukr** [comment]
Unfortunately the same with 3.25.4.

**3.25.1**
![image](https://user-images.githubusercontent.com/851307/44969182-3f596a80-af4c-11e8-9293-3f934dc9166e.png)

**3.25.3/4**
![image](https://user-images.githubusercontent.com/851307/44969262-b55dd180-af4c-11e8-93ac-853791459887.png)


To at least help a little bit, I created example .NET Core app on https://github.com/Dzoukr/OpenAPITypeProvider/tree/master/examples/NetCoreConsoleApp where you can check the error.

**Comment by Dzoukr** [comment]
Hi @Krzysztof-Cieslak, just checked on 3.26.0 and error is gone! Thanks a lot, Sir! Please, @daz10000, could you check on your side?

**Comment by Krzysztof-Cieslak** [comment]
O_o... OK... ;-)

**Comment by daz10000** [comment]
Yes,  I can happily report that 3.26.0 fixes the error for me as well.

**Comment by daz10000** [comment]
I am fairly sure 3.29.0 recreated this problem (or something very similar).   The same test project is now reporting it can't load System.Threading.Tasks.Extensions through the type provider in ionide.  The code does work and the project works with visual studio.   I will try reverting to the previous version when I get a chance.  The only other thing I did was to switch fsac to netcore instead of net (as ionide suggested).  Will also see if that changes the outcome

![image](https://user-images.githubusercontent.com/6342645/48237957-e8be4180-e37d-11e8-8dd5-3cd1b38cb9ed.png)

**Comment by daz10000** [comment]
Ok,  did one test.  This only occurs when fsac is set to netcore and not net.  That's an easy workaround for now but not sure why this would occur.
