### ISSUE TITLE
Do not suggest to open a function

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#901]
For some reason ionide wants to open functions instead of only the namespace:

![image](https://user-images.githubusercontent.com/57396/44618466-98ebd600-a876-11e8-8891-2e7a2e49bc1d.png)

Repro:

[open.zip](https://github.com/ionide/ionide-vscode-fsharp/files/2320643/open.zip)

**Comment by Krzysztof-Cieslak** [comment]
Fixed by dc55da6df24ff2f0961f55df8cdd2d2492cdf044
