### ISSUE TITLE
Project parsing failed (failed to load - Cannot find the specified file)

### ISSUE THREAD

**Issue by UnoSD** [ionide/ionide-vscode-fsharp#903]
Hi,

- I have just downloaded VS Code 64bit binaries for Linux, latest stable version.
- Deleted `~/.vscode` and `~/.config/Code`
- I installed `Ionide-fsharp` from the extensions panel
- Created a new project `dotnet net console -lang F#`
- Open the folder containing the project and I get the following error:

```
Status: failed to load

Error:
ApplicationName='dotnet', CommandLine='msbuild /home/user/newproject/newproject.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/tmp/tmp544b8a97.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/tmp/tmp1ce80a1a.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmp6b4233f3.tmp.GetProperties.txt /nologo /verbosity:quiet', CurrentDirectory='/home/user/newproject', Native error= Cannot find the specified file
```

`dotnet` is of course in the `PATH` variable and I can open the terminal from VS Code and run that same command `dotnet msbuild ...` and it works fine.

It is also using the latest version of dotnet (just downloaded the binaries, extracted and set the PATH to that location).

Any help is appreciated.

**Comment by Krzysztof-Cieslak** [comment]
How do you start VSCode? Code must be started from the context that has access to PATH variable - for example if PATH is defined in zsh profile (or other shell profile) and you start the editor using desktop icon there may have be problems with not detecting PATH variable. It's not really something we can "fix" in Ionide - it's typical behaviour of Linux/MacOS.

**Comment by UnoSD** [comment]
@Krzysztof-Cieslak I start it from the terminal (same terminal that has the dotnet folder in the PATH)

**Comment by ImaginaryDevelopment** [comment]
so I tried https://github.com/ionide/ionide-vscode-fsharp/issues/748 recommendation to install VS Build Tool 2013. now:

> [09:05:50 INFO ] listening notification on /notify started
> [09:05:50 INFO ] listening notification on /notifyWorkspace started
> [09:05:50 INFO ] listening notification on /notifyAnalyzer started
> [09:05:50 DEBUG] REQ (001) -> {workspacePeek}
> Data={"Directory":"c:\\projects\\FsInteractive\\CodeGeneration","Deep":2,"ExcludedDirs":[".git","paket-files",".fable"]}
> [09:05:51 DEBUG] RES (001) <- {workspacePeek} in 350 ms: Kind={"workspacePeek"}
> Data={"Found":[{"Type":"directory","Data":{"Directory":"c:\\projects\\FsInteractive\\CodeGeneration","Fsprojs":["c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"]}}]}
> [09:05:51 DEBUG] REQ (002) -> {workspaceLoad}
> Data={"Files":["c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"]}
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"workspaceLoad","Data":{"Status":"started"}}'
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"projectLoading","Data":{"Project":"c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"}}'
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"error","Data":{"Code":101,"Message":"Could not load project c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj in ProjectCollection. Available tools: [\"C:\\Program Files (x86)\\MSBuild\\12.0\\bin\\amd64\";\n \"C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\amd64\";\n \"C:\\Windows\\Microsoft.NET\\Framework64\\v2.0.50727\";\n \"C:\\Windows\\Microsoft.NET\\Framework64\\v3.5\";\n \"C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\"]. Message: The value \"\" of the \"Project\" attribute in element <Import> is invalid. Parameter \"path\" cannot have zero length. StackTrace:    at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.projectInstanceFromFullPath@76(FSharpList`1 properties, ProjectCollection engine, String fsprojFullPath)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.CrackProjectUsingNewBuildAPI[a](String fsprojFile, FSharpList`1 properties, FSharpOption`1 logOpt)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.FSharpProjectFileInfo..ctor(String fsprojFileName, FSharpOption`1 properties, FSharpOption`1 enableLogging)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions@396(Boolean enableLogging, FSharpList`1 properties, Dictionary`2 cache, String file)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions(String file, Boolean enableLogging, FSharpList`1 properties)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.crackOpen(String[] argv)","AdditionalData":{"Project":"c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"}}}'
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"workspaceLoad","Data":{"Status":"finished"}}'
> [09:05:51 DEBUG] RES (002) <- {workspaceLoad} in 612 ms: Kind={"workspaceLoad"}
> Data={"Status":"finished"}
> 

Here's My `<Project>` tag:

`<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

**Comment by ImaginaryDevelopment** [comment]
The entire source of the project I'm trying to open is available at https://github.com/ImaginaryDevelopment/FsInteractive

**Comment by Krzysztof-Cieslak** [comment]
CC: @enricosada

**Comment by Krzysztof-Cieslak** [comment]
This is probably outdated due to Ionide 4.0 changes
