### ISSUE TITLE
weird char sequence in F# interactive

### ISSUE THREAD

**Issue by andrzejsliwa** [ionide/ionide-vscode-fsharp#904]
When I'm starting F# interactive in vscode:   
<img width="1439" alt="screen shot 2018-08-27 at 13 30 42" src="https://user-images.githubusercontent.com/9280/44657611-b6977780-a9fd-11e8-9360-36d94d19c0ec.png">

its happen for me always on **Macosx**, with recent version of plugins and vscode:
1. First I see Welcome message from F# Interactive for a second
2. Then cursor is moved on top of Welcome message
3. Then silentCD, and file loading commands are injected (overwriting Welcome message)
4. Then **;7;3R** appearing
5. Then sending any line/selection is resulting with fail (because of **;7;3R** and text under cursor)

on Windows everything is **ok**:
<img width="1190" alt="screen shot 2018-08-27 at 14 03 40" src="https://user-images.githubusercontent.com/9280/44658782-37587280-aa02-11e8-80d3-d09ead40f131.png">

**Comment by Krzysztof-Cieslak** [comment]
I can't repro issue on my MacOS. CC: @baronfel Could you test it please? 

<img width="821" alt="screen shot 2018-09-02 at 20 31 28" src="https://user-images.githubusercontent.com/5427083/44959483-38e8d580-aeef-11e8-850e-87dee1397ea9.png">

**Comment by andrzejsliwa** [comment]
Ok, I found that issue somehow is related to shell. It's happening when you have zsh configured as your shell.
After switching back to bash, interactive working good, after switching back to zsh (chsh -s /usr/local/bin/zsh), then problem back again.

**Comment by andrzejsliwa** [comment]
here you have some example how to setup zsh to be able reproduce it: https://rick.cogley.info/post/use-homebrew-zsh-instead-of-the-osx-default/

**Comment by Krzysztof-Cieslak** [comment]
I'm using zsh as my shell.

**Comment by baronfel** [comment]
I can only repro consistently when I open the terminal using `FSI: Start` repeatedly.

The first time it will work fine, but subsequent invocations start with
```
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.
For help type #help;;
>
```
as expected, but then the `- # silentCd @"/Users/chethusk/work/server/tests/BDS.Vision.Assets.Tests";;` line appears above the top line, followed by the 
```
- # 1 @"/Users/chethusk/work/server/tests/BDS.Vision.Assets.Tests/Tests.fs"
- ;;right (c) Microsoft Corporation. All Rights Reserved.
> ;7;3R
``` 
lines. You can see it overwriting the text. Once it happens a single time it consistently behaves like this.

**Comment by andrzejsliwa** [comment]
@Krzysztof-Cieslak we can reproduce it and fix it together on my laptop if you can assist

**Comment by halcwb** [comment]
This is something that is happening on my macbook pro for months (maybe over a year) using VSCode. I use bash as the terminal. I would be very, very happy if this problem could get solved.

**Comment by schauerte** [comment]
I have the exact same problem on Linux (Ubuntu 18.04). I've managed to ignore this error for a while (not sure, when it started), but I also observe larger parts seems to get distorted when executing interactively leading to many strange error messages. I'm quite not sure, is this is related.

**Comment by Krzysztof-Cieslak** [comment]
@Tyriar, any suggestions?

**Comment by Tyriar** [comment]
Probably another case of https://github.com/Microsoft/vscode/issues/45693

**Comment by Krzysztof-Cieslak** [comment]
@Tyriar, looks like above reports are about OSX and Linux while the issue you've linked is about Windows.

**Comment by Tyriar** [comment]
@Krzysztof-Cieslak oh, I missed that. @andrzejsliwa can you run this command:

![image](https://user-images.githubusercontent.com/2193314/47037525-022fed00-d134-11e8-925f-2e158f28232e.png)

Then repro the bug and check the devtools console for the output around the troublesome output. This will print exactly what is being sent over from the shell (F#).
