### ISSUE TITLE
Parameter list is empty

### ISSUE THREAD

**Issue by ronaldschlenker** [ionide/ionide-vscode-fsharp#908]
### Problem

Invoking methods of non-BCL types in an fsx script causes a completely empty parameter list to come up,
even if the invoked method has (uncurried) parameters (ccreenshot 1).
Doing so for BCL methods, the parameter list is populated correctly.
Hovering above the method name shows a popup with all parameters populated correctly (screenshot 2).

### Steps to reproduce

Create an FSX file and paste this code:

```fsharp
#r @".\packages\Docker.DotNet\lib\net46\Docker.DotNet.dll"
#r @".\packages\System.Buffers\lib\netstandard2.0\System.Buffers.dll"

open System
open Docker.DotNet

let client = (new DockerClientConfiguration(new Uri("http://localhost:2376"))).CreateClient()

// Parameter list of 'ListContainersAsync' remains empty when pressing "Shift+Ctrl+Space"
client.Containers.ListContainersAsync()
```

**Screenshot 1**
![screenshot1](https://user-images.githubusercontent.com/472222/44844410-2189be00-ac4b-11e8-99b6-bf1e810e597f.png)

**Screenshot 2**
![screenshot2](https://user-images.githubusercontent.com/472222/44844461-4bdb7b80-ac4b-11e8-866f-30656c9218f1.png)

### Machine infos

* Operating system: **Windows_NT**
* Arch: **x64**
* VSCode: **1.26.1**
* MSBuild version:
```shell
Microsoft (R)-Build-Engine, Version 15.8.168+ga8fba1ebd7 f�r .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
```

**Comment by Krzysztof-Cieslak** [comment]
I think it's fixed by #909
