### ISSUE TITLE
Invalid signatures in tooltips

### ISSUE THREAD

**Issue by matthid** [ionide/ionide-vscode-fsharp#912]
![image](https://user-images.githubusercontent.com/1866463/44987244-d511eb80-af86-11e8-802d-72617eadb4a1.png)

I would assume this is an issue in visualfsharp but just to be sure I first wanted to report this here.
The problem disappears when renaming the "exception" parameter to something else. In fact the signature was just copied from the `ILogger` tooltip.

**Comment by Krzysztof-Cieslak** [comment]
For the errors we just feed editor with the errors provided by FCS, we have no impact on it.

**Comment by inosik** [comment]
Should we add the `exception` keyword to the grammar?

**Comment by Krzysztof-Cieslak** [comment]
Yeah... I probably don’t add double backticks in the tooltips at all, I bet it’s broken for other cases too, not only exception keyword. The bug is in the signature or tooltip formatted in FSAC if anyone would want to work on it

**Comment by 7sharp9** [comment]
So ```if paramName isKeyword then sprintf "`%s`" paramName else paramName```

**Comment by Krzysztof-Cieslak** [comment]
@7sharp9 it's probably not just keywords but also other doubleticked things are wrong. But yes, it's simple bug to fix ;-)

**Comment by 7sharp9** [comment]
Actually, I think there a function in the compiler to get back a mangled name etc

**Comment by Krzysztof-Cieslak** [comment]
`PrettyNaming.QuoteIdentifierIfNeeded`

**Comment by 7sharp9** [comment]
@Krzysztof-Cieslak Can you assign this for me to do?

**Comment by 7sharp9** [comment]
![Screenshot 2019-09-18 at 16 27 49](https://user-images.githubusercontent.com/588746/65162540-51ac2680-da31-11e9-8ecf-f38ea2e63570.png)

first part patched

**Comment by 7sharp9** [comment]
This is now fixed.
