### ISSUE TITLE
Should we prevent Ionide to load files under .fable folder

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#913]
I am opening this here because I don't think there is a benefit to parsing/loading these projects in Ionide/FSAC but I can be wrong.

cc @alfonsogarciacaro 

If we add this feature, I propose to make it configurable via a setting.

IMO it's like for projects under `paket-files`, `packages` I don't think there is a benefit to loading them but I can be wrong of course :)

**Comment by Krzysztof-Cieslak** [comment]
What’s `.fable` folder? And aren’t most people using sln files anyway? In such case Ionide loads the projects only from sln file.

**Comment by MangelMaxime** [comment]
I personally don't use `sln` I hate this file format. :)

What's the benefit of using `sln` ? 

- Help people who used VS to open our project ?
- Useful if you have several fsproj but what if you have only one ?

> What is `.fable` folder ?

Quoting @alfonsogarciacaro from another issue:

> Fable 2 is copying files from nuget packages in a local .fable folder to avoid the problem we had before that some dependencies couldn't be resolved unless users were very careful in their webpack configuration

**Comment by alfonsogarciacaro** [comment]
I think it's good to use the solution file as Ionided does now, but it'd be also good too to keep in mind repos that don't have one. Paket added the `.fable` folder as an exception (together with `node_modules`, etc) but it may be a good idea to just ignore all folders starting with `.` as that's the standard way to hide a directory in unix.

> Or maybe use the .gitignore rules (not sure how difficult this is). The `.fable` folder includes a `.gitignore` file by default.

**Comment by Krzysztof-Cieslak** [comment]
We have `FSharp.excludeProjectDirectories` which does exactly what you want, all we need is to add `.fable` to default values. PRs welcomed ;-)

**Comment by Krzysztof-Cieslak** [comment]
Thanks!

**Comment by alfonsogarciacaro** [comment]
We added ".fable" to `excludeProjectDirectories` #916 but I still get fail messages from projects in the .fable folder, any idea?

![image](https://user-images.githubusercontent.com/8275461/48625255-00fe1400-e9af-11e8-9221-fddc5ca19ef6.png)

**Comment by Krzysztof-Cieslak** [comment]
I can't reproduce that one...

**Comment by alfonsogarciacaro** [comment]
I doesn't happen all the time, it seems to be related to using Fable development version in another directory (e.g. running `dotnet run -p ../Fable/src/dotnet/Fable.Compiler`) as if that somehow widened but I don't understand why the processes should be related. I just mentioned in case it ringed a bell. Let's see if I can find the conditions to reproduce and report again.
