### ISSUE TITLE
Project parsing failed

### ISSUE THREAD

**Issue by tobia** [ionide/ionide-vscode-fsharp#919]
I'm having trouble with the projects created by the "F#: New Project" command.

I'm working in a fresh installation of VS Code, Ionide, .Net Core and the `fsharp` package on the latest Ubuntu 18. If I create a project from the terminal with `dotnet new console -lang f# -o hello` everything works. But if I create it with "F#: New Project > console" a couple of things fail.

First, Ionide fails to load the fsproj file with this error:

> Status: failed to load
>
> Error:
> MSBuild failed with exitCode 1 Working Directory: '/home/tobia/hello' Exe Path: 'dotnet' Args: 'msbuild /home/tobia/hello/hello.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/tmp/tmp193b99a6.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/tmp/tmp5c1a6ed1.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmp1ef943fd.tmp.GetProperties.txt /nologo /verbosity:quiet' Log: writing helper target file in '/home/tobia/hello/obj/hello.fsproj.proj-info.targets' /usr/share/dotnet/sdk/2.1.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(198,5): error NETSDK1005: Assets file '/home/tobia/hello/obj/project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. [/home/tobia/hello/hello.fsproj]

By the error message, I presumed it was looking for .NET 4.6.1 which I may not have (I installed .Net Core 2.1 and the other dependencies, as recommended on the website) so I tried to change this line:

    <TargetFramework>net461</TargetFramework>

to the one created by `dotnet new` which is:

    <TargetFramework>netcoreapp2.1</TargetFramework>

and now this first error message went away and the Ionide features, such as type annotations above definitions, started to appear.

But then I could not run this project. If I do `dotnet run` from a terminal, I get:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

This time I had to comment the following line in the fsproj to make it work:

    <Import Project="..\.paket\Paket.Restore.targets" />

I'm new to F# and .Net/.NetCore, so I'm sure there are many obvious things I don't understand here.

But I think that either the New Project templates are buggy / outdated, or the quick start documentation is missing some crucial step.

For now, I'm going back to running `dotnet new` and `dotnet run` in a terminal, because I'm not sure which Ionide commands replace them and how.

**Comment by tobia** [comment]
Also, selecting code and hitting Alt+Enter gives:

> The terminal process command 'fsharpi' failed to launch (exit code: 1)

I don't know if it's related.

**Comment by Krzysztof-Cieslak** [comment]
Forge (tool that we use for creating and manipulating projects) is indeed create projects targeting full framework - and it may cause some problems on non-Windows machines. TBF, at the moment I'd recommend using `dotnet new` to create projects. 

After changing the framework target to `netcoreapp2.1` you need to run `dotnet restore` (and also I'd recommend removing `obj` folder).

**Comment by Krzysztof-Cieslak** [comment]
I'm going to close the issue - I don't think it's a Ionide bug per se, but rather just a result of general problem with F# ecosystem - the movement to .Net Core and .Net SDK is still work in progress for many tools, and projects.
