### ISSUE TITLE
' always gives '' now.

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#92]
Since (I think) 1.3 of VS Code, pressing ' will now automatically give '', so you have to manually delete the second one. Is there a way to turn this off?

**Comment by Krzysztof-Cieslak** [comment]
That's good question ;)

**Comment by alfonsogarciacaro** [comment]
Seems that if you add `"editor.autoClosingBrackets": false` to the user settings this behaviour is turned off. However, it apparently affects quotations (both single and double) and brackets (squared, rounded...) at the same time, I haven't found a way to discriminate them.

**Comment by rmunn** [comment]
Relevant to this issue:

- Microsoft/vscode#8850
- Microsoft/vscode#8539

**Comment by Krzysztof-Cieslak** [comment]
I think it got recently fixed by @cloudRoutine

**Comment by isaacabraham** [comment]
Indeed. This is now fixed.
