### ISSUE TITLE
Automatic indent support. 

### ISSUE THREAD

**Issue by jnoortheen** [ionide/ionide-vscode-fsharp#921]
## Problem with Indenting
I come from Python community and just started learning F#. One thing that struck me was not able to auto-indent after specific expression/assignment. Like after module, let expression or simply after `=` . 

### Proposed Solution
Some level of auto-indenting would be great. I know it is hard to tell where an expression ends, but we can surely tell where it starts and indent any newline cursor to that. 

## Problem with Un-Indenting
I had to use backspace four time before moving to another block of code. It is definitely a part where editors can support and make indented languages better.

### Proposed Solution
It would be better I can un-indent with a single stroke of backspace. Since we do not write whitespace at the start of the line, it will be easier to differentiate within/out of expression. 

## Problem with lot of spaces
I know that there is auto-formatting available. But it will really be nice to cleanup any extra whitespaces and newlines in the file. 

Please note, I am just a noob here and expect to get the same feeling typing Python code in a Python editor.

**Comment by MangelMaxime** [comment]
> I know that there is auto-formatting available. But it will really be nice to clean up any extra whitespaces and newlines in the file.

This is something handled by VSCode, in your settings you can set:

```json
"files.trimTrailingWhitespace": true,
"files.insertFinalNewline": true,
```

This will remove any white space and make sure you have a new line at the end of the file.

**Comment by jnoortheen** [comment]
@MangelMaxime thanks for letting me know.

**Comment by eugene-g** [comment]
> I had to use backspace four time before moving to another block of code. It is definitely a part where editors can support and make indented languages better.

VSCode already supports this:
- `Tab` for indent
- `Shift + Tab` for un-indent

**Comment by MangelMaxime** [comment]
I think he wants to auto positioned the cursor when pressing `enter`.

**Comment by jnoortheen** [comment]
@MangelMaxime Yes. Auto-indent at a new block/level of code.

**Comment by inosik** [comment]
> It would be better I can un-indent with a single stroke of backspace.

> Shift + Tab for un-indent

This causes #641. I reported that at Microsoft/vscode#42041. However, I'm working around this with the [Backspace++ extension](https://marketplace.visualstudio.com/items?itemName=jrieken.backspace-plusplus). The extension makes <kbd>Backspace</kbd> behave like <kbd>Shift</kbd>+<kbd>Tab</kbd>. It isn't maintained anymore because VS Code is supposed to do the same, but it seems that it isn't the case for F#, and probably other whitespace-sensitive languages like Python.
