### ISSUE TITLE
No type signatures for dotnet new console -lang=F# after creating fake project

### ISSUE THREAD

**Issue by bratfizyk** [ionide/ionide-vscode-fsharp#922]
I can't see type signatures - just an empty row with no content.

![image](https://user-images.githubusercontent.com/10075099/45921862-5ee61200-bebe-11e8-915e-ae976aca73cd.png)

Steps to reproduce:

- mkdir test
- cd test
- dotnet new fake
- mkdir src
- cd src
- dotnet new console -lang=F#

I use Kubuntu 18.04 with the latest updates installed.
The "fake" template is the one found here:
https://fake.build/fake-gettingstarted.html

Happy to provide more info if needed. E.g. some logs, but now sure how to fine them.

**Comment by bratfizyk** [comment]
Out of interest I've checked the same behavior in Atom and it's a bit more obvious that something crashed. There's a blue-ish rectangle that covers some part of the editor:

![image](https://user-images.githubusercontent.com/10075099/45921976-1419c980-bec1-11e8-9e73-6ba0e9f46b17.png)

Again - I'm happy to provide more details. What exactly is needed ?

**Comment by vjraitila** [comment]
I experience this as well. It seems to be a race condition of sorts as I cannot reproduce it reliably. However, it seems to be easier to trigger when VS Code starts, restores a previous session and tries to process an F# file immediately. The linter and other FSAC tools fail to execute when this happens.

Here's the [log](https://github.com/ionide/ionide-vscode-fsharp/files/2430433/ionide_fsac_errors.log).

**Comment by bratfizyk** [comment]
Some update: I've managed to get it working on Kubuntu 18.04, though the plugin still dies after adding SQLProvider to my project.

The error says:
[16:21:20 ERROR] Cannot execute parse, The exception has been reported. This internal exception should now be caught at an error recovery point on the stack. Original message: One or more errors seen during provided type setup)

**Comment by Krzysztof-Cieslak** [comment]
Choose F# tab on the Activity Bar on the left - this should display solution explorer. Probably some/all projects failed to load. Right click on the project reporting an error and choose Show Project Status.
