### ISSUE TITLE
Error checking a little trigger happy during typing

### ISSUE THREAD

**Issue by daz10000** [ionide/ionide-vscode-fsharp#925]
I frequently encounter this entering code with Ionide, where the intellisense / checking occurs way too quickly, while I am typing.  This is a good example where it jumped 3 letters into my typing the word `None` and then complains very quickly that `Non` is not a valid symbol and maybe I meant `None`.  Oddly, despite being so eager to check,  it can then sit there for 5 or more minutes till it rechecks and declares things ok.   I don't what the logic is around rechecking but a minimal delay looking for a pause in typing would make sense if it isn't in there already.

![image](https://user-images.githubusercontent.com/6342645/46261733-a9622280-c4ac-11e8-8fb9-c00a74d57a3c.png)

**Comment by Krzysztof-Cieslak** [comment]
There currently exists some logic around looking for a pause in typing (delay depends on the size of the file). However, in fce263ed7398c3de75dd5905e7e0724c6ed16659 I've added option to override default delay by providing custom delay in the settings using `FSharp.customTypecheckingDelay` option.
