### ISSUE TITLE
Project parsing failed

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [ionide/ionide-vscode-fsharp#929]
I'm unable to use VSCode for F# as it always fails project parsing.

F# Language Service log:

> [08:47:07 INFO ] listening notification on /notify started
> [08:47:07 INFO ] listening notification on /notifyWorkspace started
> [08:47:07 INFO ] listening notification on /notifyAnalyzer started
> [08:47:07 DEBUG] REQ (001) -> {workspacePeek}
> Data={"Directory":"c:\\projects\\FsInteractive\\CodeGeneration","Deep":2,"ExcludedDirs":[".git","paket-files",".fable"]}
> [08:47:07 DEBUG] RES (001) <- {workspacePeek} in 327 ms: Kind={"workspacePeek"}
> Data={"Found":[{"Type":"directory","Data":{"Directory":"c:\\projects\\FsInteractive\\CodeGeneration","Fsprojs":["c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"]}}]}
> [08:47:07 DEBUG] REQ (002) -> {workspaceLoad}
> Data={"Files":["c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"]}
> [08:47:07 DEBUG] WebSocket message: '{"Kind":"workspaceLoad","Data":{"Status":"started"}}'
> [08:47:07 DEBUG] WebSocket message: '{"Kind":"projectLoading","Data":{"Project":"c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"}}'
> [08:47:08 DEBUG] WebSocket message: '{"Kind":"error","Data":{"Code":101,"Message":"Could not load file or assembly 'Microsoft.Build, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. StackTrace:    at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.FSharpProjectFileInfo..ctor(String fsprojFileName, FSharpOption`1 properties, FSharpOption`1 enableLogging)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions@396(Boolean enableLogging, FSharpList`1 properties, Dictionary`2 cache, String file)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions(String file, Boolean enableLogging, FSharpList`1 properties)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.crackOpen(String[] argv)","AdditionalData":{"Project":"c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"}}}'
> [08:47:08 DEBUG] WebSocket message: '{"Kind":"workspaceLoad","Data":{"Status":"finished"}}'
> [08:47:08 DEBUG] RES (002) <- {workspaceLoad} in 234 ms: Kind={"workspaceLoad"}
> Data={"Status":"finished"}

I tried setting `Msbuild Location` to `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe`

I have Visual Studio Build Tools 2017 installed, as well as VS 2017 15.8.6 Community.

**Comment by ImaginaryDevelopment** [comment]
```
### Machine infos

* Operating system: **Windows_NT**
* Arch: **ia32**
* VSCode: **1.27.2**
* MSBuild version:
```shell
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by ImaginaryDevelopment** [comment]
Not the same error, though same title, as https://github.com/ionide/ionide-vscode-fsharp/issues/919

**Comment by ImaginaryDevelopment** [comment]
http://ionide.io/ says to install VS Build tools 2017, which I already had. 
so I tried https://github.com/ionide/ionide-vscode-fsharp/issues/748 recommendation to install VS Build Tool 2013. now:

> [09:05:50 INFO ] listening notification on /notify started
> [09:05:50 INFO ] listening notification on /notifyWorkspace started
> [09:05:50 INFO ] listening notification on /notifyAnalyzer started
> [09:05:50 DEBUG] REQ (001) -> {workspacePeek}
> Data={"Directory":"c:\\projects\\FsInteractive\\CodeGeneration","Deep":2,"ExcludedDirs":[".git","paket-files",".fable"]}
> [09:05:51 DEBUG] RES (001) <- {workspacePeek} in 350 ms: Kind={"workspacePeek"}
> Data={"Found":[{"Type":"directory","Data":{"Directory":"c:\\projects\\FsInteractive\\CodeGeneration","Fsprojs":["c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"]}}]}
> [09:05:51 DEBUG] REQ (002) -> {workspaceLoad}
> Data={"Files":["c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"]}
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"workspaceLoad","Data":{"Status":"started"}}'
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"projectLoading","Data":{"Project":"c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"}}'
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"error","Data":{"Code":101,"Message":"Could not load project c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj in ProjectCollection. Available tools: [\"C:\\Program Files (x86)\\MSBuild\\12.0\\bin\\amd64\";\n \"C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\amd64\";\n \"C:\\Windows\\Microsoft.NET\\Framework64\\v2.0.50727\";\n \"C:\\Windows\\Microsoft.NET\\Framework64\\v3.5\";\n \"C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\"]. Message: The value \"\" of the \"Project\" attribute in element <Import> is invalid. Parameter \"path\" cannot have zero length. StackTrace:    at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.projectInstanceFromFullPath@76(FSharpList`1 properties, ProjectCollection engine, String fsprojFullPath)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.CrackProjectUsingNewBuildAPI[a](String fsprojFile, FSharpList`1 properties, FSharpOption`1 logOpt)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.FSharpProjectFileInfo..ctor(String fsprojFileName, FSharpOption`1 properties, FSharpOption`1 enableLogging)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions@396(Boolean enableLogging, FSharpList`1 properties, Dictionary`2 cache, String file)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions(String file, Boolean enableLogging, FSharpList`1 properties)\r\n   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.crackOpen(String[] argv)","AdditionalData":{"Project":"c:\\projects\\FsInteractive\\CodeGeneration\\CodeGeneration.fsproj"}}}'
> [09:05:51 DEBUG] WebSocket message: '{"Kind":"workspaceLoad","Data":{"Status":"finished"}}'
> [09:05:51 DEBUG] RES (002) <- {workspaceLoad} in 612 ms: Kind={"workspaceLoad"}
> Data={"Status":"finished"}
> 

Here's My `<Project>` tag:

`<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

The entire source of the project I'm trying to open is available at https://github.com/ImaginaryDevelopment/FsInteractive

**Comment by Krzysztof-Cieslak** [comment]
Choose F# tab on the Activity Bar on the left - this should display solution explorer. Probably some/all projects failed to load. Right click on the project reporting an error and choose `Show Project Status`.

**Comment by ImaginaryDevelopment** [comment]
result of that selection:

```
Status: failed to load

Error:
Could not load project c:\projects\FsInteractive\CodeGeneration\CodeGeneration.fsproj in ProjectCollection. Available tools: ["C:\Program Files (x86)\MSBuild\12.0\bin\amd64"; "C:\Program Files (x86)\MSBuild\14.0\bin\amd64"; "C:\Windows\Microsoft.NET\Framework64\v2.0.50727"; "C:\Windows\Microsoft.NET\Framework64\v3.5"; "C:\Windows\Microsoft.NET\Framework64\v4.0.30319"]. Message: The value "" of the "Project" attribute in element is invalid. Parameter "path" cannot have zero length. StackTrace: at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.projectInstanceFromFullPath@76(FSharpList`1 properties, ProjectCollection engine, String fsprojFullPath) at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.CrackProjectUsingNewBuildAPI[a](String fsprojFile, FSharpList`1 properties, FSharpOption`1 logOpt) at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.FSharpProjectFileInfo..ctor(String fsprojFileName, FSharpOption`1 properties, FSharpOption`1 enableLogging) at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions@396(Boolean enableLogging, FSharpList`1 properties, Dictionary`2 cache, String file) at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions(String file, Boolean enableLogging, FSharpList`1 properties) at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.crackOpen(String[] argv)
```

**Comment by skalinets** [comment]
I have the same issue, it says that file does not exist, but it does exist :)
