### ISSUE TITLE
"with" keyword is replaced with failwith

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#93]
if you have a match expression, typing ``with`` will prompt Code to replace it with ``failwith``.

![ionide](https://cloud.githubusercontent.com/assets/1781813/16798096/b7553da4-48ea-11e6-9a7c-3e417ce719fd.png)

When you press enter after typing ``with``, this is exactly what happens and you're left with incorrect F#.

**Comment by Krzysztof-Cieslak** [comment]
Getting https://github.com/ionide/ionide-vscode-fsharp/issues/58 fixed should resolve that. Closing this one.
