### ISSUE TITLE
Can't write opening curly brace while ionide is enabled

### ISSUE THREAD

**Issue by Hugibeer** [ionide/ionide-vscode-fsharp#930]
**Problem**
When I try to write opening curly brace '{', it isn't recognized by editor

**Steps to reproduce**
I created F# project using dotnet new. When trying to write opening curly brace, it doesn't get recognized.
I am new to F# and following F# tutorial, and I tried to add type definition 
```fsharp
type IntAndBool = { x: int; y: bool }
```
but on pressing curly brace, no input was registered.

**Machine infos**
Operating system: Windows 10
Arch: x64
VSCode: 1.28.0 (both user and system wide)
Runtime: netcore
Dotnet version: 2.1.104

**Comment by Krzysztof-Cieslak** [comment]
In principle VSCode extensions have no way to impact editor/typing experience in VSCode.

Please make sure that the combination of keys that is used for typing `{` is not assigned to any command as keyboard shortcut. You can check current keyboard shortcuts in `File |> Preferences |> Keyboard Shortcuts` menu.

**Comment by Hugibeer** [comment]
Oh my God. I am using ISO 104 keyboard, Croationa, where opening brace is {. I didn't realize that VS code the combination of letters AltGR + b, registers as ctrl+shift+b, which invokes build of current project.

Thank you and sorry for posting nonexistent issue
