### ISSUE TITLE
No documentation for keyword autocomplition

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#933]
There exists documentation for the keywords (displayed in the tooltips) but it's not displayed for the autocomplete. `helptext` request reports error when it tries to resolve keyword documentation.

**Comment by lsmullenbrock** [comment]
I'm neither getting tooltips nor autocomplete, just happened overnight - where do I look for logging info?

**Comment by Krzysztof-Cieslak** [comment]
Fixed by https://github.com/fsharp/FsAutoComplete/commit/a6fdf54743f6793daba00a3016665fcb88292fdb
