### ISSUE TITLE
"-1 References"

### ISSUE THREAD

**Issue by samuela** [ionide/ionide-vscode-fsharp#934]
I renamed a few things, built, and now I'm seeing negative reference counts reported.

<img width="1440" alt="screen shot 2018-10-12 at 12 42 39 pm" src="https://user-images.githubusercontent.com/226872/46890702-7b6dce00-ce1c-11e8-861d-543c30f9d92d.png">

**Comment by Krzysztof-Cieslak** [comment]
Thanks for report, happy to see that someone is actually using this feature!

Is the problem persistent, or it just goes away after you edit a file bit more? It probably has something to do with not updating symbol cache fast enough.

**Comment by samuela** [comment]
@Krzysztof-Cieslak Eventually it went away, probably after I rebuilt or something.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by 
https://github.com/ionide/ionide-vscode-fsharp/commit/7cc33d34e6e7e91954e9b5c8560bb5a68b4e7131
