### ISSUE TITLE
Compiler directives in FsLexYacc generated files cause errors

### ISSUE THREAD

**Issue by JonathanMEdwards** [ionide/ionide-vscode-fsharp#935]
```
let newline (lexbuf: LexBuffer<_>) =
  lexbuf.StartPos <- lexbuf.StartPos.NextLine


# 13 "Lexer.fs"
let trans : uint16[] array =
```
Has a squiggly above the # with the error:
Unexpected keyword 'let' or 'use' in binding. Expected incomplete structured construct at or before this point or other token.

```
                 : 'File));
# 107 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
```
Possible incorrect indentation: this token is offside of context started at position (106:19). Try indenting this token further or using standard formatting conventions.

The FSAC log is full of of these errors:
[16:59:29 DEBUG] WebSocket message: '{"Kind":"errors","Data":{"File":"/Users/edwards/Projects/subtext/src/LexAndYaccMiniProject/obj/Debug/netcoreapp2.1/LexAndYaccMiniProject.AssemblyInfo.fs","Errors":[]}}'

### Machine infos

* Operating system: **Darwin**
* Arch: **x64**
* VSCode: **1.28.1**
* Runtime: **netcore**
* Dotnet version: **2.1.403**
* Runtime: **.Net**
* Mono version:
```shell
Mono JIT compiler version 5.12.0.309 (2018-02/39d89a335c8 Thu Sep 27 06:54:53 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-release_60/8b1520c8aae)
	GC:            sgen (concurrent by default)
```
* MSBuild version:
```shell
Microsoft (R) Build Engine version 15.7.224.30163 (xplat-master/d375bb6e Thu Sep 27 07:16:13 EDT 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by Krzysztof-Cieslak** [comment]
@dsyme, isn't it an issue in FCS? Is there anything special we should do support such files?

**Comment by Krzysztof-Cieslak** [comment]
This seems no longer be happening:

![image](https://user-images.githubusercontent.com/5427083/102925856-6e38d900-4494-11eb-98ac-c03c5ac59d50.png)
