### ISSUE TITLE
Building in VSCode shows duplicate errors

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#944]
If you start a build using the built-in build support in VS Code (`ctrl + shift + b` etc.) and there are build errors thrown by FSC, they are shown in addition to the errors that Ionide figures out itself (I guess from FSAC / FS compiler service?):

![image](https://user-images.githubusercontent.com/1781813/47204255-2df4e200-d383-11e8-8bdb-d595b665ba74.png)

Note the first two errors - one is raised by kicking off a build whilst the other is generated by Ionide itself (I believe). They aren't identical, since one has the line details and error code. Double-clicking the first one takes you to the start of the line that the error is on; double clicking the second actually selects the text that is in error (red squigglies).

This also complicates matters in the text editor itself as the error is shown twice in tooltips:

![image](https://user-images.githubusercontent.com/1781813/47204494-bbd0cd00-d383-11e8-84d5-0bc53d19b200.png)

As you can see, the first one doesn't respect line returns either.

**Comment by Krzysztof-Cieslak** [comment]
This probably happens because you're using some problem matcher in your `tasks.json` build definition.

**Comment by isaacabraham** [comment]
Exactly right, turning that off fixed it - thanks. I wonder if there's any way to prevent this happening? I imagine that this could confuse other people as well.

**Comment by Krzysztof-Cieslak** [comment]
I don't think we can do anything smart (other than just reading tasks.json and checking if someone has set the problem matcher).

TBF, I don't really care too much about `tasks.json` - what I want is to provide good UX for starting building / debugging using commands/solution explorer as that's the idiomatic behavior in F# (.Net) ecosystem. From the experience of helping people before we had those commands - expecting .Net developers to create and configure `tasks.json` and `launch.json` is probably bad idea

**Comment by MangelMaxime** [comment]
Some extension propose to generate the `tasks.json` for you with a default configuration.

I am proposing that if we need to set something in the `tasks.json` and can't do the build/debug with commands only.

**Comment by isaacabraham** [comment]
My preference would be to do that rather than go outside the box. That way, standard vscode build would just work rather than having some alternative "F# build".
