### ISSUE TITLE
Failed to start language services... in non fsharp folder

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-vscode-fsharp#946]
Just experienced this error message if open a folder with no .net files - just docker-compose.yml, *.md and *.env
>Failed to start language services. Please check if Microsoft Build Tools 2013 are installed
> Source: Ionide-fsharp (Extension)

That says me the fsac starts for the foldere where it's not useful.
Shouldn't ionide first look for at least one F# file or alike?

windows 10
ionide 3.28
dotnet cli 2.1.403
fsac settings: runtime `netcore`, workspace load `workspaceLoad`

also https://github.com/ionide/ionide-vscode-fsharp/issues/939#issuecomment-430572591

**Comment by Krzysztof-Cieslak** [comment]
Ionide, as every VSCode extension is defining set of "activation events" - https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L1419-L1430

This hasn't changed probably since beginning of the extension, and I can't reproduce the issue.

**Comment by vilinski** [comment]
Now I can't reproduce it too, sorry.
Even tried to open fsharp folder in one window and docker in other.
May be some VSCode cache or alike.
Closing
