### ISSUE TITLE
Race condition in project system

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#947]
Sometimes all projects are stuck in the "not yet loaded" status. Solved by the reloading the window

**Comment by Krzysztof-Cieslak** [comment]
Fixed by 58c14ebcd0ff02256aa67aa4a75b0d1c4f59ae65

**Comment by vbfox** [comment]
I don't understand the fix

* It look like it would break `clearLoadedProjects` as the `emptyProjectsMap` dictionary isn't empty once mutated
* It doesn't look like it would change anything, javascript being single threaded the code before/after should be equivalent

**Comment by Krzysztof-Cieslak** [comment]
It's been a while since I done this change... but as far as I remember there were some impactful differences in JS code.  /shrug
