### ISSUE TITLE
Signature for functions is showing as blank lines...

### ISSUE THREAD

**Issue by janpop2017** [ionide/ionide-vscode-fsharp#950]
In version 3.29.0, the signature for functions do not show, but there is a blank line without a line number.
Another issue is that there appear a blank line above ALL 'let'  expressions:
let a = 1
let b = 2
let c = 3

**Comment by blainne** [comment]
I see the same issue (Ionide 3.29).
I also tried to enable LineLens (set the "FSharp.lineLens.enabled": "always") but they do not show up either (not even the "//" prefix).

**Comment by blainne** [comment]
Ok, I found what was causing this in my case. I have moved the F# code to new laptop and never built it. The project is .NET core so running `dotnet run` on the project immediately effected in showing the CodeLens signatures.

**Comment by janpop2017** [comment]
Blainne,thank you. Your last comment made me check every setup related to dotnet and/or net.
The Fsac Runtime flag has the value 'netcore'. Changing it to 'net' solved the problem.

**Comment by vbfox** [comment]
@janpop2017 I think an issue should be created so that the notification contains [Fix it] & [Never notify again] buttons.
