### ISSUE TITLE
Create IONIDE_DESIGN_TIME_BUILD env variable

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#951]
@forki: Another cool thing would be if ionide would pass an IONIDE_DESIGN_TIME_BUILD env variable down to MSBuild

@Krzysztof-Cieslak: On the background dotnet restore? We can do that.

**Comment by Krzysztof-Cieslak** [comment]
cc: @enricosada

**Comment by enricosada** [comment]
why? what's the scenario?

**Comment by forki** [comment]
we are generating a props file in paket:

![image](https://user-images.githubusercontent.com/57396/54740499-e8e80c80-4bbb-11e9-8aa4-dbfe810f7b53.png)

currently it only checks for VS

**Comment by enricosada** [comment]
yes, dotnet.proj.info doesnt use `DesignTimeBuild` yet.
i'll ping you in chat, let's see how fix it.

**Comment by Krzysztof-Cieslak** [comment]
The new version of Proj Info is setting `DesignTimeBuild` variable correctly for project parsing.
