### ISSUE TITLE
If we see MSBuild error then run dotnet restore and retry (once)

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#952]
@forki: if I build for raspi then afterwards ionide can't load project anymore because obj has wrong deps. Is it possible to let it just dotnet restore and retry? It would immediately fix my situation.

@Krzysztof-Cieslak: Yeah, I think we need to do that, someone suggested that earlier too. I just didn't have time to implement it.

**Comment by forki** [comment]
/cc @theimowski 

![image](https://user-images.githubusercontent.com/57396/47606895-d22cf780-da19-11e8-9824-cc98568f5495.png)

another case of this.

**Comment by theimowski** [comment]
Yup, this happened to me also when publishing for Windows while on Mac

**Comment by forki** [comment]
NETSDK1061 is another MSBuild error that is showing up here

**Comment by forki** [comment]
NETSDK1005 is another one.

**Comment by forki** [comment]
Thanks so much!

**Comment by theimowski** [comment]
Awesome! Need to check if this enhancement allows to do `dotnet watch` from a VM, maintaining proper editor support
