### ISSUE TITLE
PackageReferences in fsproj

### ISSUE THREAD

**Issue by psowinski** [ionide/ionide-vscode-fsharp#954]
VS2017 generated me fsproj with package reference in 'update' format

<PackageReference **Update**="FSharp.Core" Version="4.5.2" />

When I open the same project in vscode with ionide 
intellisense doesn't see references to other project in the same solution
Using 'Include' instead works fine.

<PackageReference **Include**="FSharp.Core" Version="4.5.2" />

**Comment by Krzysztof-Cieslak** [comment]
CC: @enricosada

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed with 5.0
