### ISSUE TITLE
Need a way to enable 64bit FSI cross platform by default for a given workspace

### ISSUE THREAD

**Issue by moloneymb** [ionide/ionide-vscode-fsharp#956]
The current fix for getting 64bit FSI working in windows involves setting FSharp.fsiFilePath to the full path of fsiAnyCpu.exe. 

I'd like to be able to add this setting into .vscode/settings.json and check it into the repository so that when someone else clones the git project they're able to run the scripts with the correct bitness.

By requiring the full path the same .vscode/settings.json becomes tied to Windows and will no longer work on Linux.

It would be nice if there was a flag to set 64bit in settings.json without needing a full path. E.g. a new parameter such as FSharp.is64bitFSI.

Alternatively if FSI could default to 64bit that too would be great.

**Comment by Krzysztof-Cieslak** [comment]
TBF, I thought that `fsiAnyCpu` is a default one...

@baronfel, was that included in your changes around detecting environmental stuff?

**Comment by dsyme** [comment]
> Alternatively if FSI could default to 64bit that too would be great.

Indeed I think it should be made the default now

**Comment by nhirschey** [comment]
This bug might have resurfaced? https://github.com/ionide/ionide-vscode-fsharp/issues/893

I had it default to 32bit again in the past month and had to reset it manually.
