### ISSUE TITLE
Option to disable touchbar integration

### ISSUE THREAD

**Issue by yuhr** [ionide/ionide-vscode-fsharp#957]
When coding, I want to use another extension which extends the touchbar, but in F# projects Ionide also extends the touchbar. These extensions seem to conflict.

I can't find any option to disable the touchbar integration of Ionide. Am I missing something?

**Comment by Krzysztof-Cieslak** [comment]
@vbfox, could this be done with the set context trick?

**Comment by vbfox** [comment]
Boolean settings can be directly referenced in `when` clauses so something like `"when": "config.fsharp.showTouchBarIcons"` along with the corresponding setting should work.

If anyone want to donate a Macbook with touchbar I can PR the change XD

**Comment by Krzysztof-Cieslak** [comment]
Fixed by bcdb3a00316358d9b1e646951581f3e7c2a5baf0
