### ISSUE TITLE
Opening a f# dot net core 1.0 project sometimes gives strange errors

### ISSUE THREAD

**Issue by bluemmc** [ionide/ionide-vscode-fsharp#96]
After a few seconds I sometimes get errors if I open a hello world f# dot net core 1.0 project. It does not happens always but often.

Steps to reproduce:
1) Install dotnet core 1.0
2) Create a f# project from command line with "dotnet new --lang f#"
3) Open in Visual Code with the Ionide plugin install
4) Say yes to installing required assets
5) Select file Program.fs
6) Wait a few seconds..

Then sometimes visual code will r.x. show the error "the type referenced though 'System.IO.TextWriter' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO'.

This error is not correct as the project will compile and run just fine.

**Comment by Krzysztof-Cieslak** [comment]
Run `dotnet build`, try to edit file, errors should disappear .

**Comment by bluemmc** [comment]
Just tried again - this time on a Mac rather then Windows. Same problem. Did both a "dotnet build" and a "dotnet run", changed files and restarted. Seemed to work for 10-20 seconds then it gave the same error again.

**Comment by angrydexterous** [comment]
Same problem
code: https://gist.github.com/angrydexterous/c5130e1fbb5c37b179f8133d90d0b397
Visual Studio Code : 1.3
Mono JIT compiler version 4.4.1 
Ubuntu 16.04

**Error**
The type referenced through 'System.Threading.Tasks.Task`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks'.at line 20 col 74

**Comment by Krzysztof-Cieslak** [comment]
Can reproduce errors, no idea what's wrong. It might actually be some FCS problem

**Comment by bluemmc** [comment]
Great that it can be reproduced. It is a blocker for me. Had to put usage of ionide on pause.

**Comment by OzieGamma** [comment]
Same here

**Comment by isamuelson** [comment]
Same here

**Comment by bellp** [comment]
Running into same issue :(

**Comment by Krzysztof-Cieslak** [comment]
It's probably https://github.com/fsharp/FSharp.Compiler.Service/issues/619

**Comment by alfonsogarciacaro** [comment]
Note that fsharp/FSharp.Compiler.Service#619 should be fixed by fsharp/FSharp.Compiler.Service#628 👏  (the PR isn't merged yet into FCS though)

**Comment by Krzysztof-Cieslak** [comment]
I think FCS version we're using should contain fix... And project.json is dead anyway.
