### ISSUE TITLE
Can't run .NET Core console app

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#965]
Steps:

1. Create an F# project from the command line via `dotnet new console --language F#`
1. Open it in VS Code, go to the F# tab, next to the project name click the "Run" symbol
1. Witness the following error message:

   ```
   The terminal process command '"C:\Program Files\dotnet\dotnet.exe" run -p 
   c:\Users\carlp\OneDrive\Desktop\RedditModTools\RedditModTools.fsproj' failed to launch (exit code: 2)
   ```
1. ... but cutting and pasting into `cmd.exe` and running this command works just fine

Ionide-fsharp 3.30.0
.NET Core SDK 2.1.500
F# 4.5
Tested on Visual Studio Code 1.28.2 and 1.29.1
Windows Insiders, version 10.0.17763

**Comment by inosik** [comment]
Works for me when I remove the extra quotes from here:

https://github.com/ionide/ionide-vscode-fsharp/blob/ff7b5ae6684b022d02b0f0056927dc71986936fc/src/Core/Project.fs#L526

**Comment by devblah** [comment]
Any updates on this?

**Comment by lilred** [comment]
@devblah PRs welcome :)))

**Comment by enricosada** [comment]
send PR https://github.com/ionide/ionide-vscode-fsharp/pull/1071

**Comment by enricosada** [comment]
Closing, fixed by https://github.com/ionide/ionide-vscode-fsharp/pull/1071

**Comment by OmanF** [comment]
Getting the exact same issue following the exact same reproducing steps.

Ionide-fsharp 3.35.0 (The latest currently. I update my plugins religiously).

**Comment by Krzysztof-Cieslak** [comment]
The fix has not been released yet
