### ISSUE TITLE
Using F# project explorer to edit project file (eg re-order files) removes some elements

### ISSUE THREAD

**Issue by richardjharding** [ionide/ionide-vscode-fsharp#967]
When I use the project explorer tools to edit the project eg
re-order files
add file
add project reference

When the .fsproj file is written out it has lost some of my other elements for example
before :
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateUserSecretsAttribute>false</GenerateUserSecretsAttribute>
    <UserSecretsId>****************************</UserSecretsId>
  </PropertyGroup> 
  <ItemGroup>
    <Compile Include="userSecrets.fs" />
    <Compile Include="userProfileDbTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

After using the explorer to re order Program.fs

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup> 
  <ItemGroup>
    <Compile Include="userSecrets.fs" />
    <Compile Include="Program.fs" />
    <Compile Include="userProfileDbTests.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

Note the 
```
<GenerateUserSecretsAttribute>false</GenerateUserSecretsAttribute>
    <UserSecretsId>****************************</UserSecretsId>
```

have been lost

.net sdk 2.1.403
ionide version 3.30.0
vs code 1.29.1

**Comment by danyx23** [comment]
I'm running into a variation of this problem - in my case we have a file that we copy using CopyToPublishDirectory="Always" and when we interact with ionide to add a file or similar this gets removed and then the config file is gone ...

Concretely, this section:
```
<None Include="appsettings.yml" CopyToPublishDirectory="Always" />
```
Gets turned into 
```
<None Include="appsettings.yml" />
```

**Comment by richardjharding** [comment]
can anyone point me at when in the solution the project file is parsed? - guessing that the elements in my case and the attributes in @danyx23 's case are not being parsed and so are not re-written out again?

**Comment by MangelMaxime** [comment]
@richardjharding Yes Ionide is using Forge to handle project modification.

I believe Forge should not modified line it doesn't understand but I am not sure if this is possible.

**Comment by richardjharding** [comment]
thanks I'll test with Forge directly and raise there if I can reproduce

**Comment by Krzysztof-Cieslak** [comment]
Yes, this is Forge problem, reported both in Forge repo and in other issue here. Closing as duplicate.
