### ISSUE TITLE
Rename doesn't work on double-ticked identifiers

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-fsharp#97]
e.g. 

``` fsharp
``Num Of Files    ``
```

![](http://i.imgur.com/0LDsaUY.png)

**Comment by Krzysztof-Cieslak** [comment]
I **think** it can be solved by using `languages.setLanguageConfiguration` and creating good RegEx for wordPattern in [LanguageConfiguration](https://code.visualstudio.com/docs/extensionAPI/vscode-api#LanguageConfiguration)

**Comment by vasily-kirichenko** [comment]
@Krzysztof-Cieslak where that `wordPattern` should be set? I've searched the codebase and have not found any place where LanguageConfiguration is set.

**Comment by Krzysztof-Cieslak** [comment]
In latest Code release they've added option to set wordPattern in `language-configuration.json` - https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/language-configuration.json

**Comment by MangelMaxime** [comment]
I tried to solve this issue but even if I got a regex matching the correct groups VSCode doesn't seems to work as expected.

If someone want to give it a try or confirm my bug [here is a gist](https://gist.github.com/MangelMaxime/7b76a694c9704fbc29de4bbb14e01197) with the regex and test strings.

**Comment by MangelMaxime** [comment]
For reference, I opened an issue on VSCode repo.

https://github.com/Microsoft/vscode/issues/32762

**Comment by Krzysztof-Cieslak** [comment]
Closing it here as an upstream VSCode issue. I hope it will be solved with new API in renameProvider (https://github.com/Microsoft/vscode/pull/37691)
