### ISSUE TITLE
Typing too quickly stop members showing in intellisense

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#970]
If you type too quickly, intellisense doesn't update and provide correct suggestions when you go "into" a module. You have to "cancel" the current intellisense pop-up and then call it again with e.g. `CTRL + SPACE` (and sometimes that doesn't work).

![intellisense](https://user-images.githubusercontent.com/1781813/49367647-fa7cd580-f6ec-11e8-9c07-b427e4de6b2a.gif)

This isn't a "show stopper" but it's quite annoying as it occurs very regularly and affects productivity and developer satisfaction.

**Comment by Krzysztof-Cieslak** [comment]
Solution: don't type so quickly

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed in Ionide 4.0 (or I don't type quickly enough)

**Comment by isaacabraham** [comment]
@Krzysztof-Cieslak this is back again in latest Ionide. Sometimes it's fine but if the typechecker isn't fast enough, intellisense simply doesn't catch up. This makes the user think that either their code is broken or that Ionide isn't working.
