### ISSUE TITLE
"do" gets replaced in for .. do loops

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#971]
If you type e.g. `for x in 1 .. 100 do` and are too slow, VS Code replaces "do" with "double". When you hit enter to go to the next line, instead you then end up with `for x in 1 .. 100 double`. This is obviously invalid and not expected behaviour, so you first have to realise what has happened, delete the characters etc. and then carry on. This isn't a show stopper but affects productivity and developer satisfaction.

![intellisense](https://user-images.githubusercontent.com/1781813/49367957-d077e300-f6ed-11e8-9e6a-67df982a5fdc.gif)

**Comment by Krzysztof-Cieslak** [comment]
Judging by the GIF you have `FSharp.keywordsAutocomplete` set to false.

**Comment by isaacabraham** [comment]
That fixes it (although I wonder if it's possible to turn off autocomplete when typing "number"?)
