### ISSUE TITLE
CD not working correctly in terminal...

### ISSUE THREAD

**Issue by janpop2017** [ionide/ionide-vscode-fsharp#972]
Testfiles attached:
[testfile.txt](https://github.com/ionide/ionide-vscode-fsharp/files/2658130/testfile.txt)
[d-drive-test.fsx.txt](https://github.com/ionide/ionide-vscode-fsharp/files/2658135/d-drive-test.fsx.txt)

I am using Ionide Fsharp 3.30.0 and Mono on Windows 10 Home Edition.
The problem exists on both fsharpc and fsharpi .

When my test script is located on the C: disk everything works perfectly using fsharpc, but not fsharpi
If I move my script to my D: disk, chdir do not work correctly 
Output from my test:
**********************
C:\Users\jrola>cd "c:\temp" && cls && "C:\Program Files\Mono\bi"
Fil efter fileReplace: 9i1.txt
Press any key to continue . . .
**********************
C:\Users\jrola>cd "d:\temp" && cls && "C:\Program Files\Mono\bi"
Fil efter fileReplace: 9i1.txt
System.IO.FileNotFoundException: Could not find file "C:\Users\jrola\9i1.txt"
*********************
Suggestion: use the command, D:  to change the actual drive, before using the chdir command, i.e.:
C:\Users\jrola>"D:" && cd "d:\temp" && cls && "C:\Program Files\Mono\bi"

**Comment by MangelMaxime** [comment]
I am not sure to see where it's related to Ionide?

I mean, from my point of view you are using the `Terminal` window from VSCode and Ionide isn't responsible of this feature.

Do you have the same problem if you use the Windows Cmd directly ?
