### ISSUE TITLE
Refactor for better command execution on different platforms

### ISSUE THREAD

**Issue by cynic** [ionide/ionide-vscode-fsharp#973]
There are a lot of issues (#939, #948, #956, #847, for example) that might be improved if we did somewhat better checks for paths, framework versions, executables, and so on.  I'd like to work on this and see if I can improve that situation.  That work might touch a bit of the core, especially `LanguageService.fs`.  So I'd like to raise it here first, and if anyone has objections or concerns, perhaps we could discuss it here?

Of course, I would try to keep to the existing style, and would try to break my commits up sensibly; and each PR is subject to the usual oversight.

**Comment by Krzysztof-Cieslak** [comment]
This is not as huge problem any more given that we removed possibility to choose runtime, and always depend on .NET SDK
