### ISSUE TITLE
Provide chocolatey command for "Visual Studio Build Tools not found" error

### ISSUE THREAD

**Issue by brianary** [ionide/ionide-vscode-fsharp#976]
I'm not sure which version or package parameters to feed to chocolatey to satisfy this requirement so that I don't have to manually install or manage it. I'm given a [download link](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15 "⤓ vs_buildtools__1324312950.1492201578.exe"), but I can't tell if that maps to `microsoft-build-tools`, `visualstudio2017buildtools`, `visualstudio2017-workload-vctools`, or something else, or if it requires a specific version number (see #449), package parameters (see [ChocolateyPackages #55](https://github.com/jberezanski/ChocolateyPackages/issues/55)), or specific [workload or component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017 "Visual Studio Build Tools 2017 component directory").

Thank you for your help!

**Comment by Krzysztof-Cieslak** [comment]
Visual Studio Build Tools are now not needed with new project parsing in Ionide 4.0
