### ISSUE TITLE
Provide auto-completion for custom operations in computation expressions

### ISSUE THREAD

**Issue by ronaldschlenker** [ionide/ionide-vscode-fsharp#981]
In FSX files, all custom operations defined on a builder are not listed in the autocomplete popup:

![image](https://user-images.githubusercontent.com/472222/50096694-9859bf80-0218-11e9-8216-d97a7ab124ba.png)

## Additional Info
VSCode Ionide Settings are:

```json
    "FSharp.saveOnSendLastSelection": true,
    "FSharp.lineLens.enabled": "replaceCodeLens",
    "FSharp.enableTreeView": false,
    "FSharp.msbuildAutoshow": true,
    "FSharp.showCodeOutlineIn": "explorer",
    "FSharp.showExplorerOnStartup": false,
```

**Comment by Krzysztof-Cieslak** [comment]
This has been fixed in the latest release.
