### ISSUE TITLE
Nothing happens except "Creating project..." in status bar

### ISSUE THREAD

**Issue by CyrexCore2k** [ionide/ionide-vscode-fsharp#989]
Issue Type: <b>Bug</b>

Creating a new F# project and I have selected the console app. I give a blank folder name and then a name for the project. Status bar says "Creating project..." but nothing happens.

Extension version: 3.30.0
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.72GB free)|
|Process Argv|-psn_0_10938990|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed with Forge improvements included in Ionide 4.0
