### ISSUE TITLE
Issues launching homebrew Mono on Mac OS X El Capitan

### ISSUE THREAD

**Issue by mariosangiorgio** [ionide/ionide-vscode-fsharp#99]
It looks to be the very same issue experienced by [OmniSharp](https://github.com/OmniSharp/omnisharp-atom/issues/42).
The only way I can get Ionide to work properly is to launch Visual Studio code from the terminal (which has `mono` in the path).

It's an issue related to Mono installed via Homebrew. The OmniSharp team solved it [in this way](https://github.com/OmniSharp/omnisharp-sublime/commit/9b9b85cff954550c85109b65733e067762bb0366).

To be honest it doesn't look too clean so I was wondering if there is another way to get everything to work as expected.

**Comment by Krzysztof-Cieslak** [comment]
Mono path can now be provide in settings using `FSharp.monoPath` option
