### ISSUE TITLE
Code lens not working with suggested FSharp.fsacRuntime:netcore setting

### ISSUE THREAD

**Issue by lfr** [ionide/ionide-vscode-fsharp#991]
Ionide-fsharp 3.3 / Windows 10 x64 / .Net Core 2.2.102

![image](https://user-images.githubusercontent.com/6348118/51313001-d121ca00-1a4c-11e9-8745-15725084d6b2.png)

If I switch to the default "net" it works as usual. Things I've tried to fix the problem after reading other similar issues:

- Installed MS Build Tools with F# support
- Updated VS Code
- Removed .foders from solution path
- Re-installed .Net SDK

**Comment by lferrao** [comment]
This seems to be related to solutions containing both F# and C#

**Comment by Krzysztof-Cieslak** [comment]
Try clearing cache (`F#: Clear Cache` command) or removing `obj` folders after changing to `netcore`

**Comment by lfr** [comment]
@Krzysztof-Cieslak thanks, this solutions seems to work so far although it appears I have to do it once per .fs file, but that's ok because eventually all files will be fixed and I guess I could just delete obj for the entire projects
