### ISSUE TITLE
Linter is going nuts on member calls

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#996]
Not really sure where to report this, but this should really be ok

![image](https://user-images.githubusercontent.com/57396/51821825-a0f2ea80-22da-11e9-906b-a27099c170e6.png)

**Comment by MangelMaxime** [comment]
Ionide received an update of FSharpLint and the new version seems to have a lot more rules included.

For example, if your file starts by a `module` it will add a warning asking you to use a `namespace` as top level.

I don't know if we can control a bit the linter settings by default or if the user has to add the `FSharpLint` configuration to their project.

PS: I do think you should add spaces after your comma 😉

**Comment by forki** [comment]
even worse: https://github.com/ionide/ionide-vscode-fsharp/issues/997

**Comment by MangelMaxime** [comment]
You can disable this rule by adding a `Settings.FSharpLint` at the root of your workspace.

The contents would be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<FSharpLintSettings>
    <!-- ... -->
    <Analysers>
        <Formatting>
            <Rules>
                <TupleCommaSpacing>
                    <Enabled>false</Enabled>
                </TupleCommaSpacing>
            </Rules>
        </Formatting>
    </Analysers>
    <!-- ... -->
</FSharpLintSettings>
```

**Comment by Krzysztof-Cieslak** [comment]
I'm closing it here as provided by @MangelMaxime is the correct solution here. If you think the warning is wrong then this can be discussed in https://github.com/fsprojects/FSharpLint repo.
