### ISSUE TITLE
Linter is going nuts on elmish

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#997]
![image](https://user-images.githubusercontent.com/57396/51826840-50828980-22e8-11e9-97ea-ed22facdc8d6.png)

**Comment by MangelMaxime** [comment]
You can disable this rule by adding a `Settings.FSharpLint` at the root of your workspace.

The contents would be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<FSharpLintSettings>
    <!-- ... -->
    <Analysers>
        <Formatting>
            <Rules>
                <TupleParentheses>
                    <Enabled>false</Enabled>
                </TupleParentheses>
            </Rules>
        </Formatting>
    </Analysers>
    <!-- ... -->
</FSharpLintSettings>
```

**Comment by Krzysztof-Cieslak** [comment]
I'm closing it here as provided by @MangelMaxime is the correct solution here. If you think the warning is wrong then this can be discussed in https://github.com/fsprojects/FSharpLint repo.

**Comment by forki** [comment]
Ok reported over there. But the thing is that this is so extremely invasive that everyone who uses SAFE-Stack / elmish is probably disabling the thing completely. Which is a bit sad. I personally think it would be good to downgrade the s
Fsharplint dependency in ionide for now.
