### ISSUE TITLE
Suggested fix for RulesFormattingF#ArrayPostfixError removes tuples 

### ISSUE THREAD

**Issue by aspnetde** [ionide/ionide-vscode-fsharp#998]
![image](https://user-images.githubusercontent.com/1322584/51849923-f8b44480-2320-11e9-9933-a66f83ef967e.png)

I think correct would be `(A * B) []` here.

### Machine infos

* Operating system: **Darwin**
* Arch: **x64**
* VSCode: **1.30.2**
* Runtime: **netcore**
* Dotnet version: **2.1.302**
* Runtime: **.Net**
* Ionide-fsharp: **3.31.0**

**Comment by Krzysztof-Cieslak** [comment]
Can you please open issue in https://github.com/fsprojects/FSharpLint repo?

**Comment by aspnetde** [comment]
FSharpLint is responsible for the actual code fix, that is being applied based on the suggestion? (I think the suggestion itself is okay.)

**Comment by Krzysztof-Cieslak** [comment]
Yes, code that is used for replacement in the code fix is also provided by FSharpLint

**Comment by aspnetde** [comment]
Thanks. Will do. Feel free to close this one.
